### ISSUE TITLE
Error in funannotate predict run

### ISSUE THREAD

**Issue by soumyarao86** [nextgenusfs/funannotate#1]
Hello,
I have a de novo genome assembly and RNA-seq data for a fungus. I installed and ran funannotate with clean, sort and species commands successfully. But I got the errors while running the following command:
```
$ funannotate predict -i fun_sort_scaffolds.fa -o fun_out1 --species my_species_augustus --rna_bam tophat2_PE/accepted_hits.bam --repeatmodeler_lib repeatmodeler-lib --min_protlen 20 --cpus 16 
```
```
[11:45:02 AM]: Operating system: linux2, 24 cores, ~ 132 GB RAM
[11:45:04 AM]: Soft-masking: running RepeatMasker with custom library
[11:45:05 AM]: Mapping proteins to genome using tBlastn/Exonerate
[11:45:05 AM]: Running pre-filter tBlastn step
[11:45:05 AM]: found 0 preliminary alignments
Traceback (most recent call last):
  File "/usr/local/funannotate/bin/funannotate-p2g.py", line 78, in <module>
    with open(genome, 'rU') as input:
IOError: [Errno 2] No such file or directory: '/home/fun_out1/predict_misc/genome.softmasked.fa'
[11:45:05 AM]: Now launching BRAKER to train GeneMark and Augustus
[11:45:05 AM]: GeneMark predictions failed, proceeding with just Augustus
[11:45:05 AM]: 0 total gene models from all sources
[11:45:05 AM]: 0 total gene models from EVM
[11:45:05 AM]: Predicting tRNAs
[11:45:05 AM]: Merging EVM output with tRNAscan output
[11:45:05 AM]: Reformatting GFF file using GAG
Traceback (most recent call last):
  File "/usr/local/funannotate/bin/funannotate-predict.py", line 461, in <module>
    total = lib.countGFFgenes(GAG_gff)
  File "/usr/local/funannotate/lib/library.py", line 188, in countGFFgenes
    with open(input, 'rU') as f:
IOError: [Errno 2] No such file or directory: 'gag1/genome.gff'
```

Please help me troubleshoot this error.
Thanks and regards,
Soumya

**Comment by nextgenusfs** [comment]
Hi Soumya,

It looks like RepeatMasker did not run correctly.  From your input command, it looks like you have passed in a file called `repeatmodeler-lib`, please make sure that file is not empty.  So if you already have a custom repeat database derived from a previous run of RepeatModeler, you can pass that multi-fasta file to the `--repeatmodeler_lib my_repeats.fasta`.  You also need to have the RepeatModeler libraries installed for genome soft-masking to work, they can be downloaded and installed from RepBase. 

And FYI, if using RNA-seq BAM files, the reads need to be mapped to the sorted scaffolds, i.e. `fun_sort_scaffolds.fa` and then the BAM file needs to be sorted, e.g. `samtools sort -o sorted.bam accepted_hits.bam`.

**Comment by soumyarao86** [comment]
Hi,
Thanks for pointing out the probable reasons. I ran repeatmodeler previously on a different server and used consensi.fa by renaming it to repeatmodeler_lib. But it seems this time there is some problem in installation and I get mpty consensi.fa file. I will try to figure it out. 
I also mapped RNA-seq reads again to fun_sort_scaffolds.fa as per your suggestion.
Anything else to be kept in mind?

**Comment by nextgenusfs** [comment]
I just released a new version (v0.1.4) which has some additional checks on input files to try to help you determine where the problem is.  If you installed funannotate with linuxbrew, you should be able to run `brew update` followed by `brew upgrade funannotate`.  Right now you have to move into the funannotate home directory and run the `./setup.sh` again to make sure that all the dependencies are installed and DB's are properly linked, e.g. `cd $homebrewpath/Cellar/funannotate/0.1.4/libexec`, and then run `./setup.sh`.  If you installed with git, then you just need to run `git pull` in the funannotate home directory.

But it seems like a problem with either configuration of RepeatMasker or not having installed the RepeatMasker RepBase libraries.  The simplest way might be to just have funannotate re-run repeatmodeler - it should only take an extra hour or so.  

I also updated the README to show what I would do with the RNA-seq data if that is helpful.

**Comment by nextgenusfs** [comment]
Just to follow up.  I pushed a new version `0.1.6` that fixed some issues that another user had with a centOS linux system - perhaps that bug was causing you problems here as well.  If you try the new version and things still aren't working, please let me know.

Jon

**Comment by soumyarao86** [comment]
Hi Jon,
1) I checked all the dependencies and ran funannotate predict with sample data successfully.

lgpa@lgpa:~/Documents/soumya/analysis/funannotate/funannotate_sample_genome1$ funannotat                                                          e predict -i /home/lgpa/Downloads/funannotate/sample_data/genome1.fasta -o genome1 -s "g                                                          enome one" --isolate fun1 --name GN01_ --augustus_species botrytis_cinerea --protein_e                                                          vidence /home/lgpa/Downloads/funannotate/sample_data/proteins.fa --transcript_evidence /                                                          home/lgpa/Downloads/funannotate/sample_data/transcripts.fa --cpus 20

I thought all the output files would be located in the output directory specified (genome1) but I found that some of the output (gag1 and 2, Genemark, genome1, Repeatmasker, RepeatModeler etc.) was in the working directory (funannotate_sample_genome1). Also at the end, I got  a message:

Traceback (most recent call last):
  File "/home/lgpa/Downloads/funannotate/bin/funannotate-predict.py", line 565, in <module>
    lib.ParseErrorReport(DirtyGFF, ErrSum, Val, discrep, NCBIcleanGFF)
  File "/home/lgpa/Downloads/funannotate/lib/library.py", line 801, in ParseErrorReport
    with open(Errsummary) as summary:
IOError: [Errno 2] No such file or directory: 'gag2/errorsummary.val'

Is that normal? Is this what is expected? log file is attached here.

2) I tried the next step annotate but it failed with the following message:
lgpa@lgpa:~/Documents/soumya/analysis/funannotate$ funannotate annotate -i funannotate_s                                          ample_genome1/genome1/ -e soumyarao86@gmail.com --cpus 20
-------------------------------------------------------
[01:06:20 AM]: Operating system: linux2, 24 cores, ~ 132 GB RAM
[01:06:20 AM]: Running funannotate v.0.1.6
[01:06:21 AM]: No NCBI SBT file given, will use default, however if you plan to submit t                                                          o NCBI, create one and pass it here '--sbt'
Traceback (most recent call last):
  File "/home/lgpa/Downloads/funannotate/bin/funannotate-functional.py", line 147, in <m                                                          odule>
    if not genbank or not GFF:
NameError: name 'genbank' is not defined


[my_funannotate_predict_genome1_log.pdf](https://github.com/nextgenusfs/funannotate/files/239024/my_funannotate_predict_genome1_log.pdf)

**Comment by nextgenusfs** [comment]
There seems to be an error in the prediction step and it did not finish completely.  What version of `tbl2asn` do you have?  It might be outdated and needs to be updated, I’m running tbl2asn v 24.9.  tbl2asn installed via apt-get is too old.

The second step `funannotate annotate` will not run if the first did not finish correctly.

**Comment by soumyarao86** [comment]
tblastn is from package blast 2.2.28+
I observed that genome1 directory had an empty directory predict_results but other directory predict_misc had  the followig files:
augustus.evm.gff3, evm.trnascan.gff, genome, gmap-map.log, repeat.gene.models.txt,   trnascan.gff3, augustus.gff3, exonerate.out, genome.fasta, gmhmm.mod,               repeatmasker.gff3, tRNAscan.out, bad_models.gff, genemark.evm.gff3, genome.repeats.to.remove.gff, predictions.gff3, repeats.xml, weights.evm.txt
cleaned.gff3, genemark.gff, genome.softmasked.fa, protein_alignments.gff3  transcript_alignments.gff3
evm.round1.gff3, genemark.temp.gff  gmap-build.log, proteins.combined.fa     transcripts.combined.fa

And logfiles directory with funannotate-EVM.log,  funannotate-p2g.log, funannotate-predict.log and funannotate-repeats.log.

**Comment by nextgenusfs** [comment]
`tbl2asn` is a program from ncbi that converts to genbank flat file.  http://www.ncbi.nlm.nih.gov/genbank/tbl2asn2/

I suspect that you have an old version installed and it needs to be upgraded.  The program did not complete and appears to have gotten hung up when converting to genbank with `tbl2asn`.

Typing `tbl2asn` should give you an interactive shell and display the version of the program you have installed.

**Comment by soumyarao86** [comment]
I upgraded tbl2asn.
both predict and annotate ran properly without any error, creating the directories predict_results, predict_misc, logfiles and annotate_results, annotate_misc, respectively.in genome1.

Thank you for your prompt support.
