### ISSUE TITLE
rmOutToGFF3.pl

### ISSUE THREAD

**Issue by krostifangers** [nextgenusfs/funannotate#10]
Hi
Just an issue due to a typo in the linux installation page

```
ln -s $HOME/.linuxbrew/opt/repeatmaskerlibexec/util/rmOutToGFF3.pl $HOME/.linuxbrew/bin
```
       ****should be replaced by****
```
ln -s $HOME/.linuxbrew/opt/repeatmasker/libexec/util/rmOutToGFF3.pl $HOME/.linuxbrew/bin
```
with the "/" between repeatmasker and libexec

Otherwise, the installation worked fine for me
Bye
krostif

**Comment by nextgenusfs** [comment]
Great, thanks.  I will fix.

**Comment by krostifangers** [comment]
Hi Jon
I am pretty new in gene prediction and functional annotation. I am 
trying to use funannotate pipeline to make prediction on my fungus. What 
command-line do you advice to run prediction when there is no 
pre-trained Augustus data?
Thank you in advance
christophe

**Comment by nextgenusfs** [comment]
By default funannotate tries to automatically determine the "best" way to train Augustus, it will default to BUSCO mediated training if there is no other options.  The best way to train would be to use the BRAKER1 mediated option that requires RNA-seq data (you pass a coord-sorted BAM file derived from RNA-seq data to the `--rna_bam`).  The second best option is PASA gene models, if you don't pass `rna_bam` and pass PASA results to `--pasa_gff`, funannotate use the PASA models to train Augustus, if you have neither of those options, funannotate will default to training Augustus using BUSCO.  If you have RNA-seq data, the README contains a workflow using some external tools; Trinity, PASA, etc.

Keep in mind that the predictions are evidence based, so you should give funannotate some `--transcript_evidence`, which could be transcripts from a closely related organism, ESTs from closely related organism, etc.  By default, funannotate uses the UniProtKB protein data base for `--protein_evidence`, you could alternatively pass other high quality protein models here as well.  Both the `--transcript_evidence` and `--protein_evidence` options allow for multiple input files separated by a comma with no space, e.g. `--protein_evidence /usr/local/share/funannotate/uniprot_sprot.fasta,my_awesome_proteins.fa,third_file.fasta`.
