### ISSUE TITLE
brew install funannotate issue

### ISSUE THREAD

**Issue by nancydongxyz** [nextgenusfs/funannotate#100]
Hello,

I am trying to install funannotate on an OS7 node on a cluster, where I don't have root access. Everything is fine until the "brew install funannotate" step. I have tried to re-install gcc using brew and ran brew update twice, but the problem persists.

[node43 ~]$ brew install funannotate
==> Installing funannotate from nextgenusfs/tap
==> Installing dependencies for nextgenusfs/tap/funannotate: pkg-config, ncurses, readline, sqlite, gdbm, openssl, berkeley-db@4, python, curl, cmake, libedit, mysql, jpeg, pcre, blast, htslib, samtools, gmap-gsnap, blat, kent-tools, tcsh, mummer, hmmer, m4, autoconf, automake, libtool, libxml2, gettext, libffi, util-linux, glib, exonerate, repeatscout, rmblast, trf, repeatmasker, recon, repeatmodeler, trnascan, bedtools, tbl2asn, raxml, trimal, mafft, braker, evidencemodeler, gag, proteinortho, paml, diamond
==> Installing nextgenusfs/tap/funannotate dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Already downloaded: /home/zhanglab1/ndong/.cache/Homebrew/pkg-config-0.29.2.tar.gz
==> ./configure --prefix=/home/zhanglab1/ndong/.linuxbrew/Cellar/pkg-config/0.29.2 --disable-host-tool --with-internal-g
        ==> make
Last 15 lines from /home/zhanglab1/ndong/.cache/Homebrew/Logs/pkg-config/02.make:
See <https://github.com/Homebrew/homebrew/issues> for instructions.
make[6]: *** [libglib_2_0_la-grand.lo] Error 1
make[6]: *** Waiting for unfinished jobs....
make[6]: Leaving directory `/tmp/pkg-config-20170813-2014-1d4z2bs/pkg-config-0.29.2/glib/glib'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/tmp/pkg-config-20170813-2014-1d4z2bs/pkg-config-0.29.2/glib/glib'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/tmp/pkg-config-20170813-2014-1d4z2bs/pkg-config-0.29.2/glib/glib'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/tmp/pkg-config-20170813-2014-1d4z2bs/pkg-config-0.29.2/glib'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/pkg-config-20170813-2014-1d4z2bs/pkg-config-0.29.2/glib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/pkg-config-20170813-2014-1d4z2bs/pkg-config-0.29.2'
make: *** [all] Error 2

Please let me know what could be the issue! Thank you very much!

Nancy

**Comment by nextgenusfs** [comment]
Installation on centOS with linuxbrew requires a few more dependencies I think, check [here](http://linuxbrew.sh). Seems like they recommend these prior to linuxbrew install:
```
sudo yum groupinstall 'Development Tools' && sudo yum install curl file git irb python-setuptools ruby
```
Given the above command requires sudo, I'm not sure that is a solution for you however.

There was a lot of trial and error in this thread https://github.com/nextgenusfs/funannotate/issues/24

You can always install the dependencies manually and then git clone the funannotate repository.  I know some users on clusters have opted for a more manual installation as LinuxBrew isn't an option.  There are a lot of dependencies, the setup script can help you determine which ones are not installed. You could git clone the repository and then run `funannotate setup -m dep` to check for dependencies. 

LinuxBrew is suppose to make it easier to install and bypass need for sudo, for some users/linux distributions that seems to be the case, not so much for others.

**Comment by nancydongxyz** [comment]
Okay, I will try that. Thank you very much!
