### ISSUE TITLE
"from Bio.SeqUtils import GC" fails as of Biopython 1.82

### ISSUE THREAD

**Issue by peterjc** [nextgenusfs/funannotate#1000]
Your code https://github.com/nextgenusfs/funannotate/blob/master/funannotate/library.py has two uses of ``from Bio.SeqUtils import GC`` which is a function deprecated in Biopython 1.80 and removed in Biopython 1.82.

Quoting https://github.com/biopython/biopython/blob/biopython-183/DEPRECATED.rst#biosequtils

> Function 'GC' in Bio.SeqUtils was deprecated in Release 1.80, and removed in Release 1.82. Instead use function 'gc_fraction'.

Note ``gc_fraction`` returns a float between 0 and 1. This was introduced in Biopython 1.80.

Possible suggested code:

```python
try:
    from Bio.SeqUtils import gc_fraction
    def GC(sequence):
        return 100 * gc_fraction(sequence, ambiguous="ignore")
except ImportError:
    # Older versions have this:
    from Bio.SeqUtils import GC
```

Cross reference https://github.com/biopython/biopython/issues/4622

**Comment by caonetto** [comment]
Yep, getting the same error.

**Comment by nextgenusfs** [comment]
> Your code https://github.com/nextgenusfs/funannotate/blob/master/funannotate/library.py has two uses of `from Bio.SeqUtils import GC` which is a function deprecated in Biopython 1.80 and removed in Biopython 1.82.
> 
> Quoting https://github.com/biopython/biopython/blob/biopython-183/DEPRECATED.rst#biosequtils
> 
> > Function 'GC' in Bio.SeqUtils was deprecated in Release 1.80, and removed in Release 1.82. Instead use function 'gc_fraction'.
> 
> Note `gc_fraction` returns a float between 0 and 1. This was introduced in Biopython 1.80.
> 
> Possible suggested code:
> 
> ```python
> try:
>     from Bio.SeqUtils import gc_fraction
>     def GC(sequence):
>         return 100 * gc_fraction(sequence, ambiguous="ignore")
> except ImportError:
>     # Older versions have this:
>     from Bio.SeqUtils import GC
> ```
> 
> Cross reference [biopython/biopython#4622](https://github.com/biopython/biopython/issues/4622)

Thanks @peterjc

**Comment by nextgenusfs** [comment]
Would someone be able to test the latest to see if this is resolved? If so I can tag a new release. Thanks.

**Comment by sarjopp** [comment]
I can try later today.

**Comment by sarjopp** [comment]
Looking at this now and I need some guidance. I'm an end user and I don't know where to insert the edited bit.

**Comment by nextgenusfs** [comment]
Oh sorry, I just meant install the latest code and see if problem is fixed. The other way to fix it is to downgrade biopython to <1.80. 

Can install the latest from GitHub like this, (assuming you are in the funannotate environment)


python -m pip install git+https://github.com/nextgenusfs/funannotate.git

**Comment by sarjopp** [comment]
I did the downgrade biopython option previously, that worked fine. I will
try latest funanno with biopython 1.83 today.

**Comment by sarjopp** [comment]
sorry, I meant I will try funannotate.v1.8.16 exactly as it comes, which I see is with an earlier version of biopython. It's running now.

**Comment by sarjopp** [comment]
Hello, everything worked great! funannotate v.1.8.16, no modifications.
