### ISSUE TITLE
Error with GAG

### ISSUE THREAD

**Issue by rajewski** [nextgenusfs/funannotate#101]
I'm having some trouble getting funannotate annotate to compile all of the annotations. I'm attaching  my script to run the program as well as the log files that were generated by the failed run.

This time I passed a genome fasta file, a GFF, and a protein fasta file, and I find that the genome.* files are not produced in the annotate_misc folder; however, when I ran this pipeline on another organism and passed in a funannotate predict output folder, the process worked fine.

[Archive.zip](https://github.com/nextgenusfs/funannotate/files/1236072/Archive.zip)

**Comment by nextgenusfs** [comment]
It seems like GAG doesn't like your GFF file - what is the source of the GFF file, is it from funannotate predict?

**Comment by rajewski** [comment]
No, the GFF isn't from funnotate predict. The one I used was exported from Geneious and has couple of manual annotations that weren't in the published genome. I'll try to run this again with the original GFF (sans the manually added genes).

**Comment by nextgenusfs** [comment]
So it is then likely a GFF formatting problem, you can try to run directly through GAG which will give you perhaps a bit more info on why it is failing.  Other GFF formatting tools (perhaps genome tools) can sometimes fix these errors, but it is one of the reasons that I don't use GFFs as the main input/output in funannotate, there are too many variations and the format is not standardized enough and all of the interesting information is located in a single column....

**Comment by rajewski** [comment]
I was able to rerun funannotate annotate with the original GFF file. GAG was able to complete, but the .tbl output simply annotated every protein as a "hypothetical protein" with no lines for database cross references. In the all.annotations.txt file however the annotations were complete and had information from multiple sources. The discrepancy.report.txt is enormous, so I'm attaching the first 50 lines here. Any ideas what's causing the information to get lost between the all.annotations.txt file and the .tbl file?
[Archive.zip](https://github.com/nextgenusfs/funannotate/files/1254085/Archive.zip)

**Comment by nextgenusfs** [comment]
Can you send the .tbl file in the `annotate_results` folder?  I can't tell from these files if it is working as it should be or not.  Right now hypothetical protein is the product description for every gene model due to the problems in NCBI submission, the info gets put into the note field as well as others. I'm working on a curated database to improve this, but it is not quite functional yet.  If you upgrade to newest version, there is a method that will incorporate eggnog-mapper results, where you will get more information for some genes in the annotation.

**Comment by rajewski** [comment]
Here is the .tbl file attached.
[Nobt.tbl.zip](https://github.com/nextgenusfs/funannotate/files/1254536/Nobt.tbl.zip)

**Comment by nextgenusfs** [comment]
So the looks like the gene/protein IDs are not from funannotate, which might be okay, but they need to match the ones in the GFF.  What is the output of these two commands, do the ID's match?  Maybe just post a few lines from each, should be straightforward to see if ID's match.
```
#get fasta headers from proteins
grep '^>' NIOBT_r1.0.masked.aa | head
```
```
#get mRNA IDs from GFF
grep $'\tmRNA\t' NIOBT_r1.0.gff | cut -f9 | head
```
For example, here is what should look like from funanntoate:
```
 grep '^>' Genome_two.proteins.fa | head 
>GN2_000001
>GN2_000002
>GN2_000003
>GN2_000004
>GN2_000005
>GN2_000006
>GN2_000007
>GN2_000008
>GN2_000009
>GN2_000010
```
```
grep $'\tmRNA\t' Genome_two.gff3 | cut -f9 | head
ID=GN2_000026-T1;Parent=GN2_000026;note=EggNog:ENOG410PMNM,COG:Q,TransMembrane:5 (o12-33i45-66o86-107i182-200o220-240i)
ID=GN2_000027-T1;Parent=GN2_000027;note=EggNog:ENOG410PHFK,COG:T,TransMembrane:1 (o12-31i);db_xref=InterPro:IPR001128,InterPro:IPR002401,InterPro:IPR002347,InterPro:IPR016040,PFAM:PF00067;go_process=oxidation-reduction process|0055114||IEA;go_function=heme binding|0020037||IEA,oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen|0016705||IEA,iron ion binding|0005506||IEA
ID=GN2_000084-T1;Parent=GN2_000084;note=EggNog:ENOG410PK1E,COG:S;db_xref=InterPro:IPR001932;go_function=catalytic activity|0003824||IEA
ID=GN2_000085-T1;Parent=GN2_000085;note=EggNog:ENOG410PH0F,COG:S;db_xref=InterPro:IPR029060,InterPro:IPR006984;go_component=small-subunit processome|0032040||IEA
ID=GN2_000086-T1;Parent=GN2_000086;note=BUSCO:EOG0926146A,EggNog:ENOG410PNTH,COG:T,TransMembrane:3 (i596-621o641-663i750-769o);db_xref=InterPro:IPR007941,InterPro:IPR029058,PFAM:PF05277
ID=GN2_000087-T1;Parent=GN2_000087;note=EggNog:ENOG410PFRH,COG:G,hydrolase family 76 protein;db_xref=InterPro:IPR000719,InterPro:IPR011009;product=Dcw1p;go_process=protein phosphorylation|0006468||IEA;go_function=protein kinase activity|0004672||IEA,ATP binding|0005524||IEA
ID=GN2_000080-T1;Parent=GN2_000080;note=EggNog:ENOG410PSZP,COG:S
ID=GN2_000081-T1;Parent=GN2_000081;note=EggNog:ENOG410PFMC,COG:S,SECRETED:SignalP(1-19);db_xref=InterPro:IPR009009
ID=GN2_000082-T1;Parent=GN2_000082;note=EggNog:ENOG410PG3N,COG:S,SECRETED:SignalP(1-18);db_xref=InterPro:IPR023346
ID=GN2_000083-T1;Parent=GN2_000083;note=EggNog:ENOG410PHX6,COG:T;db_xref=InterPro:IPR001849,InterPro:IPR011993
```
Newer versions of funannotate output Gene ID's in the protein fasta file, I think older versions output the mRNA ID (have -T1 suffix).

**Comment by rajewski** [comment]
Here is the output from 
`grep '^>' NIOBT_r1.0.masked.aa | head`

`>NIOBTv3_g00002-D2
>NIOBTv3_g00003
>NIOBTv3_g00005
>NIOBTv3_g00008
>NIOBTv3_g00009
>NIOBTv3_g00012
>NIOBTv3_g00013
>NIOBTv3_g00014
>NIOBTv3_g00015
>NIOBTv3_g00017`

And the output from
`grep $'\tmRNA\t' NIOBT_r1.0.gff | cut -f9 | head`

`ID=NIOBTv3_g00002-D2.t1;Parent=NIOBTv3_g00002-D2;Name=NIOBTv3_g00002-D2.t1
ID=NIOBTv3_g00003.t1;Parent=NIOBTv3_g00003;Name=NIOBTv3_g00003.t1
ID=NIOBTv3_g00005.t1;Parent=NIOBTv3_g00005;Name=NIOBTv3_g00005.t1
ID=NIOBTv3_g00008.t1;Parent=NIOBTv3_g00008;Name=NIOBTv3_g00008.t1
ID=NIOBTv3_g00009.t1;Parent=NIOBTv3_g00009;Name=NIOBTv3_g00009.t1
ID=NIOBTv3_g00012.t1;Parent=NIOBTv3_g00012;Name=NIOBTv3_g00012.t1
ID=NIOBTv3_g00013.t1;Parent=NIOBTv3_g00013;Name=NIOBTv3_g00013.t1
ID=NIOBTv3_g00014.t1;Parent=NIOBTv3_g00014;Name=NIOBTv3_g00014.t1
ID=NIOBTv3_g00015.t1;Parent=NIOBTv3_g00015;Name=NIOBTv3_g00015.t1
ID=NIOBTv3_g00017.t1;Parent=NIOBTv3_g00017;Name=NIOBTv3_g00017.t1`

Do you mean that the .t1 suffix on the genes from the .gff file is throwing it off?

**Comment by nextgenusfs** [comment]
Yes I think so, do a find/replace on that suffix and see if that works, i.e.
```
sed 's/.ti/-T1/g' NIOBT_r1.0.gff > NIOBT_r1.0.new.gff
```
I'll look into seeing if I can make the code a little more dynamic in regards to the naming.  It's just hard with GFF files to be consistent because there are so many variations.

**Comment by rajewski** [comment]
Great. That seems to have solved it. Thanks for helping me with this.

**Comment by nextgenusfs** [comment]
GAG has been removed from pipeline in v1.0.0 and greater, if this is still an issue feel free to reopen.

**Comment by RAJESHKMAURYA** [comment]
sed 's/.ti/-T1/g' NIOBT_r1.0.gff > NIOBT_r1.0.new.gff
I do not have this problem. but still gag shown problem.
