### ISSUE TITLE
GFF FORMAT

### ISSUE THREAD

**Issue by Panda-smile** [nextgenusfs/funannotate#1014]
**Are you using the latest release?**
1.8.17

**Describe the bug**
Hello professors！ When I submit the predict resluts to antimash online website， using the gff file format-Millerozyma_farinosa_FQ2MINIMF.gff3, it prompts that not match the target sequence file fa-Millerozyma_farinosa_FQ2MINIMF.cds-transcripts.fa.

![image](https://github.com/nextgenusfs/funannotate/assets/143200215/eb69b71c-2aa7-457b-8030-d8aeb9d58c0b)
![image](https://github.com/nextgenusfs/funannotate/assets/143200215/15d3c885-306d-4984-93c9-10f0b36c68a2)
<img width="968" alt="image" src="https://github.com/nextgenusfs/funannotate/assets/143200215/8edcfa18-fcb3-4e39-91d6-e556794c49f4">

**Comment by nextgenusfs** [comment]
Submit the genbank file.

**Comment by Panda-smile** [comment]
> Submit the genbank file.

profeesors , which one？ is  mean Millerozyma_farinosa_FQ2MINIMF.gbk? or  others，I'm not sure, because the website does not provide files in genemark format, but in gff format.

![image](https://github.com/nextgenusfs/funannotate/assets/143200215/e637096d-fe82-4711-a8e7-ee9f86e2569f)
![image](https://github.com/nextgenusfs/funannotate/assets/143200215/f1aa40c9-66bb-41d8-beaf-347000318386)

**Comment by nextgenusfs** [comment]
genbank format end with .gb, .gbk, or .gbff -- contains both sequence and annotation.
