### ISSUE TITLE
iprscan.xml related erro 

### ISSUE THREAD

**Issue by Panda-smile** [nextgenusfs/funannotate#1015]
**Are you using the latest release?**
1.8.17

**Describe the bug**
Content does not exist in xml file，The xml file has been submitted and modified to txt suffix
[iprscan.txt](https://github.com/nextgenusfs/funannotate/files/14680371/iprscan.txt)

**What command did you issue?**
Singularity> funannotate iprscan -i /data/FQ2mix_MF_alive -c 32
usage: funannotate-iprscan.py [-h] -i INPUT [-n NUM] [-c CPUS] -m {local,docker} [--cpus_per_chunk CPUS_PER_CHUNK]
                              [--iprscan_path IPRSCAN_PATH] [-o OUT] [--debug] [--no-progress]
funannotate-iprscan.py: error: the following arguments are required: -m/--method
Singularity> funannotate iprscan -i /data/FQ2mix_MF_alive -c 32 -m local
Running InterProScan5 on 11021 proteins
Important: you need to manually configure your interproscan.properties file for embedded workers.
Will try to launch 32 interproscan processes, adjust -c,--cpus for your system
     Progress: 11 complete, 0 failed, 0 remaining        
InterProScan5 search has completed successfully!
Results are here: /data/FQ2mix_MF_alive/annotate_misc/iprscan.xml

**Logfiles**
Run InterProScan (manual install): 
funannotate iprscan -i /data/FQ2mix_MF_alive -c 32

Run antiSMASH (optional): 
funannotate remote -i /data/FQ2mix_MF_alive -m antismash -e youremail@server.edu

Annotate Genome: 
funannotate annotate -i /data/FQ2mix_MF_alive --cpus 32 --sbt yourSBTfile.txt
-------------------------------------------------------
                
[03/20/24 23:33:29]: Training parameters file saved: /data/FQ2mix_MF_alive/predict_results/millerozyma_farinosa_fq2minimf.parameters.json
[03/20/24 23:33:29]: Add species parameters to database:

  funannotate species -s millerozyma_farinosa_fq2minimf -a /data/FQ2mix_MF_alive/predict_results/millerozyma_farinosa_fq2minimf.parameters.json

**OS/Install Information**
 -  output of `funannotate check --show-versions`
Singularity> funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.17
-------------------------------------------------------
You are running Python v 3.8.12. Now checking python packages...
biopython: 1.76
goatools: 1.3.11
matplotlib: 3.7.3
natsort: 8.4.0
numpy: 1.22.4
pandas: 2.0.3
psutil: 5.7.0
requests: 2.31.0
scikit-learn: 0.24.2
scipy: 1.5.3
seaborn: 0.13.0
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.302
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.31
local::lib: 2.000024
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config
$GENEMARK_PATH=/opt/gmes_linux_64_4
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.2
bamtools: bamtools 2.5.2
bedtools: bedtools v2.31.1
blat: BLAT v35
diamond: 2.1.8
emapper.py: 2.1.12
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.4 (Aug 2023)
hmmsearch: HMMER 3.4 (Aug 2023)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.520 (2023/Mar/22)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.26-r1175
pigz: 2.8
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.12
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 49
tbl2asn: 25.8
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed

**Comment by nextgenusfs** [comment]
Highly unlikely this is going to work in a container. interproscan is a very large tool/database and is not included in the docker image. You would need to have this installed on the same system, again no idea if this will work with container/singulatiry. t

**Comment by Panda-smile** [comment]
Professoers， the “inpscan” database have been installed correctly。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nextgenusfs/funannotate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月21日(星期四) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nextgenusfs/funannotate] iprscan.xml related erro  (Issue #1015)





 
Highly unlikely this is going to work in a container. interproscan is a very large tool/database and is not included in the docker image. You would need to have this installed on the same system, again no idea if this will work with container/singulatiry. t
