### ISSUE TITLE
Iprscan and annotate do not recognize predicted output folder

### ISSUE THREAD

**Issue by Okompath** [nextgenusfs/funannotate#1049]
**Are you using the latest release?**
I am running funannotate 1.8.17

**Describe the bug**
iprscan and annotate do not seem to recognize the predicted folder in the same directory (renamed to FUN). Nothing was edited besides the folder name after running funannotate predict on my data. I am running through an apptainer image as I am unable to create a local installation or an installation on my cluster.

**What command did you issue?**
apptainer run funannotate iprscan -i FUN -m docker --cpus 12

apptainer run funannotate_latest.sif funannotate annotate -i FUN \
   --cpus 12 

**Logfiles**
[Jun 14 11:01 AM]: OS: Debian GNU/Linux 10, 72 cores, ~ 791 GB RAM. Python: 3.8.12
[Jun 14 11:01 AM]: Running 1.8.17
[Jun 14 11:01 AM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Jun 14 11:01 AM]: Properly formatted 'funannotate predict' files do no exist in this directory

**OS/Install Information**

You are running Python v 3.8.12. Now checking python packages...
biopython: 1.79
goatools: 1.3.11
matplotlib: 3.7.3
natsort: 8.4.0
numpy: 1.22.4
pandas: 2.0.3
psutil: 5.9.8
requests: 2.31.0
scikit-learn: 0.24.2
scipy: 1.5.3
seaborn: 0.13.0
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
local::lib: 2.000024
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

**Comment by Truongphikt** [comment]
@Okompath, Hi. I have the same issue as you. Could you share how you solved this? Thanks.
