### ISSUE TITLE
funannotate-remote.py error: ImportError: No module named requests

### ISSUE THREAD

**Issue by Jennie17** [nextgenusfs/funannotate#105]
Hi Nextgenusfs,

Many thanks for your help. Funannotate is an amazing tool.

"funannotate annotate" can work now, but I got error msg for "funannotate remote".

The error msg:
Traceback (most recent call last):
  File "/scratch/RDS-FSC-WLR53-RW/funannotate/bin/funannotate-remote.py", line 4, in <module>
    import sys, os, subprocess, inspect, shutil, argparse, time, glob, requests, zipfile, urllib2
**ImportError: No module named requests**

My command:
/scratch/WLR53/funannotate/funannotate remote -i genome1d --cpus 6

Can you advise what may cause this error? Is any required package missing?

Could you please advise which package/module I shall install?

Looking forward to your reply

Best wishes!

**Comment by nextgenusfs** [comment]
Sorry for the delay, I need to update docs, but you need the `requests` python module. Should be able to install with pip, i.e. `pip install --user requests`.  FYI, some HPC clusters do not allow HTTP requests from their servers for security reasons.
