### ISSUE TITLE
snap-training generation assumes input genome FASTA is sorted

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#1060]
SNAP training is failing when I start with a genome from NCBI where the genome accessions are not necessarily sorted. So the writing of the scaffolds are not in the same order as the training .zff file.

**Comment by nextgenusfs** [comment]
I think this is fixed in f2 train as we make fake contig headers?

**Comment by hyphaltip** [comment]
for sure, but it was breaking a big run I was doing in f1 so its fixed now. glad the contig names are fixed in f2. will close as its fixed and we can bugfix a f1 release at some point.
