### ISSUE TITLE
Parsing EggNOG Annotations: TypeError - list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by kalonji08** [nextgenusfs/funannotate#1068]
**Are you using the latest release?**  
I am using Funannotate version 1.8.13, which is the latest on mamba

**Describe the bug**  
I encountered a bug while running the `funannotate annotate` command with `eggNOG-mapper` annotations. The error occurs during the parsing of the `eggNOG` annotations. The traceback indicates that a `NoneType` was encountered when trying to access the "Description" field in the annotations file. It seems the script is not properly handling the "Description" field, leading to this error:
```
TypeError: list indices must be integers or slices, not NoneType
```

**What command did you issue?**  
The following command was used:
```bash
funannotate annotate -i schizo_euRep_masked-Pred/ --eggnog schizophyllum_commune.emapper.annotations --antismash S_com_antiSMASH.gbk --signalp output.gff3 --cpus 25
```

**Logfiles**  
Here is the relevant section of the log file:
```
[Sep 17 09:12 PM]: Annotation consists of: 12,873 gene models
[Sep 17 09:12 PM]: 12,584 protein records loaded
[Sep 17 09:12 PM]: Running HMMer search of PFAM version 35.0
[Sep 17 09:14 PM]: 14,351 annotations added
[Sep 17 09:14 PM]: Running Diamond blastp search of UniProt DB version 2022_03
[Sep 17 09:15 PM]: 975 valid gene/product annotations from 1,394 total
[Sep 17 09:15 PM]: Existing Eggnog-mapper results found: schizo_euRep_masked-Pred/annotate_misc/eggnog.emapper.annotations
[Sep 17 09:15 PM]: Parsing EggNog Annotations
[Sep 17 09:15 PM]: EggNog version parsed as 2.1.12
Traceback (most recent call last):
  File "/home/kalonjilab/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/kalonjilab/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/kalonjilab/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 828, in main
    EggNog = parseEggNoggMapper(eggnog_result, eggnog_out, GeneProducts)
  File "/home/kalonjilab/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 250, in parseEggNoggMapper
    Description = cols[Desci].split('. ')[0]
TypeError: list indices must be integers or slices, not NoneType
```

**OS/Install Information**  
- OS: Ubuntu 20.04
- Funannotate version: 1.8.13
- Python version: 3.8.12
- Output of `funannotate check --show-versions`:
```
-------------------------------------------------------
Checking dependencies for funannotate v1.8.13
-------------------------------------------------------
You are running Python v 3.8.12. Now checking python packages...
biopython: 1.79
goatools: 1.1.9
matplotlib: 3.4.3
natsort: 7.1.1
numpy: 1.21.2
pandas: 1.3.3
psutil: 5.8.0
requests: 2.26.0
scikit-learn: 1.0
scipy: 1.7.1
seaborn: 0.11.2
All 10 python packages installed
-------------------------------------------------------
Checking external dependencies...
tbl2asn: 25.7
RepeatMasker: RepeatMasker 4.1.2-p1
RepeatModeler: RepeatModeler version DEV
Trimmomatic: 0.39
hisat2: 2.2.1
bowtie2: 2.4.4
tbl2asn: 25.7
ete3: 3.1.1
samtools: 1.13
barrnap: 0.9
busco: 5.2.2
bedtools: v2.30.0
gag: not installed
blast+: 2.10.1+
diamond: 2.0.6
hmmscan: HMMER 3.3.2 (Nov 2020)
mafft: v7.475 (2020/Nov/4)
emapper.py: 2.1.12
```

**Comment by kalonji08** [comment]
this is how my eggnog.annotation look like: (i run it locally)
head -n 5 schizophyllum_commune.emapper.annotations
## Mon Sep  9 22:57:14 2024
## emapper-2.1.12
## emapper.py -m diamond --itype proteins -i /media/external/Comp-analysis/2024_proteins/schizophyllum_commune.fasta -o /media/external/Comp-analysis/eggNOG-results-fungi/schizophyllum_commune --cpu 28 --excel
##
#query	seed_ortholog	evalue	score	eggNOG_OGs	max_annot_lvl	COG_category	Description	Preferred_name	GOs	EC	KEGG_ko	KEGG_Pathway	KEGG_Module	KEGG_Reaction	KEGG_rclass	BRITE	KEGG_TC	CAZy	BiGG_Reaction	PFAMs

**Comment by kalonji08** [comment]
This is my eggnog.annotation output (i run it locally)

```
head -n 5 schizophyllum_commune.emapper.annotations
## Mon Sep  9 22:57:14 2024
## emapper-2.1.12
## emapper.py -m diamond --itype proteins -i /media/external/Comp-analysis/2024_proteins/schizophyllum_commune.fasta -o /media/external/Comp-analysis/eggNOG-results-fungi/schizophyllum_commune --cpu 28 --excel
##
#query	seed_ortholog	evalue	score	eggNOG_OGs	max_annot_lvl	COG_category	Description	Preferred_name	GOs	EC	KEGG_ko	KEGG_Pathway	KEGG_Module	KEGG_Reaction	KEGG_rclass	BRITE	KEGG_TC	CAZy	BiGG_Reaction	PFAMs
```

**Comment by nextgenusfs** [comment]
❯ conda search funannotate
Loading channels: done
# Name                       Version           Build  Channel             
funannotate                    1.8.1    pyh3252c3a_0  bioconda            
funannotate                    1.8.1    pyh3252c3a_1  bioconda            
funannotate                    1.8.3    pyh3252c3a_0  bioconda            
funannotate                    1.8.5    pyh3252c3a_0  bioconda            
funannotate                    1.8.5    pyh3252c3a_1  bioconda            
funannotate                    1.8.7    pyh5e36f6f_0  bioconda            
funannotate                    1.8.9    pyhdfd78af_0  bioconda            
funannotate                    1.8.9    pyhdfd78af_1  bioconda            
funannotate                    1.8.9    pyhdfd78af_2  bioconda            
funannotate                    1.8.9    pyhdfd78af_3  bioconda            
funannotate                   1.8.11    pyhdfd78af_0  bioconda            
funannotate                   1.8.13    pyhdfd78af_0  bioconda            
funannotate                   1.8.15    pyhdfd78af_0  bioconda            
funannotate                   1.8.15    pyhdfd78af_1  bioconda            
funannotate                   1.8.15    pyhdfd78af_2  bioconda            
funannotate                   1.8.17    pyhdfd78af_0  bioconda

**Comment by kalonji08** [comment]
it solved the bug thank you @nextgenusfs
