### ISSUE TITLE
Where do I put the result of an Antismash analysis performed outside of Funannotate?

### ISSUE THREAD

**Issue by eacosta82** [nextgenusfs/funannotate#1079]
Hello everyone.

I apologize for a question that may seem obvious.

I ran the Antismash analyses outside of the Funannotate pipeline. In which folder do I put the result (my_result.gbk)?

Do I put it inside the results/annotate_misc folder?

Or should I pass the .gbk file using the --genbank parameter.

I have always used the pipeline results folder as the input parameter, I don't know if passing the result using the --genbank parameter will ignore what was done previously.

I'm using the lastest release of Funannotate.

Thank you.

**Comment by nextgenusfs** [comment]
can pass the antismash genbank file (which contains all the annotations) to the `--antismash` parameter of `funannotate annotate`

**Comment by eacosta82** [comment]
Thank you so much!  \o/
