### ISSUE TITLE
funannotate clean is very slow

### ISSUE THREAD

**Issue by gskrasnov** [nextgenusfs/funannotate#108]
Hi Jon

Thank you for a wonderful pipeline with detailed instructions how to install it and use it. 
I hope it can really help to annotate genome.
I'm running script "funannotate clean" to clean up assembled genome of Linum usitatissimum. This is tetraploid organism. Assembled genome size is ~360Mb, N50=130.000, total 45.000 scaffolds > 500bp.
I would like to clean up all duplicated scaffolds/contigs, even if this will lead to losses of alleles.

funannotate clean gives me output like this:
jcf7180002614721 appears duplicated: 97% identity over 100% of the contig. contig length: 504
jcf7180002614994 appears duplicated: 95% identity over 100% of the contig. contig length: 504
jcf7180002615221 appears duplicated: 96% identity over 100% of the contig. contig length: 504
jcf7180002615325 appears duplicated: 99% identity over 100% of the contig. contig length: 504
jcf7180002617143 appears duplicated: 95% identity over 99% of the contig. contig length: 504
jcf7180002617150 appears duplicated: 98% identity over 100% of the contig. contig length: 504
jcf7180002617559 appears duplicated: 96% identity over 99% of the contig. contig length: 504
......
......

This script analyzes fasta entries (e.g. scaffolds) one-by-one using mummer mapping against the rest of genome, if I have correctly understood. Each scaffold/contig is analyzed for several minutes (2..5...). 5.000 contigs = 20.000 minutes = 14 days.

My funannotate clean has been already running for 30 hours.

Why not to do mapping "complete genome - vs. - complete genome" (not one-by-one) and then eliminate duplicated scaffolds/contigs?

Or maybe not to use funannotate clean ?

Thanks in advance,
George

**Comment by nextgenusfs** [comment]
Hi George,

`funannotate clean` was written with haploid fungal genomes in mind (~ 30 Mb), thus it may not scale appropriately to a larger assembly.  The idea behind this is that I wanted to just remove duplicates, but not sequencing information. So it starts with the smallest contigs and then iteratively maps those back to the rest of the assembly, if it is "duplicated" then it is dropped from the working assembly - essentially then you end up keeping the largest of the duplicated contigs.  Parsing the all vs all in Mummer wasn't very easy and you have to deal with mapping to multiple contigs/scaffolds, which I didn't find a way to do very easily.  Admittedly, something like this might work...

I'm not sure if there is a better tool for "haploidization" of your assembly, I feel like there must be.  You may have more luck with newer/faster tool like minimap2 for example which should do this type of calculation much faster.  I could look into swapping out Mummer for minimap2 to do the calculations

Jon

**Comment by gskrasnov** [comment]
Thank you for the quick answer,

I have noticed that the processing greatest time (~half) is consumed by creating "reference.fa" file which is performed by python script, not mummer. So replacing mummer with minimap2 can speed up the process not more than two times. Multi-threading could help here.
I think, maybe I should reduce contigs count from 45.000 to ~5.000. The significant part of small contigs may come from tetrapoidy.
Now I will proceed to the next step without **funannotate clean**.

Thank a lot!

**Comment by nextgenusfs** [comment]
I'll see if I can speed that part up, its using SeqIO.parse from biopython right now, which is sort of a lot of overhead for generating the reference files.  But yes, there is some IO slow down with this method, especially in your case with 45,000 sequences.  You can pass a `--minlen` of something higher than the default (500) which will ignore all contigs shorter than that value.  Setting this to something like 1 kb or 5 kb is reasonable, you won't get any gene predictions on smaller contigs anyway.

**Comment by gskrasnov** [comment]
Yes, you are right. I'll try to increase min len threshold.

**Comment by nextgenusfs** [comment]
I just pushed an updated version of the script, https://github.com/nextgenusfs/funannotate/commit/3b3a44f6e7949bddc35e8f234e3bdb3311b577a5.  It should speed up the parsing of the reference/query files as it only reads it once now.  Also I made the default only look for duplicates in contigs that are shorter than the N50 of the assembly, also saving some time.  Shouldn't be any duplicates with contigs that large, but you can run an exhaustive search using `--exhaustive` option.  Note, the menu is not updated yet...

I tried to use minimap2 as well, however, in the short time that I spent I wasn't able to get the settings correct to work the same as mummer - it was much much faster though.  On my 30Mb test set of ~ 200 contigs went from 20 minutes down to 2 minutes.  So if I can find the correct settings can move towards using minimap2 in the future.

**Comment by gskrasnov** [comment]
Thank you, Jon!

**Comment by nextgenusfs** [comment]
v1.0.0 has slight increase in speed.  I reiterate that this script was designed with haploid genomes in mind and isn't recommended for diploid/polyploid assemblies.
