### ISSUE TITLE
problem installing matplotlib and seaborn

### ISSUE THREAD

**Issue by lduvaux** [nextgenusfs/funannotate#11]
Hi,

both these python libraries require the `freetype` lib to be installed. Unfortunately, `pip` cannot install it for the python of funannotate (`~/.linuxbrew/opt/python`).

Therefore, it's needed to install it manually:
download here: http://freetype.sourceforge.net/download.html#stable

unzip and go within the `freetype` foider.

then:
```bash
./configure --prefix=/home/ludo/.linuxbrew/Cellar/python/2.7.11/
make 
make install

pip install matplotlib seaborn
```

Ludovic

**Comment by nextgenusfs** [comment]
Okay, thanks.  The easier way to install free type is to use LinuxBrew, i.e. `brew install freetype`, I will add to instructions.

**Comment by lduvaux** [comment]
OK thanks.
