### ISSUE TITLE
Linux brew install URL for wiki

### ISSUE THREAD

**Issue by dwinter** [nextgenusfs/funannotate#110]
The linux brew repository has moved since the wiki's install instructions for ubuntu were written. Apparently the official install instructions are now:

```sh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

This should replace the current line (`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/linuxbrew/go/install)"
`)

Would have provided a PR with this change, but apparently you can't do that for a wiki.

**Comment by dwinter** [comment]
It may also be helpful to include the install instructions for `brew`, because exactly how to alter the $PATH will vary depending on whether you give the install script the sudo password and other vagaries. Page for that is here http://linuxbrew.sh/

**Comment by nextgenusfs** [comment]
Thanks, I'm planning on converting the wiki to a read-the-docs, just haven't had time to get it done yet. You should not install Brew with sudo though, that is one of the whole points of home-brew so that you shouldn't have to use sudo.  This will be included in next release (sometime next week).

**Comment by nextgenusfs** [comment]
Installation is still slight work in progress, but now located here: http://funannotate.readthedocs.io/en/latest/install.html
