### ISSUE TITLE
error installing funannotate

### ISSUE THREAD

**Issue by anjalianjali1234** [nextgenusfs/funannotate#113]
I am trying to install funannotate using ubuntu 16.04 but it is showing error while downloading dependencies 

`kunal@kunal-CELSIUS-M740Bpower:~$ brew install funannotate`
```
==> Installing funannotate from nextgenusfs/tap
==> Installing dependencies for nextgenusfs/tap/funannotate: braker, evidencemodeler, gag
==> Installing nextgenusfs/tap/funannotate dependency: braker
==> Downloading http://bioinf.uni-greifswald.de/augustus/binaries/BRAKER1_v1.11.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "braker"
Download failed: http://bioinf.uni-greifswald.de/augustus/binaries/BRAKER1_v1.11.tar.gz
```

**Comment by nextgenusfs** [comment]
Seems like they must have moved the binary....will get it fixed soon.

**Comment by nextgenusfs** [comment]
I updated link, it should be working now. `brew update` followed by `brew install funannotate`.  And btw, i'm fairly close to releasing a new version with quite a few updates and bug fixes.

**Comment by nextgenusfs** [comment]
If this is still an issue, feel free to reopen.  installation instructions now at http://funannotate.readthedocs.io/en/latest/install.html
