### ISSUE TITLE
Augustus path

### ISSUE THREAD

**Issue by lduvaux** [nextgenusfs/funannotate#12]
Quick issue:

on my Ubuntu, the path to Augustus is `$HOME/.linuxbrew/opt/augustus-3.2.2/libexec/config` and not `$HOME/.linuxbrew/opt/augustus/libexec/config`

I guess this is important for defining the `AUGUSTUS_CONFIG_PATH` variable

Ludovic

**Comment by nextgenusfs** [comment]
Yes, this is a temporary fix until the augustus 3.2.2 distribution becomes the default with home-brew, right now the 3.2.1 distribution fails during BUSCO.

**Comment by nextgenusfs** [comment]
Built a check for Augustus PPX functionality, and moved to optional for home-brew install as I can't get a unified version that installs on every OS (at this point...)
