### ISSUE TITLE
SignalP 4.1f

### ISSUE THREAD

**Issue by iwangtoknow** [nextgenusfs/funannotate#124]
I can't find 'signalp-4.1c.Linux.tar.Z' from 'http://www.cbs.dtu.dk/cgi-bin/sw_request?signalp'. I download 
'signalp-4.1f.Linux.tar.gz' file, can I just change 4.1c-filename to 4.1f-filename in your dockerfile?

**Comment by nextgenusfs** [comment]
Looks like they updated the download file. I will update according but need to change the name to match and then update how it is extracted. Not sure if contents of new release are the same or not so can’t say without looking at if that is all that needs to change. I’m traveling for next two days and will try to get to it as soon as I can.

**Comment by iwangtoknow** [comment]
Thank you, Jon. So nice of you.

**Comment by nextgenusfs** [comment]
Can you try the updated files now? http://funannotate.readthedocs.io/en/latest/docker.html#docker

**Comment by iwangtoknow** [comment]
Thank you very much, I'll have a try!

**Comment by iwangtoknow** [comment]
Hi Jon! I try to build a docker image but have a permission issue.
---
Step 6/9 : RUN zcat gm_key_64.gz > /home/linuxbrew/.gm_key &&     tar -zxvf signalp-4.1f.Linux.tar.gz &&     sed -i 's,/usr/cbs/bio/src/signalp-4.1,/home/linuxbrew/signalp-4.1,g' signalp-4.1/signalp &&     sed -i 's,#!/usr/bin/perl,#!/usr/bin/env perl,g' signalp-4.1/signalp
 ---> Running in 52a451415f94
gzip: gm_key_64.gz: Permission denied
The command '/bin/sh -c zcat gm_key_64.gz > /home/linuxbrew/.gm_key &&     tar -zxvf signalp-4.1f.Linux.tar.gz &&     sed -i 's,/usr/cbs/bio/src/signalp-4.1,/home/linuxbrew/signalp-4.1,g' signalp-4.1/signalp &&     sed -i 's,#!/usr/bin/perl,#!/usr/bin/env perl,g' signalp-4.1/signalp' returned a non-zero code: 1
---
 I have linuxbrew on my Ubuntu. and 
---
$ ls -l /home
drwxr-xr-x  3 root    root        4096 Jan  2 09:21 linuxbrew
---
 So, how can I solve this?

**Comment by nextgenusfs** [comment]
What are the permissions on the files that you downloaded?  Likely that is
the problem.

**Comment by iwangtoknow** [comment]
manager@bl8vbox:/media/sf_F/Aspergillus nidulans/funannotate$ ls -l
total 57496
-rwxrwx--- 1 root vboxsf     1460 Jan 21 12:44 Dockerfile
drwxrwx--- 1 root vboxsf        0 Jan 21 12:44 funannotate
-rwxrwx--- 1 root vboxsf       82 Jan 13 21:14 gm_key_64.gz
-rwxrwx--- 1 root vboxsf 51207503 Jan 30  2017 RepBaseRepeatMaskerEdition-20170127.tar.gz
-rwxrwx--- 1 root vboxsf  7654780 Jan 15 10:42 signalp-4.1f.Linux.tar.gz
-rwxrwx--- 1 root vboxsf    11211 Jan 15 10:39 SignalP-license.txt
---
Should I chown to manager?

**Comment by iwangtoknow** [comment]
![docker](https://user-images.githubusercontent.com/35318350/35208200-fb64c6c8-ff81-11e7-9a66-9ea2762fb7ea.jpg)

![home](https://user-images.githubusercontent.com/35318350/35208191-f5603bcc-ff81-11e7-9b06-6eb64307a26d.jpg)
I lunch super user(root account), but it still doesn't work.
![fun](https://user-images.githubusercontent.com/35318350/35208185-eb92420c-ff81-11e7-9056-57f733215b3d.jpg)

**Comment by nextgenusfs** [comment]
I don't have access to a Linux machine to test how Docker works on Linux, I know there are permissions issues.  I think you need to make sure that you are running these commands inside a folder that Docker thinks is a shared volume, on my Mac that is under Preferences and File Sharing in the docker app. You can try to edit the Dockerfile and add `sudo` in front of those commands and see if that works.  What is your system setup?  If you are on Ubuntu, it should be somewhat easy to install with linuxbrew.  But also seems like based on your username that you are running VirtualBox?  Are you trying to install Docker containers inside a VirtualBox container??

**Comment by iwangtoknow** [comment]
Yes, you're right, I'm working on a virtual machine running Ubuntu 14.04 from Sanger Pathogens -vm, and try to build a docker image. I have a genome of Aspergillus nidulans, PacBio sequencing, 13 contigs (I know the reference genome has 8 chromosome), and I need to annotate this genome.
My computer operation system is Windows 8.1.
My work space is weird, right?
If you interested I can sent you my raw assembly.

**Comment by nextgenusfs** [comment]
Can you try Docker for windows?  That seems like it would be a lot simpler.

**Comment by nextgenusfs** [comment]
Otherwise just install funannotate on your virtual box Ubuntu image.

**Comment by iwangtoknow** [comment]
Yes, I'd like to directly install docker on my operating system, but only Windows10 with 10th anniversary update installed, can support docker CE well, otherwise I need a toolkit. It makes me confuse to install funannotate on my virtual machine. I like docker even though it occupied a lot disk space.

**Comment by nextgenusfs** [comment]
Docker for older windows: https://docs.docker.com/toolbox/toolbox_install_windows/

Installing on your VirtualBox Ubuntu shouldn't be that difficult, you can use LinuxBrew: http://funannotate.readthedocs.io/en/latest/homebrew.html#homebrew

**Comment by iwangtoknow** [comment]
Dear Jon,
               So nice of you, and I found something.
               I checked the command permission denied, gzip: gm_key_64.gz:
Permission denied and, which command use gzip? This: The command '/bin/sh
-c zcat gm_key_64.gz > /home/linuxbrew/.gm_key &&... ,why there is a dot in
front of the gm_key? And if I deleted the dot, I will have a file in
/home/linuxbrew.


Grateful, So nice of you.
​Wang Yiqing

2018-01-24 0:06 GMT+08:00 Jon Palmer <notifications@github.com>:

**Comment by iwangtoknow** [comment]
Dear Jon,
         Sorry, now I know that is a hidden file.😅
Wang Yiqing

2018-01-25 9:20 GMT+08:00 王益清 <iwangtoknow@gmail.com>:

**Comment by iwangtoknow** [comment]
​Dear Jon,
        I finished to build a funannotate docker image on my Ubuntu. I
switch to superuser and modified the DockerFile, add sudo in front of some
commands.
        But there's still two red lines when I building the image.
        Ones is TERM environment variable not set.

And the other one appears when downloading the Merops database.
I'll keep on.
Thank you.
Wang Yiqing
​

2018-01-25 9:26 GMT+08:00 王益清 <iwangtoknow@gmail.com>:

**Comment by iwangtoknow** [comment]
![term](https://user-images.githubusercontent.com/35318350/35367287-89f131e6-01b8-11e8-992a-f90ddfd310fe.jpg)
![merops](https://user-images.githubusercontent.com/35318350/35367289-8def77a8-01b8-11e8-8696-ce76fab01789.jpg)

**Comment by iwangtoknow** [comment]
[Dockerfile.txt](https://github.com/nextgenusfs/funannotate/files/1662345/Dockerfile.txt)

**Comment by nextgenusfs** [comment]
The download error was because merops renamed the file... I don't know what the TERM environmental variable means, but if repeat masker builds correctly maybe it isn't a big deal.  Unfortunately, I have to re-build the funannotate-base docker file in order for the merops database problem to go away.  That will likely take a few days, but I will let you know when it is done.

**Comment by iwangtoknow** [comment]
Dear Jon,
        tour de force, in Chinese "给力".
  Grateful!
Wang Yiqing

2018-01-26 6:08 GMT+08:00 Jon Palmer <notifications@github.com>:

**Comment by nextgenusfs** [comment]
Okay you should be good to try to install again via docker, v1.1.1 should be live on docker cloud.  Good luck.

**Comment by iwangtoknow** [comment]
Hi Jon,
I have build a fuannotate image on my Ubuntu.
But
New issue.
![evm](https://user-images.githubusercontent.com/35318350/35793663-94674376-0a8d-11e8-8faa-dd9e223b6a9a.jpg)
I checked the file, it is empty indeed.
Thank you.
Yours sincerely.
Wang Yiqing

**Comment by nextgenusfs** [comment]
What is in the EVM log file? located in `logfiles/funannotate-EVM.log`

**Comment by iwangtoknow** [comment]
[funannotate-EVM.log](https://github.com/nextgenusfs/funannotate/files/1712992/funannotate-EVM.log)
![evm__unitig5_quiver](https://user-images.githubusercontent.com/35318350/36058402-0747d066-0e5a-11e8-8270-62009a679763.jpg)
I'm not sure the problem...
This is the log file anyway.
Thank you Jon.
Wang Yiqing

**Comment by nextgenusfs** [comment]
It might be your contig/scaffold names.  You can rename them using something like `funannotate sort`.
