### ISSUE TITLE
BRAKER failing on Linux....

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/funannotate#127]
Several users have found Braker erroring out and stopping predict pipeline.  Investigate. I'm sort of sick of this, might just re-write the braker steps for training in funannotate which would be then one less dependency.....

**Comment by nextgenusfs** [comment]
It is not a Linux problem per say, it is a braker version problem.  versions < 2.0.0 do not support the `--working_dir` option.  versions >2.0.0 but <2.0.2 support `--working_dir` but the folder 'braker' is created onto of the directory you specifed.  In v2.0.2 it seems to work the way one would expect, i.e. whatever you specify for `--working_dir` is where the files are saved. 

So basically 2 options for support: 1) require everybody to use v2.02 or greater and then be at the mercy of whatever they change next time, or 2) just re-write the training steps in python so I have control of location, paths, etc.  I'm in favor of 2) just will take a bit longer....

**Comment by nextgenusfs** [comment]
Another wrench.... Braker v2.0.2 does not have a functional `braker.pl --version` option.  It is coded and appears to be available, however, it doesn't return the version number. 

Other options include packaging a functional version of braker into funannotate, however, I think the software licenses are not congruent....

**Comment by nextgenusfs** [comment]
The best thing to do here is I think to write the training steps in python so don't have to rely on more dependencies that are unstable.  Issues that need to be addressed include:
1) write native python `bam2hints` program. This is optional as can just run bam2hints from python, but might resolve other issues. Can use the native python pybam parser to do this, note it will be slower than the C program likely, however, this would alleviate the huge problem of compiling bamtools and augustus "correctly" --> which remains an installation nightmare.
2) after bam file is converted to hints file, use the protein evidence and transcript evidence hint files to run GeneMark-ET
3) Grab "random" (note probably not random but grab good gene models for training) GeneMark-ET gene models for training Augustus, re-using the bam, protein, and transcript hints. This isn't too difficult, just running etraining and optimize augustus.

Anything else I'm missing?

**Comment by hyphaltip** [comment]
It makes sense to package it better but there will be some divergence perhaps in funannotate results from other pipelines if the steps are not as reproducible/transferrable. 

Or if the braker authors end up developing other specifications to what bam2hints should look like?

**Comment by nextgenusfs** [comment]
I just wish they (Augustus/Braker folks) would use GitHub or something so there was a way to document and help them fix bugs. I've emailed and posted on their forums in the past and never heard back.  I can try again to at least patch the `braker.pl --version` bug so we can make funannotate work with a specific version.  Right now I can't predict where the output folder is going to be created, thus causing pipeline to fail for different reasons on different systems.

**Comment by nextgenusfs** [comment]
Package braker with funannotate to avoid these problems, funannotate will use embedded copy of braker. https://github.com/nextgenusfs/funannotate/commit/378966f86d15713e81545b95f25ea4d770d7ff36
