### ISSUE TITLE
BUSCO migrated

### ISSUE THREAD

**Issue by AnotherSimon** [nextgenusfs/funannotate#136]
When running "funannotate predict" with option "--busco_db basidiomycota" the script stalls because it tries to download the BUSCO models from "http://busco.ezlab.org". Presumably it fails with any of the possible values for this parameter.

As part of the upgrade from BUSCO v2 to v3, they have moved to a new domain ("https://gitlab.com/ezlab/busco/tree/master"). "http://busco.ezlab.org" is currently unavailable, not sure where the models will end up eventually. 

Any suggestions for a temporary work-around? I already tried downloading the models into the working directory from their temporary home on Google drive (and unpacked them and kept the tar ball) but the script still tries to download from ezlab.org.

Edit: My current workaround is to kill the wget operation after which the script proceeds with unpacking the manually downloaded tar ball but for people running funannotate on a HPC this will probably not be helpful.

**Comment by nextgenusfs** [comment]
If the busco folder is downloaded and unpacked in the funannotate database folder it still tries to download it?  I have been meaning to transfer this to the setup script. Will try to get it fixed tomorrow.  I can probably move the models to another location so they won’t keep moving around, will need to look at their license again to make sure that is okay.

**Comment by AnotherSimon** [comment]
My mistake, I assumed busco was only stored in working directory because that's where the folder "dikarya_odb9" folder appeared (default downloaded during my test run of the pipeline).

Just checked $FUNANNOTATE_DB folder and it now contains subfolders "dikarya" and "basidiomycota" so I assume it will run smoothly in future for me. But other users will likely run into same issue until they get their domain sorted out.

**Comment by nextgenusfs** [comment]
Yes, it downloads in working directory and then moves to funannotate_db. But this behavior will change in next release, as some HPC users don't have access to internet, so going to put this in the setup so that an administrator could install all of them for example.

It looks like the busco site is back online, however, I also moved them to the funannotate OSF shared folder and will download from there which will hopefully make sure this doesn't happen in the future.
