### ISSUE TITLE
resume pipeline

### ISSUE THREAD

**Issue by AnotherSimon** [nextgenusfs/funannotate#137]
Hi again Jon,

The funannotate pipeline currently already supports picking up work where it left off after an error or interruption pretty well. However, there is little or no documentation on the order in which files are generated and which ones a user would need to delete to restart from point B and not point C.

In my case I've repeatedly run into problems with Pasa where certain tables were not generated or already exist and the pipeline tries to resume without going through the required steps again.

Could be solved by more extensive documentation or more thorough checkpointing, pick your favorite.
(File under enhancement?)

**Comment by nextgenusfs** [comment]
Yes I know the docs are lacking at this point, sorry about that.  I've been working on trying to get the whole pipeline to support multiple transcripts (which is much more work than I thought) --> the goal is getting it stable so I can get a manuscript prepared along with more complete docs.  The RNA-seq modules are still quite new and docs are absent for most of this (I would like to replace PASA with something easier to run/install but don't of any alternatives). 

It would be helpful if you documented what specifically didn't make sense and/or wasn't clear, as being the person that wrote it, what is obvious to me won't be obvious to others  --> that way I can make sure it gets into the docs.

**Comment by AnotherSimon** [comment]
Sorry it took a while to reply, issues pop up as you go. Pretty sure this is not a definitive list but here are a few potential improvements to pipeline/documentation that I see so far:

- SOAP for PERL not mentioned in dependencies but required for remote Phobius run
- `funannotate remote` with `--mode all` might benefit from running in parallel for the 3 DBs queried
- for any step of the pipeline: if you ran into some trouble and wish to rerun, you need to delete the following files to rerun rather than resume from point x in the pipeline
- include a command similar to `funannotate check --show-versions > DependenciesVersions.out` by default, costs relatively little running time and forces users to have version records (maybe include a switch to turn this behaviour off if required)
- in `funannotate predict` how do the following options interact when active at same time and are any required when working with RNAseq data support:
		`--augustus_species`	Augustus species config. Default: uses species name
 		`--busco_seed_species`	Augustus pre-trained species to start BUSCO. Default: anidulans
		`--optimize_augustus`	Run 'optimze_augustus.pl' to refine training (long runtime)
		`--busco_db`			BUSCO models. Default: dikarya.
- multiple inputs to `funannotate predict --protein_evidence` fails early (before repeat masking), `--help` suggests a comma separated list is fine but does not work in my hands, both files separately start off fine (havn't tried running to completion yet)

**Comment by devonorourke** [comment]
I was curious about the specifics for restarting a run. 
I have a `funannotate predict` job that failed only because my cluster requires us to allocated a particular amount of time to each job, and I didn't make it through the entire pipeline in 4.5 days. 
Is it as simple as rerunning the same `funannotate predict ...` command with the same `-o ` prefix? I was curious if I need to delete any temporary directories first, as mentioned in the above thread:
> for any step of the pipeline: if you ran into some trouble and wish to rerun, you need to delete the following files to rerun rather than resume from point x in the pipeline

Two examples: 
1. Say I get through the Diamond/Exonerate step, but only half way through Genemark
2. Say I get through Genemark, but only half way through Augustus

Thanks for the help

**Comment by nextgenusfs** [comment]
You should be able to just resubmit with the same command -- if the final results of a step are present it will use them and move onto the next step. If it was interrupted in the middle of a step then it should restart that step from the beginning.
