### ISSUE TITLE
local iprscan error

### ISSUE THREAD

**Issue by AnotherSimon** [nextgenusfs/funannotate#138]
When running funannotate iprscan on a genome that successfully made it through the predict step (~8000 genes), the result is a nearly empty xml file.

Command issued:
'nohup nice -19 funannotate iprscan -i MyFungus --method local --iprscan_path ~/software/interproscan-5.25-64.0/interproscan.sh --cpus 24 > FunannotateIprScan.out &'

Sample output from temporary working directory for one of the protein chunks:
'19/02/2018 12:14:36:022 Welcome to InterProScan-5.25-64.0
For the (-d) option you specified a location which doesn't exist or is not readable:
/full/path/to/Myfungus/iprscan_26485/iprscan_26485'

The temp dir seems to be duplicated when passed to the "-d" parameter.

**Comment by nextgenusfs** [comment]
Thanks, I think https://github.com/nextgenusfs/funannotate/commit/983620d31d99d885e970386b80533a3b1aa811cd should fix it. Let me know if it works as I don't have a local IPR installation to test it on.

**Comment by AnotherSimon** [comment]
yup, seems to have done the trick IPR is humming away
