### ISSUE TITLE
error adding new outgroup for funannotate compare

### ISSUE THREAD

**Issue by AnotherSimon** [nextgenusfs/funannotate#139]
When running:
'funannotate outgroups --input Ensembl.sourced.pep.all.fa --species "MyOut species" --busco_db basidiomycota --cpus 24'

The StdOut shows this error:

> [92m[02:52:44 PM][0m: OS: linux2, 24 cores, ~ 66 GB RAM. Python: 2.7.9
> [92m[02:52:45 PM][0m: Running funannotate v1.1.1
> -------------------------------------------------------
> Traceback (most recent call last):
>   File "/data1/home/simon/software/funannotate/util/add2outgroups.py", line 48, in <module>
>     lib.download_buscos(args.busco_db)
> TypeError: download_buscos() takes exactly 2 arguments (1 given)`

(Apologies for the automatic formatting.)

**Comment by nextgenusfs** [comment]
Thanks, this script wasn't updated when I changed the way the databases were managed. Also, moved busco database install to `funannotate setup` so downloading the models on the fly is no longer supported. https://github.com/nextgenusfs/funannotate/commit/6fb063af39d69e2b2ed98370375f646534b4dcf2.  Few more tests to do and then moving towards a v1.2.0 release shortly.

**Comment by AnotherSimon** [comment]
While you're fixing the setup module, the number of BUSCO outgroups is currently (v1.0) listed as 8 while there actually only 6 species files in the folder. The other 2 are presumably the Mac hidden files `.DS_Store` and `._.DS_Store`.

**Comment by AnotherSimon** [comment]
This issue seems to be fixed as of 1.3.0 (skipped 1.2 in my tests).
