### ISSUE TITLE
InterProScan issue

### ISSUE THREAD

**Issue by krostifangers** [nextgenusfs/funannotate#14]
Dear Jon
I am stuck with InterProScan. It seems unable to reach the server...
I had the following message for hours...

```
[04:28:29 PM]: Now running InterProScan search remotely using EBI servers on 47 proteins
 IPR progress: [------------------------------] 0.00% 
```

How can I fix it?
Thanks in advance
regards
christophe

**Comment by nextgenusfs** [comment]
Hi Christophe,
Sounds like maybe a connectivity issue with the EBI servers.  Can you try to run the script directly (without the FA wrapper), you have to pass it a single protein in fasta format (there is a tmp folder in your 'annotate_misc' folder that is created during IPR runs that should have each individual protein (or actually any protein sequence in fasta format), so you could run it like so:
```
$HOMEBREW_PATH/opt/funannotate/libexec/util/runIPRscan.py --goterms \
--email email@youraddress.com --outfile test --input single_protein_seq.fa
```
The output should look something like this:
```
runIPRscan.py --goterms --email palmer3@wisc.edu --outfile test --input test.fa 
iprscan5-R20160608-175132-0414-15170974-es
RUNNING
RUNNING
FINISHED
test.out.txt
test.log.txt
test.tsv.txt
test.xml.xml
test.htmltarball.html.tar.gz
test.gff.txt
test.svg.svg
test.sequence.txt
```

**Comment by nextgenusfs** [comment]
Just a follow up, for remote IPR search the `--email` option is required.  See discussion https://github.com/nextgenusfs/funannotate/issues/33
