### ISSUE TITLE
local InterProScan number of threads

### ISSUE THREAD

**Issue by AnotherSimon** [nextgenusfs/funannotate#140]
When running the command:
`funannotate iprscan -i MyAnnotation --method local --iprscan_path /path/to/interproscan.sh --cpus N `

The number of threads used is not actually N but rather N * number of protein chunk files. Documentation should reflect this or the script needs to be changed to run chunks sequentially rather than parallel to avoid flooding resources.

**Comment by nextgenusfs** [comment]
It should be running --cpus / --cpus_per_chunk, i.e. `--cpus 20` and `--cpus_per_chunk 4` would launch 5 Interproscan instances. Is that not what it is doing?

**Comment by nextgenusfs** [comment]
Oh.... its in your interproscan.properties settings.  yes that needs to be clarified.  The script was written for docker, so I'm modifying the properties file to run what I described above. A local install you will need to control that manually.

**Comment by nextgenusfs** [comment]
https://github.com/nextgenusfs/funannotate/commit/0757e53bccac789238f6984e1c1d215c4998ecd0 this make more sense?

**Comment by AnotherSimon** [comment]
sounds good
