### ISSUE TITLE
Deleting too short proteins from the assembly

### ISSUE THREAD

**Issue by gskrasnov** [nextgenusfs/funannotate#143]
Dear Jon!

I have found that funannotate predicts lots of proteins less than 200 aa. Many of them cannot be adequately mapped to UniProt (total 64.000 proteins have been identified). I would like to remove them from the assembly completely. I have prepared list of the proteins.
However, `funannotate annotate .... --remove delete.txt` removes only the annotations.
Is there any way to completely delete such records (only proteins, not mRNA and genes)?

**Comment by nextgenusfs** [comment]
Right now -- not exactly.  But I can probably come up with something.  You should be able to filter them at the `funannotate predict` step, i.e. with `--min_protlen` but if you have already generated functional annotation then it will likely result in changing locus names (which you may not want).  Let me see if I can add an option to `funannotate fix` that can filter on length as well as maybe just locus_tags (if you have them in list form).

**Comment by gskrasnov** [comment]
This is not exactly what I mean. I would like to eliminate proteins from a manually created list. And this list is created based on the functional annotation. A protein will be excluded if 1) it is shorter than 200 aa and have no UniProt target with homologous regions >45% of its length, or 2) is shorter than 500 aa and its closest UniProt target has 2-fold greater length, i.e. the protein is most likely truncated.

I think that changing locus/gene names is not a big problem....

**Comment by nextgenusfs** [comment]
Yeah I understand. Funannotate fix will make a backup if the data and then modify the tbl file, I just need to add a —drop option so you can pass a file containing locus_tag that you would like to drop from the annotation. I could add this to annotate but more overhead there than necessary. Sound like that would work?

**Comment by gskrasnov** [comment]
Theoretically, `--drop <user_defined_list.txt>` option is just what I want.

**Comment by gskrasnov** [comment]
Thank you, Jon! I see that you have added this option in the release 1.2 .

**Comment by nextgenusfs** [comment]
Let me know if it isn't working the way you want it to.
