### ISSUE TITLE
Funannotate clean error

### ISSUE THREAD

**Issue by ignadb** [nextgenusfs/funannotate#147]
When running funannotate clean, it exits after a few seconds with the following error messages:

-----------------------------------------------
1,714 input contigs, 1,714 larger than 500 bp, N50 is 156,341 bp
Checking duplication of 1,583 contigs shorter than N50
-----------------------------------------------
Traceback (most recent call last):
  File "xxx/funannotate/bin/funannotate-contig_cleaner.py", line 174, in <module>
    runNucmer('query.fa', 'reference.fa', scaffolds[i])
  File "xxx/funannotate/bin/funannotate-contig_cleaner.py", line 120, in runNucmer
    os.remove(input)
OSError: [Errno 2] No such file or directory: 'LLCB01001711.1.delta'

There is also a file called nucmer.error which contains the following info:
20180301|225801| 18737| ERROR: mummer and/or mgaps returned non-zero

Unfortunately I cannot seem to find any further log files to see what could be the issue, any ideas?

Thanks in advance!

**Comment by nextgenusfs** [comment]
Sounds like mummer is not installed correctly, can you just run this command and see if you get some errors?
```
nucmer -p test query.fa target.fasta
```
The two fasta files can be any fasta files, but hopefully will give you a more understandable error message.

**Comment by ignadb** [comment]
Hi, please see below

xxx/funannotate$ nucmer -p test test_nucmer.fa Fmandshurian_3rd_timepoint.fa

1: PREPARING DATA

2,3: RUNNING mummer AND CREATING CLUSTERS

# reading input file "test.ntref" of length 26566

# construct suffix tree for sequence of length 26566

# (maximum reference length is 536870908)

# (maximum query length is 4294967295)

# CONSTRUCTIONTIME xxx/MUMmer3.23/mummer test.ntref 0.01

# reading input file "xxx/funannotate/Fmandshurian_3rd_timepoint.fa" of length 1063215

# matching query-file "xxx/funannotate/Fmandshurian_3rd_timepoint.fa"

# against subject-file "test.ntref"

# COMPLETETIME xxx/MUMmer3.23/mummer test.ntref 0.31

# SPACE xxx/MUMmer3.23/mummer test.ntref 1.06

4: FINISHING DATA
xxx/funannotate$

**Comment by nextgenusfs** [comment]
Okay, and then there was an output file called `test.delta` that was created?  If so, then that isn't the error.  But there is obviously an error...
```
There is also a file called nucmer.error which contains the following info:
20180301|225801| 18737| ERROR: mummer and/or mgaps returned non-zero
```
Have you checked for any empty contigs in your fasta file?  Not sure what else the problem could be.

**Comment by ignadb** [comment]
Hi,

Yes, I got the test.delta file no problems.

I tried rerunning funannotate clean against another input file which has worked previously and I get the same error. Is there any way to increase the logging so I could see which command goes wrong so I can figure out whats happening? Either that or if you could give me the sequence of commands which are run by funannotate clean. I get 2 .fa files in the folder where I try to run it which are both 0 bytes, query.fa and reference.fa.

The .mgaps and .ntref files are also suspiciously small, 6 and 69 bytes respectively.

Thanks.

**Comment by ignadb** [comment]
Update, I ran a funannotate sort on the fasta file that was causing the problems and it changed all the descriptions to scaffold_1 etc, previously there were spaces in the descriptions and that seems to have been the cause of the problem.

Thanks for your time and I am sorry to have troubled you.

**Comment by nextgenusfs** [comment]
Glad you got it fixed.

**Comment by kastman** [comment]
Seconded (apologies if this inadvertantly reopens the issue, but I don't think it will). Maybe this would be a good candidate for an FAQ question.

I also had illegal characters in my fasta deflines (parenthesis), and this was breaking `nucmer`, but the error "`OSError: [Errno 2] No such file or directory: 'contig (name).delta'` wasn't helpful for figuring out what mistake I made. Renaming first (through `funannotate sort` or similar) fixed this.

**Comment by nextgenusfs** [comment]
Would you be able to run it again (with the parenthesis) and pass `--method minimap2` and see if it runs to completion or gives you a similar error?  This has been built into the code for awhile but I didn't put in the menu, but now that `minimap2` is used in many other steps in `funannotate` I'm considering dropping `mummer` from this command because it is the only place its used.  I'd like to limit dependencies if possible.

**Comment by kastman** [comment]
Sure, I'll take a crack at it. Also adding @lizlandis to the conversation in case she wants to follow along (or try it with `--method minimap2`). I'm guessing that you've cross-checked the results / benchmarked and they're more or less comparable?

**Comment by nextgenusfs** [comment]
Yes they are not identical -- which is due I think to the differences in the alignment algorithms. Mummer identifies more duplicated contigs -- whether that is the "correct" answer I don't know. Minimap2 is much much faster.
