### ISSUE TITLE
BRAKER producing bad GeneMark predictions?

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/funannotate#149]
I think that BRAKER is not producing very good GeneMark gene predictions via its GeneMark-ET "training".  I've seen with very complete RNA-seq data that GeneMark results from BRAKER are actually "worse" than those from self-training GeneMark-ES.  Also with larger genomes, it seems that GeneMark-ET results via BRAKER are fragmented or producing many small gene predictions.

I'm wondering if this is related to https://github.com/nextgenusfs/funannotate/issues/143, @gskrasnov mentioned getting lots of short gene predictions from funannotate. @gskrasnov are these short models that you see derived from GeneMark?  

I'm now working on trying to test this more thoroughly and likely working towards a solution where `--braker` is an option and not the standard approach if providing RNA-seq data. Instead I think if you have RNA-seq data and you ran PASA, that funannotate will use those PASA models to train Augustus and use GeneMark-ES data.  That should result in accurate training of Augustus and stick with GeneMark-ES data which in many cases seems to be better than GeneMark-ET.

Thoughts?

**Comment by nextgenusfs** [comment]
So looks like after quite a bit of testing.... I think GeneMark is generating many more gene models if it is given anything in the `--evidence` option. I added this option awhile ago, thinking that it could only help - as is the case with Augustus.  But now re-thinking this.  A few more tests to go, but right now I'm leaning toward removing the `--evidence` option from Genemark and providing more options to user to decide on how they would like to run Genemark.  But in the process of testing which evidence is leading to the 20-30% increase in number of gene models predicted. 

So you could run BRAKER by adding `--braker` option. You can run GeneMark-ET by providing the `-gm ET` or `--genemark_mode ET` option. The default option for GeneMark (`-gm ES`) will run standard GeneMark-ES.

**Comment by liqg** [comment]
I am not familiar with gene prediction. Is the problem of the option `-max_intronlen` during Genemark-ES,
I say this:
```
 cmd = ['gmes_petap.pl', '--ES', '--max_intron', str(maxintron), '--soft_mask', '5000', '--cores', str(cpus), '--sequence', contigs]
```
