### ISSUE TITLE
iprscan.xml parsing every time necessary?

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#153]
Does it make sense to just check if the IPR_terms file is older than the IPRCombined file first and only run the parsing again if it has been updated? Its a small performance thing but just wondering if you think this sort of caching is a problem. Would basically change this code below so that it didn't alway remove the file, but removed it and ran the next step only if the file age was older.

```
   if os.path.isfile(IPR_terms):
        os.remove(IPR_terms)
    cmd = [sys.executable, IPR2ANNOTATE, IPRCombined, IPR_terms]
    lib.runSubprocess(cmd, '.', lib.log)
```

**Comment by nextgenusfs** [comment]
Yeah that would be fine, seems like can get last modified time with `os.path.getmtime(file)`.
So something like:
```
    if os.path.isfile(IPR_terms):
	if os.path.getmtime(IPR_terms) < os.path.getmtime(IPRCombined):
        	os.remove(IPR_terms)
    if not lib.checkannotations(IPR_terms):
    	lib.log.info("Parsing InterProScan5 XML file")
    	cmd = [sys.executable, IPR2ANNOTATE, IPRCombined, IPR_terms]
    	lib.runSubprocess(cmd, '.', lib.log)
```
