### ISSUE TITLE
KeyError in funannotate-functional.py

### ISSUE THREAD

**Issue by AnotherSimon** [nextgenusfs/funannotate#155]
Hi John,
When running `funannotate annotate -i MyBug --fix MyBug/MyBug.annotationsFixed.txt`, I get the following error:
```
[03:36:35 PM]: Converting to final Genbank format, good luck!
[03:37:17 PM]: Creating AGP file and corresponding contigs file
[03:37:17 PM]: Cross referencing SM cluster hits with MIBiG database version 1.3
[03:37:43 PM]: Creating tab-delimited SM cluster output
[03:37:46 PM]: Writing genome annotation table.
Traceback (most recent call last):
 File "/data_n2/home/simon/software/funannotate/bin/funannotate-functional.py", line 1249, in <module>
lib.annotationtable(final_gbk, FUNDB, final_annotation)
 File "/data_n2/home/simon/software/funannotate/lib/library.py", line 3205, in annotationtable
Product = f.qualifiers['product'][0]
KeyError: 'product'
```

More context: performed `funannotate remote -m all` first, then `funannotate annotate` with the 3 remote annotation results specified, then create a copy of and manually fix `MyBug/annotate_results/MyBug.annotations.txt` (2 genes with "RRM" for gene description, fails because all caps). And then lastly the command above. We recently moved to a new production system so it's possible that this is an artefact from the move but it seems strange that all other steps seem to work so far.

**Comment by nextgenusfs** [comment]
I think this might be due to changes from single transcript to multiple transcripts and likely hitting a tRNA model that is lacking a product annotation.  Which version are you running?  It may have been fixed already in tip repository.

**Comment by nextgenusfs** [comment]
But if hasn't been fixed and isn't from a tRNA model, then this should fix it, if not found defaults to hypothetical protein. https://github.com/nextgenusfs/funannotate/commit/82915f47bf627ceac5fc0fcf4600a91f8605c6b6

**Comment by AnotherSimon** [comment]
I created the gene models with v1.1.1 but updated to master yesterday (v1.3.0) because a lot of the fixes relate to issues I was encountering. I'm rerunning from `funannotate predict` now to save on time or do you advise to rerun from scratch?

Either way, will let you know if it's fixed.

**Comment by AnotherSimon** [comment]
It was indeed an incompatibility between PASA db made in funnanotate v1.1 
Shouldn't affect most users.
