### ISSUE TITLE
error renaming IPRscan log

### ISSUE THREAD

**Issue by AnotherSimon** [nextgenusfs/funannotate#157]
When running `funannotate remote -m interproscan` the scan completes just fine and the `MyBug/annotate_misc/iprscan.xml` file is generated. However, the end of the log file reads:
> Traceback (most recent call last):
  File "/home/simon/software/funannotate/bin/funannotate-remote.py", line 299, in <module>
    os.rename(log_name, os.path.join(outputdir, 'logfiles', log_name))
OSError: [Errno 2] No such file or directory

**Comment by nextgenusfs** [comment]
https://github.com/nextgenusfs/funannotate/commit/7347659131140c330a06f0eefda3aa6e60eb4b33 should fix this error.
