### ISSUE TITLE
arthropod annotation

### ISSUE THREAD

**Issue by ptranvan** [nextgenusfs/funannotate#16]
Hello,

How can I modifiy your pipeline for arthropod annotation ?

Thanks for your help.

**Comment by nextgenusfs** [comment]
Hi @ptranvan, while I have not tested it - I think that funannotate can do this.  What other data do you have besides the genome?  Any RNA-seq?

If you just have the genome, the `funannotate predict` command could look something like this:
```
funannotate predict -i your_genome.fa -o annotate_results --organism other \
--species "Genus species" --busco_db arthropoda --busco_seed_species tribalism \
--transcript_evidence ESTs.fa --max_intronlen 10000 --cpus X
```

Try to give the script some transcript evidence, can be from a closely related species (ESTs for example). My default it will use the UniProtKb protein database for protein evidence.  If you had RNA-seq, then I would do a bit more work before funannotate to assemble the transcriptome (Trinity/PASA, etc) and align the reads to the genome (--rna_bam) and feed those data to funannotate which will increase accuracy of prediction.

Let me know if this works, thanks.
