### ISSUE TITLE
No funannotate formula found on taps

### ISSUE THREAD

**Issue by thebenallen** [nextgenusfs/funannotate#164]
Hi! Doing the homebrew installation on OSX 10.11

I have all of the dependencies, but when I run
`brew install funannotate`

I get:

`Error: No available formula with the name "funannotate" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.`

I checked in https://github.com/brewsci/homebrew-science/tree/master/Formula and I didn't see funannotate. So, I suppose it is missing, but maybe I'm missing something.

**Comment by nextgenusfs** [comment]
You are following these instructions? http://funannotate.readthedocs.io/en/latest/homebrew.html#homebrew

You need to tap my repository, `brew tap nextgenusfs/tap`.  I haven't put the formula into the new brewsci tap yet.

**Comment by thebenallen** [comment]
Yes I was following along with those instructions but must've goof'd when tapping the correct repository... Fixed now, thanks!

**Comment by thebenallen** [comment]
Connected to the correct tap, but keep getting this SHA256 mismatch error when trying to install tbl2asn. I thought I might be able to work around by installing tbl2asn with conda, and then rerunning `brew install funannotate` but that didn't work either. Tried removing the file but that also didn't work.

`==> Installing funannotate from nextgenusfs/tap
==> Installing dependencies for nextgenusfs/tap/funannotate: tbl2asn, gmp, mpfr, libmpc, isl, gcc, raxml, trimal, mafft, evidencemodeler, proteinortho, paml, diamond, hisat2, cmake, protobuf, gperftools, express, tbb, bowtie2, jellyfish, trimmomatic, trinity, szip, hdf5, kallisto
==> Installing nextgenusfs/tap/funannotate dependency: tbl2asn
==> Downloading https://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/mac.tbl2asn.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c79416ff5fea23baf4ac10ff1a67f7f6e099980a45ac878f649821ba7b68788b
Actual: eb86fe57e1af285914b655b0bee1e5f2e357e28c5bc301b8f891bee0fdf955c8
Archive: /Users/b8a/Library/Caches/Homebrew/tbl2asn-25.6.gz
To retry an incomplete download, remove the file above.`

**Comment by nextgenusfs** [comment]
Seems to be working on my system?
```
brew reinstall tbl2asn
==> Reinstalling brewsci/bio/tbl2asn 
==> Downloading https://linuxbrew.bintray.com/bottles-bio/tbl2asn-25.6.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring tbl2asn-25.6.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/tbl2asn/25.6: 4 files, 9.3MB
```
Try to run `brew update` first and then run `brew install funannotate` again.

**Comment by thebenallen** [comment]
Tried both `brew update` and `brew cleanup && brew update` then to install, but still getting same error. I'll keep searching around to see if there's another solution as well and will let you know if I find anything.

**Comment by nextgenusfs** [comment]
perhaps the taps are still messed up and you still have home-brew/science tapped?
`brew tap` should list the taps you have.  Should be:
```
brewsci/bio
brewsci/science
nextgenusfs/tap
```
Note you might have others.

**Comment by thebenallen** [comment]
Tapped into all of those but still same error unfortunately.

**Comment by thebenallen** [comment]
Success! I edited the tbl2asn .rb file and added the expected SHA256 hash and the rest of the install work as expected. Instructions for fix were here: https://thecoatlessprofessor.com/programming/updating-a-homebrew-formula/
