### ISSUE TITLE
Repeats database retrieval error 

### ISSUE THREAD

**Issue by thebenallen** [nextgenusfs/funannotate#165]
I've been able to get all of the dependencies and databases setup so far except for the repeats database. 

When I run `funannotate setup -d /Users/b8a/Bioinfotools/Databases -i repeats --update`

I get the following error:

> Traceback (most recent call last):
>   File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 445, in <module>
>     repeatDB(DatabaseInfo, args.force)
>   File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 233, in repeatDB
>     download(lib.DBURL.get('repeats'), fasta+'.tar.gz')
>   File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 67, in download
>     u = urllib2.urlopen(url)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
>     '_open', req)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
>     context=self._context)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
>     raise URLError(err)
> urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>

Appears related to this issue: https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version

**Comment by nextgenusfs** [comment]
Hmmm, not seen this one before.  I just re-ran on my system and it seemed to work fine. But I'm also running the current tip repository not a release..
```
$ funannotate setup -i repeats -d /usr/local/share/funannotate -f
-------------------------------------------------------
[May 02 04:02 PM]: OS: MacOSX 10.13.4, 8 cores, ~ 17 GB RAM. Python: 2.7.11
[May 02 04:02 PM]: Running funannotate v1.3.0-092e243
[May 02 04:02 PM]: Database location: /usr/local/share/funannotate
[May 02 04:02 PM]: Downloading Repeat database
[May 02 04:02 PM]: Downloading: https://osf.io/vp87c/download?version=1 Bytes: 6325661
[May 02 04:02 PM]: Building diamond database
[May 02 04:02 PM]: Repeat Database: version=1.0 date=2018-05-02 records=11,950
[May 02 04:02 PM]: Funannoate setup complete. Add this to ~/.bash_profile or ~/.bash_aliases:

	export FUNANNOTATE_DB=/usr/local/share/funannotate

```
So maybe there is a problem with the link in the home-brew release.

**Comment by nextgenusfs** [comment]
I don't see any differences in the links for v1.2 and the tip repository - can you try to run the command above and then output the entire terminal error so I can see where it is erring?

**Comment by thebenallen** [comment]
`MacBook-Pro-2:~ b8a$ funannotate setup -i repeats -d /Users/b8a/Bioinfotools/Databases -f
-------------------------------------------------------
[May 02 04:43 PM]: OS: MacOSX 10.11.6, 8 cores, ~ 17 GB RAM. Python: 2.7.11
[May 02 04:43 PM]: Running funannotate v1.2.0
[May 02 04:43 PM]: Database location: /Users/b8a/Bioinfotools/Databases
[May 02 04:43 PM]: Downloading Repeat database
Traceback (most recent call last):
  File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 445, in <module>
    repeatDB(DatabaseInfo, args.force)
  File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 233, in repeatDB
    download(lib.DBURL.get('repeats'), fasta+'.tar.gz')
  File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>`

**Comment by nextgenusfs** [comment]
Seems like maybe your ssl python needs maybe to be upgraded/rebuilt.  Can you try this:
```
pip install requests[security]
```

**Comment by thebenallen** [comment]
Ran that command and also `pip install openssl` but still getter the same:

```
$ pip install requests[security]
Requirement already satisfied: requests[security] in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (2.9.1)
Collecting pyOpenSSL>=0.13; extra == "security" (from requests[security])
  Downloading https://files.pythonhosted.org/packages/79/db/7c0cfe4aa8341a5fab4638952520d8db6ab85ff84505e12c00ea311c3516/pyOpenSSL-17.5.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 522kB/s 
Collecting ndg-httpsclient; extra == "security" (from requests[security])
  Downloading https://files.pythonhosted.org/packages/4b/a1/73ba15c5e56be36f184b0eabf7ea0873ea54022238313757e55781e8a2ad/ndg_httpsclient-0.5.0-py2-none-any.whl
Collecting pyasn1; extra == "security" (from requests[security])
  Downloading https://files.pythonhosted.org/packages/ba/fe/02e3e2ee243966b143657fb8bd6bc97595841163b6d8c26820944acaec4d/pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 1.1MB/s 
Requirement already satisfied: six>=1.5.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pyOpenSSL>=0.13; extra == "security"->requests[security]) (1.10.0)
Collecting cryptography>=2.1.4 (from pyOpenSSL>=0.13; extra == "security"->requests[security])
  Downloading https://files.pythonhosted.org/packages/58/c1/23bea66007d4be75ce02056fac665f9a207535e89fb3c7931420fa4a5f57/cryptography-2.2.2-cp27-cp27m-macosx_10_6_intel.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 825kB/s 
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=2.1.4->pyOpenSSL>=0.13; extra == "security"->requests[security])
  Downloading https://files.pythonhosted.org/packages/7e/4a/b647e46faaa2dcfb16069b6aad2d8509982fd63710a325b8ad7db80f18be/cffi-1.11.5-cp27-cp27m-macosx_10_6_intel.whl (238kB)
    100% |████████████████████████████████| 245kB 4.3MB/s 
Requirement already satisfied: enum34; python_version < "3" in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from cryptography>=2.1.4->pyOpenSSL>=0.13; extra == "security"->requests[security]) (1.1.2)
Collecting asn1crypto>=0.21.0 (from cryptography>=2.1.4->pyOpenSSL>=0.13; extra == "security"->requests[security])
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 612kB/s 
Collecting idna>=2.1 (from cryptography>=2.1.4->pyOpenSSL>=0.13; extra == "security"->requests[security])
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 1.4MB/s 
Collecting ipaddress; python_version < "3" (from cryptography>=2.1.4->pyOpenSSL>=0.13; extra == "security"->requests[security])
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyOpenSSL>=0.13; extra == "security"->requests[security])
  Downloading https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 833kB/s 
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /Users/b8a/Library/Caches/pip/wheels/c0/a1/27/5ba234bd77ea5a290cbf6d675259ec52293193467a12ef1f46
Successfully built pycparser
Installing collected packages: pycparser, cffi, asn1crypto, idna, ipaddress, cryptography, pyOpenSSL, pyasn1, ndg-httpsclient
Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.2.2 idna-2.6 ipaddress-1.0.22 ndg-httpsclient-0.5.0 pyOpenSSL-17.5.0 pyasn1-0.4.2 pycparser-2.18
MacBook-Pro-2:~ b8a$ funannotate setup -d /Users/b8a/Bioinfotools/Databases -i repeats --update
-------------------------------------------------------
[May 02 05:14 PM]: OS: MacOSX 10.11.6, 8 cores, ~ 17 GB RAM. Python: 2.7.11
[May 02 05:14 PM]: Running funannotate v1.2.0
[May 02 05:14 PM]: Database location: /Users/b8a/Bioinfotools/Databases
[May 02 05:14 PM]: Checking for newer versions of database files
[May 02 05:14 PM]: Downloading Repeat database
Traceback (most recent call last):
  File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 445, in <module>
    repeatDB(DatabaseInfo, args.force)
  File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 233, in repeatDB
    download(lib.DBURL.get('repeats'), fasta+'.tar.gz')
  File "/usr/local/Cellar/funannotate/1.2.0/libexec/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
```

**Comment by thebenallen** [comment]
I wonder, is there any way to install the database from local if I have the tar.gz file?

**Comment by nextgenusfs** [comment]
Yeah you can do it manually, just wondering why it doesn't work... what is your output of 
```
$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.3.0-092e243
-------------------------------------------------------
You are running Python v 2.7.11. Now checking python packages...
biopython: 1.68
goatools: 0.7.11
matplotlib: 2.1.1
natsort: 5.2.0
numpy: 1.12.1
pandas: 0.22.0
psutil: 5.4.3
requests: 2.18.4
scikit-learn: 0.19.1
scipy: 1.0.1
seaborn: 0.8.1
All 11 python packages installed
.
.
.
```

**Comment by nextgenusfs** [comment]
Maybe upgrading the requests library?  I moved to minconda python awhile ago - which seems to handle the dependencies better than pip and a bit easier to use - although looks like you have everything from the Python side at least. Eventually I want to make a funannotate conda recipe but too many dependencies not in anaconda yet.
```
pip install -U requests
```

**Comment by nextgenusfs** [comment]
I can give you instructions on how to manually install the repeats, but I have a hard time believing that everything else was working and just that one failed --- they all use the same download function.  But if that is the case, i.e. if the following command runs to completion then can just manually install the repeat database.
```
funannotate setup -i merops uniprot dbDAN pfam go mibig interpro busco_outgroups gene2product -d /your/path/ -u
```

**Comment by thebenallen** [comment]
I ran the above successfully, minus the `busco_outgroups` because it gave the same `[SSL: TLSV1_ALERT_PROTOCOL_VERSION]` error as repeats

```
$ funannotate setup -i merops uniprot dbCAN pfam go mibig interpro gene2product -d /Users/b8a/Bioinfotools/Databases
-------------------------------------------------------
[May 03 11:32 AM]: OS: MacOSX 10.11.6, 8 cores, ~ 17 GB RAM. Python: 2.7.11
[May 03 11:32 AM]: Running funannotate v1.2.0
[May 03 11:32 AM]: Database location: /Users/b8a/Bioinfotools/Databases
[May 03 11:32 AM]: Downloading Merops database
[May 03 11:32 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1942655
[May 03 11:32 AM]: Building diamond database
[May 03 11:32 AM]: MEROPS Database: version=12.0 date=2017-10-04 records=4,968
[May 03 11:32 AM]: Downloading UniProtKB/SwissProt database
[May 03 11:33 AM]: Downloading: ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz Bytes: 87826374
[May 03 11:34 AM]: Downloading: ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt Bytes: 151
[May 03 11:34 AM]: Building diamond database
[May 03 11:34 AM]: UniProtKB Database: version=2018_04 date=2018-04-25 records=557,275
[May 03 11:34 AM]: Downloading dbCAN database
[May 03 11:34 AM]: Downloading: http://csbl.bmb.uga.edu/dbCAN/download/dbCAN-fam-HMMs.txt Bytes: 84280707
[May 03 11:34 AM]: Downloading: http://csbl.bmb.uga.edu/dbCAN/download/FamInfo.txt Bytes: 62494
[May 03 11:34 AM]: Downloading: http://csbl.bmb.uga.edu/dbCAN/download/readme.txt Bytes: 6940
[May 03 11:34 AM]: Creating dbCAN HMM database
[May 03 11:34 AM]: dbCAN Database: version=6.0 date=2017-09-12 records=585
[May 03 11:34 AM]: Downloading Pfam database
[May 03 11:34 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.hmm.gz Bytes: 257664436
[May 03 11:36 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.clans.tsv.gz Bytes: 304729
[May 03 11:36 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam.version.gz Bytes: 115
[May 03 11:36 AM]: Creating Pfam HMM database
[May 03 11:36 AM]: Pfam Database: version=31.0 date=2017-02 records=16,712
[May 03 11:36 AM]: Downloading GO Ontology database
[May 03 11:36 AM]: Downloading: http://purl.obolibrary.org/obo/go.obo Bytes: 36582665
[May 03 11:37 AM]: GO ontology version=2018-04-30 date=2018-04-30 records=47,167
[May 03 11:37 AM]: Downloading MiBIG Secondary Metabolism database
[May 03 11:37 AM]: Downloading: http://mibig.secondarymetabolites.org/MIBiG_prot_seqs_1.3.fasta Bytes: 16287563
[May 03 11:51 AM]: Building diamond database
[May 03 11:51 AM]: MiBIG Database: version=1.3 date=2018-05-03 records=24,085
[May 03 11:51 AM]: Downloading InterProScan Mapping file
[May 03 11:51 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro.xml.gz Bytes: 26872522
[May 03 11:51 AM]: InterProScan XML: version=68.0 date=2018-04-26 records=33,947
[May 03 11:51 AM]: Downloaded curated gene names and product descriptions
[May 03 11:51 AM]: Downloading: https://raw.githubusercontent.com/nextgenusfs/gene2product/master/ncbi_cleaned_gene_products.txt Bytes: 984797
[May 03 11:51 AM]: Gene2Product: version=1.7 date=2018-05-02 records=25,008
[May 03 11:51 AM]: Funannoate setup complete. Add this to ~/.bash_profile or ~/.bash_aliases:

	export FUNANNOTATE_DB=/Users/b8a/Bioinfotools/Databases

MacBook-Pro-2:~ b8a$ funannotate database

--------------------------------------------------------------
Funannotate Databases currently installed:
--------------------------------------------------------------
Database       Type      Version      Date         Num_Records   Md5checksum                       
pfam           hmmer3    31.0         2017-02      16712         3e47eec766a99b599cb24f28c4d393f8  
gene2product   text      1.7          2018-05-02   25008         f98be0954ef54ff83104214fb9f30cff  
interpro       xml       68.0         2018-04-26   33947         dedefd8bcecaee4dc07a57b7ba43d09d  
dbCAN          hmmer3    6.0          2017-09-12   585           3cb06f6f93c72a56c9fa12a6294b41d5  
merops         diamond   12.0         2017-10-04   4968          d923f0177c6d27c3d2886c705347adc0  
mibig          diamond   1.3          2018-05-03   24085         84b3cd16e0b3b074e4b7ee18c6aa31fd  
uniprot        diamond   2018_04      2018-04-25   557275        b3e6aa9a2d1a57a8f81411959f6e4314  
go             text      2018-04-30   2018-04-30   47167         66beedc1cfb39093e8b7be0697b20e32  
--------------------------------------------------------------

To update a database type:
	funannotate setup -i DBNAME -d /Users/b8a/Bioinfotools/Databases --force

```

**Comment by nextgenusfs** [comment]
Okay, thanks that's helpful.  So both of those "databases" I serve on OSF.io.  So must be something with their server setup and for some reason your python installation -- which doesn't make a ton of sense.  But here is manual instructions (note that if manual install they won't show up in the `funannotate database` command but scripts should function).

Move into the $FUNANNOTATE_DB directory and then run these:

For the buscos you can just download and extract:
```
wget -O busco_outgroups.tar.gz https://osf.io/r9sne/download?version=1
tar -zxf busco_outgroups.tar.gz
```
For the repeats the headers need to be fixed, so a few more steps
```
wget -O funannotate.repeat.proteins.fa https://osf.io/vp87c/download?version=1
tar -zxf funannotate.repeat.proteins.fa.tar.gz
sed 's/#/_/g' funannotate.repeat.proteins.fa | sed 's,/,-,g' | sed 's/&//g' > funannotate.repeats.reformat.fa
diamond makedb --in funannotate.repeats.reformat.fa --db repeats -parse_seqids
```

```

**Comment by nextgenusfs** [comment]
Just following up, did you end up getting this sorted out?

**Comment by thebenallen** [comment]
Hello again! Sorry for radio silence. Taking another crack at this. My issue now is that when I run
`diamond makedb --in funannotate.repeats.reformat.fa --db repeats -parse_seqids`

I get this: 
` diamond v0.9.21.122 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: funannotate.repeats.reformat.fa
Opening the database file...  [0.000604s]
Loading sequences...  [0.000434s]
Error: Inflate error.
 `
I'm investigating to see how I might overcome the inflate error but any advice would be appreciated.

**Comment by thebenallen** [comment]
Thought that limiting the CPU threads might help but no luck.

**Comment by nextgenusfs** [comment]
The file isn't gzipped is it?
http://megan.informatik.uni-tuebingen.de/t/inflate-error-running-diamond/380

**Comment by nextgenusfs** [comment]
But it could also be a malformed FASTA file (perhaps that is more likely).

**Comment by thebenallen** [comment]
Yup looks like running 

`wget -O funannotate.repeat.proteins.fa https://osf.io/vp87c/download?version=1`

Yields a garbled FASTA file. I downloaded the file directly and it looks correct. Will try the other steps with that one.

**Comment by thebenallen** [comment]
Was able to successfully build the repeats.dmnd database and get both it and the BUSCO outgroups folder into the database directory. When I try `funannotate predict` on my FASTA file I get:

```
[Jun 09 05:42 PM]: OS: MacOSX 10.11.6, 8 cores, ~ 17 GB RAM. Python: 2.7.11
[Jun 09 05:42 PM]: Running funannotate v1.2.0
[Jun 09 05:42 PM]: ERROR: dikarya busco database is not found, install with funannotate setup -b dikarya
```

Strangely, when I run `funannotate setup -i busco_outgroups`it shows the busco_outgroups database as being installed:

```
[Jun 09 05:55 PM]: OS: MacOSX 10.11.6, 8 cores, ~ 17 GB RAM. Python: 2.7.11
[Jun 09 05:55 PM]: Running funannotate v1.2.0
[Jun 09 05:55 PM]: Database location: /Users/b8a/Bioinfotools/Databases
[Jun 09 05:55 PM]: BUSCO outgroups: version=12.0 date=2017-10-04 records=4,968
```

**Comment by nextgenusfs** [comment]
It’s looking for ‘dikarya’ folder in your funannotate database folder

**Comment by thebenallen** [comment]
Ok, I think I've gotten nearly everything in place. Only exception now is that I'm struggling with one final dependency, "gmes_petap.pl"

When I run `funannotate predict` I get "Missing Dependencies: gmes_petap.pl"

I've downloaded GeneMark-ES / ET v.4.33, placed the gmes_petap folder in /usr/local/ and ran: 
`export GENEMARK_PATH=/usr/local/gmes_petap/gmes_petap.pl`

and I still get the "Missing Dependencies: gmes_petap.pl" error

When I run 
`funannotate check --show-versions`
it does show the path as exported.

Any advice as to why it can't find the gmes_petap.pl? Worth noting that I did download the Mac version of GeneMark-ES / ET v.4.33. Do I need Linux build?

**Comment by hyphaltip** [comment]
I believe you want 
```export GENEMARK_PATH=/usr/local/gmes_petap/```

**Comment by thebenallen** [comment]
Tried that too but still getting the same result :/

**Comment by thebenallen** [comment]
Thanks for all your help. For now, I took a different route and went through the docker installation and it's working well.
