### ISSUE TITLE
initial busco evm run uses non buscos.bed intersected versions of Genemark etc

### ISSUE THREAD

**Issue by zzaheridor** [nextgenusfs/funannotate#17]
Just wonder.
https://github.com/nextgenusfs/funannotate/blob/master/bin/funannotate-predict.py#L710
Do You really want to use non-intersected version of Exonerate and Transcripts
instead of busco_proteins and busco_transcripts.
Sorry for such a stupid question :)

Great tool! Thank You :)

**Comment by nextgenusfs** [comment]
No you are right, that is a mistake (copy and paste from a different module), those should be the busco_transcripts/proteins.  Although it is unlikely to matter in the next step we run EVM followed by the BUSCO protein HMM scan to only pull out only those models, but I will make the fix and push the fix in the next update.  Thanks for catching it!

**Comment by zzaheridor** [comment]
Welcome )
