### ISSUE TITLE
Funnannotate Clean -cpus?

### ISSUE THREAD

**Issue by PlantDr430** [nextgenusfs/funannotate#176]
I know you created this with haploids in mind and have tried to speed up the pace of the program, but why can't we allocate more cores towards the job? I see that you can allocate more cores for the predict and annotate features, but not the clean? Is there any chance this will be added in the future?

**Comment by nextgenusfs** [comment]
Right now it works by sorting contigs from shortest to longest and then uses mummer and a 'leave-one-out' strategy to determine if duplicated, so it removes the shortest scaffold and then searches that against the rest, if duplicated it gets dropped as it loops through all the scaffolds. So the method right now isn't very amendable for multiple cores.  I tried to switch to minimap2 awhile ago and didn't get similar results, but I think that the right settings in minimap2 just need to be found, that would speed it up considerably.  The minimap2 method is still in the code, you could try it by passing `--method minimap2`.

**Comment by PlantDr430** [comment]
Okay, I think I found another way around it. Since it only uses like 1-2 cores I just open up multiple screens and within each screen I run a separate instance with a different genome. I already got most done over night instead of trying to loop a script and have it complete one genome at a time.

**Comment by VidJa** [comment]
Instead of mummer, may I suggest minimap2? In my experience it is faster than Mummer. https://github.com/lh3/minimap2

**Comment by nextgenusfs** [comment]
Yup -- as I said above, `minimap2` has been built into the script for a long time.

**Comment by nextgenusfs** [comment]
`minimap2` is now default in `funannotate clean`, this can be changed using the `--method` flag.
