### ISSUE TITLE
Anyone test the pipeline with a well annotated strain?

### ISSUE THREAD

**Issue by iwangtoknow** [nextgenusfs/funannotate#178]
Hello,

Any one test funannotate with a well annotated strain such as those reference isolates in fungidb.org/fungidb?

And what's the result.
How much identity should be normal between funannotated and manually annotated genome?
Thanks.

**Comment by hyphaltip** [comment]
Jon has done this for Neurospora w some new rnaseq and has numbers. I'll let him send out but depends on how you count isoforms in the accuracy.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by iwangtoknow** [comment]
Thank you, Sir.

**Comment by nextgenusfs** [comment]
There isn't a straight forward answer to this - as it is more of a problem with for a given genome annotation we really don't know what is "correct".  For example, there is still a debate on the number of genes in humans... But as @hyphaltip says, how "accurate" depends on what metrics you want to use. We will provide some examples in the funannotate paper (hopefully in the next month or so), but you can use some of the utilities in funannotate to check for your self, i.e. in newer versions of funannotate there is a command called `funannotate util compare` which will compare annotations to a reference.  You can pass multiple annotations to this script and it will compare them step-wise to the reference and then output a summary. 
```
$ funannotate util compare

Usage:       funannotate util <arguments>
version:     1.4.0-98c44b5

Description: Compare annotations to reference. Annotations in either GBK or GFF3 format.
    
Arguments:   -r, --reference            Reference Annotation. GFF3 or GBK format
             -f, --fasta                Genome FASTA. Required if GFF3 used
             -q, --query                Annotation query. GFF3 or GBK format
             -o, --output               Output basename
             -c, --calculate_pident     Measure protein percent identity between query and reference
```
I will try to get the docs updated to reflect some of these new tools.  But here you can pass several GFF3/GBK files to the `--query` option. 


Below are some results from `funannotate v1.1.3` - these numbers will change slightly when newest version is used.  And remember that the "reference" here is actually a fairly old annotation of N. crassa and we don't know what the "correct" answer is. 

Stats | Reference | Maker2 (RNA-seq) | funannotate (base) | funannotate (RNA-seq)**
-- | -- | -- | -- | --
Total Genes | 10,398 | 9,054 | 9,681 | 10,215
Coding Genes | 9,730 | 8,644 | 9,343 | 9,892
Coding transcripts | 10,785 | 8,644 | 9,343 | 10,312
tRNA Genes | 415 | 410 | 338 | 323
tRNA transcripts | 415 | 410 | 338 | 323
Identical CDS | 0 | 5,180 | 4,952 | 5,815
Avg mRNA AED* | 0 | 0.266 | 0.286 | 0.267
Avg CDS AED* | 0 | 0.201 | 0.151 | 0.156
Protein pident | - | 87.10% | 89.80% | 92.30%
Run Time (12 cores) | - | ~72 hrs | ~8 hrs | ~13 hrs
NCBI errors | - | 788 | 1 | 0

**Comment by hmontenegro** [comment]
Sorry to ask here, but it seems there isn't a discussion group for funannotate, is there? My question is related to annotation: how many "hypothetical proteins" vs annotated genes one should expect? After gene prediction and annotation, I end up with 13776 "hypothetical protein" and 2212 proteins with diverse annotations. Is this expected? I somehow expected the proportion of annotated proteins would be higher.

**Comment by nextgenusfs** [comment]
That is about how many I would expect.  Depends on the organism, but unless you are resequencing a model organism that has extensive annotations, the majority of proteins aren’t named and don’t have formal descriptions. Funannotate is conservative with gene names and descriptions because it’s aim is to be able to submit to genbank, which tightly controls gene naming/descriptions. The other inherent issue relates to how much information should be gleaned from only primary sequence homology - I tend to err on the conservative side as identify thresholds differ between orthologous groups making assignment on a whole genome challenging as well as a potential problem of incorrect annotation spreading through automated annotation pipelines. I sort of think that there should be some experimental data required to infer a function - hence a name/description.

**Comment by iwangtoknow** [comment]
Thanks, John,
Let me close this issue.

**WANG**
