### ISSUE TITLE
augustus_parallel.py: slow hints file slicing

### ISSUE THREAD

**Issue by zzaheridor** [nextgenusfs/funannotate#18]
Problem:
I have a huge ~ 1.7m contigs fasta for annotation (awfully assembled, nonetheless).
And hints splicing is painfully slow.

I'm using concurrent.futures python package and had no time to patch/test setup whatever now.
If you don't mind, I'll merge it lately. As for now patched version is attached.

Contig splitting parallelisation makes low sence (in the pacthed version), but as for hints splitting -- it'll be great to read them once :)

As ever, sorry for stupid question and for pasting it like file not via github.
[augustus_parallel.patched.py.gz](https://github.com/nextgenusfs/funannotate/files/406532/augustus_parallel.patched.py.gz)

Great tool :)

**Comment by nextgenusfs** [comment]
Great!  Thanks, I will give it a try.  Yes, I couldn't figure out a way to read the hints file once and parse into chunks as it is sometimes not sorted correctly.  It may work fine to not split the hints file at all?  But perhaps getting it sorted correctly by contig:start-stop position would allow a single read of the hints file.  I'm not familiar with the concurrent.futures package but will have a look.  Do you see increased speed with the fix in the attached script?

**Comment by zzaheridor** [comment]
1) not splitting hints. well, i don't know. I suppose augustus will ignore uknown contigs, but not sure.
2) sorting. do augustus need sorted hints by chr start end? in the patched version i'm using dict with lists with lines for contig.
3) It seems to be faster. mostly due to not greping hits file for each contig.

Thanks!

**Comment by zzaheridor** [comment]
just looked into extrinsicinfo.cc (augustus):
2245 void FeatureCollection::readGFFFile(const char *filename){
uses
2298                     psfc->addFeature(f);
which seems to insert features in the sorted / proper way on its own:

hints.cc:
577 /*
578  * HintGroup::addFeature
579  * put the feature at the right place: sorted increasingly by end positions
580  */
581 void HintGroup::addFeature(Feature *hint){
582     if (hints == NULL) {
583         hints = new list<Feature*>;
584         name = hint->groupname;
585     }
586 // TODO. This could be more efficient when the list is traversed from the end
587     list<Feature*>::iterator fit = hints->begin();
588     while(fit != hints->end() && (*fit)->end < hint->end)
589         fit++;
590     hints->insert(fit, hint);
591     // if feature is genic then reset begin and end if neccessary
592     // nongenic features: irpartF, nonexonpartF
593     if (begin < 0 || begin > hint->start)
594         begin = hint->start;
595     if (end < 0 || end < hint->end)
596         end = hint->end;
597     if (hint->type != irpartF && hint->type != nonexonpartF) {
598         if (geneBegin <0 || geneBegin > hint->start)
599             geneBegin = hint->start;
600         if (geneEnd <0 || geneEnd < hint->end)
601             geneEnd = hint->end;
602     }
603     if (hint->priority > priority)
604         priority = hint->priority;
605     if (hint->mult > copynumber)
606       copynumber = hint->mult;
607 }


I'm talking about augustus-3.2.2/src .
Sorry for off-top.

**Comment by nextgenusfs** [comment]
Thanks.  I will run some tests of just using the complete hints file vs splitting it up.  If there is no difference in processing time, then no point in intersecting the hints file - which should dramatically speed up if large genomes.  I work primarily on fungi, so typically genome sizes of ~ 30 Mb, so I had not tested with much larger genomes so any other areas where you can find a speed enhancement would be helpful.  Augustus versions are another problem, as depending on the version of Linux and/or Mac you are on, there are either problems with compilation or problems with the PPX functionally used by BUSCO.

**Comment by zzaheridor** [comment]
ok. it'll be great )

**Comment by nextgenusfs** [comment]
So looks like it results are the same if you pass the entire hints file to augustus for each 'chunk' versus splitting the hints file up and passing to augustus.  I tested with the current `augustus_parallel.py` script and got real time of 16 minutes with the old way (split hints) and 15 minutes with passing the entire hints file each time (~30 Mb, 557 contigs, using 6 cpus).  I got an error with your patched script on multiprocessor splitting of the contig files, I don't have time to troubleshoot it right now, but I updated `augustus_parallel.py` to skip slicing the hints file.  Let me know if that speeds it up for you.

**Comment by zzaheridor** [comment]
Thaks!
btw, what was the error?

**Comment by nextgenusfs** [comment]
An undefined variable in the get_ranges function.
```
Traceback (most recent call last):
  File "/Users/jon/Downloads/augustus_parallel.patched.py", line 121, in <module>
    (start, end) = get_ranges(part, chunks, contiglength)
NameError: name 'part' is not defined
```

**Comment by zzaheridor** [comment]
oops. sorry.
there should be
    (start, end) = get_ranges(i, chunks, contiglength)
