### ISSUE TITLE
Installing Error Augustus

### ISSUE THREAD

**Issue by BiodeB** [nextgenusfs/funannotate#181]
I was trying to install Augustus in Ubuntu 16.04. However I have followed (http://bioinf.uni-greifswald.de/augustus/binaries/README.TXT) for installation but stuck in between the steps,

-htslib
   -bcftools
   -tabix
   -samtools
   For bam2wig, these four packages must be installed from github. An installation via Ubuntu packages is not sufficient.
   See detailed installation & compilation instructions at auxprogs/bam2wig/README.TXT
   Also, the environment variable TOOLDIR (directory in which htslib, bcftools, tabix and samtools reside) must be exported:
   export TOOLDIR=/path/where/dependencies/reside
   Compiling utrrnaseq requires Boost library >Boost_1_49_0.  For Ubuntu e.g. install with
      sudo apt-get install libboost-all-dev

> sudo make

Error Output:

bam2wig.c:18:17: fatal error: sam.h: No such file or directory
compilation terminated.
Makefile:33: recipe for target 'bam2wig.o' failed
make[2]: *** [bam2wig.o] Error 1
make[2]: Leaving directory '/home/ub/softwares/augustus-3.3.1/auxprogs/bam2wig'
Makefile:7: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ub/softwares/augustus-3.3.1/auxprogs'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2

Hoping for good suggestion.

**Comment by nextgenusfs** [comment]
You can look at how I did it in the docker build https://github.com/nextgenusfs/funannotate/blob/master/dockerbuild/Dockerfile-base.  But I also couldn't get bam2wig to build --> but funannotate doesn't use that script.  The Augustus authors rarely provide any support or help.

```
#first need to build bamtools
wget https://github.com/pezmaster31/bamtools/archive/v2.5.0.tar.gz
tar -zxvf v2.5.0.tar.gz
rm v2.5.0.tar.gz
mv bamtools-2.5.0 bamtools
cd bamtools
mkdir build
cd build
cmake .. 
make
sudo make install
cd /usr/include
sudo ln -f -s ../local/include/bamtools/
cd /usr/lib/
sudo ln -f -s /usr/local/lib/bamtools/libbamtools.* . 

#install augustus, change to make file to comment out bam2wig as it wouldn't build
wget http://bioinf.uni-greifswald.de/augustus/binaries/augustus-3.3.1.tar.gz
tar -zxvf augustus-3.3.1.tar.gz
rm augustus-3.3.1.tar.gz
mv augustus-3.3.1 augustus
cd augustus
sed -i 's/	cd bam2wig; make/	#cd bam2wig; make/g' /home/linuxbrew/augustus/auxprogs/Makefile
make clean
make
```

**Comment by BiodeB** [comment]
Thank you so much for the suggestion. I'll surely try funannotate; I would like to enquire you that is it good for invertebrate metazoan species?
Though for Augustus I was following your steps but 
```
$ sudo ln -f -s ../local/include/bamtools/
ln: ./bamtools: cannot overwrite directory
```

**Comment by BiodeB** [comment]
Okay, 3 files namely  libbamtools.a, libbamtools.so and libbamtools.so.2.4.0 are present in the /usr/lib/

**Comment by nextgenusfs** [comment]
Okay, then you should be okay with just installing Augustus as the makefiles should then find bamtools. Just comment out the `bam2wig` command.

**Comment by BiodeB** [comment]
Thank you Jon, finally I'm able to install Augustus .

**Comment by chiu-shenpo** [comment]
@nextgenusfs thanks for the advice cuz i was facing the same problem while installing the Augustus.
