### ISSUE TITLE
hmmsearch for Pfam assignment

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#182]
Is there a reason you are using a hardcutoff of 1e-50 for the pfam searches and not just using the Gathering Threshold that is estimated for each Pfam domain HMM? eg using the --cut_ga option?

**Comment by nextgenusfs** [comment]
No reason... I didn't know about `--cut_ga`, so was trying to make sure it was a real hit.

**Comment by nextgenusfs** [comment]
If you use `--cut_ga` does that mean that all of the output passes the threshold?

This is the current call to hmmsearch:
```
cmd = ['hmmsearch', '--domtblout', pfam_out, '--cpu', '1', '-E', '1e-50', HMM, input]
```
So this should be just like this?
```
cmd = ['hmmsearch', '--domtblout', pfam_out, '--cpu', '1', --cut_ga HMM, input]
```
And then drop the `evalue` filtering when processing the results?

**Comment by hyphaltip** [comment]
I believe it is the 'right' thing to do so you don't need an arbitrary high cutoff - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3245129/#__sec16title
That said you probably also get these same domains in Interpro search so maybe not missing much anyways.

**Comment by nextgenusfs** [comment]
Okay, I will check what difference it has on PFAM assignment in Neurospora -- if looks good I will update the pfam method.  Close to pushing v1.4.0 so might as well make this change.

**Comment by nextgenusfs** [comment]
Okay, well with previous method on ~ 5400 yeast proteins had 1800 PFAM annotations. If I use the `--cut_ga` and then turn off Evalue filtering, there are 7402 PFAM annotations. This seems too high to me, but they are S. cerevisiae.  In both cases, I'm still filtering that the hit must be at least 50% of the length of HMM model.  I don't feel strongly about this one way or the other, so I'm fine including more PFAM annotations.

**Comment by nextgenusfs** [comment]
https://github.com/nextgenusfs/funannotate/commit/e6d9f552f048852c8302692028f1559ba91c5fd7
