### ISSUE TITLE
3' partial when codon_start=3

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#184]
Jon - I'm noticing that I get 3' partial marked CDS/mRNA/genes when the codon_start=3 is case - this is rare so is only a handful of genes but appears in gene sets when this is the case. I suspect these are sub-part gene calls anyways but they need to be fixed to pass tbl2asn and submissions. I am manually fixing these but seems like there is a step upstream in the .tbl generation which is causing this. Any ideas where to look?

`BS091_001258	Got stop codon, but 3'end is labeled partial`

**Comment by nextgenusfs** [comment]
Yeah I have seen this occasionally, typically only 1 or 2 gene models per genome and haven't been able to trace the problem. Good to know that it seems to be only codon_start=3 -- how about orientation (+/-)? The function that parses the GFF3 and turns into tbl file is here: 
https://github.com/nextgenusfs/funannotate/blob/e6d9f552f048852c8302692028f1559ba91c5fd7/lib/library.py#L2202

It looks like I'm relying on an EVM script to generate the protein translations - which are then used to determine if proper stop codon exists or not.  I think this might be a "bug" in this EVM script, if I remember correctly it searches for the "best" translation (which I think is longest) and does not translate the exact coordinates of gene model (it is maybe off for these partial models that have codon_start=3). I think I can re-write this to translate the proteins on the fly as the GFF3 coordinates are processed, maybe that will fix problem.

**Comment by nextgenusfs** [comment]
Okay, this still works the same locally for me https://github.com/nextgenusfs/funannotate/commit/284c6dbdc9fc8d62fae45ee698f17e61c845ec6f.  I replaced EVM script generating proteins (as I think that might have been problem) and then added translation to GFF3 parsing to check for proper starts/stops.  Let me know if this fixes it.  It is a little bit slower during tbl file generation due to translation, but needs to be getting correct start/stops.

**Comment by hyphaltip** [comment]
Well my latest attempt at submission is basically passing tbl2asn locally but a submit give these errors:


```ERROR: valid [SEQ_FEAT.SuspiciousFrame] Suspicious CDS location - reading frame > 1 but not 5' partial FEATURE: CDS: hypothetical protein <207>  [(lcl|scaffold_7:c23621-23531, c23487-23040, c22988-22789, c22717-22619, c22567-22378, c22330-22160, c22091-21582, c21539-<21366)] [lcl|scaffold_7: delta, dna len= 23639] -> [gnl|ncbi|CU098_011980-T1]
```

**Comment by nextgenusfs** [comment]
Yeah that is what the script is suppose to be doing, basically each model gets loaded as partial and then gets set to 5' "full-length" if codon_start == 1 and starts with methionine (as you could still have partial with codon_start == 1.  I will look through the code again and see if I can find any discrepencies. 

Those errors aren't in any of the tbl2asn discrepancy report or the genome.val?  Or are there there and funannotate isn't parsing them correctly?

**Comment by nextgenusfs** [comment]
Can you see if https://github.com/nextgenusfs/funannotate/commit/5e1ddb4d22ed563be0d4df1df52ca997a5fa668a is yielding same results.  I tried to unify the tbl generation function -- basically over time these things have evolved as originally didn't support multiple transcripts, etc.  I think this should now be working -- where all annotation is loaded into "funannotate annotation dictionary" and that is then written to tbl format with one function (so should be easier to track any errors/bugs).

**Comment by hyphaltip** [comment]
Still there  - I can see all these errors in annotate_misc/tbl2asn/genome.val - note these are not called out in the funannotate log so may want to think about reporting more

This is a fragmented assembly which I know is driving these but should still be able to create proper gene models here. I'm not seeing the 5' partial annotation being applied.  I'll note these errors don't seem to be in the predict_misc/tbl2asn/genome.val so I not sure where/why the flags are coming up different.

Did you basically re-write GAG into funannotate? 


`ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: hypothetical protein [(lcl|scaffold_5040:c>724-445, c390-307, c258-106, c52-15)] [lcl|scaffold_5040: raw, dna len= 819] -> [gnl|ncbi|CU097_000374-T1]
ERROR: valid [SEQ_FEAT.SuspiciousFrame] Suspicious CDS location - frame > 1 but not 5' partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5045:c787-572, c515-<242)] [lcl|scaffold_5045: raw, dna len= 816] -> [gnl|ncbi|CU097_002025-T1]
ERROR: valid [SEQ_FEAT.PartialProblem] Got stop codon, but 3'end is labeled partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5045:c787-572, c515-<242)] [lcl|scaffold_5045: raw, dna len= 816] -> [gnl|ncbi|CU097_002025-T1]
ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: hypothetical protein [lcl|scaffold_5049:c>711-30] [lcl|scaffold_5049: raw, dna len= 812] -> [gnl|ncbi|CU097_000872-T1]
ERROR: valid [SEQ_FEAT.StartCodon] Illegal start codon used. Wrong genetic code [1] or protein should be partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5054:c762-657, c611-<295)] [lcl|scaffold_5054: raw, dna len= 809] -> [gnl|ncbi|CU097_002167-T1]
ERROR: valid [SEQ_FEAT.PartialProblem] Got stop codon, but 3'end is labeled partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5054:c762-657, c611-<295)] [lcl|scaffold_5054: raw, dna len= 809] -> [gnl|ncbi|CU097_002167-T1]
ERROR: valid [SEQ_INST.BadProteinStart] gap symbol at start of protein sequence (CU097_002167 - hypothetical protein) BIOSEQ: gnl|ncbi|CU097_002167-T1: raw, aa len= 140
ERROR: valid [SEQ_FEAT.SuspiciousFrame] Suspicious CDS location - frame > 1 but not 5' partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5088:c767-240, c185-<17)] [lcl|scaffold_5088: raw, dna len= 783] -> [gnl|ncbi|CU097_000455-T1]
ERROR: valid [SEQ_FEAT.PartialProblem] Got stop codon, but 3'end is labeled partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5088:c767-240, c185-<17)] [lcl|scaffold_5088: raw, dna len= 783] -> [gnl|ncbi|CU097_000455-T1]
ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: hypothetical protein [lcl|scaffold_5090:c>624-76] [lcl|scaffold_5090: raw, dna len= 782] -> [gnl|ncbi|CU097_001364-T1]
ERROR: valid [SEQ_FEAT.StartCodon] Illegal start codon used. Wrong genetic code [1] or protein should be partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5100:c753-638, c564-477, c424-<356)] [lcl|scaffold_5100: raw, dna len= 776] -> [gnl|ncbi|CU097_002348-T1]
ERROR: valid [SEQ_FEAT.PartialProblem] Got stop codon, but 3'end is labeled partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5100:c753-638, c564-477, c424-<356)] [lcl|scaffold_5100: raw, dna len= 776] -> [gnl|ncbi|CU097_002348-T1]
ERROR: valid [SEQ_INST.BadProteinStart] gap symbol at start of protein sequence (CU097_002348 - hypothetical protein) BIOSEQ: gnl|ncbi|CU097_002348-T1: raw, aa len= 90
ERROR: valid [SEQ_FEAT.SuspiciousFrame] Suspicious CDS location - frame > 1 but not 5' partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5125:c637-475, c450-<181)] [lcl|scaffold_5125: raw, dna len= 758] -> [gnl|ncbi|CU097_001854-T1]
ERROR: valid [SEQ_FEAT.PartialProblem] Got stop codon, but 3'end is labeled partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5125:c637-475, c450-<181)] [lcl|scaffold_5125: raw, dna len= 758] -> [gnl|ncbi|CU097_001854-T1]
ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: Negative regulator of mitotic exit [(lcl|scaffold_5130:c>699-232, c178-151, c97-20)] [lcl|scaffold_5130: raw, dna len= 757] -> [gnl|ncbi|CU097_000571-T1]
ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: hypothetical protein [(lcl|scaffold_5154:c>608-303, c234-80)] [lcl|scaffold_5154: raw, dna len= 739] -> [gnl|ncbi|CU097_001391-T1]
ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: hypothetical protein [lcl|scaffold_5159:c>184-10] [lcl|scaffold_5159: raw, dna len= 736] -> [gnl|ncbi|CU097_000085-T1]
ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: hypothetical protein [lcl|scaffold_5173:c>266-86] [lcl|scaffold_5173: raw, dna len= 731] -> [gnl|ncbi|CU097_001420-T1]
ERROR: valid [SEQ_FEAT.StartCodon] Illegal start codon used. Wrong genetic code [1] or protein should be partial FEATURE: CDS: hypothetical protein [lcl|scaffold_5180:c704-<411] [lcl|scaffold_5180: raw, dna len= 727] -> [gnl|ncbi|CU097_002469-T1]
ERROR: valid [SEQ_FEAT.PartialProblem] Got stop codon, but 3'end is labeled partial FEATURE: CDS: hypothetical protein [lcl|scaffold_5180:c704-<411] [lcl|scaffold_5180: raw, dna len= 727] -> [gnl|ncbi|CU097_002469-T1]
ERROR: valid [SEQ_INST.BadProteinStart] gap symbol at start of protein sequence (CU097_002469 - hypothetical protein) BIOSEQ: gnl|ncbi|CU097_002469-T1: raw, aa len= 97
ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: hypothetical protein [lcl|scaffold_5194:c>450-239] [lcl|scaffold_5194: raw, dna len= 722] -> [gnl|ncbi|CU097_002014-T1]
ERROR: valid [SEQ_FEAT.SuspiciousFrame] Suspicious CDS location - frame > 1 but not 5' partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5207:c689-613, c319-216, c162-<114)] [lcl|scaffold_5207: raw, dna len= 715] -> [gnl|ncbi|CU097_001623-T1]
ERROR: valid [SEQ_FEAT.PartialProblem] Got stop codon, but 3'end is labeled partial FEATURE: CDS: hypothetical protein [(lcl|scaffold_5207:c689-613, c319-216, c162-<114)] [lcl|scaffold_5207: raw, dna len= 715] -> [gnl|ncbi|CU097_001623-T1]
ERROR: valid [SEQ_FEAT.NoStop] Missing stop codon FEATURE: CDS: hypothetical protein [(lcl|scaffold_5219:c>375-214, c186-32)] [lcl|scaffold_5219: raw, dna len= 707] -> [gnl|ncbi|CU097_000925-T1]
ERROR: valid [SEQ_FEAT.StartCodon] Illegal start codon used. Wrong genetic code [1] or protein should be partial FEATURE: CDS: Mitochondrial succinate-fumarate transporter [(lcl|scaffold_5221:c649-403, c346-<123)] [lcl|scaffold_5221: raw, dna len= 705] -> [gnl|ncbi|CU097_001662-T1]
ERROR: valid [SEQ_FEAT.PartialProblem] Got stop codon, but 3'end is labeled partial FEATURE: CDS: Mitochondrial succinate-fumarate transporter [(lcl|scaffold_5221:c649-403, c346-<123)] [lcl|scaffold_5221: raw, dna len= 705] -> [gnl|ncbi|CU097_001662-T1]`

**Comment by hyphaltip** [comment]
Here are the predict_misc and annotate_misc tbl2asn folders for comparison. tbl files also show the input and .val files show the errors.

Putting these up here - still exploring if I can see what changes are needed.
[predict_misc.zip](https://github.com/nextgenusfs/funannotate/files/2152386/predict_misc.zip)
[annotate_misc.zip](https://github.com/nextgenusfs/funannotate/files/2152391/annotate_misc.zip)

**Comment by nextgenusfs** [comment]
Okay, well the problem seems to be that the 5' partial and 3' partial data is being parsed incorrectly during `funannotate annotate`.  I'm not sure why yet though, is the predict step run with an old version of `funannotate` and then annotate being run with a newer version?  For a bit there there were some problems with the tbl output from predict -- but I think that is all fixed now.  Can you look at the `annotate_misc/genome.tbl` file and see if that matches the one in `predict_results/genome.tbl` -- note that the tbl file is re-generated from the GBK file at the moment (so I think this is where error is).  Give me a minute and I will update that function to use the unified tbl writing function (I'm thinking this should fix the problem).

**Comment by hyphaltip** [comment]
Originally it was older version with predict but I deleted the evm files in predict_misc so I assume was regenerating. 

I can give a try with pushed changes let me know.

**Comment by hyphaltip** [comment]
Let me know what I should rm to make sure it runs clean.

**Comment by nextgenusfs** [comment]
You should be able to just re-run predict with same command - as the tbl file gets re-generated each run.  Testing the updated tbl writing now - if that doesn't fix than it must be error in gbk parser.

**Comment by nextgenusfs** [comment]
Okay.  Well there are a few things.  I updated the gb2parts function which parses the genbank input file and then write to tbl, proteins, transcripts, etc (I think this is where error was).  One of the problems/limitations with genbank format is that for multiple transcripts there is currently no way to properly link the mRNA transcript to the CDS -- so I updated to just re-use (copy over) the tbl file from `predict_results` or `update_results` instead of regenerating these files. The function will still generate tbl file for multiple transcripts -- there is just a chance that the mRNA/CDS may not be properly linked. 

Because I've changed some other things in predict -- if you re-run predict then there is a chance your protein models may change -- so you would have to re-run a fresh funannotate annotate then to make sure there aren't any mistakes. 

Let me know if this commit fixes these issues or not. https://github.com/nextgenusfs/funannotate/commit/041f5c5a83a279772eb0932ebfd0595165fe8e6b

**Comment by hyphaltip** [comment]
Yeah okay. I expected to have to rerun annotate anyways. Will try in few hrs.

Seems cleaner to only rely on genbank file at end but use tbl as much as possible as primary Storage for gene structure and annotation anyways so I’m happy to hear that change.

The road is littered with previous genbank to gff3 parsing scripts in bioperl and others so it’s not an ideal format for going back and forth in the annotation storage.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by nextgenusfs** [comment]
I've run some tests by doing the following:

1) running `funannotate annotate` using `-i folder_name` which will just copy over the `tbl` file from `update_results` or `predict_results`
2) running `funannotate annotate` using `--genbank update_results/genome.gbk` which will generate `tbl` file using `gb2parts` function
3) running `funannotate annotate` using `--gff3 update_results/genome.gff3 --fasta update_results/genome.scaffolds.fa` which will generate `tbl` file using `convertgff2tbl` function.

These two functions `gb2parts` and `convertgff2tbl` were updated to use the unified parsers as well as `dicts2tbl` function (which writes the tbl) file.  It seems like all three of these inputs resulted in same results for me locally.  So I hope this is fixed.  

When you have time to confirm then I think I will cut a new release -- as there is an unrelated but fairly important bug fix in mapping transcripts in previous versions I'd like to get fixed ASAP.

**Comment by hyphaltip** [comment]
okay seems to be fixing it properly now. 

I see only warnings about start not matching for a gene 
`WARNING: valid [SEQ_FEAT.PartialProblem] PartialLocation: Start does not include first/last residue of sequence FEATURE: tRNA: Ser [lcl|scaffold_34:<16692->16773] [lcl|scaffold_34: delta, dna len= 16807]
WARNING: valid [SEQ_FEAT.PartialProblem] PartialLocation: Stop does not include first/last residue of sequence FEATURE: tRNA: Ser [lcl|scaffold_34:<16692->16773] [lcl|scaffold_34: delta, dna len= 16807]
`
for this tRNA feature 
`16692   16773   gene
                        locus_tag       CU098_013986
<16692  >16773  tRNA
                        product tRNA-Ser
`

Should the tRNA gene location also match the tRNA as partial? This is a warning not and error so maybe not important for tRNAs?

**Comment by nextgenusfs** [comment]
Default is to make all tRNA partial as I think that results in fewer errors during submission. Otherwise they are validated somehow, which I didn’t think was hugely important.

**Comment by hyphaltip** [comment]
Okay that seems fine then, I'm rerunning functional predictions and will try a new submission at NCBI to see if these pass - seem to pass locally now at least.

**Comment by hyphaltip** [comment]
Jon - the 
but the tRNA errors are real and get flagged at NCBI as fatal:
```
ERROR: valid [SEQ_FEAT.PartialProblem5Prime] Start does not include first/last residue of sequence FEATURE: tRNA: Ser <936>  [lcl|scaffold_34:<16692->16773] [lcl|scaffold_34: delta, dna len= 16807]```

I think this is just because the tRNA gene needs to be partial not exact?

So 
```
<16692  >16773  gene
                        locus_tag       CU098_013986
<16692  >16773  tRNA
                        product tRNA-Ser
```
instead of what is in the current tbl file
```
16692  16773  gene
                        locus_tag       CU098_013986
<16692  >16773  tRNA
                        product tRNA-Ser
```

**Comment by nextgenusfs** [comment]
Ok, https://github.com/nextgenusfs/funannotate/commit/574d27121219524e1888d5e1a9f130574aaa1bbd should fix it.

**Comment by hyphaltip** [comment]
what step I need to re-run - hopefully not re-annotate everything ... ?

**Comment by nextgenusfs** [comment]
Should be able to just re-issue same command - it should re-use all the annotation data and just regenerate the tbl file and subsequent tbl2asn command.
