### ISSUE TITLE
Question about GeneMark

### ISSUE THREAD

**Issue by PlantDr430** [nextgenusfs/funannotate#185]
Hello,

This really isn't an issue, but I had a question about the default GeneMark setting in Funannotate predict. I noticed that the --soft-mask was set to 5000. Is there a way to change this setting from the command line with a flag or something?

**Comment by nextgenusfs** [comment]
At the moment there isn't a way as it is hard coded, but I can make it an option.

**Comment by PlantDr430** [comment]
Okay, in my opinion it would be nice as an option. I like that the pipeline uses GeneMark on the soft-maked genome, but feel that 5000 is quite large. Therefore, I am debating whether to run repeatmodeler and GeneMark beforehand to alter the soft-mask option and then just use those files for the funannotate input. This is all do-able, but adding a flag option in the future might save some time if others are interesting in altering that parameter as well.

**Comment by nextgenusfs** [comment]
https://github.com/nextgenusfs/funannotate/commit/51c8aa622576815dc25da143bbd7d208ef9fd066 added in this commit.  It will be included in next release, which I hope to get out very soon.

**Comment by nextgenusfs** [comment]
Note... I'm not usually this fast, but was getting close to a release so thought I would add it before I forgot.  Default is taken from BRAKER settings at 5kb (so meaning won't run GeneMark on soft masked sequences < 5 kb in length).  Its difficult to get reliable annotation predictions on short contigs even if they aren't repetitive. In some of my tests I didn't see a whole lot of difference between GeneMark runs when you modify this parameter, but you can now adjust to whatever you like with `--soft_mask` flag.

**Comment by PlantDr430** [comment]
Yes, I understand. I guess it was just great timing of when I asked :) Thanks for adding it, I look forward to the update.

**Comment by nextgenusfs** [comment]
`--soft_mask` added in v1.4.0 and default changed to 2000 in v1.4.1.
