### ISSUE TITLE
funannotate-predict.py: bedtools intersect fails -- negative starts

### ISSUE THREAD

**Issue by zzaheridor** [nextgenusfs/funannotate#19]
Hello!
https://github.com/nextgenusfs/funannotate/blob/master/bin/funannotate-predict.py#L658
bedtools says starts less then 1

**Comment by nextgenusfs** [comment]
Thanks, will fix shortly.  I'm at a conference but can push these changes later today - I won't do a full release until I know it is stable, but should be able to just clone the repository.

And I appreciate the help in finding bugs!

**Comment by zzaheridor** [comment]
welcome %)

**Comment by zzaheridor** [comment]
to be serious, You've done a great work.
btw what is the way to reference funannotate?

**Comment by nextgenusfs** [comment]
Thanks.  Right now you can cite the github repo I guess:  something like
```
Palmer JM. 2016. Funannotate: a fungal genome annotation and comparative genomics pipeline. https://github.com/nextgenusfs/funannotate.
```

I pushed some updates to predict to fit this negative location in bedtools, if you get an error on the other end (which you might) it might be a bit longer of a fix, but doable.

**Comment by zzaheridor** [comment]
Thank You.
I supposed when intersecting bedtools didn't know anything about contigs sizes.
Though it's possible to get errors when extracting sequences :(

**Comment by nextgenusfs** [comment]
Yes, I just need to load the contig names and sizes into a dictionary and make sure that the coordinates don't go outside those parameters. that should be a more stable fix

**Comment by nextgenusfs** [comment]
Okay, just pushed a fix.  Not sure of stability yet, running the test now, but most likely is okay.

**Comment by zzaheridor** [comment]
thank you
