### ISSUE TITLE
Funannotate fix 'too many values to unpack"

### ISSUE THREAD

**Issue by PlantDr430** [nextgenusfs/funannotate#191]
I finished a prediction on an older version (1.3.2) and got a message about needing to fix a part of the .tbl output file. I've done this before and have used the "fix" command successfully before, but now when I am trying to run it I get an error of "ValueError: too many values to unpack".

stephenwyka@bspmgenomics:/data/wyka/funannotate/Batch_2/Cfusi$ funannotate fix -i Cfusi_fun_output/predict_results/Claviceps_fusiformis_PRL_1980.gbk -t Cfusi_fun_output/predict_results/Claviceps_fusiformis_PRL_1980.tbl
-------------------------------------------------------
[10:28 PM]: OS: linux2, 24 cores, ~ 264 GB RAM. Python: 2.7.12
[10:29 PM]: Running funannotate v1.3.2-3ba4c2e
Traceback (most recent call last):
  File "/data/linuxbrew/.linuxbrew/Homebrew/Cellar/funannotate/1.3.2/libexec/util/updateGBK.py", line 62, in <module>
    locustag, genenum, justify = lib.getGBKLocusTag(args.input)
  File "/data/linuxbrew/.linuxbrew/Homebrew/Cellar/funannotate/1.3.2/libexec/lib/library.py", line 2293, in getGBKLocusTag
    tag, count = lastTag.split('_')
ValueError: too many values to unpack

**Comment by PlantDr430** [comment]
Oh okay, I manually changed it as I wanted two underscores in the locus tag. I guess I'll have to change it back. If you get the time could you also look at this SNAP gff3 file that I have. It took a while to figure out how to get SNAP outputs into gff3 format. I finally did, but now when I use the --other_gff <filename>:<weight> it tells me that the gff3 file is not a valid file.  I've attached the file as a .txt

stephenwyka@bspmgenomics:/data/wyka/funannotate/snap_runs/LM4_snap$ nice -n 19 /data/bin/funannotate-1.4.0/funannotate predict -i LM4A_assembly_masked.fasta -o LM4C_longaugustus_fun_output -s "Claviceps purpurea" --isolate LM4C --protein_evidence ../../../../../home/stephenwyka/Pconf.fasta --cpus 20 --busco_seed_species Claviceps_purpurea --busco_db sordariomyceta_odb9 --name LM4C\_FUN --min_protlen 100 --optimize_augustus --soft_mask 1000 --other_gff LM4_snap.gff3:1 
-----------------------------------------------------------------
[09:48 AM]: OS: linux2, 24 cores, ~ 264 GB RAM. Python: 2.7.12
[09:48 AM]: Running funannotate v1.4.0-90e1680
[09:48 AM]: AUGUSTUS (3.2.2) detected, version seems to be compatible with BRAKER and BUSCO
[09:48 AM]: LM4_snap.gff3:1 is not a valid file, exiting


[LM4_snap.gff3.txt](https://github.com/nextgenusfs/funannotate/files/2163775/LM4_snap.gff3.txt)

**Comment by nextgenusfs** [comment]
Sure I will take a look. There should be some snap2gff scripts out there @hyphaltip do you recall any?  I will make this script support the multiple underscores, it will just split on the last one. Probably get it updated tomorrow.

**Comment by PlantDr430** [comment]
yea I actually had to do a zff to gff3 (which wasn't gff3), but then found a converter from that gff to an actual gff3 file.

**Comment by nextgenusfs** [comment]
The `--other_gff` files need to pass EvidenceModeler validator, that script is located in `$EVM_HOME/EvmUtils/gf3_gene_prediction_file_validator.pl`. So run that script on your GFF3 file and see what errors it is giving you.  I'd be surprised that the SNAP-to-gff3.pl isn't give you compatible output?

**Comment by PlantDr430** [comment]
That's what I thought. Especially since the script comes with EvidenceModeler. I'll run the validator later and  see where that gets me. Thanks for the help.

**Comment by PlantDr430** [comment]
So I ran the validator and got no errors.

```
swyka430@swyka-ubuntu:/Wyka/bioinformatics/LM4$ perl ../../../usr/local/bin/EVidenceModeler-1.1.1/EvmUtils/gff3_gene_prediction_file_validator.pl LM4_snap.gff3 
swyka430@swyka-ubuntu:/Wyka/bioinformatics/LM4$ 
```

I also ran it with an incorrect gff version to make sure it was working and I got errors. 

```
swyka430@swyka-ubuntu:/Wyka/bioinformatics/LM4$ perl ../../../usr/local/bin/EVidenceModeler-1.1.1/EvmUtils/gff3_gene_prediction_file_validator.pl LM4_snap_wronggff3.gff3 
Use of uninitialized value $feature_info in pattern match (m//) at ../../../usr/local/bin/EVidenceModeler-1.1.1/EvmUtils/gff3_gene_prediction_file_validator.pl line 54, <$fh> line 3.
Fatal Error: cannot parse ID from entry
contig_1	snap	CDS	7191	7196	.	-	Name=contig_1-snap.1 at ../../../usr/local/bin/EVidenceModeler-1.1.1/EvmUtils/gff3_gene_prediction_file_validator.pl line 54, <$fh> line 3.
```
So I don't know why Funannotate is having trouble with the correct LM4_snap.gff3 file.

**Comment by nextgenusfs** [comment]
So it seems to be passing for me locally as well, what was the command that you issued to `funannotate predict` and then the error that it gives you?  Maybe I'm looking in the wrong place.

**Comment by nextgenusfs** [comment]
Oh... I think I see the problem.  Did you pass a weight for this file, i.e. `--other_gff LM.gff3:1`?

**Comment by PlantDr430** [comment]
Yea, I ran a weight `--other_gff LM4_snap.gff3:1 ` you can see it at the end of my command line in the previous post.

**Comment by nextgenusfs** [comment]
Okay, https://github.com/nextgenusfs/funannotate/commit/da6734e12f0dd177a8a473c6b306b8a43f173766 should fix it.  The error was that the file couldn't be found in a previous check because there is a colon in the name (that needed to be fixed).

**Comment by PlantDr430** [comment]
Okay, thanks for looking into this. I'll let me admin know to update to the latest version once a new update comes out.

**Comment by nextgenusfs** [comment]
In the meantime it should work to just leave off the `:1`, it will default to a value of 1 automatically.

**Comment by PlantDr430** [comment]
Cool, I'll give that a shot

**Comment by PlantDr430** [comment]
So I got it to work without putting the weight. Quick question, if I have multiple .gff3 files from other predictors can I just list them after `--other_gff` (i.e. `--other_gff snap.gff3 cegma.gff3` ). Or should I try to just combine them into one file?

**Comment by nextgenusfs** [comment]
Right now `--other_gff` can only take a single file as input. So you'll have to combine them into a single file, I've not tried this, but I think it should work -- might be a problem with overlapping/similar annotations but I'm not sure.

**Comment by PlantDr430** [comment]
Ahh that make sense. That will probably be a problem, thanks for the quick reply.

**Comment by nextgenusfs** [comment]
This issues should be fixed in v1.4.1 -- reopen if you experience any related problems.

**Comment by kmkocot** [comment]
I am having a similar issue as originally described above with the test feature in funannotate v1.8.4. I installed funannotate using pip and to the best of my knowledge, all the dependencies are installed and working normally.

Command used: 
`funannotate test -t all --cpus 38`

Selected relevant output:
`#########################################################
Running `funannotate predict` unit testing
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 38 --species Awesome testicus
#########################################################
-------------------------------------------------------
[Feb 11 08:22 AM]: OS: Ubuntu 18.04, 40 cores, ~ 66 GB RAM. Python: 3.6.9
[Feb 11 08:22 AM]: Running funannotate v1.8.4
[Feb 11 08:22 AM]: Skipping CodingQuarry as no --rna_bam passed
[Feb 11 08:22 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pretrained     
  genemark     selftraining   
  glimmerhmm   busco          
  snap         busco          
[Feb 11 08:22 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Feb 11 08:22 AM]: Genome loaded: 6 scaffolds; 3,776,588 bp; 19.75% repeats masked
[Feb 11 08:22 AM]: Mapping 1,065 proteins to genome using diamond and exonerate
[Feb 11 08:22 AM]: Found 1,784 preliminary alignments --> aligning with exonerate
[Feb 11 08:22 AM]: Exonerate finished: found 1,428 alignments
[Feb 11 08:22 AM]: Running GeneMark-ES on assembly
[Feb 11 08:23 AM]: 1,533 predictions from GeneMark
[Feb 11 08:23 AM]: Running BUSCO to find conserved gene models for training ab-initio predictors
[Feb 11 08:23 AM]: Multi-threading in tblastn v2.6.0 is unstable, running in single threaded mode for BUSCO
[Feb 11 08:26 AM]: 373 valid BUSCO predictions found, validating protein sequences
[Feb 11 08:26 AM]: 370 BUSCO predictions validated
[Feb 11 08:26 AM]: Running Augustus gene prediction using saccharomyces parameters
[Feb 11 08:28 AM]: 1,492 predictions from Augustus
[Feb 11 08:28 AM]: Pulling out high quality Augustus predictions
[Feb 11 08:28 AM]: Found 371 high quality predictions from Augustus (>90% exon evidence)
[Feb 11 08:28 AM]: Running SNAP gene prediction, using training data: annotate/predict_misc/busco.final.gff3
[Feb 11 08:28 AM]: 1,516 predictions from SNAP
[Feb 11 08:28 AM]: Running GlimmerHMM gene prediction, using training data: annotate/predict_misc/busco.final.gff3
[Feb 11 08:29 AM]: 1,772 predictions from GlimmerHMM
[Feb 11 08:29 AM]: Summary of gene models passed to EVM (weights):
  Source         Weight   Count
  Augustus       1        1331 
  Augustus HiQ   2        372  
  GeneMark       1        1533 
  GlimmerHMM     1        1772 
  snap           1        1516 
  Total          -        6524 
[Feb 11 08:29 AM]: EVM: partitioning input to ~ 35 genes per partition
Traceback (most recent call last):
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 433, in <module>
    partitions=args.no_partitions)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 146, in create_partitions
    chr, start, end = line.split('\t')
ValueError: too many values to unpack (expected 3)
[Feb 11 08:29 AM]: Evidence modeler has failed, exiting
Traceback (most recent call last):
  File "/home/wirenia/.local/bin/funannotate", line 713, in <module>
    main()
  File "/home/wirenia/.local/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/predict.py", line 1780, in main
    os.remove(EVM_out)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wirenia/Desktop/funannotate_test/test-predict_e7c9f4d7-5764-4793-a40e-787cd143d4af/annotate/predict_misc/evm.round1.gff3'
#########################################################
Traceback (most recent call last):
  File "/home/wirenia/.local/bin/funannotate", line 713, in <module>
    main()
  File "/home/wirenia/.local/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 405, in main
    runPredictTest(args)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 161, in runPredictTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_testicus.gff3')) <= 1800
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-predict_e7c9f4d7-5764-4793-a40e-787cd143d4af/annotate/predict_results/Awesome_testicus.gff3'`

**Comment by nextgenusfs** [comment]
Looks like evidence modeler is not installed properly, check the log for for EVM for some hints. And would be better to open a new issue than add to one that is 3 years old.
