### ISSUE TITLE
This line expect transcripts to be of form LOCUS-T1

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#193]
https://github.com/nextgenusfs/funannotate/blob/574d27121219524e1888d5e1a9f130574aaa1bbd/lib/library.py#L1783

But you've changed the generation of .tbl files so they use the evm names not the LOCUS-T1 -- 
I have a simple patch attached - which just assumes transcripts are in order in the table file and so just counts up as they are seen?

[library.py.patch.txt](https://github.com/nextgenusfs/funannotate/files/2169330/library.py.patch.txt)

**Comment by nextgenusfs** [comment]
Should be fixed with v1.4.1 as these transcripts that fail a few checks are ignored.
