### ISSUE TITLE
tRNA cannot be partial

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#195]
Jon - this is the current error log from NCBI  when submitting a record from latest release - tRNAs cannot be partial

[1] The following issues persist:
=======================================================
tRNA should not be partial inside a sequence (see files posted on the 
portal). If you don't have their full sequence length, either annotate them as 
misc_feature (with no gene feature associated to them and no locus tag) or 
remove them.

SEQ_FEAT.PartialProblem5Prime           71
SEQ_FEAT.PartialProblem3Prime           71
=======================================================

**Comment by nextgenusfs** [comment]
Okay well I guess that’s perhaps new? So how do we determine full length tRNAs?

**Comment by nextgenusfs** [comment]
So they should all be full length? https://github.com/nextgenusfs/funannotate/commit/d74367adbeddcdf3773da3c0f0fbe0f5493d7183 this commit will make them full length -- want to see if that goes through?
