### ISSUE TITLE
Non-fungal genomes?

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/funannotate#2]
There has been some interest (at least 1 person...) that is interested in using funanntoate for non-fungal genome annotation.  Anybody else interested?  I could probably do something like: arthropods, vertebrate, metazoans, and fungi (essentially the BUSCO clades).  This would increase the DB files substantially....

**Comment by nextgenusfs** [comment]
as of `v0.3.0` non-fungal organisms might work.  In `funannotate predict` you can use the `--organism other` option to disable fungal specific prediction steps.  You can also use the `--busco_db` and `--eggnog_db` options to specify valid busco and eggnog databases.  If the local databases do not exist, funannotate will download and format them for you on the fly.

**Comment by abpatel2288** [comment]
I am planning for annotation of cattle genome, will it work this --organism other option ?
Do I need to modify any other database.

**Comment by nextgenusfs** [comment]
Hi @abpatel2288.  It potentially should work, although I have not tested it.  You will also want to adjust the `--busco_db`, `--busco_seed_species`, and `--max_intronlen`, if you do not have other data, such as RNA-seq/assembled transcriptome.  If you have a transcriptome and RNAseq reads, then `funannotate` will use `BRAKER1` to train `augustus`, however you should still specify the `--busco_db metazoa` to download the proper database.

See https://github.com/nextgenusfs/funannotate/issues/16 here for a related answer on arthropods.

**Comment by nextgenusfs** [comment]
support for non-fungal genomes is currently in alpha (i.e. I think it works but have not tested it).
