### ISSUE TITLE
funannotate-predict.py: final proteins not copied

### ISSUE THREAD

**Issue by zzaheridor** [nextgenusfs/funannotate#20]
https://github.com/nextgenusfs/funannotate/blob/master/bin/funannotate-predict.py#L999

hi!
is it ok? or just lost?

Thank You )

**Comment by nextgenusfs** [comment]
This is a relict from previous version where I was outputting proteins from the GAG tool, however, GAG sometimes has problems translating proteins in the reverse strand, thus I elected to just sort of remove it.  It would be trivial to add back in a translated proteins and transcribed transcripts if that would be useful output?

**Comment by zzaheridor** [comment]
IC
Thank You!
it's up to You.
No need in it  if it has a strange behavior.
Closing?

**Comment by nextgenusfs** [comment]
I just fixed this to output both proteins and transcripts, but not using GAG - just parsing the final GBK file.  Will be part of new release.

**Comment by zzaheridor** [comment]
Thanks!

**Comment by nextgenusfs** [comment]
fixed: https://github.com/nextgenusfs/funannotate/commit/9d6722d2e8c4dadbdb91d7cf931e391a7c9a42fe
