### ISSUE TITLE
Set up of partial CDS in genbank file

### ISSUE THREAD

**Issue by EricFournier3** [nextgenusfs/funannotate#201]
**Describe the bug**
In some case where CDS is partial, the annotation is incorrect. For example, this CDS annotation
CDS     complement(43..>363)

should be 
CDS     complement(<43..363)
instead. Because it is the 5' end on the **complement** that is partial (not the 3' end on the forward strand).

Is there a way to find and correct this bug ?
Thanks

**What command did you issue?**

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`
version 1.3.4

**Comment by EricFournier3** [comment]
i also note that in other case there is illigal start codon; for example 

 CDS             complement(<1847..2197)
                     /locus_tag="FUN_009172"
                     /codon_start=1
                     /product="hypothetical protein"
                     /protein_id="ncbi:FUN_009172-T1"
                     /translation="-
                     LASGSISFVSCSVSALRVTAQVIMSSSGGGGGGGGGGNVNINGNNYGTINASGGGGGG
                     GGSGSCNNGSGSGSGSGYGRDPVTGMTYRTTNGGANIDTDDYNRIVRSMGYPGVPGR"


     1801 ctctagtaag gccgagagca cccatagact tggagtcctc ctaagcctat cgtcctggga
     1861 cacctgggta gcccatggat cgaacaatcc ggttgtagtc gtctgtgtcg atgtttgcac
     1921 caccgttggt ggttcgatac gtcatgccag taaccggatc acgaccgtag ccgctgccac
     1981 tgccgctgcc actgccatta ttgcaactgc cactgccgcc gccgccgccg ccgccgccgc
     2041 tagcgttgat ggtaccgtag ttgttaccgt tgatattgac atttcctcca cctccacctc
     2101 cacctccacc tccactggaa gacattataa cttgagcggt aacccgaaga gctgaaactg
     2161 agcaagagac gaacgagatg gaaccggagg caaggaactg tcgagatgag taatagaaag

**Comment by nextgenusfs** [comment]
Yes please check with newest version. If same errors with newest release then will be helpful if you can pull out the GFF, tbl, and gbk annotations so we can try to figure out where the error is in the code.
