### ISSUE TITLE
Does running Augustus in parallel negatively affect gene prediction?

### ISSUE THREAD

**Issue by jpiechura** [nextgenusfs/funannotate#206]
In our efforts for gene prediction from prokaryotic genomes, we adopted a strategy of submitting scaffolds one at a time to the Prodigal gene predictor, modeled after the manner in which Augustus is runs in parallel in funannotate, one scaffold at a time. However, we found that for some bacteria, gene prediction suffers if run in parallel compared to giving prodigal the entire genome at once for gene prediction - for some bacteria, several thousand genes are not called if prodigal is run one scaffold at a time compared to submitting the whole genome at once. We presume this is because giving prodigal one scaffold at a time does not allow proper collection of intrinsic evidence from the genome sequence as a whole. Given this observation, we wonder if running Augustus in parallel might also suffer from this issue. 

Have you tested whether running Augustus in parallel gives the same results as running Augustus on all scaffolds at once, for several different fungi? Do you expect that Augustus can collect sufficient intrinsic evidence about the genome if given only one scaffold?

**Comment by nextgenusfs** [comment]
Training of Augustus is done before running it. The parallel script that runs Augustus yields identical results as running in entire genome. Speed is one reason to run in parallel but another is RAM usage can get very high on large scaffolds. So the input is actually chunked into overlapping parts if contig > 500kb. The results are then stitched back together with Augustus scripts, i.e. this isn’t something I came up with but developers of Augustus did.

**Comment by jpiechura** [comment]
Great, thank you for the info!
