### ISSUE TITLE
Conflicting recursive dependencies on Install

### ISSUE THREAD

**Issue by alishaquandt** [nextgenusfs/funannotate#207]
I'm currently doing a first install on a brand new Mac OS. I am doing the homebrew installation. I get through your instructions up until the actual install.

**Describe the bug**
brew install funannotate leads to the following error:
"==> Installing funannotate from nextgenusfs/tap
Error: nextgenusfs/tap/funannotate contains conflicting version recursive dependencies:
  mysql, mysql@5.7
View these with `brew deps --tree nextgenusfs/tap/funannotate`."

Thank you!
Alisha

**Comment by nextgenusfs** [comment]
Yes I’m aware of some problems with homebrew at the moment. Only solution right now is to install those packages one at a time I think before funannotate. I really want to get this on bioconda which will be easier for everyone.

**Comment by nextgenusfs** [comment]
The recipes causing the problem are blat and Kent-tools.

**Comment by MichaelFokinNZ** [comment]
so, the solution is just to install blat and Kent-tools first and re-run "brew install funannotate" after? or the opposite?

**Comment by MichaelFokinNZ** [comment]
or go with conda? :)

**Comment by nextgenusfs** [comment]
I’m out of office this week but I think would need to install one of those two tools manually perhaps and then pass ‘—without-blat’ to the ‘brew install funannotate’ command. Yes, or take Conda route or use docker, etc.

**Comment by MichaelFokinNZ** [comment]
any chance something changed for better?

**Comment by alishaquandt** [comment]
I tried to install using --without-blat. Now I'm getting an error about repeatmodeler not being located at the specified address. The specified URL is not found. I tried to talk to homebrew about this, and they couldn't help. Anybody else getting that error?
