### ISSUE TITLE
funannotate check --show-versions fails on "check_modules.py" checking external dependencies

### ISSUE THREAD

**Issue by robpowers1978** [nextgenusfs/funannotate#208]
**Are you using the latest release?**
Yes. 1.4.2

**Describe the bug**
funannotate check --show-versions fails on "check_modules.py" checking external dependencies

```
Checking external dependencies...
Traceback (most recent call last):
  File "/home/robpower/bin/funannotate-1.4.2/util/check_modules.py", line 262, in <module>
    ExtDeps[prog] = check_version6(prog)
  File "/home/robpower/bin/funannotate-1.4.2/util/check_modules.py", line 172, in check_version6
    return (vers)
UnboundLocalError: local variable 'vers' referenced before assignment
```
I have attempted to use an updated check_modules.py suggested by this post: https://github.com/nextgenusfs/funannotate/issues/183
with the code here:
https://github.com/nextgenusfs/funannotate/commit/14bae1cadf0cae70313cc08d8e160392cb9a65b6

but the problem persists.

**What command did you issue?**
 funannotate check --show-versions

**Logfiles**
N/A

**OS/Install Information**
This is running an an HPC/Flux cluster (to which I do not have sudo access). 
CentOS 7.4.1708

[flux-login3 funannotate-1.4.2]$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.4.2
-------------------------------------------------------
You are running Python v 2.7.14. Now checking python packages...
biopython: 1.68
goatools: 0.8.4
matplotlib: 2.2.2
natsort: 5.3.3
numpy: 1.11.3
pandas: 0.23.1
psutil: 5.4.6
requests: 2.14.2
scikit-learn: 0.19.1
scipy: 1.1.0
seaborn: 0.8.1
All 11 python packages installed

You are running Perl v 5.016003. Now checking perl modules...
Bio::Perl: 1.006001
Carp: 1.26
Clone: 0.38
DBD::SQLite: 1.58
DBD::mysql: 4.023
DBI: 1.636
DB_File: 1.838
Data::Dumper: 2.145
File::Basename: 2.84
File::Which: 1.21
Getopt::Long: 2.4
Hash::Merge: 0.300
JSON: 2.90
LWP::UserAgent: 6.15
Logger::Simple: 2.0
POSIX: 1.30
Parallel::ForkManager: 1.20
Pod::Usage: 1.63
Scalar::Util::Numeric: 0.40
Storable: 2.45
Text::Soundex: 3.04
Thread::Queue: 3.02
Tie::File: 0.98
URI::Escape: 3.31
YAML: 1.18
threads: 1.87
threads::shared: 1.43
All 27 Perl modules installed

Checking external dependencies...
Traceback (most recent call last):
  File "/home/robpower/bin/funannotate-1.4.2/util/check_modules.py", line 262, in <module>
    ExtDeps[prog] = check_version6(prog)
  File "/home/robpower/bin/funannotate-1.4.2/util/check_modules.py", line 172, in check_version6
    return (vers)
UnboundLocalError: local variable 'vers' referenced before assignment

**Comment by nextgenusfs** [comment]
Thanks.  Sorry about that 64068b7 should fix it.

**Comment by robpowers1978** [comment]
That fixed it. Thanks
