### ISSUE TITLE
funannotate-functional.py: AUGUSTUS for BUSCO

### ISSUE THREAD

**Issue by zzaheridor** [nextgenusfs/funannotate#21]
https://github.com/nextgenusfs/funannotate/blob/master/bin/funannotate-functional.py#L83

hi!
Stupid question.
Do You really need it? OGS mode ...

Thnx

**Comment by nextgenusfs** [comment]
Perhaps it is necessary to double check with OGS mode, I just want to be sure that the models coming out of this are in fact BUSCO models. Is this contributing to a long runtime?  For fungal genomes, this only adds about 2 minutes.

**Comment by nextgenusfs** [comment]
If my memory serves, I think in my testing I would sometimes have some "rogue" gene models that arise from the EVM command - but that could have been due to the copy/paste error I had before which you found :).

**Comment by nextgenusfs** [comment]
Still see some models that are not BUSCO models show up, so leaving in additional protein search
