### ISSUE TITLE
clean (v1.4.0) dropping reads less than it reports?

### ISSUE THREAD

**Issue by FatihSarigol** [nextgenusfs/funannotate#210]
Hi, thank you for funannotate!

This is what I did:

/funannotate-1.4.0/funannotate clean -i Input.fasta -o Output.fasta

This is what the log said:

41,195 input contigs, 41,194 larger than 500 bp, N50 is 84,371 bp
Checking duplication of 39,199 contigs shorter than N50
scaffold_40836 appears duplicated: 96% identity over 99% of the contig. contig length: 1003
...184 lines of these scaffolds reported in total
scaffold_19394 appears duplicated: 96% identity over 99% of the contig. contig length: 1708
41195 input contigs, 1811 duplicated, 41010 written to file

Indeed my output file has 41010 contigs now. 
So 1 is shorter than 500bp that gets dropped, and 184 contigs that were reported to be duplicated with their names in the log; makes perfect sense as it drops a total of 185.
Now I can continue with this 41010 contigs, but I wanted to ask about it because first of all the log says as you see 1811 duplicated; is that a bug maybe with doing the addition?

And secondly, I had started clean with a previous version, this is still running:

/funannotate-1.3.4/funannotate clean -i Input.fasta -o Output.fasta

At the moment it is comparing scaffold_23534 and the reference.fa has 38780 contigs in it, I assume it drops a contig on the go when it finds it to be duplicated and so it seems to have already found 2414 so far. I know these 2 versions use different programs for clean, so I wonder if you would expect this drastic difference between the 2, or perhaps was "1811 duplicated" log report of 1.4.0 correct but it only dropped 184 because of another bug? Or does "clean" drop reads from reference.fa for other reasons during the analysis as well and then at the end the cleaned file gets larger? Because I am pretty sure the reference.fa had become smaller while 1.4.0 was running, too, but the eventual output became larger.

ThankS!

**Comment by nextgenusfs** [comment]
I believe this is just an error in the number of reads that were reported -- the script is working as it should and outputting the correct contigs, but the numbers it was reporting are wrong.  The last few commits should fix that and will be fixed in next release.
