### ISSUE TITLE
Are input files for tutorial available

### ISSUE THREAD

**Issue by robertbjornson** [nextgenusfs/funannotate#212]
I'm a software support person for our compute clusters and am attempting to install funannote.  I see a tutorial on the website, http://funannotate.readthedocs.io/en/latest/tutorials.html but I don't see the input files being available for download.  It would be very helpful to have  the exact input files used in the tutorial as a way to validate my installation.  Could they be made available?

Thanks,

Rob

**Comment by ChrisBrownNZ** [comment]
Hi,
It would be good to have all the test files as you intend. Its disconcerting to have the tests fail.
Thanks
Chris
