### ISSUE TITLE
Different isoform in BUSCO assessment.

### ISSUE THREAD

**Issue by iwangtoknow** [nextgenusfs/funannotate#213]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**

**What command did you issue?**
Copy/paste the command used.
`$busco -i funannotate.proteins.fasta -c 10 -o funannotate -l fungi_odb9 -z -sp aspergillus_nidulans -m prot`
**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`

Hi Jon,
I use BUSCO to assess my annotate results.
![busco_figure](https://user-images.githubusercontent.com/35318350/44184482-e747f900-a141-11e8-9942-642b13940ff7.png)
**6frame.min10.code1** is the database I prepared for proteome MS protein discovery;
**funannotate.20180409** is the result of funannotate in genome mode only;
**funannotate.20180530** is the result of funannotate with short reads evidence;
**funannotate.20180727** is the result of funannotate added long reads evidence;

I checked the duplicated protein, they are all different isoforms of one gene.
```bash
grep Duplicated ./run_funannotate.20180727/full_table_funannotate.20180727.tsv
EOG092C0I1P	Duplicated	FUN_003147-T1	998.6	574
EOG092C0I1P	Duplicated	FUN_003147-T2	849.1	453
EOG092C0UR7	Duplicated	FUN_008851-T1	586.8	487
EOG092C0UR7	Duplicated	FUN_008851-T2	587.5	487
EOG092C0UR7	Duplicated	FUN_008851-T3	587.5	487
EOG092C1OUP	Duplicated	FUN_001782-T1	578.0	457
EOG092C1OUP	Duplicated	FUN_001782-T2	578.3	457
EOG092C1VMQ	Duplicated	FUN_006330-T1	504.4	369
EOG092C1VMQ	Duplicated	FUN_006330-T2	504.3	369
EOG092C1VMQ	Duplicated	FUN_006330-T3	499.0	351
EOG092C2S2R	Duplicated	FUN_009862-T1	207.5	274
EOG092C2S2R	Duplicated	FUN_009862-T2	177.5	230
EOG092C2SMS	Duplicated	FUN_007305-T1	205.2	199
EOG092C2SMS	Duplicated	FUN_007305-T2	207.2	198
EOG092C3703	Duplicated	FUN_003313-T1	472.8	389
EOG092C3703	Duplicated	FUN_003313-T2	426.8	359
EOG092C3DV0	Duplicated	FUN_008102-T1	299.4	247
EOG092C3DV0	Duplicated	FUN_008102-T2	276.3	233
EOG092C3DV0	Duplicated	FUN_008102-T3	301.0	247
EOG092C4JUE	Duplicated	FUN_008425-T1	367.6	227
EOG092C4JUE	Duplicated	FUN_008425-T2	367.6	227
EOG092C54JK	Duplicated	FUN_004661-T1	177.1	131
EOG092C54JK	Duplicated	FUN_004661-T2	172.8	131
EOG092C59CG	Duplicated	FUN_007458-T1	294.6	186
EOG092C59CG	Duplicated	FUN_007458-T2	294.6	186
EOG092C5KDG	Duplicated	FUN_005012-T1	254.0	144
EOG092C5KDG	Duplicated	FUN_005012-T2	264.5	152
```
Is there any problem? I mean these 'duplicated' isoforms should be single copied?

**WANG**

**Comment by nextgenusfs** [comment]
You have multiple transcripts per locus (you used RNA-seq which is good) -- here with the `-T1, -T2, -T3`, etc.  Thus they are showing up as duplicated. BUSCO isn't recognizing that and saying they are duplicated.  Am I missing something -- is that your question?

**Comment by iwangtoknow** [comment]
Yeah,thanks Jon. I got it.
