### ISSUE TITLE
Incorrect diamond command

### ISSUE THREAD

**Issue by hmontenegro** [nextgenusfs/funannotate#215]
Using funannotate v1.5.0 from the releases page, after running `funannotate train`, `funannotate predict` fails because it can't find "aug.blast.txt". I believe this happens due to a missing comma at line 5872 from file "lib/library.py"

``` cmd = ['diamond', 'blastp', '--query', 'augustus.training.proteins.fa', '--db', 'aug_training.dmnd', '--more-sensitive', '-o' 'aug.blast.txt', '-f', '6', 'qseqid', 'sseqid', 'pident', '--query-cover', '80', '--subject-cover', '80', '--id', '80', '--no-self-hits']```

Which results in the following diamond command:

```diamond blastp --query augustus.training.proteins.fa --db aug_training.dmnd --more-sensitive -oaug.blast.txt -f 6 qseqid sseqid pident --query-cover 80 --subject-cover 80 --id 80 --no-self-hits```

It should be `'-o', 'aug.blast.txt'` instead of `'-o' 'aug.blast.txt'`

**Comment by nextgenusfs** [comment]
Thanks. Yes there should be a comma there. What error did it give you and did adding the comma fix the issue?

**Comment by hmontenegro** [comment]
Sorry, I lost the exact error message, I overwrote the log. 

Yes, adding the comma fixed it. I ran into other issue, but unrelated to this one - missing CodingQuarry, which I forgot to install.

**Comment by nextgenusfs** [comment]
should be fixed in v1.5.1 -- reopen if error persists.

**Comment by dvera** [comment]
I still get this error with the latest docker image, even though the mentioned comma exists library.py (I also deleted library.pyc and reran).

**Comment by nextgenusfs** [comment]
I don’t think the docker image has been updated

**Comment by dvera** [comment]
Any chance you can update it, or provide instructions to create the tarballs it uses to build the container (e.g. funnotate-genemark)

**Comment by nextgenusfs** [comment]
I only build the new docker container when I cut a new release -- which I haven't had time to do recently.  I pushed a release today and the updated docker image is uploading now. Let me know if you run into any problems.

**Comment by dvera** [comment]
thanks!

**Comment by dvera** [comment]
The version reported in the latest docker image is still 1.5.0. Is this expected?

**Comment by nextgenusfs** [comment]
No. Then something wrong. So you ran docker pull nextgenusfs/funannotate?  And then proceeded to rebuild the funannotate image according to instructions?

**Comment by dvera** [comment]
Yes

**Comment by dvera** [comment]
Maybe this will be helpful. See the modify dates for ~/funannotate in the latest docker image

![image](https://user-images.githubusercontent.com/5902410/53694645-dbd7ba80-3d7f-11e9-8dd2-e9ba9619d247.png)

**Comment by nextgenusfs** [comment]
So that's not the most recent version....
```
$ docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
nextgenusfs/funannotate             latest              b8d8415f8745        7 days ago          7.78GB
```
Check your sha256:
```
$ docker pull nextgenusfs/funannotate
Using default tag: latest
latest: Pulling from nextgenusfs/funannotate
Digest: sha256:1bf9c8eca337012faaafc05cb9f3785875678c6cbcc9a512366f05b7294fe0dc
Status: Image is up to date for nextgenusfs/funannotate:latest
```
Note I've not built the entire version here -- just pulling the "base" version from docker. 
```
$ docker run -it --rm -v $PWD:/home/linuxbrew/data nextgenusfs/funannotate
linuxbrew@3eeeb23d5903:~$ funannotate 

Usage:       funannotate <command> <arguments>
version:     1.5.2

Description: Funannotate is a genome prediction, annotation, and comparison pipeline.
    
Command:     clean          Find/remove small repetitive contigs
             sort           Sort by size and rename contig headers
             mask           Repeatmask genome assembly
             
             train          RNA-seq mediated training of Augustus/GeneMark
             predict        Run gene prediction pipeline
             fix            Fix annotation errors (generate new GenBank file)
             update         RNA-seq/PASA mediated gene model refinement
             remote         Partial functional annotation using remote servers
             iprscan        InterProScan5 search (Docker or local)
             annotate       Assign functional annotation to gene predictions
             compare        Compare funannotated genomes
             
             util           Format conversion and misc utilities 
             setup          Setup/Install databases
             test           Download/Run funannotate installation tests       
             check          Check Python, Perl, and External dependencies
             species        list pre-trained Augustus species
             database       Manage databases             
             outgroups      Manage outgroups for funannotate compare
                          
Written by Jon Palmer (2016-2018) nextgenusfs@gmail.com
```
