### ISSUE TITLE
Ribosomal RNA

### ISSUE THREAD

**Issue by EricFournier3** [nextgenusfs/funannotate#216]
Can we annotate rRNA with the pipeline ?

Thanks
Eric

**Comment by hyphaltip** [comment]
I don't think there is a general tool for annotating rRNA from genomes that works so well. The ITSx tool has HMMs to id and extract SSU/LSU and ITS intervening. JGI has a sort of BLAST-based approach they use in their pipeline I believe.

I think a separate tool for rRNA annotation is needed first before focusing on integration into funannotate as process.

**Comment by EricFournier3** [comment]
ok thanks

**Comment by nextgenusfs** [comment]
To add to that, if you find a tool that works well we can integrate it - I would want it to be compatible with both Linux and macOS. 

Also, many times the rRNA array is not assembled correctly unless assembly done with long reads but even then likely requires some mania work. I have often removed the rRNA contigs from draft assemblies as I know they are incorrect.

**Comment by hyphaltip** [comment]
https://github.com/merenlab/anvio/blob/master/anvio/data/hmm/Ribosomal_RNAs/README.md
