### ISSUE TITLE
"GeneMark is not installed" when it is?

### ISSUE THREAD

**Issue by bdentinger** [nextgenusfs/funannotate#218]
**Are you using the latest release?**
v1.5.0

**Describe the bug**
When executing funannotate predict, I get this:
"GeneMark is not installed, proceeding with only Augustus ab-initio predictions"

But, GeneMark-ES is installed: gmes_petap.pl is in my PATH and executable and the GENEMARK_PATH ENV is exported.

I had problems with getting some dependencies working, notably I was unable to install DBD::MySql module in the homebrew version of perl using cpanm, so had to uninstall perl from brew and use the version in /usr/bin.

**What command did you issue?**
funannotate predict -i ../relabeled/species.relabeled.repeatmasked.fasta --cpus 72 -o species_annotated -s species --augustus_species coprinus_cinereus --transcript_evidence ../EST_clusters.fasta

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.5.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.72
goatools: 0.8.4
matplotlib: 2.2.3
natsort: 5.3.3
numpy: 1.15.1
pandas: 0.23.4
psutil: 5.4.7
requests: 2.19.1
scikit-learn: 0.19.2
scipy: 1.1.0
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.022001. Now checking perl modules...
Bio::Perl: 1.006924
Carp: 1.50
Clone: 0.39
DBD::SQLite: 1.50
DBD::mysql: 4.048
DBI: 1.641
DB_File: 1.835
Data::Dumper: 2.161
File::Basename: 2.85
File::Which: 1.19
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 2.97001
LWP::UserAgent: 6.35
Logger::Simple: 2.0
POSIX: 1.53_01
Parallel::ForkManager: 1.20
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 2.53_01
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.01
URI::Escape: 3.31
YAML: 1.26
threads: 2.21
threads::shared: 1.58
All 27 Perl modules installed

Checking external dependencies...
RepeatMasker: RepeatMasker 4.0.7
RepeatModeler: RepeatModeler 1.0.8
Trinity: 2.8.3
augustus: 3.3.1
bamtools: bamtools 2.5.1
bedtools: bedtools v2.27.1
blat: BLAT v36
diamond: diamond 0.9.22
ete3: 3.1.1
exonerate: exonerate 2.2.0
hisat2: 2.1.0
hmmscan: HMMER 3.1b2 (February 2015)
hmmsearch: HMMER 3.1b2 (February 2015)
java: 1.8.0_181
kallisto: 0.44.0
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.7.1+
minimap2: 2.12-r827
rmblastn: rmblastn 2.2.27+
samtools: samtools 1.9
stringtie: 1.3.4d
tRNAscan-SE: 1.3.1 (January 2012)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.7.1+
trimal: trimAl v1.4.rev15 build[2013-12-17]
        ERROR: CodingQuarry not installed
        ERROR: emapper.py not installed
        ERROR: fasta not installed
        ERROR: gmap not installed
        ERROR: gmes_petap.pl not installed
        ERROR: nucmer not installed
        ERROR: pslCDnaFilter not installed
Checking Environmental Variables...
$FUNANNOTATE_DB=/home/bdentinger/funannotate_db
$EVM_HOME=/home/linuxbrew/.linuxbrew/opt/evidencemodeler
$AUGUSTUS_CONFIG_PATH=/home/linuxbrew/.linuxbrew/opt/augustus/config
$GENEMARK_PATH=/home/bdentinger/gm_et_linux_64/gmes_petap/gmes_petap.pl
$BAMTOOLS_PATH=/home/linuxbrew/.linuxbrew/opt/bamtools/bin
        ERROR: PASAHOME not set. export PASAHOME=/path/to/dir
        ERROR: TRINITYHOME not set. export TRINITYHOME=/path/to/dir

**Comment by bdentinger** [comment]
Sorry, this is running on Ubuntu 16.04

**Comment by nextgenusfs** [comment]
There should be more info on what happened in `species_annotated/logfiles/funannotate-predict.log`.  Also, was this folder created `species_annotated/predict_misc/genemark/`?  

My first guess is that a `perl` dependency from GeneMark is not installed or isn't linked -- or the GeneMark key is not installed correctly. Try to run genemark on the contigs outside of funannotate, i.e.
```
gmes_petap.pl --ES --fungus --cpus 24 --sequence species.relabeled.repeatmasked.fasta
```
If there is a dependency problem it should spit it out to terminal.  The logging doesn't always capture the error messages correctly -- largely because the many dependencies don't output them the same.

**Comment by nextgenusfs** [comment]
And I see that I made a mistake in the docs.... $GENEMARK_PATH is only used if `gmes_petap.pl` is not in the $PATH, however, it is meant to point to the directory, not the script, i.e. that env var in your `~/.bashrc` should be:
```
export GENEMARK_PATH=/home/bdentinger/gm_et_linux_64/gmes_petap
```

**Comment by nextgenusfs** [comment]
Sorry to string responses -- but the output from `funannotate check --show-versions` is telling you that `gmes_petap.pl` is not properly installed.  As of v1.5.0 it will run without `genemark` as some users can't install `genemark` due to licensing issues.  So the original warning message is just to let you know that it will proceed with only `augustus` if `genemark` isn't present.

**Comment by nextgenusfs** [comment]
Looks like you have what you need to run `predict` without RNA-seq data.  Might need to refresh or re-source your `~/.bashrc` for the changes to take effect (or new terminal window)?  The `funannotate check` command is basically running the `which gmes_petap.pl` command -- so if that works then it should be showing up as "installed" unless there is a missing dependency or running `gmes_petap.pl` results in error.

You might need to delete the output folder and run a "fresh run" with same command -- or give it a different `-o` folder.  By default `funannotate` will re-use any existing data -- but it isn't smart enough to know if that file ran "correctly".
