### ISSUE TITLE
Bad translation in compare function

### ISSUE THREAD

**Issue by jolobito** [nextgenusfs/funannotate#219]
Hi, I obtained a similar error to https://github.com/nextgenusfs/funannotate/issues/158.
I see several pal2nal failed, but not in all ortho groups
```
> dNdS Error: pal2nal failed for felines_compare_10k/orthology/orth4.aln
```

The problem seems to be a error with the transcript from one the genomes
```
> #--- ERROR: inconsistency between the following pep and nuc seqs ---#
> LWI_000631-T1
> NKEKMSDLSESSILRKSQSNDTRVRSNFLYWTKPSSLYLITSTVSSSRSLGGAYSSTLIR
> RSSCSMDTAWVCPRRFLKCMNVRRTKTGSCIWYMPLRRHLESKCLC
> LWI_000631-T1
> AACAAAGAGTAGAAGATGTCCGACTTATCCGAGAGCAGCATCCTACGAAAATCCCAGTGA
> TCATAGAACGATACAAGGGTGAGAAGCAACTTCCTGTACTGGACAAAACCAAGTTCCTTG
> TACCTGATCACGTCAACATGAGTGAGCTCATCAAGATCATTAGGAGGCGCTTACAGCTCA
> ACGCTAATCAGGCGTTCTTCCTGTTAGTCAATGGACACAGCATGGTGAGTGTGTCCACGC
> CGATTTCTGAAGTGTATGAACGTGAGAAGGACGAAGACGGGTTCCTGTATATGGTATATG
> CCTCTCAGGAGACATTTGGAATCAAAGTGTCTGTGTAA
>     ###-----   Check the following TBLASTN output:           -----###
>     ###-----       your pep -> 'Query'                       -----###
>     ###-----       your nuc -> 'Sbjct'                       -----###
> Query= LWI_000631-T1
> (106 letters)
> LWI_000631-T1
> Length = 338
> Score = 193 bits (490), Expect = 5e-72
> Identities = 105/112 (93%), Positives = 105/112 (93%), Gaps = 6/112 (5%)
> Frame = +1
> Query: 1 NKE-KMSDLSESSILRKSQS--NDTRVRSNFLYWTKPSSLYLITST-VSSSRSLGGAYSS 56
> NKE KMSDLSESSILRKSQ NDTRVRSNFLYWTKPSSLYLITST VSSSRSLGGAYSS
> Sbjct: 1 NKE\*KMSDLSESSILRKSQ\*S\*NDTRVRSNFLYWTKPSSLYLITST\*VSSSRSLGGAYSS 180
> Query: 57 TLIRRSSC-SMDTAW-VCPRRFLKCMNVRRTKTGSCIWYMPLRRHLESKCLC 106
> TLIRRSSC SMDTAW VCPRRFLKCMNVRRTKTGSCIWYMPLRRHLESKCLC
> Sbjct: 181 TLIRRSSCSMDTAWVCPRRFLKCMNVRRTKTGSCIWYMPLRRHLESKCLC 336
> 
```
The sequence translated from the transcript have a lot of stop codons and is different from the protein in paste /annotate_result
Protein translated in compare
```
> LWI_000631-T1 LWI_000631
> NKE\*KMSDLSESSILRKSQ\*S\*NDTRVRSNFLYWTKPSSLYLITST\*VSSSRSLGGAYSS
> TLIRRSSC\*SMDTAW\*VCPRRFLKCMNVRRTKTGSCIWYMPLRRHLESKCLC
```
Protein translated in annotate_result
```
> LWI_000631-T1 LWI_000631
> QRVEDVRLIREQHPTKIPVIIERYKGEKQLPVLDKTKFLVPDHVNMSELIKIIRRRLQLNANQAFFLLVNGHSMVSVSTP
> ISEVYEREKDEDGFLYMVYASQETFGIKVSV
```

Also the transcript is not multiple of 3 and is in frame +3.
```
> LWI_000631-T1 LWI_000631
> AACAAAGAGTAGAAGATGTCCGACTTATCCGAGAGCAGCATCCTACGAAAATCCCAGTGATCATAGAACGATACAAGGGT
> GAGAAGCAACTTCCTGTACTGGACAAAACCAAGTTCCTTGTACCTGATCACGTCAACATGAGTGAGCTCATCAAGATCAT
> TAGGAGGCGCTTACAGCTCAACGCTAATCAGGCGTTCTTCCTGTTAGTCAATGGACACAGCATGGTGAGTGTGTCCACGC
> CGATTTCTGAAGTGTATGAACGTGAGAAGGACGAAGACGGGTTCCTGTATATGGTATATGCCTCTCAGGAGACATTTGGA
> ATCAAAGTGTCTGTGTAA
> 
```
I am using the last version (1.5). I am not using RNA-seq information and the predict was realized using a gmhmm.mod from a close related species

Thanks!

**Comment by nextgenusfs** [comment]
Can you find the annotation in your genbank file so I can see what the translation is suppose to be and whether there are multiple transcripts. Might also be helpful to pull that gene model out of the GFF3 output as well. Is this the only error or are there multiple?

**Comment by jolobito** [comment]
Hi, there are multiple similar errors.
The translation in the annotation in the gbk file is:

> 
> FEATURES             Location/Qualifiers
>      source          1..10134
>                      /organism="Leopardus wiedii"
>                      /mol_type="genomic DNA"
>                      /db_xref="taxon:61382"
>      gene            complement(7..>4590)
>                      /gene="MAP1LC3B"
>                      /locus_tag="LWI_000631"
>      mRNA            complement(join(7..181,821..927,4535..>4590))
>                      /gene="MAP1LC3B"
>                      /locus_tag="LWI_000631"
>                      /product="Microtubule-associated proteins 1A/1B light
>                      chain 3B"
>      CDS             complement(join(7..181,821..927,4535..>4590))
>                      /gene="MAP1LC3B"
>                      /locus_tag="LWI_000631"
>                      /codon_start=3
>                      /product="Microtubule-associated proteins 1A/1B light
>                      chain 3B"
>                      /protein_id="ncbi:LWI_000631-T1"
>                      /db_xref="InterPro:IPR004241"
>                      /db_xref="InterPro:IPR029071"
>                      /db_xref="PFAM:PF02991"
>                      /db_xref="PFAM:PF04110"
>                      /translation="QRVEDVRLIREQHPTKIPVIIERYKGEKQLPVLDKTKFLVPDHV
>                      NMSELIKIIRRRLQLNANQAFFLLVNGHSMVSVSTPISEVYEREKDEDGFLYMVYASQ
>                      ETFGIKVSV"
> 

The are only one CDS, different from the transcript in compare analysis.


The gene model in the GFF3:

> LPA_65553       GenBank gene    7       4590    .       -       .       ID=LWI_000631;Name=MAP1LC3B;
> LPA_65553       GenBank mRNA    7       4590    .       -       .       ID=LWI_000631-T1;Parent=LWI_000631;product=Microtubule-associated proteins 1A/1B light chain 3B;
> DBxref=InterPro:IPR004241,InterPro:IPR029071,PFAM:PF02991,PFAM:PF04110;
> LPA_65553       GenBank exon    4535    4590    .       -       .       ID=LWI_000631-T1.exon1;Parent=LWI_000631-T1;
> LPA_65553       GenBank exon    821     927     .       -       .       ID=LWI_000631-T1.exon2;Parent=LWI_000631-T1;
> LPA_65553       GenBank exon    7       181     .       -       .       ID=LWI_000631-T1.exon3;Parent=LWI_000631-T1;
> LPA_65553       GenBank CDS     4535    4590    .       -       2       ID=LWI_000631-T1.cds;Parent=LWI_000631-T1;
> LPA_65553       GenBank CDS     821     927     .       -       0       ID=LWI_000631-T1.cds;Parent=LWI_000631-T1;
> LPA_65553       GenBank CDS     7       181     .       -       1       ID=LWI_000631-T1.cds;Parent=LWI_000631-T1;
>

**Comment by jolobito** [comment]
Yes, the translation fail in all genes that don't have codon_start == 1. Thanks for your help! I will waiting for the update.

**Comment by nextgenusfs** [comment]
Notes for myself... these updated functions should fix issue...
```
def translatemRNA(input, output):
	from Bio.SeqIO.FastaIO import SimpleFastaParser
	with open(output, 'w') as outfile:
		with open(input, 'rU') as fasta:
			for header, seq in SimpleFastaParser(fasta):
				codon_start = 1
				for x in header.split(' '):
					if x.startswith('codon_start='):
						codon_start = int(x.replace('codon_start=', '').rstrip())
				protSeq = translate(seq, '+', codon_start-1) #transcripts should already be in proper orientation
				outfile.write('>{:}\n{:}\n'.format(header, protSeq))

def gb2proteinortho(input, folder, name):
	gffOut = os.path.join(folder, name+'.gff')
	FastaOut = os.path.join(folder, name+'.faa')
	Transcripts = os.path.join(folder, name+'.transcripts.fa')
	genes = {}
	with open(input, 'rU') as gbk:
		for record in SeqIO.parse(gbk, 'genbank'):
			for f in record.features:
				gb_feature_add2dict(f, record, genes) 
	#now output the files you need
	with open(gffOut, 'w') as gff:
		with open(FastaOut, 'w') as fasta:
			with open(Transcripts, 'w') as transcripts:
				for k,v in natsorted(genes.items()):
					if v['type'] == 'mRNA':
						for i,item in enumerate(v['ids']):
							transcripts.write(">{:} {:} codon_start={:} strand={:}\n{:}\n".format(
												item, k, v['codon_start'][i], v['strand'], v['cds_transcript'][i]))
							fasta.write(">%s %s\n%s\n" % (item, k, v['protein'][i]))
							gff.write("{:}\t{:}\tCDS\t{:}\t{:}\t.\t{:}\t.\tID={:};Parent={:};product={:};\n".format(v['contig'], v['source'], v['location'][0], v['location'][1], v['strand'], item, k, v['product'][i]))
```

**Comment by jolobito** [comment]
Hi,
I tried the updates functions and the issue was fixed! 
Thanks!
