### ISSUE TITLE
funannotate-functional.py: output not defined if input custom (has no predict_results subbdir)

### ISSUE THREAD

**Issue by zzaheridor** [nextgenusfs/funannotate#22]
https://github.com/nextgenusfs/funannotate/blob/master/bin/funannotate-functional.py#L185
subj,
don't know if it's a bug/

thnx

**Comment by nextgenusfs** [comment]
Did you get an error here?  the script is just trying to predict the many ways in which a user might input data in a way that it is not expecting.  It gets to that point and just tries it's best.

**Comment by zzaheridor** [comment]
error occurs here:
https://github.com/nextgenusfs/funannotate/blob/master/bin/funannotate-functional.py#L198

**Comment by nextgenusfs** [comment]
What command did you pass to script?

**Comment by nextgenusfs** [comment]
This should fix this: https://github.com/nextgenusfs/funannotate/commit/9435d6dcc5a5a7acb13deca0976dc467a689714f

**Comment by zzaheridor** [comment]
Thnx. Was offline.
