### ISSUE TITLE
Stringtie step in funannotate train is not checked when re-run

### ISSUE THREAD

**Issue by AlexdeMendoza** [nextgenusfs/funannotate#220]
I am running a funannotate train run with RNAseq, and somehow PASA failed as it tried to run TransDecoder.LongOrf from a folder whithin PASA (plugins/transdecoder). I have transdecoder installed through conda, so I just added symlinks to the that folder (it would be good to have this fixed, but I guess it is responsability of PASA maintainers). 
In any case, when I tried to re run the script, I noticed that funannotate train checks the previous steps if succesful (trinity run, .bam files, etc..), but in the case of stringtie, despite I had the output in the folder, it just runs it again. The if loop only considers if stringtie is installed, and not if it has been ran before. This then causes trouble in later steps.

Best,

A.

**Comment by AlexdeMendoza** [comment]
I am also having quite a lot of trouble with augustus, as I installed it through miniconda, but the directory structure is not the same as an augustus installation (all scripts are in augustus/bin/ instead of ausgustus/scripts/).

**Comment by nextgenusfs** [comment]
Thanks. I will look at stringtie issue. Yes I just noticed the bioconda Augustus problem yesterday - I think we can get the bioconda recipe updated. The short term fix is to softlink the scripts folder to bin in anaconda. Basically scripts and config folder need to be in same base directory. See more #194.

**Comment by AlexdeMendoza** [comment]
Thanks for the response and for the link to the discussion about augustus and bioconda. Today I just realised that bioconda augustus v3.3, despite it compiled without problems, fails when run (only augustus gives segmentation fault errors, the other utilities work fine). So luckily I still had the bioconda augustus v3.2 there, which is working well. This is on a RedHat7 system, so it seems that the latest augustus release of v.3.3 might have some issues beyond OSX.

**Comment by nextgenusfs** [comment]
You may just want to install it manually. It is kind of a pain to link BAMTOOLS correctly and several makefiles have to be adjusted as they contain developer paths, but likely just need to do it once. I can’t count the number of hours I’ve spent installing/troubleshooting Augustus.....

**Comment by AlexdeMendoza** [comment]
I had a manual installation of v.3.2.2, but somehow the boost libraries are not compatible with it anymore (libboost_iostreams.so.5), likely because some other conda installation changed them... and yes, I have to agree that augustus, despite it is very good at what it does, it is a hellish software to tame... PASA is quite the same. It is also quite frustrating that pasa always tries to find Transdecoder bin and scripts within the PASAPipeline/pasa-plugins/transdecoder folder instead of $PATH.

**Comment by nextgenusfs** [comment]
Trick I use with PASA is to git clone it and then have to remember to git submodule  init followed by git submodule update. Then run make command. This will properly link transdecoder.

**Comment by AlexdeMendoza** [comment]
Thanks for the tip. I did it the hard way (git clone transdecoder and move it to pasa-plugins/transdecoder folder). But it might be good to add this info in the documentation: https://funannotate.readthedocs.io/en/latest/conda.html#conda. I guess it is impossible to accomodate every system and installation, but anyway, thanks for keeping this pipeline updated.

**Comment by AlexdeMendoza** [comment]
Hi again, 

This is not a bug sorry. But I ran Launch_PASA_pipeline.pl outside funannotate train (it was more convenient for my purposes), and now I would like to  obtain the pasa gene models to add to a EVM run. I see that within the script `funannotate-train.py ` you have these two functions, `pasa_transcript2gene` and `getPASAtranscripts2genes`, but my python is not good enough to make them into a separate standalone script. Could you please add a script in the utils to convert a XXX.pasa_assemblies.gff3 to pasa_predictions.gff3?

Thanks a lot in advance for your help.

A.

**Comment by nextgenusfs** [comment]
Can you open a new issue with the PASA script request? Going to close this one.
