### ISSUE TITLE
Using gbk files in funannotate

### ISSUE THREAD

**Issue by jolobito** [nextgenusfs/funannotate#221]
Hi,
I am having some difficulties using gbk files from genbank (ftp://ftp.ncbi.nlm.nih.gov/genomes/Panthera_pardus/CHR_Un/9691_ref_PanPar1.0_chrUn.gbk.gz). I tried to use compare function, but a error associated to locus_tag appear.

`funannotate compare -i 9691_ref_PanPar1.0_chrUn.gbk 74533_ref_PanTig1.0_chrUn.gbk -o compare_gbk --cpus 5`
> 
> 
> -------------------------------------------------------
> Traceback (most recent call last):
>   File "/guest-storage/pfreitas/software/funannotate-master_1.5/bin/funannotate-compare.py", line 190, in <module>
>     genomeStats = lib.genomeStats(GBK)
>   File "/guest-storage/pfreitas/software/funannotate-master_1.5/lib/library.py", line 4909, in genomeStats
>     locus_tag = f.qualifiers.get("locus_tag")[0].split('_')[0]
> TypeError: 'NoneType' object has no attribute '__getitem__'
> 

In the gbk file, the gene section not contain locus_tag

>      gene            28125..62625
>                      /gene="RNF149"
>                      /note="Derived by automated computational analysis using
>                      gene prediction method: Gnomon."
>                      /db_xref="GeneID:109267634"
 
I also tried to reannotate the gbk file, but I obtained several erros, like:

`funannotate annotate --genbank 9691_ref_PanPar1.0_chrUn.gbk -o Panthera_pardus_anntt --cpus 5`

> Checking GenBank file for annotation
> XP_019306149.1 has no translation

here the CDS of  XP_019306149.1 in the .gbk. There is not translation section.

>     CDS             join(28428..28884,40794..41044,41981..42049,47880..47962,
>                      50118..50214,53623..53821,61412..61455)
>                      /gene="RNF149"
>                      /note="Derived by automated computational analysis using
>                      gene prediction method: Gnomon."
>                      /codon_start=1
>                      /product="E3 ubiquitin-protein ligase RNF149 isoform X1"
>                      /protein_id="XP_019306149.1"
>                      /db_xref="GI:1111067205"
>                      /db_xref="GeneID:109267634"

The script fail in several steps because genome.proteins.fasta has only fasta names, and not sequences.

What is the best approach to work with gbk files?

**Comment by nextgenusfs** [comment]
Hi @jolobito.  Sorry to hear you are getting this error.  This is not a new problem, @hyphaltip and I have looked at many GBK genomes and have tried to address many of the issues, obviously this one slipped through.  The biggest problem I have with NCBI is that this was annotated with their own in-house Gnomon software, which apparently doesn't conform to the standards that they require the rest of us to submit genomes through.  GBK files without `locus_tag` should be invalid (at least they would be if one tried to submit it that way). At any rate, I think that the changes we made to the GBK parsing to try to capture all these differently formatted GBK files didn't make its way into the `funannotate compare` code - so this will need to be fixed.  To make it work with the current version, could you try to get the GFF3 + FASTA file from NCBI for this genome and then run it through the `funannotate annotate` command?  This should calculate all the translations and you should end up with a GBK file that `funannotate compare` can parse.

**Comment by jolobito** [comment]
Hi @nextgenusfs. Thanks for your help. I will try your recommendation and teste the GFF3+ FASTA file.

**Comment by jolobito** [comment]
Hi @nextgenusfs,
I tried run the annotate command with GFF3 + FASTA file without success
GFF3: ftp://ftp.ncbi.nlm.nih.gov/genomes/Panthera_pardus/GFF/ref_PanPar1.0_top_level.gff3.gz
Fasta: ftp://ftp.ncbi.nlm.nih.gov/genomes/Panthera_pardus/CHR_Un/9691_ref_PanPar1.0_chrUn.fa.gz

 `funannotate annotate --gff ref_PanPar1.0_top_level.gff3 --fasta 9691_ref_PanPar1.0_chrUn.fa -s 'Panthera tigris' -o Panthera_tigris_anntt --cpus 5
`

> -------------------------------------------------------
> [11:42 PM]: OS: linux2, 128 cores, ~ 1026 GB RAM. Python: 2.7.13
> [11:42 PM]: Running funannotate v1.5.0
> [11:42 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
> [11:42 PM]: Parsing annotation and preparing annotation files.
> Error, can't find ID or Parent. Malformed GFF file.
> NW_017619845.1  RefSeq  region  1       84051066        .       +       .       ID=id0;Dbxref=taxon:9691;Name=Unknown;chromosome=Unknown;gbkey=Src;genome=genomic;isolate=Maewha;mol_type=genomic DNA;sex=female;tissue-type=muscle
> 
> 

Also I tried the GFF3 from Gnomon: ftp://ftp.ncbi.nlm.nih.gov/genomes/Panthera_pardus/Gnomon/ref_PanPar1.0_gnomon_top_level.gff3.gz
with a different error

`funannotate annotate --gff ref_PanPar1.0_gnomon_top_level.gff3 --fasta 9691_ref_PanPar1.0_chrUn.fa -s 'Panthera tigris' -o Panthera_tigris_anntt --cpus 5
`

> -------------------------------------------------------
> [11:54 PM]: OS: linux2, 128 cores, ~ 1026 GB RAM. Python: 2.7.13
> [11:54 PM]: Running funannotate v1.5.0
> [11:54 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
> [11:54 PM]: Parsing annotation and preparing annotation files.
> Traceback (most recent call last):
>   File "/guest-storage/pfreitas/software/funannotate-master_1.5/bin/funannotate-functional.py", line 467, in <module>
>     GeneCounts = lib.convertgff2tbl(GFF, prefix, Scaffolds, Proteins, Transcripts, annotTBL)
>   File "/guest-storage/pfreitas/software/funannotate-master_1.5/lib/library.py", line 1664, in convertgff2tbl
>     Genes = gff2dict(gff, fasta, Genes)
>   File "/guest-storage/pfreitas/software/funannotate-master_1.5/lib/library.py", line 3086, in gff2dict
>     mrnaSeq = getSeqRegions(SeqRecords, v['contig'], sortedExons)
>   File "/guest-storage/pfreitas/software/funannotate-master_1.5/lib/library.py", line 1649, in getSeqRegions
>     partial = SeqRecordDict[header][x[0]-1:x[1]]
> KeyError: 'NW_017619916.1'
> 

thanks!

**Comment by jolobito** [comment]
In the case of use the gff3 of gnomon, the problem seem to be the different contig name. In fasta is 

> \>gi|589289707|ref|NW_006711270.1| Panthera tigris altaica isolate TaeGuk unplaced genomic scaffold, PanTig1.0 scaffold1000, whole genome shotgun sequence

In gff3 is

> NW_006711272.1  Gnomon  gene    417     2721    .       -       .       ID=gene0;Name=gene.2715507234;description=gene.2715507234;gbkey=Gene;gene=gene.2715507234

I changed the fasta names to be concordat with gff3 and the error was solved

**Comment by alishaquandt** [comment]
Hi again Jon,

I've run into a similar but different snag with my gbk inputs into funannotate compare. Here's my command:
funannotate compare -i Nagfri.gbk Kwoniella.gbk Crypto_neo.gbk Crypto_gattii.gbk Solico.gbk Filobasid.gbk Treme.gbk Nagalbida.gbk --cpus 8 --run_dnds estimate

Here's the output I'm getting:

[10:43 AM]: OS: linux2, 24 cores, ~ 132 GB RAM. Python: 2.7.16
[10:43 AM]: Running funannotate v1.6.0-0eff679
[10:43 AM]: Now parsing 8 genomes
[10:43 AM]: working on Naganishia friedmannii
[10:44 AM]: working on Kwoniella bestiolae CBS 10118 CBS 10118
[10:44 AM]: working on Cryptococcus neoformans var. grubii H99 H99
[10:44 AM]: working on Cryptococcus gattii WM276 WM276
Traceback (most recent call last):
  File "/projects/caqu8258/software/build/funannotate/bin/funannotate-compare.py", line 196, in <module>
    functional = lib.getGBKannotation(GBK, FUNDB)
**File "/projects/software/build/funannotate/lib/library.py", line 5960, in getGBKannotation
    product = f.qualifiers['product'][0]
KeyError: 'product'**

Here is a look at the (funannotate derived) gbk file (Nagfri.gbk):

FEATURES             Location/Qualifiers
     source          1..936343
                     /organism="Naganishia friedmannii"
                     /mol_type="genomic DNA"
                     /db_xref="taxon:89922"
     gene            3482..3573
                     /locus_tag="NAGFRI_000001"
     tRNA            3482..3573
                     /locus_tag="NAGFRI_000001"
                     /product="tRNA-Pro"
     gene            complement(4527..6944)
                     /locus_tag="NAGFRI_000002"
     mRNA            complement(join(4527..4605,4661..4712,4765..6351,
                     6422..6944))
                     /locus_tag="NAGFRI_000002"
                     /product="hypothetical protein"
     CDS             complement(join(4527..4605,4661..4712,4765..6351,
                     6422..6944))
                     /locus_tag="NAGFRI_000002"
                     /note="antiSMASH:Cluster_1;
                     BUSCO:EOG092R0EXY;
                     GO_function: GO:0005515 - protein binding [Evidence IEA]"
                     /codon_start=1
                     /product="hypothetical protein"
                     /protein_id="ncbi:NAGFRI_000002-T1"
                     /db_xref="InterPro:IPR001870"
                     /db_xref="InterPro:IPR003877"
                     /db_xref="InterPro:IPR013320"
                     /db_xref="InterPro:IPR035780"
                     /db_xref="PFAM:PF00622"
                     /translation="MAHDTTQTSPDRRPMQIEAVMSYYVDDAESPLSISAEQPVNMAG
                     IDDYLSIQRTDTDILDNGDDPHEQYPFPIKTAPSVPQPSQLPGSGQSNNGKTVYILLP
                     VFVILSTLLVLLIVFLIGIICSKRRKGIRLVEDGGPLDLSRNDGVIGEGGIEGVESRW

Here's a look at one of the Genbank derived files, feature area:

FEATURES             Location/Qualifiers
     source          1..1984823
                     /organism="Cryptococcus gattii WM276"
                     /mol_type="genomic DNA"
                     /strain="WM276"
                     /serotype="B"
                     /db_xref="taxon:367775"
                     /chromosome="A"
     gene            complement(<567..>6253)
                     /locus_tag="CGB_A0010C"
                     /db_xref="GeneID:10188881"
     mRNA            complement(join(<567..671,740..821,899..1204,1285..1516,
                     1583..1685,1741..1788,1845..1925,1981..2639,2692..3004,
                     3063..3376,3435..3917,3970..4144,4196..4278,4332..4492,
                     4543..5080,5127..5281,5330..5432,5479..5561,5612..5765,
                     5818..>6253))
                     /locus_tag="CGB_A0010C"
                     /product="xenobiotic-transporting ATPase, putative"
                     /transcript_id="XM_003191114.1"
                     /db_xref="GeneID:10188881"
     CDS             complement(join(567..671,740..821,899..1204,1285..1516,
                     1583..1685,1741..1788,1845..1925,1981..2639,2692..3004,
                     3063..3376,3435..3917,3970..4144,4196..4278,4332..4492,
                     4543..5080,5127..5281,5330..5432,5479..5561,5612..5765,
                     5818..6253))
                     /locus_tag="CGB_A0010C"
                     /note="Similar to TIGR gene model, INSD accession
                     AAW41688.1"
                     /codon_start=1
                     /product="xenobiotic-transporting ATPase, putative"
                     /protein_id="XP_003191162.1"
                     /db_xref="GeneID:10188881"
                     /translation="MAFAGVGALGPSYDRTEHSAGATLNRTTSRSHYYNDHPNDNLPS


**For some reason, it seems to be tripping on the "product" in some but not all of the GBK files from Genbank. But I can't understand because I see "product" in both file types. Any thoughts?** 

Just so you know, I get the following output in the protortho directory, so it is working correctly, until it gets to Cryptococcus gattii (it also trips on some of the others - I've been tinkering with the order, just to troubleshoot): 

Naganishia_friedmannii.transcripts.fa
Naganishia_friedmannii.faa
Naganishia_friedmannii.gff
Kwoniella_bestiolae_CBS_10118_CBS10118.transcripts.fa
Kwoniella_bestiolae_CBS_10118_CBS10118.faa
Kwoniella_bestiolae_CBS_10118_CBS10118.gff
Cryptococcus_neoformans_var._grubii_H99_H99.transcripts.fa
Cryptococcus_neoformans_var._grubii_H99_H99.faa
Cryptococcus_neoformans_var._grubii_H99_H99.gff

Thanks in advance!
Alisha
