### ISSUE TITLE
Python packages not recognized: goatools, psutil, seaborn

### ISSUE THREAD

**Issue by BurlEarl** [nextgenusfs/funannotate#222]
I have tried installing funannotate dependencies using your conda(mostly) method.  

It looks like goatools, psutil, and seaborn installed correctly, but the dependency checker can't find them.
```
#show installed python packages
$ conda list
# packages in environment at /home/miniconda3:
#
# Name                    Version                   Build  Channel
...
goatools                  0.8.4                      py_0    bioconda
psutil                    5.4.7            py27h470a237_1    conda-forge
...
seaborn                   0.9.0                      py_0    conda-forge
...

#check dependencies
$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.5.0-4cb0e53
-------------------------------------------------------
You are running Python v 2.7.14. Now checking python packages...
biopython: 1.71
matplotlib: 2.2.2
natsort: 5.2.0
numpy: 1.14.2
pandas: 0.22.0
requests: 2.18.4
scikit-learn: 0.19.1
scipy: 1.0.1
   ERROR: goatools not installed, pip install goatools or conda install goatools
   ERROR: psutil not installed, pip install psutil or conda install psutil
   ERROR: seaborn not installed, pip install seaborn or conda install seaborn
...
```
All the other python packages were installed at the same time, so I assume that funannotate is looking in the correct directory, but is there a PATH variable I can give funannotate to direct it to these packages.

Thanks for taking on the challenge and creating this huge tool and for the community.

Earl

**Comment by nextgenusfs** [comment]
The script isn't doing anything 'fancy', it is just trying to import those tools and returns ERROR if it cannot. So something must be not installing correctly?  Are you in a conda virtual environment or the base directory?  I find it easier to manage the dependencies to create an env and then add the tools that way, i.e.
```
conda create -n funannotate python=2.7 numpy natsort psutil matplotlib seaborn goatools .....
```
I also see you have miniconda3 installed, so wondering if those packages were perhaps only installed in py3 and not in py2?

**Comment by BurlEarl** [comment]
Jon,
Thanks for the speedy reply...i'm super dumb.  I just installed the python3 versions. 
Now, a couple more dependencies and I'm up and running.
Thanks again!
Earl

**Comment by nextgenusfs** [comment]
Its happened to me more times than I'd like to admit.... Good luck!

**Comment by BurlEarl** [comment]
thanks!
