### ISSUE TITLE
http://csbl.bmb.uga.edu is down

### ISSUE THREAD

**Issue by aaronmck** [nextgenusfs/funannotate#224]
Thanks for the great tool here, I'm excited to get it set up and running.  This is not a funannotate issue directly, but I don't know who to contact at UGA to get this fixed. The funannotate setup script pulls the dbCAN database from http://csbl.bmb.uga.edu, but this appears to be down over the last ~week. I've switched my install over to a link at niu.edu (http://cys.bios.niu.edu/dbCAN/download/), but I'm not sure if that's correct, or if it will work with the existing toolsets. 

Thanks again!

**Comment by aberaslop** [comment]
Hi aaronmkc,

I have exactly the same issue. Did you figure out a solution? Thank you!

**Comment by aaronmck** [comment]
I just replaced all of the csbl links in [lib/library.py](https://github.com/nextgenusfs/funannotate/blob/41943f5c359f565e8d93bf0c58e2e913c59c203c/lib/library.py) with links to files of the same name from http://cys.bios.niu.edu/dbCAN/download/. Everything is still running so I'm not sure if this will work, but it did complete the setup stage.

**Comment by nextgenusfs** [comment]
Thanks for reporting the issue. Do we know/think that the data is the same from either place?  I need to look at the license info, but I can move a copy over to OSF so this doesn’t happen - but then if database gets updated it won’t be automatically integrated.

**Comment by aaronmck** [comment]
Yeah this is totally a concern; I don't have the data from csbl (clearly :-) ) so I can't checksum the files, but here's a diff of which file paths had to change:

-        'dbCAN': 'http://cys.bios.niu.edu/dbCAN/download/dbCAN-fam-HMMs.txt',
-        'dbCAN-tsv': 'http://cys.bios.niu.edu/dbCAN/download/FamInfo.txt',
-        'dbCAN-log': 'http://cys.bios.niu.edu/dbCAN/download/readme.txt',
+        'dbCAN': 'http://csbl.bmb.uga.edu/dbCAN/download/dbCAN-fam-HMMs.txt',
+        'dbCAN-tsv': 'http://csbl.bmb.uga.edu/dbCAN/download/FamInfo.txt',
+        'dbCAN-log': 'http://csbl.bmb.uga.edu/dbCAN/download/readme.txt',

If you have the csbl files lying around it should be quick to tell if they're the same. Thanks again for the great tool!

**Comment by fjlicht** [comment]
Thank you for the fix @aaronmck been having the same issue for the past week trying to install. Error here:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.0/libexec/bin/funannotate-setup.py", line 443, in <module>
    dbCANDB(DatabaseInfo, args.force)
  File "/home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.0/libexec/bin/funannotate-setup.py", line 162, in dbCANDB
    download(lib.DBURL.get('dbCAN'), os.path.join(FUNDB,'dbCAN.tmp'))
  File "/home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.0/libexec/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_1/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_1/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_1/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_1/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_1/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_1/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by nextgenusfs** [comment]
Let me know if latest update v1.5.1 is working for you.

**Comment by nextgenusfs** [comment]
Sorry I forgot to push the home-brew recipe update, should be live now.

**Comment by aaronmck** [comment]
A fresh setup using 1.5.1 worked without issue, thanks! I'll close the issue. Also, it's worth noting that the scripts still display the version as 1.5.0, which can be confusing.

**Comment by nextgenusfs** [comment]
Ah, okay.  Sorry about that -- will bump the version.
