### ISSUE TITLE
Upgrade to Busco v3?

### ISSUE THREAD

**Issue by PlantDr430** [nextgenusfs/funannotate#232]
Hello,

I was wondering if future versions of Funannotate would implement BUSCO v3 instead of BUSCO v2 which it is currently using?

**Comment by nextgenusfs** [comment]
Are the models different in v2 vs v3?  I thought they were the same. Are the results any different between the versions?  I’m using a modified busco v2 internally as there were lots of issues with v2 which I fixed to work with funannotate, so I’m hesitant to change and then be faced with some additional compatibility issues. If busco v3 is python2 compatible I could swap it out, but If it is python3 only then it won’t work with funannotate.

**Comment by PlantDr430** [comment]
Ah, I am not entirely sure about the differences between v2 and v3. I don't have v3 installed on our departments server so I can't compare the two yet. I did notice that you are running a modified version, which I am also running to train SNAP. I was more just wondering if it was a plan of yours for future versions. I do believe v3 is python2 compatible as it says that on their user guide. They just recommend python3 when available.

**Comment by nextgenusfs** [comment]
If you want to compare the versions and show that there are differences (improvements I would hope) in results then I will consider making the change.  Otherwise I’d rather not change it as it is working at the moment.
