### ISSUE TITLE
Interproscan produces no results

### ISSUE THREAD

**Issue by ignadb** [nextgenusfs/funannotate#234]
Hi Jon
Thanks for your hard work on funannotate!

I am experiencing no result from interproscan. What I have just a single XML file with the following header ..

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5">
</protein-matches>

However, Interproscan runs just fine when I run it directly. Can you imagine what plausibly causes this? The command I use is .. 

./funannotate iprscan -i /home/CK/Desktop/Chi01/new_annotation_30102018/predict_results/Hynemoscyphus_chi01.proteins.fa -m local -o /home/CK/Desktop/Chi0/new_annotation_30102018/predict_results/iprs -c 24 --iprscan_path /home/CK/software/interproscan-5.25-64.0/

Thank you very much!

**Comment by nextgenusfs** [comment]
Perhaps running out of memory?  There are log files for each process In the temp directory you will likely get a hint there. When I run it locally have to set the interproscan.properties file to use only a single core - as the script is going to split in input and then launch 24 interproscan instances. So with default settings in the properties file it might be trying to use a lot of system resources.

**Comment by ignadb** [comment]
Hi Jon,

I took alok at it and i changed the interproscan.properties and launched the funannotate with -c 4 so it would launch less processes of interproscan as well - however I'm still only getting a empty result file.

I'm not quite sure which temp folder you are referring to, but in the funannotate folder where I launch the command from I get a iprscan_<number> folder which contains some fasta files and a log file which seems to be generated by interproscan - however most of them seem fine.

Any other ideas as to what to look for?

Regards,
Chatchai

________________________________

**Comment by ignadb** [comment]
Hi Jon,

No error messages to terminal, and I think it launches since I get a bunch of java processes and other processes launching, and it takes like 4+ hours to finish.

I've tried amending interproscan.sh to the path, I'll keep you updated with the results.

Regards,
Chatchai

________________________________

**Comment by ignadb** [comment]
Hi Jon,

It's working now, turns out it was the 2 parameters referring to TMHMM in the interproscan.properties file that was the problem, sorted now and I'm getting results from funannotate.

Thanks for your support!

Regards,
Chatchai

________________________________
From: Chatchai Kosawang
Sent: Sunday, November 18, 2018 18:38
To: nextgenusfs/funannotate
Subject: RE: [nextgenusfs/funannotate] Interproscan produces no results (#234)

Hi Jon,

No error messages to terminal, and I think it launches since I get a bunch of java processes and other processes launching, and it takes like 4+ hours to finish.

I've tried amending interproscan.sh to the path, I'll keep you updated with the results.

Regards,
Chatchai

________________________________
