### ISSUE TITLE
funannotate predict generates empty output

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/funannotate#237]
Hi!

I am trying to annotate a genome with funannotate v1.5.0. and no evidence data in a virtual machine. The first couple of steps run smoothly. However, I am having some trouble running some funannotate intermediate steps such as, for instance, interproscan. 

"funannotate predict" seems to run fine, it gives no errors. However, it produces three folders: logfiles, predict_misc and predict_results. Predict results has some empty files, whereas predict_misc has files with data in them. Is there anything I am missing?

I do not know if this is relevant, but at some point do get a warning reported in funannotate-EVM.log:

perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_GB:en",
        LC_ALL = (unset),
        LANG = "en_GB.UTF-8"
    are supported and installed on your system. 

I have attached the resulting log files.

Thank you so much!
[funannotate-EVM.log](https://github.com/nextgenusfs/funannotate/files/2622576/funannotate-EVM.log)
[funannotate-p2g.log](https://github.com/nextgenusfs/funannotate/files/2622577/funannotate-p2g.log)
[funannotate-predict.log](https://github.com/nextgenusfs/funannotate/files/2622578/funannotate-predict.log)

**Comment by nextgenusfs** [comment]
It seems that your copy of tbl2asn is the problem. Try to launch this command manually and hopefully it will tell you what is wrong:

tbl2asn -y "Annotated using funannotate v1.5.0" -N 1 -t /home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.1/libexec/lib/test.sbt -M n -j "[organism=Escovopsis weberi]" -V b -c fx -T -a r10u -l paired-ends -Z gene_prediction_softm_genome_only/predict_misc/tbl2asn/1/discrepency.report.txt -p gene_prediction_softm_genome_only/predict_misc/tbl2asn/1

**Comment by aberaslop** [comment]
Thank you for such a quick answer!

I run that command and I got the following:

tbl2asn: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory

Any idea of what is causing this?

**Comment by nextgenusfs** [comment]
Try to reinstall tbl2asn, looks like it was compiled with a shared library that is no longer where it expects.

**Comment by aberaslop** [comment]
Thanks!
I installed funannotate with the Homebrew mediated installation. Should I just install the new tbl2asn where the current one is?

**Comment by nextgenusfs** [comment]
Try:
brew reinstall —build-from-source tbl2asn

**Comment by nextgenusfs** [comment]
Ok, uninstall the brew version and just download the binary from NCBI. It just needs to be in your path for funannotate to find it.

**Comment by aberaslop** [comment]
Thanks!

I have downloaded it from NCBI, and placed it in /home/linuxbrew/.linuxbrew/bin. Then run:

tbl2asn -y "Annotated using funannotate v1.5.0" -N 1 -t /home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.1/libexec/lib/test.sbt -M n -j "[organism=Escovopsis weberi]" -V b -c fx -T -a r10u -l paired-ends -Z gene_prediction_softm_genome_only/predict_misc/tbl2asn/1/discrepency.report.txt -p gene_prediction_softm_genome_only/predict_misc/tbl2asn/1

And got:

[tbl2asn] Flatfile genome

[tbl2asn] Validating genome

Should I re-run funannotate predict now?

**Comment by nextgenusfs** [comment]
Yeah just reissue the same command you ran the first time and it will complete.

**Comment by aberaslop** [comment]
Wonderful! Thanks a lot! Will let you know if this works.

**Comment by aberaslop** [comment]
Happy to report that it worked already! The predict_results folder now contains files with data. Thank you so much for your help
