### ISSUE TITLE
Problem installing funannotate

### ISSUE THREAD

**Issue by soumyarao86** [nextgenusfs/funannotate#24]
Hi
I tried to install funannotate on centos 6 by following the instructions on https://github.com/nextgenusfs/funannotate/blob/master/docs/ubuntu_install.md
I followed every step till I got stuck while running the command `brew install funannotate`
There seems to be no config.log file created. I tried brew gist-logs funannotate which didn't work.
I could only make out the problem with c compiler from .linuxbrew/bin.

```
Last 15 lines from /home/lgpa/.cache/Homebrew/Logs/pkg-config/01.configure:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /home/lgpa/.linuxbrew/bin/gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/pkg-config-20160830-28790-ykpq9q/pkg-config-0.29.1':
configure: error: C compiler cannot create executables
```

Please help me fix it.

**Comment by nextgenusfs** [comment]
I did get it installed once on centos7.  Seems like you are having an issue similar to this one: https://github.com/Linuxbrew/legacy-linuxbrew/issues/689.  You were able to get GCC installed via, `brew install gcc`?

**Comment by nextgenusfs** [comment]
Based on this: https://github.com/Linuxbrew/brew/issues/80.  You could try:
`brew install --cc=gcc-5 pkg-config`

**Comment by soumyarao86** [comment]
I didn't install gcc on brew. It was already there.
I tried to run the command you suggested:
```
 brew install --cc=gcc-5 pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar.gz
Already downloaded: /home/lgpa/.cache/Homebrew/pkg-config-0.29.1.tar.gz
==> ./configure --prefix=/home/lgpa/.linuxbrew/Cellar/pkg-config/0.29.1_1 --disable-host-tool --with-internal-glib --with-pc-path=/home/lgpa/.linuxbrew/lib/pkgconfig
Last 15 lines from /home/lgpa/.cache/Homebrew/Logs/pkg-config/01.configure:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /home/lgpa/.linuxbrew/bin/gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/pkg-config-20160831-7733-1pr9ltq/pkg-config-0.29.1':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues
```

**Comment by nextgenusfs** [comment]
I assume you've tried to run `brew update` twice followed by `brew doctor` as part of the troubleshooting it points you to [here](https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)?  I would try to reinstall gcc, `brew reinstall gcc` and then try again.  If that doesn't work I don't know what the problem is and you could get some help by filing an issue with LinuxBrew folks (info for that is in link above) as this seems like it is a LinuxBrew problem (where I'm not that much help).

**Comment by soumyarao86** [comment]
I could get C compiler working by changing permissions of some files and keeping the path of .linuxbrew before /usr/bin in my .bashrc.
But then encountered errors in subsequent steps. Solved the problem with blast but got stuck at blat. I am trying to fix it.
```make[1]: Entering directory `/tmp/blat-20160901-14378-wb6jth/blatSrc/gfClient'
gcc -O -g -Os -w -pipe -march=native -I/home/lgpa/.linuxbrew/opt/libpng/include -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -DUSE_SSL -DCOLOR32   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I/include -I/home/lgpa/.linuxbrew/Cellar/libpng/1.6.24/include/libpng16  -o gfClient.o -c gfClient.c
gcc -O -g -o /home/lgpa/.linuxbrew/Cellar/blat/36/bin/gfClient gfClient.o   ../lib/x86_64/jkOwnLib.a ../lib/x86_64/jkweb.a -rdynamic -L/usr/lib64/mysql -lmysqlclient -lz -lcrypt -lnsl -lm -lssl -lcrypto -lstdc++ -lrt -lm  -pthread -L/lib -lssl -lcrypto -L/home/lgpa/.linuxbrew/Cellar/libpng/1.6.24/lib -lpng16 -lm  -lm
/home/lgpa/.linuxbrew/bin/ld: warning: libssl.so.10, needed by /usr/lib64/mysql/libmysqlclient.so, not found (try using -rpath or -rpath-link)
/home/lgpa/.linuxbrew/bin/ld: warning: libcrypto.so.10, needed by /usr/lib64/mysql/libmysqlclient.so, not found (try using -rpath or -rpath-link)
/usr/lib64/mysql/libmysqlclient.so: undefined reference to `OPENSSL_add_all_algorithms_noconf@libcrypto.so.10'
/usr/lib64/mysql/libmysqlclient.so: undefined reference to `SSL_CTX_ctrl@libssl.so.10'
/usr/lib64/mysql/libmysqlclient.so: undefined reference to `SSL_accept@libssl.so.10'
```
a long list of undefined references..
```
collect2: error: ld returned 1 exit status
make[1]: *** [/home/lgpa/.linuxbrew/Cellar/blat/36/bin/gfClient] Error 1
make[1]: Leaving directory `/tmp/blat-20160901-14378-wb6jth/blatSrc/gfClient'
make: *** [all] Error 2
```
```
locate SSL_CTX_ctrl
/home/lgpa/.linuxbrew/Cellar/openssl/1.0.2h_1/share/man/man3/SSL_CTX_ctrl.3ssl
/home/lgpa/.linuxbrew/share/man/man3/SSL_CTX_ctrl.3ssl
/usr/share/man/man3/SSL_CTX_ctrl.3ssl.gz
```
I am also trying to figure out if ```brew install funannotate``` can bypass installing the tools like blast that were installed previously. It takes about 45 minutes to reinstall blast before getting the same error when I repeat ```brew install funannotate```.
I keep doing ```brew update``` and ```brew doctor``` and end up with many warnings like the ones in the attached file.
[Warning.docx](https://github.com/nextgenusfs/funannotate/files/448831/Warning.docx)

**Comment by nextgenusfs** [comment]
Here is the linuxbrew install [page](http://linuxbrew.sh), it seems there are some additional dependencies for centos/redhat.  As it sounds more like you are missing several system dependencies/libraries. Before installing linuxbrew, etc, you need to install the centOS equivalent of the system libraries shown in the ubuntu tutorial, instead of `sudo apt-get` you can install with `yum`.  
For example, these are equivalent:
```
#ubuntu
sudo apt-get install -y build-essential
#centOS/redhat
sudo yum groupinstall 'Development Tools'
```
So the instructions in the linuxbrew site say to run this to install (is this what you ran?):
```
sudo yum groupinstall 'Development Tools' && sudo yum install curl git irb python-setuptools ruby
```

To solve the permissions issues with the linuxbrew folder you can do this (perhaps you already did):
```
sudo chown -R $(whoami) $HOME/.linuxbrew
```
Sorry you are having a hard time I know how frustrating it is.  The reason I made it install via home-brew is that it is much easier than doing it all manually.  If you can just get to where linuxbrew is functioning then it should be a lot easier.  Keep googling when you get errors.  Alternatively you can install all the tools manually and then just do a `git clone` of the funannotate repository, there is a setup/install tool that checks all the dependencies and should let you know if something isn't installed correctly for funannotate to run.

**Comment by soumyarao86** [comment]
Thanks a lot for all your suggestions. I did follow instructions on .linuxbrew site still there seem to be some missing dependencies. I know how simple it is to install all the tools I need with brew. So only I am tryimng hard to get it work. I will try to fix it also and still if I get stuck, will go for manual installation for all the tools needed (which again gets stuck with new set of problems).
I did install it on Ubuntu few months back but now I have to work on CentOS. So need to do everything all over again. And yeah it is a little depressing that I spend more time on installation and have not yet reached a stage where I can analyze the results! But there is no short cut or any IT support available, and I am determined to get things done. I am grateful to you for making such a nice pipeline as funannotate that will make life easier later.

**Comment by nextgenusfs** [comment]
If you want to keep track of which dependencies are different we can make a centOS installation guide that would help others that would be great. When I get some time I can try a fresh install on virtual box and see if it works. 






On Thu, Sep 1, 2016 at 6:52 AM -0500, "soumyarao86" <notifications@github.com> wrote:












Thanks a lot for all your suggestions. I did follow instructions on .linuxbrew site still there seem to be some missing dependencies. I know how simple it is to install all the tools I need with brew. So only I am tryimng hard to get it work. I will try to fix it also and still if I get stuck, will go for manual installation for all the tools needed (which again gets stuck with new set of problems).

I did install it on Ubuntu few months back but now I have to work on CentOS. So need to do everything all over again. And yeah it is a little depressing that I spend more time on installation and have not yet reached a stage where I can analyze the results! But there is no short cut or any IT support available, and I am determined to get things done. I am grateful to you for making such a nice pipeline as funannotate that will make life easier later.

**Comment by soumyarao86** [comment]
Sure. That will be very helpful for others too. I will try to note down all the steps while troubleshooting.

**Comment by soumyarao86** [comment]
Hi Jon, 
I passed blat test too! I noticed that msql was in /usr/lib64, so installed it through brew and then tried ``` brew install funannotate ```. And it seemed to work and go past blat last night. However tit is still trying to install at Repeatmodeler since last 6 hours.
```
/home/lgpa/.linuxbrew/Cellar/repeatmasker/4.0.5: 217 files, 344.7M, built in 25 seconds
==> Installing nextgenusfs/tap/funannotate dependency: recon
==> Downloading https://linuxbrew.bintray.com/bottles-science/recon-1.07.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring recon-1.07.x86_64_linux.bottle.tar.gz
🍺  /home/lgpa/.linuxbrew/Cellar/recon/1.07: 12 files, 211.2K
==> Installing nextgenusfs/tap/funannotate dependency: repeatmodeler
==> Downloading https://linuxbrew.bintray.com/bottles-science/repeatmodeler-1.0.8_1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring repeatmodeler-1.0.8_1.x86_64_linux.bottle.tar.gz
==> perl ./configure <config.txt
```
So I am waiting and trying not to kill the process.
Does this step take this much much time? Is perl required in the last step? How long it may take to complete funannotate installation? Is there any way to avoid reinstalling all the existing tools in case it ends abruptly and needs to be repeated.

**Comment by nextgenusfs** [comment]
There must still be some system dependencies missing, it should install in 10 minutes or less.  Blast will take the longest to install, but the rest of the tools shouldn’t take that much time.  Yes perl is a dependency.

**Comment by soumyarao86** [comment]
It was the ./configure in repeatmodeler file where I changed the path of perl and ran '''perl ./configure``` to install it. I did install rest of the programs using ``` brew install <name_in_lowercase>```
like trnascan, braker, evidencemodeler etc. But I don't know how to get funannotate now so that it doesn't install rest of the dependencies. 
I have two files in my system:
```
/home/lgpa/.linuxbrew/Library/Locks/funannotate.brewing
/home/lgpa/.linuxbrew/Library/Taps/nextgenusfs/homebrew-tap/funannotate.rb
```
Is there a way to get it installed directly?

**Comment by soumyarao86** [comment]
And I forgot to mention that trnascan failed to install through brew. 
```
brew install trnascan
==> Installing trnascan from homebrew/science
==> Downloading http://eddylab.org/software/tRNAscan-SE/tRNAscan-SE.tar.Z
Already downloaded: /home/lgpa/.cache/Homebrew/trnascan-1.23.tar.Z
tar (child): compress: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Failure while executing: tar xf /home/lgpa/.cache/Homebrew/trnascan-1.23.tar.Z
```

**Comment by nextgenusfs** [comment]
You can always just git clone the repository.  But it really sounds like you are missing core build dependencies still, but I know know for sure.
```
git clone https://github.com/nextgenusfs/funannotate.git
```

**Comment by soumyarao86** [comment]
Hello Jon,

Happy to inform you that I could finally install funannotate along with all the dependencies. tRNAscan was installed from source. Augustus was installed using ``` brew install --force-bottle augustus ```.
./setup.sh ran successfully.
However running funannotate predict on the sample data returned
``` GeneMark-ES failed, likely input was not sufficient for training, provide a gmhmm.mod file and re-run``` 
Hope this can be fixed.

**Comment by nextgenusfs** [comment]
Can you paste the output form the log file - located in outputfolder/logfiles/funannotate-predict.log

**Comment by nextgenusfs** [comment]
And then next place to look is in the genemark folder at the gmes.log file

**Comment by soumyarao86** [comment]
The genemark folder is empty. gmes.log is not found. It fails at ``` gmes_petap.pl --ES --fungus --cores 6 --sequence /home/lgpa/funannotate/sample_run/genome1/predict_misc/genome.softmasked.fa ```
There is no file named genome.softmasked.fa in the given path.  funannotate-repeats.log shows no error and ends with 
```
cycle 7
cycle 8
cycle 9
cycle 10
Generating output...
masking
done
```

**Comment by soumyarao86** [comment]
I am sorry, the file genome.softmasked.fa exists but the error is 
```
stat(/home/lgpa/Documents/soumya/funannotate/sample_run/gmes.log): No such file or directory at /usr/local/gmes_petap/gmes_petap.pl line 1006.
OIO::Method error: Can't locate object method "write_error" via package "Logger::Simple"
Package: Logger::Simple
File: /usr/local/share/perl5/Logger/Simple.pm
Line: 45


Trace begun at /usr/local/share/perl5/Logger/Simple.pm line 45
Logger::Simple::open_log('Logger::Simple=SCALAR(0x1f0a938)') called at /usr/local/share/perl5/Logger/Simple.pm line 37
Object::InsideOut::new('Logger::Simple', 'HASH(0x239dcb8)') called at /usr/local/gmes_petap/gmes_petap.pl line 1008
main::SetLogger at /usr/local/gmes_petap/gmes_petap.pl line 987
main::ReadParameters at /usr/local/gmes_petap/gmes_petap.pl line 96
```

**Comment by nextgenusfs** [comment]
genemark is not properly installed, looks like you are missing the perl module Logger::Simple.  If you have cpanminus installed can install like (depending on your setup and if you are using system perl or not you may need to use sudo):
```
cpanm Logger::Simple
```
This is from the install page, you need these modules:
```
cpanm Getopt::Long Pod::Usage File::Basename threads threads::shared \
        Thread::Queue Carp Data::Dumper YAML Hash::Merge Logger::Simple Parallel::ForkManager \
        DBI Text::Soundex Scalar::Util::Numeric
```
If you type the following, you should see that it is not installed, what is the output of for the perl modules section:
```
funannotate setup --dep
```

**Comment by soumyarao86** [comment]
I made sure all the libraries are up to date including logger::simple. I don't know why gmes_petap.pl fails.

**Comment by nextgenusfs** [comment]
when you launch genemark by itself what are the errors?  i.e. 
```
gmes_petap.pl --ES --fungus --cores 6 --v genome.softmasked.fa
```
My guess is that maybe you have multiple versions of perl installed? GeneMark is hard-coded to use system Perl in `/usr/bin/perl`, however you may have another version of perl where the modules have been installed, i.e. `/usr/local/bin/perl`.  Check the output of `which perl` to see what is in your environment.

**Comment by soumyarao86** [comment]
The command gave the error I mentioned earlier ```OIO::Method error: Can't locate object method "write_error" via package "Logger::Simple"```
```which perl``` gives /usr/bin/perl but /usr/bin/perl5.10.1 also exists, so I renamed the latter. However the error persists with gmes_petap.pl. 
Logger::Simple is called at /usr/local/share/perl5/Logger/Simple.pm. What should I do? Changing the name of files from /usr/bin doesn't feel safe.

**Comment by nextgenusfs** [comment]
Well at least you know it is a Perl problem, other than that I'm not sure exactly what the problem is.  Is there an issue with the version of Perl and/or the version of Logger::Simple?  I'm grasping here.... You could try asking the GeneMark developers for help.

**Comment by soumyarao86** [comment]
Yes, I get it. I will get back to you after hearing from GeneMark developers.

**Comment by jelber2** [comment]
For trnascan-se on CentOS 6.8, I had to do the following:
`brew install gnu-tar` then `brew install trnascan`
