### ISSUE TITLE
New RepeatMasker release breaks Docker build 

### ISSUE THREAD

**Issue by thallinger** [nextgenusfs/funannotate#241]
The Docker build uses RepeatMasker 4.0.7 and requires RepBaseRepeatMaskerEdition-20170127.tar.gz
as the corresponding database. Since the release of RepeatMasker 4.0.8 end of October the current database is RepBaseRepeatMaskerEdition-20181026.tar.gz and the link to the previous database
is not valid any more.

Therefore, either the database link in the Docker installation instructions should be changed to 
https://www.girinst.org/server/archive/RepBase23.09/protected/repeatmaskerlibraries/RepBaseRepeatMaskerEdition-20170127.tar.gz
or Dockerfile should be upgraded to RepeatMasker 4.0.8 and the database link changed to 
http://www.girinst.org/server/RepBase/protected/repeatmaskerlibraries/RepBaseRepeatMaskerEdition-20181026.tar.gz.

The error output for RepeatMasker and database version mismatch is as follows:
Enter path [ /home/linuxbrew/repeatmasker ]: Rebuilding RepeatMaskerLib.embl library
  - Read in 216 sequences from /home/linuxbrew/repeatmasker/Libraries/DfamConsensus.embl
  - Read in 49011 sequences from /home/linuxbrew/repeatmasker/Libraries/RMRBSeqs.embl
    Reading metadata database...Error! Could not find SNAP-OL2
Error! Could not find HATN14_DR
Error! Could not find Bridge2(Xena)
Error! Could not find R2-1a_Cis
Error! Could not find TOS1_OS
Error! Could not find MAGELLAN_ZM-LTR
Error! Could not find MI167_AT 
...

**Comment by nextgenusfs** [comment]
thanks, updated link in docs (note I have not tested the link) -- https://github.com/nextgenusfs/funannotate/blob/master/docs/docker.rst
