### ISSUE TITLE
RepeatMasker bug

### ISSUE THREAD

**Issue by antben** [nextgenusfs/funannotate#25]
I'm trying to use funannotate on a bee genome, though my issue does not seem specific to my data. When I run "predict", RepeatModeler runs successfully but then RepeatMasker fails and funannotate reports: 
"[11:33:22 AM]: Soft-masking: running RepeatMasker with custom library
RepeatMasker::createLib(): Error invoking /usr/local/hmmer/3.1b2/binaries/hmmpress on file /Genomics/kocherlab/berubin/annotation/ligatus/funannotate/RM_49155.SunSep181133222016/consensi.fa.
[11:33:26 AM]: RepeatMasking failed, check log files."

This appears to be a problem with RepeatMasker not handling custom databases correctly when the search engine is hmmer as hmmer expects a file of hmm's but is passed a fasta file by RepeatMasker. Has anyone else experienced this problem or is it something about my installation? Is there an easy way to just change the search engine used by RepeatMasker to get around the issue?

Thanks,
Ben

**Comment by antben** [comment]
I tried running funannotate on the sample data and I'm less confident in my diagnosis now. Apparently, RepeatModeler returns 0 models, though there is sequence in consensi.fa. Not sure if this is informative. I have attached the logs from the sample data run.

[funannotate-predict.log.txt](https://github.com/nextgenusfs/funannotate/files/478829/funannotate-predict.log.txt)
[funannotate-repeats.log.txt](https://github.com/nextgenusfs/funannotate/files/478830/funannotate-repeats.log.txt)

**Comment by nextgenusfs** [comment]
Hi Ben,
You need to re-configure your RepeatMasker installation to use RMBlast and the RepBase database, not HMMer based DFAM.  You should be able to reconfigure by moving to the repeat masker installation directory, if you are on mac it installed with home-brew would be `/usr/local/Cellar/repeatmasker/4.0.5/libexec` (on linux would be `$HOME/.linuxbrew/Cellar/repeatmasker/4.0.5/libexec`), and then run `perl ./configure` - follow the installation directions and setup to use RMBlast by default.  Did you install the RepBase libraries?

**Comment by nextgenusfs** [comment]
Hi Ben,
Actually let me just make a change to the code so it runs RMblast/ncbi and not the default, you should be able to have both installed - for funannotate I want it to use RMblast and the RepBase database - but you should be able to use DFAM for other things on your system if you want.  Give me a few minutes and I will test my change and push a new version.
Jo

**Comment by nextgenusfs** [comment]
OK, This should fix it https://github.com/nextgenusfs/funannotate/commit/3ac1a105cf990c900403b2a989f505b78b31a13b

You can update with linux brew, `brew update`, `brew upgrade funannotate`, and then you will need to run `funannotate setup --db` to make sure databases are setup.

**Comment by antben** [comment]
Hi Jon,

That makes sense. I'm trying to get it installed on our server so will have
to ask our IT team to update and I expect that it won't happen until
tomorrow but I'll let you know then if I have any more issues. Thanks so
much for the help.

Ben
