### ISSUE TITLE
busco_db and busco_seed_species needed with RNAseq data?

### ISSUE THREAD

**Issue by EarlyEvol** [nextgenusfs/funannotate#251]
Hi Jon,
After getting through interproscan and gearing up to run funannotate annotate, I have noticed that busco_db and busco_seed_species are not the same arguments.  I am annotating a hymenopteran genome and just used --busco_seed_species hymenoptera for predict, but left out busco_db.  Also, I didn't use either busco arguments for funannotate update.  Now that I am looking more closely, Your documentation on predict that shows a step by step workflow makes it seem that BUSCO is not used at all if you provide RNAseq and PASA evidence (my output files corroborate this).  I think everything is fine but at the bottom of the "tutorials" page it says for non-fungal genomes "Pay attention to the --busco_db option in all scripts." and that got me nervous.

As a curiosity, how do these arguments differ?  I saw in issue #2 you recommended to use --busco_db arthropod and --busco_seed_species tribolium.  Does this mean that, if necessary, you should use a broader taxon for busco_db and the narrowest for busco_seed_species?

Thanks,
Earl

**Comment by hyphaltip** [comment]
The seed species I believe is what target species to use when Busco does Augustus runs  so it should match a parameter set that is in your Augustus config/species folder.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by nextgenusfs** [comment]
@hyphaltip that is correct -- perhaps it should be renamed to `--augustus_seed_species`.  BUSCO is only run when there is no RNA-seq data, therefore the script didn't error out, so with the parameters you passed it just ignored the `--busco_seed_species` as well as `--busco_db`.   

If you want to train `augustus` using BUSCO, then don't provide the script RNA-seq data.  The `--busco_seed_species` should be a value from `funannotate species` which is simply pulling the pre-trained augustus folders in your local environment.  The script will exit if the argument you pass to `--busco_seed_species` is not present on your system and let you know why.  The `--busco_seed_species` is an option for BUSCO -- it determines which starting parameters to use for the first pass of BUSCO prediction.  It makes some preliminary predictions and then uses those to refine the parameters for your particular genome.  So the closest pre-trained organism that is present should be used, i.e. `funannotate species`. 

The `--busco_db` option dictates which models are used for BUSCO.  This parameter is then also used in `funannotate annotate` as well as `funannotate compare`. You can see which are available with this command:
```
$ funannotate outgroups --show_buscos
-----------------------------
BUSCO DB tree: (# of models)
-----------------------------
eukaryota (303)
        metazoa (978)
                nematoda (982)
                arthropoda (1066)
                        insecta (1658)
                        endopterygota (2442)
                        hymenoptera (4415)
                        diptera (2799)
                vertebrata (2586)
                        actinopterygii (4584)
                        tetrapoda (3950)
                        aves (4915)
                        mammalia (4104)
                euarchontoglires (6192)
                        laurasiatheria (6253)
        fungi (290)
                dikarya (1312)
                        ascomycota (1315)
                                pezizomycotina (3156)
                                        eurotiomycetes (4046)
                                        sordariomycetes (3725)
                                        saccharomycetes (1759)
                                                saccharomycetales (1711)
                        basidiomycota (1335)
                microsporidia (518)
        embryophyta (1440)
        protists (215)
                alveolata_stramenophiles (234)
```
Note that these need to be installed with `funannotate setup`, specifically the `--busco_db` option of `funannotate setup`: 
```
$ funannotate setup

Usage:       funannotate setup <arguments>
version:     XXXXX

Description: Script will download/format necessary databases for funannotate.

Options:     -i, --install    Download format databases. Default: all
                              [merops,uniprot,dbCAN,pfam,repeats,go,
                               mibig,interpro,busco_outgroups,gene2product]
             -b, --busco_db   Busco Databases to install. Default: dikarya [all,fungi,aves,etc]
             -d, --database   Path to funannotate databse
             -u, --update     Check remote md5 and update if newer version found
             -f, --force      Force overwriting database
```

**Comment by EarlyEvol** [comment]
Thanks, that makes sense.
