### ISSUE TITLE
ploidy documentation question

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#255]
Dear Jon,

firstly excellent tool!! Thanks. 

Would you please add some notes to the documentation about ploidy. I know the default is:
--ploidy 1 .  But I cant find anywhere if 1 = haploid and 2 = diploid.   or if 0 is haploid?

cheers,

Pete

**Comment by hyphaltip** [comment]
haploid=1 diploid=2 this factors in how many copies of putatively single-copy genes are expected.

**Comment by peterthorpe5** [comment]
Excellent thank you very much.

Pete
________________________________
