### ISSUE TITLE
custom annotations

### ISSUE THREAD

**Issue by EarlyEvol** [nextgenusfs/funannotate#261]
Jon,

I finally have everything working and am on the home stretch.

I'm wondering if you have any suggestions on how to add custom functional annotations.  Basically I want to try to get rid of a bunch of predicted gene models that seem inaccurate, so I thought adding alignments to related refseq entries during ```funannotate annotate``` would be a good start. Then, if there are no annotations added by the normal pipeline, I could just search the final gff for a flag that's added from the RefSeq alignments.  Also, I thought while I'm at it I should add them during ```predict``` too.  
Adding to extra protiens to predict seems straightforward:
```
# does this mean DIAMOND will search for hym_reseq_prot.dmnd and uniprot.dmnd in FUNANNOTATE_DB?
funannotate predict -i ${asm1%.*}.srt.msk.fasta --species "$species" --strain $SAMPLE.1 \
 --repeats2evm --cpus $threads --organism other --optimize_augustus \
 --protein_evidence hym_refseq_prot.fa uniprot.fa  
 --max_intronlen 50000 -o $fun_out.retrainNannot.50kIntron
```
But adding functional annotations (or just protein hits) from a custom fasta is less clear to me.
Do I need to run ```diamond``` against Basename.proteins.fa separately then digest those alignments into tsv format for ```funannotate annotate --annotations```? 
If I write a script to do it, what are the three columns expected for the ```--annotations custom_hits.tsv```? 
FUN_00001-T1    subject_ID    hit_score?
(This is probably a dumb question, sorry)

Thanks,
Earl

**Comment by nextgenusfs** [comment]
The protein evidence option in `predict` is what is fed into the `diamond/exonerate` pipeline, this is mapping proteins to the genome sequences (DNA).  You likely just want to do a `blastp` search of protein models that are output by `funannotate predict`.  So you could search them against anything you deem "reasonable" and setup some filtering options that you think are okay. If you find some models that you want to get rid of, you can use `funannotate fix` for that, i.e. passing a list of gene ids to remove to the `--drop` option.  This will archive your old output from `predict` and generate new GBK, protein fasta file, etc. 

The custom annotations in `funannotate annotate -a` are what will be added to the annotation, in other words this could be any annotation that you want and the format is that of tab delimited format -- for examples look at the files in `annotate_misc` that have 'annotations' in the file name. If you are submitting to NCBI, these annotations need to conform to what is in the NCBI annotation documentation about which terms are allowed, etc.

**Comment by EarlyEvol** [comment]
That's awesome, thanks.  I guess if I am trying to kick out erroneous gene models, adding more evidence during ```predict``` wouldn't really help anything.  

I'm super glad you told me about ```funannotate fix --drop```, that makes the whole process really painless!

I ran ```fix``` on a drop_file with only one gene model and it worked as expected, except the ```genus_species_sample``` file prefixes got switched to just ```genus_species``` in the output folder.  Do you know where the new prefix is getting set?  I tried ```--species --strain``` but they are unrecognized by ```funannotate fix```.

Thanks for all your help.
