### ISSUE TITLE
Augustus optimize folder wrong location?

### ISSUE THREAD

**Issue by timkahlke** [nextgenusfs/funannotate#265]
Version v1.5.2-8a16cb0
OS Ubuntu 16.04

I just ran `funannotate predict` among others with `-optimize_augustus` and was unable to run `funannotate update` afterwards. Reason is that the `predict_*` folders are not in the output directory but in a directory called `ptimize_augustus` (missing "o" intended) in the working directory. Is this wanted?

I copied the folders `predict_misc` and `predict_result` into the usual output directory and now `funannotate update` runs properly.

**Comment by nextgenusfs** [comment]
I'm not sure how thats possible? What command did you pass?

**Comment by nextgenusfs** [comment]
Oh you probably passed -optimize_augustus and it was interpreted as -o or out folder. Should be —optimize_augustus.
