### ISSUE TITLE
funannotate iprscan: Docker is not installed, exiting.

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#267]
**Are you using the latest release?**
docker version 1.5.0

**Describe the bug**
ipscan fails straight away

**What command did you issue?**
$ funannotate iprscan -i fun_newton -m docker -c 6        
Running InterProScan5 on 19680 proteins
Docker is not installed, exiting.
linuxbrew@d8f47948512e:~/data/funannotate$ echo $FUNANNOTATE_DB                                    
/home/linuxbrew/DB

Dear Jon,

I am sorry to keep pestering you. I seem to have come across another issue with the docker image ...
Does this error mean anything to you?
$ funannotate iprscan -i fun_newton -m docker -c 6        
Running InterProScan5 on 19680 proteins
Docker is not installed, exiting.
regards,

Pete

**Comment by nextgenusfs** [comment]
That script won’t work inside the funannotate docker container. It basically launches a docker container that has interproscan or it can run a local installation. I couldn’t package up interproscan with funannotate as the size is already very large, interproscan is very large in itself. 

You might be able to run the interproscan remote search using EBI servers, that’s located in funannotate remote command. But if you also have internet connectivity problems with docker that isn’t going to work either. 

I’ve probably said this before, but if you are on Linux you will have fewer headaches if you just installed funannotate locally than use the docker image. I added the docker image as it was a user request.

**Comment by peterthorpe5** [comment]
Hi Jon,

Thank you very much for your reply. I have to say the docker image has been great so far!! Thanks for the heads up. I will see what damage I can do outside of the image.

Cheers,

Pete
