### ISSUE TITLE
"Hypothetical protein" in every proteins

### ISSUE THREAD

**Issue by Maximepm** [nextgenusfs/funannotate#27]
Hi,
The annotation went well but in the output .gbk file, every protein is an hypothetical protein, like this:
/product="hypothetical protein"

Is this normal? What can I do to fix it?

Thanks!

**Comment by nextgenusfs** [comment]
Did you run the `funannotate annotate` command as well?  I'm assuming yes.  Basically NCBI has a lot of rules when it comes to gene names and product descriptions, so if you try to do this automated (e.g. through funannotate) you end up with a lot of errors during NCBI submission.  Funannotate will put some information in the protein_desc field that could work in the product field, however these need to be manually curated as lots of words will cause errors in the `tbl2asn` submission program (you can review those errors in the discrepancy report.  If you have gene product descriptions for, you can add them manually by creating a tab delimited file and re-running the `funannotate annotate` command.  The script will re-use existing annotation which by default is found in the `annotate_misc` output folder - you need to pass a 3 column file that has the filename that starts with `annotations` (e.g. `annotations.products.txt`) that looks like this:
```
mRNAid<tab>product<tab>Product description
```
specific example:
```
VC83_00005-T1	product	STE/STE7 protein kinase
VC83_00032-T1	product	NEK protein kinase
VC83_00007-T1	product	phosphoglycerate mutate
```
Note that this is the mRNA-ID and not the gene-ID, which means you will likely need a `-T1` at the end of the gene name.  You can see examples of these files in the `annotate_misc` folder from the various databases where funannotate pulled annotation information.

**Comment by Maximepm** [comment]
Thank you very much for this answer!
