### ISSUE TITLE
phobius line split: Not "\t" for me. 

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#270]
**Are you using the latest release?**
1.5.0

Hi Jon,

I have found a potential problem with parsing phobius run else where:
line 3879   /lib/library.py
    with open(phobius, 'rU') as input1:
        for line in input1:
            line = line.replace('\n', '')
            if line.startswith('ID\t'):
                continue
**cols = line.split('\t')**

For me phobius data is not tab separated. 

if "\t" in line:
    cols = line.split('\t')
else:
   cols = line.split()

This changed worked for me. 
cheers,

Pete

**Comment by nextgenusfs** [comment]
Did you run with -short option?

**Comment by peterthorpe5** [comment]
Yes, command I run on our server:

perl ./apps/phobius/phobius.pl -short \
Gpal_newtontest03_newton.proteins.fa  > Gp_newton.phobius

I have noticed this behaviour before when redirecting to a file.

Cheers,

Pete
