### ISSUE TITLE
greater than ~90% of exons supported, this is really stringent which is what we want here,

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#273]
**Are you using the latest release?**
docker image 1.5.0

**Describe the bug**
[10:40 AM]: Pulling out high quality Augustus predictions
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-predict.py", line 1074, in <module>
    if float(values[1]) > 89: #greater than ~90% of exons supported, this is really stringent which is what we want here, as we are going to weight these models 5 to 1 over genemark
IndexError: list index out of range

similar to issue  #252 (if I try deleting predict_misc - the issue remains).

**What command did you issue?**
funannotate predict -i Gp_Newton_haplotype1.softmaked.fasta -o final_newton --species Gpal_newton --strain newton --cpus 6 --max_intronlen 15000 --organism other --busco_db nematoda --database /home/linuxbrew/data/databases/ --organism other --augustus_species GPAL_newton_softmasked20rounds --rna_bam Gp_finalAligned.sortedByCoord.out.bam --name GPALNEWT --ploidy 2 --SeqCenter Norway --genemark_gtf genemark.gtf --augustus_gff augustus.hints.gff3

**OS/Install Information**
OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.14

Dear Jon,
(Once again I am a massive fan of this software - GREAT WORK!!!!!)

For reasons which will bore you I am starting again with my prediction. I got it to work before (without the DIAMOND and Swiss prot searching). This failed due to a non-acsii character (not reproducible error!!). But it did mean that the whole process worked. 

Now, once the DIAMOND search is completed I get the following error (this seems to be before it run Augustus): 

 if float(values[1]) > 89: #greater than ~90% of exons supported, this is really stringent which is what we want here, as we are going to weight these models 5 to 1 over genemark  .... I have tried forcing diamond to fail, but this error keeps coming back. 

As suggested in issue #252: if I try deleting predict_misc - the issue remains.

I see that the docker image for 1.5.2 is available I will try this. And report if the issue remains. 

cheers,

Pete

**Comment by peterthorpe5** [comment]
yes, still the same issue with the latest docker image (downloaded 01st March 2019)

**Comment by nextgenusfs** [comment]
Okay do same method to debug as I reported before. Can you look at the Augustus output and show a few gene models, this is in predict_misc and the augustus.gff3.  If that file is empty than look in the logfile and get the command it issues to run Augustus in parallel and then manually execute that command to see if there are any additional errors.

**Comment by peterthorpe5** [comment]
that fixed it. Thanks.
