### ISSUE TITLE
Use os.sched_getaffinity(0) to grab available cpu count?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [nextgenusfs/funannotate#276]
When available (always in Linux?), it's more accurate to use `os.sched_affinity(0)` to grab the CPU count, since this will describe the set of cores actually available to the process (and kids).

Not crucial, but worst case this could start N parallel processes when only a single CPU is available for use (due to the CPU mask).  This would not be uncommon in an HPC environment.

```
$ python3
Python 3.7.1 (default, Dec 14 2018, 19:28:38)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, multiprocessing
>>> multiprocessing.cpu_count()
28
>>> os.sched_getaffinity(0)
{1, 3, 5, 7}
>>> len(os.sched_getaffinity(0))
4
```

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.cpu_count

**Comment by nextgenusfs** [comment]
And this works on python2?  Code is not py3 compatible at the moment.

**Comment by michaelkarlcoleman** [comment]
Whoops, missed the Python2.  And Unix (Linux) only for Python3.  Closing...
