### ISSUE TITLE
Missing Dependencies: BuildDatabase

### ISSUE THREAD

**Issue by rodriguez-salarichs** [nextgenusfs/funannotate#28]
Hi

Trying to run the sample_data example, I have the following:

[03:30:16 PM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.12
[03:30:16 PM]: Running funannotate v.0.3.7
[03:30:16 PM]: Missing Dependencies: BuildDatabase.  Please install missing dependencies and re-run script

I checked correct installation of dependencies and libraries with commands 
funannotate setup -all 
      and
./setup

Further, I checked that the /usr/local/funannotate/DB symbolic link is pointing to the directory with DB files.   
 
ls -hslt /usr/local/funannotate/DB

0 lrwxrwxrwx 1 root root 31 sep 27 15:16 /usr/local/funannotate/DB -> /media/DATA/DB_funannotate

I do not know what the problem is

Thanks,
Javier

**Comment by nextgenusfs** [comment]
`BuildDatabase` is part of the `RepeatModeler` program, likely your repeatmodeler/repeatmasker installation is wrong. You can try to re-install with linuxbrew, e.g. `brew reinstall repeatmodeler` and see if you get any errors.  You also need to install the RepeatMasker libraries, did you figure that part out?

**Comment by rodriguez-salarichs** [comment]
Hi

I did not use linuxbrew, sorry. But I already understood what the problem was. BuildDatabase is a program within RepeatModeler and funannotate could not find it.

I solved this problem making a softlink of /usr/local/RepeatModeler/BuildDatabase at /usr/local/bin.

ln -s /usr/local/RepeatModeler/BuildDatabase /usr/local/bin

Now, RepeatModeler is working perfectly. 

Thanks

Javier
