### ISSUE TITLE
also have error in funannotate predict and annotate

### ISSUE THREAD

**Issue by gengce** [nextgenusfs/funannotate#281]
(python2) [root@localgc 1Genome_quast_introduction]# funannotate test -t annotate
#########################################################
Running `funannotate annotate` unit testing
Downloading: https://osf.io/97pyn/download?version=1 Bytes: 341476
CMD: funannotate annotate --genbank Genome_one.gbk -o annotate --cpus 2 --iprscan genome_one.iprscan.xml --eggnog genome_one.emapper.annotations
#########################################################
-------------------------------------------------------
[12:10 PM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[12:10 PM]: Running funannotate v1.5.3
[12:10 PM]: Database files not found in /home/funannotate/FunDB, run funannotate database and/or funannotate setup
#########################################################
ERROR: `funannotate annotate` test failed - check logfiles
#########################################################

(python2) [root@localgc 1Genome_quast_introduction]# funannotate test -t annotate -check logfiles
usage: funannotate-test.py [-h] -t
                           {all,clean,mask,predict,annotate,busco,rna-seq,compare}
                           [{all,clean,mask,predict,annotate,busco,rna-seq,compare} ...]
                           [--cpus CPUS]
funannotate-test.py: error: unrecognized arguments: -check logfiles
(python2) [root@localgc 1Genome_quast_introduction]# funannotate test -t predict
#########################################################
Running `funannotate predict` unit testing
Downloading: https://osf.io/te2pf/download?version=1 Bytes: 1489808
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 2 --species Awesome testicus
#########################################################
-------------------------------------------------------
[12:11 PM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[12:11 PM]: Running funannotate v1.5.3
[12:11 PM]: Augustus training set for saccharomyces already exists. To re-train provide unique --augustus_species argument
[12:11 PM]: AUGUSTUS (3.2.3) detected, version seems to be compatible with BRAKER and BUSCO
[12:11 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[12:11 PM]: Genome loaded: 6 scaffolds; 3,776,588 bp; 19.75% repeats masked
[12:11 PM]: Mapping proteins to genome using Diamond blastx/Exonerate
[12:11 PM]: Using 1,065 proteins as queries
[12:11 PM]: Running Diamond pre-filter search
[12:11 PM]: Found 1,774 preliminary alignments
[12:12 PM]: Exonerate finished: found 1,341 alignments
Traceback (most recent call last):
  File "/home/funannotate/bin/funannotate-p2g.py", line 275, in <module>
    lib.SafeRemove(tmpdir)
  File "/home/funannotate/lib/library.py", line 686, in SafeRemove
    shutil.rmtree(input)
  File "/root/miniconda3/envs/python2/lib/python2.7/shutil.py", line 270, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/root/miniconda3/envs/python2/lib/python2.7/shutil.py", line 268, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: 'p2g_19893'
Traceback (most recent call last):
  File "/home/funannotate/bin/funannotate-predict.py", line 654, in <module>
    lib.runSubprocess5(cmd, '.', lib.log, allhintstmp_sort, hints_all)
  File "/home/funannotate/lib/library.py", line 732, in runSubprocess5
    proc = subprocess.Popen(cmd, cwd=dir, stdin=infile, stdout=out, stderr=subprocess.PIPE)
  File "/root/miniconda3/envs/python2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/root/miniconda3/envs/python2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
#########################################################
Traceback (most recent call last):
  File "/home/funannotate/bin/funannotate-test.py", line 334, in <module>
    runPredictTest()
  File "/home/funannotate/bin/funannotate-test.py", line 168, in runPredictTest
    assert 1500 <= countGFFgenes(os.path.join(tmpdir, 'annotate', 'predict_results', 'Awesome_testicus.gff3')) <= 1700
  File "/home/funannotate/bin/funannotate-test.py", line 58, in countGFFgenes
    with open(input, 'rU') as f:
IOError: [Errno 2] No such file or directory: 'test-predict_19800/annotate/predict_results/Awesome_testicus.gff3'

_**the error told me :"Database files not found in /home/funannotate/FunDB, run funannotate database and/or funannotate setup",But indeed I have setup database**_
(python2) [root@localgc 1Genome_quast_introduction]# funannotate setup -u -b fungi  -d /home/funannotate/FunDB -u
-------------------------------------------------------
[09:57 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[09:57 AM]: Running funannotate v1.5.3
[09:57 AM]: Database location: /home/funannotate/FunDB
[09:57 AM]: Checking for newer versions of database files
[09:58 AM]: merops database is current.
[09:58 AM]: MEROPS Database: version=12.0 date=2017-10-04 records=4,968
[09:58 AM]: uniprot-release database is current.
[09:58 AM]: UniProtKB Database: version=2019_02 date=2019-02-13 records=559,228
[10:00 AM]: dbCAN database is current.
[10:00 AM]: dbCAN Database: version=7.0 date=2018-08-25 records=607
[10:00 AM]: pfam-log database is current.
[10:00 AM]: Pfam Database: version=32.0 date=2018-08 records=17,929
[10:00 AM]: repeats database is current.
[10:00 AM]: Repeat Database: version=1.0 date=2019-03-25 records=11,950
[10:02 AM]: go-obo database is out of date, updating.
[10:02 AM]: Downloading GO Ontology database
[10:02 AM]: Downloading: http://purl.obolibrary.org/obo/go.obo Bytes: 34091323
[10:03 AM]: GO ontology version=2019-03-19 date=2019-03-19 records=47,362
[10:04 AM]: mibig database is current.
[10:04 AM]: MiBIG Database: version=1.4 date=2019-03-25 records=31,023
[10:07 AM]: interpro database is current.
[10:07 AM]: InterProScan XML: version=73.0 date=2019-03-21 records=36,702
[10:07 AM]: outgroups not found in database
[10:07 AM]: Downloading pre-computed BUSCO outgroups
[10:07 AM]: Downloading: https://osf.io/r9sne/download?version=1 Bytes: 2374032
[10:07 AM]: BUSCO outgroups: version=1.0 date=2019-03-28 records=8
[10:07 AM]: gene2product database is current.
[10:07 AM]: Gene2Product: version=1.31 date=2019-02-20 records=26,139
[10:07 AM]: Downloading busco models: fungi
[10:07 AM]: Funannoate setup complete. Add this to ~/.bash_profile or ~/.bash_aliases:

	export FUNANNOTATE_DB=/home/funannotate/FunDB

(python2) [root@localgc 1Genome_quast_introduction]# export FUNANNOTATE_DB=/home/funannotate/FunDB
(python2) [root@localgc 1Genome_quast_introduction]# funannotate database

Funannotate Databases currently installed:

  Database          Type        Version      Date         Num_Records   Md5checksum                     
  pfam              hmmer3      32.0         2018-08            17929   de7496fad69c1040fd74db1cb5eef0fc
  gene2product      text        1.31         2019-02-20         26139   fd87019053c59ed6b4162e0ca5633c89
  interpro          xml         73.0         2019-03-21         36702   9e1b0aeb614451d08ca4e3688b844c64
  dbCAN             hmmer3      7.0          2018-08-25           607   51c724c1f9ac45687f08d0faa689ed58
  busco_outgroups   outgroups   1.0          2019-03-28             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          4968   d923f0177c6d27c3d2886c705347adc0
  mibig             diamond     1.4          2019-03-25         31023   118f2c11edde36c81bdea030a0228492
  uniprot           diamond     2019_02      2019-02-13        559228   7b42b43b6a9cc28f2424d2fa73ae4852
  go                text        2019-03-19   2019-03-19         47362   00575e6917279fc76cfd1b076406d1ac
  repeats           diamond     1.0          2019-03-25         11950   4e8cafc3eea47ec7ba505bb1e3465d21

To update a database type:
	funannotate setup -i DBNAME -d /home/funannotate/FunDB --force

**Comment by nextgenusfs** [comment]
What version of diamond and version of exonerate?  Would be helpful to post output of funannotate check —show-versions

**Comment by gengce** [comment]
(python2) [root@localgc annotatation]# funannotate annotate --gff comp_genemark.gff3 --fasta coemp.fa -s "Coleophoma empetri" -o FUNcolemp
-------------------------------------------------------
[02:44 PM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[02:44 PM]: Running funannotate v1.5.3
[02:44 PM]: **Database files not found in /home/funannotate/FunDB, run funannotate database and/or funannotate setup**
(python2) [root@localgc annotatation]# funannotate database

Funannotate Databases currently installed:

  Database          Type        Version      Date         Num_Records   Md5checksum                     
  pfam              hmmer3      32.0         2018-08            17929   de7496fad69c1040fd74db1cb5eef0fc
  gene2product      text        1.32         2019-03-27         26175   3278dd8de7513e0ba2d6f3f3f1e0b1fd
  interpro          xml         73.0         2019-03-21         36702   9e1b0aeb614451d08ca4e3688b844c64
  dbCAN             hmmer3      7.0          2018-08-25           607   51c724c1f9ac45687f08d0faa689ed58
  busco_outgroups   outgroups   1.0          2019-03-29             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          4968   d923f0177c6d27c3d2886c705347adc0
  mibig             diamond     1.4          2019-03-25         31023   118f2c11edde36c81bdea030a0228492
  uniprot           diamond     2019_02      2019-02-13        559228   7b42b43b6a9cc28f2424d2fa73ae4852
  go                text        2019-03-19   2019-03-19         47362   00575e6917279fc76cfd1b076406d1ac
  repeats           diamond     1.0          2019-03-25         11950   4e8cafc3eea47ec7ba505bb1e3465d21

To update a database type:
	funannotate setup -i DBNAME -d /home/funannotate/FunDB --force

(python2) [root@localgc annotatation]# funannotate check --vesion
-------------------------------------------------------
^[[AChecking dependencies for funannotate v1.5.3
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
All 27 Perl modules installed


Checking external dependencies...
All 32 external dependencies are installed

Checking Environmental Variables...
All 7 environmental variables are set
-------------------------------------------------------

**Comment by gengce** [comment]
I am so sorry for not show the dependencies versions
(python2) [root@localgc annotatation]# funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.5.3
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.72
goatools: 0.8.12
matplotlib: 2.2.3
natsort: 6.0.0
numpy: 1.16.2
pandas: 0.24.2
psutil: 5.6.1
requests: 2.21.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.50
Clone: 0.41
DBD::SQLite: 1.60
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.843
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.37
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.11
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.27
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking external dependencies...
CodingQuarry: 2.0
RepeatMasker: RepeatMasker version development-$Id: RepeatMasker,v 1.332 2017/04/17 19:01:11 rhubley Exp $
RepeatModeler: RepeatModeler 1.0.11
Trinity: 2.5.1
augustus: 3.2.3
bamtools: bamtools 2.4.1
bedtools: bedtools v2.27.1
blat: BLAT v36
diamond: diamond 0.9.24
emapper.py: emapper-1.0.3-3-g3e22728
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
gmap: 2018-07-04
gmes_petap.pl: 4.38
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 1.8.0_121
kallisto: 0.44.0
mafft: v7.427 (2019/Mar/24)
makeblastdb: makeblastdb 2.6.0+
minimap2: 2.16-r922
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.6.0+
samtools: samtools 1.9
stringtie: 1.3.5
tRNAscan-SE: 2.0.2 (February 2019)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.6.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
All 32 external dependencies are installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/funannotate/FunDB
$PASAHOME=/root/PASApipeline
$TRINITYHOME=/root/Trinity
$EVM_HOME=/root/evidencemodeler
$AUGUSTUS_CONFIG_PATH=/root/miniconda3/pkgs/augustus-3.2.3-boost1.60_0/config
$GENEMARK_PATH=/opt/biosoft/gm_et_linux_64/gmes_petap
$BAMTOOLS_PATH=/root/bamtools
All 7 environmental variables are set
-------------------------------------------------------

**Comment by nextgenusfs** [comment]
Hmmm, nothing seems out of place...  What OS and version?  Are you on a mounted file structure? Could you also list the files in the funannotate database location, ie ls -l $FUNANNOTATE_DB

**Comment by gengce** [comment]
**Every time I must export the DB location again.**  My emapper database base have been moved to other place, have the effect on the **annotate** ? (python2) [root@localgc FunDB]# export FUNANNOTATE_DB=/home/funannotate/FunDB \
> export PASAHOME=/root/PASApipeline \
> export TRINITYHOME=/root/Trinity \
> export EVM_HOME=/root/evidencemodeler \
> export AUGUSTUS_CONFIG_PATH=/root/miniconda3/pkgs/augustus-3.2.3-boost1.60_0/config \
> export GENEMARK_PATH=/opt/biosoft/gm_et_linux_64/gmes_petap \
> export BAMTOOLS_PATH=/root/bamtools
(python2) [root@localgc FunDB]#  ls -l $FUNANNOTATE_DB总用量 2313824
drwxr-xr-x. 5 1046  1200        147 2月  14 2017 actinopterygii
drwxr-xr-x. 5 1046  1200        147 11月 18 2016 alveolata_stramenophiles
drwxr-xr-x. 5 1046  1200        147 11月  1 2016 arthropoda
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 ascomycota
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 aves
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 basidiomycota
-rwxrwxrwx. 1 root root     2374032 3月  29 14:34 busco_outgroups.tar.gz
-rwxrwxrwx. 1 root root        6082 3月  28 14:57 dbCAN.changelog.txt
-rwxrwxrwx. 1 root root       59480 3月  28 14:57 dbCAN-fam-HMMs.txt
-rwxrwxrwx. 1 root root    87670624 3月  28 14:57 dbCAN.hmm
-rwxrwxrwx. 1 root root       26459 7月   4 2018 dbCAN.hmm.h3i
drwxrwxrwx. 5 root root         147 2月  13 2017 dikarya
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 diptera
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 endopterygota
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 euarchontoglires
drwxr-xr-x. 5 1046  1200        147 11月  2 2016 eukaryota
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 eurotiomycetes
-rwxrwxrwx. 1 root root        1068 3月  29 14:34 funannotate-db-info.txt
-rw-r--r--. 1  501 games   11017103 3月   2 2016 funannotate.repeat.proteins.fa
-rwxrwxrwx. 1 root root    11017079 3月  25 18:02 funannotate.repeats.reformat.fa
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 fungi
-rwxrwxrwx. 1 root root    34091323 3月  28 10:03 go.obo
drwxr-xr-x. 3 root root          21 3月  26 12:29 hmmdb_levels
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 hymenoptera
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 insecta
-rw-r--r--. 1 root root   168332787 3月  28 09:26 interpro.xml
drwxr-xr-x. 3 1046  1200         18 2月  13 2017 laurasiatheria
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 mammalia
-rwxrwxrwx. 1 root root     1434038 3月  25 18:04 merops.dmnd
-rwxrwxrwx. 1 root root     1372931 3月  25 18:04 merops.formatted.fa
-rwxrwxrwx. 1 root root     1942655 3月  25 18:04 merops_scan.lib
drwxr-xr-x. 5 1046  1200        182 2月  13 2017 metazoa
-rwxrwxrwx. 1 root root    21740850 3月  25 17:57 mibig.dmnd
-rwxrwxrwx. 1 root root    21244378 3月  25 17:57 mibig.fa
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 microsporidia
-rwxrwxrwx. 1 root root     1037981 3月  28 15:00 ncbi_cleaned_gene_products.txt
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 nematoda
drwxr-xr-x. 2  501 games       4096 12月  5 2016 outgroups
drwxr-xr-x. 3 1046  1200         18 2月  13 2017 pezizomycotina
-rw-r--r--. 1 root root     1041991 3月  25 17:14 Pfam-A.clans.tsv
-rw-r--r--. 1 root root  1434541235 3月  25 17:13 Pfam-A.hmm
-rwxrwxrwx. 1 root root     1153233 7月   4 2018 Pfam-A.hmm.h3i
-rw-r--r--. 1 root root         111 3月  25 17:14 Pfam.version
drwxr-xr-x. 5 1046  1200        147 11月 18 2016 protists
-rwxrwxrwx. 1 root root    11090223 3月  25 18:02 repeats.dmnd
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 saccharomycetales
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 saccharomycetes
drwxr-xr-x. 5 1501  1200        147 2月  13 2017 sordariomycetes
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 tetrapoda
-rwxrwxrwx. 1 root root   281991405 3月  25 18:08 uniprot.dmnd
-rwxrwxrwx. 1 root root         151 3月  25 18:08 uniprot.release-date.txt
-rw-r--r--. 1 root root   276112349 3月  25 18:07 uniprot_sprot.fasta
drwxr-xr-x. 5 1046  1200        147 2月  13 2017 vertebrata
 **My OS version:**
(python2) [root@localgc FunDB]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

(python2) [root@localgc FunDB]#  lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core

**Comment by gengce** [comment]
**annotate problem still exsit, and I laso moved the  files that need be annotated to root files.**
(python2) [root@localgc COEMP]# pwd
/root/COEMP
(python2) [root@localgc COEMP]# ls
coemp.fa  comp_genemark.gff3  funannotate-annotate.log  funannotate-setup.log
(python2) [root@localgc COEMP]# funannotate annotate --gff comp_genemark.gff3 --fasta coemp.fa -s "Coleophoma empetri" -o FUNcolemp
-------------------------------------------------------
[10:33 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[10:33 AM]: Running funannotate v1.5.3
[10:33 AM]: Database files not found in /home/funannotate/FunDB, run funannotate database and/or funannotate setup
(python2) [root@localgc COEMP]# funannotate database

Funannotate Databases currently installed:

  Database          Type        Version      Date         Num_Records   Md5checksum                     
  pfam              hmmer3      32.0         2018-08            17929   de7496fad69c1040fd74db1cb5eef0fc
  gene2product      text        1.32         2019-03-27         26175   3278dd8de7513e0ba2d6f3f3f1e0b1fd
  interpro          xml         73.0         2019-03-21         36702   9e1b0aeb614451d08ca4e3688b844c64
  dbCAN             hmmer3      7.0          2018-08-25           607   51c724c1f9ac45687f08d0faa689ed58
  busco_outgroups   outgroups   1.0          2019-03-29             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          4968   d923f0177c6d27c3d2886c705347adc0
  mibig             diamond     1.4          2019-03-25         31023   118f2c11edde36c81bdea030a0228492
  uniprot           diamond     2019_02      2019-02-13        559228   7b42b43b6a9cc28f2424d2fa73ae4852
  go                text        2019-03-19   2019-03-19         47362   00575e6917279fc76cfd1b076406d1ac
  repeats           diamond     1.0          2019-03-25         11950   4e8cafc3eea47ec7ba505bb1e3465d21

To update a database type:
	funannotate setup -i DBNAME -d /home/funannotate/FunDB --force

(python2) [root@localgc COEMP]# funannotate setup -d /home/funannotate/FunDB -b fungi
-------------------------------------------------------
[10:33 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[10:33 AM]: Running funannotate v1.5.3
[10:33 AM]: Database location: /home/funannotate/FunDB
[10:33 AM]: MEROPS Database: version=12.0 date=2017-10-04 records=4,968
[10:33 AM]: UniProtKB Database: version=2019_02 date=2019-02-13 records=559,228
[10:33 AM]: dbCAN Database: version=7.0 date=2018-08-25 records=607
[10:33 AM]: Pfam Database: version=32.0 date=2018-08 records=17,929
[10:33 AM]: Repeat Database: version=1.0 date=2019-03-25 records=11,950
[10:33 AM]: GO ontology version=2019-03-19 date=2019-03-19 records=47,362
[10:33 AM]: MiBIG Database: version=1.4 date=2019-03-25 records=31,023
[10:33 AM]: InterProScan XML: version=73.0 date=2019-03-21 records=36,702
[10:33 AM]: BUSCO outgroups: version=1.0 date=2019-03-29 records=8
[10:33 AM]: Gene2Product: version=1.32 date=2019-03-27 records=26,175
[10:33 AM]: Downloading busco models: fungi
[10:33 AM]: Funannoate setup complete. Add this to ~/.bash_profile or ~/.bash_aliases:

	export FUNANNOTATE_DB=/home/funannotate/FunDB

(python2) [root@localgc COEMP]# funannotate annotate --gff comp_genemark.gff3 --fasta coemp.fa -s "Coleophoma empetri" -o FUNcolemp
-------------------------------------------------------
[10:33 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[10:33 AM]: Running funannotate v1.5.3
[10:33 AM]: Database files not found in /home/funannotate/FunDB, run funannotate database and/or funannotate setup
(python2) [root@localgc COEMP]#

**Comment by gengce** [comment]
after rerun the funannotate setup script  the database is working, thank you very much for this fantastic software. a small suggestion: can we set the gene "product name" is not the product="hypothetical protein" in  the annotate GBK format file?

**Comment by nextgenusfs** [comment]
Those that can be annotated will get a description for the product name, the naming requires a gene name in order to be in compliance with NCBI submission requirements. So the short answer is you can add whatever you want manually using custom annotations, but more than likely those won’t pass NCBI submission. I’ve tried to pull as many as possible.

**Comment by gengce** [comment]
Hi, thank you for your answer, I still do not know how to fix the product name with the file in folder annotate_misc, my command is: (**python2) [root@localgc COEMP]# funannotate annotate --gff comp_genemark.gff3 --fasta coemp.fa --eggnog coemp_protein.faa.emapper.annotations  --iprscan iprscan.xml  -s "Coleophoma empetri" --fix annotations.genes-products.txt -o FUNcolemp**
but the product name in my GBK file still hypothetical protein
