### ISSUE TITLE
Annotated gene name not match the hits by manually blast

### ISSUE THREAD

**Issue by ykjyhmj** [nextgenusfs/funannotate#284]
Hi Jon,

I came to a weird problem. The annotated gene name is not agree with the hits by NCBI or Swissport blast. Here's two example.

>CUZD1_4
MSSTNLLHSLMCVLLVTDCFSRCCITASARKVDKGEPIDNPPPVRLQGPRSSNGTGRVEVYYNGEWGTICDDSWDLRDAEVICRQLGYDYAVRALKGSNVPDGSGRIWLDDVRCVGNESNISSCSHRGWGSHNCGHHEDAGVQCSVVNSVRLRGPKRSSGRGRVEVFYNGEWGTICDDSWDIKDAKVVCRQLGYKYAVSALQGGNVPDGSGRIWLDDVRCVGNENNISSCSHRGWGSHNCGHHKDAGVKCSGFNFVRLRGPKSSCGRGRVEVFYNEEWGTICDDSWDLKDAIVVCRQLGYDYAVSALKGSSVLDGRGKIWLDDVRCVGNENNISSCSHRGWGTHNCRHHKDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGYDYAVSALQGGNVPDGRGQIWLDDVRCVGNENNISSCSHSGWGSHDCRHYEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKEAKVVCRQLGYDYAVSALQGGNVPDGSGQIWLDDVRCVGNENNISSCSHRGWGTHNCGHHEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGYACCQCFTRKGWGSHNCTHDEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGYDYAVSALKGSSVPDGRGKIWLDDVRCVGNENNISSCSHRGWGTHNCGHHEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGYDYAVSALQGGNVPDGRGQIWLDDVRCVGNENNISSCSHSGWGSHNCGHDEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCLQLGYDYAVSALKGSSVPDGRGKIWLDDVRCVGNENNISSCSHRGWGTHNCGHHEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFFNGEWGTICDDSWDLKDAKVVCRQLGLGAATSALQGSHVPDGSGRIWLDDVRCVGNENNISSCSHRGWGSHNCEHDEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGLGAATSALQGSHVPDGSGRIWLDDVRCVGNENTISSCSHRGWGSHNCGHNEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGYDYAVSALQGGNVPDGSGRIWLDDVRCVGNENNISSCSHSGWGSHNCGHDEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGQWGTICDDSWDIKDAKVVCRQLGLGAATSALQGSHVPDGSGRIWLDDVRCVGNENNISSCSHSGWGSHNCGHDEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGQWGTICDDSWDIKDAKVVCRQLGLGAATSALQGGNVPDGSGRIWLDDVRCVGNENNISSCSHRGWGSHNCTHEEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCLQLGYDYAVSALQGGDVPDGSGRIWLDDVRCVGNENNISSCSHSGWGSHNCGHDEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGLMTTSALQGGNVPDGSGRIWLDDVRCVGNENNISSCSHRGWGSHNCTHDEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGYEYAVSALQGGDVPDGRGQIWLDDVRCVGNENNISSCSHSGWGSHNCGHDEDAGVQCSVVNSVRLRGSKRSSGRGRVEVFYNGEWGTICDNSWDIKDAKVVCRQLGLGEATSALQGSHVPDGSGRIWLDDVRCVGNENNILSCSHGGWGTHNCTHYEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAEVVCRQLGYDYAVSALQGGDVPDGRGQIWLDDVRCVGNENNISSCSHSGWGSHNCGHDEDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLNDAKVVCRQLGYDYAVSALQGGNVPDGSGRIWLDDVRCVGNENNISSCSHSGWGSHNCGHNEDAGVQCSVFNYVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLRYDYAVSALKGSSVPDGSGRIWLDDVRCVGNENNISSCSHRGWGTHNCTHYKDAGVQCSVVNSVRLRGPKSSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGYEYAVSALQGGDVPDGRGQIWLDDVRCVGNENNISSCSHSGWGSHNCGHDEDAGVQCSVVNSVRLRGPKRSSGRGRVEVFYNGEWGTICDDSWDLNDAEVFCRQLGYDYAVSALQGGNVPDGSGRIWLDDVRCVGNENNISSCSHSGWGSHNCGHNEDAGVQCSVFKSVRLRGPKSSSGRGRVEIFYNGEWGTICDDSWDLKDAKVVCRQLGYDYAVSALKGSSVPDGSGRIWLDDVRCVGSENNILSCSHGGWGTHNCTHYEDAGVQCSVVNSVRLRGPKSSSGRGRVEIFYNGEWGTICDDSWDIKDAKVVCRQLGLGAATSALQGSHVPDGSGRIWLDDVRCVGNENNISSCSHGGWGTHNCGHYEDAGVQCSVVNSVRLRGPKGSSGRGRVEVFYNGEWGTICDDSWDLKDAKVVCRQLGYDYAVSALKGSSVPDGSGKIWLDDVRCVGNENNISSCSHRGWGSHNCTHYEDAGVQCSGINECLQNKHNCGNNSNCINTIGSFICVCHHGFSGNGENCSANCNFDNGNICNFNNGAGEFNWTINTGPTLSYDTGPSNDTSGSGYYLYIETSSPRQHGDKATVLTPYLNGEQCMKFAYHMYGSSIGSLNIYAGSQMIFKKSGNQGNIWVFVEKFIRLNGSYMVKFEGVRGLSFQGDIAIDAISFKPGRCSLKTPKPTTQST
>CD36_2
MKACNCKICSFLLVCFGFALTISATVCILFNCFDDLIKNTIVKNVQLKNGTEAFKNWKSPSSDVYMQFFMFNLTNAKNVSDGKKPSVKQVGPYSYREIRKNVPRFFNHESNTLAYFSQKAYVFDKATSCAGCDPVKDKFVTINIPLLKLSELVKKGVDSLPHGLAILLLPLLNQFFGKEDVFRARSVSDLLWGYDDFILSRFHNFTVELNKQLKNHTLPFHVPIINSLVMLQSNNTNTSGEIHTGVGKIDRLGAYVKYNGMSTLPWWHTKWANMINGTDGTIFHPDINKGDHLPIFSSDICRSINIRYHSTVDVEGIPLYRFFAGPEQFKYNADNRAGFCNPDANSCVPDGLLDVSVCKPLNVPVVVSLPHFLFANKTVIDSVNGMHPNEEDHSTFISIEPNTGITMQANKRIQVNVALTNLTGITQFENMRTVFLPVLFVNETAVISKSDADKFKNDVLLPKKLLDIGKYVFIGVGLIIMVLGLILLRVKGRKVRHSETSVQIQNEQVGGSEKSPLMRSVQNYVTMASVSTWRKFSAFLILFGSLVFVSFMICVSYSVFDKFWKHTVEKNVQLKNGTEAFKNWKSPSSDVYMQFFMFNLTNAKNVSDGKKPSVKQVGPYSYREIRKNVPRFFNHESNTLAYFSQKAYVFDKATSCAGCDPVKDKFVTINIPLLKLSELVKKGVDSLPHGLAILLLPLLNQFFGKEDVFRARSVSDLLWGYDDFILSRFHNFTVELNKQLKNHTLPFHVPIINSLVMLQSNNTNTSGEIHTGVGKIDRLGAYVKYNGMSTLPWWHTKWANMINGTDGTIFHPDINKGDHLPIFSSDICRSINIRYHSTVDVEGIPLYRFFAGPEQFKYNADNRAGFCNPDANSCVPDGLLDVSVCKPLNVPVVVSLPHFLFANKTVIDSVNGMHPNEEDHSTFISIEPNTGITMQANKRIQVNVALTNLTGITQFENMRTVFLPVLFVNETAVISKSDADKFKNDVLLPKKLLDIGKYVFIGVGLIIMVLGLILLRVKGRKVRHSETSVQIQNEQVGGSEKSPLMRSVQNYVT

The Annotated gene names are CUZD1_4 and CD36_2, while the blast top hits are: DMBT1 and Lysosome membrane protein 2.

I can't find clear clue about how this happened. One possible I can come up is that the annotation database is not right. And I found in the funannotate database there's a uniprot fasta file named uniprot_sprot.fasta. The size is only 262M while uniprot.dmnd is only 268M. Is the default annotation only suitable with fungi? Actually, my genome is not fungi genome.

Thanks very much for any help!

Minjie

**Comment by nextgenusfs** [comment]
The raw names it came up with are located in `annotate_misc/uniprot_eggnog_raw_names.txt` --> look there to see what the hits were from SwissProt and Eggnog. If it is not a valid gene name it will ignore it.  But this is the curated UniProt/SwissProt database (not just for fungi). 

https://github.com/nextgenusfs/funannotate/blob/master/bin/funannotate-functional.py#L669-L674

**Comment by ykjyhmj** [comment]
Hi Jon,
Sorry for the delayed reply. Get super busy recently and forgot to reply here. The name matches with Eggnog. It's just wired that different database have different name.
