### ISSUE TITLE
Option to turn off seqclean

### ISSUE THREAD

**Issue by Tierhon** [nextgenusfs/funannotate#288]
**Are you using the latest release?**
Yes.

**Describe the bug**
Seqclean fails because the filesystem does not support hard linking. It is likely same as the issue described here: http://seqanswers.com/forums/showthread.php?t=8324. The filesystem is BeeGFS (https://www.beegfs.io/content/).

**Logfiles**
-= Rebuilding trinity.fasta cdb index =-
683755 entries from file trinity.fasta were indexed in file trinity.fasta.cidx
 Launching actual cleaning process:
 psx -p 16  -n 1000  -i trinity.fasta -d cleaning -C '/work/users/olekto/cod2_annotation_new/funannotate_test/trinity.fasta:ANLMS100:::11:0' -c '/cluster/home/olekto/miniconda2/opt/pasa-2.3.3/bin/seqclean.psx'
ERROR: link failed for olekto.10546.sx_file_1 to cleaning_1/olekto.10546.sx_file_1! (errno = 1)
WAITING for all children to finish before exiting!
Error at 'psx -p 16  -n 1000  -i trinity.fasta -d cleaning -C '/work/users/olekto/cod2_annotation_new/funannotate_test/trinity.fasta:ANLMS100:::11:0' -c '/cluster/home/olekto/miniconda2/opt/pasa-2.3.3/bin/seqclean.psx''

It would be nice with an option to turn off cleaning of the transcripts. It might not be strictly necessary (https://github.com/PASApipeline/PASApipeline/wiki/PASA_alignment_assembly#step-a-cleaning-the-transcript-sequences-optional). 

Thank you.

**Comment by nextgenusfs** [comment]
So you aren't interested in recompiling the "fixed" version?  I think I suggested that the fixed version get incorporated into PASA, but not sure if it has been yet: https://github.com/PASApipeline/PASApipeline/issues/87

**Comment by Tierhon** [comment]
Maybe. I've used Conda to install as many of the programs I need to run Funannotate, PASA included, and I don't like to change stuff which I will forget. In the version I have, 2.3.3, this is not fixed. That is not a surprise, since that release is a year old. I guess it still could be fixed in the next release then. 

I'll give it a go. 

Thank you.

**Comment by nextgenusfs** [comment]
Use PASA >=2.4.1 which now has the updated psx code.

**Comment by ala98412** [comment]
Hi, 
I am using PASApipeline-v2.5.2, which version is >= 2.4.1. 
But I still have this issue.

Below is my error message,
==================================================================
seqclean running options:
seqclean ../trinity_out_dir.Trinity.fasta -v /home/why/Tools/PASApipeline-v2.5.2/seqclean/UniVec.fasta
 Standard log file: seqcl_trinity_out_dir.Trinity.fasta.log
 Error log file:    err_seqcl_trinity_out_dir.Trinity.fasta.log
 Using 1 CPUs for cleaning
-= Rebuilding trinity_out_dir.Trinity.fasta cdb index =-
1474296 entries from file ../trinity_out_dir.Trinity.fasta were indexed in file trinity_out_dir.Trinity.fasta.cidx
 Launching actual cleaning process:
 psx -p 1  -n 1000  -i ../trinity_out_dir.Trinity.fasta -d cleaning -C '/home/why/Juihung/Candidia_barbatus/trinity_out_dir/seqclean/../trinity_out_dir.Trinity.fasta:ANLMS100:/home/why/Tool
s/PASApipeline-v2.5.2/seqclean/UniVec.fasta::11:0' -c '/home/why/Tools/PASApipeline-v2.5.2/bin/seqclean.psx'
 ERROR: psx: child terminated with nonzero exit status (2) - exiting!!
WAITING for all children to finish before exiting!
Error at 'psx -p 1  -n 1000  -i ../trinity_out_dir.Trinity.fasta -d cleaning -C '/home/why/Juihung/Candidia_barbatus/trinity_out_dir/seqclean/../trinity_out_dir.Trinity.fasta:ANLMS100:/home
/why/Tools/PASApipeline-v2.5.2/seqclean/UniVec.fasta::11:0' -c '/home/why/Tools/PASApipeline-v2.5.2/bin/seqclean.psx''


Process terminated with an error!
seqclean (../trinity_out_dir.Trinity.fasta) encountered an error.
================================================================

I am sorry that after I read some pages(http://seqanswers.com/forums/showthread.php?t=8324) 
about how to fix this problem, but still can not fix it.

Thank you for helping.
