### ISSUE TITLE
CodingQuarry failed, but predict completes

### ISSUE THREAD

**Issue by manabanana** [nextgenusfs/funannotate#289]
**Are you using the latest release?**
version:     1.5.3-21ad095

**Describe the bug**
CodingQuarry fails with the following error in the funannotate-predict.log when I run funannotate predict. The prediction completes without CodingQuarry, so it's not a huge problem, but I wanted to check if there was an error on my part in running the program? I do have QUARRY_PATH set and when I run predict, the predict_misc/CodingQuarry directory is empty.  The error mentions something about the configuration file, but I couldn't figure out where the file is.  If you have any advice, I would appreciate it!

**What command did you issue?**
```
funannotate predict -i sbillumina.funmask.fasta -o sbnorm_newfun -s "Coccidioides posadasii" --strain sb --cpus 28 --name SB_ \
--transcript_evidence funannotate_train.trinity-GG.fasta ../evidence/ESTs.fa \
--rna_bam funannotate_train.coordSorted.bam \
--pasa_gff funannotate_train.pasa.gff3 \
--augustus_species coccidioides_immitis
```

**Logfiles**

```
[05/14/19 13:20:24]: CodingQuarry installed --> running CodingQuarry prediction on RNA-seq alignments
[05/14/19 13:20:24]: CodingQuarry -p 28 -f /rsgrps/gof1VSsb_pacbio/funannotate/predict/sbnorm_newfun/predict_misc/genome.softmasked.fa -t /rsgrps/gof1VSsb_pacbio/funannotate/predict/sbnorm_newfun/predict_misc/stringtie.gff3
[05/14/19 13:20:24]: The environmental variable QUARRY_PATH is set as: /rsgrps/bin/anaconda2/bin/QuarryFiles
There was a problem reading the configuration
file! Please review.


[05/14/19 13:20:24]: CodingQuarry failed, moving on without result, check logfile

```

**OS/Install Information**
 -  output of `funannotate check --show-versions`

```
-------------------------------------------------------
Checking dependencies for funannotate v1.5.3-21ad095
-------------------------------------------------------
You are running Python v 2.7.14. Now checking python packages...
biopython: 1.71
goatools: 0.8.12
matplotlib: 2.2.2
natsort: 5.2.0
numpy: 1.14.2
pandas: 0.22.0
psutil: 5.5.1
requests: 2.18.4
scikit-learn: 0.19.1
scipy: 1.0.1
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.022001. Now checking perl modules...
Bio::Perl: 1.006924
Carp: 1.36
Clone: 0.41
DBD::SQLite: 1.62
DBD::mysql: 4.033
DBI: 1.642
DB_File: 1.835
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.21
Getopt::Long: 2.45
Hash::Merge: 0.300
JSON: 2.90
LWP::UserAgent: 6.15
Logger::Simple: 2.0
POSIX: 1.53_01
Parallel::ForkManager: 1.19
Pod::Usage: 1.64
Scalar::Util::Numeric: 0.40
Storable: 2.53_01
Text::Soundex: 3.05
Thread::Queue: 3.05
Tie::File: 1.01
URI::Escape: 3.31
YAML: 1.15
threads: 2.21
threads::shared: 1.59
All 27 Perl modules installed


Checking external dependencies...
CodingQuarry: 2.0
RepeatMasker: RepeatMasker version development-$Id: RepeatMasker,v 1.332 2017/04/17 19:01:11 rhubley Exp $
RepeatModeler: RepeatModeler 1.0.11
Trinity: 2.8.4
augustus: 3.3.2
bamtools: bamtools 2.5.1
bedtools: bedtools v2.27.1
blat: BLAT v36x2
diamond: diamond 0.9.24
emapper.py: emapper-0.12.7
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
gmap: 2017-11-15
gmes_petap.pl: 4.38
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 1.8.0_212
kallisto: 0.44.0
mafft: v7.305b (2016/Aug/16)
makeblastdb: makeblastdb 2.6.0+
minimap2: 2.16-r922
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.6.0+
samtools: samtools 1.4
stringtie: 1.3.5
tRNAscan-SE: 2.0 (December 2017)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.6.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
All 32 external dependencies are installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/rsgrps/funannotate_db
$PASAHOME=/home/u11/bin/PASApipeline-v2.3.3
$TRINITYHOME=/home/u11/bin/Trinity-v2.8.4
$EVM_HOME=/home/u11/bin/EvidenceModeler
$AUGUSTUS_CONFIG_PATH=/home/u11/bin/Augustus-3.3.2/config
$GENEMARK_PATH=/home/u11/bin/gm_et_linux_64/gmes_petap
$BAMTOOLS_PATH=/home/u11/bin/bamtools-2.5.1/bin
All 7 environmental variables are set
```

**Comment by nextgenusfs** [comment]
Did you try to run that command manually and see what the error is?
```
CodingQuarry -p 28 \
   -f /rsgrps/gof1VSsb_pacbio/funannotate/predict/sbnorm_newfun/predict_misc/genome.softmasked.fa \
   -t /rsgrps/gof1VSsb_pacbio/funannotate/predict/sbnorm_newfun/predict_misc/stringtie.gff3
```

**Comment by manabanana** [comment]
Hi Jon. Thanks for getting back.  Yes, I did try that and it still gives me the same error with no output files.  Permission for QuarryFiles shouldn't be a problem either so I'm a bit confused.  The QuarryFiles directory is empty, but is it supposed to be empty in the beginning?

```
-bash-4.1$ cat codingquarry.o2171588
The environmental variable QUARRY_PATH is set as: /rsgrps/bin/anaconda2/bin/QuarryFiles
There was a problem reading the configuration
file! Please review.
```

**Comment by nextgenusfs** [comment]
Oh, okay.  I think this is a problem with anaconda installed CQ. I tried to fix this a few weeks upstream in bioconda and then updated the code to adapt.  It has not been fixed yet in bioconda because there are some build issues: https://github.com/bioconda/bioconda-recipes/pull/15012. 

But CQ is asking for files in that QuarryFiles folder and since yours is empty it must not have gotten copied properly in the conda install.  You can likely fix your install by downloading the source from here: https://sourceforge.net/p/codingquarry/.  And then copy recursively the files in the CQ distribution in the `QuarryFiles` folder to your anaconda folder, i.e. `/rsgrps/bin/anaconda2/bin/QuarryFiles`.

**Comment by manabanana** [comment]
Hi Jon.  Thanks so much; recursively copying those files got CQ running!  But what I'm surprised by now, is that I only got 5 genes predicted by CQ although the other programs predict much higher numbers.  Is this normal (I'm annotating a fungal genome that's expected to have >9000 genes)?  Just in case it's a problem with the anaconda version of CQ, I'm currently running the sourceforge installed version of CQ, and I'll see if the numbers change.

```
CodeQuarry models (2):  5
Augustus models (1):    6,133
Genemark models (1):    8,145
HiQ models (2):         4,393
PASA models (6):        4,498
Total models:           23,174
```

**Comment by nextgenusfs** [comment]
Sounds like it might have died? As you said, perhaps something wrong with the compiled version via anaconda.  CQ tends to over-predict actually, I would expect something like  10-12k models from CQ.  I haven't made it a dependency because I'm not super thrilled about the results from CQ generally.  If the RNA-seq is high quality resulting in decent stringtie results, then it seems to perform okay.  But I've also seen it get trained on "noiser" RNA-seq data resulting in small fragmented gene model predictions.  Likely a `--no-cq` option or something to turn it off would be helpful when this happens.

**Comment by manabanana** [comment]
Oops, I feel rather dumb, but I just re-read this post you provided: https://github.com/nextgenusfs/funannotate/issues/200

Sorry, I had not completed those steps.  Is that why CQ would have very few genes?

**Comment by nextgenusfs** [comment]
I just re-looked at your first command.  You will likely get some improved results from leaving off the `--augustus_species` command.  The way you are running it now will use Augustus pre-trained parameters, which is probably not ideal.  Since you have RNA-seq and PASA results, the script will train Augustus based on your PASA gene models which should be more accurate.

**Comment by manabanana** [comment]
Ok, thank you!  I will give that a try!

**Comment by nextgenusfs** [comment]
The post in #200 was when I was giving it a try the first time outside of funannotate.  Now it is incorporated into the code, so essentially those steps are being run internally.  You shouldn't need to do anything else, if it is not returning the proper number of gene models, I would suspect that there is a compilation problem with either CQ or Stringtie.

**Comment by manabanana** [comment]
Thanks for the feedback.   I still only got 5 genes called by CQ even though I tried running it using the sourceforge version of CQ and omitting the "augustus_species" parameter....I guess I'm confused as to what I may be setting incorrectly, but if CQ predictions aren't as reliable, I think I will go with your suggestion of removing CQ from my PATH and just using GeneMarkES and Augustus predictions.  Thank you for helping me understand what goes on with the program and creating this awesome annotation tool!
