### ISSUE TITLE
Broken Repeat Scout link

### ISSUE THREAD

**Issue by giriarteS** [nextgenusfs/funannotate#29]
I have repeat scout in my computer, however when I try to brew install funannotate it fails because a broken link to Repeat scout.
==> Installing funannotate from nextgenusfs/tap
==> Installing dependencies for nextgenusfs/tap/funannotate: repeatscout, recon, repeatmodeler, trnascan, bedtools, raxml, trimal, mafft, braker, evidencemodeler, gag, proteinortho
==> Installing nextgenusfs/tap/funannotate dependency: repeatscout
==> Downloading http://repeatscout.bioprojects.org/RepeatScout-1.0.5.tar.gz

curl: (6) Could not resolve host: repeatscout.bioprojects.org
Error: Failed to download resource "repeatscout"
Download failed: http://repeatscout.bioprojects.org/RepeatScout-1.0.5.tar.gz

**Comment by nextgenusfs** [comment]
@giriarteS this seems to be a broken link to the repeatscout download, you can temporarily fix this doing the following:
```
brew edit repeatscout
```
Then you can change the url of the formula to: `http://www.repeatmasker.org/RepeatScout-1.0.5.tar.gz`.  Save the formula, and then reinstall.
```
brew install funannotate
```
Unfortunately, home-brew doesn't have a mechanism to detect non-homebrewed packages, there maybe a way around it to symlink your repeatscout installation, but generally the easier approach is to let home-brew do it.  If you have all/nearly all of these dependencies already installed, you can build funannotate without any dependencies by running:
```
brew install funannotate --ignore-dependencies
```
You can then manually or use home-brew to install the rest of the dependencies.

**Comment by nextgenusfs** [comment]
I opened an issue with HomeBrew Science letting them know the link was dead https://github.com/Homebrew/homebrew-science/issues/4356

**Comment by giriarteS** [comment]
Thanks

**Comment by giriarteS** [comment]
Got another issue, I trying to run fun annotate predict and I got this message:

[05:43:38 PM]: OS: MacOSX 10.11.6, 24 cores, ~ 67 GB RAM. Python: 2.7.12
[05:43:38 PM]: Running funannotate v.0.3.10
[05:43:39 PM]: ERROR: AUGUSTUS (3.2.2) is not installed properly and this version not work with BUSCO, on MacOSX 10.11.6 you should try manual compilation with gcc-6 of v3.2.1.

How can I solve this?

**Comment by nextgenusfs** [comment]
So exactly as the error says, this is an upstream problem with AUGUSTUS compilation.  I have tried to contact developers numerous times to get them to address it but I have not heard a response.  Note this will only be an issue if you are going to use BUSCO to train Augustus, if you are going to use pre-trained data, BRAKER, or PASA mediated training (i.e. you have RNA-seq) then you won't need to re-compile Augustus. 

 The current workaround on a Mac is to uninstall home-brew AUGUSTUS, `brew uninstall augustus`.  And then you will need to download Augustus v3.2.1 and manually compile using gcc-5 or gcc-6.  I have a version where I modified the make files accordingly.  You can download Augustus 3.2.1 for Mac [here](https://www.dropbox.com/s/1v3u3ii0j51faq5/augustus-3.2.1-osx.tar.gz?dl=0).  Unpack and then do the following:
```
#install gcc5
brew install homebrew/versions/gcc5 
```
Then move into the augustus directory and run these commands:
```
make clean
make
sudo make install
```
This will install Augustus to `/opt/augustus-3.2.1/` directory.  You will then need to change your AUGUSTUS_CONFIG_PATH environmental variable accordingly.
