### ISSUE TITLE
How to "Manually edit the tbl file"?

### ISSUE THREAD

**Issue by FatihSarigol** [nextgenusfs/funannotate#296]
Hello!
I use version 1.4.2-cafe914
After running "predict" I received this error:

[06:18 PM]: There are 3 gene models that need to be fixed.
[06:18 PM]: Manually edit the tbl file PREDIG/predict_results/BrownAnole.tbl, then run:
funannotate fix -i PREDIG/predict_results/BrownAnole.gbk -t PREDIG/predict_results/BrownAnole.tbl
[06:18 PM]: After the problematic gene models are fixed, you can proceed with functional annotation.

First strange thing is that, there is this file in the directory predict_results titled "BrownAnole.models-need-fixing.txt" and it only has 1 gene instead of 3 as reported in the log output. The file has these 2 lines:

#GeneID Error Message
FUN_020585      1 internal stops. Genetic code [1]

The manual on readthedocs says this:

"The user must manually fix the .tbl annotation file to fix these models." 

but doesn't give a hint how exactly we should manually fix it? The <fix> wrapper seems to be the solution, but when I ran it in the way suggested:

`funannotate fix -i PREDIG/predict_results/BrownAnole.gbk -t PREDIG/predict_results/BrownAnole.tbl`

It again gave this error:

[10:46 AM]: There are 3 gene models that need to be fixed.
FUN_020585      1 internal stops. Genetic code [1]
[10:46 AM]: Manually edit the tbl file PREDIG/predict_results/BrownAnole.tbl, then run:
funannotate fix -i PREDIG/predict_results/BrownAnole.gbk -t PREDIG/predict_results/BrownAnole.tbl

Any clues? Should I manually delete the lines that belong to this gene from the tbl file?
Thanks!

**Comment by nextgenusfs** [comment]
The line counter is off. So you can either delete that gene model by passing the identifier to funannotate fix or figure out why the gene model has an internal stop, then edit the .tbl to fix it manually. To generate updated output files can run funannotate fix using the manually edited .tbl file.

**Comment by skylerhar1** [comment]
Is it possible to edit the GBK file instead of the tbl file. For example changing the assembly gap ranges.
