### ISSUE TITLE
absolute path not being used

### ISSUE THREAD

**Issue by kcamnairb** [nextgenusfs/funannotate#30]
Hi, I've been going through some of your code to see exactly what some of the steps are doing and I saw a mistake at line 220 in funannotate-functional.py:
```
#get absolute path for all input so there are no problems later
for i in Scaffolds, Proteins, Transcripts, GFF:
    i = os.path.abspath(i)
```
This will only modify the loop variable, leaving the original variables unmodified. Something like this would do what you are expecting it to do:
`Scaffolds, Proteins, Transcripts, GFF = [os.path.abspath(i) for i in [Scaffolds, Proteins, Transcripts, GFF]]`

**Comment by nextgenusfs** [comment]
Thanks @kcamnairb, let me know if you have more question and/or suggestions.
