### ISSUE TITLE
potential improvement: hisat2-build multi thread

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#303]
**Are you using the latest release?**
Docker version 1.5.3 via singularity

**Describe the bug**
funannotate update : Potential improvement in threading. hisat2-build-s currently runs as single thread. According to the online docs, this can be multi threaded. 

(funannotate update )
def runTrinityGG(genome, readTuple, longReads, shortBAM, hisatexons, hisatss, output):
    '''
    function will run genome guided Trinity. First step will be to run hisat2 to align reads
    to the genome, then pass that BAM file to Trinity to generate assemblies
    '''
    #build hisat2 index, using exons and splice sites
    lib.log.info("Starting Trinity genome guided")
    lib.log.info("Building Hisat2 genome index, incorporating exons and splice-sites")
    **cmd = ['hisat2-build', '--exon', hisatexons, '--ss', hisatss, genome, os.path.join(tmpdir, 'hisat2.genome')]**

add the **-p agrs.THREADS**  (however threads are called)

I dont know if this has RAM implication? RAM per CPU etc ...

just a thought, as this is currently taking a while to complete. 

As I have said before. Love the tool!!!

Pete

**Comment by nextgenusfs** [comment]
Sure can make that change. I guess with the fungal genomes i work with this only takes a few minutes to build the index.

**Comment by peterthorpe5** [comment]
Yes, this an 500 Mbp aphid genome. So took nearly 1 hour.

I am going to get a load of Nanopore cDNA, which has been selected for in a new unpublished method to obtain only full length transcripts. This data I am going to abuse Funannotate with. I have several plans to do this, are you up for idea bouncing via email?

**Comment by nextgenusfs** [comment]
Okay, cpus added to `hisat2-build` command in `train` and `update` commands.  Yes -- very interested in the nanopore method to get full length transcripts as well as willing to help you get them integrated.  Likely  will need to "pre-polish" the data slightly from nanopore.  But feel free to send emails with queries, etc.  Will be a good opportunity to improve the code.

**Comment by peterthorpe5** [comment]
Yes these have been pre polished …

Can you email me so I can get your email address? Mine is below and hopefully not going to get picked up by bots.

pjt6   @  st  -  andrews (dot) ac (dot) uk
