### ISSUE TITLE
funannotate-predict.py not found

### ISSUE THREAD

**Issue by souzaems** [nextgenusfs/funannotate#305]
Hi, I have many problems during the conda installation and now I finally finish the installation, all the dependences are ok and I fix previously erros.

When I did a test using this command line 
`funannotate.py  predict -i /dados/trichechus/test_dataset/example/genome.fa -o /dados/trichechus/testFUN -s "Aspergillus fumigatus" -c 20`

The follow error came:

> /dados/public/anaconda3/envs/funannotate/bin/python: can't open file '/dados/public/anaconda3/envs/funannotate/bin/bin/funannotate-predict.py': [Errno 2] No such file or directory

After this I tried to do a symbolic link using 
`ln -s /dados/public/anaconda3/envs/funannotate/bin/funannotate/bin/funannotate-predict.py /dados/public/anaconda3/envs/funannotate/bin/bin`

After that I used again the command and that was the results:
`unannotate.py  predict -i /dados/trichechus/test_dataset/example/genome.fa -o /dados/trichechus/testFUN -s "Aspergillus fumigatus" -c 20
Traceback (most recent call last):
  File "/dados/public/anaconda3/envs/funannotate/bin/bin/funannotate-predict.py", line 8, in <module>
    import lib.library as lib
ImportError: No module named lib.library`

That's the result of:
`python funannotate check --show-versions`
`-------------------------------------------------------
Checking dependencies for funannotate v1.6.0-4872470
-------------------------------------------------------
You are running Python v 2.7.16. Now checking python packages...
biopython: 1.68
goatools: 0.9.5
matplotlib: 2.2.3
natsort: 6.0.0
numpy: 1.16.4
pandas: 0.24.2
psutil: 5.6.3
requests: 2.22.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.41
DBD::SQLite: 1.62
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking external dependencies...
CodingQuarry: 2.0
RepeatMasker: RepeatMasker 4.0.9
RepeatModeler: RepeatModeler version DEV
Trinity: 2.8.5
augustus: 3.3
bamtools: bamtools 2.4.1
bedtools: bedtools v2.28.0
blat: BLAT v36
diamond: diamond 0.9.24
emapper.py: /dados/public/anaconda3/envs/funannotate/eggnog-mapper/bin/diamond /dados/public/anaconda3/envs/funannotate/eggnog-mapper
ete3: 3.1.1
exonerate: exonerate 2.4.0
gmap: 2017-11-15
gmes_petap.pl: 4.38
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 1.8.0_152-release
kallisto: 0.46.0
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.6.0+
minimap2: 2.17-r941
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.6.0+
samtools: samtools 1.9
stringtie: 1.3.6
tRNAscan-SE: 2.0.3 (April 2019)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.6.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
	ERROR: fasta not installed
Checking Environmental Variables...
$FUNANNOTATE_DB=/dados/public/anaconda3/envs/funannotate/DB
$PASAHOME=/dados/public/anaconda3/envs/funannotate/opt/pasa-2.3.3
$TRINITYHOME=/dados/public/anaconda3/envs/funannotate/bin
$EVM_HOME=/dados/public/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/dados/public/anaconda3/envs/funannotate/config/
$GENEMARK_PATH=/dados/public/anaconda3/envs/funannotate/gm_et_linux_64/gmes_petap
$BAMTOOLS_PATH=/dados/public/anaconda3/envs/funannotate/bamtools
All 7 environmental variables are set
-------------------------------------------------------`

I did find errors like that, so it would be nice to have some clue about it.

Many thanks

**Comment by nextgenusfs** [comment]
`funannotate` is the executable not `funannotate.py`.  Which part of the instructions were problematic?  https://funannotate.readthedocs.io/en/latest/conda.html#conda

Use the `funannotate test` command to test your installation/system.

If you type `funannotate` and don't get the help menu then it is not properly in your PATH.

**Comment by souzaems** [comment]
I did that part

> Clone the funannotate repo and add to PATH
And the github file was in `/dados/public/anaconda3/envs/funannotate/bin/funannotate`
 
Also, when I tested: 
`(funannotate) [root@vm-centos-prof-mnery bin]# pwd
/dados/public/anaconda3/envs/funannotate/bin
(funannotate) [root@vm-centos-prof-mnery bin]# python funannotate test
/dados/public/anaconda3/envs/funannotate/bin/python: can't find '__main__' module in 'funannotate'
(funannotate) [root@vm-centos-prof-mnery bin]# pwd
/dados/public/anaconda3/envs/funannotate/bin
(funannotate) [root@vm-centos-prof-mnery bin]# funannotate test
bash: funannotate: command not found
(funannotate) [root@vm-centos-prof-mnery bin]# cd funannotate/
(funannotate) [root@vm-centos-prof-mnery funannotate]# funannotate test
bash: funannotate: command not found
(funannotate) [root@vm-centos-prof-mnery funannotate]# python funannotate test

Usage:       funannotate test <arguments>
version:     1.6.0-4872470

Description: This is a script that runs several unit tests.  It will download data and run
             several different tests to determine if installion is functioning properly. If
             you cannot download from the machine funannotate is installed at - then download
             the 7 tar.gz files from https://osf.io/bj7v4/files/ and run script from directory 
    
Arguments:   -t, --tests    Test sets to run. [all,clean,mask,predict,busco,rna-seq,annotate,compare]
             --cpus         Number of cpus to use. Default: 2
             
Written by Jon Palmer (2016-2018) nextgenusfs@gmail.com
        
(funannotate) [root@vm-centos-prof-mnery funannotate]# pwd
/dados/public/anaconda3/envs/funannotate/bin/funannotate`

The `funannotate test` only works with python before it and inside of `/dados/public/anaconda3/envs/funannotate/bin/funannotate`

**Comment by nextgenusfs** [comment]
So this means it’s not in your PATH. If ‘which funannotate’ doesn’t give you the path then it isn’t installed properly. 

You symlinked funannotate to the conda env bin, correct?  Copying it won’t work.

**Comment by souzaems** [comment]
I used this command to link the funannotate file

git clone https://github.com/nextgenusfs/funannotate.git  #inside of funannotate envs
ln -s /dados/public/anaconda3/envs/funannotate/funannotate /dados/public/anaconda3/envs/funannotate/bin/funannotate

And when I but which funannotate, this is the result
`(funannotate) [root@vm-centos-prof-mnery funannotate]# which funannotate
/usr/bin/which: no funannotate in (/dados/public/anaconda3/envs/funannotate/gm_et_linux_64/gmes_petap:/dados/public/anaconda3/envs/funannotate/gm_et_linux_64/gmes_petap:/dados/public/anaconda3/envs/funannotate/bin:/dados/public/anaconda3/condabin:/dados/public/anaconda3/bin/conda:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/dados/erica/bin)`

I need to link outside of the envs/funannotate? Like in conda/bin?

**Comment by nextgenusfs** [comment]
Don’t clone it inside the anaconda environment, conda doesn’t like non conda installed folders in its structure. So I would delete that as well as any symlink you made and then re clone it elsewhere. And then funannotate needs to be in your PATH so any directory that is in PATH is fine. Based on your path the location should work but something is clearly wrong as it can’t find the wrapper script.

**Comment by souzaems** [comment]
Hi
The funannotate it's running now, I didn't test all the commands but it's running, what we did was insert this on the PATH:

`export PATH="/dados/software/funannotate:$PATH"`

Instead
`#add to PATH
ln -s /path/to/funannotate/funannotate /path/to/conda/envs/funannotate/bin/funannotate`

Sorry if my question was silly, I'm only a biologist and I have no idea about this "basic" concepts from PATH and path, but I'm very grateful for your help
