### ISSUE TITLE
Manually add in a completely missed gene

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#306]
**Are you using the latest release?**
Docker version 1.5.3

**Describe the bug**
No bug: Application question

Hi Jon,

I have re-predicted genes for the pea aphid using Funannotate. There are two existing published annotations for this beastie ... There is a gene which has proteomics and RNAseq support which was not called by Funannotate. 

Just adding it in will mess up the numbering system etc ... Do you have any words of wisdom for doing this? Of course I have been right through and added all the annotation steps, so preserving the annotation would be great.

Pete

**Comment by hyphaltip** [comment]
are you wondering how to add it in manually to the .tbl file? Out of order numbering is okay or you can designate a LOCUS_M_0001 to indicate your manual genes you add in. 

I also think a workflow strategy is funannotate -> jbrowse + apollo for editing -> export and submit to genbank. I'm working on some code to do the jbrowse export so that a result of funannotate could be the packaging of what is needed to spin up a virtual machine with Jbrowse for curation afterwards.

**Comment by peterthorpe5** [comment]
Thank you for your reply! So If I altered the table ( a brief guide would be handy). Could I then regenerate all the other files Funannot gives you, such as the gff, gbk, AA.fa, nt.fa, etc ...?

Adding your code would be very helpful to help with manual curation. 

cheers,

Pete

**Comment by nextgenusfs** [comment]
Yes so you can add/update the tbl annotation file and then run ‘funannotate fix’.

**Comment by peterthorpe5** [comment]
Hi all, this sounds great. Would you please be able to glance over the lines below to help identify the error? Or I can email you the files?

I want to add this in: (clearly something in here is wrong. I have tried my best to look at the other genes to replicate the format. This is -ve encoding)

139477	124180	gene
			locus_tag	LOCUS_M_0001
124395	124180	mRNA
124577	124483
129351	129270
129492	129427
130702	130571
130902	130769
134047	133897
135561	135371
139477	139327
			product	hypothetical protein
			transcript_id	gnl|ncbi|LOCUS_M_0001-T1_mrna
			protein_id	gnl|ncbi|LOCUS_M_0001-T
124395	124180	CDS
124577	124483	CDS
129351	129270	CDS
129492	129427	CDS
130702	130571	CDS
130902	130769	CDS
134047	133897	CDS
135561	135371	CDS
139477	139327	CDS
139477	139475	codon_start	1
			transcript_id	gnl|ncbi|LOCUS_M_0001-T1_mrna
			protein_id	gnl|ncbi|LOCUS_M_0001-T


Using this embeded in the .tbl file produces the following error:

> ../funannotate/funannotate fix -t pea_fun_Api.tbl -i ./annotate_results/pea_fun_Api.gbk -o Api15787_gene_added_asLOCUS_M_0001
-------------------------------------------------------
[11:02 AM]: OS: linux2, 32 cores, ~ 529 GB RAM. Python: 2.7.15
[11:02 AM]: Running funannotate v1.6.0-4872470
[11:03 AM]: Extracting genome sequence and parsing meta information
[11:03 AM]: 23,924 contigs containing 30,916 protein coding genes and 340 tRNA genes
[11:04 AM]: Converting to GenBank format
error: [Errno 2] No such file or directory run(*(['tbl2asn', '-y', '"Annotated using funannotate v1.6.0-4872470"', '-N', '1', '-t', '/storage/home/users/pjt6/funannotate/lib/test.sbt', '-M', 'n', '-j', '"[organism=pea_fun]"', '-V', 'b', '-c', 'fx', '-T', '-a', 'r10u', '-l', 'paired-ends'], 'Api15787_gene_added_asLOCUS_M_0001/tbl2asn/6'), **{})
error: [Errno 2] No such file or directory run(*(['tbl2asn', '-y', '"Annotated using funannotate v1.6.0-4872470"', '-N', '1', '-t', '/storage/home/users/pjt6/funannotate/lib/test.sbt', '-M', 'n', '-j', '"[organism=pea_fun]"', '-V', 'b', '-c', 'fx', '-T', '-a', 'r10u', '-l', 'paired-ends'], 'Api15787_gene_added_asLOCUS_M_0001/tbl2asn/1'), **{})
error: [Errno 2] No such file or directory run(*(['tbl2asn', '-y', '"Annotated using funannotate v1.6.0-4872470"', '-N', '1', '-t', '/storage/home/users/pjt6/funannotate/lib/test.sbt', '-M', 'n', '-j', '"[organism=pea_fun]"', '-V', 'b', '-c', 'fx', '-T', '-a', 'r10u', '-l', 'paired-ends'], 'Api15787_gene_added_asLOCUS_M_0001/tbl2asn/2'), **{})
error: [Errno 2] No such file or directory run(*(['tbl2asn', '-y', '"Annotated using funannotate v1.6.0-4872470"', '-N', '1', '-t', '/storage/home/users/pjt6/funannotate/lib/test.sbt', '-M', 'n', '-j', '"[organism=pea_fun]"', '-V', 'b', '-c', 'fx', '-T', '-a', 'r10u', '-l', 'paired-ends'], 'Api15787_gene_added_asLOCUS_M_0001/tbl2asn/4'), **{})
error: [Errno 2] No such file or directory run(*(['tbl2asn', '-y', '"Annotated using funannotate v1.6.0-4872470"', '-N', '1', '-t', '/storage/home/users/pjt6/funannotate/lib/test.sbt', '-M', 'n', '-j', '"[organism=pea_fun]"', '-V', 'b', '-c', 'fx', '-T', '-a', 'r10u', '-l', 'paired-ends'], 'Api15787_gene_added_asLOCUS_M_0001/tbl2asn/5'), **{})
error: [Errno 2] No such file or directory run(*(['tbl2asn', '-y', '"Annotated using funannotate v1.6.0-4872470"', '-N', '1', '-t', '/storage/home/users/pjt6/funannotate/lib/test.sbt', '-M', 'n', '-j', '"[organism=pea_fun]"', '-V', 'b', '-c', 'fx', '-T', '-a', 'r10u', '-l', 'paired-ends'], 'Api15787_gene_added_asLOCUS_M_0001/tbl2asn/3'), **{})
[11:04 AM]: Generating output files.
Traceback (most recent call last):
  File "/storage/home/users/pjt6/funannotate/util/updateGBK.py", line 120, in <module>
    lib.tbl2allout(final_tbl, os.path.join(basedir, 'tbl2asn', 'genome.fsa'), final_gff, final_proteins, final_transcripts, final_cds_transcripts, final_fasta)
  File "/storage/home/users/pjt6/funannotate/lib/library.py", line 1937, in tbl2allout
    Genes = tbl2dict(input, fasta, Genes)
  File "/storage/home/users/pjt6/funannotate/lib/library.py", line 2127, in tbl2dict
    protSeq = translate(cdsSeq, v['strand'], v['codon_start'][i]-1)
IndexError: list index out of range

Regards,

Pete

**Comment by peterthorpe5** [comment]
ok that was a dependency issue. Sorted!!
