### ISSUE TITLE
Braker error augustus not executable

### ISSUE THREAD

**Issue by SilenzCS** [nextgenusfs/funannotate#314]
Hi all,

I nearly got braker running except for one problem. I doesn't find the augustus to be executable, altough it's there and has permission. Any ideas?

> (base) silenz@DESKTOP-O4FOG8G:~$ export AUGUSTUS_SCRIPTS_PATH=/home/silenz/anaconda3/pkgs/augustus-3.2.2-0/scripts
> 
> (base) silenz@DESKTOP-O4FOG8G:~$ export AUGUSTUS_BIN_PATH=/home/silenz/anaconda3/pkgs/augustus-3.2.2-0/bin/
> (base) silenz@DESKTOP-O4FOG8G:~$ export GENEMARK_PATH=/home/silenz/gm_et_linux_64/gmes_petap/
> (base) silenz@DESKTOP-O4FOG8G:~$ export AUGUSTUS_CONFIG_PATH=/home/silenz/anaconda3/pkgs/augustus-3.2.2-0/config
> (base) silenz@DESKTOP-O4FOG8G:~$ export BAMTOOLS_PATH=/home/silenz/anaconda3/pkgs/bamtools-2.5.1-he860b03_5/bin/

> (base) silenz@DESKTOP-O4FOG8G:~/anaconda3/pkgs/augustus-3.2.2-0/config$ braker.pl --genome=genome.fa --bam=rna.bam
> NEXT STEP: check files and settings
> ERROR: /home/silenz/anaconda3/pkgs/augustus-3.2.2-0/config/../bin/augustus not executable on this machine.

> ERROR: augustus executable not found at /home/anaconda3/pkgs/augustus-3.2.2-0/config/../bin/augustus.
> 
> 
> (base) silenz@DESKTOP-O4FOG8G:~/anaconda3/pkgs/augustus-3.2.2-0/bin$ la -ls
> total 5452
> 1568 -rwxrwxrwx 3 silenz silenz 1603359 Jun  3  2016 augustus
>  488 -rwxrwxrwx 3 silenz silenz  497107 Jun  3  2016 bam2hints
> 1752 -rwxrwxrwx 3 silenz silenz 1790872 Jun  3  2016 etraining
>  368 -rwxrwxrwx 3 silenz silenz  373952 Jun  3  2016 fastBlockSearch
>  672 -rwxrwxrwx 3 silenz silenz  686381 Jun  3  2016 filterBam
>  156 -rwxrwxrwx 3 silenz silenz  156253 Jun  3  2016 homGeneMapping
>  404 -rwxrwxrwx 3 silenz silenz  410840 Jun  3  2016 joingenes
>   44 -rwxrwxrwx 3 silenz silenz   44298 Jun  3  2016 prepareAlign
> 
>

**Comment by nextgenusfs** [comment]
Braker is in the code for historical reasons -- I don't use it anymore as the default method for training in funannotate is both faster and more accurate.  Are you trying to run braker from within funannotate or just running braker by itself?

**Comment by SilenzCS** [comment]
Currently I'm trying to run braker by itself. Could it be aproblem that I try to run it in the subsystem of windows?

**Comment by nextgenusfs** [comment]
Maybe you should open an issue with the braker developers then....
