### ISSUE TITLE
Adding description to anntation

### ISSUE THREAD

**Issue by mictadlo** [nextgenusfs/funannotate#315]
Hi, 
Our HPC does not support Docker. At the moment, I was not able to get `funannotate` running inside a Singularity container. Therefore, I ran DIAMOND with SwissProt manually. Next, I will install docker on my laptop and wonder how to add a description to the annotation?

Thank you in advance,

Michal

**Comment by nextgenusfs** [comment]
Install the pipeline on the HPC with conda....
