### ISSUE TITLE
funannotate predict - with zero alignment evidence & pretrained gene models

### ISSUE THREAD

**Issue by fbemm** [nextgenusfs/funannotate#320]
Hi,

I am trying to evaluate if I can annotate a target region with funannotate. I have a highly trained Augustus profile as part of a whole genome workflow. The target regions is rather small (<2Mb). Usually we don't see lots if not zero evidence mapping there. Would it be possible to reuse the gene predictor models from the whole genome run (SNAP, CodingQuary, Augustus GlimmerHMM) to annotate the target? Right now funannotate fails because hints.*.gff stays empty and BUSCO does not find a core gene to start of. Is there a way to simple run the predict pipeline without re-training and allowing zero alignment evidence?

Bests
Felix

**Comment by nextgenusfs** [comment]
Interesting. Never had that problem before but at the moment not sure it’s easily possible. Could be an option that we could add. I guess we could make a training type structure akin to Augustus that saves the training files for the predictors so it could be rerun with different DNA sequence.

**Comment by nextgenusfs** [comment]
This should now be possible as of v1.7.0 -- all of the ab initio training parameters are saved and can be reused.
