### ISSUE TITLE
transcripts file is not CDS file: mRNA != amino acid

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#321]
**Are you using the latest release?**
DOcker version 1.5.3

**Describe the bug**
The translation of the transcript file (after the "uppate has completed") does not match the proteins file

**What command did you issue?**
N/A

**OS/Install Information**
Docker version 1.5.3

Hi Fun people,

Once the (excellent) software has finished, including the update step. There are the usual output files. 

My issue is that the transcripts file does not translate to match the proteins file. The (3 time) length of the transcript does not match the protein length. 

When I translate the transcripts files and do a Linux diff command between the funannotate.proteins and the aminod_acids I produced, the result are, for example (see below). Different (data was line wrapped to be the same length, the seq_record.description was not outputted, so this is always different, but the actual seq is not the same). 

Is the transcripts file not supposed to be the cds of the proteins? I.e. do the transcripts contain UTR regions, which would explain this? Can we please have a script, and by default the nucleotide cds output too? I cant find a sensible tool that will output the AA and nt_cds while preserving the gene names .... life it tough :)

Pete

< IIYTLNAELQAHQQVCKAVTGIVTAQQMTLHDIVCTLQAFHLHRQRCI*
< >GPALN_000002-T1
---
> IIYTLNAELQAHQQVCKAVTGIVTAQQMTLHDIVCTLQAFHLHRQRCI
> >GPALN_000002-T1 GPALN_000002
8,9c8,9
< KKLKEQMEEWKTKFELKNKALHAELKHQKVLIAHMAQQRKTEEY*
< >GPALN_000003-T1
---
> KKLKEQMEEWKTKFELKNKALHAELKHQKVLIAHMAQQRKTEEY
> >GPALN_000003-T1 GPALN_000003
11,12c11,12
< EDCETNESLKYVQAMLVAELEEYQKQQKQNIDAGGSVGVMPLAPQRHGPGGGLCDGKDDLFFTPTVHSDVNAS*
< >GPALN_000004-T1
---
> EDCETNESLKYVQAMLVAELEEYQKQQKQNIDAGGSVGVMPLAPQRHGPGGGLCDGKDDLFFTPTVHSDVNAS
> >GPALN_000004-T1 GPALN_000004
20,36c20,32
< LEWRRFGEEFWLLIRCPIERDEDKWAEWEKEEAAEWDCLWQWNCISINFNDWDIGDGEDKKRRKRRSRVSKKGKK*
< >GPALN_000005-T1
< R*NRKKE*MAPPAKKKKANSSVTHCQSLALSQSLITSAAGARRSAGLANKNKTKKIFICGDVWLDIFPFLGHAKVAFEVA
< LLSNRFDLLVDAHFKSKEYSLGRLNIRRTTDKKGAVIVKLVNGKVERRLPIPQDPLPDKVIGFQLITISYVDQNVIEFLQ
< RIRRLFDSKGIILSIGTNIDLNRSWEIIWEKIWPLIKDNICCFHLDAHDFGGFPPTFLCNCSKLRVIHSDYGFPTFPAND
< SAGASSVQALFKWLYTPRGDGRPKAFLNSTASRNFIICLKLHWHSADIVPFELKNNLTGERLELRSLNSYKCLLVRCPIE
< RDAAKWAKWENEAAGLDWRRQWTRIHINLEDSAIGDGLLEAKEGPSEPKKRKN*GQQNLEENSSRENGLNT*NWCFLTTK
< FRFIHKCLNAE*SPKKLLTPKK*WRWSCVTFKHAEKNMSYILLLLLAVNSKPSGIFPIFVPIFSVF*KFSDLYEEGV*S
< >GPALN_000005-T2

**Comment by peterthorpe5** [comment]
I see this has been fixed in version 1.6.0 where a mRNA.transcripts is outputted. I will test this. 

cheers,

ptee

**Comment by peterthorpe5** [comment]
ok, so the mRNA transcript file does not match the proteins, here is an example, where the mRNA does not start with a ATG. No 6 frame translation is close to the amino acid sequence:

>GPALN_002593-T1 GPALN_002593
MRKVSTNCCFLLLAIVALPSAAVQSPPYGQLQVKGSKLMSSSGKQIMLRGMSLFWSQWDPKYWNAETVNQLKCKWGINIL
RAPMGVEGSDGYLQSAAANAANTQKLMTVVDACINAGIYVIIDWHYTSGTAYTDKAVEFFKKMAQKYGKNPHILYEIWNE
PVGVDWKRVLKPYLQKLISAIRPIDPDNVILLGTPNYSMDLNSVASSPITGQKNIMYSFHFYAADSTPSEQTKQQNMGKE
SDSGRFSGVRH


>GPALN_002593-T1 GPALN_002593
GTTTGCCCGGGGGCCAAATGTCCTCGGGGACCGCCATCGCCAGTTTTCAAAAAGGGCTTTTCACTTTCATTGCCGGGGTC
TCTGTCCTTTCCTGAATTGAAACCAAAGGTTGGCGCAATTGGCACTTTTTACAATGGCTGAATAAACAAACCAAAAGCTT
TCCCGTCGTTTGTTCAAATATCGCCGCTTTTAAATTAAACAAATTTCGGATATAAAAGGCGGACGACAAATTATGAAAAT
TAATTTAAAAAAACTATTCGTTACAAATAAATAAAGCAATGAGGAAAGTTTCAACTAATTGCTGCTTTTTGTTACTCGCA
ATTGTCGCACTTCCGTCGGCGGCCGTCCAATCTCCGCCGTATGGCCAACTGCAGGTTAAGGGGAGTAAGCTGATGAGTTC
GAGCGGGAAGCAAATAATGTTGAGAGGAATGTCGCTGTTTTGGAGCCAATGGGACCCGAAGTACTGGAATGCCGAAACTG
TCAACCAACTGAAGTGCAAATGGGGCATTAACATCCTTCGGGCTCCGATGGGCGTTGAGGGCAGCGACGGATATTTGCAA
AGTGCGGCGGCAAATGCGGCGAACACTCAGAAACTGATGACGGTTGTTGACGCGTGCATAAATGCGGGCATTTACGTTAT
AATCGATTGGCACTACACCAGTGGCACGGCATACACTGACAAAGCTGTGGAATTTTTCAAGAAAATGGCACAGAAATATG
GCAAAAACCCACACATTTTGTACGAAATATGGAACGAACCAGTTGGGGTCGATTGGAAACGCGTGCTGAAGCCGTACCTT
CAGAAGTTGATCTCGGCAATCCGACCCATTGACCCCGACAATGTGATCCTTCTGGGCACGCCGAACTACTCGATGGACTT
GAATTCTGTGGCCAGCAGCCCCATCACGGGCCAAAAGAACATTATGTATTCATTTCACTTTTACGCGGCCGACTCGACTC
CGAGTGAACAGACCAAACAACAAAACATGGGTAAAGAAAGTGACTCAGGGCGGTTTTCCGGTGTTCGTCACTGAAAGCGG
TGCCGGCTCCGGCGGGAGCAATTCCCCCGTCAATTTGCCCATAATGAATCAATGGTGGTCCCTTCTGGAGCAGCTCAAAA
TCTCATATATCATTTGGGGCGTTCGCGGAGAAGGAAATTACCAAAATCCGCTAAAGCAGGGGACGGCACCCGCAAATGTT
GGGCAGAGCTCGTCGTTGACGGACTACGGGAAAGTGGTCAAAAATGTGTTCACAAAGAACGGACAGCCGAAAGGATGCTG
ACAAAGAAAAGAGACTTCTTTCATCGGATGCAAATTAAGAATAAATTAAAAGACGCTTAATTGGGTAATTTGGTGTAACT
TCTAGTGATGTCAAATAAAATTTTAATG

**Comment by nextgenusfs** [comment]
The output of annotate should be producing both mRNA and cds, maybe that didn’t get ported to the output of update command. If doesn’t use the transcript files for anything so not something I probably checked closely at that step in pipeline. But I will look into it.

**Comment by peterthorpe5** [comment]
This works on the Docker 1.6.0 version. But the mRNA does not translate into the protein sequence. I am happy to share files ...

**Comment by nextgenusfs** [comment]
It shouldn’t because it contains UTRs, the cds-transcripts I think was just recently added. But I recall a bug where crick strands weren’t being reverse complemented, so need to double check that as well.

**Comment by peterthorpe5** [comment]
"It shouldn’t because it contains UTRs" - Ok that makes sense ...

cds-transcripts: I think the reverse complement thing could explain it. is this easy to fix?

**Comment by nextgenusfs** [comment]
Yes should be an easy fix, just need to figure out exactly what problem is. So to confirm, you are getting a single or multiple transcript output files from the update command?

**Comment by peterthorpe5** [comment]
Ok – hang fire. I ran this on an old dataset (Version 1.5.3) with version 1.6.0. There are now:
.cds-transcripts.fa
.transcripts.fa
.mrna-transcripts.fa

I will try and break thing with the cds-transcripts.fa file  - this may be ok.

Give me 30 mins.

Pete

**Comment by peterthorpe5** [comment]
Hi Jon,

Using the .cds-transcripts.fa file - my back-translations no longer failed. SUCCESS!!!!!!!!

cheers,

Pete
