### ISSUE TITLE
Enter Funannotate pipeline at the annotation step

### ISSUE THREAD

**Issue by Quandt-Mycology-Lab** [nextgenusfs/funannotate#323]
Hi Jon, is it possible to enter the funannotate workflow at the "annotate" step. For example, I have genome1 from Genbank, and it's really basically annotated. So I have the genome1.gbk file, but it doesn't have any functional annotation, but I would like to annotate it so that I can add it to my "funannotate compare" analysis.  Is this possible? For input into "funannotate annotate", it says the output directory from "predict" is necessary. Would I need to re-predict the gene models from Genbank genome using funannotate just to be able to run "annotate"?

Thanks as always for your help,
Alisha

**Comment by hyphaltip** [comment]
Yes. You can provide a gbk file to the annotate step.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by Quandt-Mycology-Lab** [comment]
Hi Jason,
Thanks! I see that option now when I type:
funannotate annotate -h

But didn't see it on the funannotate website or manual.

**Comment by nextgenusfs** [comment]
Formatting isn’t maybe ideal but it’s here (should say or in between).  https://funannotate.readthedocs.io/en/latest/annotate.html#annotate

Probably needs to get updated
