### ISSUE TITLE
About new species training!

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#324]
Hello,
This is a excellent pipeline for annotation genome.
I have de novo assembled a few fungi genome. One isolate of this fungi have been sequenced and annotated. I want to use transcripts and repeat elements of this isolates for annotating my draft genome. I do not have RNA-seq data.
However, I can not find these species in funannotate species and BUSCO species. Can I train them using the known transcripts?
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
Per using repeat elements from related species -- you need to have these repeat sequences in a fasta file, then you would soft mask your genome like this:
```
funannotate mask -i assembly.fasta --repeatmodeler_lib repeats.fasta -o assembly.masked.fasta
```

Per training a new species -- see example 2 at https://funannotate.readthedocs.io/en/latest/predict.html.  You should specify the closest species from the `funannotate species` command to `--busco_seed_species`.  You can pass any transcript evidence you want to `--transcript_evidence`. For example if closest species with training parameters was Neurospora crassa then you would run:
```
funannotate predict -i assembly.masked.fasta -s "Genus speciesname" --isolate XYNX \
    --busco_seed_species neurospora_crassa -o output_folder \
    --transcript_evidence ests.fa related_species_transcripts.fa anyotherforevidence.fa
```

**Comment by sunnycqcn** [comment]
Thanks,
I got it.
Fuyou
