### ISSUE TITLE
funannotate mask error!

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#325]
Hello,
 I installed funannotate under conda. RepeatMasker and RepeatModuler were installed un conda too.
When I run mask, I met the error is like as following.  Could you look through what it happen?

 ~/miniconda3/envs/funannotate/bin/funannotate mask -i BL06.fasta -l LM.lib -o a.fasta  --cpus 20

-------------------------------------------------------
[04:46 PM]: OS: linux2, 80 cores, ~ 1057 GB RAM. Python: 2.7.15
[04:46 PM]: Running funannotate v1.6.0-401c258
[04:46 PM]: Loading sequences and soft-masking genome
[04:46 PM]: Soft-masking: building RepeatModeler database
[04:47 PM]: Soft-masking: generating repeat library using RepeatModeler
[05:05 PM]: Soft-masking: running RepeatMasker with default library (RepeatModeler found 0 models)
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/lib/python2.7/logging/__init__.py", line 892, in emit
    self.flush()
  File "/home/AAFC-AAC/fuf/miniconda3/lib/python2.7/logging/__init__.py", line 852, in flush
    self.stream.flush()
IOError: [Errno 116] Stale file handle
Logged from file library.py, line 4467
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/funannotate/bin/funannotate-mask.py", line 76, in <module>
    with open(args.out, 'rU') as input:
IOError: [Errno 2] No such file or directory: 'a.fasta'
The log file is as following:
RepeatMasker Version: open-4.0.9
Library Version: CONS-Dfam_3.0
Search Engine: ncbi [ symbol lookup error: /home/AAFC-AAC/fuf/miniconda3/bin/../lib/ncbi-blast+/libxcleanup.so: undefined symbol: _ZN4ncbi7objects4edit12GetNewProtIdENS0_14CBioseq_HandleERiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb ]
Command Line: /home/AAFC-AAC/fuf/miniconda3/share/RepeatMasker/RepeatMasker-e ncbi -lib /isilon/saskatoon-rdc/users/fuf/BLgenome/repeat/LM.lib -pa 20 -xsmall -dir RepeatMasker /isilon/saskatoon-rdc/users/fuf/BLgenome/repeat/BL06.fasta
Batch Number: 5
Disk Space:
Filesystem                                                                         1K-blocks         Used    Available Use% Mounted on
skyemci01-hpc2.efs.agr.gc.ca:/ifs/skyemci01/bicoe/biocluster-data/saskatoon-rdc 783831531520 340945278464 442886253056  44% /isilon/saskatoon-rdc

System Memory:
MemTotal:       1056516900 kB
MemFree:         5059624 kB
MemAvailable:   1030263008 kB
Cached:         1018302112 kB
SwapCached:          552 kB
SwapTotal:       4194300 kB
SwapFree:        4154256 kB
Further details about this problem may be found in
the directory: /isilon/saskatoon-rdc/users/fuf/BLgenome/repeat/mask_144534/RM_144556.TueSep171708182019

**Comment by nextgenusfs** [comment]
Did you install repeatmasker libraries from rep base?

**Comment by sunnycqcn** [comment]
I installed two repeatmasker. One is installed by conda, not install repeatmasker libraries. This one can directly run when funannotate. But it is fail. Other one is my root with repeatmasker libraries.  But I did not find how to connect to funannotate.
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
Hello,
I copied my libraries from my root one to conda one. It is working well now.
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
Sorry, I said wrong.
I still get the error is 
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/funannotate/bin/funannotate-mask.py", line 76, in <module>
    with open(args.out, 'rU') as input:
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
So the original error is related to this:
```
RepeatMasker Version: open-4.0.9
Library Version: CONS-Dfam_3.0
```
Dfam is shipped with RepeatMasker -- however, repeatmasker needs the RepBase repeatmasker libraries installed.  This is going to be a problem in the future as RepBase has now made these data as a pay service only, ie no longer free for academia. 

After you install the repeatmasker libraries you have to reconfigure RepeatMasker to use those libraries -- consult the repeatmasker docs.  If still erroring or a different error can you post what that is?

**Comment by sunnycqcn** [comment]
I am done.
Thanks,
FUyou
