### ISSUE TITLE
Support for using locally run Interproscan results

### ISSUE THREAD

**Issue by kcamnairb** [nextgenusfs/funannotate#33]
Interproscan 5 outputs a single xml file containing all of the results instead of an xml file for each protein as is expected in the funannotate-functional.py module. Could support for interproscan 5 xml output be added?

Thanks,
Brian

**Comment by nextgenusfs** [comment]
Hi Brian,
Yes I'm aware of this.  Years ago now I went through the arduous task of downloading and setting up IPR5 locally, only to find that at least in my hands, it isn't very fast (could be because I was running on Ubuntu in virtual box).  I actually think it is faster to run the search remotely using the EBI servers and significantly less work making sure databases are updated, etc. 

Right now it would be difficult to implement a single XML file (I think), but perhaps having a script split the single XML file into individual proteins would not be that hard.  I don't have a lot of experience parsing the XML files, but if they are simply in blocks for each protein, then shouldn't be a huge undertaking to split them.  

The other option would be perhaps to run IPR5 on each protein individual and then run that in parallel - which should output one XML file per protein.  If I remember correctly, IPR5 takes awhile to "spin-up" so not sure how fast this would be. 

Can you send me a IPR5 single file XML output that has a test dataset, i.e. like 10 proteins?  Unless you want to script something that will split into individual files?

Jon

**Comment by nextgenusfs** [comment]
Found a perl script that could work, nested in this discussion: https://groups.google.com/forum/#!topic/blast2go/ZX6565FqSZw.

**Comment by kcamnairb** [comment]
Thanks, that script might do the job. The reason I wanted to try using IPR5 was that remote interproscan step in funannotate-functional.py was taking over 10 days. When I run the $HOMEBREW_PATH/opt/funannotate/libexec/util/runIPRscan.py script directly as suggested in #14  it completes successfully within a few seconds.

**Comment by nextgenusfs** [comment]
How many proteins do you have to annotate?  Typically I can run a fungal genome in less than 24 hours, so something like 10,000 proteins. 

Let me know if that script splits the IPR5 XML correctly or not, it might need some minor tweaking to be compatible.  But I can integrate that into `funannotate annotate` to take a single IPR5 XML if it works.

**Comment by kcamnairb** [comment]
I have about 12,500 proteins to annotate. I added a print statement to the runIPRpython function to make sure there wasn't an issue with the subprocess command. Here is an example of what is given to subprocess.call: `['/usr/bin/python', '/home/brian/.linuxbrew/Cellar/funannotate/0.3.7/libexec/util/runIPRscan.py', '--goterms', '--email', None, '--outfile', './AF206-4_funannotate/annotate_misc/iprscan/AF206-4_012487', '--input', './AF206-4_funannotate/annotate_misc/protein_tmp/AF206-4_012487.fa']` It goes on to the next 25 sequences in less than a minute, but there is nothing saved in the annotate_misc/iprscan directory.

**Comment by nextgenusfs** [comment]
You have to provide an email address to identify yourself to the EBI servers, there is suppose to be a check on this in the wrapper script that doesn't let you go without an email.  But seems like the email is not getting into the script here.  What was your command to get that output?

**Comment by nextgenusfs** [comment]
I think I found the bug not exiting the script if you don't provide an email address, will push the fix.  But can you confirm that it works if you add email address?  Or is there some other error?

Any luck with that XML splitting script?

**Comment by kcamnairb** [comment]
Thanks, the command was indeed missing my e-mail: `~/.linuxbrew/bin/funannotate annotate --cpus 32 --genbank ./AF206-4.gbk --out ./AF206-4_funannotate --antismash ./AF206-4_antismash/*.final.gbk` 
Changing the argparse command to: `parser.add_argument('-e','--email', help='Email address for IPRSCAN server', required=True)` should make it fail if an e-mail is not supplied.

The IPR5 run has been running for almost 5 hours with 32 cores and says it has completed 76%. I'll let you know if it works with the XML splitting script.

**Comment by nextgenusfs** [comment]
Ok cool.  Yeah the `required=True` is one way, but if you aren't doing IPRscan sort of annoying to have to enter it.  I had another "manual" check later that I must have messed with at one time or another (as I know it used to work) and was actually an if/else that could never happen, should be fixed now I believe.  But I will wait to do a push until we can figure out of the splitting script can work, as then I can support the single file input as well.

**Comment by kcamnairb** [comment]
The splitting script output seemed to have worked well with funannotate annotate. The annotate_misc/annotations.iprscan.txt file contains 25,000 annotations.

**Comment by nextgenusfs** [comment]
Cool.  How about GO ontology terms, was it able to pick those up as well?

Would be helpful if you could send the first ~ 10-100 records from the combined IPR XML so I can test it here before incorporating into funannotate. Thanks and glad it seems to have worked!

**Comment by kcamnairb** [comment]
Yeah, it was able to pick up the GO terms as well. The first 100 individual xml files are attached. 
[individual_xml.tar.gz](https://github.com/nextgenusfs/funannotate/files/619634/individual_xml.tar.gz)

**Comment by nextgenusfs** [comment]
Sorry, I wasn't clear.  I want to have the 100 records from IPR in the single file format so I can do the splitting test here and combine the perl splitting script into funanntoate, so that you can pass the single XML IPR5 output to funannotate and it will parse it correctly.  After combining the individual records that you sent, looks like ~16000 lines.  So how about sending me the first 20,000 lines of the individual XML file (i.e. the output from IPR5).
```
head -n 20000 IPR5.out.xml > IPR5.subset.xml
```
Thanks.

**Comment by kcamnairb** [comment]
Gotcha, attached is the first 20,304 lines, in order to get a full record.
[af3357.subset.xml.tar.gz](https://github.com/nextgenusfs/funannotate/files/619825/af3357.subset.xml.tar.gz)

**Comment by nextgenusfs** [comment]
Sweet, thanks.  And always love to see Aspergillus work!  Hope funannotate is helpful.

**Comment by nextgenusfs** [comment]
Hi Brian,
So I think I incorporated the splitting script, I have not pushed a new release yet as I don't have a means to actually test it at the moment.  Would you be able to test it with your dataset?  The two files that have changed are the `bin/funannotate-functional.py` and then the prepare xml script was added to `util/prepare_ind_xml.pl`.  You could either clone the current repository or just change those two scripts manually.  But you should be able to pass a single xml file for IPR5 to the annotate command like:
```
funannotate annotate -i fun_predict_folder --iprscan IPR5.xml
```
Note you should not need to pass the `--email` option.  

Would be great if you had the time to check into this and then I will push the release if it works.

**Comment by kcamnairb** [comment]
It worked great! Two things needed to be fixed. There is an extra space in the indentation for line 348 in funannotate-functional.py and the `PROTS` variable is not initialized if an argument is provided for `--iprscan` and will cause an error unless the cleanup step in line 377 is commented out. 
Thanks for adding this.

**Comment by nextgenusfs** [comment]
Great thanks, not sure how the space got in there, but good catch.  So the cleanup step should work then if it is like this:
```
if PROTS:
     shutil.rmtree(PROTS)
 ```

**Comment by kcamnairb** [comment]
That would work, or you could add `shutil.rmtree(PROTS)` at the end of the `if not args.iprscan:` block, after line 348, since it seems to only be needed for that block.

**Comment by nextgenusfs** [comment]
supported in v0.3.13

**Comment by kcamnairb** [comment]
Sorry, I was wrong. If `PROTS' is never defined, the `if PROTS:' will cause an error: `NameError: name 'PROTS' is not defined`

**Comment by nextgenusfs** [comment]
yeah your right, i wasn't thinking straight either.  I'll just shuffle things around and declare all possible variables at the beginning, there is no harm in that.
