### ISSUE TITLE
database files not found!

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#331]
Hello,
It is strange. I have run my command to last step. All previous step is running well and I get good results and no error.
But when I run funannotate annotate, I met the error as following. I have updated the database and give the database the path.
Did you met the similar error before?
Thanks,
Fuyou

(funannotate) [fuf@biocluster repeat]$  funannotate annotate -i BL.ref
-------------------------------------------------------
[06:08 PM]: OS: linux2, 80 cores, ~ 1057 GB RAM. Python: 2.7.15
[06:08 PM]: Running funannotate v1.6.0-401c258
[06:08 PM]: Database files not found in /isilon/saskatoon-rdc/users/fuf/database/funDB/, run funannotate database and/or funannotate setup

**Comment by nextgenusfs** [comment]
Database files aren't installed correctly, here is what it is checking for.  Simplest would be to try to reinstall with `funannotate setup --force`
```
#check database sources, so no problems later
sources = [os.path.join(FUNDB, 'Pfam-A.hmm.h3p'), os.path.join(FUNDB, 'dbCAN.hmm.h3p'), os.path.join(FUNDB,'merops.dmnd'), os.path.join(FUNDB,'uniprot.dmnd')]
if not all([os.path.isfile(f) for f in sources]):
    lib.log.error('Database files not found in %s, run funannotate database and/or funannotate setup' % FUNDB)
    sys.exit(1)
```

**Comment by sunnycqcn** [comment]
Hello Jon,
This error is still occurrence.  And I reset the database lots of times. I found I can not find dbCAN.hmm.h3p and  Pfam-A.hmm.h3p. They are dbCAN.hmm.h3i and  Pfam-A.hmm.h3i. I do not know what it is the reason. 
Thanks,
Fuyou

I checked my database,
-rwxr-x--- 1 fuf domain users  2.3M Oct 10 14:12 busco_outgroups.tar.gz
-rwxr-x--- 1 fuf domain users  6.6K Oct 10 14:07 dbCAN.changelog.txt
-rwxr-x--- 1 fuf domain users   59K Oct 10 14:07 dbCAN-fam-HMMs.txt
-rwxr-x--- 1 fuf domain users   84M Oct 10 14:07 dbCAN.hmm
-rwxr-x--- 1 fuf domain users   28K Sep 16 17:13 dbCAN.hmm.h3i
drwxr-x--- 5 fuf domain users   221 Feb 13  2017 dikarya
-rwxr-x--- 1 fuf domain users   64M Oct  4 18:39 dikarya.tar.gz
drwxr-x--- 4 fuf domain users    76 Oct  4 18:34 embryophyta
-rwxr-x--- 1 fuf domain users  1.3K Oct 10 14:15 funannotate-db-info.txt
-rw-r--r-- 1 fuf domain users   11M Mar  1  2016 funannotate.repeat.proteins.fa
-rwxr-x--- 1 fuf domain users  6.1M Oct 10 14:15 funannotate.repeat.proteins.fa.tar.gz
-rwxr-x--- 1 fuf domain users   11M Oct 10 14:15 funannotate.repeats.reformat.fa
-rwxr-x--- 1 fuf domain users   33M Oct 10 14:14 go.obo
-rwxr-x--- 1 fuf domain users  176M Oct 10 14:11 interpro.xml
-rwxr-x--- 1 fuf domain users  1.4M Oct 10 14:12 merops.dmnd
-rwxr-x--- 1 fuf domain users  1.4M Oct 10 14:12 merops.formatted.fa
-rwxr-x--- 1 fuf domain users  1.9M Oct 10 14:12 merops_scan.lib
-rwxr-x--- 1 fuf domain users   21M Oct 10 14:13 mibig.dmnd
-rwxr-x--- 1 fuf domain users   21M Oct 10 14:13 mibig.fa
-rwxr-x--- 1 fuf domain users  1.2M Oct 10 14:10 ncbi_cleaned_gene_products.txt
drwxr-x--- 2 fuf domain users   392 Dec  4  2016 outgroups
-rwxr-x--- 1 fuf domain users 1018K Oct 10 14:10 Pfam-A.clans.tsv
-rwxr-x--- 1 fuf domain users  1.4G Oct 10 14:09 Pfam-A.hmm
-rwxr-x--- 1 fuf domain users  1.2M Oct  4 18:37 Pfam-A.hmm.h3i
-rwxr-x--- 1 fuf domain users   111 Oct 10 14:10 Pfam.version
-rwxr-x--- 1 fuf domain users   11M Oct 10 14:15 repeats.dmnd
-rwxr-x--- 1 fuf domain users  270M Oct 10 14:14 uniprot.dmnd
-rwxr-x--- 1 fuf domain users   151 Oct 10 14:14 uniprot.release-date.txt
-rwxr-x--- 1 fuf domain users  265M Oct 10 14:14 uniprot_sprot.fasta

**Comment by sunnycqcn** [comment]
If I converted dbCAN.hmm.h3i and Pfam-A.hmm.h3i to dbCAN.hmm.h3p and Pfam-A.hmm.h3p, the command is working.
But I am not sure they are correct.
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
You can manually repress the database with hmmpress. Although it should be running that on setup.

**Comment by sunnycqcn** [comment]
Hi Jon,
If I use hmmpress to repress the database, I get the information as following. I am not sure that the command "funannotate setup" should make database index files are Pfam-A.hmm.h3i and dbCAN.hmm.h3i. 
So dbCAN.hmm.h3p and Pfam-A.hmm.h3p can not be gotten using funannotate setup. But command "funannotate annotate" need dbCAN.hmm.h3p and Pfam-A.hmm.h3p. Maybe they are bug.
Do you think so?
Thanks,
Fuyou
hmmpress Pfam-A.hmm
SSI index file Pfam-A.hmm.h3i already exists;
Delete old hmmpress indices first

**Comment by nextgenusfs** [comment]
Yeah you need to delete index files first. I guess funannotate setup should do that in case they existed or are partial, etc.

**Comment by sunnycqcn** [comment]
Hello Jon,
I am much appreciated your pipeline and help me figure out anything. 
Now I deleted whole database and reset the database. It is working well.
Best,
Fuyou
