### ISSUE TITLE
Missing Dependencies: fasta.  Please install missing dependencies and re-run script

### ISSUE THREAD

**Issue by Homap** [nextgenusfs/funannotate#335]
Hello,

I am running `funannotate` on linux system. I managed to run `funannotate sort`, but when I got into `funannotate train`, I got the error:
`Missing Dependencies: fasta.  Please install missing dependencies and re-run script
`
When looking into my funannotate environment, a binary file for `fasta36 `exists. However, I downloaded fasta36 from the github page and put it in the path in my script. I got the error again. I am sorry if this is a simple issue but I really don't know what to try anymore. I would appreciate very much if you could help me with this.

Thank you in advance,
Kind regards,
Homa

**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**

**What command did you issue?**
Copy/paste the command used.

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`

**Comment by hyphaltip** [comment]
You need to symlink fasta36 to fasta
Eg in the folder where it is installed
ln -s fasta36 fasta



Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by Homap** [comment]
Amazing, it is working now. Thank you so so much!
