### ISSUE TITLE
Transcripts from related species?

### ISSUE THREAD

**Issue by antben** [nextgenusfs/funannotate#34]
Hi Jon,

I have some RNAseq data from a species related to the genome that I would like to annotate. The species are probably around 5% divergent. I was thinking to assemble those reads and pass them in as --transcript_evidence. Do you think that that would be effective? Would it be better to just include the translations of the assembled RNAseq data as --protein_evidence?

Thanks,
Ben

**Comment by nextgenusfs** [comment]
Hi Ben,
I would probably try both.  The protein and transcript evidence is passed to Evidence Modeler - however they are given the same weight.  Depending on the divergence at a nucleotide level, they may or may not map to the genome, however likely the protein translations will map with exonerate.  Evidence Modeler will use the splice sites to more accurately predict intron/exon boundaries in relation to the gene predictions from Augustus/GeneMark.  

If you had RNAseq from the species you were annotating, then I would do something like Trinity -> PASA.  It might be worth checking the RNAseq reads you have and seeing what percentage you can map to your genome, I would use hisat2 (but you could use any splice aware aligner).  If you can get a high percentage of the reads to map, you can also pass the sorted BAM alignment file to funannotate and it will run the BRAKER pipeline to train Augustus and GeneMark using splice sites from the mapped reads.  I would be cautious with this approach though depending on the divergence between the two species. Generally GeneMark self training produces good results and the BUSCO mediated training of Augustus is reasonable.  But you will certainly get better predictions if you use protein and transcript evidence.  Remember you can add multiple sources of evidence for both protein and transcript by passing `--transcript_evidence species1.fa,species2.fa,ests.fa,trinity.fasta`.  Same is true for proteins.

Good luck!
Jon

**Comment by antben** [comment]
OK, will do. Thanks for the advice!

Ben

**Comment by nextgenusfs** [comment]
closing as this thread is old.
