### ISSUE TITLE
funannotate train input files

### ISSUE THREAD

**Issue by Homap** [nextgenusfs/funannotate#340]
Hello,

I have 10 RNA-seq samples. When I try to run `funannotate train` using the following command:

```
FORWARD_spain=$workdir/Sample_STE*/*R1*trim_pair.fastq.gz
REVERSE_spain=$workdir/Sample_STE*/*R2*trim_pair.fastq.gz

./${fundir}/funannotate train -i ${ref_spain} -o $outdir_spain --left $FORWARD_spain --right $REVERSE_spain --no_trimmomatic --cpus 8
```
`funannotate train` does not recognise that I have multiple samples. Why is that? the $FORWARD_spain and $REVERSE_spain clearly each contains 10 files. 

Thank you,
Homa

**Comment by nextgenusfs** [comment]
Not sure exactly why this doesn't work, other than perhaps as a variable the space isn't being maintained/interpreted correctly for the input?  Bash expansion should technically work, ie I know that something like `--left *R1.fq.gz --right *R2.fq.gz` does work.
