### ISSUE TITLE
About repeat protein database!

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#342]
Hello Jon,
I can run funannotate well now. I still have a question about three repeat database: funannotate.repeats.reformat.fa, funannotate.repeat.proteins.fa.tar.gz, and repeats.dmnd.
I want to use funannotate to predict the plant genome. My question is  three repeat database are only for fungi or also for plant? I remember the repeat protein of plant is about 40M, which is much bigger than  funannotate.repeat.proteins.fa.tar.gz.
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
Those are a semi curated set of transposable elements from an older tool transposonPSI and from makers repeat protein database. So they are not fungal specific. We (as a group) need to do better with repeat detection/curation/etc especially with RepBase no longer being free for academic use.

**Comment by sunnycqcn** [comment]
Jon,
I got it.
Thanks,
Fuyou
