### ISSUE TITLE
funannotate train stopped after clustering RNA-seq reads

### ISSUE THREAD

**Issue by Homap** [nextgenusfs/funannotate#349]
Hello,

The` funannotate train` has been running for 12 days when it ended with the following error:

```
[11:47 AM]: StringTie installed, running StringTie on Hisat2 coordsorted BAM
[11:47 AM]: Alignment failed, BAM files empty. Please check logfile
```

Trinity log file is attached. 

What could be the problem in this case?

Thank you very much in advance,
Homa

[Trinity-gg.log.zip](https://github.com/nextgenusfs/funannotate/files/3880013/Trinity-gg.log.zip)

**Comment by nextgenusfs** [comment]
Do you have the `funannotate-train.log` -- trinity log looks fine.

**Comment by Homap** [comment]
The genome is 1.1 Gb. I used 31 Cpus and 500 GB RAM. I have 10 RNA-seq samples, paired end, each sample between 36 to 54 million reads. 

Please find the `funannotate-train.log` attached. 

Thanks you!
[funannotate-train.log](https://github.com/nextgenusfs/funannotate/files/3880073/funannotate-train.log)

**Comment by nextgenusfs** [comment]
Looks like seqclean failed -- this is part of PASA package.  If you upgrade PASA to v2.4.1 this should be fixed.  Its an error in some really old code that seems to only show up on HPC systems.  If it is helpful, I updated the PASA to 2.4.1 in conda maybe ~ 1 week ago, so you should be able to just do `conda install pasa=2.4.1` or `conda upgrade pasa`.  You should be able to re-issue the same command and it will pick up where it left off. 

But I agree its strange that it didn't die on your previous run...

The psx (seqclean) error from logfile:
```
[11/22/19 11:47:20]: /usit/abel/u1/annaru/miniconda3/envs/funannotate/opt/pasa-2.3.3/bin/seqclean trinity.fasta -c 16
[11/22/19 11:47:36]: seqclean running options: 
seqclean trinity.fasta -c 16
 Standard log file: seqcl_trinity.fasta.log
 Error log file:    err_seqcl_trinity.fasta.log
 Using 16 CPUs for cleaning
-= Rebuilding trinity.fasta cdb index =-
 Launching actual cleaning process:
 psx -p 16  -n 1000  -i trinity.fasta -d cleaning -C '/projects/cees/in_progress/anna/Homa/sparrow_annotation/bin/trinity.fasta:ANLMS100:::11:0' -c '/cluster/home/annaru/miniconda3/envs/funannotate/opt/pasa-2.3.3/bin/seqclean.psx'
Error at 'psx -p 16  -n 1000  -i trinity.fasta -d cleaning -C '/projects/cees/in_progress/anna/Homa/sparrow_annotation/bin/trinity.fasta:ANLMS100:::11:0' -c '/cluster/home/annaru/miniconda3/envs/funannotate/opt/pasa-2.3.3/bin/seqclean.psx''


Process terminated with an error!
seqclean (trinity.fasta) encountered an error.
Working directory was /projects/cees/in_progress/anna/Homa/sparrow_annotation/bin
seqclean (trinity.fasta) encountered an error.
Working directory was /projects/cees/in_progress/anna/Homa/sparrow_annotation/bin
```

The previous run apparently ran correctly:
```
[10/18/19 13:43:30]: seqclean running options: 
seqclean trinity.fasta -c 8
 Standard log file: seqcl_trinity.fasta.log
 Error log file:    err_seqcl_trinity.fasta.log
 Using 8 CPUs for cleaning
-= Rebuilding trinity.fasta cdb index =-
 Launching actual cleaning process:
 psx -p 8  -n 1000  -i trinity.fasta -d cleaning -C '/projects/cees/in_progress/anna/Homa/sparrow_annotation/bin/trinity.fasta:ANLMS100:::11:0' -c '/cluster/home/annaru/miniconda3/envs/funannotate/opt/pasa-2.3.3/bin/seqclean.psx'
Collecting cleaning reports

**************************************************
Sequences analyzed:    192799
-----------------------------------
                   valid:    192751  (8303 trimmed)
                 trashed:        48
**************************************************
----= Trashing summary =------
                by 'dust':       45
              by 'shortq':        3
------------------------------
Output file containing only valid and trimmed sequences: trinity.fasta.clean
For trimming and trashing details see cleaning report  : trinity.fasta.cln
--------------------------------------------------
seqclean (trinity.fasta) finished on machine c10-27
 in /projects/cees/in_progress/anna/Homa/sparrow_annotation/bin, without a detectable error.

```

**Comment by nextgenusfs** [comment]
As of a few hours ago, you can install the latest funannotate version via conda -- note that >v1.7.0 has a few changes/additions that should be useful, however, you need to re-run `funannotate setup` after installing to update the databases.

**Comment by Homap** [comment]
I installed the new version and it's been working without error so far, thank you.

**Comment by papelypluma** [comment]
Hi @nextgenusfs, I apologize for posting the same/related problem. I've tried finding ways to address the issue, but I have been so far unsuccessful. I've encountered the same issue on funannotate train where it had a non-zero exit error "Alignment failed, BAM files empty. Please check logfile". PASA version is 2.4.1. Sharing both funannotate-train.log and the list of funanntoate dependencies installed on the system for reference. 

Thank you in advance for the help!

[funannotate-train.log](https://github.com/nextgenusfs/funannotate/files/7231600/funannotate-train.log)
[funannotate_check_show-versions.txt](https://github.com/nextgenusfs/funannotate/files/7231601/funannotate_check_show-versions.txt)
