### ISSUE TITLE
`funannotate compare` test failed

### ISSUE THREAD

**Issue by AdamVS** [nextgenusfs/funannotate#350]
Hi Jon - I'm using funannotate v1.7.1 with the sample data:
`$funannotate test -t all --cpus 16`

`$funannotate compare` test failed (NB. but successfully completes everything prior)
[01:07 PM]: Missing Dependencies: proteinortho5.pl.  Please install missing dependencies and re-run script

The latest installation has the latest version:
`$whereis proteinortho'
/home/user/anaconda3/envs/funannotate/bin/proteinortho6.pl`

`
-------------------------------------------------------
Checking dependencies for 1.7.1
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.74
goatools: 0.9.9
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.6.5
requests: 2.22.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed`

`Checking Environmental Variables...
$FUNANNOTATE_DB=/home/adamvs/funannotate_db
$PASAHOME=/home/adamvs/anaconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/adamvs/anaconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/adamvs/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/adamvs/anaconda3/envs/funannotate/config/
$GENEMARK_PATH=/usr/local/bioinfo/GeneMarkES
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.0
blat: BLAT v36
diamond: 0.9.21
emapper.py: 2.0.1
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.48_3.60_lic
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 11.0.1
kallisto: 0.46.0
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.10
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
snap: 2006-07-28
stringtie: 2.0
tRNAscan-SE: 2.0.3 (April 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: signalp not installed`

BTW - signalp is installed and functional

`$ funannotate database`

Funannotate Databases currently installed:

`  Database          Type        Version      Date         Num_Records   Md5checksum                     
  pfam              hmmer3      32.0         2018-08            17929   de7496fad69c1040fd74db1cb5eef0fc
  gene2product      text        1.49         2019-11-12         30680   9289a80dd882b609bfe813f4a16dbb34
  interpro          xml         77.0         2019-11-14         37213   2fdb639b799c9265f7389f04558b382f
  dbCAN             hmmer3      8.0          2019-08-08           607   51c724c1f9ac45687f08d0faa689ed58
  busco_outgroups   outgroups   1.0          2019-11-26             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          5009   a6dd76907896708f3ca5335f58560356
  mibig             diamond     1.4          2019-11-25         31023   118f2c11edde36c81bdea030a0228492
  uniprot           diamond     2019_10      2019-11-13        561356   8e80870faa7cd3d594530da3d033765a
  go                text        2019-10-07   2019-10-07         47375   3bc9ba43a98bf8fcd01db6e7e7813dd2
  repeats           diamond     1.0          2019-11-25         11950   4e8cafc3eea47ec7ba505bb1e3465d21`

**Comment by nextgenusfs** [comment]
Thanks. That’s a bug/something that I missed when upgrading to newest version. I’m away from computer for next week. But ‘proteinortho5.pl’ should just be ‘proteinortho’ in the list of programs in the compare.py script it looks for. @hyphaltip maybe you can patch this fix?

**Comment by hyphaltip** [comment]
Will patch today. @nextgenusfs just to confirm are we working off master or development branch for 1.7.x?

**Comment by nextgenusfs** [comment]
Master branch.

**Comment by nextgenusfs** [comment]
And I missed the signalp in the question, but it is telling you it is not installed as it isn’t in path, so need to be able to run ‘signalp’.

**Comment by AdamVS** [comment]
thanks for the help but it looks like signalp is in the path ...

[01:05 PM]: Running 1.7.1
[01:05 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[01:05 PM]: Checking GenBank file for annotation
[01:05 PM]: Adding Functional Annotation to Genome one, NCBI accession: None
[01:05 PM]: Annotation consists of: 125 gene models
[01:05 PM]: 124 protein records loaded
[01:05 PM]: Running HMMer search of PFAM version 32.0
[01:05 PM]: 89 annotations added
[01:05 PM]: Running Diamond blastp search of UniProt DB version 2019_10
[01:06 PM]: 11 valid gene/product annotations from 13 total
[01:06 PM]: Existing Eggnog-mapper results found: annotate/annotate_misc/eggnog.emapper.annotations
[01:06 PM]: Parsing EggNog Annotations
[01:06 PM]: 132 COG and EggNog annotations added
[01:06 PM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.49
[01:06 PM]: 20 gene name and product description annotations added
[01:06 PM]: Running Diamond blastp search of MEROPS version 12.0
[01:06 PM]: 0 annotations added
[01:06 PM]: Annotating CAZYmes using HMMer search of dbCAN version 8.0
[01:06 PM]: 2 annotations added
[01:06 PM]: Annotating proteins with BUSCO dikarya models
[01:07 PM]: 6 annotations added
[01:07 PM]: Skipping phobius predictions, try funannotate remote -m phobius
[01:07 PM]: Predicting secreted proteins with SignalP
[01:07 PM]: 0 secretome and 0 transmembane annotations added
[01:07 PM]: Parsing InterProScan5 XML file
[01:07 PM]: Found 0 duplicated annotations, adding 625 valid annotations
[01:07 PM]: Converting to final Genbank format, good luck!
[01:07 PM]: Creating AGP file and corresponding contigs file
[01:07 PM]: Writing genome annotation table.
[01:07 PM]: Funannotate annotate has completed successfully!

**Comment by AdamVS** [comment]
Question - are there any predictions in the test data for signalp?

[01:07 PM]: 0 secretome and 0 transmembane annotations added

**Comment by nextgenusfs** [comment]
What is your output from ‘signalp’?  Maybe a newer version than I’m running and maybe the output changed?

**Comment by AdamVS** [comment]
SignalP version 5.0b Linux x86_64

**Comment by nextgenusfs** [comment]
Okay, that’s all it says? Is that printed to stdout or stderr?  I think I have v4.1 which probably explains why it isn’t getting parsed properly by funannotate check as they must have changed where the version was printed to.

**Comment by AdamVS** [comment]
that was just the -version installed and I'm running the benchmark again

**Comment by AdamVS** [comment]
I am now on:- 
`whereis proteinortho' 
`/home/user/anaconda3/envs/funannotate/bin/proteinortho6.pl`
`version 6.0.11`

but detected diamond 0.9.21
____________________________________________________________________________
!!!! 
WARNING 'diamond' version 0.9.21 has a known bug that incorrectly computes the length of an alignment, thus the coverage threshold can produce wrong results leading in false negatives. See https://gitlab.com/paulklemm_PHD/proteinortho/issues/24 for more details.

 >>> Please update diamond to 0.9.29 or higher <<<

Press 'strg+c' to prevent me from proceeding or wait 10 seconds to continue...
!!!

Well then, proceeding...

**Comment by nextgenusfs** [comment]
Okay, haven't seen this one before. Wonder if this is an "edge-case" or if it is a real problem.  The diamond version (in)compatibility is certainly a problem at the moment. I thought v0.9.24 would "thread-the-needle" and work with all of the deps, but I guess not.

**Comment by AdamVS** [comment]
Thanks again Jon and Jason, I can confirm that `funannotate compare` is fully functional with the test data set.
