### ISSUE TITLE
SignalP v5.0 compatibility issue?

### ISSUE THREAD

**Issue by AnnaMSharp** [nextgenusfs/funannotate#352]
Thank you for the tool, I'm trying to set it up to annotate some fungal genomes! We installed the program via conda yesterday

We also installed signalp5, which works when you just run signalp. SignalP and the library have been moved to the funannotate environment. However, signalP doesn't work within funannotate, is this because we're using the wrong version of it?

After running this command:
funannotate check --show-versions

We got the following error: 
	ERROR: signalp not installed

Any advice?

**Comment by nextgenusfs** [comment]
Install signalp4.1 and it will work fine.  Apparently the menu options have changed in v5.0.  The OSX version is corrupt and won't run on my computer, so I don't know what is different or if it will work with funannotate.  Its possible that 5.0 will work in the annotate portion properly, but just will look like its not installed in `funannotate check`.

**Comment by nextgenusfs** [comment]
Follow up: If signalp 4.1 and signalp 5.0 have same runtime command and the same output, then I think it will work fine.  If you could test that would be helpful.

**Comment by AdamVS** [comment]
SignalP version 5.0b (Linux x86_64) appears to work but in `funannotate check --show-versions`
then it will give an error saying not installed.

**Comment by nextgenusfs** [comment]
Okay thanks, so then how do you get version in 5.0? Is it signalp —version? And is that result printed to stdout or stderr?

**Comment by nextgenusfs** [comment]
Still need to fix this -- so if you have >v4.1 then `funannotate check` is going to tell you its not installed properly, however, it will work fine in `funannotate annotate`.

**Comment by AdamVS** [comment]
Thanks Jon. Just to confirm - I'm with v5.02 and it's working fine now (`funannotate check` still says it's not installed.

**Comment by hyphaltip** [comment]
```
/bin/signalp -version
SignalP version 5.0b Linux x86_64
```

**Comment by nextgenusfs** [comment]
Okay -- so just to confirm.  I ran signalP-5 and signalP-4.1 online -- the outputs are different. While it maybe running without error in funannotate, the results surely are not being captured properly with the current code.  Can somebody you has run this on the command line confirm the outputs below?

This is 5.0 -- results are tab delimited.
```
# SignalP-5.0	Organism: Eukarya	Timestamp: 20200217201817
# ID	Prediction	SP(Sec/SPI)	OTHER	CS Position
GN2_000001-T1	OTHER	0.001141	0.998859	
GN2_000002-T1	OTHER	0.001529	0.998471	
GN2_000003-T1	OTHER	0.000303	0.999697	
GN2_000004-T1	OTHER	0.000637	0.999363	
GN2_000005-T1	SP(Sec/SPI)	0.997068	0.002932	CS pos: 19-20. ATG-EC. Pr: 0.5013
GN2_000006-T1	OTHER	0.000747	0.999253	
GN2_000007-T1	SP(Sec/SPI)	0.996577	0.003423	CS pos: 18-19. ARA-ET. Pr: 0.8343
GN2_000008-T1	OTHER	0.014247	0.985753	
GN2_000009-T1	OTHER	0.002122	0.997878	
GN2_000010-T1	OTHER	0.000377	0.999623	
GN2_000011-T1	OTHER	0.000510	0.999490	
GN2_000012-T1	OTHER	0.001593	0.998407	
GN2_000013-T1	OTHER	0.007275	0.992725	
GN2_000014-T1	SP(Sec/SPI)	0.997222	0.002778	CS pos: 22-23. ATA-QT. Pr: 0.7208
```

This is 4.1 -- results are space delimited.
```
# SignalP-4.1 euk predictions
# name                     Cmax  pos  Ymax  pos  Smax  pos  Smean   D     ?  Dmaxcut    Networks-used
GN2_000001-T1              0.110  25  0.115  12  0.140   3  0.116   0.116 N  0.450      SignalP-noTM
GN2_000002-T1              0.147  21  0.144  21  0.218  20  0.140   0.142 N  0.450      SignalP-noTM
GN2_000003-T1              0.109  27  0.107  37  0.135  31  0.103   0.105 N  0.450      SignalP-noTM
GN2_000004-T1              0.114  24  0.121  16  0.187  11  0.140   0.129 N  0.500      SignalP-TM
GN2_000005-T1              0.649  18  0.774  18  0.949  12  0.916   0.851 Y  0.450      SignalP-noTM
GN2_000006-T1              0.116  21  0.120  21  0.286   4  0.125   0.123 N  0.450      SignalP-noTM
GN2_000007-T1              0.457  21  0.611  21  0.921   7  0.811   0.719 Y  0.450      SignalP-noTM
GN2_000008-T1              0.144  41  0.173  41  0.510  35  0.179   0.176 N  0.450      SignalP-noTM
GN2_000009-T1              0.490  38  0.289  38  0.376   8  0.217   0.250 N  0.450      SignalP-noTM
GN2_000010-T1              0.176  33  0.139  33  0.243  50  0.114   0.126 N  0.450      SignalP-noTM
GN2_000011-T1              0.109  33  0.105  33  0.115  54  0.100   0.102 N  0.450      SignalP-noTM
GN2_000012-T1              0.109  47  0.109  12  0.164   2  0.111   0.110 N  0.450      SignalP-noTM
GN2_000013-T1              0.187  32  0.178  32  0.290  18  0.172   0.175 N  0.500      SignalP-TM
GN2_000014-T1              0.751  23  0.836  23  0.971  14  0.930   0.887 Y  0.450      SignalP-noTM
```

**Comment by ChristPap** [comment]
signalP5 did not work for me. But signalP4.1 works and funnanotate check recognizes it. The output is indeed space delimited.
