### ISSUE TITLE
Script to extract the AA and nt CDS from Funanot.gff3

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#355]
Dear John,

Would you be kind enough to point me to your script, or the point in your pipeline that generates the amino acid file and the CDS- nucleotide files from a funannotate GFF3 file. 

I am having issue with reproducible cds file. (8 sequences dont match the amino acid file). I want to dig depper before bothering you further. 

    - as always. Love the software. Great work. 
cheers,

Pete

**Comment by nextgenusfs** [comment]
Hi Pete -- it depends on the version of the pipeline on how/when the outputfiles are written.  As of probably the last 6-8 months the output files are all written from the NCBI tbl file format 
 -- `_results/name_strain.tbl`, that code is here: https://github.com/nextgenusfs/funannotate/blob/master/funannotate/library.py#L2095-L2107

But basically it is all written out of the internal funannotate dictionary structure at then end of each of the scripts (predict, annotate, etc).  So a discrepancy between the GFF3 and the amino acids could be a bug in either the GFF3 output written by the above function.

The `funannotate util` scripts have some converters you can use directly:
```
$ funannotate util

Usage:       funannotate util <arguments>
version:     1.7.0

Commands:
  contrast           Compare annotations to reference (GFF3 or GBK annotations)
  tbl2gbk            Convert TBL format to GenBank format
  gbk2parts          Convert GBK file to individual components
  gff2prot           Convert GFF3 + FASTA files to protein FASTA
  gff2tbl            Convert GFF3 format to NCBI annotation table (tbl)
  bam2gff3           Convert BAM coord-sorted transcript alignments to GFF3
  prot2genome        Map proteins to genome generating GFF3 protein alignments
  stringtie2gff3     Convert GTF (stringTIE) to GFF3 format
  quarry2gff3        Convert CodingQuarry output to proper GFF3 format
```

**Comment by peterthorpe5** [comment]
Haha – this has been spread over various version, which is why I couldn’t answer the question when starting the thread. Let me dig deeper with your response before I waste any of your time.

Cheers,

Pete
