### ISSUE TITLE
funannotate update and train timing

### ISSUE THREAD

**Issue by Homap** [nextgenusfs/funannotate#356]
Hello,

Please apologise me if this is not a relevant question. I have been running `funannotate update`. It progressed without errors up until 
`[12:27 PM]: Running PASA annotation comparison step 1`

It has been there for the last 3 days. My data contains 2 samples of RNA-seq data for an avian genome of about 1.1 Gb. I've given 12 Cpus to this job.

Also, I've been running `funannotate train` for 10 samples of RNA-seq data for an avian genome of 1.1 Gb until it reached this step:
`[08:10 PM]: Running PASA alignment step using 690,493 transcripts`

 This has been running for the last 4 days. I've given 32 cpus and 500 G memory to this task.

I was wondering if this timing is quite normal or is there something wrong with the duration of these processes?

Thank you very much for your help,
All the best,
Homa

**Comment by nextgenusfs** [comment]
The default database is SQLite in PASA - this is then more flexible in terms of being able to work out of the box on most HPC systems. However, SQLite in PASA is single threaded so it is quite slow, especially if you have a large genome. You can setup MySQL with PASA and that will run multithreaded so would be a lot faster.

**Comment by Homap** [comment]
Hi Jon, 

Thank you very much for your help. I think I really need to set up MySQL with PASA as the jobs crashed after 7 days without much progress. 

I have installed funannotate using conda installation. Is there a way that I can change the database in the installed funannotate environment from SQLite to MySQL or should I download PASA from scratch?

Thank you very much in advance,
All the best,
Homa

**Comment by Homap** [comment]
Hi Jon,

I just re-read the documentation. It seems I can only change the `--pasa_db` to `mysql`. Is that correct? This seems quite easy.

Thanks,
Homa

**Comment by hyphaltip** [comment]
I think you have to also set add user/pass info in Pasa pasa_conf folder

Jason

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by Homap** [comment]
Hi Jason,

You are right, I just got the following error:
```
    with open(os.path.join(PASA, 'pasa_conf', 'conf.txt'), 'rU') as pasaconf:
IOError: [Errno 2] No such file or directory: '~/miniconda3/envs/genome_annotation/opt/pasa-2.4.1/pasa_conf/conf.txt'

I have to change the `pasa.CONFIG.template` into `conf.txt` I guess and fill out the information on username and password. Although have to figure out how to set up mysql password.

Thanks for your help,
Homa

**Comment by Homap** [comment]
Hi again,

Just one question. In the PASA github page, it says the first step is to run the following command:
`mysql -p -uroot `. However, I work on a cluster and I don't know what the root password for `mysql `is. I was wondering if you have any suggestion regarding this?

Thank you,
All the best,
Homa

**Comment by nextgenusfs** [comment]
You need to setup the mysql users and thus need admin access to the database. You need one user that can create databases/tables and the other to simply read the data.  This only has to be setup once, so try to work with your sysadmin to get the mysql backend up and running first.  The is the main reason that sqlite is the default, many clusters don't let you run mysql as it can be a security threat.

**Comment by Homap** [comment]
Thanks Jon. I see now. My genome is 1.1 Gb and I have 10 RNA-seq samples but I also now wonder if there is something I've done wrong with my funannotate installation. Is there a way to check the progress that PASA is making? In the log-file, I can only see the command of `Launch_PASA_pipeline.pl`.

Thank you very much again,
Cheers,
Homa

**Comment by Homap** [comment]
Unfortunately, had to stop `funannotate update`. Another colleague said that he did not manage to run the `update` command on his genome either. As you said, it was not possible to use MySQL on the cluster so I am going to skip update and go to functional annotation.

**Comment by nextgenusfs** [comment]
Added some docs for this here: https://funannotate.readthedocs.io/en/latest/update.html#why-is-funannotate-update-so-slow
