### ISSUE TITLE
Conda install 1.7 paths for train step utils

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#357]
In `train` - expecting to find bin/util/insilico_read_normalization.pl
But its installed in bin/insilico_read_normalization.pl in conda install so I assume should fix the train step to use the path as installed by conda version but just wanted to check if this is your intention of what goes in the bin path with the conda install?

**Comment by hyphaltip** [comment]
I see now that when trinity conda is installed we have the tool in 
```.../opt/trinity-2.8.5/util/insilico_read_normalization.pl```

**Comment by nextgenusfs** [comment]
So with Conda it should be setting your TRINITY_HOME to that `/path/to/conda/opt/trinity-2.8.5`.  Funannotate looks first for TRINITYHOME and then TRINITY_HOME. Per Trinity usage, all of the commands are called using the $TRINITY_HOME location -- if the conda install is not doing this, then I'll fix the conda install as that is the way the Trinity developers have used the code.

**Comment by hyphaltip** [comment]
No this then was a carry over from previous run scripts where I had to set this variable in earlier versions of funannotate. I’ll remove setting those variables. Prob same for pasa too!

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by nextgenusfs** [comment]
yeah, worth checking which build of conda though as well -- so for trinity only build5 I believe has the proper ENV variable exported into the environment.  I don't understand the conda solver, but I do know it doesn't always grab the most recent build.

**Comment by hyphaltip** [comment]
Now i have problems that transdecoder plugin not installed in PASA in conda - do you have it in yours - looks like it is 2.4.1 installed.
```
 [Mon Dec 16 14:08:44 2019] Running CMD: /opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/envs/funannotate/opt/pasa-2.4.1/pasa-plugins/transdecoder/TransDecoder.LongOrfs -t __all_transcripts.fasta   -S
Can't exec "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/envs/funannotate/opt/pasa-2.4.1/pasa-plugins/transdecoder/TransDecoder.LongOrfs": No such file or directory 
```

**Comment by nextgenusfs** [comment]
Huh -- which funannotate version and which script? I thought I got rid of the separate transdecoder call.
