### ISSUE TITLE
Adding transcript evidence to prediction after training

### ISSUE THREAD

**Issue by Tierhon** [nextgenusfs/funannotate#360]
**Are you using the latest release?**
Yep.

**Describe the bug**
Not a bug, just a clarification of how the code works.

Hi,
am I correct in interpreting code (specifically  https://github.com/nextgenusfs/funannotate/blob/93288e88e7319b4fe461a1c6d09920123b8e0d47/funannotate/predict.py#L329) correctly in that if funannotate_train.transcripts.gff3 exists, anything specified in transcript_evidence or transcript_alignments are ignored? 

The reason I am asking is that I have some manually found genes (or fragments of genes) which I would like to add in some way to make sure that they are called. 

If adding them as transcript evidence is not working as it is now, can I add them to other_gff even though the intron-exon borders are not exact? What does EVM do if it is just a fragment not supported by any gene prediction?

Thank you.

Ole

**Comment by nextgenusfs** [comment]
Yes -- the assumption that you ran `funannotate train` using RNA-seq data then the pipeline re-uses those data and passes the results to EVM, so the pipeline tries to save some time by not re-running those alignments.  But perhaps this should be a bit more flexible, where maybe unique transcripts found in `--transcript_evidence` should be added if they do not exist in `--transcript_alignments`. 

EVM only uses transcript alignments to help choose the best model from the gene predictions, so it will not generate gene models from any evidence (protein or transcript).

So if you want some particular gene models to persist you can pass them via the --other_gff option and then give it a significant weight, ie. `--other_gff yourManualGenes.gff:10`.  That will add those gene models and give it a weight of 10, which should be enough to alter the EVM scoring to keep those models. But you want to make sure that they are real gene models, ie make a valid protein sequence (don't have internal stops etc).  If it is not a valid ORF, it won't make it out of EVM/filtering.

**Comment by Tierhon** [comment]
So more flexibility could be nice, but I understand that there is a lot of choices one has to make along the path to developing this.

I think the --other_gff is a good solution so far at least for me. It is good to have as a sanity check the gene models are proper ORFs. 

Thank you.

Ole

**Comment by nextgenusfs** [comment]
I'm looking into how long will take to parse a normal BAM alignment file and cross-reference with transcripts added via `--transcript_evidence`.  If I can do this somewhat quickly, then will add that as default routine if both `--transcript_alignments` and `--transcript_evidence` are present.

**Comment by nextgenusfs** [comment]
Latest few commits in the master should address this issue, now the evidence is checked against alignments and those sequences that do not have alignments are re-aligned with minimap2.  Additionally, Augustus hints were not being generated for those alignments in `--transcript_alignments`, so that is now added as well.

**Comment by Tierhon** [comment]
Cool, thank you.
