### ISSUE TITLE
About command funannotate compare

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#361]
Dear Jon,
Happy new year!
I have annotated my fungal genome. I want to use command funannotate compare. However, I am successful to use this command with version 1.6. 
I updated to 1.71 version.
Then I met three problems as following. I can not figure out these.
Thanks,
Fuyou

1. NO COG annotations found. In fact, COG have been annotated when I annotated genome.
2. No SignalP annotations found. It is the same with above.
3. It is stop with following error. 
```
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/compare.py", line 376, in main
    pfamdf2.to_csv(os.path.join(args.out, 'pfam', 'pfam.results.csv'))
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/core/generic.py", line 3020, in to_csv
    formatter.save()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 172, in save
    self._save()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 288, in _save
    self._save_chunk(start_i, end_i)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 315, in _save_chunk
    self.cols, self.writer)
  File "pandas/_libs/writers.pyx", line 55, in pandas._libs.writers.write_csv_rows
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2032' in position 1: ordinal not in range(128)
```

**Comment by nextgenusfs** [comment]
Log files would be helpful.

**Comment by nextgenusfs** [comment]
Or if you would like to send me two of your GenBank files that are causing problems I can take a look. nextgenusfs at gmail dot com

**Comment by sunnycqcn** [comment]
Hi Jon,
I have sent you by email.
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
Hi Jon,
The log file looks like good. But the isolates are 166. I remembered somebody said he can run 62 genome previous issue. Can I run about more 100 isolates?
Thanks,
Fuyou 
[funannotate-compare.log](https://github.com/nextgenusfs/funannotate/files/4031856/funannotate-compare.log)

**Comment by nextgenusfs** [comment]
I'm not sure but I think it can't support that many genomes -- I think the issue has to do with auto generation of the graphics, it will likely die on you.  If I knew where the "cutoff" was we could have it only draw the graphics if less than X number of species.

**Comment by sunnycqcn** [comment]
How about only have the statistics summary? Can I set some parameters?

**Comment by nextgenusfs** [comment]
I'll have to add an option/parameter to the script to be able to turn on/off the graphs, or perhaps set a limit that can be adjusted, ie `--graph-max-species 20`

**Comment by sunnycqcn** [comment]
If you improve this, it should be very helpful to me. I have annotated about 160 isolate fungal genomes using your pipeline. It is excellent results. I want to compare them.
Thanks,
Fuyou

**Comment by atiweb** [comment]
Hi #sunnycqcn, check if it is solved for you this issue and close this.
Greetings

**Comment by sunnycqcn** [comment]
> Hi #sunnycqcn, check if it is solved for you this issue and close this.
> Greetings

Hi @atiweb ,
I am reannotated my isolates. I did not test the new command. I think I will test it next week. If I have any problem, I will let you know.
Thanks for your helping.
Fuyou

**Comment by sunnycqcn** [comment]
Hello Jon,
I still have this problem when I compare the annotation files, the command can not find  COG and SignalP annotations. Others are good.
I have rerun all isolates with the latest version. I think my annotations files have COG and SignalP results. 
The attachments are my running log file.
By the way, currently, I can compare more 60 isolates. It is a good ehancement.
Thanks,
Fuyou

[funannotate-compare.log](https://github.com/nextgenusfs/funannotate/files/4403968/funannotate-compare.log)
[funannotate-annotate.log](https://github.com/nextgenusfs/funannotate/files/4403976/funannotate-annotate.log)

**Comment by sunnycqcn** [comment]
Hi Jon,
I changed dpi=1000 into dpi=1 in code library.py", line 6773, in drawHeatmap fig.savefig(output, format='pdf', dpi=1000, bbox_inches='tight') ,
Then I can do about 200 isolates compare with all figures. 
However,  I still can not figure our why I can not get COG and SignalP compare.
Best,
Fuyou
