### ISSUE TITLE
All hypothetical proteins

### ISSUE THREAD

**Issue by apn83** [nextgenusfs/funannotate#364]
Hi,
I used the following command to perform funannotate:
I tried to use gff3 output by braker, but it did not work (log: malformed gff3). hence I updated it using PASA and used it.

`funannotate annotate --gff CC7_pasa_updated.gff3 --fasta CC7_R6_locked.scaffolds.Protein.masked.fasta -s "Nematostella vectensis" -o CC7_fun --eggnog 21.CC7_emapper.annotations --iprscan IPR_CC7v2.xml --busco_db metazoa -d ./funannotate_db/ --cpus 20`

The log file showed the program completed successfully !. However, *.annotation.txt shows all the protein to be "hypothetical protein". When I check the annotation_misc folder, each of the database searches were generated properly and I could see genes mapped to their corresponding annotations (
[funannotate-annotate.log](https://github.com/nextgenusfs/funannotate/files/4044678/funannotate-annotate.log)
. Can you please let me know, what is the issue here ?
Thanks in Advance.

**Comment by nextgenusfs** [comment]
Can you post a few lines of the resulting .tbl annotation file?  And then also 10 or so lines of the annotations file, `annotate_misc/all.annotations.txt`.  My guess is that the gene models are named in a way it is not expecting.

**Comment by gitarunprasanna83** [comment]
> Can you post a few lines of the resulting .tbl annotation file? And then also 10 or so lines of the annotations file, `annotate_misc/all.annotations.txt`. My guess is that the gene models are named in a way it is not expecting.

Hi,
all.annotations.txt is the following:
```
AIPCC7_20144.t1	db_xref	PFAM:PF10417
AIPCC7_20144.t2	db_xref	PFAM:PF10417
AIPCC7_20167.t1	db_xref	PFAM:PF00198
AIPCC7_20129.t1	db_xref	PFAM:PF13640
AIPCC7_20800.t1	db_xref	PFAM:PF01073
AIPCC7_20828.t1	db_xref	PFAM:PF00001
AIPCC7_20099.t1	db_xref	PFAM:PF00001
AIPCC7_20082.t1	db_xref	PFAM:PF00001
AIPCC7_20827.t1	db_xref	PFAM:PF00001
AIPCC7_20327.t1	db_xref	PFAM:PF00001
AIPCC7_20961.t1	db_xref	PFAM:PF00001
AIPCC7_21143.t1	db_xref	PFAM:PF00001
AIPCC7_21078.t1	db_xref	PFAM:PF00001
AIPCC7_20973.t1	db_xref	PFAM:PF00001
AIPCC7_20419.t1	db_xref	PFAM:PF00001
AIPCC7_21329.t1	db_xref	PFAM:PF00001
AIPCC7_20507.t1	db_xref	PFAM:PF00001
AIPCC7_21038.t1	db_xref	PFAM:PF00001
AIPCC7_21057.t1	db_xref	PFAM:PF00001
```
.tbl file:

>Feature CC7scaffold1
1	9589196	REFERENCE
			CFMR	12345
27204	23573	gene
			locus_tag	AIPCC7_15333
27204	27131	mRNA
27060	27000
26640	26535
25815	25727
25175	25002
24635	24472
23678	23573
			product	hypothetical protein
			transcript_id	gnl|ncbi|AIPCC7_15333-T1_mrna
			protein_id	gnl|ncbi|AIPCC7_15333-T1
27204	27131	CDS
27060	27000
26640	26535
25815	25727
25175	25002
24635	24472
23678	23573
			codon_start	1
			product	hypothetical protein
			transcript_id	gnl|ncbi|AIPCC7_15333-T1_mrna
			protein_id	gnl|ncbi|AIPCC7_15333-T1
50091	41247	gene
			locus_tag	AIPCC7_15334
50091	49558	mRNA
48102	48058
47618	47493
43929	43832
43330	43201
42880	42785
41666	41570
41368	41247
			product	hypothetical protein
			transcript_id	gnl|ncbi|AIPCC7_15334-T1_mrna
			protein_id	gnl|ncbi|AIPCC7_15334-T1
Thanks.

**Comment by nextgenusfs** [comment]
Okay, I think I found it. A function that writes the tbl file was implementing the funannotate-like naming of transcripts/proteins, i.e. -T1, -T2, etc -- which then made the protein names not match those in the annotation file (you can see that from what you posted).  I've flipped this off when passing --gff and --fasta options, so it should use then the IDs for the mRNA field as the transcript/protein identifiers.  

I also tried to expand the GFF3 parsing a little bit -- its difficult to parse all the different flavors of GFF3 out there.  If you know which lines that it said 'malformed gff3' for then I can take a look at why its failing on those -- it might have told you in the log file?  

I'm still running some internal tests on these changes and when it checks out I'll push the updates.  Hopefully after updating funannotate, you can issue the same command and it technically should re-ruse the data you've already generated and complete successfully.

**Comment by gitarunprasanna83** [comment]
> Okay, I think I found it. A function that writes the tbl file was implementing the funannotate-like naming of transcripts/proteins, i.e. -T1, -T2, etc -- which then made the protein names not match those in the annotation file (you can see that from what you posted). I've flipped this off when passing --gff and --fasta options, so it should use then the IDs for the mRNA field as the transcript/protein identifiers.
> 
> I also tried to expand the GFF3 parsing a little bit -- its difficult to parse all the different flavors of GFF3 out there. If you know which lines that it said 'malformed gff3' for then I can take a look at why its failing on those -- it might have told you in the log file?
> 
> I'm still running some internal tests on these changes and when it checks out I'll push the updates. Hopefully after updating funannotate, you can issue the same command and it technically should re-ruse the data you've already generated and complete successfully.

Hi Jon,
I agree that, it is difficult to cater flexible formats of gff3. It will be good to have one consensus gff3 format for funannotate to begin. Say, users can pass the gff3 to existing parsers to tidy it up a bit (e.g. gff3toolkit).
--malformed gff3 was logged, when I used braker output. Those gene entries that carried 'stop_codon' before exon regions showed this kind of error. I used isoseq data to update these regions and this gff3 was one I used. 
Thank you very much for your help !. Awaiting your message to finish the job. 
Best.

**Comment by nextgenusfs** [comment]
Okay, I think it should be fixed. You can install master into your env with:
```
python2 -m pip install git+https://github.com/nextgenusfs/funannotate.git
```

**Comment by nextgenusfs** [comment]
Let me know if braker GFF3 parsing is fixed as well.

**Comment by gitarunprasanna83** [comment]
> Okay, I think it should be fixed. You can install master into your env with:
> 
> ```
> python2 -m pip install git+https://github.com/nextgenusfs/funannotate.git
> ```

I installed it with conda. Should I just do conda update funnotate ?

**Comment by gitarunprasanna83** [comment]
> Okay, I think it should be fixed. You can install master into your env with:
> 
> ```
> python2 -m pip install git+https://github.com/nextgenusfs/funannotate.git
> ```
Hi,
conda update did not help. and i did pip install. It uninstalled 1.7.2 and installed 1.7.3. Good news is that, tbl assigns the proteinid in correct format and now I get the ipr,pfam,GO and other columns filled. But in the Name column, its all hypothetical proteins again !.
.tbl file:
```
>Feature CC7scaffold1
1	9589196	REFERENCE
			CFMR	12345
27204	23573	gene
			locus_tag	AIPCC7_15333
27204	27131	mRNA
27060	27000
26640	26535
25815	25727
25175	25002
24635	24472
23678	23573
			product	hypothetical protein
			transcript_id	gnl|ncbi|AIPCC7_15333.t1_mrna
			protein_id	gnl|ncbi|AIPCC7_15333.t1
```
*discrepancy.report:
Discrepancy Report Results

Summary
```
DISC_PROTEIN_NAMES:All proteins have same name "hypothetical protein"
FATAL: INCONSISTENT_LOCUS_TAG_PREFIX:8406 features have locus tag prefix AIPCC7.
FATAL: INCONSISTENT_LOCUS_TAG_PREFIX:54 features have locus tag prefix novel.
FATAL: INCONSISTENT_LOCUS_TAG_PREFIX:7 features have locus tag prefix split.
FATAL: BAD_LOCUS_TAG_FORMAT:78 locus tags are incorrectly formatted.
```

*.annotation.txt

`AIPCC7_19759	CDS	CC7scaffold185	56252	57509	-		hypothetical protein		PF05485	IPR006612;IPR038441	ENOG41		GO:0003676						M..`

**Comment by nextgenusfs** [comment]
No conda available until I tag a release and then get the conda recipe updated. 

Okay, so looks better.  But you still have 100% of proteins as hypotheticals? There should be an intermediate file that has the gene names parsed from uniprot/eggnog -- something must still be not quite right.  How many did it say it found in the logfile?

**Comment by gitarunprasanna83** [comment]
> No conda available until I tag a release and then get the conda recipe updated.
> 
> Okay, so looks better. But you still have 100% of proteins as hypotheticals? There should be an intermediate file that has the gene names parsed from uniprot/eggnog -- something must still be not quite right. How many did it say it found in the logfile?

Hi Jon,
Yes. all were hypotheticals. I dont find anything weird in log files. I have just head all annotation file for your reference.
Thanks,
Arun
[annotations_misc.head.txt](https://github.com/nextgenusfs/funannotate/files/4055013/annotations_misc.head.txt)
[funannotate-annotate.log](https://github.com/nextgenusfs/funannotate/files/4055016/funannotate-annotate.log)

**Comment by nextgenusfs** [comment]
Thanks -- okay error is here:
```
==> annotations.genes-products.txt <==
AIPCC7_21555.t1	name	AAK1_1
AIPCC7_21555.t1	product	AP2-associated protein kinase 1
AIPCC7_21563.t1	name	AAK1_2
AIPCC7_21563.t1	product	AP2-associated protein kinase 1
AIPCC7_21565.t1	name	AAK1_3
AIPCC7_21565.t1	product	AP2-associated protein kinase 1
AIPCC7_6510.t1	name	ABCB7
AIPCC7_6510.t1	product	ATP-binding cassette sub- B member 7, mitochondrial
AIPCC7_20154.t1	name	ABCD3
AIPCC7_20154.t1	product	ATP-binding cassette sub- D member 3
```
The gene names should be listed (not transcript IDs) for the name.  If a gene doesn't have a name it can't have a product definition.  So that means something is not quite right there with parsing of your GFF3.  I'll have a look in more detail after work tonight. 

for example, it should look like:
```
AIPCC7_21555 	name	AAK1_1
AIPCC7_21555.t1	product	AP2-associated protein kinase 1
```

**Comment by gitarunprasanna83** [comment]
> Thanks -- okay error is here:
> 
> ```
> ==> annotations.genes-products.txt <==
> AIPCC7_21555.t1	name	AAK1_1
> AIPCC7_21555.t1	product	AP2-associated protein kinase 1
> AIPCC7_21563.t1	name	AAK1_2
> AIPCC7_21563.t1	product	AP2-associated protein kinase 1
> AIPCC7_21565.t1	name	AAK1_3
> AIPCC7_21565.t1	product	AP2-associated protein kinase 1
> AIPCC7_6510.t1	name	ABCB7
> AIPCC7_6510.t1	product	ATP-binding cassette sub- B member 7, mitochondrial
> AIPCC7_20154.t1	name	ABCD3
> AIPCC7_20154.t1	product	ATP-binding cassette sub- D member 3
> ```
> 
> The gene names should be listed (not transcript IDs) for the name. If a gene doesn't have a name it can't have a product definition. So that means something is not quite right there with parsing of your GFF3. I'll have a look in more detail after work tonight.
> 
> for example, it should look like:
> 
> ```
> AIPCC7_21555 	name	AAK1_1
> AIPCC7_21555.t1	product	AP2-associated protein kinase 1
> ```

Please find a screenshot of how my pasa updated gff3 looks, if it helps you.
![example_gene_gff3](https://user-images.githubusercontent.com/17428109/72283661-47e9a700-3650-11ea-8dc6-2c0d3956c714.jpeg)

**Comment by nextgenusfs** [comment]
It should be grabbing both the ID and Name separately -- but yes something like that is happening.  Can you show me a few of the FASTA headers in genome.proteins.fasta?  I want to make sure the headers look okay.  But I think I have likely something hard coded with splitting based on the funannotate naming, ie. splitting on -T1 to get the gene name -- just need to find where it is in the code!

**Comment by nextgenusfs** [comment]
Okay found it and I think now fixed.  Can you test the most recent master? Install with same pip command as above.

**Comment by gitarunprasanna83** [comment]
> Okay found it and I think now fixed. Can you test the most recent master? Install with same pip command as above.

Hi Jon,
I did the same, but not working still.
After I pip, it built 1.7.3-*
`Created wheel for funannotate: filename=funannotate-1.7.3-cp27-none-any.whl size=445988 sha256=67af5349b3903b27712ad56f6e8711ce5caae86014bbeddac5555018f61d1e27`

The header for my genome.protein.fa and genome.transcripts.fasta file (mRNA id and ID separated by space):
`>AIPCC7_1.t1 AIPCC7_1`
Please find attached the discrepancy report for your reference.
Thanks.
[discrepency.report.txt](https://github.com/nextgenusfs/funannotate/files/4057853/discrepency.report.txt)

**Comment by nextgenusfs** [comment]
Okay, I made a test case like yours and got it to work -- the last commit is a very minor change and I'd be surprised if it behaved differently than the previous.  Could you please try?  Also, you might need to run a somewhat "fresh" run, so specify a new output directory and see if that fixes the issues.

**Comment by gitarunprasanna83** [comment]
> Okay, I made a test case like yours and got it to work -- the last commit is a very minor change and I'd be surprised if it behaved differently than the previous. Could you please try? Also, you might need to run a somewhat "fresh" run, so specify a new output directory and see if that fixes the issues.

Hi Jon,
I ran it again with latest pip, but no difference. I did delete the old folders and gave a fresh run, still I got "all hypothetical proteins". I tried a new thing, manually removed the annotation-gene-product.txt to look like,
```
AIPCC7_21555	name	AAK1_1
AIPCC7_21555.t1	product	AP2-associated protein kinase 1
```
and re-ran the program thinking that it would escape through checkpoint. However, it was over-written again with old-format we are dealing with !.

**Comment by nextgenusfs** [comment]
Would you be able to send me a subset of your data so I can try locally? Not sure where else to look. Can email it to nextgenusfs at gmail dot com.

**Comment by nextgenusfs** [comment]
Don't worry about what you see above -- I actually misspoke about the format of the annotation-gene-product.txt file, it shouldn't have the gene name actually for name -- this gets modified on the fly with a dictionary.

**Comment by euduca** [comment]
Hi Jon,
i finished my annotation today and I got 15006 hypothetical proteins (total proteins: 15800).

I'm using funannotate 1.7.4 and I followed the tutorial at https://funannotate.readthedocs.io/en/latest/tutorials.html .

If there's a way to help you can count with me. (Iim not a developer but I can be a tester).

Best.

**Comment by bearcuhk** [comment]
Did you use eggnog and interproscan? I added eggnog and interproscan, and then much more genes got names. For your information.
