### ISSUE TITLE
Request: Docker 1.7.X on Docker hub

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#366]
HI Jon,
As always, love the software. 

Would you please put up a "latest" version in Docker hub (if possible with both type of SQL?), we too have Conda issues (of various kinds) ... Some, I think related to the old Linux version we are currently stuck on. 

Publication: How long till this is published? I will need to reference it soon. 
Cheers,

Pete

**Comment by nextgenusfs** [comment]
Okay. I was planning on not supporting the docker image as I spent the time to get conda working. The docker image building was taking quite a bit of time. Do you have any refs/walkthroughs on how to make that automatic? Ie if new version released then it builds and pushes to docker?  I was having to do it manually — and since my time on this is volunteer outside of work and I don’t use docker — I decided that it was more work than necessary.

**Comment by peterthorpe5** [comment]
Hi Jon,

I completely understand!! We are appreciate your efforts. I have asked a local expert for advise on automatic Docker build and submit. I will get back to you once I have something sensible.

Conda is the future, but some dependencies require a more modern Linux (as does the docker to be fair).

Cheers,

Pete

**Comment by peterthorpe5** [comment]
The answer is yes. I will write you some notes. Back in touch after I have done this.

Pete

**Comment by reslp** [comment]
Hi,

Jon, first of all thank you for funannotate! 
I just wanted to let you know that I have spent some time on preparing a Docker container for funannotate (currently based on the 1.7.2 release). Maybe this is interesting for you. At the moment it works reasonable well, although I have no possibility to test every feature of funannotate. It is still very much a work in progress and usage (eg. howto bind local directories) needs to be documented better.
The goal is to also make it work in a cluster setting with singularity containers and snakemake. Initial tests for that look promising but there are some quirks. If you are interested, have a look [here](https://github.com/reslp/funannotate-docker).


all the best, 
Philipp

**Comment by peterthorpe5** [comment]
Thanks Philip, this is useful!!!! Regarding binding directories, do you need to do this in singularity? I know you do in docker ... 

Kind regards, Pete

**Comment by nextgenusfs** [comment]
Nice @reslp.  The GlimmerHMM likely fails because the training module required a whole bunch of patches in order to work -- see the bioconda recipe that we built/hacked here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/glimmerhmm/build.sh.

**Comment by reslp** [comment]
Thanks for the hint Jon, I will have a look at the glimmerhmm recipe. 
Pete, yes you also have to bind directories in singularity. Singularity does bind some places automatically (eg. the home folder). But special things need to be bound manually as well.
