### ISSUE TITLE
assemble_clusters.dbi fails

### ISSUE THREAD

**Issue by ctxchris** [nextgenusfs/funannotate#368]
Hi,

I run funannotate 1.7.2 installed via conda on Ubuntu 18.04. 

`funannotate train` was executed with mapped Illumina RNAseq data. The `assemble_clusters.dbi` step in Pasa throws the following errors

> DBD::SQLite::st execute failed: disk I/O error at /envs/funannotate/opt/pasa-2.4.1/PerlLib/DB_connect.pm line 178
> Failed query: <select ci.id, ci.length, ci.cdna_acc, ci.is_fli,  ci.header, a.lend, a.rend, a.mlend, a.mrend, a.orient,  al.aligned_orient, al.spliced_orient, al.validate, al.prog, al.align_acc, a.per_id  from alignment a, cdna_info ci, align_lin
> k al  where a.align_id = 205922 and a.align_id = al.align_id  and al.cdna_info_id = ci.id >       values: 
> Errors: disk I/O error
> Thread 135 terminated abnormally: Failed query: <select ci.id, ci.length, ci.cdna_acc, ci.is_fli,  ci.header, a.lend, a.rend, a.mlend, a.mrend, a.orient,  al.aligned_orient, al.spliced_orient, al.validate, al.prog, al.align_acc, a.per_id  from al
> ignment a, cdna_info ci, align_link al  where a.align_id = 205922 and a.align_id = al.align_id  and al.cdna_info_id = ci.id >     values: 
> Errors: 
>  at /envs/funannotate/opt/pasa-2.4.1/PerlLib/DB_connect.pm line 203 thread 135.
>         DB_connect::do_sql_2D(DB_connect=HASH(0x5654a6ef0f70), "select ci.id, ci.length, ci.cdna_acc, ci.is_fli,  ci.header, "...) called at /envs/funannotate/opt/pasa-2.4.1/PerlLib/Ath1_cdnas.pm line 59 thread 135
>         Ath1_cdnas::create_alignment_obj(DB_connect=HASH(0x5654a6ef0f70), 205922, SCALAR(0x5654a6c46308)) called at /envs/funannotate/opt/pasa-2.4.1/scripts/assemble_clusters.dbi line 203 thread 135
>         main::assemble_transcripts_on_scaffold("seq252") called at /envs/funannotate/opt/pasa-2.4.1/scripts/assemble_clusters.dbi line 135 thread 135
>         eval {...} called at /envs/funannotate/opt/pasa-2.4.1/scripts/assemble_clusters.dbi line 135 thread 135
> ERROR, thread 135 exited with error Failed query: <select ci.id, ci.length, ci.cdna_acc, ci.is_fli,  ci.header, a.lend, a.rend, a.mlend, a.mrend, a.orient,  al.aligned_orient, al.spliced_orient, al.validate, al.prog, al.align_acc, a.per_id  from 
> alignment a, cdna_info ci, align_link al  where a.align_id = 205922 and a.align_id = al.align_id  and al.cdna_info_id = ci.id >   values: 
> Errors: 
>  at /envs/funannotate/opt/pasa-2.4.1/PerlLib/DB_connect.pm line 203 thread 135.
>         DB_connect::do_sql_2D(DB_connect=HASH(0x5654a6ef0f70), "select ci.id, ci.length, ci.cdna_acc, ci.is_fli,  ci.header, "...) called at /envs/funannotate/opt/pasa-2.4.1/PerlLib/Ath1_cdnas.pm line 59 thread 135
>         Ath1_cdnas::create_alignment_obj(DB_connect=HASH(0x5654a6ef0f70), 205922, SCALAR(0x5654a6c46308)) called at /envs/funannotate/opt/pasa-2.4.1/scripts/assemble_clusters.dbi line 203 thread 135
>         main::assemble_transcripts_on_scaffold("seq252") called at /envs/funannotate/opt/pasa-2.4.1/scripts/assemble_clusters.dbi line 135 thread 135
>         eval {...} called at /envs/funannotate/opt/pasa-2.4.1/scripts/assemble_clusters.dbi line 135 thread 135

I started `train` with 50 cores. 
Executing `assemble_clusters.dbi` separately with just one core worked, so it may be an issue with perl parallelization.

Best,
Chris

**Comment by atiweb** [comment]
SqLite do not admit paralelization. See https://github.com/mapbox/node-sqlite3/issues/408

Use --pasa_db mysql in funannotate train, you will use all cpu, otherwise, with sqlLite will use only one.

Here Jon explain it better:
The default SQL database for PASA is set to use SQLite – this is for compatibility. However, the limitation is that SQLite database in PASA is single threaded due to SQLite database lock issue. Thus even if you pass multiple cpus to the script, it will run all of the PASA steps single threaded, which can take a long time depending on PASA alignments and genome size. If you setup PASA to use MySQL, then the scripts can run PASA multi-threaded and funannotate update will run much faster. 
Greetings

**Comment by ctxchris** [comment]
Thanks Adalberto. I will set up a mysql db.
In the meantime I tried to continue with sqlite, but the perl DB module seems somewhat unstable:

> /envs/funannotate/opt/pasa-2.4.1/scripts/populate_mysql_assembly_sequence_field.dbi -M 'DB' -G genome.fasta
-connecting to SQLite db: DB
DBD::SQLite::st execute failed: disk I/O error at /envs/funannotate/opt/pasa-2.4.1/PerlLib/DB_connect.pm line 178, <$fh> line 3305827.
Failed query: <select ci.id, ci.length, ci.cdna_acc, ci.is_fli,  ci.header, a.lend, a.rend, a.mlend, a.mrend, a.orient,  al.aligned_orient, al.spliced_orient, al.validate, al.prog, al.align_acc, a.per_id  from alignment a, cdna_info ci, align_link al  where a.align_id = 237036 and a.align_id = al.align_id  and al.cdna_info_id = ci.id >	values: 
Errors: disk I/O error
Failed query: <select ci.id, ci.length, ci.cdna_acc, ci.is_fli,  ci.header, a.lend, a.rend, a.mlend, a.mrend, a.orient,  al.aligned_orient, al.spliced_orient, al.validate, al.prog, al.align_acc, a.per_id  from alignment a, cdna_info ci, align_link al  where a.align_id = 237036 and a.align_id = al.align_id  and al.cdna_info_id = ci.id >	values: 
Errors: 
 at /envs/funannotate/opt/pasa-2.4.1/PerlLib/DB_connect.pm line 203, <$fh> line 3305827.
	DB_connect::do_sql_2D(DB_connect=HASH(0x56335a004538), "select ci.id, ci.length, ci.cdna_acc, ci.is_fli,  ci.header, "...) called at /envs/funannotate/opt/pasa-2.4.1/PerlLib/Ath1_cdnas.pm line 59
	Ath1_cdnas::create_alignment_obj(DB_connect=HASH(0x56335a004538), 237036, SCALAR(0x56335a5fe778)) called at /envs/funannotate/opt/pasa-2.4.1/scripts/populate_mysql_assembly_sequence_field.dbi line 74

I tried this several times and it stops at different points.
Installed DBD::SQLite Perl module version is 1.6.4
Is there a more stable version?

Thanks,
Chris

**Comment by atiweb** [comment]
Looks like the actual version of DBD::SQLite perl is 1.64 https://metacpan.org/pod/DBD::SQLite
Did you check file permission? It appear to be a file access problem too. Make a test with higer credential to see what happen.

**Comment by ctxchris** [comment]
It's probably an NFS issue. It worked after I copied the database from an NFS share to a local folder. Seems that the perl SQLite module is rather picky.

**Comment by atiweb** [comment]
Yes, I have issues too with NFS, the default parameter sync is slow, have to use async for better performance.
