### ISSUE TITLE
Checkannotations fails if 'input' is None

### ISSUE THREAD

**Issue by Tierhon** [nextgenusfs/funannotate#369]
**Are you using the latest release?**
Not using the absolute newest, but this code is the same.

**Describe the bug**
If 'input' is None in https://github.com/nextgenusfs/funannotate/blob/master/funannotate/library.py#L882, I get a TypeError.  In my case, this is called from: https://github.com/nextgenusfs/funannotate/blob/master/funannotate/update.py#L2039.

**What command did you issue?**
I am trying to run 'funannotate update' on FASTA file + GFF, to get around the issue with the GenBank format. This is the command I run:
```
funannotate update \
--species "fish update_gff" \
--gff fish/predict_results/fish_train.gff3 \
--fasta ../masked_assembly/fish_villosus_sm.fasta \
-o fish_update_gff \
-l fish/training/trimmomatic/trimmed_left.fastq.gz \
-r fish/training/trimmomatic/trimmed_right.fastq.gz \
--left_norm /cluster/work/users/user/annotation/fish/funannotate_train/fish/training/normalize/trimmed_left.fastq.gz.normalized_K25_maxC50_minC5_maxCV10000.fq \
--right_norm /cluster/work/users/user/annotation/fish/funannotate_train/fish/training/normalize/trimmed_right.fastq.gz.normalized_K25_maxC50_minC5_maxCV10000.fq \
--no_trimmomatic \
--no_normalize_reads \
--cpus 20 > update_gff.out 2> update_gff.err
```

I guess I could reuse the PASA from 'funannotate train', but not completely sure about the commands I would use. Therefore I've tried specifying the trimmed and normalized reads in the first case. 

Anyhow, this can be reproduced with this simple example:
```
>python
Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:39:44) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.isfile(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/projects/user/miniconda3/envs/funannotate/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
I wonder if you can just change https://github.com/nextgenusfs/funannotate/blob/master/funannotate/library.py#L883 to:
if input and os.path.isfile(input):

and https://github.com/nextgenusfs/funannotate/blob/master/funannotate/library.py#L889 to:
elif input and os.path.islink(input):

Thank you.

Ole

**Comment by nextgenusfs** [comment]
Thanks for reporting and providing the fix.
