### ISSUE TITLE
Differences in PASA db creation between train and update

### ISSUE THREAD

**Issue by Tierhon** [nextgenusfs/funannotate#370]
**Are you using the latest release?**
Yes, close enough.

**Describe the bug**
In update.py, the database name for PASA is derived from the species name, but it does not refer to the folder where PASA is run. In train.py, the folder is explicitly added. See https://github.com/nextgenusfs/funannotate/blob/b5df18e3eb732c3eab6fa7f15bf4851aee9cb1fd/funannotate/update.py#L534 vs https://github.com/nextgenusfs/funannotate/blob/b5df18e3eb732c3eab6fa7f15bf4851aee9cb1fd/funannotate/train.py#L305. For me, PASA is unable to find the database (possibly because it conflicts with an existing folder/file). While it could work fine, would not the approach used in runPASAtrain be better?

I rewrote the update version to be similar to train, but the job has not started yet for me, so unsure if it is correct.

Thank you.

Ole

**Comment by nextgenusfs** [comment]
Let me look at it.  There is some weirdness here because PASA distinguishes between Sqlite and MySQL by whether or not the "database" in the config file is full path (Sqlite) or just a database name (MySQL). 

So are you using MySQL or SQLite (default)?

**Comment by nextgenusfs** [comment]
This part of the code in `update.py` would be working only if update was run and the 'training' folder was not found, ie you are running update from scratch (which I think is what you are doing?). So I think you are probably correct and that line needs to be explicit for the path (otherwise abspath isn't doing anything as it is just a name).  

This would explain why I never see this error in my local tests.

**Comment by Tierhon** [comment]
That is correct. I am running with fasta and GFF and such specified. Got
too long sequence names in my fasta for NCBI, and it is too late to change
now.

søn. 19. jan. 2020, 17:42 skrev Jon Palmer <notifications@github.com>:

**Comment by nextgenusfs** [comment]
Okay, so to double-check: you change L534 in update to:
`DataBaseName = os.path.abspath(os.path.join(folder, DataBaseName))`

Does this then work for you?

**Comment by Tierhon** [comment]
The job is in queue on our cluster, but I'll let you know the result when
it finishes.

søn. 19. jan. 2020, 18:11 skrev Jon Palmer <notifications@github.com>:

**Comment by nextgenusfs** [comment]
Ok thanks.  Just an FYI, but it might take a long time to run depending on genome size, Sqlite PASA runs only single threaded.  If you can setup MySQL (some systems this isn't an option) then it will run multi-threaded.

**Comment by Tierhon** [comment]
With the changes I made, PASA started and is running at least. Hopefully I did not break anything. 

I changed L533 and L534 to: 

```
 if pasa_db == 'sqlite':
     DataBaseName = os.path.abspath(os.path.join(folder, DataBaseName))
else:
     DataBaseName = os.path.abspath(DataBaseName)
```
I can't use MySQL, but it runs fast enough for me for now.

Thank you.

Ole

**Comment by nextgenusfs** [comment]
I pushed the fix a bit ago and tested locally. Only the first part needs to be changed and importantly for MySQL the dbname cannot be a full path.
