### ISSUE TITLE
change IDs in a GFF3 file

### ISSUE THREAD

**Issue by mictadlo** [nextgenusfs/funannotate#371]
Hi,
Does your pipeline have any scripts to change IDs in a GFF3 file?

Thank you in advance,

Michal

**Comment by hyphaltip** [comment]
do you mean after prediction is done? see the  `--rename `option in `funannotate annotate ` however I find that this wasn't always happening for me so I end up just running a perl one liner on the annotate_results folder eg:
`perl -i.bak -p -e 's/OLDLOCUS_/NEWLOCUS_/g' *.gff3 *.gbk *.tbl *.sqn *.fa `
assuming your OLDLOCUS_ is suitable unique term....

**Comment by nextgenusfs** [comment]
Funannotate fix also has rename option. It’s not difficult to do and can show you how to do in python with funannotate library. This could be added to the util menu as well. But if just changing the base name then @hyphaltip suggestion will work just fine.
