### ISSUE TITLE
MAKER2 input erro

### ISSUE THREAD

**Issue by Dikaryotic** [nextgenusfs/funannotate#373]
Hiya, 

I've been using Funannotate for a little while now and recently decided to have a play with MAKER2 as well and wanted to use the output from that as input for my Funannotate run. Given that there is the --maker_gff input I figured this would be straight forward, however I've run into an issue. MAKER2 was run with the exact same genome, repeat masked and everything. The output gff file wasnt modified in any way. I'm using Funannotate v. 1.7.2 and used MAKER2 v. 2.31.10. The file funannotate-predict.log doesn't show anything meaningful.

This is the code I've used and the subsequent error. The code runs well if I drop the --maker_gff flag and input:

funannotate predict -i RM-LEN2.sorted.fasta -o LEN2_Test -s "Lentinula novae-zealandiae" --optimize_augustus --busco_db basidiomycota  --protein_evidence  Lentinula-edodes-Geneious-proteins.fasta $FUNANNOTATE_DB/uniprot_sprot.fasta --transcript_evidence Trinity-GG.fasta 1-bud-Trinity-GG.fasta 3-body-Trinity-GG.fasta LightInduced-Trinity-GG.fasta 2-button.Trinity-GG.fasta --min_protlen 30  --cpus 4 --maker_gff LEN2.sorted.MAKER2.gff
-------------------------------------------------------
[03:45 PM]: OS: linux2, 4 cores, ~ 23 GB RAM. Python: 2.7.15
[03:45 PM]: Running funannotate v1.7.2
[03:45 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
[03:45 PM]: CodingQuarry will be skipped --> --rna_bam required for training
[03:45 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[03:46 PM]: Genome loaded: 44 scaffolds; 53,023,550 bp; 30.19% repeats masked
[03:46 PM]: Parsing Maker2 GFF for use in EVidence Modeler
Traceback (most recent call last):
  File "/home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/lib/python2.7/site-packages/funannotate/predict.py", line 712, in main
    lib.maker2evm(args.maker_gff, os.path.join(args.out, 'predict_misc'))
  File "/home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/lib/python2.7/site-packages/funannotate/library.py", line 999, in maker2evm
    if 'maker' in cols[1]:
IndexError: list index out of range

Any thoughts? I was able to use the predicted proteins from MAKER2 as input to funannotate, but I'd much rather use the actual gff file. 

Cheers,
Chris

**Comment by nextgenusfs** [comment]
Probably GFF parsing error.  Can you paste like 20 lines of GFF file (enough so I can see some gene models, etc).  I admittedly haven't used this functionality in years -- so probably broke in v1.7.0 with the changes that were pushed then. I wouldn't actually recommend that you use it this way -- all it is going to do is pull out the Maker mediated gene models and run them through EVM.

**Comment by Dikaryotic** [comment]
Ayuh, reckon it's worth bothering at ll with MAKER2 then? It doesnt sound like it. Thanks for the super quick response!

**Comment by Dikaryotic** [comment]
Woops, forgot the gff data: 

head -50 LEN2.sorted.MAKER2.gff 
##gff-version 3
LEN2_25	maker	gene	5193	8030	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39;Name=maker-LEN2_25-augustus-gene-0.39
LEN2_25	maker	mRNA	5193	8030	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1;Parent=maker-LEN2_25-augustus-gene-0.39;Name=maker-LEN2_25-augustus-gene-0.39-mRNA-1;_AED=0.01;_eAED=0.01;_QI=34|1|1|1|1|0.83|6|74|819
LEN2_25	maker	exon	5193	6165	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:exon:38470;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	exon	6222	6395	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:exon:38471;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	exon	6446	6630	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:exon:38472;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	exon	6684	6766	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:exon:38473;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	exon	6819	6968	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:exon:38474;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	exon	7028	8030	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:exon:38475;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	five_prime_UTR	5193	5226	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:five_prime_utr;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	CDS	5227	6165	.	+	0	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:cds;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	CDS	6222	6395	.	+	0	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:cds;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	CDS	6446	6630	.	+	0	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:cds;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	CDS	6684	6766	.	+	1	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:cds;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	CDS	6819	6968	.	+	2	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:cds;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	CDS	7028	7956	.	+	2	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:cds;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	three_prime_UTR	7957	8030	.	+	.	ID=maker-LEN2_25-augustus-gene-0.39-mRNA-1:three_prime_utr;Parent=maker-LEN2_25-augustus-gene-0.39-mRNA-1
LEN2_25	maker	gene	13401	15004	.	+	.	ID=maker-LEN2_25-augustus-gene-0.40;Name=maker-LEN2_25-augustus-gene-0.40
LEN2_25	maker	mRNA	13401	15004	.	+	.	ID=maker-LEN2_25-augustus-gene-0.40-mRNA-1;Parent=maker-LEN2_25-augustus-gene-0.40;Name=maker-LEN2_25-augustus-gene-0.40-mRNA-1;_AED=0.02;_eAED=0.02;_QI=0|1|0.5|1|1|0.5|2|87|484
LEN2_25	maker	exon	13401	14827	.	+	.	ID=maker-LEN2_25-augustus-gene-0.40-mRNA-1:exon:38476;Parent=maker-LEN2_25-augustus-gene-0.40-mRNA-1
LEN2_25	maker	exon	14890	15004	.	+	.	ID=maker-LEN2_25-augustus-gene-0.40-mRNA-1:exon:38477;Parent=maker-LEN2_25-augustus-gene-0.40-mRNA-1
LEN2_25	maker	CDS	13401	14827	.	+	0	ID=maker-LEN2_25-augustus-gene-0.40-mRNA-1:cds;Parent=maker-LEN2_25-augustus-gene-0.40-mRNA-1
LEN2_25	maker	CDS	14890	14917	.	+	1	ID=maker-LEN2_25-augustus-gene-0.40-mRNA-1:cds;Parent=maker-LEN2_25-augustus-gene-0.40-mRNA-1
LEN2_25	maker	three_prime_UTR	14918	15004	.	+	.	ID=maker-LEN2_25-augustus-gene-0.40-mRNA-1:three_prime_utr;Parent=maker-LEN2_25-augustus-gene-0.40-mRNA-1
LEN2_25	maker	gene	28874	29552	.	+	.	ID=maker-LEN2_25-augustus-gene-0.41;Name=maker-LEN2_25-augustus-gene-0.41
LEN2_25	maker	mRNA	28874	29552	.	+	.	ID=maker-LEN2_25-augustus-gene-0.41-mRNA-1;Parent=maker-LEN2_25-augustus-gene-0.41;Name=maker-LEN2_25-augustus-gene-0.41-mRNA-1;_AED=0.09;_eAED=0.09;_QI=0|1|0.5|1|0|0|4|0|137

**Comment by nextgenusfs** [comment]
Well I guess the scripts should still support it.  Basically I wrote it as a way to "save" a Maker run so it could be submitted to NCBI -- otherwise the number of manual fixes required was too many.
