### ISSUE TITLE
Genemark not being run

### ISSUE THREAD

**Issue by Dikaryotic** [nextgenusfs/funannotate#374]
Hi, 

I've another issue to throw your way, sorry about this! I recently did a Funannotate run only to find that it appears genemark wasn't run for some reason. When I run Funannotate check I get the following: 

Checking dependencies for 1.7.2
-------------------------------------------------------
To print all dependencies and versions: funannotate check --show-versions

You are running Python v 2.7.15. Now checking python packages...
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
All 27 Perl modules installed

Checking Environmental Variables...
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
	ERROR: /home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/opt/pasa-2.3.3/Launch_PASA_pipeline.pl not installed
	ERROR: signalp not installed

Recently my genemark license expired so I re-installed it, prior to doing so Funannotate flagged that it wasn't working, now however it's saying it's installed. I'm running genemark-es v. 4.48_3.60_lic. I've also used genemark separately as part of a MAKER2 run I did. In the logfiles folder there are logs for augustus, busco, evidence modeler and the predict run itself. I've attached the predict logfile, which initially shows genemark in the list of ab initio predictors, only to then just not run it downstream, with no errors. In the /predict_misc/ folder there are also no files associated with genemark. Pretty weird right? 

Any thoughts? 

Cheers,
Chris 

[funannotate-predict.log](https://github.com/nextgenusfs/funannotate/files/4119319/funannotate-predict.log)

**Comment by nextgenusfs** [comment]
Is it in your path in that environment, i.e. what is output of `gmes_petap.pl`?

**Comment by Dikaryotic** [comment]
Yep, that was one of the first things I checked. It's in the path and running as per normal.

**Comment by hyphaltip** [comment]
Can you run a test gmes run on a test file first in the same way your job is being run. I had a user with similar problem but we debugged after ~/.gm_key was found to be fixed.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by Dikaryotic** [comment]
Hi Jason, 

I ran genemark separately on the same genome file just last week for a MAKER2 run and it worked fine. Genemark is definitely functional and running. Is that sufficient to answer your request? I don't mind re-running it if that'd help, I'm just unsure what if any further info it could provide. 


Cheers,
Chris

**Comment by nextgenusfs** [comment]
Do you have $GENEMARK_PATH set?

**Comment by Dikaryotic** [comment]
Yep, 100%, it's part of my standard setup for running Funannotate. Also, if it wasn't Funannotate would flag that it's unable to find it. I've also made sure that the genemark path is pointing to the newly installed genemark so it's not that either. Funannotate seems to recognize it's installed, but just doesnt run it.

**Comment by nextgenusfs** [comment]
Okay, well another user just reported a perhaps similar issue #372.  Strangely I don't see that same behavior locally.  Not sure what would have changed that this all of the sudden doesn't work.  See if adding a slash at the end of your $GENEMARK_PATH fixes the issue or not.

**Comment by nextgenusfs** [comment]
Also, if you have `gmes_petap.pl` in your path, then you don't need `$GENEMARK_PATH` set at all. So another test would be to run:
```
unset GENEMARK_PATH
```
And then try to run it again and see if it picks up GeneMark properly.

**Comment by Dikaryotic** [comment]
I looked at #372 like suggested and added a slash at the end of $GENEMARK_PATH. I've just set Funannotate running and it seems to have fixed the problem. Thanks for the help dudes!

**Comment by nextgenusfs** [comment]
Okay thanks for update. Will see if I can get the underlying issue fixed in next release.
