### ISSUE TITLE
Phobius error on funannotate annotate

### ISSUE THREAD

**Issue by atiweb** [nextgenusfs/funannotate#376]
**Are you using the latest release?**
Using version 1.7.3

**Describe the bug**
 Predicting secreted and transmembrane proteins using Phobius
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/funannotate/aux_scripts/phobius-multiproc.py", line 102, in <module>
    result = line[1].split(' ')
IndexError: list index out of range

**What command did you issue?**
funannotate annotate --input /mnt/sdb/bichos_marcus/Amauroascus_niger/UAMH_3544/fun_out --out /mnt/sdb/bichos_marcus/Amauroascus_niger/UAMH_3544/annotation_out --species Amauroascus_niger_UAMH_3544 --strain UAMH_3544 --force --antismash /mnt/sdb/bichos_marcus/Amauroascus_niger/UAMH_3544/antismash_OUT/Amauroascus_niger_UAMH_3544_UAMH_3544.gbk --iprscan /mnt/sdb/bichos_marcus/Amauroascus_niger/UAMH_3544/fun_out/annotate_misc/iprscan.xml --cpus 15

**Logfiles**
[phobius_generated_files.zip](https://github.com/nextgenusfs/funannotate/files/4188770/phobius_generated_files.zip)

**OS/Install Information**
-------------------------------------------------------
Checking dependencies for 1.7.3
-------------------------------------------------------
You are running Python v 2.7.17. Now checking python packages...
biopython: 1.73
goatools: 0.9.5
matplotlib: 2.2.4
natsort: 6.0.0
numpy: 1.13.3
pandas: 0.24.2
psutil: 5.6.7
requests: 2.22.0
scikit-learn: 0.20.3
scipy: 1.2.2
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026001. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.42
Clone: 0.39
DBD::SQLite: 1.62
DBD::mysql: 4.050
DBI: 1.643
DB_File: 1.852
Data::Dumper: 2.167
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.49
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.31
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 2.62
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.28
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/mnt/sdb/funannotate/DB_funannotate
$PASAHOME=/mnt/sdb/funannotate/PASApipeline
$TRINITYHOME=/mnt/sdb/funannotate/trinityrnaseq-v2.9.0
$EVM_HOME=/mnt/sdb/funannotate/EVidenceModeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/mnt/sdb/funannotate/Augustus/config
$GENEMARK_PATH=/mnt/sdb/funannotate/gm_et_linux_64/gmes_petap
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.9.1
augustus: 3.3.2
bamtools: bamtools 2.5.1
bedtools: bedtools v2.26.0
blat: BLAT v36x2
diamond: 0.9.24
emapper.py: 2.0.1
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.38
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 11.0.6
kallisto: 0.46.0
mafft: v7.453 (2019/Nov/8)
makeblastdb: makeblastdb 2.9.0+
minimap2: 2.17-r943-dirty
proteinortho: 6.0.10
pslCDnaFilter: no way to determine
salmon: salmon 0.14.0
samtools: samtools 1.9-66-gc15e884
signalp: 4.1
snap: 2006-07-28
stringtie: 1.3.6
tRNAscan-SE: 1.3.1 (January 2012)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.9.0+
trimal: trimAl v1.4.rev22 build[2015-05-21]
trimmomatic: 0.39
All 36 external dependencies are installed

The problem tracked is that the file UAMH3544_007299-T1.phobius have no data, hence the error when parse. Is evidently a Phobius bug, or something like that, the solution found, or what I have done to continue working is the following:
On phobius-multiproc.py, line 102, added:
try:
                result = line[1].split(' ')
                result = [x for x in result if x]
                if result[1] == 'prediction':
                    continue
                if int(result[1]) > 0:
                    TMdomain += 1
                if result[2] == 'Y':
                    SigPep += 1
                output.write("%s\t%s\t%s\t%s\n" % (
                    result[0], result[1], result[2], result[3].replace('\n', '')))
            except IndexError:
                pass

May not be the best solution, but it works to continue the process.
Best wishes.

**Comment by hyphaltip** [comment]
BTW I did an annotation of Amauroascus_niger a few years ago am happy to also share if you want!

**Comment by atiweb** [comment]
> BTW I did an annotation of Amauroascus_niger a few years ago am happy to also share if you want! Thought it was an earlier version of funannotate so you might have better results with this version anyways.

Thank you Jason, it may be useful indeed, Im annotating using RNA from NCBI, This is a study for Marcus Texeira, He will contact you.
Greetings

**Comment by nextgenusfs** [comment]
Thanks @atiweb -- I changed/added this in the python3 codebase, which hopefully I can released shortly (v1.8.0).

**Comment by atiweb** [comment]
Thank you @nextgenusfs , glad to help.
Greetings
