### ISSUE TITLE
Question: How to include SignalP online results? 

### ISSUE THREAD

**Issue by Dikaryotic** [nextgenusfs/funannotate#378]
Hiya, 

I was wondering if you had any thoughts/advice on using SignalP results from the webserver as input to the annotation step? I've gotten Phobius to run easily enough, but I'd like to use SignalP, however my institution isn't recognized on their whitelist so downloading it has proven somewhat problematic. I've contacted them directly to no avail, so I figured I'd try just running on the webserver and using the results from that as input, but I don't see any documentation or options to do that. Any thoughts? 

Cheers,
Chris

**Comment by nextgenusfs** [comment]
Currently not supported, but if you could give us a sample output of the webserver then should be something we could incorporate as a `--signalp` input to `funannotate annotate`.

**Comment by Dikaryotic** [comment]
Awesome! It outputs a number of result files, a .gff3 annotation file, but also a file that is pretty similar to the phobius output. An example, using protein output from a recent Funannotate 1.7.2 run:

# SignalP-5.0	Organism: Eukarya	Timestamp: 20200213034924
# ID	Prediction	SP(Sec/SPI)	OTHER	CS Position
FUN_000001-T1	OTHER	0.004283	0.995717	
FUN_000002-T1	OTHER	0.000619	0.999381	
FUN_000003-T1	OTHER	0.001544	0.998456	
FUN_000004-T1	OTHER	0.001247	0.998753	
FUN_000005-T1	OTHER	0.000598	0.999402	
FUN_000006-T1	OTHER	0.000398	0.999602	
FUN_000007-T1	OTHER	0.000546	0.999454	
FUN_000008-T1	OTHER	0.063273	0.936727	
FUN_000009-T1	OTHER	0.000722	0.999278	
FUN_000010-T1	SP(Sec/SPI)	0.996765	0.003235	CS pos: 20-21. AVA-AP. Pr: 0.9122
FUN_000011-T1	OTHER	0.000715	0.999285	
FUN_000012-T1	OTHER	0.000328	0.999672	
FUN_000013-T1	OTHER	0.000897	0.999103	
FUN_000014-T1	OTHER	0.021837	0.978163	
FUN_000015-T1	OTHER	0.000431	0.999569	
FUN_000016-T1	OTHER	0.000416	0.999584	
FUN_000017-T1	OTHER	0.001581	0.998419	
FUN_000018-T1	OTHER	0.001221	0.998779	
FUN_000019-T1	OTHER	0.000650	0.999350	
FUN_000020-T1	OTHER	0.003005	0.996995	
FUN_000021-T1	OTHER	0.000489	0.999511	
FUN_000022-T1	OTHER	0.002877	0.997123	
FUN_000023-T1	OTHER	0.000623	0.999377	
FUN_000024-T1	OTHER	0.026239	0.973761	
FUN_000025-T1	OTHER	0.004099	0.995901	
FUN_000026-T1	OTHER	0.000581	0.999419	
FUN_000027-T1	OTHER	0.009879	0.990121	
FUN_000028-T1	OTHER	0.010835	0.989165	
FUN_000029-T1	OTHER	0.000157	0.999843	
FUN_000030-T1	OTHER	0.004390	0.995610	
FUN_000031-T1	OTHER	0.000565	0.999435	
FUN_000032-T1	OTHER	0.001144	0.998856	
FUN_000033-T1	OTHER	0.006611	0.993389	
FUN_000034-T1	OTHER	0.001135	0.998865	
FUN_000035-T1	OTHER	0.000785	0.999215	
FUN_000036-T1	OTHER	0.000832	0.999168	
FUN_000037-T1	OTHER	0.001365	0.998635	
FUN_000038-T1	OTHER	0.002031	0.997969	
FUN_000039-T1	OTHER	0.000644	0.999356	
FUN_000040-T1	OTHER	0.000992	0.999008	
FUN_000041-T1	OTHER	0.001246	0.998754	
FUN_000042-T1	OTHER	0.000234	0.999766	
FUN_000043-T1	OTHER	0.000585	0.999415	
FUN_000044-T1	OTHER	0.002752	0.997248	
FUN_000045-T1	OTHER	0.001329	0.998671	
FUN_000046-T1	OTHER	0.000616	0.999384	
FUN_000047-T1	OTHER	0.002682	0.997318	
FUN_000048-T1	OTHER	0.000997	0.999003	
FUN_000049-T1	OTHER	0.002046	0.997954	
FUN_000050-T1	OTHER	0.000715	0.999285	
FUN_000051-T1	OTHER	0.000825	0.999175	
FUN_000053-T1	OTHER	0.004588	0.995412	
FUN_000054-T1	OTHER	0.001108	0.998892	
FUN_000055-T1	OTHER	0.000193	0.999807	
FUN_000056-T1	OTHER	0.000329	0.999671	
FUN_000057-T1	OTHER	0.000935	0.999065	
FUN_000058-T1	OTHER	0.000934	0.999066	
FUN_000059-T1	OTHER	0.003559	0.996441	
FUN_000060-T1	OTHER	0.000767	0.999233	
FUN_000061-T1	OTHER	0.000493	0.999507	
FUN_000062-T1	OTHER	0.001284	0.998716	
FUN_000063-T1	OTHER	0.001990	0.998010	
FUN_000064-T1	OTHER	0.025184	0.974816	
FUN_000065-T1	OTHER	0.009673	0.990327	
FUN_000066-T1	OTHER	0.008833	0.991167	
FUN_000067-T1	OTHER	0.001743	0.998257	
FUN_000068-T1	OTHER	0.001149	0.998851	
FUN_000069-T1	OTHER	0.001122	0.998878	
FUN_000070-T1	OTHER	0.021437	0.978563	
FUN_000071-T1	OTHER	0.000639	0.999361	
FUN_000072-T1	OTHER	0.000304	0.999696	
FUN_000073-T1	OTHER	0.000936	0.999064	
FUN_000074-T1	OTHER	0.000671	0.999329	
FUN_000075-T1	OTHER	0.002855	0.997145	
FUN_000076-T1	OTHER	0.002752	0.997248	
FUN_000077-T1	OTHER	0.000663	0.999337	
FUN_000078-T1	OTHER	0.002195	0.997805	
FUN_000079-T1	OTHER	0.001981	0.998019	
FUN_000080-T1	OTHER	0.002695	0.997305	
FUN_000081-T1	OTHER	0.002005	0.997995	
FUN_000082-T1	OTHER	0.002044	0.997956	
FUN_000083-T1	OTHER	0.001102	0.998898	
FUN_000084-T1	OTHER	0.016130	0.983870	
FUN_000085-T1	OTHER	0.000262	0.999738	
FUN_000086-T1	OTHER	0.000570	0.999430	
FUN_000087-T1	OTHER	0.001263	0.998737	
FUN_000088-T1	OTHER	0.002014	0.997986	
FUN_000089-T1	OTHER	0.001110	0.998890	
FUN_000090-T1	OTHER	0.001048	0.998952	
FUN_000091-T1	OTHER	0.000727	0.999273	
FUN_000092-T1	OTHER	0.056879	0.943121	
FUN_000094-T1	OTHER	0.000711	0.999289	
FUN_000095-T1	OTHER	0.001543	0.998457	
FUN_000096-T1	OTHER	0.002550	0.997450	
FUN_000097-T1	OTHER	0.003752	0.996248	
FUN_000098-T1	OTHER	0.000758	0.999242	
FUN_000099-T1	OTHER	0.009929	0.990071	
FUN_000100-T1	OTHER	0.002351	0.997649	
FUN_000101-T1	OTHER	0.001169	0.998831	
FUN_000102-T1	OTHER	0.000703	0.999297	
FUN_000103-T1	OTHER	0.000516	0.999484	
FUN_000104-T1	OTHER	0.000883	0.999117	
FUN_000105-T1	SP(Sec/SPI)	0.862881	0.137119	CS pos: 18-19. ILG-QT. Pr: 0.6136
FUN_000106-T1	OTHER	0.000588	0.999412	
FUN_000107-T1	OTHER	0.000315	0.999685	
FUN_000108-T1	OTHER	0.011685	0.988315	
FUN_000109-T1	OTHER	0.001334	0.998666	
FUN_000110-T1	OTHER	0.001512	0.998488	
FUN_000111-T1	OTHER	0.001459	0.998541	
FUN_000113-T1	SP(Sec/SPI)	0.689529	0.310471	CS pos: 27-28. ATA-AT. Pr: 0.3710
FUN_000114-T1	OTHER	0.018650	0.981350	
FUN_000115-T1	OTHER	0.000815	0.999185	
FUN_000116-T1	OTHER	0.002015	0.997985	
FUN_000117-T1	OTHER	0.001082	0.998918	
FUN_000118-T1	OTHER	0.000730	0.999270	
FUN_000119-T1	OTHER	0.002113	0.997887	
FUN_000120-T1	OTHER	0.001032	0.998968	
FUN_000121-T1	OTHER	0.000406	0.999594	
FUN_000122-T1	OTHER	0.001324	0.998676	
FUN_000123-T1	OTHER	0.001816	0.998184	
FUN_000124-T1	OTHER	0.003017	0.996983	
FUN_000125-T1	OTHER	0.160130	0.839870	
FUN_000126-T1	OTHER	0.000680	0.999320	
FUN_000127-T1	OTHER	0.009422	0.990578	
FUN_000128-T1	OTHER	0.011263	0.988737	
FUN_000129-T1	OTHER	0.000584	0.999416	
FUN_000130-T1	OTHER	0.000804	0.999196	
FUN_000131-T1	OTHER	0.005571	0.994429	
FUN_000132-T1	OTHER	0.002481	0.997519	
FUN_000133-T1	SP(Sec/SPI)	0.775277	0.224723	CS pos: 18-19. VFA-IP. Pr: 0.4743
FUN_000134-T1	SP(Sec/SPI)	0.657965	0.342035	CS pos: 24-25. LTA-VS. Pr: 0.1663
FUN_000135-T1	OTHER	0.003699	0.996301	
FUN_000136-T1	OTHER	0.048867	0.951133	
FUN_000137-T1	OTHER	0.000952	0.999048	
FUN_000138-T1	OTHER	0.004929	0.995071	
FUN_000139-T1	OTHER	0.000495	0.999505	
FUN_000140-T1	OTHER	0.002122	0.997878	
FUN_000141-T1	OTHER	0.003447	0.996553	
FUN_000142-T1	OTHER	0.000808	0.999192	
FUN_000143-T1	OTHER	0.000808	0.999192	
FUN_000144-T1	OTHER	0.005328	0.994672	
FUN_000145-T1	OTHER	0.000456	0.999544	
FUN_000146-T1	SP(Sec/SPI)	0.526512	0.473488	CS pos: 30-31. ASS-TS. Pr: 0.2988
FUN_000147-T1	OTHER	0.000787	0.999213	
FUN_000148-T1	OTHER	0.001226	0.998774	
FUN_000149-T1	OTHER	0.000924	0.999076	
FUN_000150-T1	OTHER	0.002829	0.997171	
FUN_000151-T1	OTHER	0.006443	0.993557	
FUN_000152-T1	OTHER	0.058059	0.941941	
FUN_000153-T1	OTHER	0.001225	0.998775	
FUN_000154-T1	OTHER	0.000607	0.999393	
FUN_000155-T1	OTHER	0.024499	0.975501	
FUN_000156-T1	OTHER	0.008956	0.991044	
FUN_000157-T1	OTHER	0.000375	0.999625	
FUN_000158-T1	SP(Sec/SPI)	0.770643	0.229357	CS pos: 26-27. ISA-LP. Pr: 0.4683
FUN_000159-T1	OTHER	0.001019	0.998981	
FUN_000160-T1	OTHER	0.001019	0.998981	
FUN_000161-T1	OTHER	0.002561	0.997439	
FUN_000162-T1	OTHER	0.001638	0.998362	
FUN_000163-T1	SP(Sec/SPI)	0.773965	0.226035	CS pos: 34-35. MLA-RP. Pr: 0.4070
FUN_000164-T1	OTHER	0.002306	0.997694	
FUN_000165-T1	OTHER	0.000475	0.999525	
FUN_000166-T1	OTHER	0.002756	0.997244	
FUN_000167-T1	SP(Sec/SPI)	0.927895	0.072105	CS pos: 22-23. VNA-IP. Pr: 0.8462
FUN_000168-T1	OTHER	0.027619	0.972381	
FUN_000169-T1	OTHER	0.001245	0.998755	
FUN_000170-T1	OTHER	0.001328	0.998672	
FUN_000171-T1	OTHER	0.001177	0.998823	
FUN_000172-T1	OTHER	0.000403	0.999597	
FUN_000173-T1	OTHER	0.000602	0.999398	
FUN_000174-T1	OTHER	0.000293	0.999707	
FUN_000175-T1	OTHER	0.000300	0.999700	
FUN_000176-T1	OTHER	0.000394	0.999606	
FUN_000177-T1	OTHER	0.431399	0.568601	
FUN_000178-T1	OTHER	0.000950	0.999050	
FUN_000179-T1	OTHER	0.000662	0.999338	
FUN_000180-T1	OTHER	0.002372	0.997628	
FUN_000181-T1	OTHER	0.002327	0.997673	
FUN_000182-T1	OTHER	0.001222	0.998778	
FUN_000183-T1	OTHER	0.000854	0.999146	
FUN_000184-T1	OTHER	0.001543	0.998457	
FUN_000185-T1	OTHER	0.001311	0.998689	
FUN_000186-T1	OTHER	0.007152	0.992848	
FUN_000187-T1	OTHER	0.003396	0.996604	
FUN_000188-T1	OTHER	0.001932	0.998068	
FUN_000189-T1	OTHER	0.003556	0.996444	
FUN_000190-T1	OTHER	0.000491	0.999509	
FUN_000191-T1	OTHER	0.001932	0.998068	
FUN_000192-T1	OTHER	0.003556	0.996444	
FUN_000193-T1	OTHER	0.000491	0.999509	
FUN_000194-T1	OTHER	0.002737	0.997263	
FUN_000195-T1	OTHER	0.000877	0.999123	
FUN_000196-T1	OTHER	0.003283	0.996717	
FUN_000197-T1	OTHER	0.007490	0.992510	
FUN_000198-T1	OTHER	0.001251	0.998749	
FUN_000199-T1	OTHER	0.000382	0.999618	
FUN_000200-T1	OTHER	0.000681	0.999319	
FUN_000201-T1	OTHER	0.000275	0.999725	
FUN_000202-T1	OTHER	0.001452	0.998548	
FUN_000203-T1	OTHER	0.000349	0.999651	
FUN_000204-T1	OTHER	0.000757	0.999243	
FUN_000205-T1	OTHER	0.001009	0.998991	
FUN_000206-T1	OTHER	0.017988	0.982012	
FUN_000207-T1	OTHER	0.000737	0.999263	
FUN_000208-T1	OTHER	0.000516	0.999484	
FUN_000209-T1	SP(Sec/SPI)	0.984287	0.015713	CS pos: 27-28. VEG-ET. Pr: 0.9748
FUN_000210-T1	OTHER	0.002221	0.997779	
FUN_000211-T1	OTHER	0.001852	0.998148	
FUN_000212-T1	OTHER	0.014585	0.985415	
FUN_000213-T1	OTHER	0.001890	0.998110	
FUN_000214-T1	OTHER	0.001994	0.998006	
FUN_000215-T1	OTHER	0.001061	0.998939	
FUN_000216-T1	OTHER	0.000088	0.999912	
FUN_000217-T1	SP(Sec/SPI)	0.994006	0.005994	CS pos: 25-26. TQG-GD. Pr: 0.9622
FUN_000218-T1	OTHER	0.001579	0.998421	
FUN_000220-T1	OTHER	0.000788	0.999212	
FUN_000222-T1	OTHER	0.000478	0.999522	
FUN_000224-T1	OTHER	0.001558	0.998442	
FUN_000225-T1	OTHER	0.000450	0.999550	
FUN_000226-T1	OTHER	0.001089	0.998911	
FUN_000227-T1	OTHER	0.015128	0.984872	
FUN_000228-T1	OTHER	0.002681	0.997319	
FUN_000229-T1	OTHER	0.000599	0.999401	
FUN_000230-T1	SP(Sec/SPI)	0.734604	0.265396	CS pos: 17-18. ITA-MV. Pr: 0.6472
FUN_000231-T1	OTHER	0.000386	0.999614	
FUN_000232-T1	OTHER	0.000454	0.999546	
FUN_000233-T1	OTHER	0.009642	0.990358	
FUN_000234-T1	OTHER	0.009642	0.990358	
FUN_000235-T1	OTHER	0.000298	0.999702	
FUN_000236-T1	OTHER	0.048750	0.951250	
FUN_000237-T1	SP(Sec/SPI)	0.949916	0.050084	CS pos: 23-24. TFS-AA. Pr: 0.5096
FUN_000238-T1	OTHER	0.001146	0.998854	
FUN_000239-T1	OTHER	0.027091	0.972909	
FUN_000240-T1	SP(Sec/SPI)	0.989670	0.010330	CS pos: 17-18. AFA-QS. Pr: 0.7300
FUN_000241-T1	OTHER	0.002030	0.997970	
FUN_000242-T1	OTHER	0.001936	0.998064	
FUN_000243-T1	SP(Sec/SPI)	0.996172	0.003828	CS pos: 18-19. ASA-DR. Pr: 0.9427
FUN_000244-T1	OTHER	0.002867	0.997133	
FUN_000245-T1	OTHER	0.000567	0.999433	
FUN_000246-T1	OTHER	0.011197	0.988803	
FUN_000247-T1	OTHER	0.030149	0.969851	
FUN_000248-T1	OTHER	0.000286	0.999714	
FUN_000249-T1	OTHER	0.001203	0.998797	
FUN_000250-T1	SP(Sec/SPI)	0.977028	0.022972	CS pos: 25-26. VCA-LP. Pr: 0.7
