### ISSUE TITLE
Funannotate remote fails with OSError in singularity container

### ISSUE THREAD

**Issue by reslp** [nextgenusfs/funannotate#379]
Hi Jon,

I try to solve a weird problem which occurs when I run funannotate remote inside my funannotate singularity container. The command runs fine, output is correctly generated but the command fails at the step where the logfile is moved into the logdir. This is the output I get:

```
-------------------------------------------------------
[10:33 AM]: OS: linux2, 32 cores, ~ 197 GB RAM. Python: 2.7.17
[10:33 AM]: Running 1.7.2
[10:33 AM]: Output directory testgteu already exists
[10:33 AM]: Checking GenBank file for annotation
[10:37 AM]: Predicting secreted and transmembrane proteins using Phobius
[10:37 AM]: Remote searches complete
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 657, in <module>
    main()
  File "/usr/local/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/remote.py", line 300, in main
    os.rename(log_name, os.path.join(outputdir, 'logfiles', log_name))
OSError: [Errno 16] Device or resource busy
```

The strange thing is that the logfile is created correctly but it can not be moved. I cannot figure out why exactly this happens. Running the same command in the same container in Docker works just fine. Also other funannotate commands don't produce this error.
From what I know, the error can occur when trying to move an open file. But I am not sure if this is the case here.
Do you have an idea what could be the problem? As a quick workaround, I am thinking of commenting out line 300 in remote.py when the container is built, but I don't want to tinker with the internals of funannotate too much, because the behavior of funannotate should be the same regardless of how it is used.

If you have any idea how to fix this I would be very happy to hear it.

Thank you for your time!

all the best,

Philipp

**Comment by nextgenusfs** [comment]
I have occasionally seen a similar type of error which seems to happen with some systems and their file system mounts - NFS mounts is on the tip of my tongue but can’t remember any specific config as I’ve only seen it in other peoples logfiles. Also not familiar with singularity so I don’t know if there are options for different ways to mount the file system. 

We could put a try/except on that one in the future as a band aid but doesn’t address the underlying problem which doesn’t seem obvious.

**Comment by reslp** [comment]
Thank you for your quick response. I have Singularity running on a CentOS system on a big cluster. Maybe this is is part of the problem. I also came across the file system mounts but didn't look at it in detail. 
When it comes to mounting the FS in Singularity, I think I have already exhausted pretty much every possibility. I have now commented out the line in the script and will try if it works like this.

**Comment by nextgenusfs** [comment]
Okay. Wonder if a copy of that file and then delete would work. Maybe different method, ie shutil.copyfile?

**Comment by reslp** [comment]
Good idea. I will give that a try as well.

**Comment by reslp** [comment]
Hi again, I managed to make it work. Commenting out the two lines works. It also works to copy and remove the file instead of moving it directly. I prefer the second solution. If you like to include this just let me know and I can send you a pull request.

**Comment by nextgenusfs** [comment]
Okay, I just pushed a release (1.7.3) with that os.rename changed to a copy and delete. Let me know if that fixes it. Likely to follow up shortly with a py3 version (1.8.0) -- which is mostly working at the moment, but want to do some more testing.

**Comment by reslp** [comment]
Great, thank you! I will try it. I also found that funannotate annotate has the same problem. I already fixed it in the Dockerfile but didn't have time to test it yet. Building the image, then converting to Singularity takes a while...

**Comment by nextgenusfs** [comment]
Okay, I'll just change all the os.rename() calls to a shutil.copyfile() followed by os.remove().  

Also about your docker file - the easiest solution I would think now would be to just start with a miniconda3 ubuntu image and then just call `conda install funannnotate`?  Or did that not work for some reason?

**Comment by reslp** [comment]
Great thanks! Yes, this was my initial idea, I set up most of my other Docker containers like that because it makes version control easier to handle. However in this case it did not work for some reason, now off the top of my head I don't remember why, I think there was some conflict with one of the dependency packages.
I am looking forward to the python3 version already :)

**Comment by nextgenusfs** [comment]
Its on the python3 branch at the moment -- it needs some more testing I think (picking up today after a few weeks), so if you have some time and want to test that would be helpful.

**Comment by reslp** [comment]
Sure I will give it a try. I can test it mostly in a container setting, on the cluster I currently work on it is the only way I can use it.

**Comment by reslp** [comment]
I just gave the conda installation in a miniconda container another try. Now I remember what the problem was. Everything installs fine, but in `funannotate check` it gives an error about ete3:
```
Checking external dependencies...
Traceback (most recent call last):
  File "/opt/conda/envs/funannotate/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/opt/conda/envs/funannotate/lib/python2.7/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/opt/conda/envs/funannotate/lib/python2.7/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name TextFace
	ERROR: emapper.py not installed
	ERROR: ete3 not installed
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed
```

I remember googeling this but could not find a good solution, but I realized it is a version issue. Installing another version with conda however does break all kinds of other dependencies so I installed version 3.0.0b35 with pip to make it work.

**Comment by nextgenusfs** [comment]
Huh, okay.  This is related to this PyQt4 vs PyQt5 issues of some kind that has been around for awhile with ete3.  Surprised I don't see this on the centOS or macOS that I've used the conda package on.  Hopefully this goes away with py3....  so if you call the conda install like this, it breaks or doesn't find a solution?
```
conda install -n funannotate python=2.7 ete3=3.0.0b35 funannotate
```

**Comment by reslp** [comment]
Yes, I also narrowed it down to PyQt being the cause of the trouble. Your suggested command was one of the things I tried, unfortunately without success. Conda finds conflicts which it is unable to resolve. I just ran it again to confirm. This is what i get:
```
(funannotate) root@10ca1c018169:/# conda install python=2.7 ete3=3.0.0b35 funannotate
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package glib conflicts for:
funannotate -> ete3 -> pyqt[version='>=4.11.*'] -> qt=5.9 -> gtk2 -> gdk-pixbuf -> glib[version='>=2.48.0|>=2.51']
funannotate -> r-base[version='>=3.4.1'] -> cairo[version='>=1.16.0,<1.17.0a0'] -> glib[version='2.55.*|>=2.58.2,<2.59.0a0']
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> pango -> harfbuzz=1.3 -> glib=2.51
funannotate -> r-base[version='>=3.4.1'] -> glib[version='>=2.53.6,<3.0a0|>=2.55.0,<2.56.0a0|>=2.56.1,<3.0a0|>=2.56.2,<2.57.0a0|>=2.56.2,<3.0a0|>=2.58.2,<3.0a0|>=2.58.3,<3.0a0']
Package iqtree conflicts for:
funannotate -> iqtree
Package freetype conflicts for:
funannotate -> matplotlib -> freetype[version='>=2.8,<2.9.0a0|>=2.9.1,<3.0a0']
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> pango -> freetype=2.7
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> freetype[version='2.7|2.7.*']
funannotate -> goatools -> graphviz -> fontconfig[version='>=2.13.0,<3.0a0'] -> freetype[version='2.8.*|2.8.1.*|>=2.9,<3.0a0']
funannotate -> goatools -> graphviz -> freetype[version='2.8.1|>=2.8.1,<2.9.0a0']
Package qt conflicts for:
ete3=3.0.0b35 -> pyqt=4.11 -> qt[version='4.8.*|>=4.8.6,<5.0']
funannotate -> ete3 -> pyqt[version='>=4.11.*'] -> qt[version='5.6.*|5.9.*|>=5.12.5,<5.13.0a0|>=5.6.2,<5.7.0a0|>=5.9.4,<5.10.0a0|>=5.9.6,<5.10.0a0|>=5.9.7,<5.10.0a0']
Package cairo conflicts for:
funannotate -> r-base[version='>=3.4.1'] -> cairo[version='>=1.14.12,<1.15.0a0|>=1.14.12,<2.0a0|>=1.16.0,<1.17.0a0']
funannotate -> goatools -> graphviz -> cairo=1.14
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> pango -> harfbuzz=1.3 -> cairo=1.14
funannotate -> goatools -> graphviz -> harfbuzz[version='>=1.7.6,<2.0a0'] -> cairo[version='>=1.14.10,<2.0a0']
Package ete3 conflicts for:
funannotate -> ete3
ete3=3.0.0b35
Package harfbuzz conflicts for:
funannotate -> r-base[version='>=3.4.1'] -> pango[version='>=1.42.4,<1.43.0a0'] -> harfbuzz[version='1.7.*|>=1.5.0,<2.0a0|>=1.7.4,<2.0a0|>=1.7.6,<1.8.0a0|>=1.7.6,<2.0a0|>=1.8.4,<2.0a0|>=1.8.6,<2.0a0|>=1.9.0,<2.0a0|>=2.3.0,<3.0a0|>=2.4.0,<3.0a0']
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> pango -> harfbuzz[version='1.3.*|1.4.*']
Package fontconfig conflicts for:
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> fontconfig=2.12
funannotate -> r-base[version='>=3.4.1'] -> cairo[version='>=1.16.0,<1.17.0a0'] -> fontconfig[version='2.12.*|>=2.12.4,<3.0a0|>=2.12.6,<3.0a0|>=2.13.0,<3.0a0|>=2.13.1,<3.0a0']
Package pyqt conflicts for:
ete3=3.0.0b35 -> pyqt[version='4.*|4.11.*']
funannotate -> ete3 -> pyqt[version='5.*|5.6.*|5.9.*|>=4.11.*|>=5.12.3,<5.13.0a0|>=5.6,<6.0a0|>=5.6.0,<5.7.0a0|>=5.9.2,<5.10.0a0']
Package pango conflicts for:
funannotate -> goatools -> graphviz -> pango[version='>=1.41.0,<2.0a0']
funannotate -> r-base[version='>=3.4.1'] -> pango[version='1.*|1.40.*|>=1.40.14,<1.41.0a0|>=1.42.1,<2.0a0|>=1.42.4,<1.43.0a0|>=1.42.4,<2.0a0']
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> pango
```
I tried many other things as well eg. installind pyqt4 with pip etc. Also without success. 
I generally like conda, but it has also caused me headaches from time to time, environments and packages are sometimes not interchangable between OSes.

**Comment by nextgenusfs** [comment]
Great thanks for the info.  There are several dependencies I'd like to replace, maybe time to replace ete3, it actually isn't used for very much in the pipeline.  Maybe I can just pull out the functions it's using instead of installing the whole thing.

**Comment by euduca** [comment]
Hi, 
I have got the same error:

```
Checking external dependencies...
Traceback (most recent call last):
  File "/home_nfs/duca/local/conda/4.7.12.1/envs/funannotate/bin/ete3", line 8, in <module>
    sys.exit(main())
  File "/home_nfs/duca/local/conda/4.7.12.1/envs/funannotate/lib/python2.7/site-packages/ete3/tools/ete.py", line 95, in main
    _main(sys.argv)
  File "/home_nfs/duca/local/conda/4.7.12.1/envs/funannotate/lib/python2.7/site-packages/ete3/tools/ete.py", line 109, in _main
    p = Popen(["git", "describe", "--tags"], stdout=PIPE, stderr=PIPE)
  File "/home_nfs/duca/local/conda/4.7.12.1/envs/funannotate/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home_nfs/duca/local/conda/4.7.12.1/envs/funannotate/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory
```
But, it was weird because I installed the funannotate in another server last week.
So, I made some tests and figured out the installation occurs with success in CentOS 7, but in CentOS 6 the installation fails.
I made the test with 2 servers with CentOS 7 and another 2 servers with CentOS 6.

Best.

**Comment by nextgenusfs** [comment]
`ete3` is literally only used in `funannotate compare` if you use the `--run_dnds` option.  So I'm thinking the easiest short term fix to make installation easier on more systems is to remove `ete3` from the conda recipe.  Users that want to run dN/dS in compare can still do it, they just need to install ete3 manually. 

Would that work for you guys?

**Comment by euduca** [comment]
I haven't performed a` funannotate compare` yet, but I will do it to test your suggestion.

**Comment by nextgenusfs** [comment]
@euduca -- if everything else is installed (except ete3), all of the tests in `funannotate test -t all --cpus X` should all pass (I can't remember off top of my head if the compare test has `--run_dnds` enabled or not).  In `funannotate compare` it should only look for `ete3` if you pass `--run_dnds` option, thus it should run properly under default settings even if `ete3` isn't installed.

**Comment by euduca** [comment]
Great.

Thanks.
