### ISSUE TITLE
Genemark-Es failed

### ISSUE THREAD

**Issue by shanmugavadivelps** [nextgenusfs/funannotate#381]
I am running GeneMark-ES in MXlinux19. I downloaded Genemark file and added key file as mentioned and also installed all 4 perl dependencies.

I used a command "/home/iipruser/Genemark_ES/gmes_petap.pl --sequence /media/iipruser/Drive_2/Repeatmasker_out/spades_sca55to71/scaffolds55to71.fasta --ES --fungus --cores 10".

But i am getting an error message like this 

warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_345.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_345
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_346.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_346
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_347.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_347
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_348.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_348
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_349.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_349
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_35.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_35
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_350.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_350
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_351.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_351
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_352.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_352
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_353.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_353
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_354.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_354
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_355.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_355
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_356.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_356
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_357.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_357
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_358.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_358
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_36.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_36
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_37.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_37
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_38.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_38
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_39.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_39
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_4.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_4
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_40.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_40
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_41.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_41
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_42.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_42
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_43.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_43
warning on: /home/iipruser/Genemark_ES/gmhmme3  -m /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_ini/es_ini.mod   -f tr  -T /home/iipruser/Genemark_ES   -o /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run/ES_A_1/hmmout/dna.fa_44.out  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/data/training/dna.fa_44
/home/iipruser/Genemark_ES/parse_set.pl: 9: /home/iipruser/Genemark_ES/parse_set.pl: use: not found
/home/iipruser/Genemark_ES/parse_set.pl: 10: /home/iipruser/Genemark_ES/parse_set.pl: use: not found
/home/iipruser/Genemark_ES/parse_set.pl: 11: /home/iipruser/Genemark_ES/parse_set.pl: use: not found
/home/iipruser/Genemark_ES/parse_set.pl: 12: /home/iipruser/Genemark_ES/parse_set.pl: Syntax error: "(" unexpected
error on call: /home/iipruser/Genemark_ES/parse_set.pl --section ES_A --cfg  /media/iipruser/Drive_1/Shanmu/Fusarium/Genemark/run.cfg  --v 
	(in cleanup) 	(in cleanup)  at /home/iipruser/anaconda3/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction.
I changed perl location in all .pl as /home/iipruser/anaconda3/bin/perl.

Again i failed to run

**Comment by nextgenusfs** [comment]
I have seen this one before:
```
in cleanup) (in cleanup) at /home/iipruser/anaconda3/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction
```
Which is apparently harmless on my computer.  However, I don't know what the problem is -- perhaps the GeneMark developers would be of help.  I would have changed the shebang to something a bit more flexible, ie. `#!/usr/bin/env perl` (I really wish this would get changed upstream...), but assuming you installed the perl modules in your anaconda distribution that theoretically could work.
