### ISSUE TITLE
 Evidence modeler has failed, exiting

### ISSUE THREAD

**Issue by unalibun** [nextgenusfs/funannotate#382]
Hi Jon, 
I am running funannotate in a conda ENV created recently, I am running the tutorial step by step but once the funannotate finish the prediction step my predics_results folder is empty. My std error file show this information
...
[09:35 PM]: Multi-threading in tblastn v2.9.0 is unstable, running in single-threaded mode for BUSCO
[09:42 PM]: 0 valid BUSCO predictions found, now formatting for EVM
[09:44 PM]: Running EVM commands with 9 CPUs
[09:46 PM]: Converting to GFF3 and collecting all EVM results
[09:46 PM]: Evidence modeler has failed, exiting

My command is this: 

#!/bin/bash
#$ -cwd
#$ -V
#$ -q all.q
#$ -pe smp 10
module load miniconda2
module load GeneMark/4.38
module load signalp/4.1
conda activate funannotate_my_env

export FUNANNOTATE_DB="$HOME/funannotate_db"
export GENEMARK_PATH="/Storage/progs/gm_et_linux_64_v4.38/gmes_petap"

funannotate predict -i p_ulei_scaf_clean_sfmasked_relabled.fa -o fun_p_ulei -s "Pseudocercospora ulei" --protein_evidence /Storage/data2/me/PacBio/annotation/braker_more_evidence/all_pseudocercosporas_reduced_stop_repaires.faa --augustus_gff /Storage/data2/me/PacBio/annotation/braker_new_genome_buscos/braker/Pseudocercospora_ulei/augustus.joingenes.gff3  --busco_seed_species zymoseptoria_tritici --other_gff /Storage/data2/me/PacBio/annotation/braker_new_genome_buscos/hisat_scaf/p_fijiensis_hints.gff --cpus $NSLOTS \

my ENV log is very long and does not show any error. On the other hand, my predict_misc busco files are empty but genemark files are completed.

I hope you can help me.

Best 

UnalIbun

**Comment by nextgenusfs** [comment]
What version of funannotate? Most likely the BUSCO error is related to write permissions problems with $AUGUSTUS_CONFIG_PATH directory. I think this is attempted to be fixed in most recent release but on clusters it is difficult to know as many systems are setup with custom permissions settings. Look at the BUSCO logfile to see if that gives you a hint.
