### ISSUE TITLE
funannotate update - "Duplicate key" error

### ISSUE THREAD

**Issue by ctxchris** [nextgenusfs/funannotate#390]
Hi,

I get an error running funannotate update.

**Are you using the latest release?**
Version 1.7.2

**Describe the bug**

funannotate update throws a "Duplicate key 'contig3'" error when trying to convert the "bestmodels.gff3" to tbl format in function  "GFF2tblCombinedNEW". All previous steps have been run and completed without error.

> Traceback (most recent call last):
  File "/home/anaconda/envs/funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/home/anaconda/envs/funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/home/anaconda/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 2200, in main
    alt_transcripts=args.alt_transcripts)
  File "/home/anaconda/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 1040, in GFF2tblCombinedNEW
    evm, genome, gene_inter, Genes)
  File "/home/anaconda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 3254, in gff2interlapDict
    Genes = gff2dict(input, fasta, Genes, gap_filter=True)
  File "/homeanaconda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 3686, in gff2dict
    SeqRecords = SeqIO.to_dict(SeqIO.parse(fasta, 'fasta'))
  File "/home/anaconda/envs/funannotate/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 833, in to_dict
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'contig3'

Thanks for any on this,
Chris

**Comment by nextgenusfs** [comment]
Seems to be saying you have more than one contig with that name - check your genome fasta headers.

**Comment by ctxchris** [comment]
You're right. The odd thing is that the input genome fasta doesn't have duplicate headers and "genome.fa.fai" also shows no duplicates. Only after Pasa and kallisto "genome.fa" shows 52 duplicate sequences.

**Comment by ctxchris** [comment]
The original headers and the ones in update_misc/genome.fasta all look like contig1, contig2 etc. Some just get written twice in genome.fasta. I noticed that 38 of the 52 duplicated contigs two mRNAs (*-T1 and *-T2) per gene annotated.

E.g. from update_misc/genome.gff3
> contig319	GenBank	gene	1642	1932	.	-	.	ID=FUN_038157;
contig319	GenBank	mRNA	1642	1932	.	-	.	ID=FUN_038157-T1;Parent=FUN_038157;product=hypothetical protein;
contig319	GenBank	exon	1642	1932	.	-	.	ID=FUN_038157-T1.exon1;Parent=FUN_038157-T1;
contig319	GenBank	CDS	1642	1932	.	-	0	ID=FUN_038157-T1.cds;Parent=FUN_038157-T1;
contig319	GenBank	mRNA	1642	1932	.	-	.	ID=FUN_038157-T2;Parent=FUN_038157;product=hypothetical protein;
contig319	GenBank	exon	1642	1932	.	-	.	ID=FUN_038157-T2.exon1;Parent=FUN_038157-T2;
contig319	GenBank	CDS	1642	1932	.	-	0	ID=FUN_038157-T2.cds;Parent=FUN_038157-T2;

From pasa/*gene_structures_post_PASA_updates.1932.bed
> contig319	1641	1932	ID=FUN_038157-T2;FUN_038157;FUN_038157-T2	0	-	1641	1932	0	1	291	0
contig319	1641	1932	ID=FUN_038157-T1;FUN_038157;FUN_038157-T2	0	-	1641	1932	0	1	291	0
contig319	1641	1932	ID=FUN_038157-T1;FUN_038157;FUN_038157-T2	0	-	1641	1932	0	1	291	0

**Comment by nextgenusfs** [comment]
Okay thanks for checking. Can you also check the number of contigs and headers from the results of predict? When you run update with just the folder as input it grabs data from the predict_results folder, specifically it grabs the genbank file in that folder and then splits it into several pieces. So I guess need to see if the headers are repeated in that GenBank file in predict_results or if the bug is somehow in the parsing of that file. Thanks for the help.

**Comment by ctxchris** [comment]
The genbank file in predict_results already has the duplicated entries, the *tbl and *scaffolds.fa files are fine.

**Comment by ctxchris** [comment]
I removed the duplicate entries in the genbank file and continued funannotate update.

The next error I get apparently concerns the gff format:

>ERROR: ID=FUN_022885 has no CDS features, removing gene model
Traceback (most recent call last):
  File "/home/anaconda/envs/funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/home/anaconda/envs/funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/home/anaconda/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 2200, in main
    alt_transcripts=args.alt_transcripts)
  File "/home/anaconda/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 1040, in GFF2tblCombinedNEW
    evm, genome, gene_inter, Genes)
  File "/home/anaconda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 3254, in gff2interlapDict
    Genes = gff2dict(input, fasta, Genes, gap_filter=True)
  File "/home/anaconda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 3695, in gff2dict
    Genes[k]['mRNA'][i] = sortedExons
KeyError: u'FUN_022885'


The entries for that gene in bestmodels.gff3 look like this:

>contig31	PASA	gene	302709054	302711523	.	+	.	ID=FUN_022885;
contig31	PASA	mRNA	302709054	302711523	.	+	.	ID=FUN_022885-T1;Parent=FUN_022885;Note=TPM:82.92;
contig31	PASA	exon	302709054	302709099	.	+	.	ID=FUN_022885-T1.exon1;Parent=FUN_022885-T1;
contig31	PASA	CDS	302709054	302709099	.	+	0	ID=cds.FUN_022885-T1;Parent=FUN_022885-T1;
contig31	PASA	exon	302709263	302709402	.	+	.	ID=FUN_022885-T1.exon2;Parent=FUN_022885-T1;
contig31	PASA	CDS	302709263	302709402	.	+	2	ID=cds.FUN_022885-T1;Parent=FUN_022885-T1;
contig31	PASA	exon	302711331	302711405	.	+	.	ID=FUN_022885-T1.exon3;Parent=FUN_022885-T1;
contig31	PASA	CDS	302711331	302711405	.	+	0	ID=cds.FUN_022885-T1;Parent=FUN_022885-T1;
contig31	PASA	exon	302711428	302711523	.	+	.	ID=FUN_022885-T1.exon4;Parent=FUN_022885-T1;
contig31	PASA	CDS	302711428	302711523	.	+	0	ID=cds.FUN_022885-T1;Parent=FUN_022885-T1;
contig31	PASA	gene	302709054	302711523	.	+	.	ID=FUN_022885;
contig31	PASA	mRNA	302709054	302711523	.	+	.	ID=FUN_022885-T2;Parent=FUN_022885;Note=TPM:82.92;
contig31	PASA	exon	302709054	302709099	.	+	.	ID=FUN_022885-T2.exon1;Parent=FUN_022885-T2;
contig31	PASA	CDS	302709054	302709099	.	+	0	ID=cds.FUN_022885-T2;Parent=FUN_022885-T2;
contig31	PASA	exon	302709263	302709402	.	+	.	ID=FUN_022885-T2.exon2;Parent=FUN_022885-T2;
contig31	PASA	CDS	302709263	302709402	.	+	2	ID=cds.FUN_022885-T2;Parent=FUN_022885-T2;
contig31	PASA	exon	302711331	302711405	.	+	.	ID=FUN_022885-T2.exon3;Parent=FUN_022885-T2;
contig31	PASA	CDS	302711331	302711405	.	+	0	ID=cds.FUN_022885-T2;Parent=FUN_022885-T2;
contig31	PASA	exon	302711428	302711523	.	+	.	ID=FUN_022885-T2.exon4;Parent=FUN_022885-T2;
contig31	PASA	CDS	302711428	302711523	.	+	0	ID=cds.FUN_022885-T2;Parent=FUN_022885-T2;
contig31	PASA	gene	302709054	302711523	.	+	.	ID=FUN_022885;
contig31	PASA	mRNA	302709054	302711523	.	+	.	ID=FUN_022885-T1;Parent=FUN_022885;Note=TPM:82.92;
contig31	PASA	exon	302709054	302709099	.	+	.	ID=FUN_022885-T1.exon1;Parent=FUN_022885-T1;
contig31	PASA	CDS	302709054	302709099	.	+	0	ID=cds.FUN_022885-T1;Parent=FUN_022885-T1;
contig31	PASA	exon	302709263	302709402	.	+	.	ID=FUN_022885-T1.exon2;Parent=FUN_022885-T1;
contig31	PASA	CDS	302709263	302709402	.	+	2	ID=cds.FUN_022885-T1;Parent=FUN_022885-T1;
contig31	PASA	exon	302711331	302711405	.	+	.	ID=FUN_022885-T1.exon3;Parent=FUN_022885-T1;
contig31	PASA	CDS	302711331	302711405	.	+	0	ID=cds.FUN_022885-T1;Parent=FUN_022885-T1;
contig31	PASA	exon	302711428	302711523	.	+	.	ID=FUN_022885-T1.exon4;Parent=FUN_022885-T1;
contig31	PASA	CDS	302711428	302711523	.	+	0	ID=cds.FUN_022885-T1;Parent=FUN_022885-T1;
contig31	PASA	gene	302709054	302711523	.	+	.	ID=FUN_022885;
contig31	PASA	mRNA	302709054	302711523	.	+	.	ID=FUN_022885-T2;Parent=FUN_022885;Note=TPM:82.92;
contig31	PASA	exon	302709054	302709099	.	+	.	ID=FUN_022885-T2.exon1;Parent=FUN_022885-T2;
contig31	PASA	CDS	302709054	302709099	.	+	0	ID=cds.FUN_022885-T2;Parent=FUN_022885-T2;
contig31	PASA	exon	302709263	302709402	.	+	.	ID=FUN_022885-T2.exon2;Parent=FUN_022885-T2;
contig31	PASA	CDS	302709263	302709402	.	+	2	ID=cds.FUN_022885-T2;Parent=FUN_022885-T2;
contig31	PASA	exon	302711331	302711405	.	+	.	ID=FUN_022885-T2.exon3;Parent=FUN_022885-T2;
contig31	PASA	CDS	302711331	302711405	.	+	0	ID=cds.FUN_022885-T2;Parent=FUN_022885-T2;
contig31	PASA	exon	302711428	302711523	.	+	.	ID=FUN_022885-T2.exon4;Parent=FUN_022885-T2;
contig31	PASA	CDS	302711428	302711523	.	+	0	ID=cds.FUN_022885-T2;Parent=FUN_022885-T2;

It also seems that I get "has no CDS features, removing gene model" error messages for every gene model, even though there are CDS tags.

**Comment by nextgenusfs** [comment]
Okay, so you can also pass --fasta and --gff to update which will then theoretically fix your issue in the short term by not parsing the GenBank file.  For this re-run that you ran, did you delete the intermediate results in `update_misc` before re-running? If not, you will likely need to do that as `funannotate` will re-use existing data which in this case would be wrong.  

But I'm more interested in how/why it happened in the first place.  Do you have a large number of contigs and/or large genome size?  I ask this because `funannotate` will run tbl2asn (which generates the GBK file from tbl + fasta) in "multithreaded" mode which basically just means it chunks the input and then runs tbl2asn on the chunks and then merges results back together.  So in your `predict_misc` folder should be a sub-folder called `tbl2asn` -- you can see how many chunks it ran by looking in that directory.   

And then also which version of tbl2asn are you using - is this a bug in tbl2asn?  Lastly, in v1.7.3 I fixed a bug that showed up if there were gene models predicted to start/end in gaps -- do you have gaps in your contigs?  Either way, I'd upgrade to newest version if possible as easier to troubleshoot.

**Comment by ctxchris** [comment]
It's a 3G genome with about 2k sequences. There are 26 chunks in tbl2asn. The tbl2asn version bundled within conda crashed so I replaced it with a version from early February this year. Could be that it's an issue with mixing old and new intermediate files.

**Comment by nextgenusfs** [comment]
If you have time would be helpful to run tbl2asn outside of funannotate on the complete tbl and fasta file -- the command it runs should be in your logfile from predict.  That way I know if there is a problem with the splitting/recombining or with tbl2asn -- my guess is the split/recombine.....
