### ISSUE TITLE
DB xrefs do not conform to GFF3 spec

### ISSUE THREAD

**Issue by sestaton** [nextgenusfs/funannotate#392]
To be brief, `DBxref` is not the same thing as `Dbxref` according to the GFF3 spec: https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md#ontology-associations-and-db-cross-references

This is a very hard thing to catch since it is not recognized by certain parsers and thus ignored.

**Comment by nextgenusfs** [comment]
Funannotate is built to output proper genbank submission files, which at the time this was written, NCBI never supported GFF3. So the output here is built for NCBI’s db_xref annotation per tbl2asn tbl format.  Parsing GFF3 is sort of a fools errand as very few if any tools follow the spec.....  It does write GFF3 as output files as a matter of convenience.

**Comment by nextgenusfs** [comment]
Updated 'DBxref' to 'Dbxref' in GFF3 parsing and output in the py3 branch which will be next release. https://github.com/nextgenusfs/funannotate/commit/8e725988a7d388fc70bc25711e6e001f880a8a12

**Comment by sestaton** [comment]
Thanks, this will be appreciated by others I'm sure. I agree that a lot of what people call GFF3 are really just tab-delimited files of various forms, but there are validation tools and ontologies for checking that all of the features, terms, and types are defined properly. That level of detail is unnecessary for this project, but it is helpful (necessary even) for maintaining standards across APIs, genome browsers, etc.
