### ISSUE TITLE
error in funannotate test

### ISSUE THREAD

**Issue by Homap** [nextgenusfs/funannotate#393]
Hello,

Trying to run `funannotate test -t all --cpus 8`, I get the following error:                                                                   
```
#########################################################
Running `funannotate clean` unit testing: minimap2 mediated assembly duplications
CMD: funannotate clean -i test.clean.fa -o test.exhaustive.fa --exhaustive
#########################################################
-----------------------------------------------
6 input contigs, 6 larger than 500 bp, N50 is 427,039 bp
Checking duplication of 6 contigs
-----------------------------------------------
scaffold_91 appears duplicated: 100% identity over 100% of the contig. contig length: 8858
scaffold_73 appears duplicated: 100% identity over 100% of the contig. contig length: 15153
scaffold_27 appears duplicated: 100% identity over 100% of the contig. contig length: 427039
-----------------------------------------------
6 input contigs; 6 larger than 500 bp; 3 duplicated; 3 written to file
#########################################################
SUCCESS: `funannotate clean` test complete.
#########################################################

#########################################################
Running `funannotate mask` unit testing: RepeatModeler --> RepeatMasker
CMD: funannotate mask -i test.fa -o test.masked.fa --cpus 8
#########################################################
-------------------------------------------------------
[10:59 AM]: OS: linux2, 20 cores, ~ 131 GB RAM. Python: 2.7.15
[10:59 AM]: Running funanotate v1.7.2
[10:59 AM]: Soft-masking simple repeats with tantan
[10:59 AM]: Repeat soft-masking finished: 
Masked genome: /crex/proj/uppstore2018213/homap/test-mask_7062/test.masked.fa
num scaffolds: 2
assembly size: 1,216,048 bp
masked repeats: 50,965 bp (4.19%)
-------------------------------------------------------
#########################################################
SUCCESS: `funannotate mask` test complete.
#########################################################

#########################################################
Running `funannotate predict` unit testing
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 8 --species Awesome testicus
#########################################################
-------------------------------------------------------
[10:59 AM]: OS: linux2, 20 cores, ~ 131 GB RAM. Python: 2.7.15
[10:59 AM]: Running funannotate v1.7.2
Traceback (most recent call last):
  File "/proj/uppstore2018213/PROJ_ENVS/funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/proj/uppstore2018213/PROJ_ENVS/funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/proj/uppstore2018213/PROJ_ENVS/funannotate/lib/python2.7/site-packages/funannotate/predict.py", line 426, in main
    for f in os.listdir(os.path.join(LOCALAUGUSTUS, 'species', aug_species)):
OSError: [Errno 2] No such file or directory: 'annotate/predict_misc/ab_initio_parameters/augustus/species/saccharomyces'
#########################################################
Traceback (most recent call last):
  File "/proj/uppstore2018213/PROJ_ENVS/funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/proj/uppstore2018213/PROJ_ENVS/funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/proj/uppstore2018213/PROJ_ENVS/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 389, in main
    runPredictTest(args)
  File "/proj/uppstore2018213/PROJ_ENVS/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 152, in runPredictTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_testicus.gff3')) <= 1800
  File "/proj/uppstore2018213/PROJ_ENVS/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 40, in countGFFgenes
    with open(input, 'rU') as f:
IOError: [Errno 2] No such file or directory: 'test-predict_7062/annotate/predict_results/Awesome_testicus.gff3'


```
**OS/Install Information**
 -  output of `-------------------------------------------------------
Checking dependencies for 1.7.2
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 0.9.9
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.6.7
requests: 2.22.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.024001. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.40
Clone: 0.39
DBD::SQLite: 1.54
DBD::mysql: 4.043
DBI: 1.634
DB_File: 1.84
Data::Dumper: 2.160
File::Basename: 2.85
File::Which: 1.21
Getopt::Long: 2.48
Hash::Merge: 0.200
JSON: 4.02
LWP::UserAgent: 6.26
Logger::Simple: 2.0
POSIX: 1.65
Parallel::ForkManager: 1.19
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.11
Text::Soundex: 3.05
Thread::Queue: 3.09
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.26
threads: 2.07
threads::shared: 1.51
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/crex/proj/uppstore2018213/funannotate_db
$PASAHOME=/proj/uppstore2018213/PROJ_ENVS/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/proj/uppstore2018213/PROJ_ENVS/funannotate/opt/trinity-2.8.5
$EVM_HOME=/proj/uppstore2018213/PROJ_ENVS/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/proj/uppstore2018213/PROJ_ENVS/funannotate/config/
$GENEMARK_PATH=/sw/bioinfo/GeneMark/4.38-es/rackham/gmes_petap.pl
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: 2.0.1
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.38
hisat2: 2.1.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.1
mafft: v7.455 (2019/Dec/7)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.12
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
signalp: 4.1
snap: 2006-07-28
stringtie: 2.0
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed`

Thank you very much for your help

**Comment by nextgenusfs** [comment]
Might just be the Augustus version. What is the output of “funannotate species” command? Is saccharomyces in that table?

**Comment by pavlohrab** [comment]
I have the same issue. Have you managed to solve it?
