### ISSUE TITLE
free RepBase alternative

### ISSUE THREAD

**Issue by mictadlo** [nextgenusfs/funannotate#395]
Hi,
Is there a free alternative for RepBase for academics?

Thank you in advance,

Michal

**Comment by hyphaltip** [comment]
There is not at this time though some discussion of crowd sourcing based on annotations in a bunch of genome sets and many of us who had last version releases of files might be able to share. I am not sure what is allowed.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by mictadlo** [comment]
Will funannotate work without a softmasked genome or will it give different results?

**Comment by nextgenusfs** [comment]
The current version uses a simple repeat masking using tantan as default. It can still run repeatmodeler/masker/repbase but given the licensing situation they are not installed via conda install.  If you try to run predict without a softmasked genome it will make you pass the —force option. I have not explicitly tested many genomes with and without masking, it would depend on the repeats in the genome you are working with. 

The community could benefit from an open source repeat masking solution, both in terms of data curation but also in terms of ease of use/install/etc (repeatmasker/modeler isn’t very easy to work with). We’ve heard there is some work from the DFAM team in expanding their HMM database beyond just human genomics, but I don’t know the current status.

**Comment by mictadlo** [comment]
Do you know how to use DFAM?

**Comment by mictadlo** [comment]
An alternative could be [windowmasker](https://www.ncbi.nlm.nih.gov/pubmed/16287941)

```
#!/bin/bash
# usage: sh windowmasker_pbs.sh ref.fasta
cat << EOF  |qsub
#!/bin/bash -l
#PBS -N windowmasker
#PBS -l walltime=150:00:00
#PBS -j oe
#PBS -l mem=12G
#PBS -l ncpus=2
#PBS -M m.lorenc@qut.edu.au

cd \$PBS_O_WORKDIR

##WinMasker on your genome assembly in two separate stages.
## stage 1: create the reusable masking library
windowmasker -checkdup true -mk_counts -in $1 -out ${1}-windowmasker.ustat  -mem 10500

## stage 2: use the masking library to soft-mask the genome assembly
windowmasker -ustat ${1}-windowmasker.ustat -in $1 -out \$(basename ${1})-windowmasker.fasta -outfmt fasta -dust true

EOF
```
