### ISSUE TITLE
Usage of '--weights' in 'funannotate prediction' for specifying predictor and weight

### ISSUE THREAD

**Issue by Shunsuke-Kanamori** [nextgenusfs/funannotate#397]
Hello,

`--weights` in `funannotate predict` specify predictors?
If I set `--weights augustus:1 pasa:1`, results of prediction by SNAP, GlimmerHMM, CodingQuarry and GeneMark-ES/ET will be totally ignored?

Thank you in advance.

Shunsuke Kanamori

**Comment by nextgenusfs** [comment]
They are set to default of 1, so you will need to turn those to 0 if you want to ignore those data.

**Comment by Shunsuke-Kanamori** [comment]
Thank you for your quick reply.

I'll set it that way and try.

**Comment by Nitin123-4** [comment]
I have a followup question according to Evidence Modeler, still incorporate the structural information (introns, exons)
but just not incorporate additional weighting to them - but those structures will accumulate scores from other inputs.

If we give --weights as 0 for some tools will it completely avoid in the final results?

**Comment by hyphaltip** [comment]
yes exactly to no run these two tools at all you can do:
```
--weights snap:0 glimmerhmm:0 
```
