### ISSUE TITLE
PASA MySQL setup comment

### ISSUE THREAD

**Issue by timkahlke** [nextgenusfs/funannotate#398]
Hi,

This is basically not your problem but I thought it might be worth mentioning. When setting up PASA with MySQL the [PASA-How-To](https://github.com/PASApipeline/PASApipeline/wiki/setting-up-pasa-mysql) set's the write access for sql user _pasa_write_ only for specific databases (prefix _pasa).

```
grant all privileges on `%_pasa`.* to 'pasa_write'@'localhost';
```

However, funannotate doesn't follow that naming scheme and the pasa_write user can't create/write to the databases. 

Might be a security problem, of course, but granting access to everything fixes that.

`grant all privileges on *.* to 'pasa_write'@'localhost';`

Cheers,
Tim

**Comment by schraderL** [comment]
Hi, 
I am running into this issue, as our admins don't want to grant full priviliges to the mysql PASA user. Is it possible to change the names of the sql databases created by funannotate to match the `_pasa` or another prefix?
Cheers
lukas

**Comment by hyphaltip** [comment]
So just a `_pasa` suffix to the db names - seems easy update @nextgenusfs ?
