### ISSUE TITLE
mRNA transcripts span gaps

### ISSUE THREAD

**Issue by isgilman** [nextgenusfs/funannotate#399]
Hello Jon, I'm using v1.6.0, which I know is old, but I think my question is relevant across versions.

Funannotate automatically flags models that begin or end in gaps, but not those that span gaps. For example, here are some models that made it through `update` that span a gap.

![Screen Shot 2020-03-27 at 2 22 01 PM](https://user-images.githubusercontent.com/15131080/77788960-8fb98100-7038-11ea-928f-c6e815b41b33.png)

Why is this is default behavior of funannotate? As a rule of thumb, I would drop any model that spans a gap. In total, I found 105 predicted mRNAs that spanned gaps but only 6 models were caught by the "begin or end in gap" criterion. 

Best,

Ian

**Comment by hyphaltip** [comment]
This is however EVM will manage to make these calls. Presumably if exonerate aligned a transcript across and EVM calls the transcript valid then it is still called. But I agree this might be filtered out or an option allowed.

**Comment by nextgenusfs** [comment]
Hi @isgilman are those models present before you ran `funannotate update`?  There were some bugs in the filtering for start/end in gap that were fixed in v1.7.3 -- so as always I'd recommend updating if you can (obvs can be hard if in the middle of something or shared system). 

As far as I understand EVM, is that it will not create a gene model from transcript or protein alignments, but rather will ONLY call a gene model if one exists in the ab initio predictions (gene_predictions.gff3) and the transcript/protein alignments help to weight the scoring of which model it chooses.

**Comment by isgilman** [comment]
Checking the mRNA file in `predict_results`

```bash
(base) [isg4@c20n01 predict_results]$ grep -E "NN+" Portulaca_amilis_v0.mrna-transcripts.fa | wc -l
1
```

found only a single line with `N`s. So it seems like more were found between `fix` and `update`.  In the `training` directory, `trinity.fasta` has no `N`s but `pasa/Portulaca_amilis.assemblies.fasta` has plenty of gaps. Could the `pasa` results be where they're coming from? 

Ideally I'd update but this annotation is just about in great shape so we're not going to tinker with anything right now. As far as I can tell, `funannotate` has caught every model that does _begin or end_ in a gap. After I added the models with gaps to the list of models to drop, running `fix` after `update` removed all the problematic models as expected.

**Comment by nextgenusfs** [comment]
PASA (via fun annotate update) can add new gene models, likely even if they were removed by filtering in predict -- I'll have to look at what is being used for filtering there, perhaps need to add back the span/start/begin in gaps to remove those models after running update. As far as I know there is no real setting to control that behavior in PASA.  

Ideally we should look into other solutions for UTR extension and alternative transcript calling, PASA is kind of a pain to manage/use.
