### ISSUE TITLE
question and/or request for `--stranded` argument

### ISSUE THREAD

**Issue by devonorourke** [nextgenusfs/funannotate#401]
When passing multiple RNAseq datasets into `funannotate train`, is it possible to specify the `--stranded` flag to particular reads and not others? 

For example, in the tutorial:
```
funannotate train -i MyAssembly.fa -o fun \
    --left liquid_R1.fq.gz solid_R1.fq.gz medium_R1.fq.gz \
    --right liquid_R2.fq.gz solid_R2.fq.gz medium_R2.fq.gz \
    --nanopore_mrna nanopore_mRNA.fq.gz \
    --stranded RF --jaccard_clip --species "Pseudogenus specicus" \
    --strain JMP12345 --cpus 12
```

What if I knew that the **liquid** and **solid** datasets were _unstranded_, but the **medium** dataset was _stranded_?

I'm guessing there is some sort of alternative where we might run Trinity externally on each RNAseq dataset separately (either invoking `--SS_lib_type` as needed), then passing that info back into Funannotate somehow?

Perhaps it's not a big difference?

**Comment by nextgenusfs** [comment]
Short answer is no they can’t be individual stranded settings for each dataset. If they are not all stranded then trinity should be run in unstranded mode. It should still yield good results as what funannotate runs here is genome guided trinity, so it aligns reads to the genome and then de novo assembles the reads in “bins” based on their alignment.
