### ISSUE TITLE
ModuleNotFoundError: No module named 'funannotate'

### ISSUE THREAD

**Issue by caonetto** [nextgenusfs/funannotate#405]
Hi,
I have the most recent conda installation of funnanotate.
When trying to predict genes I get the following error during the augustus run,
`Traceback (most recent call last):
  File "/scratch/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/augustus_parallel.py", line 9, in <module>
    import funannotate.library as lib
ModuleNotFoundError: No module named 'funannotate'
`
Why would this module be missing?

Thanks,

**Comment by xiaoaozqd** [comment]
Hi caonetto,
I have observed the same problem. Have you fixed this problem and how?
`File "~/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/augustus_parallel.py", line 9, in <module>
    import funannotate.library as lib
ImportError: No module named funannotate.library`

**Comment by jasminelmah** [comment]
Just came across this. I'm having the same problem. Did either of you find a solution? Thanks!

**Comment by jasminelmah** [comment]
Hi, I found a solution for my problem. Perhaps it may work for you. See issue [424](https://github.com/nextgenusfs/funannotate/issues/424#issuecomment-632827857).

**Comment by margaretc-ho** [comment]
Thanks for the solution! I also submitted my job from a clean node (no funannotate conda env activated, only activated conda env from within the script using source activate) and it ran AUGUSTUS within funannotate predict without issues.

**Comment by hyphaltip** [comment]
you may want to make sure your job submission scripts have `#!/usr/bin/bash -l` with the `-l` ensures a clean env on a job starting.

**Comment by aldendirks** [comment]
I was getting this same error running from a conda environment on a computing cluster with slurm. I was loading python again in my script (module load python), which was not needed (and detrimental) since the correct python was already installed in the conda environment. A rookie mistake; hopefully this comment will help others avoid it.

**Comment by aberaslop** [comment]
Hi all! I am also getting the same error. Any advice of how to fix it is welcome. Thank you!

[Oct 08 03:32 AM]: Running Augustus gene prediction using fusarium parameters
Traceback (most recent call last):
  File "/scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/augustus_parallel.py", line 10, in <module>
    import funannotate.library as lib
ModuleNotFoundError: No module named 'funannotate'
[Oct 08 03:32 AM]: CMD ERROR: perl /scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/opt/evidencemodeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl FBUL/predict_misc/augutus.gff3
[Oct 08 03:32 AM]: Error, cannot open file FGRES/predict_misc/augustus.gff3 at /scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/opt/evidencemodeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl line 23.

I have tried to run funannotate from a cluster with slurm, in a new ssh session, as suggested, and this does not work (i have uploaded the script). I have also tried to run it without the script, just running "funannotate predict" on an interactive session. The same error appears. 
[submit_funpred.txt](https://github.com/user-attachments/files/17288936/submit_funpred.txt)

I have checked: 

ls -l /scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/augustus_parallel.py

Which results in: 

-rwxrwxr-x 2 zrs382 R_SciStor-UCIT-Guests-BAZIS_C 6941 Apr 26  2023 /scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/augustus_parallel.py


I think all the packages are installed: 


-------------------------------------------------------
Checking dependencies for 1.8.15
-------------------------------------------------------
You are running Python v 3.8.15. Now checking python packages...
biopython: 1.81
goatools: 1.3.11
matplotlib: 3.4.3
natsort: 8.4.0
numpy: 1.24.4
pandas: 1.5.3
psutil: 5.9.5
requests: 2.31.0
scikit-learn: 1.3.2
scipy: 1.10.1
seaborn: 0.13.0
All 11 python packages installed


You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.50
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.858
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.54
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.17
YAML: 1.30
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/scistor/guest/zrs382/software/funannotate_db
$PASAHOME=/scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/opt/pasa-2.5.3
$TRINITY_HOME=/scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/config/
$GENEMARK_PATH=/scistor/guest/zrs382/.conda/envs/mamba/envs/funannotate/opt/gmes_linux_64_4
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.5.3
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.5.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.31.1
blat: BLAT v37x1
diamond: 2.1.8
emapper.py: 2.1.12
ete3: 3.1.3
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2023-10-10
gmes_petap.pl: 4.71_lic
hisat2: 2.2.1
hmmscan: HMMER 3.4 (Aug 2023)
hmmsearch: HMMER 3.4 (Aug 2023)
java: 17.0.3-internal
kallisto: 0.46.1
mafft: v7.520 (2023/Mar/22)
makeblastdb: makeblastdb 2.14.1+
minimap2: 2.26-r1175
pigz: 2.8
proteinortho: 6.3.0
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.16.1
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.12 (Nov 2022)
tantan: tantan 40
tbl2asn: 25.8
tblastn: tblastn 2.14.1+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: signalp not installed


Thank you so much!
