### ISSUE TITLE
Local interproscan not working.

### ISSUE THREAD

**Issue by caonetto** [nextgenusfs/funannotate#406]
Trying to run inteproscan locally.

`funannotate iprscan -i funnannotate -m local --iprscan_path '/scratch/installers/interproscan/interproscan-5.36-75.0/interproscan.sh' -c 10`

Getting the following error when using version 5.36 on Interproscan.

Running InterProScan5 on 10757 proteins
Important: you need to manually configure your interproscan.properties file for embedded workers.
Will try to launch 10 interproscan processes, adjust -c,--cpus for your system
Traceback (most recent call last):
  File "/scratch/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 361, in <module>
    combine_xml(final_list, finalOut)
  File "/scratch/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 54, in combine_xml
    tree.write(output, encoding='utf-8', xml_declaration=True)
  File "/scratch/conda/envs/funannotate/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/scratch/conda/envs/funannotate/lib/python2.7/xml/etree/ElementTree.py", line 876, in _namespaces
    iterate = elem.getiterator # cET compatibility
AttributeError: 'NoneType' object has no attribute 'getiterator'

Any ideas? Thanks

**Comment by Dikaryotic** [comment]
I've no solution, but I thought I'd chime in to say I've also encountered the same error. This was running using a script that had previously ran fine, so my suspicion is that it's something to do with updating to funannotate v 1.7.4 which I've done since last running the script.

**Comment by nextgenusfs** [comment]
Did it create a temp directory? It should generate a logfile for each interproscan run, the error relates to parsing XML so either format has changed or it died and there is no xml file to parse.

**Comment by Dikaryotic** [comment]
Yep, a temp directory was created, I've attached one of the logfiles from a recent attempt I ran. 

[Lentinula_novae-zelandiae_LEN2.proteins_1.log](https://github.com/nextgenusfs/funannotate/files/4484293/Lentinula_novae-zelandiae_LEN2.proteins_1.log)

**Comment by nextgenusfs** [comment]
Okay -- so hopefully that's helpful?  Looks like you need to adjust your interproscan properties file.  Could be related to the version of python3 you are supplying?

**Comment by caonetto** [comment]
I managed to run interproscan independently and then included the xml file to funannotate annotate without any issues.

**Comment by atiweb** [comment]
You are using interproscan version 5.36-75.0, maybe something change in the xml parse, update if posible. Funnanotate parse well interproscan version 5.39 and 5.40
