### ISSUE TITLE
suggestions on RNAseq data to use (or not)

### ISSUE THREAD

**Issue by devonorourke** [nextgenusfs/funannotate#407]
I was curious in @nextgenusfs's and other Funannotate users experience how they incorporate same and related-species RNAseq data. I'm working with two North American bat species in the same genus. I have three separate tissues worth of RNAseq data for one species ("**speciesA**"), and one RNAseq dataset derived from a cell line of the second species ("**speciesB**".

When running Funannotate for **speciesA**, it seemed reasonable to just use the 3 same-species libraries. No need to add in the one other library from the alternate species. But in the case of **speciesB**, I wondered if it would be worthwhile adding in some or all of the RNAseq data from **speciesA**. I wasn't sure exactly which processes the transcript alignment information is important for (PASA? Augustus?), but given that **SpeciesB** only has RNAseq data from a cell line (which I'm not sure what fraction of transcripts/proteins it's expressing), maybe it is sensible to use the alternate **speciesA** data too.

I'm curious to learn how others think about incorporating information from related species in Funannotate, and what risks there might be in adding in related species transcript evidence. Maybe there is something that I can tweak downstream in Evidence Modeler to differentiate the same vs. related species inputs?

Thanks!

**Comment by atiweb** [comment]
Make a try and see whats happens. Compare results after...

**Comment by devonorourke** [comment]
Thanks @atiweb , any particular suggestions on what to compare? My guess is trying to match up alignment data to gene predictions with and without alternate species data.

In Maker there is an option to use EvidenceModeler to specify the weights of the same vs. alternative species data; in Funannotate all I can tell EvidenceModeler is used for is to set weights for the various gene prediction programs. Given that all input read data is concatenated into a single file,  I'm not sure how I might get the program to tease the same vs. alternative species apart if needed.  If for instance, it seems that the alternative-species has additional splice site data that is absent in the same-species data _some of the time_, but in other times is _absent_ in many others, then it would make sense to me recalibrate the EVM weights to prefer same over alternative species, not treat them as equal (as can be done in Maker).

I've already found several of the default parameters in Funannotate need to be changed in my vertebrate genome. For example, when first testing the various gene predictors, only Augustus is working well, and SNAP, GeneMark, and GlimmerHMM are performing poorly (albeit for different reasons). The comparison here was simply to look at gene dense regions and determine how the various prediction programs stack up to alignment evidence. Perhaps you're suggesting that "_Compare results after..._" is taking a similar approach?

**Comment by nextgenusfs** [comment]
EVM will only make gene model calls from gene_predictions (ie from input that is labeled ab into or other) -- it only uses the protein alignments and transcript alignments to score which model to select at each locus.  In practice, I don't really see how altering the weights from same/close species on transcript alignments is going to make much of a difference -- admittedly I have not tried this. It wouldn't be that hard to run this comparisons outside of the fun annotate pipeline, ie you could use the EVM wrapper in funannotate to run EVM on input data that you've partitioned in different ways.  It just uses the 'source' tag of the GFF3 along with the weights parameters to adjust its internal scoring.

**Comment by EarlyEvol** [comment]
Minor thread hijack.
Do you have a suggestion for how to incorporate multiple RNA-seq types? I have a stranded larval and an non-stranded adult data set.  Is there a way to feed everything into PASA (by preassembling and concatenating) while only using stranded for ab initio training set?  My thinking was to capture as many gene models as possible from RNA-seq with PASA, but use the more accurate stranded assembly for training to reduce spurious ab initio models.  Am I overthinking this?

Thanks all

**Comment by nextgenusfs** [comment]
There isn't a way to separate datasets currently in funannotate.  You can combine stranded and unstranded data -- basically you will want to run Trinity in "unstranded" mode. You could run some preliminary experiments to perhaps look at how this might effect the results, ie run Trinity on the stranded dataset in both "stranded" and "unstranded" mode and see how big of difference the results are (ie you could run funannotate train to do this, just run it twice with the stranded dataset in stranded/unstranded mode). If you don't see much of a difference in the resulting PASA gene model output, then likely there is no harm in combining them. You should be able to use `funannotate util contrast` to compare the GFF3 files from each method.

**Comment by EarlyEvol** [comment]
Thanks!  I'll set that up right now.
Do you know if having mixed data sets will mess with any assumptions of stringtie or hints file generation/usage?  I guess I could contrast those outputs too.

**Comment by nextgenusfs** [comment]
The hintsfiles are simply the intron/exon boundaries -- so likely not.  Stringtie is really only used to train CodingQuarry -- basically as a somewhat "independent" method.  I have not testing this explicitly.

**Comment by EarlyEvol** [comment]
Oh! gotchya.  Thanks for all the info.
