### ISSUE TITLE
Avoid RepeatModeler ?

### ISSUE THREAD

**Issue by ptranvan** [nextgenusfs/funannotate#41]
Hi!

I am using an another tool for TE detection.
Is that possible to run funannotate without the step RepeatModeler and Repeatmasking ? (assuming that I repeatmask my genome myself).

**Comment by nextgenusfs** [comment]
Yes - the most recent updates should allow that, I haven't done a release yet as I haven't had a chance to thoroughly test it. But you should be able to pass `--masked_genome` and `--repeatmasker_gff3` to bypass TE detection via RepeatModeler/RepeatMasker.

**Comment by nextgenusfs** [comment]
As of v0.5.5 this is now supported.
