### ISSUE TITLE
"funannotate update" failed in the last step of parsing GenBank files.

### ISSUE THREAD

**Issue by Shunsuke-Kanamori** [nextgenusfs/funannotate#414]
I simply run `funannotate update -i fun`.
Then, I got the following log and error.

> [09:36 AM]: OS: linux2, 24 cores, ~ 396 GB RAM. Python: 2.7.15
> [09:36 AM]: Running funannotate v1.6.0-98d4d3f
> [09:36 AM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
> [09:36 AM]: Found relevent files in fun/training, will re-use them:
> 	Forward reads: fun/training/left.fq.gz
> 	Reverse reads: fun/training/right.fq.gz
> 	Forward Q-trimmed reads: fun/training/trimmomatic/trimmed_left.fastq.gz
> 	Reverse Q-trimmed reads: fun/training/trimmomatic/trimmed_right.fastq.gz
> 	Forward normalized reads: fun/training/normalize/left.norm.fq
> 	Reverse normalized reads: fun/training/normalize/right.norm.fq
> 	Trinity results: fun/training/funannotate_train.trinity-GG.fasta
> 	PASA config file: fun/training/pasa/alignAssembly.txt
> 	BAM alignments: fun/training/funannotate_train.coordSorted.bam
> 	StringTie GTF: fun/training/funannotate_train.stringtie.gtf
> [09:37 AM]: Reannotating Anolis allisoni, NCBI accession: None
> [09:37 AM]: Previous annotation consists of: 25,340 protein coding gene models and 2,539 non-coding gene models
> [09:50 AM]: Converting transcript alignments to GFF3 format
> [09:50 AM]: Converting Trinity transcript alignments to GFF3 format
> [09:51 AM]: PASA database is SQLite: /lustre7/home/lustre3/kanashun/analysis/chromium_genome/repeatmask__to__funannotate/lasts/allisoni/fun/training/pasa/Anolis_allisoni
> [09:51 AM]: Running PASA annotation comparison step 1
> [07:09 PM]: Running PASA annotation comparison step 2
> [11:30 AM]: Using Kallisto TPM data to determine which PASA gene models to select at each locus
> [11:30 AM]: Building Kallisto index
> [11:34 AM]: Mapping reads using pseudoalignment in Kallisto
> [11:40 AM]: Parsing Kallisto results. Keeping alt-splicing transcipts if expressed at least 10.0% of highest transcript per locus.
> [11:40 AM]: Wrote 27,631 transcripts derived from 25,542 protein coding loci.
> [11:41 AM]: Validating gene models (renaming, checking translations, filtering, etc)
> [11:41 AM]: Writing 27,885 loci to TBL format: dropped 0 overlapping, 4 too short, and 21 frameshift gene models
> [11:41 AM]: Converting to Genbank format
> [11:59 AM]: Collecting final annotation files
> [12:00 PM]: Parsing GenBank files...comparing annotation
> Traceback (most recent call last):
>   File "/lustre7/home/lustre3/kanashun/software/funannotate160/bin/funannotate-update.py", line 2061, in <module>
>     compareAnnotations2(GBK, final_gbk, Changes)
>   File "/lustre7/home/lustre3/kanashun/software/funannotate160/bin/funannotate-update.py", line 1313, in compareAnnotations2
>     UTRs = findUTRs(newGenes[gene[2]]['CDS'], newGenes[gene[2]]['mRNA'], newGenes[gene[2]]['strand'])
>   File "/lustre7/home/lustre3/kanashun/software/funannotate160/bin/funannotate-update.py", line 1363, in findUTRs
>     refInterlap = InterLap(mrna[i])
> IndexError: list index out of range

I haven't successfully installed the latest version yet, is there any way to resolve it using version 1.6.0?
Or is it fixed in the latest version?

**Comment by nextgenusfs** [comment]
I don't know what the problem is from what you've posted here. Is there more information in the log file? Do the GenBank files look complete?

**Comment by Shunsuke-Kanamori** [comment]
I started over again from `funannotate train` and this time `funannotate update` worked solidly to the end.
There may have been some subtle glitches in my environment when `train` or `predict` worked.
I'm sorry to bother you.
I'll share again when I find out what's causing it.
