### ISSUE TITLE
Documentation: Kallisto in funannotate train not clear

### ISSUE THREAD

**Issue by photocyte** [nextgenusfs/funannotate#415]
Thanks for making funannotate.  In my past experience with PASA, a real value add has been to incorporate transcript expression information for filtering.  I'm glad to see from (https://github.com/nextgenusfs/funannotate/blob/1ee07cb06fcaa595dc59f1ffcfa32aa8cff61598/funannotate/train.py) , that funannotate seems to do this too, but maybe it isn't so clear in the documentation?  E.g. this doesn't list Kallisto as a dependency: https://funannotate.readthedocs.io/en/latest/commands.html#funannotate-train

**Comment by nextgenusfs** [comment]
Kallisto is used to estimate relative expression of each gene model -- then to "choose" to keep alternative spliced models or not.  The default is to keep all alt spliced models that are expressed at least 10% of the most highly expressed variant at that locus. Will try to find some time to update docs....
