### ISSUE TITLE
Some gene is incomplete without stop codon

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#417]
Hello Jon,
I am much appreciated for your help.
I found a error about final gene and protein sequence. I can run all command well in plant genome. However, I met a error log when I use CDS and protein sequence to do PAML analysis. The error is like as well. 
Then I check the gene sequence, I found the sueqnce do not have correct plant stop codon. Could you help me check this error?
Thanks,
Fuyou
Skipping sequence SH_022915-T1 in orthogroup  not in codon frame

-- Fri May  1 12:28:10 2020 - Running CODEML failed

>SH_022915-T1 SH_022915
ATGCAAGGAGAATCTTCTCATCCCCATCACCAGGAAGCTGAAGTCTCCACATCCTTTCAAGGAAATGAGAGATCCACCAAATCGCCTATCACTGCTTTAATCCAAGTTGAAGGTGACAATAGAGAGCTAGCTCTGCAAGAATCATCTCCTCACAATCCTCTCAATGCAGCCGAGGGTAATTCAGTTACTTCACTCTCCATCTCTACTTCTCATGCTCATCATCCAGGATCATTGGTGGCTGCAAATCTTCAAATAGTTGAGACTTCCAAGAATATGGAGATTGAAGAAGTCTTAGTTGATGCCACCATTTCCTCTGATTTACCATCTATCAAACCTGGACTCACTACTCCCATAGTTAGTGGATCAACTAAAACCTGGAAAAGAGATAGAACCAAGGATGGAAGACTTCAAAGGGAACCAGTACTCCTCATCCTCATCGACAAAGAGATTACAAGTAAAAGGCAAAG

**Comment by hyphaltip** [comment]
You mean it doesn't have a terminal stop codon - for one PAML wants those
trimmed out anyways.
what translation table are you using?
Some gene will be incomplete without curation - you should probably exclude
those that don't meet a criteria before you proceed to molecular evolution
I'm not clear what error you get from PAML for this gene to know what the
issue is exactly.

Jason Stajich
@hyphaltip
http://lab.stajich.org

**Comment by sunnycqcn** [comment]
Hello Jason,
I am much appreciated for your replying. I want to know if I can get all CDS with stop codon using funannotate. I used funannotate to annotate other genomes. It is excellent. But I met this error when I run PAML.
Can I control this error in funannotate?
Best,
Fuyou

**Comment by hyphaltip** [comment]
Your question isn’t clear. You have one problem with one gene or all genes? Sometimes Incomplete or inframe stops come through in the predictions you should consider a filter before running the paml analysis. It is unclear how to just fix the problem you don’t have that much context. Is this a gene model that shouldn’t be predicted. Is it a pseudo gene or transposon that got through.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by sunnycqcn** [comment]
Hello Jason,
Thans for your fast replying.
I got CDS and protein sequence with funannotate pipeline. I think I should get complete CDS and protein with this pipeline. In fact, I got the complete CDS and protein sequence in fungi genome prediction. But this time, I got some CDS and protein were incomplete.
My question is I can change the parameters to get all complete predicted CDS and proteins when I use funannotate pipeline.
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
Hi Jon,
I have checked my prediction file when I used it for predicting plant genome. I found the prediction files have some incorrect format.
Between cds and protein file,
1. Some cds are incomplete
2. Some cds without stop codon
3. Some cds can not corresponding with their correct protein. For example, 1500 bases cds should have 499 aas,  however it may be 450 aas.
All these errors were not found in my fungal genome.
If you have time, could you check what it happen?
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
Hi Jon,
I still met this problem when I annotate plant genome using funannotate pipeline.
I did not know what it happened.
Thanks,
Fuyou
