### ISSUE TITLE
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by yangzuokun** [nextgenusfs/funannotate#421]
build DB wrong: funannotate setup  -d /DB

[11:36 PM]: Downloaded curated gene names and product descriptions
File "/opt/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 668, in main
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address>

**Comment by yangzuokun** [comment]
def curatedDB(info, force=False, args={}):
    curatedFile = os.path.join(FUNDB, 'ncbi_cleaned_gene_products.txt')
    if os.path.isfile(curatedFile) and args.update and not force:
        if check4newDB('gene2product', info):
            force = True
    if not os.path.isfile(curatedFile) or force:
        lib.log.info('Downloaded curated gene names and product descriptions')
        for x in [curatedFile]:
            if os.path.isfile(x):
                os.remove(x)
        if args.wget:
            wget(resources.DBURL.get('gene2product'), curatedFile)
        else:
            download(resources.DBURL.get('gene2product'), curatedFile)
        md5 = calcmd5(curatedFile)
        num_records = 0
        curdate = ''
        version = ''
        with open(curatedFile, 'rU') as infile:
            for line in infile:
                if line.startswith('#version'):
                    version = line.split(' ')[-1].rstrip()
                elif line.startswith('#Date'):
                    curdate = line.split(' ')[-1].rstrip()
                else:
                    num_records += 1
        curdate = datetime.datetime.strptime(
            curdate, "%m-%d-%Y").strftime("%Y-%m-%d")
        info['gene2product'] = ('text', curatedFile,
                                version, curdate, num_records, md5)
    type, name, version, date, records, checksum = info.get('gene2product')
    lib.log.info('Gene2Product: version={:} date={:} records={:,}'.format(
        version, date, records))

**Comment by nextgenusfs** [comment]
Are you behind a firewall/proxy server? Usually this happens if you can't connect to the internet from your system. You can try the `-w` flag which will use `wget` instead of the python requests module.
