### ISSUE TITLE
Busco can't read Database

### ISSUE THREAD

**Issue by nhartwic** [nextgenusfs/funannotate#422]
Currently trying to get funannotate functioning on aws. I installed funannotate using conda. I'm getting the following error message whenever I try to run funannotate.

INFO    ****************** Start a BUSCO 2.0 analysis, current time: 05/17/2020 17:47:20 ******************
ERROR   Impossible to read ./fun_db/dikarya

ERROR   BUSCO analysis failed !

...Any ideas why busco would be unable to read the busco database?

**Comment by nextgenusfs** [comment]
Is that path correct? `./fun_db/dikarya` and the folder exists?  If so, probably permissions.

**Comment by nhartwic** [comment]
Thanks, it was a path issue. The funannotate db option is apparently not evaluated relative to the working directory from which the funannotate command was issued. I'm not sure where its evaluated relative to, but using an absolute path fixes it.

**Comment by nextgenusfs** [comment]
if you set FUNANNOTATE_DB as an ENV variable should then not have to pass that as an option to any of the scripts.

**Comment by nhartwic** [comment]
I generally prefer to make arguments explicit rather than implicit. And in any case, it wouldn't have solved my problem. I just needed to use an absolute rather than relative path. To clarify...

```
# This pair of commands does not work
funannotate setup -i all -d fun_db/

funannotate predict  -i ath.softmasked.fasta  \
    -o ath --species ath -d fun_db/  \
    --organism other --repeats2evm \
    --name WM --augustus_species maize \
    --cpus 32

# This pair of commands works
funannotate setup -i all -d fun_db/

funannotate predict  -i ath.softmasked.fasta  \
    -o ath --species ath -d $(pwd)/fun_db/  \
    --organism other --repeats2evm \
    --name WM --augustus_species maize \
    --cpus 32
```

**Comment by nextgenusfs** [comment]
okay, thanks for clarification.  Shouldn't be a problem to add `os.path.abspath()` to the database option.
