### ISSUE TITLE
Not sucessful when install funannotate with Conda on HPC

### ISSUE THREAD

**Issue by chenpingau** [nextgenusfs/funannotate#423]
**Are you using the latest release?**
Yes

**Describe the bug**
I tried to install funannotate on HPC
I followed the instructions EXACTLY from https://funannotate.readthedocs.io/en/latest/install.html
But still not successful.

There are several errors (refer to the below output of "funannotate check --show-versions")

1. ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir 

2. samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

3. fasta: no way to determine

4. pslCDnaFilter: no way to determine

5. tbl2asn: no way to determine, likely 25.X

6.         ERROR: emapper.py not installed
        ERROR: ete3 not installed
        ERROR: gmes_petap.pl not installed
        ERROR: samtools not installed
        ERROR: signalp not installed

I have some experience with HPC, a little experiences with Conda, and totally new with funannotate. I have no idea how to fix the above issues.

Could anyone help me with above issues?

**What command did you issue?**
# then create environment
$ conda create --name funannotate01 python=2.7 funannotate

# start up conda ENV
$ conda activate funannotate01

# check that all modules are installed
$ funannotate check --show-versions

# download/setup databases to a writable/readable location
$ funannotate setup -d /home/chenpingau/tools/funannotate_db_01

# set ENV variable for $FUNANNOTATE_DB
echo "export FUNANNOTATE_DB=/home/chenpingau/tools/funannotate_db_01" > /home/chenpingau/.conda/envs/funannotate01/etc/conda/activate.d/funannotate.sh
echo "unset FUNANNOTATE_DB" > /home/chenpingau/.conda/envs/funannotate01/etc/conda/deactivate.d/funannotate.sh

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
(base)                                        
/home/chenpingau/tools
$ conda activate funannotate01                
(funannotate01)                               
/home/chenpingau/tools
$ funannotate check --show-versions           
-------------------------------------------------------
Checking dependencies for 1.7.4                        
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76                                                 
goatools: 0.6.4                                                 
matplotlib: 2.2.4                                               
natsort: 6.2.0                                                  
numpy: 1.16.5                                                   
pandas: 0.24.2                                                  
psutil: 5.7.0                                                   
requests: 2.23.0                                                
scikit-learn: 0.20.3                                            
scipy: 1.2.1                                                    
seaborn: 0.9.0                                                  
All 11 python packages installed                                

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002                                          
Carp: 1.38                                                   
Clone: 0.42                                                  
DBD::SQLite: 1.64                                            
DBD::mysql: 4.046                                            
DBI: 1.642                                                   
DB_File: 1.852                                               
Data::Dumper: 2.173                                          
File::Basename: 2.85                                         
File::Which: 1.23                                            
Getopt::Long: 2.5                                            
Hash::Merge: 0.300                                           
JSON: 4.02                                                   
LWP::UserAgent: 6.39                                         
Logger::Simple: 2.0                                          
POSIX: 1.76                                                  
Parallel::ForkManager: 2.02                                  
Pod::Usage: 1.69                                             
Scalar::Util::Numeric: 0.40                                  
Storable: 3.15                                               
Text::Soundex: 3.05                                          
Thread::Queue: 3.12                                          
Tie::File: 1.02                                              
URI::Escape: 3.31                                            
YAML: 1.29                                                   
threads: 2.15                                                
threads::shared: 1.56                                        
All 27 Perl modules installed                                

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/chenpingau/tools/funannotate_db_01
$PASAHOME=/home/chenpingau/.conda/envs/funannotate01/opt/pasa-2.4.1               
$TRINITY_HOME=/home/chenpingau/.conda/envs/funannotate01/opt/trinity-2.8.5        
$EVM_HOME=/home/chenpingau/.conda/envs/funannotate01/opt/evidencemodeler-1.1.1    
$AUGUSTUS_CONFIG_PATH=/home/chenpingau/.conda/envs/funannotate01/config/          
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir         
-------------------------------------------------------                         
Checking external dependencies...                                               
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
PASA: 2.4.1                                                                                                                  
CodingQuarry: 2.0                                                                                                            
Trinity: 2.8.5                                                                                                               
augustus: 3.3.2
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.24
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1
kallisto: 0.46.2
mafft: v7.464 (2020/Apr/21)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: ete3 not installed
        ERROR: gmes_petap.pl not installed
        ERROR: samtools not installed
        ERROR: signalp not installed
(funannotate01)
/home/chenpingau/tools

**Comment by nextgenusfs** [comment]
See here for some tips https://github.com/nextgenusfs/funannotate/issues/389. You have to install GeneMark manually due to licensing.  The other errors are not errors, just telling you there is no way to determine version in that particular software.  Try a different version of samtools on bioconda, this is a common problem with some dependencies. 

I suspect that you have packages installed in your base conda directory, hence some dependencies get adjusted by conda.

**Comment by chenpingau** [comment]
@nextgenusfs, thank you for your quick reply!

I found on HPC it has GeneMark-ES module.

Now I ran

   $ module load genemark-es/4.33

before starting the Conda environment. Then I ran the following test:

$ funannotate test -t all --cpus 1

I already found the famous GeneMark license issue happened in the test

I'll try to solve this license issue and other issues if there any.

Thank you again!
