### ISSUE TITLE
Problem with Trinity Assembly input

### ISSUE THREAD

**Issue by mccartneya90** [nextgenusfs/funannotate#425]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**

**What command did you issue?**
Copy/paste the command used.

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`

**Comment by mccartneya90** [comment]
Heya,

So I've a slight issue. I have 25 stick insect species to annotate. The post doc before me assembled all of their transcriptomes using Trinity, but somehow some of the species have lost their original raw reads. I have tried running funannotate train using only the de-novo assemblies but it keeps erroring out. Below is what I am submitting. Am I missing a parameter OR is this just not possible?

funannotate \
train \
-i clitarchus_sorted.fna \
--trinity 6Cli_Trinity_cdhit.fasta \
--max_intronlen 64000 \
-o honeybee_train \
--memory 50G \
--species "honeybee1" \
--cpus 10 

Thanks in advance,
Ann

**Comment by nextgenusfs** [comment]
Likely going to run into problems without the raw data, its used several times to validate the gene models and pick alternative transcripts to use.  It might be possible to address this in the future.
