### ISSUE TITLE
Proteinortho error

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/funannotate#426]
Hi Jon,

I have posted this issue in a closed thread, and I don't know if you would see it there. I apologize for that. 

I have analyzed a number of fungal genomes with no problem. However, when I run "funannotate compare", it stops at the proteinortho step with an error saying that my species is not found in proteinortho results. I have attached the log file and an excerpt of one of my gbk files below, as well as the funannotate check logs (I ran eggnog outside funannotate). 

I am running funannotate v.1..7.2 with conda in Ubuntu 14.04.6 LTS.  Any idea of how I could fix this? Thank you so much! 
   
[gbk_excerpt.txt](https://github.com/nextgenusfs/funannotate/files/4658775/gbk_excerpt.txt)

[funannotate-compare.log](https://github.com/nextgenusfs/funannotate/files/4658747/funannotate-compare.log)

[funannotate_check.log](https://github.com/nextgenusfs/funannotate/files/4662796/funannotate_check.log)

**Comment by aberaslop** [comment]
Update: Finding the species name in each Genebank file and replacing the space with an underscore, seems to have fixed the problem. 

Cheers!

**Comment by nextgenusfs** [comment]
Okay thanks for the follow up.  I thought this issue had been addressed already, perhaps in the newest version its no longer an issue. I will try to double check before next release.
