### ISSUE TITLE
Pfam database setup urls may need updating

### ISSUE THREAD

**Issue by DigitalNomadDotXyz** [nextgenusfs/funannotate#433]
Hello,

It looks like EMBL's pfam database ftp paths may have changed.  When I was performing a new funannotate setup today, the database setup failed on the pfam urls in the resources script (550 errors getting returned)

https://github.com/nextgenusfs/funannotate/blob/9e8483b3ca0287f2c0e7d24ca162fd2c7b5a23c4/funannotate/resources.py#L154

It looks like they have updated the paths for those:

ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_releases

When I updated the script locally to point to where the files now live, the database setup was able to complete

Thanks for providing this project as open source!

**Comment by DigitalNomadDotXyz** [comment]
As an aside, I setup another instance yesterday and did not observe this problem, so they must have just changed the paths

**Comment by nextgenusfs** [comment]
Okay great thanks for info.  In next release I took the hard coded paths out of the code and will have that as a JSON file -- which gets updated when you run setup (ie downloads from GitHub).  That should allow us to update the links when they change without modifying/updating the code.

**Comment by nextgenusfs** [comment]
So it went from .../current_release to .../current_releases, correct?

**Comment by DigitalNomadDotXyz** [comment]
Correct, it looks like they just added an s!

**Comment by DigitalNomadDotXyz** [comment]
As an update, it now looks like the Pfam database urls currently in master branch resources.py and downloads.json are working again, and the "updated" url I mentioned above no longer works

I have no idea what they were doing 2 weeks ago, but it looks like no changes would be needed after all!  I guess this Issue could be closed

Working again:
  ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/
  ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/

Not working:
  ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_releases
