### ISSUE TITLE
Question about "AUTHORS" and "JOURNAL" in the final output file "*.gbk"

### ISSUE THREAD

**Issue by szzxpxf** [nextgenusfs/funannotate#435]
Hi Jon,

I have found funannotate you built very helpful for my annotation project. Thanks for creating such a great tool. I do have a question about the final output file "*.gbk". I see that in the file the "AUTHORS" included your name "Palmer, J.M." and under the Journal it lists "Submitted (13-JUN-2020) CFMR, USDA Forest Service, 1 Gifford Pinchot Drive, Madison, WI 53726, USA". 

I am confused why the above information was included in the final annotation output file. More importantly, I would like to know if such information will become part of the NCBI record if I submit this "*.gbk" file to NCBI. Please advise and your time is much appreciated!

Nick

**Comment by hyphaltip** [comment]
You need to provide your own sbt file when you run the annotate or update step - go here to create one. https://submit.ncbi.nlm.nih.gov/genbank/template/submission/

**Comment by szzxpxf** [comment]
Thanks for the explanation!
