### ISSUE TITLE
interpro DB apparent format change

### ISSUE THREAD

**Issue by nhartwic** [nextgenusfs/funannotate#437]
As of June 18, the interpro xml file seems to have changed its date formats which is breaking the funannotate setup. The latest interpro.xml includes a version entry that looks like

```
<dbinfo version="80.0" dbname="INTERPRO" entry_count="37471" file_date="18-JUN-2020"/>
```

If you check [the code](https://github.com/nextgenusfs/funannotate/blob/9e8483b3ca0287f2c0e7d24ca162fd2c7b5a23c4/funannotate/setupDB.py#L431), funannotate expects the file_date to be formatted as '%d-%b-%y'. This format should be "%d-%b-%Y" due to the date now including the full 4 digit year encoding.

I'm uncertain if anything else needs to be fixed here. I'll try to get a dev environment setup and submit a pull request.

**Comment by nextgenusfs** [comment]
Thanks for reporting— we will need to support backwards compatibility with previous format.  But I don’t think will be too difficult as can hopefully parse the version first?

**Comment by nhartwic** [comment]
I can just add a check for datetime format as part of parsing. Basically:

```
try old format
catch parse error:
    try new format
```

**Comment by nhartwic** [comment]
Not really related, but a quick right up in the docs on how to successfully create a dev environment for funannotate would be very helpful for people who want to contribute.
