### ISSUE TITLE
funannotate compare 

### ISSUE THREAD

**Issue by SolayMane** [nextgenusfs/funannotate#439]
Thank you very much for this very useful pipeline.
I'm runing funannotate compare with " genomes as fellow : 

funannotate compare -i ../m13annotation2 GCA_005930515.1_ASM593051v1_genomic.gbff GCA_007994515.1_ASM799451v1_genomic.gbff -o funannotate_compare --cpus 50 --num_orthos 1000 --outgroup fusarium_graminearum.dikarya

**Logfiles**

Please provide relavent log files of the error.
 [01:50 PM]: OS: linux2, 56 cores, ~ 396 GB RAM. Python: 2.7.18
[01:50 PM]: Running 1.7.4
[01:50 PM]: Now parsing 3 genomes
[01:50 PM]: working on Fusarium oxysporum f. sp. albedinis
[01:51 PM]: working on Fusarium oxysporum f. sp. cubense 160527
[01:51 PM]: working on Fusarium oxysporum f. sp. cubense TR4
[01:52 PM]: No secondary metabolite annotations found
[01:52 PM]: Summarizing PFAM domain results
[01:52 PM]: Summarizing InterProScan results
[01:52 PM]: Loading InterPro descriptions
Traceback (most recent call last):
  File "/home/inra/conda/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/inra/conda/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/inra/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/compare.py", line 419, in main
    INTERPRO = lib.iprxml2dict(os.path.join(FUNDB, 'interpro.xml'), uniqIPR)
  File "/home/inra/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 6978, in iprxml2dict
    iprDict[ID] = description
UnboundLocalError: local variable 'description' referenced before assignment

**OS/Install Information**
Checking dependencies for 1.7.4
-------------------------------------------------------
You are running Python v 2.7.18. Now checking python packages...
biopython: 1.76
goatools: 1.0.5
matplotlib: 2.2.5
natsort: 5.0.2
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.12.5
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.7.7
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/sanhome2/data/annotation/funannotate_db
$PASAHOME=/home/inra/conda/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/inra/conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/inra/conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/inra/conda/envs/funannotate/config/
$GENEMARK_PATH=/home1/software/genmark/gmes_linux_64
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.34
emapper.py: 2.0.1
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.57_lic
hisat2: 2.2.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.467 (2020/May/14)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.17
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.7
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: signalp not installed

**Comment by nextgenusfs** [comment]
InteProScan changed their XML format.  The code in master is updated, you can install and update database like this:
```
# from your current funannotate environment (assuming conda)
python -m pip install git+https://github.com/nextgenusfs/funannotate.git

# update interpro files
funannotate setup -i interpro --force
```

Just a side note -- NCBI genomes won't have all of the annotations funannotate is looking for, although it will run the phylogeny -- but you will need to run them through `funannotate annotate` in order to get the functional annotation in a format that `funannotate compare` can parse.

**Comment by SolayMane** [comment]
Thank you for your collaboration! 
You mean that I need to reannotate the NCBI genomes using funannotate annotate?
Can I trust the phylogeny without reannotating these genomes?

**Comment by nextgenusfs** [comment]
It should still run fine — just lots of the results that count and compare functional annotation will be empty because the data isn’t in the genbank annotation files. The phylogeny should still run I think.
