### ISSUE TITLE
Locus Tag issue

### ISSUE THREAD

**Issue by vcastroagudin** [nextgenusfs/funannotate#440]
I am looking for help with the locus tab information that should be input through the sbt file.
In the sbt template file downloaded from the Ncbi website there is no field to complete with the locus tag given for a genome, only the biosample and bio project numbers. So, where the locus tag info go? How I I put my code into funannotate annotate? Is this not needed anymore in funannotate 1,7.4? Has the sbt from Ncbi changed?

Thanks.

**Comment by nextgenusfs** [comment]
To get a locus_tag you need to start a genome submission. If the plan is to submit to NCBI you can start this before you annotate, basically fill out a new genome submission and in the notes tell NCBI that you will be annotating the assembly you upload. You can add the annotation at a later date. This is helpful as then NCBI will run their QC pipeline on your assembly and they will let you know if the assembly is okay, ie no adapter contamination etc. If you have to fix the assembly after you’ve annotated it, the process is kind of a nightmare.

**Comment by vcastroagudin** [comment]
Hi Jon,
Thanks for your reply. I understand how the process. Indeed, I did my submission and got the template file. But the question is, where in that file is that locus tag the Funannotate will use. I open the template file in a text editor after doing my submission to check it and the tag I got assigned is not written there anywhere. That is the reason of my question. DO you have an example I could check and test?

Thanks.

Vanina

**Comment by nextgenusfs** [comment]
It should be on your submission page, likely elsewhere.  Here is one from a few years ago.
<img width="781" alt="Screen Shot 2020-06-25 at 9 16 27 AM" src="https://user-images.githubusercontent.com/6164308/85757936-be410980-b6c4-11ea-82cf-68f24b8097ac.png">

**Comment by vcastroagudin** [comment]
I see that in the ncbi website , but the sbt file you download to feed Funannotate does not have all that info.


Submit-block ::= {
  contact {
    contact {
      name name {
        last "Castroagudin",
        first "Vanina",
        middle "",
        initials "",
        suffix "",
        title ""
      },
      affil std {
        affil "USDA-ARS",
        div "Mycology and Nematology Genetic Diversity  and Biology Laboratory",
        city "Beltsville",
        sub "Maryland",
        country "USA",
        street "10300 Baltimore Ave, Building 10A -",
        email "vanina.castroagudin@usda.gov",
        phone "4793133790",
        postal-code "20705-2325"
      }
    }
  },
  cit {
    authors {
      names std {
        {
          name name {
            last "LeBlanc",
            first "Nicholas",
            middle "",
            initials "",
            suffix "",
            title ""
          }
        },
        {
          name name {
            last "Castroagudin",
            first "Vanina",
            middle "",
            initials "L.",
            suffix "",
            title ""
          }
        },
        {
          name name {
            last "Crouch",
            first "Jo",
            middle "",
            initials "A.",
            suffix "",
            title ""
          }
        }
      },
      affil std {
        affil "USDA-ARS",
        div "Mycology and Nematology Genetic Diversity  and Biology Laboratory",
        city "Beltsville",
        sub "Maryland",
        country "USA",
        street "10300 Baltimore Ave, Building 10A -",
        postal-code "20705-2325"
      }
    }
  },
  subtype new
}
Seqdesc ::= pub {
  pub {
    gen {
      cit "unpublished",
      authors {
        names std {
          {
            name name {
              last "LeBlanc",
              first "Nicholas",
              middle "",
              initials "",
              suffix "",
              title ""
            }
          },
          {
            name name {
              last "Castroagudin",
              first "Vanina",
              middle "",
              initials "L.",
              suffix "",
              title ""
            }
          },
          {
            name name {
              last "Crouch",
              first "Jo",
              middle "",
              initials "A.",
              suffix "",
              title ""
            }
          }
        }
      },
      title "Calonectria pseudonaviculata Isolate CT1 Annotations"
    }
  }
}
Seqdesc ::= user {
  type str "DBLink",
  data {
    {
      label str "BioProject",
      num 1,
      data strs {
        "PRJNA418489"
      }
    },
    {
      label str "BioSample",
      num 1,
      data strs {
        "SAMN08028600"
      }
    }
  }
}
Seqdesc ::= user {
  type str "Submission",
  data {
    {
      label str "AdditionalComment",
      data str "ALT EMAIL:vanina.castroagudin@usda.gov"
    }
  }
}
Seqdesc ::= user {
  type str "Submission",
  data {
    {
      label str "AdditionalComment",
      data str "Submission Title:None"
    }
  }
}

**Comment by nextgenusfs** [comment]
So in `funannotate` the locus_tag is passed to `funannotate predict --name` option. In `funannotate annotate --rename` should do the same thing.  Its not parsed from the SBT file.

**Comment by vcastroagudin** [comment]
Thank you very much. That was not very clear in the manual. Thank you for the details.
