### ISSUE TITLE
--rename argument from funannotate annotate didn't rename locus_tags

### ISSUE THREAD

**Issue by vcastroagudin** [nextgenusfs/funannotate#443]
HELLO,

I ran the following command with the rename option but it did not work. Any help will be appreciated!!!

funannotate annotate --input ./predict_results --fasta masked_Cps_CT1.fasta --species Calonectria pseudonaviculata --out ./CT1_annonations --sbt CT1_template.sbt --eggnog CT1_Eggnog_annotations.tsv --antismash CT1_antishmash.gbk --iprscan CT1_intersproscan.xml --phobius CT1_phobius.txt --rename CT692 --cpus 8

Part of the Output without "FUN" tag changed in the gbk file...

(...)

COMMENT     'Annotated using 1.7.4'.
FEATURES             Location/Qualifiers
     source          1..5578780
                     /organism="Calonectria pseudonaviculata"
                     /mol_type="genomic DNA"
                     /db_xref="taxon:196064"
     gene            1381..>1612
                     /locus_tag="FUN_000001"
     mRNA            1381..>1612
                     /locus_tag="FUN_000001"
                     /product="hypothetical protein"
     CDS             1381..>1612
                     /locus_tag="FUN_000001"
                     /codon_start=1
                     /product="hypothetical protein"
                     /protein_id="ncbi:FUN_000001-T1"
                     /translation="MGDRMLLAADDYEIGFLFPEEPEDNVERIPTKLLQQLNLQPGQN
                     GHLHNFDFSTEVQRLLAAIPPNDPMFRAKHSVD"

(...)

**Comment by nextgenusfs** [comment]
Thanks for reporting, I will have a look when I get a chance. Likely a bug/failed logic somewhere.

**Comment by nextgenusfs** [comment]
Latest commit to master branch should fix it, you can install latest with:
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git
```
