### ISSUE TITLE
"NCBI tbl file not found, exiting" when running funannotate annotate

### ISSUE THREAD

**Issue by pavlohrab** [nextgenusfs/funannotate#449]
**Are you using the latest release?**
Yes. v 1.8.0

**Describe the bug**

I have genome as a Genbank file. I tried to assign functional annotation, but this error occurs:
`[02:33 PM]: NCBI tbl file not found, exiting `

I generated several *.tbl files with Artemis (save entry as feature ) and [this](https://github.com/wanyuac/BINF_toolkit/blob/master/gbk2tbl.py) script. They all had the same name as *.gbk file (not two at the same time), but none of them have worked. 

**What command did you issue?**
`funannotate annotate --genbank funannotate_S136/S136.gbk  -o Genomes/funannotate --iprscan funannotate_S136/S136.xml`

**Logfiles**
```
-------------------------------------------------------
[02:32 PM]: OS: linux2, 4 cores, ~ 16 GB RAM. Python: 2.7.15
[02:32 PM]: Running 1.8.0
[02:32 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[02:32 PM]: Found existing output directory Genomes/funannotate. Warning, will re-use any intermediate files found.
[02:32 PM]: Checking GenBank file for annotation
[02:33 PM]: NCBI tbl file not found, exiting
```

**OS/Install Information**
```
------------------------------------------------------
Checking dependencies for 1.8.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.24.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/data/funannotate
$PASAHOME=/data/miniconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/data/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/data/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/data/miniconda3/envs/funannotate/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
Traceback (most recent call last):
  File "/data/miniconda3/envs/funannotate/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/data/miniconda3/envs/funannotate/lib/python2.7/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/data/miniconda3/envs/funannotate/lib/python2.7/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name TextFace
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.0
hmmscan: HMMER 3.1b2 (February 2015)
hmmsearch: HMMER 3.1b2 (February 2015)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.245 (2015/07/22)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: ete3 not installed
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed


```

**How can I solve this issue?**

**Comment by nextgenusfs** [comment]
Okay, the problem with Genbank is in relation to multiple/alternative transcripts -- if they exist in the Genbank file, there is actually no way to properly align the mRNA/transcript with the CDS feature in Genbank format. Its a non-issue if there is only a single transcript/CDS per gene. That's why the script is looking for a tbl file.  It probably should be generating the tbl file when you give it the `--genbank` option. 

I don't know the format it which Artemis or your script you used wrote it, likely its missing something that funannotate is expecting.  You can try to use `funannotate util gbk2parts` and see if that tbl file is appropriate.  I will look into and likely add tbl file generation from Genbank if it is missing.

**Comment by pavlohrab** [comment]
I don't know that `funannotate util gbk2parts` exist. The script generated  several files from which .tbl one is empty. 
Using `funannotate util gff2tbl` with generateв gff3 and proteins.fasta gave me a .tbl file but `funannotate annotate` still is not seeing it. The error message is `NCBI tbl file not found, exiting`

If it helps I am trying to add functional annotation to bacteria genome. Genbank file is generated with prokka.


> Okay, the problem with Genbank is in relation to multiple/alternative transcripts -- if they exist in the Genbank file, there is actually no way to properly align the mRNA/transcript with the CDS feature in Genbank format. Its a non-issue if there is only a single transcript/CDS per gene. That's why the script is looking for a tbl file. It probably should be generating the tbl file when you give it the `--genbank` option.
> 
> I don't know the format it which Artemis or your script you used wrote it, likely its missing something that funannotate is expecting. You can try to use `funannotate util gbk2parts` and see if that tbl file is appropriate. I will look into and likely add tbl file generation from Genbank if it is missing.

**Comment by nextgenusfs** [comment]
This is written for eukaryotes.  There are many ways to functionally annotate bacterial genomes. The fundamental difference in the data structures is that bacterial annotations typically do not contain transcript level annotations, ie CDS are children of genes.  That is invalid for eukaryotes, where CDS are children of mRNA which is a child of a gene -- hence the GFF3/GBK parsers, etc all assume eukaryotic structure.  Its outside the scope of this project to try to support prokaryotes. Having said that, you probably could reformat a prokaryotic GFF3 to funannotate/eukaryotic compliant and it should work, but I would think there are ways to add functional annotation in prokka.
