### ISSUE TITLE
busco.final.gff3 missing

### ISSUE THREAD

**Issue by gedankenstuecke** [nextgenusfs/funannotate#45]
Hey, I just encountered a weird problem when running funannotate. I started `funannotate predict` with some `--transcript_evidence Trinity.All.fasta --protein_evidence protein_evidence.fa` and at some point after the initial BUSCO & EVM step it crashes with the following error:

```
[06:07:13 PM]: OS: linux2, 8 cores, ~ 66 GB RAM. Python: 2.7.12
[06:07:14 PM]: Running funannotate v0.5.3
[06:07:25 PM]: AUGUSTUS (3.1.0) detected, version seems to be compatible with BRAKER1 and BUSCO
[06:07:41 PM]: Using existing transcript evidence alignments
[06:07:42 PM]: Mapping proteins to genome using tBlastn/Exonerate
[06:07:42 PM]: Using existing protein evidence alignments
[06:07:59 PM]: Running BUSCO to find conserved gene models for training Augustus
[06:23:36 PM]: BUSCO predictions complete, now formatting for EVM
[06:24:34 PM]: 1,245 total gene models from EVM
[06:24:34 PM]: Checking BUSCO protein models for accuracy
-------------------------------------------------------
Traceback (most recent call last):
  File "~/.linuxbrew/Cellar/funannotate/0.5.3/libexec/bin/funannotate-predict.py", line 759, in <module>
    total = lib.countGFFgenes(busco_final)
  File "~/.linuxbrew/Cellar/funannotate/0.5.3/libexec/lib/library.py", line 347, in countGFFgenes
    with open(input, 'rU') as f:
IOError: [Errno 2] No such file or directory: '~/xanthoria_reannotate/predict_misc/busco.final.gff3'
```

I couldn't find any reported issues with that specific error, so I'm a bit at a loss. Anyone having encountered this before?

**Comment by nextgenusfs** [comment]
I haven't seen this one before.  Is there anymore information in the logfiles?  The 'busco.log' file in the 'logfiles' is for your first BUSCO2 genome search, it seems like that completed successfully.  After EVM runs, the output is then check again using BUSCO2 proteome search, that log file is actually then appended to 'busco.log' - so check that and see if there is anymore information.  If BUSCO2 proteome ran correctly, then the output file should be a file containing protein models in 'predict_misc' called 'busco.evm.proteins.fa'.  If that file is present but busco.final.gff3 is not, then the conversion script has failed for some reason.

**Comment by gedankenstuecke** [comment]
Okay, so I'm a bit closer to the issue I think (different genome now, but same error, as I deleted the old output already): 

```
INFO	****** Phase 2 of 2, predictions using species specific training ******
INFO	****** Step 1/3, current time: 02/08/2017 01:07:49 ******
INFO	Extracting missing and fragmented buscos from the ancestral_variants file...
WARNING	The busco id(s) ['EOG09264LBC', 'EOG092628A0', 'EOG09264KTU', 'EOG09260TDY', 'EOG09262WSH', 'EOG09262XMN', 'EOG09265E6R', 'EOG09262ZZ8', 'EOG09265QTV', 'EOG09261PUF', 'EOG09260J8F', 'EOG09261666', 'EOG09260OZU', 'EOG09261CQG', 'EOG092656JA', 'EOG0926079Q', 'EOG09265822', 'EOG09261I8J', 'EOG09260PJ9', 'EOG0926407T', 'EOG09260OQ8', 'EOG09262VOC', 'EOG092646C6', 'EOG09265JNA', 'EOG092625P1', 'EOG09260TUT', 'EOG092632FC', 'EOG09264NC7', 'EOG0926423H', 'EOG09264FYY', 'EOG092634MM', 'EOG09265K60', 'EOG09260FX0', 'EOG09260KM4', 'EOG09264QRY', 'EOG09261EMF', 'EOG09265AT5', 'EOG092638CT', 'EOG09260LBU', 'EOG09265BCT', 'EOG09265PWR', 'EOG092652KR', 'EOG09261UWT', 'EOG092638EN', 'EOG0926386D', 'EOG09262BVA', 'EOG09265MAN', 'EOG09262HP3', 'EOG09263X4B', 'EOG09263KVG', 'EOG092645MK', 'EOG09264XUV', 'EOG09264B74', 'EOG09263IMF', 'EOG092644TW', 'EOG09262YP5', 'EOG09263L52', 'EOG09264G4X', 'EOG09263OXI', 'EOG09264HX6', 'EOG09263MR4', 'EOG092644DY'] were not found in the ancestral_variants file
INFO	Running tblastn, writing output to ~/busco/run_umbilicaria_muehlenbergii_new/blast_output/tblastn_umbilicaria_muehlenbergii_new_missing_and_frag_rerun.tsv...
```

This seems to be off already, because the output should be written to ~/umbilicaria_new/predict_misc/busco/run_umbilicaria_muehlenbergii_new/blast_output/tblastn_umbilicaria_muehlenbergii_new_missing_and_frag_rerun.tsv? But that just seems to be an logging artifact, as the file is in the correct directory. 

Then it goes on: 

```
INFO	[tblastn]	Warning: [tblastn] Query is Empty!
INFO	Getting coordinates for candidate regions...
INFO	****** Step 2/3, current time: 02/08/2017 01:07:50 ******
INFO	Training Augustus using Single-Copy Complete BUSCOs:
INFO	02/08/2017 01:07:50 =>	Converting predicted genes to short genbank files...
INFO	02/08/2017 01:08:53 =>	All files converted to short genbank files, now running the training scripts...
INFO	Pre-Augustus scaffold extraction...
INFO	Re-running Augustus with the new metaparameters, number of target BUSCOs: 62
INFO	02/08/2017 01:08:58 =>	0% of predictions performed (0 to be done)
INFO	02/08/2017 01:08:58 =>	100% of predictions performed
INFO	Extracting predicted proteins...
INFO	****** Step 3/3, current time: 02/08/2017 01:08:58 ******
INFO	Running HMMER to confirm orthology of predicted proteins:
INFO	02/08/2017 01:08:58 =>	0% of predictions performed (0 to be done)
INFO	02/08/2017 01:08:58 =>	100% of predictions performed
INFO	Results:
INFO	C:95.3%[S:94.8%,D:0.5%],F:2.4%,M:2.3%,n:1312
INFO	1250 Complete BUSCOs (C)
INFO	1244 Complete and single-copy BUSCOs (S)
INFO	6 Complete and duplicated BUSCOs (D)
INFO	31 Fragmented BUSCOs (F)
INFO	31 Missing BUSCOs (M)
INFO	1312 Total BUSCO groups searched

INFO	BUSCO analysis done with WARNING(s). Total running time: 1573.7398591 seconds
INFO	Results written in ~/busco/run_umbilicaria_muehlenbergii_new/
```

Again, the same wrong directory. But the actual output is written in the right directory:

```
INFO	****************** Start a BUSCO 2.0 analysis, current time: 02/08/2017 01:13:03 ******************
INFO	The lineage dataset is: dikarya_odb9 (eukaryota)
INFO	Mode is: proteins
INFO	To reproduce this run: python ~/.linuxbrew/Cellar/funannotate/0.5.3/libexec/util/funannotate-BUSCO2.py -i ~/umbilicaria_new/predict_misc/busco.evm.proteins.fa -o umbilicaria_muehlenbergii_new -l ~/.linuxbrew/Cellar/funannotate/0.5.3/libexec/DB/dikarya/ -m proteins -c 8 -sp anidulans
INFO	Check dependencies...
INFO	Check input file...
ERROR	Please provide a protein file as input

ERROR	BUSCO analysis failed !
INFO	Check the logs, read the user guide, if you still need technical support, then please contact mailto:support@orthodb.org
```

I've checked. The file `~/umbilicaria_new/predict_misc/busco.evm.proteins.fa` does exist, but it's empty. So somewhere the generation of this file seems to be the culprit. I'm currently in the process of upgrading funannotate to the latest version (let's see whether the update w/ Linuxbrew works out) to see whether this is maybe fixed in the latest version.

**Comment by gedankenstuecke** [comment]
Ok, updating to 0.5.5 doesn't work with Linuxbrew, because for whatever reason it tries to reinstall gmap-gsnap (which is actually already installed through Linuxbrew) and the latest gmap-gsnap on Linuxbrew does not compile on Linux it seems: https://github.com/Homebrew/homebrew-science/pull/5110

So I'm a bit at a loss again right now. 😉

**Comment by nextgenusfs** [comment]
You can upgrade I think by ignoring dependencies you can upgrade:
```
brew upgrade --ignore-dependencies funannotate
```

Then run the `funannotate setup —db` which should find your previous install and softlink the DB folder.

**Comment by nextgenusfs** [comment]
What is your command for funannotate, does it contain the ~ character?

You can upgrade I think by ignoring dependencies you can upgrade:
```
brew upgrade --ignore-dependencies funannotate
```
Then run the `funannotate setup —db` which should find your previous install and softlink the DB folder.

**Comment by gedankenstuecke** [comment]
Ah, I tried `brew upgrade funannotate --ignore-dependencies` and this didn't work. But I "fixed" that problem now by just cloning the repo and doing the `setup.sh` again. So it's now running in the latest version. 

I gave the absolute paths for all input-files, just to save some space here I shortened them to `~`. 

Full command used: 

`funannotate predict -i ~/funannotate_input/Xanpa2_AssemblyScaffolds.fasta -o ~/xanthoria_reannotate --species 'Xanthoria parietina' --transcript_evidence ~/funannotate_input/Trinity.All.fasta --protein_evidence ~/funannotate_input/protein_evidence.fa`, with `~` being `/home/bastian` in all cases.

**Comment by gedankenstuecke** [comment]
(Should have checked my jobs before sending the comment). So the error stays the same when running `v0.5.7`.

**Comment by nextgenusfs** [comment]
Seems like a path problem confusion bug, can you try to just give the output folder like so and see if that works?:
```
funannotate predict -i /home/bastian/funannotate_input/Xanpa2_AssemblyScaffolds.fasta \
-o xanthoria_reannotate --species 'Xanthoria parietina' \
--transcript_evidence /home/bastian/funannotate_input/Trinity.All.fasta \
--protein_evidence /home/bastian/funannotate_input/protein_evidence.fa
```

**Comment by gedankenstuecke** [comment]
Ok, will give it a try and keep you posted. Thanks so much for the support ❤️

**Comment by gedankenstuecke** [comment]
Mh, unfortunately the error persists despite giving it just the way you did.

**Comment by nextgenusfs** [comment]
Hmm, not sure. I can't get the error to reproduce locally.  How about a simpler version, I've put another fasta file in the `sample_data` directory called `genome4.fasta`.  It is large enough that can be used to run the BUSCO2 method and is what I use for testing that method.  So do a `git pull` and then  from the `sample_data` folder can you try this command:
```
funannotate predict -i genome4.fasta -s "Genome four" -o genome4 --name GN4_ \
--protein_evidence proteins.fa --transcript_evidence transcripts.fa \
--busco_seed_species botrytis_cinerea --cpus 6
```

**Comment by gedankenstuecke** [comment]
So I started it with this command from the `sample_data` directory and the error stays the same. If one does a `ls -lah` in the `predict_misc` folder this is the output: 

```
total 33M
-rw-r--r-- 1 bastian users  180K Feb 23 15:13 blat.filt.psl
-rw-r--r-- 1 bastian users  208K Feb 23 15:13 blat.psl
-rw-r--r-- 1 bastian users  180K Feb 23 15:13 blat.sort.psl
-rw-r--r-- 1 bastian users  180K Feb 23 15:13 blat.sort.tmp.psl
drwxr-xr-x 4 bastian users  4.0K Feb 23 15:29 busco
-rw-r--r-- 1 bastian users  178K Feb 23 15:30 busco_augustus.gff3
-rw-r--r-- 1 bastian users  211K Feb 23 15:30 busco_augustus.tmp
-rw-r--r-- 1 bastian users  227K Feb 23 15:30 busco.evm.gff3
-rw-r--r-- 1 bastian users     0 Feb 23 15:30 busco.evm.proteins.fa
-rw-r--r-- 1 bastian users     0 Feb 23 15:30 busco_genemark.gff3
-rw-r--r-- 1 bastian users  178K Feb 23 15:30 busco_predictions.gff3
drwxr-xr-x 2 bastian users  4.0K Feb 23 15:30 busco_proteins
-rw-r--r-- 1 bastian users     0 Feb 23 15:30 busco_proteins.gff3
-rw-r--r-- 1 bastian users  9.4K Feb 23 15:29 buscos.bed
-rw-r--r-- 1 bastian users     0 Feb 23 15:30 busco_transcripts.gff3
-rw-r--r-- 1 bastian users    99 Feb 23 15:30 busco_weights.txt
drwxr-xr-x 9 bastian users  4.0K Feb 23 15:30 EVM_busco
-rw-r--r-- 1 bastian users  727K Feb 23 15:14 exonerate.out
drwxr-xr-x 6 bastian users  4.0K Feb 23 15:19 genemark
-rw-r--r-- 1 bastian users 1002K Feb 23 15:19 genemark.evm.gff3
-rw-r--r-- 1 bastian users  1.1M Feb 23 15:19 genemark.gff
-rw-r--r-- 1 bastian users 1002K Feb 23 15:19 genemark.temp.gff
drwxr-xr-x 3 bastian users  4.0K Feb 23 15:13 genome
-rw-r--r-- 1 bastian users  4.0M Feb 23 15:04 genome.fasta
-rw-r--r-- 1 bastian users  4.1M Feb 23 15:12 genome.softmasked.fa
-rw-r--r-- 1 bastian users  6.8K Feb 23 15:13 gmap-build.log
-rw-r--r-- 1 bastian users  253K Feb 23 15:13 gmap-map.log
-rw-r--r-- 1 bastian users  950K Feb 23 15:18 gmhmm.mod
-rw-r--r-- 1 bastian users  327K Feb 23 15:13 hints.E.gff
-rw-r--r-- 1 bastian users  483K Feb 23 15:14 hints.PE.gff
-rw-r--r-- 1 bastian users  156K Feb 23 15:14 hints.P.gff
-rw-r--r-- 1 bastian users  152K Feb 23 15:14 protein_alignments.gff3
-rw-r--r-- 1 bastian users  4.1M Feb 23 15:13 proteins.combined.fa
drwxr-xr-x 2 bastian users  4.0K Feb 23 15:12 RepeatMasker
-rw-r--r-- 1 bastian users  140K Feb 23 15:12 repeatmasker.gff3
drwxr-xr-x 3 bastian users  4.0K Feb 23 15:11 RepeatModeler
-rw-r--r-- 1 bastian users   822 Feb 23 15:11 repeatmodeler.lib.fa
-rw-r--r-- 1 bastian users  457K Feb 23 15:13 transcript_alignments.gff3
-rw-r--r-- 1 bastian users   12M Feb 23 15:12 transcripts.combined.fa
```

So the `busco.evm.proteins.fa` stays empty. Is there a way to manually run the subroutine that should generate it in order to see what's happening there?

**Comment by nextgenusfs** [comment]
OK, so at least narrowed down to the the BUSCO2 proteome validation I guess.  As it looks like the busco.evm.gff3 file is there.  So the next step is to convert those GFF3 gene models into proteins, it does this by using a script from EvidenceModeler. 

The command that generates the `busco.evm.proteins.fa` is as follows, see if that runs and/or gives you an error:
```
$EVM_HOME/EvmUtils/gff3_file_to_proteins.pl predict_misc/busco.evm.gff3 predict_misc/genome.softmasked.fa
```

**Comment by gedankenstuecke** [comment]
Now we're getting somewhere, apparently my perl DB module doesn't place nice!

```
perl: symbol lookup error: /home/bastian/perl5/perlbrew/perls/perl-5.24.0-thread-multi/lib/site_perl/5.24.0/x86_64-linux-thread-multi/auto/DB_File/DB_File.so: undefined symbol: db_version
```

**Comment by nextgenusfs** [comment]
Okay good.  I've tried to improve the error capturing, but obviously not perfect still.  Can you confirm in the `logfiles/funannotate-predict.log` that it did not capture the error?  For example, mine ran correctly so I don't get an error and looks like this:
```
2017-02-22 07:34:40,470: 256 total gene models from EVM
2017-02-22 07:34:40,470: Checking BUSCO protein models for accuracy
2017-02-22 07:34:40,470: /usr/local/opt/evidencemodeler/EvmUtils/gff3_file_to_proteins.pl /Users/jon/funannotate/sample_data/genome4/predict_misc/busco.evm.gff3 /Users/jon/funannotate/sample_data/genome4/predict_misc/genome.softmasked.fa
2017-02-22 07:34:56,771: 256 gene models validated, using for training Augustus
```
The desired behavior, would be for the log file to capture the perl error that you got above in the log file and it *should* be then in the log file.  But I'm guessing it's not working the way I want it to.

**Comment by gedankenstuecke** [comment]
Sure, so my logfile ends like this: 

```
2017-02-23 15:30:23,223: 249 total gene models from EVM
2017-02-23 15:30:23,225: Checking BUSCO protein models for accuracy
2017-02-23 15:30:23,225: /home/bastian/.linuxbrew/opt/evidencemodeler/EvmUtils/gff3_file_to_proteins.pl /home/bastian/bin/test/funannotate/sample_data/genome4/predict_misc/busco.evm.gff3 /home/bastian/bin/test/funannotate/sample_data/genome4/predict_misc/genome.softmasked.fa
```

and ends there, without any error message. And you don't happen to have an idea how I can make DB_File work on a Ubuntu 16.x system, do you? Apparently the libdb version supplied by Ubuntu is too new and can't be used with the DB_File module?

**Comment by nextgenusfs** [comment]
I don't have any solutions other than googling... I'm sure you found this: http://stackoverflow.com/questions/38617400/error-on-using-perl-db-file-module-in-ubuntu

Or search for a sudo-apt debian package?  Although that probably won't work with the brewed Perl.

**Comment by gedankenstuecke** [comment]
Yeah, the problem seems to be that the older libdb isn't supported by the latest Ubuntu releases, so already getting that installed somehow will be an issue I fear. But in any case, thanks so much again for the support. I'll have a look in how to solve the issue then! :-)

**Comment by nextgenusfs** [comment]
I will add the DB_File module to the `funannotate setup --dep` check, in case others have this problem.  Hopefully you can get it working!
