### ISSUE TITLE
Preoblems with Signal IP and funannotate Annotate

### ISSUE THREAD

**Issue by vcastroagudin** [nextgenusfs/funannotate#454]
I have some issue with SignalIP, for somereason, despite having the appropriate licence for SiganlIP and having the program in the path, funannotate annotate is not working with SignalIP.

I got this ifo in the annotate log:

"0 secretome and 3,017 transmembane annotations added"

And it does not male biological sense at all!

Also the signalip.result.txt file in the annoate_mics folder is empty.

Is there any log file somewhere I could check to try to find out which is the problem?

Thank you in advance,

Vanina

**Comment by nextgenusfs** [comment]
You can try to run the signalP commands from the logfile and see if you get errors. But depending on the version of signalP you might need to manually adjust the Perl script to show it where the decodehmm binary is located (v4.1 and below). I have not used version 5 as we don't have a license at work and I only have a Mac at home where it doesn't run for me. Secretion signals are calculated from both phobius and signalP. So likely this result is a parsing error of the failed signalP run, it gets transmembrane data from phobius and should be getting secretion signal from both phobius and signalP.

**Comment by mswyers** [comment]
Just as an added note, I've noticed when passing my samples through the pipeline I end up with very long assembly file names, and therefore very long predict/ folder names. SignalP seems to have a parsing issue with names over a certain character limit, and simply shortening my predict/ folder names caused things that previously would fail at the signalP stage of annotation to pass.

**Comment by nextgenusfs** [comment]
So you ran funannotate with the output/out option as `-o pos-p1-G07.mask.assembly.signalp.outsta.predict`? Interesting that the length of the string would matter as long as its a valid path to the folder?

**Comment by mswyers** [comment]
So what I had put together was a for loop setup for the clean/sort/mask:

```
for file in *assembly.fasta; do
	cleanfile=${file/assembly/clean}
	sortfile=${cleanfile/clean/sort}
	maskfile=${sortfile/sort/mask}
	
	funannotate clean -i $file -o $cleanfile;
	funannotate sort -i $cleanfile -o $sortfile;
	funannotate mask -i $sortfile -o $maskfile -s anidulans;
	
	done 
```

The output of this was a file called sample.mask.assembly.fasta, running predict on all of these gave me a folder called sample.mask.assembly.predict/

For some reason signalP didn't like this, I think it has to do with me using "." to separate out my steps and how signalP stores it's temp files.

**Comment by nextgenusfs** [comment]
I typically do these things with a tsv/csv mapping file of sorts, ie something like generate a file that is tab delimited file:
```
assembly-name.fasta    shortname    genus species training_species
assembly-name2.fasta   shortname2   genus species training_species2
```
Then you can use bash to read that file into individual variables, ie:
```
while read genome name genus species training; do 
    funannotate clean -i $genome -o $name.clean.fasta;
    funannotate sort -i $name.clean.fasta -o $name.sort.fasta;
    funannotate mask -i $name.sort.fasta -o $name.softmasked.fasta;
    funannotate predict -i $name.softmasked.fasta -o $name\_funannotate --busco_seed_species $training -s '"'$genus $species'"';
    done; < name_of_tsv_mapping_file.txt
```
Then each genome from funannotate will have the simple output name of whatever you have in column2+_funannotate. 

You could use comma separated delimiter similarly like:
```
IFS=','; while read ......; do ....; done < inputfile.csv
```
You can play around with the proper syntax by just echoing the variables in bash to make sure doing what you want it to.
