### ISSUE TITLE
Hisat2 2.2.0 not being recognized

### ISSUE THREAD

**Issue by mswyers** [nextgenusfs/funannotate#456]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
Funannotate fails to recognise hitsat2 ver 2.2.0 (latest) and running `$funannotate check` shows the package as not being installed unless you manually downgrade to 2.1.0 via

`conda install hisat2=2.1.0`

**What command did you issue?**
```
funannotate check
-------------------------------------------------------
Checking dependencies for 1.7.4
-------------------------------------------------------
To print all dependencies and versions: funannotate check --show-versions

You are running Python v 2.7.15. Now checking python packages...
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
All 27 Perl modules installed


Checking Environmental Variables...
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
	ERROR: emapper.py not installed

```

I haven't run anything new to see if this actually affects running, but noticed this while putting a fresh install on a new machine.

Specifying the previous version fixes this from coming up in the check.

**Comment by nextgenusfs** [comment]
Okay, it's probably just the check command, ie they must have changed the output location of how they check for version. As long as hisat2 is in path I don't think will effect the run.

**Comment by mswyers** [comment]
Great, just wanted to put it up in case anyone had any issues revolving around this dependency.
