### ISSUE TITLE
docker container for funannotate?

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/funannotate#46]
I don't have experience with docker, but I will look into making a container if people are interested.

**Comment by simas232** [comment]
Would be nice to have a container for funannotate, since the pipeline is very well structured, easy to use and really useful when preparing fungal genomes for NCBI submission or doing gene prediction right from assembled genomes.

**Comment by nextgenusfs** [comment]
Docker container is now built, instructions are located https://github.com/nextgenusfs/funannotate/wiki/funannotate-on-Docker
