### ISSUE TITLE
GeneMark-ES not working

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/funannotate#461]
Hi, 

I have just installed funannotate with Conda and currently, all dependencies seem installed (except for hisat2 and ete3). However, I don't know if GeneMark is actually working. The path is set, and gmes_petap.pl seems to be installed (and in the path). When I run check_intall.bash, it returns:

checking GeneMark-ES installation
Error, installation key is missing or expired

However, .gm_key is new and located in the home directory. 

 Also, if I try to run GeneMark outside funannotate it fails, see log file attached. 
[gmes.log](https://github.com/nextgenusfs/funannotate/files/5030358/gmes.log)

I am running this from an Ubuntu system.

Does anyone have any idea on to fix this? Thank you!

L. 

 -  output of `funannotate check --show-versions`
-------------------------------------------------------
Checking dependencies for 1.8.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.24.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.302
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.30
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/aberas2/funannotate_db
$PASAHOME=/home/aberas2/miniconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/aberas2/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/aberas2/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/aberas2/miniconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/aberas2/software/gmes_linux64
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: 2.0.1b-2-g816e190
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.59_lic
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
signalp: 4.1
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: ete3 not installed
	ERROR: hisat2 not installed

**Comment by hyphaltip** [comment]
Hmm, sometimes a highly fragmented assembly fails w genemark. I am having trouble seeing what is triggering the error in your genemark log. Sometimes i do training outside funannotate with only the biggest contigs (> 100kb perhaps?) - but depends on your assembly quality. 

I think this might be red herring? @nextgenusfs might know have to check what triggers that error.
```
checking GeneMark-ES installation
Error, installation key is missing or expired
```

**Comment by hyphaltip** [comment]
Tho it is warning on the gmhme3 I can't tell what the warning is signalling.

```
/home/aberas2/software/gmes_linux_64/gmes_petap.pl : [Wed Aug  5 14:10:56 2020] warning on: /home/aberas2/software/gmes_linux_64/gmhmme3  -m /home/aberas2/Currie-Lab/ICBG1054/genemark/run/ES_ini/es_ini.mod   -f tr   -o /home/aberas2/Currie-Lab/ICBG1054/genemark/run/ES_A_1/hmmout/dna.fa_55.out  /home/aberas2/Currie-Lab/ICBG1054/genemark/data/training/dna.fa_55
```

**Comment by hyphaltip** [comment]
Are you able to run any of the funannotate test to make sure genemark is working in general?

**Comment by nextgenusfs** [comment]
`gmes_petap.pl: 4.59_lic` seems like a newer version than what I've run locally.  Could be related to that I suppose.

**Comment by hyphaltip** [comment]
yeah I'm running 4.38 right now.

**Comment by nextgenusfs** [comment]
But as @hyphaltip suggests, see if running `funannotate test -t predict` works or if that gives you errors.  The code will attempt to fix GeneMark results if it fails by running the `gmhmme3` steps manually.  But this issue seems like more of a general GeneMark installation problem -- you might get some help by reaching out to the GeneMark developers.

**Comment by aberaslop** [comment]
Hi! Thank you so much for your answers. Thank you for the info on GeneMark, I will try to install it anyway, but if I can't, I will run the analysis without it.

I have encountered a problem when running funannotate test, though. It errors with this message:

[08/06/20 10:00:29]: Directory not copied. Error: [Errno 2] No such file or directory: '/data1/home/aberas2/funannotate_db/trained_species/saccharomyces/augustus'

(I have attached the full log file)
[funannotate-predict.log](https://github.com/nextgenusfs/funannotate/files/5035479/funannotate-predict.log)


I realized that the program is looking for the files in a directory that no longer exists. Our server was recently updated and all our files were backed up. Funannotate was installed in that server and /data1/home/aberas2/funannotate_db/trained_species/saccharomyces/augustus makes sense in that scenario. However, this directory does not exist anymore and I have installed a new version of funannotate in the newly revamped server. Could these two versions of funannotate be interacting with each other? My current paths would look like: /home/aberas2/... (no /data1/)

Thank you!

L.

**Comment by hyphaltip** [comment]
I see these errors when checking with `funannotate check`  as well as some YAML errors - I would try and run gmes_petap.pl alone - I also went in to the genemark folder and ran `change_path_in_perl_scripts.pl "/usr/bin/env perl"` which fixed issues because the perl I needed to run was in the conda env not in the system (so the necessary perl modules were there). 

Then I made sure I could run all the Perl libs 
```
Can't locate Logger/Simple.pm in @INC (you may need to install the Logger::Simple module) (@INC contains: /opt/linux/centos/7.x/x86_64/pkgs/PASA/2.4.1/PerlLib /opt/linux/centos/7.x/x86_64/pkgs/tRNAscan-SE/1.3.1/lib/perl /opt/linux/centos/7.x/x86_64/pkgs/tRNAscan-SE/1.3.1/bin /bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/lib/site_perl/5.26.2/x86_64-linux-thread-multi /bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/lib/site_perl/5.26.2 /bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/lib/5.26.2/x86_64-linux-thread-multi /bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/lib/5.26.2 .) at /opt/linux/centos/7.x/x86_64/pkgs/genemarkESET/4.59_lic/gmes_petap.pl line 78.
BEGIN failed--compilation aborted at /opt/linux/centos/7.x/x86_64/pkgs/genemarkESET/4.59_lic/gmes_petap.pl line 78.
	ERROR: gmes_petap.pl found but error running gmes_petap.pl
```

**Comment by nextgenusfs** [comment]
It's still hard for me to understand why they haven't changed the shebang line to `/usr/bin/env perl` by default -- there is no reason to use the system perl as default when you require several modules....

**Comment by aberaslop** [comment]
I run 'which perl', and the terminal showed: '/home/aberas2/miniconda3/envs/funannotate/bin/perl'. So that is what I changed the shebang to. Would this be a problem?

**Comment by nextgenusfs** [comment]
It will be if you build a new environment in Conda for example, `/usr/bin/env perl` is a better choice as it will use the perl in the current environment.

**Comment by aberaslop** [comment]
Great, thank you, Jon!!
