### ISSUE TITLE
RepeatMasker

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/funannotate#466]
Hi!

I have run RepeatModeler outside of funannotate, and now I am successfully running funannotate mask:

funannotate mask -i ICBG1054-clean-sort.fa -o ICBG1054-clean-sort-masked.fa -m repeatmasker -s fungi -l repeatmodeler/RM_25243.MonAug100654572020/consensi.fa.classified --cpus 16 --debug

I haven't been able to install the RepBase database. Would this still be ok to soft mask the genome and proceed with funannotate predict?

Thank you!

L.

**Comment by nextgenusfs** [comment]
You can certainly run it and see what sort of masking percentage you get and more/less guess if that is reasonable or not. Probably most fungi are in the range of 6-40% repeats. 

There are some other ways to repeat mask, but in terms of adding something back into funannotate I was waiting/hoping that somebody would either curate a public repeat database or write some newer software to do this without the RepBase requirement. Jason @hyphaltip and I have talked about some potential options, but so far no momentum on a solution that I'm aware of.  I tested out the RED repeat masker awhile back and wrote a wrapper -- https://github.com/nextgenusfs/redmask -- but it seemed to not perform robustly for different species. You could try that, it doesn't require any other dependencies, but the parameters are tricky to work out. 

But to be clear -- your annotation will still run with funannotate -- and based on how we filter out repeats, it may still perform reasonably.  And the default now is simple to run `tantan`, which probably isn't the best solution, but it actually does an okay job at masking the simple repeats.

**Comment by aberaslop** [comment]
Hi Jon,

Thank you so much! I did so and repeat masker reports around 15% repeats. It seems this is reasonable. Thanks again for all your help!

L.

**Comment by xonq** [comment]
I've used the Dfam database which is configured by default these days for repeatmasker/modeler, etc. From the sample of a couple fungi I've tested, I've gotten almost the same masking % referencing Dfam as I do referencing an older version of the RepBase library.
