### ISSUE TITLE
Hisat2 Installation Error

### ISSUE THREAD

**Issue by wywye** [nextgenusfs/funannotate#469]
Hello,

Thank you for writing and maintaining this tool! I am running into issues installing Hisat2. I used the conda mediated installation command provided from `https://funannotate.readthedocs.io/en/latest/conda.html` however it does not seem to work. I have also tried to install hisat2 in a separate conda install. The cluster that I am using already has hisat2 installed in a shared apps directory, is there anyway to pass a different hisat2 path to funannotate?

`-------------------------------------------------------
Checking dependencies for 1.8.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 2.2.5
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.24.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/wyatte/funannotate_db
$PASAHOME=/home/wyatte/.conda/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/wyatte/Trinity-v2.5.1
$EVM_HOME=/home/wyatte/.conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/wyatte/.conda/envs/funannotate/config/
$GENEMARK_PATH=/home/wyatte/gmes_petap
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: 2.0.1
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.33
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.8-internal
kallisto: 0.46.2
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.15.0
samtools: samtools 1.10
signalp: 4.1
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: hisat2 not installed`

Different issue - I am running the following command:
`/usr/bin/time -v funannotate train -i C_reinhardtii.fa -o fun --left $DAY1 $NIGHT1 --right $DAY2 $NIGHT2 --stranded RF --species "Chlamydomonas_reinhardtii" --cpus 24 --TRINITYHOME /home/wyatte/.conda/envs/funannotate/opt/trinity-2.8.5` 
and get the following error in `trinity_normalization.PE.log`:
`-prepping seqs
Converting input files. (both directions in parallel)CMD: seqtk-trinity seq -r -A <(gunzip -c /panfs/biopan03/home/wyatte/Chlamydomonas_reinhardtii/funannotat_test/fun/training/trimmomatic/trimmed_left.fastq.gz) >> left.fa
CMD: seqtk-trinity seq -A <(gunzip -c /panfs/biopan03/home/wyatte/Chlamydomonas_reinhardtii/funannotat_test/fun/training/trimmomatic/trimmed_right.fastq.gz) >> right.fa
Error, not recognizing read name formatting: [SRR2132402.1]

If your data come from SRA, be sure to dump the fastq file like so:

	SRA_TOOLKIT/fastq-dump --defline-seq '@$sn[_$rn]/$ri' --split-files file.sra 

Error, not recognizing read name formatting: [SRR2132402.1]

If your data come from SRA, be sure to dump the fastq file like so:

	SRA_TOOLKIT/fastq-dump --defline-seq '@$sn[_$rn]/$ri' --split-files file.sra 

gzip: 
gzip: stdout: Broken pipe
stdout: Broken pipe
Thread 2 terminated abnormally: Error, cmd: seqtk-trinity seq -A <(gunzip -c /panfs/biopan03/home/wyatte/Chlamydomonas_reinhardtii/funannotat_test/fun/training/trimmomatic/trimmed_right.fastq.gz) >> right.fa died with ret 512 at /home/wyatte/.conda/envs/funannotate/opt/trinity-2.8.5/util/insilico_read_normalization.pl line 788.
Thread 1 terminated abnormally: Error, cmd: seqtk-trinity seq -r -A <(gunzip -c /panfs/biopan03/home/wyatte/Chlamydomonas_reinhardtii/funannotat_test/fun/training/trimmomatic/trimmed_left.fastq.gz) >> left.fa died with ret 512 at /home/wyatte/.conda/envs/funannotate/opt/trinity-2.8.5/util/insilico_read_normalization.pl line 788.
Error, conversion thread failed at /home/wyatte/.conda/envs/funannotate/opt/trinity-2.8.5/util/insilico_read_normalization.pl line 336.`

The `funannotate-train.log` file contains the following error:
`[08/25/20 09:48:33]: Read normalization failed, fun/training/normalize/left.norm.fq does not exist.`

Do you have any recommendations to resolve this error as well?

Thank you for your time and help!

**Comment by nextgenusfs** [comment]
You just need to have `hisat2` be in the PATH of your environment, doesn't need to be installed via conda. So symlink it into that environment should be sufficient (note you'll also need `hisat2-build`). 

The second error should be somewhat obvious -- TRINITY is sensitive to the FASTQ headers, these appear to not be in the format that it wants. So if they are SRA reads, then just re-download with the command it tells you to.

**Comment by hyphaltip** [comment]
It doesn't seem like it is in your path even though it is installed on the system? If the following doesn't work you need to adjust your PATH or symlink the exe into a folder in your PATH.
```
which hisat2
```
For your RNASeq messages - did you follow the directions provided in the log you posted? you need to dump your fastq so that it has /1 and /2 trailing the read name. Do this by redumping your fastq or you can write a short perl/sed/python to fix the name.
```
Error, not recognizing read name formatting: [SRR2132402.1]

If your data come from SRA, be sure to dump the fastq file like so:

SRA_TOOLKIT/fastq-dump --defline-seq '@$sn[_$rn]/$ri' --split-files file.sra 
```

**Comment by wywye** [comment]
Thank you so much for your timely responses! Sorry I don't have much experience setting up software. I have a path in my .bashrc to link hisat2 or do I need to put it into the path to my conda environment?

**Comment by wywye** [comment]
I had to change my Hisat2 path from `~/.conda/envs/funannotate/bin/hisat2` to `/opt/apps/hisat2-2.0.5/hisat2` it seems that funannotate did not like the conda installed version. The new fastq-dump command seemed to work as well. Thank you for the help!

**Comment by hyphaltip** [comment]
yah! glad you solved it
