### ISSUE TITLE
Cazyme annotation - all the same loci?

### ISSUE THREAD

**Issue by vcastroagudin** [nextgenusfs/funannotate#471]
Hello,

I notice a problem with the output of the annotation after the comparison with dbCAN databases. The output end with the same loci name in all annotations. It is hard to explain... see attachment
[annotations.dbCAN.txt](https://github.com/nextgenusfs/funannotate/files/5152822/annotations.dbCAN.txt)
. No error message was found in the annotation log.

Any help will be appreciated

**Comment by nextgenusfs** [comment]
What version are you using? I seem to recall fixing this at some point.

**Comment by vcastroagudin** [comment]
This is what I am using:

-------------------------------------------------------
Checking dependencies for 1.7.4
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.24.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/home/vanina/funannotate_db
$PASAHOME=/home/vanina/conda/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/vanina/conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/vanina/conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/vanina/conda/envs/funannotate/config/
$GENEMARK_PATH=/home/vanina/genemark
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: 1.0.3
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.58_lic
hisat2: 2.2.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.470 (2020/Jun/20)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
signalp: 4.1
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39

**Comment by nextgenusfs** [comment]
What version of funannotate -- the bioconda v1.7.4? or have you at some point upgraded to using the master (somewhat confusing as it will say v1.8.0, but there are lots of changes as I haven't tagged a release yet).

**Comment by nextgenusfs** [comment]
If you are running v1.8.0 -- then upgrade to latest and let me know if still a problem, ie `python -m pip install git+https://github.com/nextgenusfs/funannotate.git`

**Comment by vcastroagudin** [comment]
yes updated using the master, after some previous changes you did like 4 - 6 weeks ago...

**Comment by vcastroagudin** [comment]
I will check, and write back  to you. Thanks.

**Comment by nextgenusfs** [comment]
Any update here? Assuming installed new version fixed the issue?
