### ISSUE TITLE
error with bamtools/augustus installation

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#48]
The error appears as following. Any suggestions? Thank you.... I can install augustus myself, but how to integrate it to funannotate?

==> make INCLUDES=/home/manager/.linuxbrew/opt/bamtools/include/bamtools
Last 15 lines from /home/manager/.cache/Homebrew/Logs/augustus/02.make:
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl]+0x3e): undefined reference to `boost::iostreams::detail::gzip_header::reset()'
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl]+0x47): undefined reference to `boost::iostreams::detail::gzip_footer::reset()'
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl]+0x60): undefined reference to `boost::iostreams::detail::gzip_header::process(char)'
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl]+0x10d): undefined reference to `boost::iostreams::detail::gzip_footer::process(char)'
genbank.o: In function `long boost::iostreams::basic_gzip_decompressor<std::allocator<char> >::read<boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> > >(boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> >&, char*, long)':
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x7b): undefined reference to `boost::iostreams::detail::gzip_header::reset()'
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x83): undefined reference to `boost::iostreams::detail::gzip_footer::reset()'
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0xc1): undefined reference to `boost::iostreams::detail::gzip_header::process(char)'
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x1c6): undefined reference to `boost::iostreams::detail::gzip_footer::process(char)'
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x288): undefined reference to `boost::iostreams::detail::gzip_header::reset()'
genbank.cc:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x290): undefined reference to `boost::iostreams::detail::gzip_footer::reset()'
collect2: error: ld returned 1 exit status
make[1]: *** [etraining] Error 1
make[1]: Leaving directory `/tmp/augustus-20170313-27615-16gksyr/augustus-3.2.2/src'
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

These open issues may also help:
augustus: undefined reference to BamTools::BamAlignment::RemoveTag https://github.com/Homebrew/homebrew-science/issues/3929
augustus: Build a bottle for Linuxbrew: undefined reference to `boost::iostreams::zlib::okay' https://github.com/Homebrew/homebrew-science/pull/5158
augustus `--proteinprofile` or PPX method fails https://github.com/Homebrew/homebrew-science/issues/3583

**Comment by nextgenusfs** [comment]
Yes, installing augustus can be a real pain depending on what OS you are running.  You can install augustus manually, it just needs to be the the $PATH and you have to set $AUGUSTUS_CONFIG_PATH per the installation instructions.  funannotate will run some tests on whether Augustus is functioning properly when it is launched.  To continue the home-brew installation, you can comment out the bamtools and augustus lines in the linuxbrew formula, to get to the editable version just type `brew edit funannotate` which will launch editor and allow you to modify the formula locally.  Save your changes, install augustus/bamtools manually, and then continue on with linuxbrew via `brew install funannotate`.

**Comment by MichaelFokinNZ** [comment]
thank you! ubuntu 14, zsh
