### ISSUE TITLE
SignalP v. 5.0flag -t changed to -org

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#480]
Hi I have been struggling with signalP in fun annotate (although in truth I had it working in interproscan which I run outside). I have read that it must work with signalP v 5.0 but you have not used it yet.

I do not know if you solved it for your next release, however the flag -t has changed to -org in v5.0
The commands found in the logfile:

`signalp -t euk -f short /foo_bar/chunk_13.fa` consequently fails with the following error.
`flag provided but not defined: -t`

All the best

Fer

*Edit:* Following up on the flag issue,`-f short` is now `-format short` and although I have not tried stdin, the input file is specified with `-fasta`

**Comment by nextgenusfs** [comment]
Thanks for reporting - yes I've still not used so didn't know of the command line change, unfortunate they changed usage.... I will push a fix and let you know when you can try.

**Comment by nextgenusfs** [comment]
Can you post the output of `signalp -V` for me by chance? Want to make sure I'm parsing the version number correctly.

**Comment by ferninfm** [comment]
I obviously reverted to SignalP v4.1 and it does work.

The signalP version I reported about was `SignalP version 5.0b Linux x86_64`

Just FYI signalp v5.0 seems to be a binary file not a perl script. As a result they also changed all flags:

Usage of /usr/local/src/signalp-5.0b/bin/signalp:
  -batch int
    	Number of sequences that the tool will run simultaneously. Decrease or increase size depending on your system memory. (default 10000)
  -fasta string
    	Input file in fasta format.
  -format string
    	Output format. 'long' for generating the predictions with plots, 'short' for the predictions without plots. (default "short")
  -gff3
    	Make gff3 file of processed sequences.
  -mature
    	Make fasta file with mature sequence.
  -org string
    	Organism. Archaea: 'arch', Gram-positive: 'gram+', Gram-negative: 'gram-' or Eukarya: 'euk' (default "euk")
  -plot string
    	Plots output format. When long output selected, choose between 'png', 'eps' or 'none' to get just a tabular file. (default "png")
  -prefix string
    	Output files prefix. (default "Input file prefix")
  -stdout
    	Write the prediction summary to the STDOUT.
  -tmp string
    	Specify temporary file directory. (default "System default tmpdir")
  -verbose
    	Verbose output. Specify '-verbose=false' to avoid printing. (default true)
  -version
    	Prints version.

**Comment by hyphaltip** [comment]
On my system:
```
$ signalp
  -batch int
    	Number of sequences that the tool will run simultaneously. Decrease or increase size depending on your system memory. (default 10000)
  -fasta string
    	Input file in fasta format.
  -format string
    	Output format. 'long' for generating the predictions with plots, 'short' for the predictions without plots. (default "short")
  -gff3
    	Make gff3 file of processed sequences.
  -mature
    	Make fasta file with mature sequence.
  -org string
    	Organism. Archaea: 'arch', Gram-positive: 'gram+', Gram-negative: 'gram-' or Eukarya: 'euk' (default "euk")
  -plot string
    	Plots output format. When long output selected, choose between 'png', 'eps' or 'none' to get just a tabular file. (default "png")
  -prefix string
    	Output files prefix. (default "Input file prefix")
  -stdout
    	Write the prediction summary to the STDOUT.
  -tmp string
    	Specify temporary file directory. (default "System default tmpdir")
  -verbose
    	Verbose output. Specify '-verbose=false' to avoid printing. (default true)
  -version
    	Prints version.
No input file provided.
$  signalp -version
SignalP version 5.0b Linux x86_64```

**Comment by nextgenusfs** [comment]
And if you add the -V flag does it show same message (in 4.1 that's how you get version).

**Comment by hyphaltip** [comment]
Sadly no - then it just shows the first message - same as if no options provided. So you might have to run 2x if there isn't a pattern match to a version message?

**Comment by nextgenusfs** [comment]
Okay, can you tell me what output is from funannotate environment in the python interpreter if you do this:
```
from funannotate.check import check_version7
version = check_version7('signalp')
print(version)
```

**Comment by nextgenusfs** [comment]
And then @hyphaltip or @ferninfm  if you have both v5.0 and v4.1 installed can you do a test with these commands to make sure output is what I'm expecting, there is already a parser for v5 (I put draft function below for reference).
```
# version 4.1
signalp -t euk -f short prots.fasta | head -n 20

# version 5.0b
signalp -org euk -format short -fasta prots.fasta | head -n 20
```

```
def signalP(input, tmpdir, output):
    # split input file into chunks, 20 should mean < 200 proteins per chunk
    from funannotate.check import check_version7
    version = check_version7('signalp')
    if '.' in version:
        version = int(version.split('.')[0])
    if version > 4:
        cmd = ['signalp', '-org', 'euk', '-format', 'short', '-fasta']
    else:
        cmd = ['signalp', '-t', 'euk', '-f', 'short']
    fasta2chunks(input, 40, tmpdir, 'signalp_tmp')
    for file in os.listdir(os.path.join(tmpdir, 'signalp_tmp')):
        if file.startswith('chunk'):
            file = os.path.join(tmpdir, 'signalp_tmp', file)
            tmp_out = file.replace('.fa', '.signalp.out')
            cmd1 = cmd + [file]
            runSubprocess2(cmd1, '.', log, tmp_out)
    # now concatenate all outputs
    if os.path.isfile(output):
        os.remove(output)
    with open(output, 'a') as finalout:
        for file in os.listdir(os.path.join(tmpdir, 'signalp_tmp')):
            if file.endswith('.signalp.out'):
                file = os.path.join(tmpdir, 'signalp_tmp', file)
                with open(file) as infile:
                    finalout.write(infile.read())
    # cleanup tmp directory
    shutil.rmtree(os.path.join(tmpdir, 'signalp_tmp'))


def parseSignalP(sigP, secretome_annot):
    sigpDict = {}
    version = 4
    with open(sigP, 'r') as results:
        for line in results:
            line = line.rstrip()
            if line.startswith('#'):
                if line.startswith('# SignalP-5'):
                    version = 5
                continue
            if version < 5:
                col = line.split(' ')  # not tab delimited
                col = [_f for _f in col if _f]  # clean up empty spaces
                if col[9] == 'Y':  # then there is signal peptide
                    ID = col[0]
                    end = int(col[2]) - 1
                    sigpDict[ID] = [end, '', '']
            else:  # version 5 has different format and tab delimited hooray!
                if '\t' in line:
                    cols = line.split('\t')
                    if cols[1] != 'OTHER':  # then signal peptide
                        ID, prediction, score1, score2, position = cols[:5]
                        components = position.split()
                        pos = components[2].split('-')[0]
                        prob = components[-1]
                        aa = components[3].replace('.', '')
                        sigpDict[ID] = [pos, aa, prob]

    with open(secretome_annot, 'w') as secout:
        for k, v in natsorted(list(sigpDict.items())):
            if v[1] != '':
                secout.write("{:}\tnote\tSECRETED:SignalP(1-{:},cutsite={:},prob={:})\n".format(k, v[0], v[1], v[2]))
            else:
                secout.write("{:}\tnote\tSECRETED:SignalP(1-{:})\n".format(k, v[0]))
```

**Comment by nextgenusfs** [comment]
@hyphaltip fixed this one https://github.com/nextgenusfs/funannotate/pull/484.  Reopen if you are still having problems.
