### ISSUE TITLE
Feature request: utils rename GFF genes/ names

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#487]
**Are you using the latest release?**
1.8

Hi Jon,

I was wondering if it would be possible for you to add a script to your utils which could rename the genes in a given gff, while reordering the scaffolds (reorder and NOT preserve the gene numbering). Hear the specific problem below:

I know this sounds weird: A collaborator of mine insists on using BRAKER results ... However, the annotation step in Funan is superb (so I want to use this). I have successfully done this with a BRAKER output, however, Sometimes, BRAKER does not order the scaffolds and g1.t1 can be on scaff89 for example. Rather than g1.t1 being at the very start of scaff1. 

reordering the scaffs and renaming is tricky. I completely understand if you don't want to touch thi as making something for other tools gff output is always doomed to fail!

I can sort them easily enough with genometools, but renaming the genes which doesn't brake whatever you then use it the problem. Everything complains about parents!

cheers,

Pete

**Comment by nextgenusfs** [comment]
Yes, that should be too hard. can you send me an example GFF3 output? It should be basically a re-use of existing code.  Parsing GFF3 is not a fun job and impossible to capture all the variants out there....

**Comment by peterthorpe5** [comment]
Hi Jon,

Thank you for your reply. I will send you an download link to your email. 

cheers,

Pete

**Comment by nextgenusfs** [comment]
This function is in `funannotate util gff-rename`
