### ISSUE TITLE
funannotate annotate error

### ISSUE THREAD

**Issue by hao7261** [nextgenusfs/funannotate#488]
Hi @nextgenusfs I am getting an error I don't understand when I run funannotate annotate command.
(Everything works fine from funannotate clean, sort, mask, predict and even antismash remotely.)

The error:

funannotate annotate -i '/home/ubuntu/Desktop/data/funannotate_1/g55_predict' --cpus 8
-------------------------------------------------------
[10:26 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.18
[10:26 AM]: Running 1.8.0
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/fun/bin/funannotate", line 670, in <module>
    main()
  File "/home/ubuntu/.conda/envs/fun/bin/funannotate", line 660, in main
    mod.main(arguments)
  File "/home/ubuntu/.conda/envs/fun/lib/python2.7/site-packages/funannotate/annotate.py", line 362, in main
    if not lib.CheckDiamondDB(os.path.join(FUNDB, 'merops.dmnd')):
  File "/home/ubuntu/.conda/envs/fun/lib/python2.7/site-packages/funannotate/library.py", line 566, in CheckDiamondDB
    for line in execute(['diamond', 'dbinfo', '-d', database]):
  File "/home/ubuntu/.conda/envs/fun/lib/python2.7/site-packages/funannotate/library.py", line 551, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '[u'diamond', u'dbinfo', u'-d', '/home/ubuntu/funannotate_db/merops.dmnd']' returned non-zero exit status 1

**Command I ran for annotate**

Funannotate annotate -i <funannotate_predict_file> --cpus X

**Funannoatate database**

Funannotate Databases currently installed:

  Database          Type        Version      Date         Num_Records   Md5checksum                     
  pfam              hmmer3      33.1         2020-04            18259   228db640818af54066a1c23404a3ba38
  gene2product      text        1.64         2020-08-25         33640   aa985b947a9758cc696421923f654a27
  interpro          xml         81.0         2020-08-13         37821   ec10ff5e4d6f7fa4982ce00c1c6335e9
  dbCAN             hmmer3      9.0          2020-08-04           641   04696dfba1c3bb82ff9b72cfbb3e4a65
  busco_outgroups   outgroups   1.0          2020-10-01             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          5009   a6dd76907896708f3ca5335f58560356
  mibig             diamond     1.4          2020-10-01         31023   118f2c11edde36c81bdea030a0228492
  uniprot           diamond     2020_04      2020-08-12        563082   da5725f3aa16b176d6dcf4e7ba7c1ea1
  go                text        2020-09-10   2020-09-10         47243   08cf4043c53d84fcadac2be9ca7a4926
  repeats           diamond     1.0          2020-10-01         11950   4e8cafc3eea47ec7ba505bb1e3465d21

To update a database type:
	funannotate setup -i DBNAME -d /home/ubuntu/funannotate_db --force

To see install BUSCO outgroups type:
	funannotate database --show-outgroups

To see BUSCO tree type:
	funannotate database --show-buscos

**funannotate check --show-versions**

Checking dependencies for 1.8.0
-------------------------------------------------------
You are running Python v 2.7.18. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 2.2.5
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.24.0
scikit-learn: 0.18.2
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.30
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/ubuntu/funannotate_db
$PASAHOME=/home/ubuntu/.conda/envs/fun/opt/pasa-2.4.1
$TRINITY_HOME=/home/ubuntu/.conda/envs/fun/opt/trinity-2.8.5
$EVM_HOME=/home/ubuntu/.conda/envs/fun/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/ubuntu/.conda/envs/fun/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.8.22
emapper.py: 1.0.3
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hmmscan: HMMER 3.1b2 (February 2015)
hmmsearch: HMMER 3.1b2 (February 2015)
java: 11.0.8-internal
kallisto: 0.46.2
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.15.0
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.6 (May 2020)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: gmes_petap.pl not installed
	ERROR: hisat2 not installed
	ERROR: signalp not installed

How can I solve this issue?

Thank You for your attention.

**Comment by nextgenusfs** [comment]
What version of diamond. Looks like might be too old of a version and that cmd fails or the database doesn't exist. Try updating diamond - note that you will likely need to rerun setup
with --force to reinstall databases with same version of diamond.
