### ISSUE TITLE
question of annotate output 

### ISSUE THREAD

**Issue by hychenIG** [nextgenusfs/funannotate#492]
Hi Jon,  I have a question about "funannotate annotate" as follow:

In the annotate log file: [10/02/20 13:45:34]: Found 103 clusters, 250 biosynthetic enyzmes, and 424 smCOGs predicted by antiSMASH. But in the "tab-delimited SM cluster output",  that '.clusters.txt file' just have 16 clusters. Why?

Thanks!

**Comment by nextgenusfs** [comment]
How many are supposed to be there from antiSMASH? What version of antiSMASH and funannotate?

**Comment by hychenIG** [comment]
As far as I know, if in the log-file, it says found N clusters, in the output file should have N clusters, is that right? 

I using "antiSMASH 5.1.2"

**Comment by nextgenusfs** [comment]
How many clusters are listed in the antiSMASH output, ie the html or tsv results?

And what version of funannotate?

**Comment by hychenIG** [comment]
There are 121 clusters list in the html file , I use the funannotate 1.7.4

**Comment by nextgenusfs** [comment]
Okay, if you can upgrade to newest version and let me know if the problem persists then I can look into it.  Also confirm that you ran antiSMASH using funannotate GBK file?

**Comment by hychenIG** [comment]
Thanks, Jon. I found the reason for this. it's because the name of the scaffold. I mixed multiple FAC clones as a single genome to do the prediction and annotation. In order to figure out the cluster come from which FAC clone sample, I named each scaffold by sampleID. Such as the second scaffold of FAC: 01C-A1-A06 is named as 01C-A1-A06_2. In the follow cluster bed file, you can see that clusters in two different scaffold, 01C-A1-A06_2 and 01C-A1-B03_2 were named as single cluster_2.1, and only the last one was write to the output txt file. 

01C-A1-A06_2	0	40403	Cluster_2.1	0	+
01C-A1-B03_2	12757	55040	Cluster_2.1	0	+
01C-A1-B05_1	17222	65331	Cluster_1.1	0	+
01C-A2-B02_1	71448	118344	Cluster_1.1	0	+

**Comment by hychenIG** [comment]
> Okay, if you can upgrade to newest version and let me know if the problem persists then I can look into it. Also confirm that you ran antiSMASH using funannotate GBK file?

For upgrade to newest version, now my funannotate is 1.7.4, how to upgrade to newest version? how to deal with the old version?Thanks
