### ISSUE TITLE
Can't conda install on linux

### ISSUE THREAD

**Issue by nhartwic** [nextgenusfs/funannotate#493]
I've installed using conda several times in the past. Sometime in the last few weeks, it seems like some package got modified such that funannotate can't be installed by conda, at least on linux. I've let conda run for literally hours on multiple machines, without conda finding a sollution for the environment. 

Sorry I can't really offer any more info here. I'm uncertain, what if anything I can do to help resolve this problem.

**Comment by nextgenusfs** [comment]
If anything it should have more options for install due to now py 2/3. If you install a new/fresh miniconda3 will it work then? I did test it on centOS and it obviously built on bioconda. In the past when I've had problems with conda it's nearly always that there are packages installed in the base environment.

**Comment by nextgenusfs** [comment]
But if you already have an environment that was working for an older version you can just upgrade funannotate using pip.

**Comment by nhartwic** [comment]
I just started attempting to build the image specified by this singularity container...

```
Bootstrap:docker
From:continuumio/miniconda3

%post
    . /opt/conda/etc/profile.d/conda.sh
    conda activate
    conda create -n myenv -c bioconda -c conda-forge -c defaults funannotate

%runscript
    exec "$@"
```

...This is about as isolated and fresh as I can get short of nuking my computers. I'll let it run for a couple hours I suppose.

I'm fairly certain tools in the base environment aren't a problem though. I don't have anything installed to the base environment on my own machine and can't build there. My server does have some things installed to base but they really shouldn't be causing any problems here. 

I don't currently have access to an older version. I've been mostly running funannotate using snakemake and tibanna on aws. Funannotate environments were built at run time on whatever ec2 instance got spun up to run my jobs.  At some point, relatively recently, this system stopped working as attempting to install funannotate with conda seems to take forever.

**Comment by nextgenusfs** [comment]
When you run the conda channels like that what is the resulting order? The proper order should be: conda-forge bioconda defaults. So I don't know if the proper way in a single command is: conda create -c defaults -c bioconda -c conda-forge, or the other way: conda create -c conda-forge -c bioconda -c defaults.

**Comment by nextgenusfs** [comment]
And i think there is a way to pull the docker container from quay on bioconda directly.

**Comment by nhartwic** [comment]
It seems like my problem was with the channel order. 

```
# This doesn't work (at least not in a reasonable time frame. Perhaps it does eventually)
conda create -n myenv -c bioconda -c conda-forge -c defaults funannotate
# This does work
conda create -n myenv -c conda-forge -c bioconda -c defaults funannotate
```

Good to know.

**Comment by nextgenusfs** [comment]
At some point within last year bioconda changed the recommendation for channel orders (what you had originally was the old way). I don't know exactly why that matters but seems to be quite important. Glad you got it working.
