### ISSUE TITLE
funannotate predict Augustus/OpenBlas RLIMIT_NPROC errors

### ISSUE THREAD

**Issue by estolle** [nextgenusfs/funannotate#497]
During funannotate predict lots of error message popped up related to Augustus and OpenBlas. Seems its something related to max number of processors for OpenBlas. I found that setting it to 1 fixed it. Just wanted to report this here in case others encounter this problem.

**Solution:
export OPENBLAS_NUM_THREADS=1

**Are you using the latest release?**
yes (1.8.1 with python3)

**Describe the bug**
[10:44 PM]: Running Augustus gene prediction using nannotrigona_perilampoides parameters
[10:44 PM]: CMD ERROR: augustus --species=nannotrigona_perilampoides --extrinsicCfgFile=/home/ek/.conda/envs/funnotate181/lib/python3.7/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=2020_10_10_NannotrigonaPerilampoides/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=2020_10_10_NannotrigonaPerilampoides/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_72581/jcf7180001022836.fa
[10:44 PM]: (None, b'OpenBLAS blas_thread_init: pthread_create failed for thread 33 of 112: Resource temporarily unavailable\nOpenBLAS blas_thread_init: RLIMIT_NPROC 2062784 current, 2062784 max\n')

**What command did you issue?**
Copy/paste the command used.

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
Ubuntu 16.04
 -  output of `funannotate check --show-versions`

funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.1
-------------------------------------------------------
## conda update numpy scipy openblas
You are running Python v 3.7.8. Now checking python packages...
biopython: 1.78
goatools: 1.0.6
matplotlib: 3.3.2
## conda update numpy scipy openblas
natsort: 7.0.1
numpy: 1.19.1
pandas: 1.1.3
psutil: 5.7.2
requests: 2.24.0
scikit-learn: 0.23.2
scipy: 1.5.2
seaborn: 0.11.0
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
   ERROR: DB_File not installed, install with cpanm DB_File  #this fails to install

Checking Environmental Variables...
$FUNANNOTATE_DB=/scratch/funannotatedb
$PASAHOME=/home/ek/.conda/envs/funnotate181/opt/pasa-2.4.1
$TRINITYHOME=/opt/trinityrnaseq-Trinity-v2.5.1
$EVM_HOME=/opt/EVidenceModeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/ek/.conda/envs/funnotate181/config/
$GENEMARK_PATH=/opt/gm_et_linux_64/gmes_petap
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 2.0.4
emapper.py: 1.0.3
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.35
hisat2: 2.2.1
hmmscan: HMMER 3.3.1 (Jul 2020)
hmmsearch: HMMER 3.3.1 (Jul 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.23
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
signalp: 4.1
snap: 2006-07-28
stringtie: 2.1.4
tRNAscan-SE: 2.0.6 (May 2020)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed

**Comment by xizhesun** [comment]
thanks estolle. your solution works!

**Comment by kushalsuryamohan** [comment]
Hi @xizhesun, I'm facing the same issue but don't see the solution here in the comments (looks like it was removed). Can you please let me know how you fixed this?

**Comment by xizhesun** [comment]
Please read the issue carefully, It contains the solution.
