### ISSUE TITLE
criteria to name/number proteins

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#501]
Hi,
I realised a peculiar behaviour in funannotate predict (guessing), which I am not sure is desired as such.

The gene models found and proteins are wonderfully named correlatively: species_00001-T1 and so on within each scaffold. This is perfect. I expected this naming to continue correlative to the order of scaffolds: Scaffold_1 proteins 00001 to 01000 Scaffold_2 protein 01001 to 03000.

This is not the case. Scaffolds are ordered by name (as text) and not using the numerical index, so the naming of proteins is:
Scaffold_1: proteins 00001 to 01000
Scaffold_10: proteins 01001 to 03000
Scaffold_11
Scaffold_110...
Scaffold_2: proteins 05001 to 06000

It is quite trivial, and if anything, it can only get confusing when trying to troubleshoot mediocre datasets. Still, my OCD does not let me believe this is the behaviour you desired....

Take care,
All the best
Fer

**Comment by nextgenusfs** [comment]
Okay -- this is a quick fix I think, basically native python sort is sorting currently, we can change this to use natsort module which will sort like a human would.

**Comment by ferninfm** [comment]
Using natsort seems like a great idea!
Take care.

Fernando
