### ISSUE TITLE
No output write to file using funannotate clean

### ISSUE THREAD

**Issue by hychenIG** [nextgenusfs/funannotate#504]
Hi Jon,
I just update my funannotate to 1.8.2. Now I run funannotate clean, no output write into file. 

'''''''''''''funannotate clean -i 01C-A1-A01.assembly.fasta -o 01C-A1-A01.clean -m 5000 --exhaustive
-----------------------------------------------
13 input contigs, 8 larger than 5,000 bp, N50 is 14,739 bp
Checking duplication of 8 contigs
-----------------------------------------------
-----------------------------------------------
13 input contigs; 8 larger than 5000 bp; 0 duplicated; 8 written to file'''''''''''

Nothing write to the output file 01C-A1-A01.clean

**Comment by nextgenusfs** [comment]
My first guess would be the fasta headers are atypical. Nothing has changed in the code for that method in quite some time.

**Comment by hychenIG** [comment]
Thanks, Jon. But I check the fasta headers, which should be fine. I using the same input fasta file, the output can write to the file by funannotate sort, but nothing from funannotate clean.

**Comment by nextgenusfs** [comment]
You can test with:
```
funannotate test -t clean --debug
```
And then let me know if the output file is really empty.  If the test is working properly, then its most likely your fasta headers. 

If you use results of sort into clean, does it work then (ie simplified headers)?

**Comment by hychenIG** [comment]
As you suggestion, all the test are work. so it's caused by the headers. But the fasta file with the header is automatically generated from assemble_facs.py pipline. such as ">ctg1 length=115083 depth=1.00x". 
Anyway, it works after change the headers. Thanks!

**Comment by nextgenusfs** [comment]
oh, yeah its the spaces in the header.

**Comment by nextgenusfs** [comment]
But I'm not sure you want to run clean on that output if its a FAC -- its meant for removal of repetitive/contained contigs from a de novo assembly. Running sort is good to clean up the headers.

**Comment by hychenIG** [comment]
Yes, it's not necessary to run clean for the FAC-assembly.fasta, I don't really understand the mean of clean function. Run sort is enough for my case. Thanks a lot!
