### ISSUE TITLE
predict has a problem using the PASA gff file

### ISSUE THREAD

**Issue by estolle** [nextgenusfs/funannotate#505]
**Are you using the latest release?**
1.8.1

**Describe the bug**
PASA training with reads and Trinity assembly done.
Predict now fails using the transcripts.gff from PASA.

And idea?

[12:28 PM]: OS: Ubuntu 16.04, 112 cores, ~ 528 GB RAM. Python: 3.7.8
[12:28 PM]: Running funannotate v1.8.1
[12:28 PM]: Found training files, will re-use these files:
  --pasa_gff 2020_10_16_TetragonulaCarbonaria/training/funannotate_train.pasa.gff3
  --transcript_alignments 2020_10_16_TetragonulaCarbonaria/training/funannotate_train.transcripts.gff3
Traceback (most recent call last):
  File "/home/ek/.conda/envs/funnotate181/bin/funannotate", line 688, in <module>
    main()
  File "/home/ek/.conda/envs/funnotate181/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/ek/.conda/envs/funnotate181/lib/python3.7/site-packages/funannotate/predict.py", line 430, in main
    predictor, weight = x.split(':')
ValueError: too many values to unpack (expected 2)

**What command did you issue?**
(
funannotate train --cpus 60 --species "$SPECIES" --max_intronlen 10000 --pasa_alignment_overlap 30.0 --pasa_db sqlite --no_trimmomatic --coverage 50 --min_coverage 5 --memory 100G --stranded no --aligners minimap2 --pasa_min_pct_aligned 85 --pasa_min_avg_per_id 90 --pasa_num_bp_splice 3 \
--trinity $TRINITY \
--input $ASM \
--out $OUT \
--left $FWD \
--right $REV \
)

(
funannotate predict \
-i $ASM \
-o $OUT \
-s "$SPECIES" \
--name $NAME"_" \
--weights augustus:2,pasa:8,codingquarry:1 \
--rna_bam $BAMFILE \
--busco_seed_species bombus_impatiens1 \
--busco_db hymenoptera \
--cpus $CPUs \
--keep_no_stops \
--keep_evm \
--SeqCenter XXXX \
--organism other \
--max_intronlen 10000 \
--optimize_augustus \
--ploidy 1 \
--repeat_filter overlap blast \
--soft_mask 5000 \
--protein_evidence \
$INPUT2 \
$INPUT4 \
$INPUT5 \
$INPUT6 \
$INPUT7 \
$INPUT8 \
$INPUT9 \
$INPUT10 \
$INPUT11 \
$INPUT12 \
$INPUT13 \
$INPUT14) \
--stringtie $STRINGTIE \
--transcript_evidence \
$TRINITY \
$BINPACKER \
)

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`

**Comment by nextgenusfs** [comment]
Options to --weights are space separated not comma.

**Comment by estolle** [comment]
oh, I didn't realize, thanks! It runs now =)
