### ISSUE TITLE
funannotate update fails at very last table

### ISSUE THREAD

**Issue by estolle** [nextgenusfs/funannotate#506]
Hi

v181 gives me an error at the update step, at the very end when writing the output tables. I googles but don't see an easy/obvs fix I can apply. Any idea how to fix or how to workaround and proceed? I still wanted to run the iprscan and annotation steps.

Command:
CPUs=60
(
funannotate update -i $OUT \
        --cpus $CPUs \
        --left $FWD \
        --right $REV \
        --memory 100G --stranded no --pasa_db sqlite \
        --species "$SPECIES" --max_intronlen 10000 --pasa_alignment_overlap 30.0 --coverage 50 --name "$FUNNAME" \
        --trinity $TRINITY \
)

Terminal ouput:

[01:38 AM]: Writing 17,671 loci to TBL format: dropped 0 overlapping, 2 too short, and 0 frameshift gene models
[01:38 AM]: Converting to Genbank format
[02:04 AM]: Collecting final annotation files
[02:05 AM]: Parsing GenBank files...comparing annotation
[02:07 AM]: putative transcript from ncbi:EuglossaDilemma_016971-T1 has no ID
(ncbi:EuglossaDilemma_016971-T1 None ncbi:EuglossaDilemma_016971-T1)
Traceback (most recent call last):
  File "/home/ek/.conda/envs/funnotate181/bin/funannotate", line 688, in <module>
    main()
  File "/home/ek/.conda/envs/funnotate181/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/ek/.conda/envs/funnotate181/lib/python3.7/site-packages/funannotate/update.py", line 2361, in main
    compareAnnotations2(GBK, final_gbk, Changes, args=args)
  File "/home/ek/.conda/envs/funnotate181/lib/python3.7/site-packages/funannotate/update.py", line 1357, in compareAnnotations2
    newGenes[gene[2]]['CDS'], hitInfo['CDS'])
  File "/home/ek/.conda/envs/funnotate181/lib/python3.7/site-packages/funannotate/update.py", line 1492, in pairwiseAED
    splitAED = [pAED[i:i+len(query)] for i in range(0, len(pAED), len(query))]
ValueError: range() arg 3 must not be zero

**Comment by nextgenusfs** [comment]
Can you pull that gene out of the tbl file so I can see what it is? EuglossaDilemma_016971-T1

**Comment by estolle** [comment]
<10280  10043   gene
                        locus_tag       EuglossaDilemma_016971
<10280  10043   mRNA
                        product hypothetical protein
                        transcript_id   gnl|ncbi|EuglossaDilemma_016971-T1_mrna
                        protein_id      gnl|ncbi|EuglossaDilemma_016971-T1
<10281  10043   CDS
                        codon_start     3
                        product hypothetical protein
                        transcript_id   gnl|ncbi|EuglossaDilemma_016971-T1_mrna
                        protein_id      gnl|ncbi|EuglossaDilemma_016971-T1


looks normal to me. There was no previous hint to "fix" this (or any other) gene model.

**Comment by estolle** [comment]
ah wait, looks like the CDS is ending 1bp later than the mRNA and Gene.

It anyway wasnt flagged to be "fixed" after predict.

Is it possible to fix it in the update folder and apply the fix command there instead the predict folder? it would save rerunning the funannotate update

**Comment by nextgenusfs** [comment]
Yeah, you can edit the tbl file and then run `funannotate fix` -- it will archive the current data and generate new output files in place. 

So I guess this came out of PASA then?  Was this gene present in predict output?

**Comment by nextgenusfs** [comment]
This could be a small error in the function that finds genes that start/stop in gaps and trims them back to the first non-N character, are you able to see if that was the case? ie is it right next to a stretch of ambiguous bases (N's)?

**Comment by estolle** [comment]
its odd. The coordinates in the update_misc folder files (pasa gff, best models gff) and the predict_results table are correct. Unclear where this 1bp gets lost then.
There is no N in that scaffold.

**Comment by nextgenusfs** [comment]
So this same gene model in the tbl file from `predict_results` looks identical as above?  I'm just trying to track down where the error has crept in.  There is a function that should have caught this and adjusted the mRNA/gene locations to contain the CDS.

**Comment by skylerhar1** [comment]
I had a very similar issue to this one. Here's the check-version, log files and tbl file. I have two loci without any ID: FUN_004038, FUN_012373
[fun_check_version.txt](https://github.com/nextgenusfs/funannotate/files/6919354/fun_check_version.txt)
[Rhizopogon_salebrosus.tbl.txt](https://github.com/nextgenusfs/funannotate/files/6919368/Rhizopogon_salebrosus.tbl.txt)
[update_log_7_30.e9819512.txt](https://github.com/nextgenusfs/funannotate/files/6919369/update_log_7_30.e9819512.txt)
