### ISSUE TITLE
RepeatMasker4.0.5 is not compartible with the most recent GIRI database

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#51]
The link below from Ubuntu installation manual is not live anymore

> #download RepeatMasker libraries and install
> wget --user name --password pass http://www.girinst.org/server/RepBase/protected/repeatmaskerlibraries/repeatmaskerlibraries-20160829.tar.gz
> tar zxvf repeatmaskerlibraries-20160829.tar.gz -C $HOME/.linuxbrew/opt/repeatmasker/libexec

while the new one RepBaseRepeatMaskerEdition-20170127.tar.gz is not compatible with RepeatMasker4.0.5 from _homebrew-science_ and therefore RepeatModeler is not able to work without full database....  (installation of 4.0.7 just on place of 4.0.5 helps, but needs a lot of manual troubleshooting)

> COMPATIBILITY WITH OLDER VERSIONS OF REPEATMASKER
> 
> This library distribution involves a major shift away from a monolithic
> ( one source ) library format and embraces the notion that libraries may
> increasingly come from multiple sources.  Unfortunately this requires
> changes in the library structures that will not work with previous versions
> of RepeatMasker ( 4.0.6 and earlier ).  We have not removed support for 
> older libraries and versions 20140131 and on should continue to work with
> the latest releases of RepeatMasker.

**Comment by nextgenusfs** [comment]
Thanks for the info.  You should be able to grab one of the archived versions of the RepeatMasker libraries.  I will look into the new version and check compatibility with the rest of funannotate.

**Comment by nextgenusfs** [comment]
Looks like v4.07 works same as v4.05.  And some more testing shows that I don't think you need to download the RepBase libraries anymore as default settings in funannotate are to use custom library generated from RepeatModeler.  Previous versions seemed to have still required the RepBase library, but now a minimal library is shipped with RepeatMasker.  Will work on updating the brew RepeatMasker version and instructions.

**Comment by nextgenusfs** [comment]
You can install 4.07 via home-brew this way, it is not yet available in parent repository.
```
brew install nextgenusfs/science/repeatmasker
```
