### ISSUE TITLE
inconsistent of exon and CDS position

### ISSUE THREAD

**Issue by tfwangasimb** [nextgenusfs/funannotate#510]
Hello,
I have questions in gff3 results. There are some genes predicted isoforms, yet T1 exons numbers are not matched T1 CDS numbers but T2. Please take a look at the example.
```
ChIII      GenBank exon    17326   18890   .       -       .       ID=TR_000005-T1.exon1;Parent=TR_000005-T1;
ChIII      GenBank exon    17010   17248   .       -       .       ID=TR_000005-T1.exon2;Parent=TR_000005-T1;
ChIII      GenBank exon    16713   16953   .       -       .       ID=TR_000005-T1.exon3;Parent=TR_000005-T1;
ChIII      GenBank exon    16112   16657   .       -       .       ID=TR_000005-T1.exon4;Parent=TR_000005-T1;
ChIII      GenBank CDS     17326   18576   .       -       0       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank CDS     17010   17248   .       -       0       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank CDS     16440   16953   .       -       1       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank exon    17326   18890   .       -       .       ID=TR_000005-T2.exon1;Parent=TR_000005-T2;
ChIII      GenBank exon    17010   17248   .       -       .       ID=TR_000005-T2.exon2;Parent=TR_000005-T2;
ChIII      GenBank exon    16112   16953   .       -       .       ID=TR_000005-T2.exon3;Parent=TR_000005-T2;
ChIII      GenBank CDS     17326   18576   .       -       0       ID=TR_000005-T2.cds;Parent=TR_000005-T2;
ChIII      GenBank CDS     17010   17248   .       -       0       ID=TR_000005-T2.cds;Parent=TR_000005-T2;
ChIII      GenBank CDS     16713   16953   .       -       1       ID=TR_000005-T2.cds;Parent=TR_000005-T2;
ChIII      GenBank CDS     16550   16657   .       -       0       ID=TR_000005-T2.cds;Parent=TR_000005-T2;
```
To me, the result seems like T1 CDS belongs to T2 exon, and T2 exon matches to T1 CDS. Also, I check the T1 transcript is a perfect match for the T2 protein sequence, vice versa. However, it is quite complicated, not all of the genes with isforms are switch. I've checked the gff3 files from predict_result, update_result, and annotation_result. The output file after funannotate-predict was right, but inconsistent in update and annotation.
Is there anything I can fix this problem?

Thanks for your help.
Best,

Wan

**Comment by nextgenusfs** [comment]
How/where in the pipeline did you get this GFF3 file from? Did you pass GBK file to `annotate`?  How did you run the commands in funannotate?  The problem with GenBank format with multiple/alternative transcripts is that the program that write genbank flat files does not write the transcript/CDS in order and coupled with the fact that there is no identifier that ties CDS to a mRNA field in Genbank format (ie there is no parent field), the data become jumbled.  Funannotate deals with this by using the NCBI tbl format when you run the scripts as they were intended, if you pass genbank files then the script warns you that it might make mistakes due to this issue.

**Comment by tfwangasimb** [comment]
Basically, I follow the Tutorials pipeline: sort –> mask –> train –> predict –> update –> annotate
In the update step, the command was: funannotate update -i "test_fun" --cpus 10
In the annotate step, the command was: funannotate annotation -i test_fun --sbt template.sbt --cpus 32 --antismash TR_antismash.final.gbk --strain Q --species our_study --busco_db ascomycota
"test_fun" is the folder name that created in the funannotate-train step.
I got the GFF3 files in the output folder of update_results and annotate_results, which were under the "test_fun".

The commands for update and annotate, the required of input is  Funannotate folder.

Required:
-i, --input              Funannotate folder or Genome in GenBank format (.gbk,.gbff).
      or
-f, --fasta              Genome in FASTA format
-g, --gff                Annotation in GFF3 format
--species              Species name, use quotes for binomial, e.g. "Aspergillus fumigatus"

Sorry, I may totally misunderstand your meaning. How to change the input file to tbl format?
Thank you for your kind reply.

**Comment by nextgenusfs** [comment]
Okay, you didn't do anything wrong, just not quite sure where the error would be creeping in.  When you use the folder input, ie `-i` options then it will use the tbl file automatically.  

In order to track down where this is happening can you pull out the data for a gene where this is happening, basically I need to see the gene model in tbl format and GFF3 format from the `predict_results` folder and then also the `update_results`. 

For example, if you can just paste in something like:
```
# predict results tbl
519	10110	gene
			locus_tag	FUN_000001
519	849	mRNA
916	8706
8764	8797
8929	10110
			product	hypothetical protein
			transcript_id	gnl|ncbi|FUN_000001-T1_mrna
			protein_id	gnl|ncbi|FUN_000001-T1
1692	8706	CDS
8764	8797
8929	9028
			codon_start	1
			product	hypothetical protein
			transcript_id	gnl|ncbi|FUN_000001-T1_mrna
			protein_id	gnl|ncbi|FUN_000001-T1

# predict results gff
chr1	GenBank	gene	519	10110	.	+	.	ID=FUN_000001;
chr1	GenBank	mRNA	519	10110	.	+	.	ID=FUN_000001-T1;Parent=FUN_000001;product=hypothetical protein;
chr1	GenBank	exon	519	849	.	+	.	ID=FUN_000001-T1.exon1;Parent=FUN_000001-T1;
chr1	GenBank	exon	916	8706	.	+	.	ID=FUN_000001-T1.exon2;Parent=FUN_000001-T1;
chr1	GenBank	exon	8764	8797	.	+	.	ID=FUN_000001-T1.exon3;Parent=FUN_000001-T1;
chr1	GenBank	exon	8929	10110	.	+	.	ID=FUN_000001-T1.exon4;Parent=FUN_000001-T1;
chr1	GenBank	CDS	1692	8706	.	+	0	ID=FUN_000001-T1.cds;Parent=FUN_000001-T1;
chr1	GenBank	CDS	8764	8797	.	+	2	ID=FUN_000001-T1.cds;Parent=FUN_000001-T1;
chr1	GenBank	CDS	8929	9028	.	+	1	ID=FUN_000001-T1.cds;Parent=FUN_000001-T1;
```
```
# predict results tbl
519	10110	gene
			locus_tag	FUN_000001
519	849	mRNA
916	8706
8764	10110
			product	hypothetical protein
			transcript_id	gnl|ncbi|FUN_000001-T1_mrna
			protein_id	gnl|ncbi|FUN_000001-T1
552	849	CDS
916	8706
8764	10064
			codon_start	1
			product	hypothetical protein
			transcript_id	gnl|ncbi|FUN_000001-T1_mrna
			protein_id	gnl|ncbi|FUN_000001-T1
519	849	mRNA
916	8706
8764	8797
8929	10110
			product	hypothetical protein
			transcript_id	gnl|ncbi|FUN_000001-T2_mrna
			protein_id	gnl|ncbi|FUN_000001-T2
552	849	CDS
916	8706
8764	8797
8929	9028
			codon_start	1
			product	hypothetical protein
			transcript_id	gnl|ncbi|FUN_000001-T2_mrna
			protein_id	gnl|ncbi|FUN_000001-T2
            
# update results gff
chr1	funannotate	gene	519	10110	.	+	.	ID=FUN_000001;
chr1	funannotate	mRNA	519	10110	.	+	.	ID=FUN_000001-T1;Parent=FUN_000001;product=hypothetical protein;
chr1	funannotate	five_prime_UTR	519	551	.	+	.	ID=FUN_000001-T1.utr5p1;Parent=FUN_000001-T1;
chr1	funannotate	exon	519	849	.	+	.	ID=FUN_000001-T1.exon1;Parent=FUN_000001-T1;
chr1	funannotate	exon	916	8706	.	+	.	ID=FUN_000001-T1.exon2;Parent=FUN_000001-T1;
chr1	funannotate	exon	8764	10110	.	+	.	ID=FUN_000001-T1.exon3;Parent=FUN_000001-T1;
chr1	funannotate	three_prime_UTR	10065	10110	.	+	.	ID=FUN_000001-T1.utr3p1;Parent=FUN_000001-T1;
chr1	funannotate	CDS	552	849	.	+	0	ID=FUN_000001-T1.cds;Parent=FUN_000001-T1;
chr1	funannotate	CDS	916	8706	.	+	2	ID=FUN_000001-T1.cds;Parent=FUN_000001-T1;
chr1	funannotate	CDS	8764	10064	.	+	2	ID=FUN_000001-T1.cds;Parent=FUN_000001-T1;
chr1	funannotate	mRNA	519	10110	.	+	.	ID=FUN_000001-T2;Parent=FUN_000001;product=hypothetical protein;
chr1	funannotate	five_prime_UTR	519	551	.	+	.	ID=FUN_000001-T2.utr5p1;Parent=FUN_000001-T2;
chr1	funannotate	exon	519	849	.	+	.	ID=FUN_000001-T2.exon1;Parent=FUN_000001-T2;
chr1	funannotate	exon	916	8706	.	+	.	ID=FUN_000001-T2.exon2;Parent=FUN_000001-T2;
chr1	funannotate	exon	8764	8797	.	+	.	ID=FUN_000001-T2.exon3;Parent=FUN_000001-T2;
chr1	funannotate	exon	8929	10110	.	+	.	ID=FUN_000001-T2.exon4;Parent=FUN_000001-T2;
chr1	funannotate	three_prime_UTR	9029	10110	.	+	.	ID=FUN_000001-T2.utr3p1;Parent=FUN_000001-T2;
chr1	funannotate	CDS	552	849	.	+	0	ID=FUN_000001-T2.cds;Parent=FUN_000001-T2;
chr1	funannotate	CDS	916	8706	.	+	2	ID=FUN_000001-T2.cds;Parent=FUN_000001-T2;
chr1	funannotate	CDS	8764	8797	.	+	2	ID=FUN_000001-T2.cds;Parent=FUN_000001-T2;
chr1	funannotate	CDS	8929	9028	.	+	1	ID=FUN_000001-T2.cds;Parent=FUN_000001-T2;
```

**Comment by tfwangasimb** [comment]
# predict results tbl
18576   16550   gene
                        locus_tag       TR_000005
18576   17326   mRNA
17248   17010
16953   16713
16657   16550
                        product hypothetical protein
                        transcript_id   gnl|ncbi|TR_000005-T1_mrna
                        protein_id      gnl|ncbi|TR_000005-T1
18576   17326   CDS
17248   17010
16953   16713
16657   16550
                        codon_start     1
                        product hypothetical protein
                        transcript_id   gnl|ncbi|TR_000005-T1_mrna
                        protein_id      gnl|ncbi|TR_000005-T1
23181   24721   gene
                        locus_tag       TR_000006

# predict results gff
ChIII      GenBank gene    16550   18576   .       -       .       ID=TR_000005;
ChIII      GenBank mRNA    16550   18576   .       -       .       ID=TR_000005-T1;Parent=TR_000005;product=hypothetical protein;
ChIII      GenBank exon    17326   18576   .       -       .       ID=TR_000005-T1.exon1;Parent=TR_000005-T1;
ChIII      GenBank exon    17010   17248   .       -       .       ID=TR_000005-T1.exon2;Parent=TR_000005-T1;
ChIII      GenBank exon    16713   16953   .       -       .       ID=TR_000005-T1.exon3;Parent=TR_000005-T1;
ChIII      GenBank exon    16550   16657   .       -       .       ID=TR_000005-T1.exon4;Parent=TR_000005-T1;
ChIII      GenBank CDS     17326   18576   .       -       0       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank CDS     17010   17248   .       -       0       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank CDS     16713   16953   .       -       1       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank CDS     16550   16657   .       -       0       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank gene    23181   24721   .       +       .       ID=TR_000006;
ChIII      GenBank mRNA    23181   24721   .       +       .       ID=TR_000006-T1;Parent=TR_000006;product=hypothetical protein;

# update results tbl
18890   16112   gene
                        locus_tag       TR_000005
18890   17326   mRNA
17248   17010
16953   16713
16657   16112
                        product hypothetical protein
                        transcript_id   gnl|ncbi|TR_000005-T1_mrna
                        protein_id      gnl|ncbi|TR_000005-T1
18576   17326   CDS
17248   17010
16953   16713
16657   16550
                        codon_start     1
                        product hypothetical protein
                        transcript_id   gnl|ncbi|TR_000005-T1_mrna
                        protein_id      gnl|ncbi|TR_000005-T1
18890   17326   mRNA
17248   17010
16953   16112
                        product hypothetical protein
                        transcript_id   gnl|ncbi|TR_000005-T1.3.5d3f6295_mrna
                        protein_id      gnl|ncbi|TR_000005-T1.3.5d3f6295
18576   17326   CDS
17248   17010
16953   16440
                        codon_start     1
                        product hypothetical protein
                        transcript_id   gnl|ncbi|TR_000005-T1.3.5d3f6295_mrna
                        protein_id      gnl|ncbi|TR_000005-T1.3.5d3f6295
18890   17010   mRNA
16953   16112
                        product hypothetical protein
                        transcript_id   gnl|ncbi|TR_000005-T1.1.5d3f6230_mrna
                        protein_id      gnl|ncbi|TR_000005-T1.1.5d3f6230
18576   17278   CDS
                        codon_start     1
                        product hypothetical protein
                        transcript_id   gnl|ncbi|TR_000005-T1.1.5d3f6230_mrna
                        protein_id      gnl|ncbi|TR_000005-T1.1.5d3f6230

# update results gff
ChIII      GenBank gene    16112   18890   .       -       .       ID=TR_000005;
ChIII      GenBank mRNA    16112   18890   .       -       .       ID=TR_000005-T1;Parent=TR_000005;product=hypothetical protein;
ChIII      GenBank exon    17326   18890   .       -       .       ID=TR_000005-T1.exon1;Parent=TR_000005-T1;
ChIII      GenBank exon    17010   17248   .       -       .       ID=TR_000005-T1.exon2;Parent=TR_000005-T1;
ChIII      GenBank exon    16713   16953   .       -       .       ID=TR_000005-T1.exon3;Parent=TR_000005-T1;
ChIII      GenBank exon    16112   16657   .       -       .       ID=TR_000005-T1.exon4;Parent=TR_000005-T1;
ChIII      GenBank CDS     17326   18576   .       -       0       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank CDS     17010   17248   .       -       0       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank CDS     16440   16953   .       -       1       ID=TR_000005-T1.cds;Parent=TR_000005-T1;
ChIII      GenBank mRNA    16112   18890   .       -       .       ID=TR_000005-T2;Parent=TR_000005;product=hypothetical protein;
ChIII      GenBank exon    17326   18890   .       -       .       ID=TR_000005-T2.exon1;Parent=TR_000005-T2;
ChIII      GenBank exon    17010   17248   .       -       .       ID=TR_000005-T2.exon2;Parent=TR_000005-T2;
ChIII      GenBank exon    16112   16953   .       -       .       ID=TR_000005-T2.exon3;Parent=TR_000005-T2;
ChIII      GenBank CDS     17326   18576   .       -       0       ID=TR_000005-T2.cds;Parent=TR_000005-T2;
ChIII      GenBank CDS     17010   17248   .       -       0       ID=TR_000005-T2.cds;Parent=TR_000005-T2;
ChIII      GenBank CDS     16713   16953   .       -       1       ID=TR_000005-T2.cds;Parent=TR_000005-T2;
ChIII      GenBank CDS     16550   16657   .       -       0       ID=TR_000005-T2.cds;Parent=TR_000005-T2;
ChIII      GenBank mRNA    16112   18890   .       -       .       ID=TR_000005-T3;Parent=TR_000005;product=hypothetical protein;
ChIII      GenBank exon    17010   18890   .       -       .       ID=TR_000005-T3.exon1;Parent=TR_000005-T3;
ChIII      GenBank exon    16112   16953   .       -       .       ID=TR_000005-T3.exon2;Parent=TR_000005-T3;
ChIII      GenBank CDS     17278   18576   .       -       0       ID=TR_000005-T3.cds;Parent=TR_000005-T3;

**Comment by nextgenusfs** [comment]
Okay, so the tbl file is correct, but the naming of the gene models is strange, ie I don't know where the `T1.3.5d3f6295_mrna` these longer names are coming from. 

What version of funannotate are you using here? And how was `funannotate train` run?

**Comment by tfwangasimb** [comment]
> And this is the GFF3 file in update_results?

Yep, the GFF3 file in update_results

> What version of funannotate are you using here? 

The version we use is 1.5.3
I'm installing a new one (1.8.1), and try to run again.
> And how was funannotate train run?

I provide paired-end RNA-seq 
`funannotate train  -i Q_mask.fa -o test_fun --left /home/Hisat2/RNA-reads/1-1_R1.fastq.gz --right /home/Hisat2/RNA-reads/1-1_R2.fastq.gz --stranded RF --jaccard_clip --memory 400G --strain Q`
`funannoate predict -i Q_mask.fa -o test_fun --strain Q --cpus 10 -s our_study  --cpus 10 --augustus_species neurospora_crassa --name TR`

**Comment by nextgenusfs** [comment]
Oh okay, if the version is that old could explain why it doesn't seem right to me. Let me know if newest version has same problem.

**Comment by tfwangasimb** [comment]
Hi Jon,

Thanks for your advice. I use the newest version and it works.

Best,

**Comment by hyphaltip** [comment]
Seems like update version solved the issue.
