### ISSUE TITLE
fasta2agp.pl error creating fasta output when sequences contain ambiguities.

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#511]
Hi,

I had a problem with a GenBank genome. I used as "outgrop"

It contained many different IUPAC coded ambiguities in the scaffolds so `funanotate annotate` breaks with an error (Illegal nucleotides in sequence....)

To cut it short. I bypassed the problem editing fasta2agp.pl at line 76 from:
https://github.com/nextgenusfs/funannotate/blob/af17b89e7cc98abbcf0c7ce9fbff0e424c5a1cc5/funannotate/aux_scripts/fasta2agp.pl#L76

to
```} elsif ( $substring_sequence =~ m/^[ACGTNMRWSYKVHDB]+$/i ) {```

This was made to fit my needs, and did the job. Still it may be a good idea to change it.

Fer

**Comment by nextgenusfs** [comment]
Should probably re-write this in python -- will leave open as I don't have time to address right now.

**Comment by hyphaltip** [comment]
I can also help rewrite this would be easy. Didn’t see this bug before

**Comment by jimie0311** [comment]
Hi nextgenusfs,
I am using funnnoate 1.8.7. I met the same error in fasta2agp.pl.  Illegal characters in sequence\n\n
However, I check the fasta2agp.pl file, The line 76 is already the correct way "} elsif ( $substring_sequence =~ m/^[ACGTNMRWSYKVHDB]+$/i ) {"

What is wrong?
Thanks.

**Comment by hyphaltip** [comment]
did you figure out what sequence was the error causing base it may not match that pattern still?

**Comment by hyphaltip** [comment]
Also this has been rewritten in the code in github to be fasta2agp.py - but I don't think @nextgenusfs has made a release yet so you might have to install from github?
