### ISSUE TITLE
funannotate compare - mafft issue with Selenocystein (U)

### ISSUE THREAD

**Issue by estolle** [nextgenusfs/funannotate#514]
Hi there

I went now further into the compare step and mafft failed with the error below. running the listed command manually witout --quiet revealed that likely Selenocystein (U) caused this. This failure can be circumvented with the flag --any-symbol. But were in the code is the mafft command (I do not find it in th ecompare script when I search for mafft. Is this a different scipt?

[12:38 AM]: CMD ERROR: mafft test/phylogeny/phylogeny.concat.fa
[12:38 AM]: (None, b'')

nthread = 0
nthreadpair = 0
nthreadtb = 0
ppenalty_ex = 0
stacksize: 8192 kb
rescale = 1
Gap Penalty = -1.53, +0.00, +0.00
========================================================================= 
========================================================================= 
=== 
=== Alphabet 'U' is unknown.
=== Please check site 603129 in sequence 1.
=== 
=== To make an alignment that has unusual characters (U, @, #, etc), try  
=== % mafft --anysymbol input > output
=== 
========================================================================= 
========================================================================= 
Illegal character U

Likely solution:
--anysymbol
To use unusual characters (e.g., U as selenocysteine in protein sequence; i as inosine in nucleotide sequence), use the --anysymbol option:

% mafft --anysymbol input > output

It accepts any printable characters (U, O, #, $, %, etc.; 0x21-0x7e in the ASCII code), execpt for > (0x3e) and ( (0x28).  Unusual characters are scored as unknown (not considered in the calculation), unlike in the --text mode.

**Comment by nextgenusfs** [comment]
added that option above (the functions are buried in the horribly organized library.py script). Let me know if that fixes it.

**Comment by estolle** [comment]
cool, this worked. It all ran through.

I am rerunning the analysis with my whole dataset. ... had a setback due to identical mRNA IDs in multiple NCBI Genomes - I fixed this manually and running it again. The GO enrichment step take about 24 hrs. There is no check if results already exist in funannotate compare, right?(like in funannotate predict)

**Comment by estolle** [comment]
never mind, It did skip recalculating the dNdS ratio's

However it threw another error: 


[01:31 PM]: Calculating dN/dS ratios for each ortholog group, 48945 orthologous groups
Traceback (most recent call last):
  File "/home/ek/.conda/envs/funnotate181/bin/funannotate", line 688, in <module>
    main()
  File "/home/ek/.conda/envs/funnotate181/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/ek/.conda/envs/funnotate181/lib/python3.7/site-packages/funannotate/compare.py", line 977, in main
    SeqIO.write(SeqTranscripts[i], tranout, 'fasta')
  File "/home/ek/.conda/envs/funnotate181/lib/python3.7/site-packages/Bio/File.py", line 248, in __getitem__
    record = self._proxy.get(self._offsets[key])
KeyError: 'nbisL1-mrna-2666-T1'


7 species have this mRNA and the IDs are now unique (Species name added to it). Do you know what this error means? Could it be too long?

Dufourea_novaeangliae.gbk:                     /protein_id="ncbi:DufoureaNovaeangliae_nbisL1-mrna-2666-T1"
Eufriesea_mexicana.gbk:                     /protein_id="ncbi:EufrieseaMexicana_nbisL1-mrna-2666-T1"
Friseomelitta_varia.gbk:                     /protein_id="ncbi:FriseomelittaVaria_nbisL1-mrna-2666-T1"
Habropoda_laboriosa.gbk:                     /protein_id="ncbi:HabropodaLaboriosa_nbisL1-mrna-2666-T1"
Lasioglossum_albipes.gbk:                     /protein_id="ncbi:LasioglossumAlbipes_nbisL1-mrna-2666-T1"
Megachile_rotundata.gbk:                     /protein_id="ncbi:MegachileRotundata_nbisL1-mrna-2666-T1"
Melipona_quadrifaciata.gbk:                     /protein_id="ncbi:MeliponaQuadrifaciata_nbisL1-mrna-2666-T1"

looks like a normal entry otherwise.

**Comment by estolle** [comment]
Here is the complete gbk entry (for one of the species) for the problematic entry (KeyError: 'nbisL1-mrna-2666-T1').
I did change the IDs and aded the speicesID to it becasue multiple species from NCBI have the same identifier (but for different genes). So nbisL1-mrna-2666 became DufoureaNovaeangliae_nbisL1-mrna-2666 in the gbk. the the Underline character a problem there perhaps?




     gene            2088962..2089707
                     /locus_tag="DufoureaNovaeangliae_nbisL1-mrna-2666"
     mRNA            join(2088962..2089332,2089644..2089707)
                     /locus_tag="DufoureaNovaeangliae_nbisL1-mrna-2666"
                     /product="putative LOC107194546"
     CDS             join(2088974..2089332,2089644..2089707)
                     /locus_tag="DufoureaNovaeangliae_nbisL1-mrna-2666"
                     /note="EggNog:ENOG410399W;
                     SECRETED:SignalP(1-25)"
                     /codon_start=1
                     /product="putative LOC107194546"
                     /protein_id="ncbi:DufoureaNovaeangliae_nbisL1-mrna-2666-T1"
                     /translation="MLSINMGIFKTVLFLVALVSYRVQCLSVANESSIANPATSKPLE
                     LSAEVDHYDQRQNGSENYRVGLDGLVVVFAPAEVLLLANAAAANKPILPILPESKPTV
                     SKPEAEDPPTPAPKSTNRGGSRLTDLLIPFLRRFQHQE"

**Comment by nextgenusfs** [comment]
It is probably the underscore, generally the old code assumes that your locus tag is separated from the numerical ID via a single underscore. The compare code is somewhat old so perhaps it's the identifiers. You could try to simplify the names and see if that helps.

**Comment by estolle** [comment]
nice, I'll reformat this and rerun. Thanks!
