### ISSUE TITLE
Problem parsing Eggnog output

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#515]
Dear Jon,

I am having a problem reading Eggnog results. I have the sensation that this problem had already been solved before. But It reappeared for me. I think that at a certain point I downgraded emapper to v1.0.3 in a previous funannotate version (1.8.0 or 1.8.1) and it did work.

Anyhow, I have tried feeding funannotate annotate with the output from standalone emapper v.1.03 and emapper-2.0.1b (apparently both with DB: 2.0.) through the --eggnog flag. I also tried having emapper be run from funannotate directly (Only v1.0.3).

The ´annotate_misc/annotations.eggnog.txt´file does not contain parsed data at all (I have been careful to remove it every time, btw...)

It is a succession of query_names and the string pasted in the script
´Cafla_000004-T1	note	EggNog:ENOG41´

I do not understand completely funannotates annotate.py code but

In lines 235 to 237 you have:
`
                for x in OGs:
                    if DB in x:
                        NOG = 'ENOG41' + x.split('@')[0]
`

If I am correct:

1. First you parse `DB = cols[DBi].split('[')[0]`
1.1. being DBi `DBi = item2index(headerCols, 'taxonomic scope')`
1.2. in v2 of emapper it is kind of irrelevant since the output writes `Fungi` and not `Fungi[1]`
1.3. If `.split` works like in any other language it should give the same result. **Fungi**

2. The question is why is the condition of line 236 `if DB in x:` there? **Fungi** will never be in the list of OGs `20E3B@147545,38BT1@33154,3MPMI@451870,3NU58@4751,3QQS0@4890,COG0040@1,KOG2831@2759` split by the comma.

I may be completely wrong but I think this condition is probably a leftover which is stopping the flow....

Because the scripts are compiled it is more difficult to play with them. I'll fork and modify the files to try, but definitively not today... 

Take care,

Fernando

**Comment by nextgenusfs** [comment]
Emapper v2.x is not supported because they have not settled on a output format - I can't parse the data if it is a moving target. So only v1.0.3 with v4.5 of database is supported. I know this makes a conflict now because v1.0.3 is py2 only....

**Comment by ferninfm** [comment]
Hi,

All my output files are complete and parseable be it from emapper 1.0.3 or from emapper 2.x

I think the annotate.py script as it is now should be parsing my newly obtained files correctly, as far as I went)

However, apriori the if statement of line 236 bothers me

```
for x in OGs:

    if DB in x:

```
It does not make any sense to me. The content of the column **taxonomic scope** (Fungi) is never going to be in the content of the column containing the Orthogroup codes right? At least not in the output of emapper v1.0.3 and v.2.0.1 using the database v2

Fernando

**Comment by ferninfm** [comment]
I downgraded myself to the master as of v1.8.1
I have commented out line 236 of annotate.py and indented back 237

now the annotations.eggnog.txt reads:

```

PyrenodesmiaX5_000059-T1	note	EggNog:ENOG41
PyrenodesmiaX5_000060-T1	note	EggNog:ENOG41map00520
PyrenodesmiaX5_000060-T1	note	COG:R02335
PyrenodesmiaX5_000061-T1	note	EggNog:ENOG41map01100
PyrenodesmiaX5_000061-T1	note	COG:R00548,R02135

```

I am not sure the output it is wrong but it does contain COGs and map codes

cheers

**Comment by ferninfm** [comment]
No worries,
my mistake the problem is the database format.
Why all of a sudden I am using v2 instead of v4.5 is a riddle to me now
Sorry for taking time from you

cheers
Fernando
