### ISSUE TITLE
funnanotate will not recognise install dependencies

### ISSUE THREAD

**Issue by emmannaemeka** [nextgenusfs/funannotate#518]
I install dependencies such as Augustus and tRNAscan-SE. Both I can call separately. However, when I run funannotate check it does not recognise these dependencies. 
How can I solve this, please?

**Comment by hyphaltip** [comment]
Seems like we need to see the reports of errors and perhaps the results of these commands would assist.
```
funannotate check --show-versions

which augustus
which tRNAscan-SE
```
