### ISSUE TITLE
Glimmer Parse Error

### ISSUE THREAD

**Issue by nhartwic** [nextgenusfs/funannotate#519]
Currently operating on funannotate version 1.8.2 and using docker/singularity to isolate my install. Link below...

docker://nolanhartwick/salk-containers:fun

...I'm running into an intermittent bug with glimmer. Some assemblies hit this error, some don't with no apparent rhyme or reason. Glimmer version is 3.0.4. Stack Trace below...

```
GlimmerHMM parsing error: 1     GlimmerHMM      CDS     643381  643647  .       +       0       ID=1.cds15##sequence-region 2 1 25532557
Traceback (most recent call last):
  File "/opt/conda/envs/myenv/bin/funannotate", line 706, in <module>
    main()
  File "/opt/conda/envs/myenv/bin/funannotate", line 696, in main
    mod.main(arguments)
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/funannotate/predict.py", line 1553, in main
    args.out, 'predict_misc'), GlimmerPredictions)
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/funannotate/library.py", line 6002, in runGlimmerHMM
    glimmer2gff3(glimmerRaw, output)
  File "/opt/conda/envs/myenv/lib/python3.7/site-packages/funannotate/library.py", line 5931, in glimmer2gff3
    '\t')
ValueError: not enough values to unpack (expected 9, got 4)
```

I suppose I'll work on getting the glimmer logs and raw output. If this is a known error of some kind, let me know. Thanks in advance for any assistance

**Comment by nhartwic** [comment]
Update. Glimmer logs and output files for a failed run: [glimmer_results.tar.gz](https://github.com/nextgenusfs/funannotate/files/5631759/glimmer_results.tar.gz)

Seems like issue is on line 151753 of "glimmerHMM.output.raw".

```151751 10      GlimmerHMM      CDS     6897966 6898183 .       +       0       ID=10.cds1103.1;Parent=10.path1.gene1103;Name=10.path1.gene1103;Note=initial-exon
 151752 10      GlimmerHMM      CDS     6900000 6900084 .       +       1       ID=10.cds1103.2;Parent=10.path1.gene1103;Name=10.path1.gene1103;Note=final-exon
 151753 1
 151754 ##sequence-region 11 1 14171033
 151755 11      GlimmerHMM      mRNA    2309    2458    .       +       .       ID=11.path1.gene1;Name=11.path1.gene1
 151756 11      GlimmerHMM      CDS     2309    2458    .       +       0       ID=11.cds1.1;Parent=11.path1.gene1;Name=11.path1.gene1;Note=final-exon
```

Can someone confirm that glimmhmm.pl/glimmerhmm is responsible for producing this file and not funannotate?

Assuming the above is true, there must be an error in the perl script or in the glimmerhmm executable. I suppose I'll try to recompile glimmerhmm and see if that fixes anything.

**Comment by nextgenusfs** [comment]
Hi @nhartwic, so is that 1 on its own line?  It might just be the ##sequence-region line.  Let me look at the code quick.

**Comment by nhartwic** [comment]
Yes, its on its line, You can verify by looking at "glimmerHMM.output.raw" after you unpack the tar archive. It may be the sequence region line, though I don't know why that line would get mangled.

**Comment by nextgenusfs** [comment]
Here is the function generating that output, its indeed the raw output from glimmer. 
https://github.com/nextgenusfs/funannotate/blob/bf4a348bb8045438c1ebffec4fb2a26bc28625d3/funannotate/library.py#L5994-L5999

**Comment by nextgenusfs** [comment]
I can have the parser ignore lines that don't have the proper length/num of tabs.  Hopefully that won't cause some other unintended issues?  I have not seen this error before, possible its a glimmer compilation issue I guess.

**Comment by nextgenusfs** [comment]
The parser is here: 
https://github.com/nextgenusfs/funannotate/blob/bf4a348bb8045438c1ebffec4fb2a26bc28625d3/funannotate/library.py#L5907-L5968

So would be something like adding `if line.count('\t') < 8: continue`

**Comment by nhartwic** [comment]
I would rather figure out why glimmer is outputting junk than try to make funannotate handle junk. This may not be possible though. I'm working on building a new container with a manual glimmer install and will try to test again.

I also am certain that these glimmer errors occur when writing out the models, not when writing the sequence region. There are a handful of errors that look like this when I dug in deeper...

```
12	GlimmerHMM	mRNA	8008355	8009100	.	+	.	ID=12.path1.gene1019;Name=12.path1.gene1019
12	GlimmerHMM	CDS	8008355	800840
##sequence-region 13 1 13541320
13	GlimmerHMM	mRNA	4280	4816	.	+	.	ID=13.path1.gene1;Name=13.path1.gene1
13	GlimmerHMM	CDS	4280	4816	.	+	0	ID=13.cds1.1;Parent=13.path1.gene1;Name=13.path1.gene1;Note=final-exon
```

**Comment by nextgenusfs** [comment]
Yes, good point.  I just glanced at the file and noticed what seemed like an extra config name before every ##sequence-region, but from what you have here its more of a problem.  Seems like output lines are being truncated somewhat randomly?

**Comment by nextgenusfs** [comment]
I'll push this code, so it will complete but output the offending lines to stdout:
```
>>> import funannotate.library as lib
>>> lib.glimmer2gff3('predict_misc/glimmerHMM.output.raw', 'test.glimmer.out')
ERROR parsing GlimmerHMM Raw output:
Line 151753: 1
ERROR parsing GlimmerHMM Raw output:
Line 168669: 12	GlimmerHMM	CDS	8008355	800840
GlimmerHMM parsing error: 31	GlimmerHMM	CDS	1182602	1182691	.	+	0	ID=31.cds1
GlimmerHMM parsing error: 35	GlimmerHMM	CDS	653391	653512	.	-	0	ID=
ERROR parsing GlimmerHMM Raw output:
Line 286182: 4
ERROR parsing GlimmerHMM Raw output:
Line 288006: 42	GlimmerHMM	CDS	823638	8237
```

**Comment by nhartwic** [comment]
Well, good news is your commits seem to be handling Glimmers errors. Bad news is recompiling glimmer didn't accomplish anything. I also have been looking more closely at the regions that seem to be causing the errors. Perhaps unsurprisingly, these regions have  large N gaps. I think these are what is causing the issues with glimmer, though I don't know exactly why.
