### ISSUE TITLE
modifying the tmp directory for tRNAscanSE

### ISSUE THREAD

**Issue by chipotlau** [nextgenusfs/funannotate#523]
During funannotate predict, I am getting an error from tRNAscanSE, which may result from the /tmp directory running out of space. How can I change the temporary directory for tRNAscanSE? Many thanks in advance for your help. 

**Are you using the latest release?**
Yes, version 1.8.2

**Describe the bug**
During funannotate predict, tRNAscanSE fails with this error: "Unable to open /tmp/tscan48978_iso_cm.tab for reading.  Aborting program."

**What command did you issue?**
funannotate predict -i genome.fasta -o funannotate-out -s species --organism other --cpus 12

**Comment by nextgenusfs** [comment]
I do not see the tmp directory as a command line option in `tRNAscanSE v2.0`.  It looks like in the help menu there is a configuration file, perhaps that could be modified. That source file is here: https://github.com/UCSC-LoweLab/tRNAscan-SE/blob/master/tRNAscan-SE.conf.src.  So it seems like you can modify your install to direct the tmp to somewhere else.

**Comment by chipotlau** [comment]
Hello, 

Thanks for your help. Turns out this bug was not an issue with the /tmp directory filling up, but instead it is an issue with the tRNAscanSE run. The tRNAscanSE developers suggested adding "-S off" to the tRNAscanSE command ([see tRNAscanSE issue here](https://github.com/UCSC-LoweLab/tRNAscan-SE/issues/2)), how can I do this while using funannotate predict?

**Comment by nextgenusfs** [comment]
Were you able to confirm that adding the `-S off` flag allowed it to complete properly?

Also, in the initial bug, did funannotate die or did it just not include tRNA predictions?  I'm hesitant to add this flag to the default, as I sort of prefer the "defaults" for a universal pipeline. 

There are a few ways to make the change in funannotate, simplest is just to add `-S off` to the call in funannotate -- then it will be hard coded essentially for all users. I don't know if this is a good/bad idea?  Alternatively there could be an option to run it in that mode or an option to pass custom options to tRNAscanSE.   Another option would be to run tRNAscan outside of funannotate and have an option to pass it the results (so then funannotate would just use those results instead of re-running).  My preference is probably the last option as that is most flexible to different use cases.

**Comment by chipotlau** [comment]
After adding the flag `-S off`, tRNAscanSE successfully completed, so I have the output in tabular form. 

In the initial bug, funannotate predict failed to complete due to the tRNAscanSE error- I think it would be a good idea to have the option to run tRNAscanSE outside funannotate, followed by passing the results to funannotate (similar to how we can pass interproscan and eggnog results during funannotate annotate). It seems like this error is rare, so perhaps it would not be a good idea to hardcode `-S off` for all users. 

What do you think?

**Comment by nextgenusfs** [comment]
Agreed. Do you have the error that it reported by chance? That way I can capture the error and alert user that it failed but it won't kill the run.

**Comment by chipotlau** [comment]
Here is the error from tRNAscanSE (it is also the last line in funannotate-predict.log before funannotate fails and ends): `Unable to open /tmp/tscan70051_iso_cm.tab for reading.  Aborting program.`

**Comment by nextgenusfs** [comment]
Okay, do you know what the python error was that was output to the terminal?  I'll try to make chances right now.

**Comment by chipotlau** [comment]
Here is the terminal output (precedes the tRNAscanSE error)- `CMD ERROR: tRNAscan-SE -o funannotate-out/predict_misc/tRNAscan.out --thread 12 /home/projects/funannotate-out/predict_misc/genome.softmasked.fa`

Many thanks for your help!

**Comment by nextgenusfs** [comment]
Okay, latest commit should expose a new `--trnascan` option and it should (hopefully) run and not die if tRNAscan fails (this is not necessary for generating protein models.  However, I do not have a test dataset, so I didn't test if this works.  It would be great if you could test first without providing the --trnascan option to see if it properly fails and completes the pipeline, then you can run again with adding your externally generated `--trnascan` and it should hopefully incorporate correctly. You can install latest by:
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git
```

**Comment by chipotlau** [comment]
I will give it a try now and report back (should be within the next day), thank you and happy new year!

**Comment by chipotlau** [comment]
The latest commit works- I tested: (1) without providing the `--trnascan` option, and `funannotate predict` recorded the trnascan failure but successfully completed; (2) I reran `funannotate predict` and added the externally generated tRNAscan results using the `--trnascan` option, and funannotate predict successfully incorporated the results and completed. 

Many thanks for your help!

**Comment by peterthorpe5** [comment]
Same error, same fix using the github pull from 5th Feb 2021. I have used Funannotate alot and not come across this before. Would it be possible to   try: tRNAscan-SE ,   if error,   retry with -S off option on?
