### ISSUE TITLE
Funannotate compare takes for a very long time.

### ISSUE THREAD

**Issue by shig913** [nextgenusfs/funannotate#524]
Hi,

Thank you for the useful pipeline.
I am comparing 10 genomes (~30-50 Mbp) using funannotate compare.
All the genomes were annotated using funannotate pipeline.
However, proteinortho step takes for over three days and seems not to work fine!
I get no error messages.
Is this correct?

Best,
Shige

**Comment by nextgenusfs** [comment]
It shouldn't take that long. Not sure how to help with just this information. Is a process still running? Is there any temp output in the funannotate output folders?

**Comment by shig913** [comment]
I am sorry for the late reply.
I could solve this by replacing proteinortho6 to proteinortho5.
When I installed funannotate via anaconda, proteinortho version 6 was automatically installed.
However,  proteinortho6 failed with error code 33792 under my environment.
So I removed proteinortho6, installed proteinortho5 binary, and it worked well. 

Thanks.

**Comment by nextgenusfs** [comment]
I had problems with specific versions as well -- some more info here: https://gitlab.com/paulklemm_PHD/proteinortho/-/issues/39
