### ISSUE TITLE
funannotate iprscan -i xx -m docker 

### ISSUE THREAD

**Issue by ybdong919** [nextgenusfs/funannotate#527]
When I run the command "funannotate iprscan -i xx -m docker " in docker, it always say  
      FileNotFundError: [Errno 2] No such file or directory: 'docker': 'docker'

**Comment by nextgenusfs** [comment]
What is the result in this environment from `which docker`?

Side note I don't think the `funannotate-docker` wrapper will be able to run the dockerized interproscan function.

**Comment by nextgenusfs** [comment]
Also, this is a workflow I wrote several years ago based on a dockerized interproscan https://github.com/blaxterlab/interproscan-docker.  The version it uses is now fairly old, I would recommend running interproscan in an alternative method -- either installing the most recent copy locally.  If the wrapper isn't working, then just use the docker container according to their instructions.

**Comment by ybdong919** [comment]
What is the meaning of "-m docker"? I do not understand the meaning of the
argument.

**Comment by ybdong919** [comment]
OK, I understand.
Many thanks!
Yibo

**Comment by nextgenusfs** [comment]
```
$ funannotate iprscan

Usage:       funannotate iprscan <arguments>
version:     1.8.2

Description: This script is a wrapper for running InterProScan5 using Docker or from a
             local installation. The script splits proteins into smaller chunks and then
             launches several interproscan.sh "processes". It then combines the results.

Arguments:
  -i, --input        Funannotate folder or FASTA protein file. (Required)
  -m, --method       Search method to use: [local, docker] (Required)
  -n, --num          Number of fasta files per chunk. Default: 1000
  -o, --out          Output XML InterProScan5 file
  --debug            Keep intermediate files
  --no-progress      Do not print progress to stdout for long sub jobs

Docker arguments:
  -c, --cpus         Number of CPUs (total). Default: 12
  --cpus_per_chunk   Number of cpus per Docker instance. Default: 4

Local arguments:
  --iprscan_path     Path to interproscan.sh. Default: which(interproscan.sh)
  -c, --cpus         Number of InterProScan instances to run
                     (configure cpu/thread control in interproscan.properties file)
        
```

**Comment by athulmenon** [comment]
Hi Jon,

I tried to run a local version of iprscan, but it's showing the below error. I ran using Docker wrapper script, with the location to iprscanner installed locally.

./funannotate-docker iprscan -i GCF_003316985.1_ASM331698v1_protein.faa -m local --iprscan_pa
th /Programs/interproscan/interproscan-5.48-83.0/interproscan.sh --out ipr_local --cpus 10
logname: no login name
logname: no login name
Running InterProScan5 on 11779 proteins
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 362, in <module>
    if not os.path.isfile(iprpath):
  File "/venv/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Can you please let me know if this can be resolved.

NB : I have activated a conda environment for Java11 before running this as latest iprscan needs Java11.

Thanks,
Athul

**Comment by nextgenusfs** [comment]
Okay, probably need to do a bit more here if running from the docker container -- ie you would need to mount the interproscan local directory to the docker container in order for it to be able to access/run those files.  

I'm not sure if the funannotate docker container can run the interproscan wrapper or not.

**Comment by athulmenon** [comment]
Hi,

Thank you for your reply. I will try to mount and run.

Regards,
Athul

**Comment by lukaskon** [comment]
I had the same TypeError issue and (after looking at source code with others) believe it can be solved it by calling the path as /Programs/interproscan/interproscan-5.48-83.0/ without "interproscan.sh" at the end.
