### ISSUE TITLE
not an issue. just a question.

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#53]
Would you recommend using Trinity de-novo assemblies as evidences? I found that with high coverage data, majority of isoforms are not real, but being unweighted do they spoil gene models in funannotate? Or full PASA pipeline can sort them out somehow?

**Comment by nextgenusfs** [comment]
If you have good RNA-seq than I would recommend running Trinity then PASA.  funanntoate uses different weights in Evidence Modeler for different data - so the transcript alignments done by GMAP and BLAT are essentially used for exon/intron boundaries. 

So I would run something like I have at the end of the [README](https://github.com/nextgenusfs/funannotate/blob/master/README.md), Trinity -> PASA. Align reads to genome generate a coord-sorted BAM.  Then you would pass to funannotate like
```
funannotate predict -i genome.fa -o test -s "Awesome genome" --rna_bam hisat2.bam --pasa your_pasa_models.gff --transcript_evidence trinity.all.fasta,EST.fa
```
This will utilize all of the info the best that it can.  It will train Augustus and GeneMark based on the RNA-seq alignments, pass the high quality models from PASA through to EVM, and then use the transcript and protein (swissprot is used by default) evidence as well.  Note you can pass multiple fasta files to both --transcript_evidence and --protein_evidence, separate the files with a comma (no space).

**Comment by MichaelFokinNZ** [comment]
Thank you! Will try to get better/more reliable transcriptome

**Comment by MichaelFokinNZ** [comment]
Can I use not the full pasa pipeline, but just the TransDecoder gff3 output as a "pasa" evidence? 
Seems in my case the major goal is to exclude false-isoforms with introns from gene prediction (which are assembled de-novo because of incomplete mRNA splicing in highly expressed genes....)

**Comment by nextgenusfs** [comment]
I would use the transdecoder step of PASA, see the README where I walk through what I normally do.  The `--pasa_gff` is expecting high quality gene models.
