### ISSUE TITLE
fasta2agp.pl error

### ISSUE THREAD

**Issue by 38293649** [nextgenusfs/funannotate#532]
Hi, I am using the latest version of funannotate to annotate a bird genome, but the final annotate step reported a error that I can't fix. This is the screenshot of that error, please help, thank you!
![image](https://user-images.githubusercontent.com/72552037/104828404-ff3c7d80-58a3-11eb-9526-9583022ccf24.png)
All the best,
De Chen

**Comment by nextgenusfs** [comment]
What characters do you have on the DNA sequence it is complaining about? I would always assume that only GATCN are acceptable for an assembly.

**Comment by waldeyr** [comment]
I have got the same error by running (Docker:latest) the following command: 

`funannotate annotate -i G1_predicted_genes/ --force --cpus 4 -o G1_annotated_genes/`

_OS: Debian GNU/Linux 10, 4 cores, ~ 16 GB RAM. Python: 3.7.9
Running 1.8.4
...
CMD ERROR: perl /venv/lib/python3.7/site-packages/funannotate/aux_scripts/fasta2agp.pl scaffolds.fa
(None, b"Will write contigs to file 'contigs.fsa' and AGP to STDOUT\nIllegal characters in sequence\nGATGTGAT...TG\n")_


I'm not sure, but I suspect of the **"\n"** character at the end of the sequence.

**Comment by nextgenusfs** [comment]
Are either of you able to share your genome fasta file so I can take a look?

**Comment by 38293649** [comment]
Thank you for your reply! 
I think i know the reason. There are two scaffolds in the genome with all N, the fasta2agp.pl stopped when it processed one of them. I deleted these two scaffolds and only run fasta2agp.pl, it worked. However, if I run funannotate annotate -i fun --busco_db aves --sbt fun/template.sbt --cpus 40, the genome in the annotate_misc folder will include the two problematic scaffolds again and report error. How can I use the edited genome to run the funannotate annotate, thank you!

All the best

**Comment by nextgenusfs** [comment]
It is using the GBK and TBL files from the `predict_results` folder.  So assuming there weren't any predictions on scaffolds that were all N's... than you should just be able to re-run your `funannotate predict` command with the properly edited genome FASTA file -- that way it will get incorporated into the output GBK file and then subsequently used in `funannotate annotate`.

**Comment by waldeyr** [comment]
> Thank you for your reply!
> I think i know the reason. There are two scaffolds in the genome with all N, the fasta2agp.pl stopped when it processed one of them. I deleted these two scaffolds and only run fasta2agp.pl, it worked. However, if I run funannotate annotate -i fun --busco_db aves --sbt fun/template.sbt --cpus 40, the genome in the annotate_misc folder will include the two problematic scaffolds again and report error. How can I use the edited genome to run the funannotate annotate, thank you!
> 
> All the best

Thanks for this tip. I gonna look at my scaffolds tomorrow to verify the existence of only 'Ns'. I will report it here later.

**Comment by ferninfm** [comment]
I have encountered this same problem again after updating to the newest version 1.8.4.

I manage to complete the `funannotate annotate` runs by modifying the perl code of fasta2agp.pl to use ALL IUPAC ambiguity codes. I don't know if that may cause upstream problems upon submission to NCBI. In principle all ambiguities should be accepted, or at least have been previously acceptable...

If anyone is in a hurry and for whatever reason has ambiguities other than Ns in their genomes, the solution proposed in issue #511 solves this problem.

That is changing line 76 in the fasta2agpl.pl script
from `} elsif ( $substring_sequence =~ m/^[ACGTN]+$/i ) {`
to `} elsif ( $substring_sequence =~ m/^[ACGTRYSWKMBDHVN]+$/i ) {`

Al the best

**Comment by jimie0311** [comment]
> It is using the GBK and TBL files from the `predict_results` folder. So assuming there weren't any predictions on scaffolds that were all N's... than you should just be able to re-run your `funannotate predict` command with the properly edited genome FASTA file -- that way it will get incorporated into the output GBK file and then subsequently used in `funannotate annotate`.

Hi, could you please explain what is the meaning of no any prediction on scaffolds?
If one scaffold only include tRNA, that means this scaffold will be all N's?
I met the same problem when using funannotate annotate with the error of "AGP to STDOUT\nIllegal characters in sequence\n\n" I checked the tbl file in predict_results, there are few short scaffolds which don't have cds but only tRNA predicted. Should I move them to rerun funannotate predict?

**Comment by nextgenusfs** [comment]
The error doesn't have anything to do with gene predictions but rather the DNA sequences -- ie you apparently have non IUPAC characters in your genome sequence. (this means any character that is not in this string `ACGTRYSWKMBDHVN`).

**Comment by jimie0311** [comment]
Hi Jon,
I am using v.1.8.7.   I checked the fasta2agpl.pl, it is ACGTRYSWKMBDHVN
