### ISSUE TITLE
Error in busco mediated predict test

### ISSUE THREAD

**Issue by Faheema-khan** [nextgenusfs/funannotate#533]
I have recently installed Funannotate and am running the test. The busco mediated test is failing. The program exits with the message, "Not enough gene models 175 to train Augustus (200 required), exiting". I am attaching the log files here. 
[busco.log](https://github.com/nextgenusfs/funannotate/files/5844587/busco.log)
[funannotate-predict.log](https://github.com/nextgenusfs/funannotate/files/5844588/funannotate-predict.log)

I went through some of the issues here already and tried everything mentioned there. e.g upgrading and down grading Daimond etc. 

I would really appreciate any help!

**Comment by nextgenusfs** [comment]
Its a problem with the newest Augustus v3.4, downgrade Augustus to 3.3.3 and it will work.  They changed the output in v3.4 somewhere and I haven't had time to track it down yet.

**Comment by Faheema-khan** [comment]
The number of gene models increased to 373. There are no errors in the BUSCO log file now but the program still exits without completion and it gives me this error. 

[08:16 PM]: Training Augustus using BUSCO gene models
Traceback (most recent call last):
  File "/home/faheema/.local/bin/funannotate", line 688, in <module>
    main()
  File "/home/faheema/.local/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/faheema/.local/lib/python2.7/site-packages/funannotate/predict.py", line 1341, in main
    lib.trainAugustus(AUGUSTUS_BASE, aug_species, trainingset,
UnboundLocalError: local variable 'AUGUSTUS_BASE' referenced before assignment
#########################################################
Traceback (most recent call last):
  File "/home/faheema/.local/bin/funannotate", line 688, in <module>
    main()
  File "/home/faheema/.local/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/faheema/.local/lib/python2.7/site-packages/funannotate/test.py", line 406, in main
    runBuscoTest(args)
  File "/home/faheema/.local/lib/python2.7/site-packages/funannotate/test.py", line 200, in runBuscoTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_busco.gff3')) <= 1800
  File "/home/faheema/.local/lib/python2.7/site-packages/funannotate/test.py", line 44, in countGFFgenes
    with open(input, 'r') as f:
IOError: [Errno 2] No such file or directory: 'test-busco_2133/annotate/predict_results/Awesome_busco.gff3'

**Comment by nextgenusfs** [comment]
Please install latest release and see if problem persists.  It might be related to py27.

**Comment by Faheema-khan** [comment]
I installed the latest version of Funannotate(v 1.8.4) but the problem is still the same. I get this error. 

#########################################################
Running `funannotate predict` BUSCO-mediated training unit testing                                                                          CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --cpus 8 --species Awesome busco]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]#########################################################
Traceback (most recent call last):
  File "/home/faheema/.local/bin/funannotate", line 713, in <module>
    main()
  File "/home/faheema/.local/bin/funannotate", line 702, in main
    '{:}.{:}'.format(package_name, info[cmdName]['cmd']))
  File "/sw/comp/python/3.7.2_rackham/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/predict.py", line 14, in <module>
    import funannotate.library as lib
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/library.py", line 38, in <module>
    from Bio import SeqIO
  File "/sw/bioinfo/biopython/1.73/rackham/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 384, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/sw/bioinfo/biopython/1.73/rackham/lib/python2.7/site-packages/Bio/Align/__init__.py", line 29, in <module>
    raise new_exc
ImportError: dynamic module does not define module export function (PyInit__aligners): you should not import directly from the biopython source directory; please exit the source tree and re-launch your code from there
#########################################################
Traceback (most recent call last):
  File "/home/faheema/.local/bin/funannotate", line 713, in <module>
    main()
  File "/home/faheema/.local/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/test.py", line 407, in main
    runBuscoTest(args)
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/test.py", line 201, in runBuscoTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_busco.gff3')) <= 1800
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-busco_b143edb0-8e66-48da-abbd-1bdd866db3d1/annotate/predict_results/Awesome_busco.gff3'

**Comment by Faheema-khan** [comment]
I reinstalled the latest version of Funannotate(v. 1.8.4). I still get this error:

Traceback (most recent call last):
  File "/home/faheema/.local/bin/funannotate", line 713, in <module>
    main()
  File "/home/faheema/.local/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/predict.py", line 1360, in main
    lib.trainAugustus(AUGUSTUS_BASE, aug_species, trainingset,
UnboundLocalError: local variable 'AUGUSTUS_BASE' referenced before assignment
#########################################################
Traceback (most recent call last):
  File "/home/faheema/.local/bin/funannotate", line 713, in <module>
    main()
  File "/home/faheema/.local/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/test.py", line 407, in main
    runBuscoTest(args)
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/test.py", line 201, in runBuscoTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_busco.gff3')) <= 1800
  File "/home/faheema/.local/lib/python3.7/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-busco_5ce43272-3d8b-46c7-9bbe-5f9e7418a427/annotate/predict_results/Awesome_busco.gff3'

**Comment by Faheema-khan** [comment]
I also have some warnings in the busco log e.g [tblastn]Warning: [tblastn] Query is Empty! The log file is here:
[busco.log](https://github.com/nextgenusfs/funannotate/files/5849488/busco.log)

**Comment by nextgenusfs** [comment]
What is output of:
```
funannotate check --show-versions`
```
Do you have the ENV variable AUGUSTUS_CONFIG_PATH set and what does it point to? Have you done anything to move/shuffle the Augustus folder structure?  The AUGUSTUS_BASE variable is set as the parent directory of AUGUSTUS_CONFIG_PATH and used to traverse the augustus misc/accessory scripts.

**Comment by Faheema-khan** [comment]
The output of the above command is:


-------------------------------------------------------
Checking dependencies for 1.8.4
-------------------------------------------------------
You are running Python v 3.7.2. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 3.3.2
natsort: 7.0.1
numpy: 1.19.2
pandas: 1.1.3
psutil: 5.7.2
requests: 2.24.0
scikit-learn: 0.23.2
scipy: 1.5.2
seaborn: 0.11.0
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.50
Clone: 0.39
DBD::SQLite: 1.58
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.842
Data::Dumper: 2.167
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.51
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 1.20
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.11
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.26
threads: 2.21
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/home/faheema/funannotate_db
$PASAHOME=/home/faheema/bin/PASApipeline.v2.4.1
$TRINITY_HOME=/sw/bioinfo/trinity/2.9.1/rackham
$EVM_HOME=/home/faheema/bin/EVidenceModeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/proj/uppstore2018147/nobackup/private/Faheema/annot_test/augustus_config
$GENEMARK_PATH=/sw/apps/bioinfo/GeneMark/4.57-es/rackham
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.9.1
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 2.0.4
emapper.py: 1.0.3
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2018-07-04
gmes_petap.pl: 4.57_lic
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 1.8.0_151
kallisto: 0.45.1
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.10.1+
minimap2: 2.16-r922
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 1.1.0
samtools: samtools 1.10
signalp: 4.1
snap: 2006-07-28
stringtie: 1.3.3
tRNAscan-SE: 1.3.1 (January 2012)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.10.1+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed

**Comment by nextgenusfs** [comment]
Okay, so looks like you've done a custom install of Augustus, ie it is expecting this:
```
$ ls -l $AUGUSTUS_CONFIG_PATH
total 0
drwxr-xr-x    8 jon  staff   256B Mar 26  2018 cgp/
drwxr-xr-x   13 jon  staff   416B Mar 26  2018 extrinsic/
drwxr-xr-x   27 jon  staff   864B Mar 26  2018 model/
drwxr-xr-x    5 jon  staff   160B Mar 26  2018 profile/
drwxr-xr-x  115 jon  staff   3.6K Dec 28  2019 species/
```
```
$ ls -l $AUGUSTUS_CONFIG_PATH/../
total 344
-rw-r--r--    1 jon  staff    18K Mar 26  2018 HISTORY.TXT
-rw-r--r--    1 jon  staff    34K Mar 26  2018 LICENSE.txt
-rw-r--r--    1 jon  staff   1.5K Mar 26  2018 Makefile
-rw-r--r--    1 jon  staff    20K Mar 26  2018 README-cgp.txt
-rw-r--r--    1 jon  staff    51K Mar 26  2018 README.TXT
-rw-r--r--    1 jon  staff   2.4K Mar 26  2018 README.md
drwxr-xr-x   13 jon  staff   416B Mar 26  2018 auxprogs/
drwxr-xr-x   10 jon  staff   320B Jan 26  2019 bin/
-rw-r--r--    1 jon  staff   680B Mar 26  2018 common.mk
drwxr-xr-x    8 jon  staff   256B Oct 19  2019 config/
drwxr-xr-x   15 jon  staff   480B Mar 26  2018 docs/
drwxr-xr-x   16 jon  staff   512B Mar 26  2018 examples/
drwxr-xr-x   51 jon  staff   1.6K Mar 26  2018 include/
-rw-r--r--    1 jon  staff    27K Mar 26  2018 retraining.html
drwxr-xr-x   92 jon  staff   2.9K Mar 26  2018 scripts/
drwxr-xr-x  112 jon  staff   3.5K Nov  1  2018 src/
```
It is using the $AUGUSTUS_CONFIG_PATH/../ --> $AUGUSTUS_BASE in order to find the $AUGUSTSU_CONFIG_PATH/../scripts/ directory.

**Comment by Faheema-khan** [comment]
The env variable $AUGUSTUS_CONFIG_PATH=/proj/uppstore2018147/nobackup/private/Faheema/annot_test/augustus_config is set to my current working directory where I have copied the configuration folder from the original location location of the Augustus  installation. 

So, when I do ls -l. I get this:
(funannotate2) [faheema@rackham2 annot_test]$ ls -l $AUGUSTUS_CONFIG_PATH
total 28
drwxrwsr-x   2 faheema uppstore2018147  4096 May 22  2019 cgp
drwxrwsr-x   2 faheema uppstore2018147  4096 May 22  2019 extrinsic
drwxrwsr-x   2 faheema uppstore2018147  4096 May 22  2019 model
drwxrwsr-x   2 faheema uppstore2018147  4096 May 22  2019 profile
drwxrwsr-x 110 faheema uppstore2018147 12288 May 22  2019 species

**Comment by nextgenusfs** [comment]
Yep -- you need to have the parent folder available that has the $AUGUSTUS_CONFIG_PATH/../scripts folder.

**Comment by Faheema-khan** [comment]
So, I am actually loading a module from the cluster, where I am running my analysis. i.e module load augustus/3.3.3

**Comment by Faheema-khan** [comment]
> Yep -- you need to have the parent folder available that has the $AUGUSTUS_CONFIG_PATH/../scripts folder.

I guess, it is available.

**Comment by nextgenusfs** [comment]
```
$ ls -l $AUGUSTUS_CONFIG_PATH/../scripts
total 1592
-rw-r--r--  1 jon  staff    12K Mar 26  2018 README.autoAug
-rw-r--r--  1 jon  staff    12K Mar 26  2018 SplicedAlignment.pm
drwxr-xr-x  4 jon  staff   128B Mar 26  2018 aln2wig/
-rwxr-xr-x  1 jon  staff   3.0K Mar 26  2018 augustus2browser.pl*
-rwxr-xr-x  1 jon  staff   389B Mar 26  2018 augustus2gbrowse.pl*
-rwxr-xr-x  1 jon  staff    48K Mar 26  2018 autoAug.pl*
-rwxr-xr-x  1 jon  staff    20K Mar 26  2018 autoAugPred.pl*
-rwxr-xr-x  1 jon  staff    43K Mar 26  2018 autoAugTrain.pl*
-rw-r--r--  1 jon  staff   195B Mar 26  2018 autoRun.pathInfo
-rwxr-xr-x  1 jon  staff   3.3K Mar 26  2018 bedgraph2wig.pl*
-rwxr-xr-x  1 jon  staff   4.3K Mar 26  2018 blat2gbrowse.pl*
-rwxr-xr-x  1 jon  staff    30K Mar 26  2018 blat2hints.pl*
-rwxr-xr-x  1 jon  staff    11K Mar 26  2018 block2prfl.pl*
-rwxr-xr-x  1 jon  staff   2.2K Mar 26  2018 cegma2gff.pl*
-rwxr-xr-x  1 jon  staff   3.8K Mar 26  2018 checkParamArchive.pl*
-rw-r--r--  1 jon  staff   1.1K Mar 26  2018 checkUTR
-rwxr-xr-x  1 jon  staff   535B Mar 26  2018 cleanDOSfasta.pl*
-rwxr-xr-x  1 jon  staff   7.4K Mar 26  2018 clusterAndSplitGenes.pl*
-rwxr-xr-x  1 jon  staff   4.8K Mar 26  2018 createAugustusJoblist.pl*
-rwxr-xr-x  1 jon  staff   3.2K Mar 26  2018 del_from_prfl.pl*
-rwxr-xr-x  1 jon  staff   9.3K Mar 26  2018 evalCGP.pl*
-rwxr-xr-x  1 jon  staff   3.0K Mar 26  2018 exonerate2hints.pl*
-rwxr-xr-x  1 jon  staff   1.3K Mar 26  2018 exoniphyDb2hints.pl*
-rwxr-xr-x  1 jon  staff   507B Mar 26  2018 extractTranscriptEnds.pl*
-rwxr-xr-x  1 jon  staff   435B Mar 26  2018 filter-ppx.pl*
-rwxr-xr-x  1 jon  staff   850B Mar 26  2018 filterGenes.pl*
-rwxr-xr-x  1 jon  staff   1.8K Mar 26  2018 filterGenesIn_mRNAname.pl*
-rwxr-xr-x  1 jon  staff   1.7K Mar 26  2018 filterGenesOut_mRNAname.pl*
-rwxr-xr-x  1 jon  staff   1.1K Mar 26  2018 filterInFrameStopCodons.pl*
-rwxr-xr-x  1 jon  staff   2.9K Mar 26  2018 filterMaf.pl*
-rwxr-xr-x  1 jon  staff    17K Mar 26  2018 filterPSL.pl*
-rwxr-xr-x  1 jon  staff   4.4K Mar 26  2018 filterShrimp.pl*
-rwxr-xr-x  1 jon  staff   2.0K Mar 26  2018 filterSpliceHints.pl*
-rwxr-xr-x  1 jon  staff   3.0K Mar 26  2018 gbSmallDNA2gff.pl*
-rw-r--r--  1 jon  staff   7.9K Mar 26  2018 gbrowse.conf
-rwxr-xr-x  1 jon  staff   3.7K Mar 26  2018 gbrowseold2gff3.pl*
-rwxr-xr-x  1 jon  staff   7.0K Mar 26  2018 getAnnoFasta.pl*
-rwxr-xr-x  1 jon  staff    17K Mar 26  2018 gff2gbSmallDNA.pl*
-rw-r--r--  1 jon  staff   1.7K Mar 26  2018 gff2ps_mycustom
-rwxr-xr-x  1 jon  staff   4.0K Mar 26  2018 gffGetmRNA.pl*
-rwxr-xr-x  1 jon  staff   3.0K Mar 26  2018 gp2othergp.pl*
-rwxr-xr-x  1 jon  staff    13K Mar 26  2018 gtf2gff.pl*
-rwxr-xr-x  1 jon  staff    12K Mar 26  2018 hal2maf_split.pl*
-rw-r--r--  1 jon  staff   8.0K Mar 26  2018 helpMod.pm
-rwxr-xr-x  1 jon  staff   4.4K Mar 26  2018 intron2exex.pl*
-rwxr-xr-x  1 jon  staff   1.4K Mar 26  2018 joinPeptides.pl*
-rwxr-xr-x  1 jon  staff   8.5K Mar 26  2018 join_aug_pred.pl*
-rwxr-xr-x  1 jon  staff   1.2K Mar 26  2018 join_mult_hints.pl*
-rwxr-xr-x  1 jon  staff   3.4K Mar 26  2018 maf2conswig.pl*
-rwxr-xr-x  1 jon  staff   468B Mar 26  2018 makeMatchLists.pl*
-rwxr-xr-x  1 jon  staff    16K Mar 26  2018 makeUtrTrainingSet.pl*
-rwxr-xr-x  1 jon  staff   1.6K Mar 26  2018 maskNregions.pl*
-rwxr-xr-x  1 jon  staff   2.0K Mar 26  2018 moveParameters.pl*
-rwxr-xr-x  1 jon  staff    20K Mar 26  2018 msa2prfl.pl*
-rwxr-xr-x  1 jon  staff   6.9K Mar 26  2018 new_species.pl*
-rwxr-xr-x  1 jon  staff   6.9K Mar 26  2018 opt_init_and_term_probs.pl*
-rwxr-xr-x  1 jon  staff    63K Mar 26  2018 optimize_augustus.pl*
-rwxr-xr-x  1 jon  staff   3.5K Mar 26  2018 parseSim4Output.pl*
-rwxr-xr-x  1 jon  staff    17K Mar 26  2018 partition_gtf2gb.pl*
-rwxr-xr-x  1 jon  staff   2.1K Mar 26  2018 pasapolyA2hints.pl*
-rwxr-xr-x  1 jon  staff   3.3K Mar 26  2018 peptides2alternatives.pl*
-rwxr-xr-x  1 jon  staff   6.6K Mar 26  2018 peptides2hints.pl*
-rwxr-xr-x  1 jon  staff   2.7K Mar 26  2018 phastconsDB2hints.pl*
-rwxr-xr-x  1 jon  staff   2.3K Mar 26  2018 polyA2hints.pl*
-rwxr-xr-x  1 jon  staff    10K Mar 26  2018 prints2prfl.pl*
-rwxr-xr-x  1 jon  staff   7.8K Mar 26  2018 pslMap.pl*
-rwxr-xr-x  1 jon  staff   1.6K Mar 26  2018 randomSplit.pl*
-rwxr-xr-x  1 jon  staff   584B Mar 26  2018 ratewig.pl*
-rwxr-xr-x  1 jon  staff   1.9K Mar 26  2018 retroDB2hints.pl*
-rwxr-xr-x  1 jon  staff   1.4K Mar 26  2018 rmRedundantHints.pl*
-rwxr-xr-x  1 jon  staff   723B Mar 26  2018 runAllSim4.pl*
-rwxr-xr-x  1 jon  staff   4.9K Mar 26  2018 samMap.pl*
-rwxr-xr-x  1 jon  staff   1.1K Mar 26  2018 scipiogff2gff.pl*
-rwxr-xr-x  1 jon  staff   531B Mar 26  2018 selectLongestORFs.pl*
-rwxr-xr-x  1 jon  staff   1.2K Mar 26  2018 simpleFastaHeaders.pl*
-rwxr-xr-x  1 jon  staff   2.5K Mar 26  2018 simplifyFastaHeaders.pl*
-rwxr-xr-x  1 jon  staff   1.7K Mar 26  2018 splitMfasta.pl*
-rwxr-xr-x  1 jon  staff   861B Mar 26  2018 split_wiggle.pl*
-rwxr-xr-x  1 jon  staff   2.1K Mar 26  2018 summarizeACGTcontent.pl*
-rwxr-xr-x@ 1 jon  staff    18K Mar 26  2018 transMap2hints.pl*
-rwxr-xr-x  1 jon  staff   1.9K Mar 26  2018 uniquePeptides.pl*
-rwxr-xr-x  1 jon  staff   2.3K Mar 26  2018 utrgff2gbrowse.pl*
-rw-r--r--  1 jon  staff   2.6K Mar 26  2018 webserver-results.body
-rw-r--r--  1 jon  staff   2.1K Mar 26  2018 webserver-results.head
-rw-r--r--  1 jon  staff   3.0K Mar 26  2018 webserver-results.tail
-rwxr-xr-x  1 jon  staff   1.6K Mar 26  2018 weedMaf.pl*
-rwxr-xr-x  1 jon  staff   5.2K Mar 26  2018 wig2hints.pl*
-rwxr-xr-x  1 jon  staff   2.8K Mar 26  2018 wigchoose.pl*
-rwxr-xr-x  1 jon  staff    15K Mar 26  2018 writeResultsPage.pl*
-rwxr-xr-x  1 jon  staff   9.5K Mar 26  2018 yaml2gff.1.4.pl*
```

**Comment by Faheema-khan** [comment]
Thanks alot for your prompt reply and detailed explanation! I will give it a try now.

**Comment by Faheema-khan** [comment]
It worked. Thanks once again for your help!
Best,
Faheema
