### ISSUE TITLE
Funannotate train fail when uploading mysql due to Duplicate entry from merging transcripts

### ISSUE THREAD

**Issue by supnOvel** [nextgenusfs/funannotate#535]
**Are you using the latest release?**
yes

**Describe the bug**
When supplying pre-assembled trinity-gg transcripts and pacbio/nanapore trinity-gg-transcripts (not reads), I encountered Duplicate entry errors in every mysql uploadings.  At the first time, I checked the fasta ID in case of duplicated ones but I am not right. Several debugging steps and runs, I found the problem lies with the minimap2 mapping step. In lines 262-272 of train.py, minimap2 was used to map long reads to the trinity transcripts and those unmapped ones were merged with the latter. In the crosscheckBAM, duplicates occurred due to split alignments of long transcripts, hence the resulting trinity.long-reads.fasta with duplicated IDs. It might be a bug but might not. Believe you can easily fix this.

**What command did you issue?**
```
funannotate train -i Fxan_genome_masked.fasta -o Fxan --trinity trinity_gg_illumina.fasta --pacbio_isoseq hq_pacbio.fasta --nanopore_cdna trinity_gg_ont.fasta --memory 120G --pasa_db mysql --pasa_min_pct_aligned 95 --max_intronlen 20000 --species "Fragaria ananassa" --cpus 40 --no_trimmomatic
```
**Logfiles**
[Fri Jan 22 00:08:10 2021] Running CMD: /home/chenq/miniconda3/envs/funannotate/opt/pasa-2.4.1/scripts/upload_transcript_data.dbi -M 'Fragaria_ananassa' -t /home/chenq/genome_anotation/Fxan/training/trinity.long-reads.fasta.clean  -f NULL 
DBD::mysql::db do failed: Duplicate entry 'p_18204' for key 'cdna_acc_idx' at /home/chenq/miniconda3/envs/funannotate/opt/pasa-2.4.1/PerlLib/DB_connect.pm line 221, <$filehandle> line 389292.
failed query: < insert into cdna_info (cdna_acc, is_assembly, is_fli, is_TDN, length, header) values (?,?,?,?,?,?) >	values: p_18204 0 0 0 145 p_18204
Errors: Duplicate entry 'p_18204' for key 'cdna_acc_idx'
 at /home/chenq/miniconda3/envs/funannotate/opt/pasa-2.4.1/PerlLib/DB_connect.pm line 233, <$filehandle> line 389292.
	DB_connect::RunMod(DB_connect=HASH(0x7f6160338380), " insert into cdna_info (cdna_acc, is_assembly, is_fli, is_TDN"..., "p_18204", 0, 0, 0, 145, "p_18204") called at /home/chenq/miniconda3/envs/funannotate/opt/pasa-2.4.1/scripts/upload_transcript_data.dbi line 97
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::mysql::db handle database=Fragaria_ananassa;host=localhost.
Error, cmd: /home/chenq/miniconda3/envs/funannotate/opt/pasa-2.4.1/scripts/upload_transcript_data.dbi -M 'Fragaria_ananassa' -t /home/chenq/genome_anotation/Fxan/training/trinity.long-reads.fasta.clean  -f NULL  died with ret 6400 No such file or directory at /home/chenq/miniconda3/envs/funannotate/opt/pasa-2.4.1/PerlLib/Pipeliner.pm line 187.
	Pipeliner::run(Pipeliner=HASH(0x7ff05f160a20)) called at /home/chenq/miniconda3/envs/funannotate/opt/pasa-2.4.1/Launch_PASA_pipeline.pl line 1044

**OS/Install Information**

Checking dependencies for 1.8.3
\-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.15
matplotlib: 2.2.5
natsort: 6.2.0
numpy: 1.16.6
pandas: 0.24.2
psutil: 5.7.0
requests: 2.25.1
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp:1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/chenq/funannotate_db
$PASAHOME=/home/chenq/miniconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/chenq/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/chenq/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/chenq/miniconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/chenq/tools/gmes_linux_64
All 6 environmental variables are set
\-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.4.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 2.0.6
emapper.py: /home/chenq/miniconda3/envs/funannotate/bin/diamond /home/chenq/miniconda3/envs/funannotate/lib/python2.7/site-packages
emapper-2.0.1

ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.62_lic
hmmscan: HMMER 3.3.1 (Jul 2020)
hmmsearch: HMMER 3.3.1 (Jul 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.27
pslCDnaFilter: no way to determine
salmon: salmon 0.15.0
samtools: samtools 1.10
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.1.4
tRNAscan-SE: 2.0.7 (Oct 2020)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: hisat2 not installed

Please neglect the hisat2 error, it was correctly installed, and all funannotate tests can be passed.

**Comment by nextgenusfs** [comment]
Thanks for reporting and providing all this info, A+ on error report ;).  I'll try to take a look and see if I can replicate -- if my memory serves that step is running minimap2 with `--secondary=no`, so I thought that should be only yielding primary alignments, ie there shouldn't be duplicates?  

So you mentioned that you check FASTA headers for duplicates and didn't find them?  

> In the crosscheckBAM, duplicates occurred due to split alignments of long transcripts, hence the resulting trinity.long-reads.fasta with duplicated IDs

So what gets passed to PASA is the `trinity.long-reads.fasta` and the `trinity.long-reads.fasta.clean` -- and you said there are duplicate FASTA headers here?

**Comment by supnOvel** [comment]
Thank you for your quick reply.  I have checked fasta header using seqkit rmdup to make sure no replicates.  There did exist duplicates ID in Trinity. long-reads.fasta. --secondary=no avoid multiple mapping but not split alignment that was recorded here https://github.com/lh3/minimap2/blob/master/FAQ.md

**Comment by nextgenusfs** [comment]
Does that check for duplicate sequences or duplicate headers?  Just trying to make sure I understand exactly what I need to change. I think we don't want duplicate sequences nor duplicate headers.  It is relatively trivial to add a "unique header" function after this step to ensure this can't happen.

**Comment by supnOvel** [comment]
> Does that check for duplicate sequences or duplicate headers? Just trying to make sure I understand exactly what I need to change. I think we don't want duplicate sequences nor duplicate headers. It is relatively trivial to add a "unique header" function after this step to ensure this can't happen.

The headers has duplicates.  The sequences with same headers were different, corresponding to segments of the same transcripts in long reads.

**Comment by nextgenusfs** [comment]
Okay, and then last technical question -- in this case since the long reads showed that more than 1 trinity transcript should in fact be a single transcript, perhaps we should rather keep the long transcript in addition to the trinity transcripts.  Or is there is having a long read that spans multiple trinity transcript enough evidence to keep only the long read (discarding those trinity transcripts). I guess functionally we just need to add a samtools filter step on "chimeric" alignments to keep those in the transcript pool.

**Comment by supnOvel** [comment]
Sorry for the late response. At this time I can not say which evidence is more trustworthy than the other. The pacbio transcripts were derived from the clustering of 627,654 full-length nonchimeric reads after error correction using illumina reads. For me, among the 1148 long-reads (containing 15 duplicates) that were not represented in the Trinity assemblies, I am not sure these 15 long pacbio transcripts were correct without other evidence. I have deleted all of them (as not reliable ones).

**Comment by nextgenusfs** [comment]
Thanks, I'll just do this slightly differently I think.  The point of trying to do this was to reduce the "load" on PASA so that it wasn't dealing with a bunch of very similar ONT/PacBio reads -- at the time I wrote this there wasn't really any good clustering tools for the noisy reads.  But I'll work on a fix right now and let you know when its ready, hopefully you will be able to test.

**Comment by nextgenusfs** [comment]
@supnOvel, one other thing.  Can you check if there are duplicate fasta headers in this file: `long-reads.mapped.fasta`? This is the precursor filtering step, ie reads that map to the genome.

**Comment by supnOvel** [comment]
I have checked the headers of the file long-reads.mapped.fasta, no duplicated headers are found. They are exactly corresponding to headers of iso-seq.fasta and nano-cdna.fasta. 

Thanks Jon.

**Comment by supnOvel** [comment]
> @supnOvel, one other thing. Can you check if there are duplicate fasta headers in this file: `long-reads.mapped.fasta`? This is the precursor filtering step, ie reads that map to the genome.

I have checked the headers of the file long-reads.mapped.fasta, no duplicated headers are found. They are exactly corresponding to headers of iso-seq.fasta and nano-cdna.fasta.

Thanks Jon.

**Comment by nextgenusfs** [comment]
Great, thanks for info.  I've pushed some fixes, revamped how those steps are done -- essentially doing it a bit cleaner which should prevent any duplicates being pushed to PASA.  You can install over the top of your existing in the same environment with pip, ie:
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git
```
You'll likely need to either delete all the intermediate files after Trinity or just start a new output run to test (ie clean output folder is probably better).

**Comment by supnOvel** [comment]
Great, thanks. I will restart a new trial with this update.
