### ISSUE TITLE
Question:Can I provide to funannotate predict several bam files?

### ISSUE THREAD

**Issue by el42008** [nextgenusfs/funannotate#54]
Hi, 

Can I provide to funannotate predict several bam files? 

I have a another  question about portcullis and PASA. Since I have run mikado already with portcullis and transdecoder and I got the final mikado.loci.gff3.
Do you think is necessary to use PASA if I have already used Portcullis? Do PASA and Portcullis do the same thing?

I am about to try funannotate predict .So instead of using PASA I was going to provide the final mikado.gff3 file to the option --pasa_gff Do you think this is sensible?

4.	Now you have an assembly, RNA_seq.bam, PASA_assemblies.gff3, and transcripts you can run funannotate like so:
funannotate predict -i genome.final.fa -o fun_out --species "Fungus specious" \
    --pasa_gff genome.fasta.transdecoder.genome.gff3 --rna_bam RNA_seq.bam \
    --transcript_evidence transcripts.fasta --cpus 12

Thank you very much

Elena

**Comment by nextgenusfs** [comment]
Hi Elena,
I'm not familiar with `mikado` or `portcullis` - a quick search suggests that they may do something similar to PASA -> transdecoder, but are also very new tools?  Can you post a bit of the GFF3 file from `mikado`, i.e. maybe `head -n 20 mikado.loci.gff3`.  

You can merge BAM files with `samtools merge` just be sure that the BAM file you pass to funannotated is sorted (`samtools sort`). 

When you pass a BAM file, funannotate will run the BRAKER1 pipeline to train Augustus and GeneMark.  The --pasa_gff gene models are passed directly to Evidence Modeler, so depending on what the mikado GFF3 file looks like, this may work right away, otherwise shouldn't take much to get it to work, assuming the GFF3 files are EVM compliant.  You can check that by running: 
```
$EVM_HOME/EvmUtils/gff3_gene_prediction_file_validator.pl mikado.loci.gff3
```
Jon

**Comment by el42008** [comment]
Hi Jon,

Thank you for your early answer. This is a chomp of mikado gff3 file:

C100005 Mikado_loci     superlocus      1       201     .       +
.       ID=Mikado_superlocus:C100005+:1-201;Name=superlocus:C100005+:1-201
C100005 Mikado_loci     ncRNA_gene      1       201     15      +
.
ID=mikado.C100005G1;Name=mikado.C100005G1;multiexonic=False;superlocus=Mikado_superlocus:C100005+:1-201
C100005 Mikado_loci     ncRNA   1       201     15      +       .
ID=mikado.C100005G1.1;Parent=mikado.C100005G1;Name=illu_stringtie_stolon_L1_1608_last_illumina_stolon_L1_1608.39233.1;alias=illu_stringtie_stolon_L1_1608_last_illumina_stolon_L1_1608.39233.1;fpkm=0.312273;tpm=0.514968;cov=3.895522;primary=True
C100005 Mikado_loci     exon    1       201     .       +       .
ID=mikado.C100005G1.1.exon1;Parent=mikado.C100005G1.1
C100007 Mikado_loci     superlocus      1       202     .       +
.       ID=Mikado_superlocus:C100007+:1-202;Name=superlocus:C100007+:1-202
C100007 Mikado_loci     ncRNA_gene      1       202     15      +
.
ID=mikado.C100007G1;Name=mikado.C100007G1;multiexonic=False;superlocus=Mikado_superlocus:C100007+:1-202
C100007 Mikado_loci     ncRNA   1       202     15      +       .
ID=mikado.C100007G1.1;Parent=mikado.C100007G1;Name=illu_stringtie_leaf_L1_1632_last_illumina_leaf_L1_1632.32951.1;alias=illu_stringtie_leaf_L1_1632_last_illumina_leaf_L1_1632.32951.1;fpkm=0.265315;tpm=0.356807;cov=3.497690;primary=True
C100007 Mikado_loci     exon    1       202     .       +       .
ID=mikado.C100007G1.1.exon1;Parent=mikado.C100007G1.1
C100015 Mikado_loci     superlocus      1       202     .       -
.       ID=Mikado_superlocus:C100015-:1-202;Name=superlocus:C100015-:1-202
C100015 Mikado_loci     ncRNA_gene      1       202     15      -
.
ID=mikado.C100015G1;Name=mikado.C100015G1;multiexonic=False;superlocus=Mikado_superlocus:C100015-:1-202

Thanks



2017-03-23 15:49 GMT+00:00 Jon Palmer <notifications@github.com>:

**Comment by nextgenusfs** [comment]
I don't know what EVM will do with the 'superlocus' tag as the is non-standard, you'll have to run through the EVM GFF3 validation script in previous message.  Currently, funannotate is hard-coded to expect `transdecoder` in column 2 of the PASA gff file.  So if the mikado.gff3 passes the EVM GFF3 validation, you could quickly convert your GFF3 file into a format that funanntoate is expecting by doing:
```
sed 's/\tMikado_loci\t/\ttransdecoder\t/g' mikado.loci.gff3 > mikado.loci.funannotate.gff3
```
This will swap column 2 to have the source of transdecoder.  I should be able to make this more dynamic in future version of funannotate to skip this requirement. 

Jon

**Comment by el42008** [comment]
Hi Jon,

I have check the gff mile and I got this error

Fatal Error, cannot locate data entry for ID: [mikado.C195451G1.1] at
/mnt/apps/EVidenceModeler/1.1.1/EvmUtils/
gff3_gene_prediction_file_validator.pl line 125.


2017-03-23 17:20 GMT+00:00 Jon Palmer <notifications@github.com>:

**Comment by lalalagartija** [comment]
Hi, 
merging bam files can result in chimeras in the case of alternative spicing no ? Is there any other way to avoid merging them ? 
Thanks
