### ISSUE TITLE
[Question]  When running funannotate predict what are the --rna_bam alignments.bam inputs?

### ISSUE THREAD

**Issue by Lamm-a** [nextgenusfs/funannotate#541]
When running `funannotate predict` are the `alignments.bam` for the `--rna_bam` flag raw transcript reads aligned to the assembled genome or an assemblesd transcripts aligned to the assembled genome?

**Comment by nextgenusfs** [comment]
Raw (well quality filtered) illumina rna seq reads. The train script used hisat2 to generate this alignment.

**Comment by Lamm-a** [comment]
Okay thank you. Are we fine to use any old aligner, e.g. BWA, to produce these BAMs?

**Comment by hyphaltip** [comment]
generally those are run by hisat2 and done internally so unless you have a reason, why not use what already is part of the train pipeline step anyways - do you need to do your own aligmment? - BWA doesn't account for introns so I would not use that.

**Comment by Lamm-a** [comment]
> generally those are run by hisat2 and done internally so unless you have a reason, why not use what already is part of the train pipeline step anyways - do you need to do your own aligmment? - BWA doesn't account for introns so I would not use that.

I can't see any reference tot he train pipeline before using the predict pipeline. Would you be able to point me in the direction of it please?
