### ISSUE TITLE
Busco4 error after makeblastdb: fasta not found for Tblastn job

### ISSUE THREAD

**Issue by ARW-UBT** [nextgenusfs/funannotate#542]
Hello

I am using busco4 via conda. 
It worked without problems so far with other transcriptome assemblies. But I ran into an eror with the latest assembly.
Dou you have any suggestions how to solve the issue?

Best regards.

**Describe the bug**
Busco4 exit with the message below. 

**What command did you issue?**
see below

**Logfiles**
see attachment

**OS/Install Information**
 -  output of `funannotate check --show-versions`
 funannotate is not avaialble within the conda environment

busco --config config.ini --mode transcriptome --auto-lineage-euk --update-data -i extr-SFB-MP-00543-Geneious.fasta -o Busco_run_A02-Exp007-Geneious-Geneious -f
INFO:	***** Start a BUSCO v4.0.6 analysis, current time: 02/05/2021 09:24:24 *****
INFO:	Configuring BUSCO with config.ini
INFO:	Mode is transcriptome
INFO:	'Force' option selected; overwriting previous results directory
INFO:	Input file is extr-SFB-MP-00543-Geneious.fasta
INFO:	Downloading information on latest versions of BUSCO data...
INFO:	No lineage specified. Running lineage auto selector.

INFO:	***** Starting Auto Select Lineage *****
	This process runs BUSCO on the generic lineage datasets for the domains archaea, bacteria and eukaryota. Once the optimal domain is selected, BUSCO automatically attempts to find the most appropriate BUSCO dataset to use based on phylogenetic placement.
	--auto-lineage-euk and --auto-lineage-prok are also available if you know your input assembly is, or is not, an eukaryote. See the user guide for more information.
	A reminder: Busco evaluations are valid when an appropriate dataset is used, i.e., the dataset belongs to the lineage of the species to test. Because of overlapping markers/spurious matches among domains, busco matches in another domain do not necessarily mean that your genome/proteome contains sequences from this domain. However, a high busco score in multiple domains might help you identify possible contaminations.
INFO:	Running BUSCO using lineage dataset eukaryota_odb10 (eukaryota, 2020-09-10)
INFO:	Creating BLAST database with input file
INFO:	Running 1 job(s) on makeblastdb
INFO:	[makeblastdb]	1 of 1 task(s) completed
ERROR:	DB /home/weig/busco_out/Busco_run_A02-Exp007-Geneious-Geneious/blast_db/extr-SFB-MP-00543-Geneious.fasta not found for tblastn job
ERROR:	BUSCO analysis failed !
ERROR:	Check the logs, read the user guide, and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues

**Comment by ARW-UBT** [comment]
Attachment here.
[busco.log](https://github.com/nextgenusfs/funannotate/files/5931138/busco.log)

**Comment by nextgenusfs** [comment]
Funannotate uses an internal modified BUSCO v2. Version 4 not supported.
