### ISSUE TITLE
Busco5 conda: config.ini missing

### ISSUE THREAD

**Issue by ARW-UBT** [nextgenusfs/funannotate#544]
Hi, 
I just omstalled the lated busco5 conda environment, and detected some error messages during the runs. 
One error indicates that no config.ini files has been specified. 
 I have tried to locate this file, but there is no config.ini present in the busco5 environment. 
I looked it up in the busco4 conda env, and found this file at miniconda3/envs/busco4/config/config.ini
The same folder exists unter busco5, however without ths ini file. 

Can I use the v4 config.ini, or has something changed?

Best regards,

**Comment by nextgenusfs** [comment]
You might get some help on the BUSCO git lab repo....
