### ISSUE TITLE
Not enough gene models 4 to train Augustus (200 required), exiting

### ISSUE THREAD

**Issue by Ram-Nagar** [nextgenusfs/funannotate#545]
**Are you using the latest release?**
How do I update the tool 

**Describe the bug**
While annotation an spades assembly of a ascomycetes fungus I am gating the error "Not enough gene models 4 to train Augustus (200 required), exiting". 
I initially run busco on the default  Dikarya database but then change to the ascomycota_odb10 but got the same low gene models error. I then run busco outside the funannotate and got more than 95 percent busco coverage. 

The second issue I have is with GeneMark. I have downloaded it and put the directory in the path but it throwing a perl module error "Can't locate YAML.pm in @INC (you may need to install the YAML module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./gmes_petap.pl line 76.
BEGIN failed--compilation aborted at ./gmes_petap.pl line 76.

**What command did you issue?**
funannotate predict --cpus 12 -i GCA_002194535.1_ASM219453v1_genomic_clean_sorted_masked.fna -s "Fusarium udum" \
--transcript_evidence ./Fol_4287/GCF_000149955.1_ASM14995v2_rna.fna \
-o fusarium_udum_annotation --busco_db /home/pjain/mytools/busco_db/ascomycota_odb10 --busco_seed_species fusarium

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.15
matplotlib: 2.2.5
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.25.1
scikit-learn: 0.20.4
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.30
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/pjain/funannotate_db
$PASAHOME=/home/pjain/miniconda3/envs/funannotate/opt/pasa-2.4.1
$EVM_HOME=/home/pjain/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/pjain/miniconda3/envs/funannotate/config/
	ERROR: TRINITYHOME not set. export TRINITYHOME=/path/to/dir
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
Can't locate YAML.pm in @INC (you may need to install the YAML module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/pjain/mytools/gmes_linux_64/gmes_petap.pl line 76.
BEGIN failed--compilation aborted at /home/pjain/mytools/gmes_linux_64/gmes_petap.pl line 76.
	ERROR: gmes_petap.pl found but error running gmes_petap.pl
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.4.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.6
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.0
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.2
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.10.0+
minimap2: 2.17-r941
pslCDnaFilter: no way to determine
salmon: salmon 1.4.0
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.4
tRNAscan-SE: 2.0.7 (Oct 2020)
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.10.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: gmes_petap.pl not installed
	ERROR: proteinortho not installed
	ERROR: signalp not installed
	ERROR: tantan not installed

**Comment by nextgenusfs** [comment]
Need to downgrade Augustus to < 3.4, the new release is not working with BUSCO In funannotate. The Perl module error, make sure you are installing the module in the version of Perl that is in the environment during funannotate runtime. And check the shebang line of all Perl scripts in genemark, by default it is set to use system Perl, that most likely needs to be set to env Perl.
