### ISSUE TITLE
Installing other programs in Docker

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/funannotate#546]
Hi Jon,

I am trying to install funannotate with Docker (installing with Conda was taking just too long). 
The installation works great and is super fast. If I run "funannotate-docker test -t predict --cpus 12" everything works perfectly. 

However, I would like to install some of the missing packages:

funannotate-docker check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.4
-------------------------------------------------------
You are running Python v 3.7.9. Now checking python packages...
biopython: 1.78
goatools: 1.0.15
matplotlib: 3.3.4
natsort: 7.1.1
numpy: 1.19.5
pandas: 1.2.1
psutil: 5.8.0
requests: 2.25.1
scikit-learn: 0.24.1
scipy: 1.5.3
seaborn: 0.11.1
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.15
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/venv/config
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
Traceback (most recent call last):
  File "/venv/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/venv/lib/python3.7/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/venv/lib/python3.7/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/venv/lib/python3.7/site-packages/ete3/__init__.py)
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.6
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.1 (Jul 2020)
hmmsearch: HMMER 3.3.1 (Jul 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.4
tRNAscan-SE: 2.0.7 (Oct 2020)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: ete3 not installed
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed

I have downloaded the packages and I have them in the same folder as funannotate-docker. 

~/funannotate$ ls -l
total 7687548
drwxr-xr-x 6 aberas2 users       4096 Feb  5 03:57 eggnog-mapper
-rwxr-xr-x 1 aberas2 users        930 Feb  9 10:15 funannotate-docker
-rw-r--r-- 1 aberas2 users         84 Feb  9 08:21 gm_key_64.gz
-rw-r--r-- 1 aberas2 users 7863601901 Feb  9 08:31 interproscan-5.48-83.0-64-bit.tar.gz
-rw-r--r-- 1 aberas2 users       9661 Mar 21  2019 RepBaseRepeatMaskerEdition-20181026.tar.gz
-rw-r--r-- 1 aberas2 users    8415274 Mar  7  2019 signalp-4.1g.Linux.tar.gz

I have tried to run: " docker build -t funannotate -f funannotate-docker ." But it errors:

Sending build context to Docker daemon  59.02GB
Error response from daemon: Dockerfile parse error line 3: unknown instruction: REALPATH()

I have also tried deleting this funannotate-docker, and installing the version here: https://github.com/nextgenusfs/funannotate/blob/master/docs/docker.rst
But it also errors:

docker build -t funannotate -f Dockerfile .
Sending build context to Docker daemon  59.02GB
Step 1/9 : FROM nextgenusfs/funannotate
 ---> 3c569ec6fb9c
Step 2/9 : LABEL maintainer="Jon Palmer <nextgenusfs@gmail.com>"
 ---> Using cache
 ---> 8b0b27103e74
Step 3/9 : USER linuxbrew
 ---> Using cache
 ---> 617aaba73ca3
Step 4/9 : WORKDIR /home/linuxbrew
 ---> Using cache
 ---> 682a0a0e8b86
Step 5/9 : COPY gm_key_64.gz     signalp-4.1f.Linux.tar.gz     RepBaseRepeatMaskerEdition-20170127.tar.gz     /home/linuxbrew/
COPY failed: stat /var/lib/docker/tmp/docker-builder854705664/signalp-4.1f.Linux.tar.gz: no such file or directory

Any directions on how to fix this would be greatly appreciated. Thanks!!

**Comment by nextgenusfs** [comment]
Okay, so you'll need to do some devel/testing locally to add more things to this container, it is being built by github actions currently is a two stage build: https://github.com/nextgenusfs/funannotate/blob/master/Dockerfile and then the databases are installed in a separate step: https://github.com/nextgenusfs/funannotate/blob/master/Dockerfile2.

So what this means is that I used conda-pack to build a virtual environment and pass that onto a fresh container, this significantly saves space and makes the image smaller.  So if you start with the nextgenusfus/funannotate then you'll need to add anything else you want to run to that container and install it like it was a fresh debian image.

**Comment by nextgenusfs** [comment]
For example, this might work for signalP (untested) assuming you have tar.gz in your build directory.
```
FROM nextgenusfs/funannotate

COPY signalp-4.1g.Linux.tar.gz /venv
RUN cd /venv && \
    tar -xvzf signalp-4.1g.Linux.tar.gz && \
    rm signalp-4.1g.Linux.tar.gz && \
    cd signalp-4.1 && \
    perl -i -pe "s/\$ENV{SIGNALP} = \'\/usr\/opt\/www\/pub\/CBS\/services\/SignalP-4\.1\/signalp-4\.1\'/\$ENV{SIGNALP} = \'\/venv\/signalp-4\.1\'/" signalp && \
    perl -i -pe 's/my \$outputDir = "\/var\/tmp";/my \$outputDir = "\.";/' signalp $$ \
    ln -s /venv/signalp-4.1/signalp /venv/bin/signalp
```
