### ISSUE TITLE
funannotate-predict.py: error: unrecognized arguments: --trnascan tRNAscan.out

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#547]
**Are you using the latest release?**
Yes, as of 5th Feb 2021

1.8.2  and just tried funannotate-1.8.3 - same error
**Describe the bug**
funannotate-predict.py: error: unrecognized arguments: --trnascan tRNAscan.out 9 command not recognised for pre computed tRNAscan results. 

**What command did you issue?**
/home/pthorpe/scratch/cb/final/funannotate-master/scripts/funannotate predict -i Crenichthys_baileyi.v1.0.softmasked_tantan.fasta -o Fun_braker --species Crenichthys_baileyi --strain V.1.0 --cpus 30 --max_intronlen 15000 --organism other --busco_db eukaryota --name CRENBAI --ploidy 2 --weights glimmerhmm:0 codingquarry:0 --organism other --rna_bam cbAligned.sortedByCoord.out.bam --augustus_species Crenichthys_baileyi_BUSCO2 --genemark_gtf /home/pthorpe/scratch/cb/final/genemark.gtf --other_gff /home/pthorpe/scratch/cb/final/braker2/augustus.hints_utr.gff3:4 --SeqCenter SEQ_CENTR_TO_BE_FILLED_IN --trnascan tRNAscan.out

HI Jon,

I am using the new command to take in the precomputed tRNAscan results. This does not seem to be parsing, as failing as it doesnt recognise the command:

/home/pthorpe/scratch/cb/final/funannotate-master/scripts/funannotate predict -i Crenichthys_baileyi.v1.0.softmasked_tantan.fasta -o Fun_braker --species Crenichthys_baileyi --strain V.1.0 --cpus 30 --max_intronlen 15000 --organism other --busco_db eukaryota --name CRENBAI --ploidy 2 --weights glimmerhmm:0 codingquarry:0 --organism other --rna_bam cbAligned.sortedByCoord.out.bam --augustus_species Crenichthys_baileyi_BUSCO2 --genemark_gtf /home/pthorpe/scratch/cb/final/genemark.gtf --other_gff /home/pthorpe/scratch/cb/final/braker2/augustus.hints_utr.gff3:4 --SeqCenter SEQ_CENTR_TO_BE_FILLED_IN --trnascan tRNAscan.out
usage: funannotate-predict.py [options] -i genome.fasta
funannotate-predict.py: error: unrecognized arguments: --trnascan tRNAscan.out

THIS command is there when I ask for help. I have been through the code and cannot figure out this error, sorry!!!

$ /home/pthorpe/scratch/cb/final/funannotate-master/scripts/funannotate predict -h

Usage:       funannotate predict <arguments>
version:     1.8.2

Description: Script takes genome multi-fasta file and a variety of inputs to do a comprehensive whole
             genome gene prediction.  Uses AUGUSTUS, GeneMark, Snap, GlimmerHMM, BUSCO, EVidence Modeler,
             tbl2asn, tRNAScan-SE, Exonerate, minimap2.
Required:
  -i, --input              Genome multi-FASTA file (softmasked repeats)
  -o, --out                Output folder name
  -s, --species            Species name, use quotes for binomial, e.g. "Aspergillus fumigatus"

Optional:
  -p, --parameters         Ab intio parameters JSON file to use for gene predictors
  --isolate                Isolate name, e.g. Af293
  --strain                 Strain name, e.g. FGSCA4
  --name                   Locus tag name (assigned by NCBI?). Default: FUN_
  --numbering              Specify where gene numbering starts. Default: 1
  --maker_gff              MAKER2 GFF file. Parse results directly to EVM.
  --pasa_gff               PASA generated gene models. filename:weight
  --other_gff              Annotation pass-through to EVM. filename:weight
  --rna_bam                RNA-seq mapped to genome to train Augustus/GeneMark-ET
  --stringtie              StringTie GTF result
  -w, --weights            Ab-initio predictor and EVM weight. Example: augustus:2 or pasa:10
  --augustus_species       Augustus species config. Default: uses species name
  --min_training_models    Minimum number of models to train Augustus. Default: 200
  --genemark_mode          GeneMark mode. Default: ES [ES,ET]
  --genemark_mod           GeneMark ini mod file
  --busco_seed_species     Augustus pre-trained species to start BUSCO. Default: anidulans
  --optimize_augustus      Run 'optimze_augustus.pl' to refine training (long runtime)
  --busco_db               BUSCO models. Default: dikarya. `funannotate outgroups --show_buscos`
  --organism               Fungal-specific options. Default: fungus. [fungus,other]
  --ploidy                 Ploidy of assembly. Default: 1
  -t, --tbl2asn            Assembly parameters for tbl2asn. Default: "-l paired-ends"
  -d, --database           Path to funannotate database. Default: $FUNANNOTATE_DB

  --protein_evidence       Proteins to map to genome (prot1.fa prot2.fa uniprot.fa). Default: uniprot.fa
  --protein_alignments     Pre-computed protein alignments in GFF3 format
  --p2g_pident             Exonerate percent identity. Default: 80
  --p2g_diamond_db         Premade diamond genome database for protein2genome mapping
  --p2g_prefilter          Pre-filter hits software selection. Default: diamond [tblastn]
  --transcript_evidence    mRNA/ESTs to align to genome (trans1.fa ests.fa trinity.fa). Default: none
  --transcript_alignments  Pre-computed transcript alignments in GFF3 format
  --augustus_gff           Pre-computed AUGUSTUS GFF3 results (must use --stopCodonExcludedFromCDS=False)
  --genemark_gtf           Pre-computed GeneMark GTF results
  **--trnascan               Pre-computed tRNAscanSE results**

  --min_intronlen          Minimum intron length. Default: 10
  --max_intronlen          Maximum intron length. Default: 3000
  --soft_mask              Softmasked length threshold for GeneMark. Default: 2000
  --min_protlen            Minimum protein length. Default: 50
  --repeats2evm            Use repeats in EVM consensus model building
  --repeat_filter          Repetitive gene model filtering. Default: overlap blast [overlap,blast,none]
  --keep_no_stops          Keep gene models without valid stops
  --keep_evm               Keep existing EVM results (for rerunning pipeline)
  --SeqCenter              Sequencing facilty for NCBI tbl file. Default: CFMR
  --SeqAccession           Sequence accession number for NCBI tbl file. Default: 12345
  --force                  Annotated unmasked genome
  --cpus                   Number of CPUs to use. Default: 2
  --no-progress            Do not print progress to stdout for long sub jobs

ENV Vars:  If not specified at runtime, will be loaded from your $PATH
  --EVM_HOME
  --AUGUSTUS_CONFIG_PATH
  --GENEMARK_PATH
  --BAMTOOLS_PATH

THE FILE:

$ head tRNAscan.out
Sequence                tRNA    Bounds  tRNA    Anti    Intron Bounds   Inf
Name            tRNA #  Begin   End     Type    Codon   Begin   End     Score   Note
--------        ------  -----   ------  ----    -----   -----   ----    ------  ------
CBSF_577        1       206998  207078  Undet   NNN     0       0       27.3    pseudo
CBSF_577        2       490484  490407  Undet   NNN     0       0       20.3    pseudo
CBSF_577        3       143122  143040  Undet   NNN     0       0       25.8    pseudo
CBSF_577        4       129517  129444  Ala     TGC     0       0       21.1    pseudo
CBSF_577        5       78008   77914   Tyr     ATA     0       0       24.1    pseudo
CBSF_578        1       247277  247343  Undet   NNN     0       0       22.0
CBSF_578        2       314380  314298  Undet   NNN     0       0       21.3    pseudo

cheers,

Pete

**Comment by peterthorpe5** [comment]
**UPDATE**: If I call the python predict script directly, this command is allowed. So the main script is not passing on the call correctly/ or accepting this command?: 

predict="/home/pthorpe/scratch/cb/final/funannotate-1.8.**3/funannotate/predict.py** 
    -i ${genome} -o ${out_folder} 
    --species  ${species} 
    --strain ${strain} --cpus ${threads} 
    --max_intronlen ${max_intron_len} 
    --organism other 
    --busco_db  eukaryota
    --name ${name}
    --ploidy 2
    --weights glimmerhmm:0 codingquarry:0
	--organism other 
	--rna_bam cbAligned.sortedByCoord.out.bam
    --augustus_species Crenichthys_baileyi_BUSCO2
    --genemark_gtf  /home/pthorpe/scratch/cb/final/genemark.gtf
    --other_gff /home/pthorpe/scratch/cb/final/braker2/augustus.hints_utr.gff3:4
    --SeqCenter SEQ_CENTR_TO_BE_FILLED_IN
    -**-trnascan tRNAscan.out"**
echo ${predict} 
eval ${predict}

**Comment by peterthorpe5** [comment]
Forget that last one, it doesnt work for me:


/home/pthorpe/scratch/cb/funannotate/funannotate/predict.py -i Crenichthys_baileyi.v1.0.softmasked_tantan.fasta -o cb_funannotate --species Crenichthys_baileyi --strain V.1.0 --cpus 30 --max_intronlen 15000 --organism other --busco_db eukaryota --name CRENBAI --ploidy 2 --weights codingquarry:0 --organism other --augustus_species Crenichthys_baileyi_BUSCO2 --rna_bam cbAligned.sortedByCoord.out.bam --genemark_gtf /home/pthorpe/scratch/cb/final/genemark.gtf --SeqCenter SEQ_CENTR_TO_BE_FILLED_IN --trnascan tRNAscan.out
-------------------------------------------------------
[10:56 AM]: OS: linux2, 56 cores, ~ 395 GB RAM. Python: 2.7.15
[10:56 AM]: Running funannotate v1.8.2
[10:56 AM]: Found training files, will re-use these files:
  --pasa_gff cb_funannotate/training/funannotate_train.pasa.gff3
  --transcript_alignments cb_funannotate/training/funannotate_train.transcripts.gff3
[10:56 AM]: Skipping CodingQuarry as --organism=other. Pass a weight larger than 0 to run CQ, ie --weights codingquarry:1
[10:56 AM]: Parsed training data, run ab-initio gene predictors as follows:
  [4mProgram      Training-Method[0m
  augustus     pasa           
  genemark     selftraining   
  glimmerhmm   pasa           
  snap         pasa           
Traceback (most recent call last):
  File "/home/pthorpe/scratch/cb/funannotate/funannotate/predict.py", line 1964, in <module>
    main(sys.argv[1:])
  File "/home/pthorpe/scratch/cb/funannotate/funannotate/predict.py", line 682, in main
    bad_headers, bad_contigs, suspect_contigs = lib.analyzeAssembly(
AttributeError: 'module' object has no attribute 'analyzeAssembly'

**Comment by nextgenusfs** [comment]
Something seems wrong with your install. The lib.AnalyzeAssembly function was added after version 1.8.3, so somehow it seems you have a mixed install of multiple versions installed. My suggestion will sound painful... but likely need to clean up your install.

**Comment by peterthorpe5** [comment]
As always, thank you for your response, and love the software!!!

Yes I had it installed via conda, however, I have a hunch that tRNAscan does not like large genomes, hence my run failed as in https://github.com/nextgenusfs/funannotate/issues/523 . In this issue, you modified the code to allow pre made tRNAscan results be passed . So I downloaded and tried as several version (up to date with the master), which failed. 

I am trying a fresh install now. 

cheers,

Pete

**Comment by peterthorpe5** [comment]
Just a quick note to say I am still problem solving this. I have a fresh install. Still the same problem with tRNAscan and still the same problem with passing the --trnascan file as an option. 

I am trying a few things. Will report if I solve it.

**Comment by nextgenusfs** [comment]
I can't replicate this locally with the test data:
```
funannotate-docker predict -i test.softmasked.fa --trnascan tRNAscan.out --protein_evidence protein.evidence.fasta -o test-trnascan-file2 -s "Awesome test" --cpus 3
```
tRNAscan output was generated from previous run and then I deleted a bunch of records. 
```
$ head tRNAscan.out 
Sequence   		tRNA  	Bounds	tRNA	Anti	Intron Bounds	Inf	      
Name       	tRNA #	Begin 	End   	Type	Codon	Begin	End	Score	Note
--------   	------	----- 	------	----	-----	-----	----	------	------
CP022970.1 	1	87159 	87240 	Ser	AGA	0	0	83.2	
CP022970.1 	2	100691	100762	iMet	CAT	0	0	69.1	
CP022970.1 	3	139219	139290	Arg	TCT	0	0	67.4	
CP022970.1 	4	177652	177723	Glu	TTC	0	0	60.3	
CP022970.1 	5	207877	207948	His	GTG	0	0	57.7	
CP022970.1 	6	250477	250548	Gln	TTG	0	0	65.3	
CP022970.1 	7	355371	355442	Glu	TTC	0	0	60.3	
```

**Comment by peterthorpe5** [comment]
Hi Jon,

thank you for your reply. So to summarise: I have it working, but I had to run it (the python code in predict.py) line by line and force the pre run tRNAscan file in the correct part:

    if args.trnascan:
        lib.log.info("Existing tRNAscan results passed: {}".format(args.trnascan))
        trna_result = lib.runtRNAscan(MaskGenome, os.path.join(args.out, 'predict_misc'),
                                      tRNAscan, cpus=args.cpus, **precalc=args.trnascan**)

I cant work it out. This command, even if I hard coded the file, it did not like it **precalc=args.trnascan** - wierd, as it looks fine to me. 

My thoughts are that if you are working with a big genome (1Gbp) then tRNAscan crashes as /tmp gets full. (?). So, I split the genome up and ran it in chunks (over several nodes), cat them together. This didnt crash tRNAscan. But passing this file in was tricky. 

You can close this comment, as there is no solution here. 

JUst submitted a few genomes using Funannotate: Brilliant, your output makes it so easy to do!!!! Thank you so much of this cool software!

Pete
