### ISSUE TITLE
Exonerate failed to find alignments... 

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#55]
The pipeline works perfectly with Trinity/PASA evidences, but.... tbastn/Exonerate. Having just 1 exonerate alignment, does it mean that UniProtKB evidences will not be used in gene prediction? Any idea why this happens? Any location/DB I can check manually?  Pls find short and detailed p2g logs below. Thank you.

> [09:57:37 PM]: Aligning transcript evidence to genome with GMAP
> [10:12:35 PM]: Aligning transcript evidence to genome with BLAT
> [10:28:29 PM]: Mapping proteins to genome using tBlastn/Exonerate
> [10:28:29 PM]: Running pre-filter tBlastn step
> [10:29:36 PM]: Found 2050 preliminary alignments
> [10:31:44 PM]: Exonerate finished: found 1 alignments

> 2017-03-26 22:28:29,370: /home/osboxes/.linuxbrew/Cellar/funannotate/0.5.7/libexec/bin/funannotate-p2g.py -p /home/osboxes/data/fun_out/predict_misc/proteins.combined.fa -g /home/osboxes/data/fun_out/predict_misc/genome.softmasked.fa -o /home/osboxes/data/fun_out/predict_misc/exonerate.out --maxintron 3000 --cpus 4 --ploidy 1 --logfile /home/osboxes/data/fun_out/logfiles/funannotate-p2g.log
> 
> 2017-03-26 22:28:29,558: BLAST v2.6.0+; Exonerate v2.2.0
> 2017-03-26 22:28:29,558: Running pre-filter tBlastn step
> 2017-03-26 22:28:29,559: dustmasker -in /home/osboxes/data/fun_out/predict_misc/genome.softmasked.fa -infmt fasta -parse_seqids -outfmt maskinfo_asn1_bin -out genome_dust.asnb
> 2017-03-26 22:28:32,236: makeblastdb -in /home/osboxes/data/fun_out/predict_misc/genome.softmasked.fa -dbtype nucl -parse_seqids -mask_data genome_dust.asnb -out genome
> 2017-03-26 22:28:33,175: 
> 
> Building a new DB, current time: 03/26/2017 22:28:32
> New DB name:   /home/osboxes/data/p2g_10244/genome
> New DB title:  /home/osboxes/data/fun_out/predict_misc/genome.softmasked.fa
> Sequence type: Nucleotide
> Keep MBits: T
> Maximum file size: 1000000000B
> Mask file: genome_dust.asnb
> Adding sequences from FASTA; added 228 sequences in 0.712116 seconds.
> 
> 2017-03-26 22:28:33,176: tblastn -num_threads 4 -db genome -query /home/osboxes/data/fun_out/predict_misc/proteins.combined.fa -max_target_seqs 2 -db_soft_mask 11 -threshold 999 -max_intron_length 3000 -evalue 1e-10 -outfmt 6 -out filter.tblastn.tab
> 2017-03-26 22:29:36,501: Found 2050 preliminary alignments
> 2017-03-26 22:31:44,753: Exonerate finished: found 1 alignments

**Comment by nextgenusfs** [comment]
Seems like the multithreaded exonerate crashed, this would normally take a long time as exonerate is quite slow. Did the test data run successfully?

**Comment by nextgenusfs** [comment]
So the test data from `genome1` with this command:
```
funannotate predict -i genome1.fasta -o genome1 -s "Genome one" \
    --isolate fun1 --name GN01_ --augustus_species botrytis_cinerea \
    --protein_evidence proteins.fa --transcript_evidence transcripts.fa --cpus 6
```
should yield something like this in the p2g log file, i.e. 123 exonerate alignments:
```
2017-02-20 09:36:27,601: BLAST v2.5.0+; Exonerate v2.2.0
2017-02-20 09:36:27,601: Running pre-filter tBlastn step
2017-02-20 09:36:27,601: dustmasker -in /Users/jon/funannotate/sample_data/genome1/predict_misc/genome.softmasked.fa -infmt fasta -parse_seqids -outfmt maskinfo_asn1_bin -out genome_dust.asnb
2017-02-20 09:36:27,706: makeblastdb -in /Users/jon/funannotate/sample_data/genome1/predict_misc/genome.softmasked.fa -dbtype nucl -parse_seqids -mask_data genome_dust.asnb -out genome
2017-02-20 09:36:27,901: 

Building a new DB, current time: 02/20/2017 09:36:27
New DB name:   /Users/jon/funannotate/sample_data/p2g_16080/genome
New DB title:  /Users/jon/funannotate/sample_data/genome1/predict_misc/genome.softmasked.fa
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Mask file: genome_dust.asnb
Adding sequences from FASTA; added 3 sequences in 0.0275421 seconds.

2017-02-20 09:36:27,902: tblastn -num_threads 6 -db genome -query /Users/jon/funannotate/sample_data/genome1/predict_misc/proteins.combined.fa -max_target_seqs 2 -db_soft_mask 11 -threshold 999 -max_intron_length 3000 -evalue 1e-10 -outfmt 6 -out filter.tblastn.tab
2017-02-20 09:36:40,609: Found 556 preliminary alignments
2017-02-20 09:36:50,870: Exonerate finished: found 123 alignments
```

**Comment by MichaelFokinNZ** [comment]
Yes, for test data it did exactly as expected with 123 alignments.  
I've also tested it before on a just single real contig (of ~1Mbp) and got really low Exonerate output as well with some warinings

> 2017-03-21 15:53:52,426: Found 15348 preliminary alignments
> 2017-03-21 16:08:37,722: Exonerate finished: found 14 alignments

> 
> 017-03-21 15:27:38,196: /home/osboxes/.linuxbrew/Cellar/funannotate/0.5.7/libexec/bin/funannotate-p2g.py -p /home/osboxes/data/testN9/N9_out/predict_misc/proteins.combined.fa -g /home/osboxes/data/testN9/N9_out/predict_misc/genome.softmasked.fa -o /home/osboxes/data/testN9/N9_out/predict_misc/exonerate.out --maxintron 3000 --cpus 2 --ploidy 1 --logfile /home/osboxes/data/testN9/N9_out/logfiles/funannotate-p2g.log
> 
> 2017-03-21 15:27:38,414: BLAST v2.6.0+; Exonerate v2.2.0
> 2017-03-21 15:27:38,418: Running pre-filter tBlastn step
> 2017-03-21 15:27:38,418: dustmasker -in /home/osboxes/data/testN9/N9_out/predict_misc/genome.softmasked.fa -infmt fasta -parse_seqids -outfmt maskinfo_asn1_bin -out genome_dust.asnb
> 2017-03-21 15:27:38,645: makeblastdb -in /home/osboxes/data/testN9/N9_out/predict_misc/genome.softmasked.fa -dbtype nucl -parse_seqids -mask_data genome_dust.asnb -out genome
> 2017-03-21 15:27:38,972: 
> 
> Building a new DB, current time: 03/21/2017 15:27:38
> New DB name:   /home/osboxes/PhD_funna/p2g_23716/genome
> New DB title:  /home/osboxes/data/testN9/N9_out/predict_misc/genome.softmasked.fa
> Sequence type: Nucleotide
> Keep MBits: T
> Maximum file size: 1000000000B
> Mask file: genome_dust.asnb
> Adding sequences from FASTA; added 1 sequences in 0.0457962 seconds.
> 
> 2017-03-21 15:27:38,973: tblastn -num_threads 2 -db genome -query /home/osboxes/data/testN9/N9_out/predict_misc/proteins.combined.fa -max_target_seqs 2 -db_soft_mask 11 -threshold 999 -max_intron_length 3000 -evalue 1e-10 -outfmt 6 -out filter.tblastn.tab
> 2017-03-21 15:53:52,339: Warning: [tblastn] lcl|Query_11426 AFN_CALVI: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_17149 ANP3_PAGBO: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_57447 CDN11_LITCH: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_57448 CDN11_LITGI: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_57449 CDN11_LITSP: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_57450 CDN11_LITXA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_57451 CDN14_LITCH: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_57452 CDN14_LITXA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_57477 CDN2_LITGI: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_57480 CDN5_LITCE: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_80442 CTHL3_CAPHI: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_80987 CU049_LOCMI: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_80990 CU051_LOCMI: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_81061 CU32_LOCMI: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_137087 FRE2_LITIN: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_181421 HSP2_MURBR: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_181436 HSP3_MURBR: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_181437 HSP3_OCTVU: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_210528 LE06_BIOGL: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_211725 LEPT_LEPPE: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_226533 MAR3_LEIMA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_226725 MAST_VESCR: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_248923 MTBB1_METAC: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_248924 MTBB1_METBA: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_248925 MTBB1_METBF: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_248926 MTBB1_METMA: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_248927 MTBB2_METAC: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_248928 MTBB2_METBA: Warning: One or more O characters replaced by X for alignment score calculations at positions 307 
> Warning: [tblastn] lcl|Query_248929 MTBB2_METBF: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_248930 MTBB2_METMA: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_248931 MTBB3_METAC: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_248932 MTBB3_METBA: Warning: One or more O characters replaced by X for alignment score calculations at positions 307 
> Warning: [tblastn] lcl|Query_248933 MTBB3_METMA: Warning: One or more O characters replaced by X for alignment score calculations at positions 355 
> Warning: [tblastn] lcl|Query_249697 MTMB1_METAC: Warning: One or more O characters replaced by X for alignment score calculations at positions 201 
> Warning: [tblastn] lcl|Query_249698 MTMB1_METBA: Warning: One or more O characters replaced by X for alignment score calculations at positions 201 
> Warning: [tblastn] lcl|Query_249699 MTMB1_METBF: Warning: One or more O characters replaced by X for alignment score calculations at positions 201 
> Warning: [tblastn] lcl|Query_249700 MTMB2_METAC: Warning: One or more O characters replaced by X for alignment score calculations at positions 201 
> Warning: [tblastn] lcl|Query_249701 MTMB2_METBA: Warning: One or more O characters replaced by X for alignment score calculations at positions 201 
> Warning: [tblastn] lcl|Query_249702 MTMB2_METBF: Warning: One or more O characters replaced by X for alignment score calculations at positions 201 
> Warning: [tblastn] lcl|Query_249703 MTMB3_METBF: Warning: One or more O characters replaced by X for alignment score calculations at positions 201 
> Warning: [tblastn] lcl|Query_249704 MTMB_METMA: Warning: One or more O characters replaced by X for alignment score calculations at positions 201 
> Warning: [tblastn] lcl|Query_251149 MTTB1_METAC: Warning: One or more O characters replaced by X for alignment score calculations at positions 333 
> Warning: [tblastn] lcl|Query_251150 MTTB1_METMA: Warning: One or more O characters replaced by X for alignment score calculations at positions 333 
> Warning: [tblastn] lcl|Query_251151 MTTB2_METAC: Warning: One or more O characters replaced by X for alignment score calculations at positions 333 
> Warning: [tblastn] lcl|Query_251152 MTTB2_METMA: Warning: One or more O characters replaced by X for alignment score calculations at positions 333 
> Warning: [tblastn] lcl|Query_251153 MTTB_DESHD: Warning: One or more O characters replaced by X for alignment score calculations at positions 330 
> Warning: [tblastn] lcl|Query_251154 MTTB_DESHY: Warning: One or more O characters replaced by X for alignment score calculations at positions 330 
> Warning: [tblastn] lcl|Query_251155 MTTB_METBA: Warning: One or more O characters replaced by X for alignment score calculations at positions 333 
> Warning: [tblastn] lcl|Query_251156 MTTB_METBF: Warning: One or more O characters replaced by X for alignment score calculations at positions 333 
> Warning: [tblastn] lcl|Query_251157 MTTB_METBU: Warning: One or more O characters replaced by X for alignment score calculations at positions 334 
> Warning: [tblastn] lcl|Query_251158 MTTB_METTE: Warning: One or more O characters replaced by X for alignment score calculations at positions 333 
> Warning: [tblastn] lcl|Query_292756 PCG7_PACGO: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_301104 PHI3_MYTCA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_314634 PROTO_AGEPP: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_314637 PROTO_PROSY: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315404 PRT1_ESOLU: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315409 PRT2A_ONCMY: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315413 PRT2_ONCMY: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315483 PRTY1_CLUHA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315484 PRTY1_CLUPA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315492 PRTZ_CLUHA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315493 PRTZ_CLUPA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315496 PRT_DICLA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315498 PRT_PERFV: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_315499 PRT_PHOTU: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375680 RL41_ARATH: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375682 RL41_CYPCA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375683 RL41_EPICO: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375684 RL41_FELCA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375685 RL41_GOSHI: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375686 RL41_HORVU: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375687 RL41_HUMAN: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375690 RL41_MOUSE: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375691 RL41_ORYSJ: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375692 RL41_PEA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375693 RL41_PONAB: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375696 RL41_RAT: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375698 RL41_SPOFR: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375699 RL41_TAKRU: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_375700 RL41_TOBAC: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_464313 TEMC_RANTE: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_466049 THCL_BACBA: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_466050 THCL_BACCE: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_490923 UHA1_CANLF: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_500762 VG22_BPT2: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> Warning: [tblastn] lcl|Query_500763 VG22_BPT6: Warning: Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options 
> 
> 2017-03-21 15:53:52,426: Found 15348 preliminary alignments
> 2017-03-21 16:08:37,722: Exonerate finished: found 14 alignments

**Comment by nextgenusfs** [comment]
Hmm.  Maybe be the new Blast+ 2.6 version has changed behavior, looks like they changed default output of fmt 6, https://www.ncbi.nlm.nih.gov/books/NBK131777/.  I will look into that.  But that wouldn't be consistent with the test data giving same results.

**Comment by MichaelFokinNZ** [comment]
oh, sorry the commands 
are

for sample data

> funannotate predict -i genome1.fasta -o genome1 -s "Genome one" --isolate fun1 --name GN01_ --augustus_species botrytis_cinerea --protein_evidence proteins.fa --transcript_evidence transcripts.fa --cpus 2

for a single contig

> funannotate predict -i $HOME/data/testN9/N9.fasta -o $HOME/data/testN9/N9_out --species "N9" --rna_bam $HOME/data/testN9/N9_S11sorted.bam 

for a full genome

> funannotate predict -i $HOME/data/funna.fasta -o $HOME/data/fun_out --species "F38" --pasa_gff $HOME/data/funna.assemblies.fasta.transdecoder.genome.gff3 --rna_bam $HOME/data/funnaS1S6S11_sorted.bam  --transcript_evidence $HOME/data/Trinityv03.fasta --cpus 4

**Comment by MichaelFokinNZ** [comment]
My question will be really stupid. But I finally can't understand what proteins are aligned to the genome at this step.  As written in the README I expect UniProtKB (fungal?) database to be used at this step.
> This command will first run RepeatModeler on your genome, soft-mask repeats using RepeatMasker, align UniProtKB proteins to genome using tblastn/exonerate, align transcripts.fasta to genome using GMAP, launch BRAKER to train/run AUGUSTUS and GeneMark-ET

but actually it seems to be predicted set of proteins aligned against masked genomic database. Am I right?

**Comment by MichaelFokinNZ** [comment]
And yes, it was somehow similar recent issue with Busco - the blast terminated early by error on multi-thread, corrupting all pipeline. The only solution was to run it in single core, and I think it was fixed just in a very last Busco release.

**Comment by nextgenusfs** [comment]
If you don't specifically add `--protein_evidence` it will use the UniProtKB database (>500,000) proteins (the script is processing the fasta headers before it runs the pre-filtering with tblastn and therefore uses the file in called `proteins.combined.fa` it would also concatenate if you passed multiple files to that option).  While there can be lots of tblastn hits, what I'm really after here is to find high quality protein alignments, so funannotate only keeps exonerate alignments that are > 80% identical.  While this is strict, the idea is to use the information to help the gene predictors with intron/exon boundaries. Having said that, I would expect you to have more exonerate alignments than the 14, likely in the range of 500-1,000. 

I think the BUSCO problem was actually a BLAST v2.4 linux only problem, which was supposedly fixed in v2.5.  I'm wondering if the multi-threaded tblastn error is back in v2.6.  I've also considered changing this pre-filtering to use Diamond which is much faster than tblastn, I have the script written to replace tblastn with Diamond, but haven't had a lot of time to test it.  I will push the update now if you want to give it a try, otherwise will take me until at least tomorrow to get this figured out.  I'm in the process of getting a new release together with a few other minor fixes.

**Comment by MichaelFokinNZ** [comment]
thank you much for explaining this :) will try to play with settings.

In the tbl2asn/genome.stats what is the Modified genome?

**Comment by nextgenusfs** [comment]
That is the GAG output for before and after processing.  Typically all that has changed is that start and stops are added and then the genome table file is made by GAG to be used in tbl2asn.

**Comment by MichaelFokinNZ** [comment]
yes and it looks very strange getting 2k alignments for the full genome, while 15k for a single scaffold...

**Comment by nextgenusfs** [comment]
If you want to try the Diamond/exonerate method I just pushed the script.  If you installed via git clone you could just do a git pull to update, otherwise you could just grab the script below and replace it in the linuxbrew `/funannotate/libexec/bin` directory.  But you can also just call the script directly from the predict_misc folder that you had before, would be something like:
```
/path/to/funannotate/bin/funannotate-p2g.py -p proteins.combined.fa -g genome.softmasked.fa \
-o exonerate.diamond.out -f diamond -t diamond.output.txt --cpus 8
```
You can install diamond via linux brew if you went that route, should just be `brew install diamond`.

**Comment by MichaelFokinNZ** [comment]
Ok. Thank you! Will try to play around all options!!!

**Comment by nextgenusfs** [comment]
The other option would be to downgrade your Blast+ version to v2.3.0.  I'm fairly certain that version was bug free on linux.

**Comment by MichaelFokinNZ** [comment]
it is not a multi-thread issue, the same on 1 cpu, something my-genome-related

**Comment by MichaelFokinNZ** [comment]
> Traceback (most recent call last):
>   File "/home/osboxes/PhD_funna/funannotate_scripts/funannotate-p2g.py", line 9, in <module>
>     import lib.library as lib
> ImportError: No module named lib.library
>

**Comment by MichaelFokinNZ** [comment]
when running  funannotate-p2g.py

> Traceback (most recent call last):
>   File "/home/osboxes/.linuxbrew/bin/funannotate-p2g.py", line 9, in <module>
>     import lib.library as lib
> ImportError: No module named lib.library

**Comment by nextgenusfs** [comment]
I'm fairly certain its an error in tblastn v2.6.0, as my linux docker image also produced similar results with that version of blast. But it seems like different error than tblastn v2.4.0 as it does not seg fault.  

As per the error above, the script is located in the wrong place, should be in `/home/osboxes/.linuxbrew/opt/funannotate/libexec/bin`

**Comment by nextgenusfs** [comment]
Yeah, so on linux blast v2.6.0 it found 5,436 alignments, but using blast 2.4.0 on mac, I have 342,199 alignments.  This was using the same genome.  So there is clearly a problem with blast.  Currently testing the tblastn versus diamond to see if end results are the same.

**Comment by MichaelFokinNZ** [comment]
can it be your default database specific?
since UniprotKB_fungi division database gives more reasonable results for my genome

> 
> [10:43:17 PM]: Found 41540 preliminary alignments
> [11:29:22 PM]: Exonerate finished: found 1189 alignments

**Comment by nextgenusfs** [comment]
did you try a different version of blast?  Splitting to fungi in Uniprot can save some time, but it shouldn't result in more alignments than the entire database.

**Comment by MichaelFokinNZ** [comment]
no i didn't

**Comment by nextgenusfs** [comment]
It seems like only `tblastn` is causing problems, you can remove the `tblastn` symlink and default back to blast+ 2.2.31 as part of the apt-get package like so:
```
rm $HOME/.linuxbrew/bin/tblastn
```

**Comment by MichaelFokinNZ** [comment]
@nextgenusfs looks strange, haven't tried the large/default Uniprot database, but for Uniprot_fungi blast+ 2.2.31 gives the same numbers as blast+ 2.6

**Comment by nextgenusfs** [comment]
I think the tbl2asn error has something to do with the larger number of queries and targets.  As I agree, on smaller tests sets I see the same behavior of v2.6.0 as v2.2.32, but when there seems to be more queries then getting strange results. ~ 1200 alignments is about what you would expect from the UniProt database (remember these are only high quality hits, >80% identity).
