### ISSUE TITLE
What analyses does funannotate iprscan perform?

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/funannotate#554]
Hi Jon, 

I am running funannotate version 1.8.3. I have found some problems to make interproscan-5.48-83.0 run within funannotate, so I have decided to run it outside of it and then pass --iprscan in funannotate annotate. 
I was wondering which are the analyses that Interproscan runs within funannotate. Does it run all the available ones? 
(TIGRFAM, SFLD, amap, SMART, CDD, ProSiteProfiles, ProSitePatterns, SUPERFAMILY,  PRINTS, PANTHER, Gene3D, PIRSF, Pfam, Coils, MobiDBLite, SignalP_GRAM_POSITIVE, SignalP_EUK, Phobius, TMHMM). 

I have done a test run with all analyses and it seems a bit of an overkill (and it is taking forever for just one genome ~13000 proteins)

Thanks a lot!

**Comment by nextgenusfs** [comment]
Now you know why I wrote the parallel wrapper ;) -- it is very slow....

The command its running (in parallel) is `interproscan.sh -i input.fasta -d . -f XML -goterms -pa`.

I don't think the wrapper will work from docker without some more work (I have not tried that).

**Comment by aberaslop** [comment]
Now I now :D

I will make sure to install Interproscan locally then. Thanks!!

**Comment by aberaslop** [comment]
Hi Jon, 
I have managed to run interproscan through funannotate (what didn't work was Interproscan's tmhmm, but it appears that if you have Phobius running, it is not a problem). 

When I installed interproscan, I did install Phobius and signalp within it, so I did not install them in funannotate. Will funannotate still parse Phobius and signalp results run from interproscan?  I ask because after 'funannotate annotate' while I see entries in the annotation.tbl like InterPro, Pfam, BUSCO, COG, EggNog etc, I do not see any from Phobius or Signalp, and I wonder if they will be within the InterPro ones, or they have been lost. 
Thanks!

**Comment by nextgenusfs** [comment]
It does not currently parse the individual hits from InterProScan -- but just grabs the InterPro and GO data.

**Comment by aberaslop** [comment]
Thanks! So, am I understanding it correctly, that funannotate will also not gather panther data, or tigrfam, for instance? or those are considered Interpro data?

**Comment by nextgenusfs** [comment]
Correct -- it just generates the db_xref entries for InterPro:XXXX and then the GO terms. 

Its possible that we could grab all that other info -- although essentially InterPro domains are defined as being composed of the sub domains in panther, etc.

**Comment by aberaslop** [comment]
Great, thanks for the super quick clarification!
