### ISSUE TITLE
TransDecoder.Predict error died with ret 512 whilst running pasa_asmbls_to_training_set.dbi

### ISSUE THREAD

**Issue by Lamm-a** [nextgenusfs/funannotate#560]
**Input**
funannotate train -i $input -o $outdir --left $rnaLeft --right $rnaRight --stranded $stranded

**Error**
I am getting this error:
`Error, cmd: TransDecoder.Predict -t IC0001_sorted_masked.assemblies.fasta  died with ret 512 at /services/tools/funannotate/1.8.3/opt/pasa/scripts/pasa_asmbls_to_training_set.dbi line 148.`

Seems to be as a result of:
`No such file or directory at /services/tools/funannotate/1.8.3/opt/transdecoder/PerlLib/Pipeliner.pm line 185.`

Whole error report is here:
[funannotate_train-call.sh.e30742184.zip](https://github.com/nextgenusfs/funannotate/files/6043875/funannotate_train-call.sh.e30742184.zip)

Any help would be appreciated.

**Comment by nextgenusfs** [comment]
Here: https://github.com/PASApipeline/PASApipeline/issues/116 which links to several other issues -- the result seems to be there are not enough gene models to make the calculation.
```
[03:57 PM]: PASA assigned 99 transcripts to 96 loci (genes)
```
This is not from the test data, correct? If it is the test data then something upstream is wrong.

**Comment by Lamm-a** [comment]
This is not from the test data. The transcripts being used are whole transcriptomes so there should be no lack of 5' UTRs. The genome itself is a symbiotic fungi which tend to have a lot of repeat regions if that could be causing it?

`[03:57 PM]: PASA assigned 99 transcripts to 96 loci (genes)`

Meaning it was only able to use the transcriptome to identify 99 genes? Hmm weird! Would you like the input data to see if something is going wrong?
