### ISSUE TITLE
"ValueError: too many values to unpack (expected 3)" - getting this error on two different machines with funanotate test

### ISSUE THREAD

**Issue by kmkocot** [nextgenusfs/funannotate#561]
Hello,

I'm using funannotate 1.8.3 on a machine with Ubuntu 20.04 and another machine with Ubuntu 18.04. It seems to behave normally with the test until it gets to the EVM stage. On both machines, I get the following error at that point: 
```
Traceback (most recent call last):
  File "/home/apodomenia/miniconda3/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 433, in <module>
    partitions=args.no_partitions)
  File "/home/apodomenia/miniconda3/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 146, in create_partitions
    chr, start, end = line.split('\t')
ValueError: too many values to unpack (expected 3)
```
The command I used on my primary machine is:
```
funannotate test -t all --cpus 16 --debug
```
EVM seems to be working fine when I run it on another dataset.

Here's the output of funannotate check --show-versions on my primary machine:
```
You are running Python v 3.7.6. Now checking python packages...
biopython: 1.77
goatools: 1.0.15
matplotlib: 3.3.4
natsort: 7.1.1
numpy: 1.19.1
pandas: 1.2.1
psutil: 5.8.0
requests: 2.25.1
scikit-learn: 0.24.1
scipy: 1.6.0
seaborn: 0.11.1
All 11 python packages installed


You are running Perl v b'5.026001'. Now checking perl modules...
Bio::Perl: 1.7.4
Carp: 1.42
Clone: 0.39
DBD::SQLite: 1.56
DBD::mysql: 4.050
DBI: 1.64
DB_File: 1.84
Data::Dumper: 2.167
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.49
Hash::Merge: 0.302
JSON: 2.97001
LWP::UserAgent: 6.31
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 2.62
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.30
threads: 2.21
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/home/apodomenia/databases
$PASAHOME=/home/apodomenia/stow-Programs/PASApipeline-master
$TRINITY_HOME=/usr/local/bin
$EVM_HOME=/home/apodomenia/stow-Programs/EVidenceModeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/apodomenia/stow-Programs/augustus-3.3.3/config
$GENEMARK_PATH=/home/apodomenia/stow-Programs/gm_et_linux_64
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.11.0
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.26.0
blat: BLAT v36x9
diamond: 2.0.7
emapper.py: /usr/local/bin/diamond /home/apodomenia/stow-Programs/eggnog-mapper-master
emapper-2.0.1

exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.46
hisat2: 2.2.1
hmmscan: HMMER 3.1b2 (February 2015)
hmmsearch: HMMER 3.1b2 (February 2015)
java: 11.0.10
kallisto: 0.46.1
mafft: v7.453 (2019/Nov/8)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 1.4.0
samtools: samtools 1.10-17-gdcb0b2a
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.1.4
tRNAscan-SE: 1.3.1 (January 2012)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl 1.2rev59
	ERROR: ete3 not installed
	ERROR: trimmomatic not installed
```
Note that no matter what I do, I can't get ete3 to work and trimmomatic doesn't seem to be available via conda anymore and my attempts at satisfying funannotate with a wrapper script for the jarfile have failed. I've read all the relevant funannotate issues on these and more but nothing seems to help. My understanding is that either of these are involved in the step where I am getting this error, so I am pretty sure this is unrelated.

I've uploaded all the output files from this test run to http://genomes.ua.edu/2021-02-25_funannotate_test.zip

Any assistance would be greatly appreciated.

Best,
Kevin Kocot

**Comment by nextgenusfs** [comment]
Hmm, this one is strange.  It seems like the `bedtools merge` command failed.  Can you run this manually and see what the output is?
```
$ bedtools merge -s -i /home/apodomenia/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM/genes.28236.bed
```

**Comment by kmkocot** [comment]
Thanks for your help! I played around some more so there is a file in that directory but not by that name. I think that's irrelevant but just in the interest of being thorough, here's what I did and what happened:
`apodomenia@Apodomenia:~/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM$ pwd
/home/apodomenia/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM
apodomenia@Apodomenia:~/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM$ ls
genes.28407.bed
apodomenia@Apodomenia:~/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM$ bedtools merge -s -i /home/apodomenia/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM/genes.28236.bed
Error: Unable to open file /home/apodomenia/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM/genes.28236.bed. Exiting.
apodomenia@Apodomenia:~/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM$ bedtools merge -s -i /home/apodomenia/Desktop/2021-02-25_funannotate_test/test-predict_28614/annotate/predict_misc/EVM/genes.28407.bed > bedtools_output.txt`

[bedtools_output.txt](https://github.com/nextgenusfs/funannotate/files/6055924/bedtools_output.txt)

**Comment by nextgenusfs** [comment]
Okay, so that looks fine -- in the master I added a line to skip any empty lines in that step. You can install master from pip and then try the test run again `funannotate test -t predict`, make sure you are in the funannotate environment. 
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git
```

**Comment by kmkocot** [comment]
Thanks for your quick response! I uninstalled funannotate and installed it with the command you provided. Here's what I'm getting now:
[Feb 27 08:54 PM]: EVM: partitioning input to ~ 35 genes per partition
[Feb 27 08:54 PM]: Converting to GFF3 and collecting all EVM results
[Feb 27 08:54 PM]: Evidence modeler has failed, exiting
#########################################################
Traceback (most recent call last):
  File "/home/wirenia/.local/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 405, in main
    runPredictTest(args)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 161, in runPredictTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_testicus.gff3')) <= 1800
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_results/Awesome_testicus.gff3'

The command that failed was: 
`/usr/bin/python /home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py -w /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/weights.evm.txt -c 20 -g /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/gene_predictions.gff3 -d /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/EVM -f /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/genome.softmasked.fa -l annotate/logfiles/funannotate-EVM.log -m 10 -i 2000 -o /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/evm.round1.gff3 --EVM_HOME /home/wirenia/EVidenceModeler-1.1.1 -p /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/protein_alignments.gff3` 

When I run the failed command manually, I get:
wirenia@wirenia:~/Desktop/2021-02-27_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f$ /usr/bin/python /home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py -w /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/weights.evm.txt -c 20 -g /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/gene_predictions.gff3 -d /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/EVM -f /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/genome.softmasked.fa -l annotate/logfiles/funannotate-EVM.log -m 10 -i 2000 -o /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/evm.round1.gff3 --EVM_HOME /home/wirenia/EVidenceModeler-1.1.1 -p /home/wirenia/Desktop/2021-02-25_funannotate_test/test-predict_8abbd3a8-eb59-4d5f-8e84-b6aadd499f2f/annotate/predict_misc/protein_alignments.gff3
[Feb 27 09:27 PM]: EVM: partitioning input to ~ 35 genes per partition
Traceback (most recent call last):
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 452, in <module>
    partitions=args.no_partitions)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 108, in create_partitions
    SeqRecords = SeqIO.index(fasta, 'fasta')
  File "/home/wirenia/.local/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 980, in index
    proxy_class(filename, format, alphabet), key_function, repr, "SeqRecord"
  File "/home/wirenia/.local/lib/python3.6/site-packages/Bio/SeqIO/_index.py", line 197, in __init__
    SeqFileRandomAccess.__init__(self, filename, format, alphabet)
  File "/home/wirenia/.local/lib/python3.6/site-packages/Bio/SeqIO/_index.py", line 46, in __init__

Sorry but I'm not sure what to make of this.

I've uploaded the input/output here: http://genomes.ua.edu/2021-02-27_funannotate_test.zip

Thanks again!
Kevin

**Comment by nextgenusfs** [comment]
Okay that’s a biopython error. So something is wrong with your PATH in your funannotate environment. This is essentially the problem: 

b6aadd499f2f$ /usr/bin/python /home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py

Which means that from the environment you are running funannotate you have system python in front of the conda python in the PATH — so non of the modules are installed in system python and that’s why it fails. It might be because you’ve installed it with pip into your local environment and not system wide.

**Comment by kmkocot** [comment]
Thanks for your help. I'll try to figure this out. FYI, I also tried uninstalling it and installing it with miniconda following the instructions on the website (https://funannotate.readthedocs.io/en/latest/install.html) but it just says "Solving environment" forever.

`wirenia@wirenia:~$ conda install -c bioconda funannotate
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment:`

**Comment by nextgenusfs** [comment]
If you have a bunch of stuff installed in the `base` environment it won't solve....

But you are missing channels in the proper order -- see bioconda docs https://bioconda.github.io/user/install.html#set-up-channels
The channel order should be: `-c conda-forge -c bioconda -c defaults`,
