### ISSUE TITLE
Funannotate fails at minimap2 step

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/funannotate#562]
Hi Jon,

I am analyzing around 60 fungal genomes and most of them have gone through "funannotate predict" without any problems. However, a number of them fail at the minmap2 step. I would appreciate any help to solve this hiccup. Thanks!!

**Are you using the latest release?**
Yes, I think so. I am currently using it in a conda environment. 

**Describe the bug**
Some genomes fail at minimap2 step.

**What command did you issue?**
nohup funannotate predict -i ICBG751_clean_sorted_masked.fa --species ICBG751 --name ICBG751 --augustus_species escovopsis_weberi  --optimize_augustus --busco_db sordariomycetes --transcript_evidence ../../Escovopsis/maker_evidence/escovopsis_EST.fa ../../Escovopsis/maker_evidence/Trinity.fasta  --protein_evidence ../../Escovopsis/maker_evidence/GCA_001278495.1_ASM127849v1_protein.faa ../../Escovopsis/maker_evidence/GCF_000146045.2_R64_protein.faa ../../Escovopsis/maker_evidence/GCF_000149205.2_ASM14920v2_protein.faa ../../Escovopsis/maker_evidence/GCF_000167675.1_v2.0_protein.faa ../../Escovopsis/maker_evidence/GCF_000170995.1_TRIVI_v2.0_protein.faa ../../Escovopsis/maker_evidence/GCF_000171015.1_TRIAT_v2.0_protein.faa ../../Escovopsis/maker_evidence/GCF_000182925.2_NC12_protein.faa ../../Escovopsis/maker_evidence/uniprot.faa -o ICBG751_predict --cpus 16

**Logfiles**
The terminal outputs: 
[04:32 AM]: OS: Debian GNU/Linux 10, 24 cores, ~ 264 GB RAM. Python: 3.7.9
[04:32 AM]: Running funannotate v1.8.3
[04:32 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[04:32 AM]: Skipping CodingQuarry as no --rna_bam passed
[04:32 AM]: Parsed training data, run ab-initio gene predictors as follows:
[04:32 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
  ^[[4mProgram      Training-Method^[[0m
  augustus     busco
  glimmerhmm   busco
  snap         busco
[04:32 AM]: Genome loaded: 222 scaffolds; 30,981,712 bp; 12.98% repeats masked
[04:32 AM]: Aligning transcript evidence to genome with minimap2
Traceback (most recent call last):
  File "/home/aberas2/funannotate-conda/bin/funannotate", line 713, in <module>
    main()
  File "/home/aberas2/funannotate-conda/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/aberas2/funannotate-conda/lib/python3.7/site-packages/funannotate/predict.py", line 853, in main
    minimapGFF3, hintsM)
  File "/home/aberas2/funannotate-conda/lib/python3.7/site-packages/funannotate/library.py", line 1744, in bam2ExonsHints
    for aln in execute(['samtools', 'view', os.path.realpath(input)]):
  File "/home/aberas2/funannotate-conda/lib/python3.7/site-packages/funannotate/library.py", line 551, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['samtools', 'view', '/home/aberas2/data/Esco-predict/ICBG751_predict/predict_misc/transcripts.minimap2.bam']' returned non-zero exit status 1.

The funannotate predict log is here: 
[funannotate-predict.log](https://github.com/nextgenusfs/funannotate/files/6060650/funannotate-predict.log)

**OS/Install Information**
 -  output of `funannotate check --show-versions`
 -------------------------------------------------------
Checking dependencies for 1.8.3
-------------------------------------------------------
You are running Python v 3.7.9. Now checking python packages...
biopython: 1.78
goatools: 1.0.15
matplotlib: 3.3.4
natsort: 7.1.1
numpy: 1.20.1
pandas: 1.2.2
psutil: 5.8.0
requests: 2.25.1
scikit-learn: 0.24.1
scipy: 1.5.3
seaborn: 0.11.1
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/aberas2/funannotate-conda/funannotate_db
$PASAHOME=/home/aberas2/funannotate-conda/opt/pasa-2.4.1
$TRINITY_HOME=/home/aberas2/funannotate-conda/opt/trinity-2.8.5
$EVM_HOME=/home/aberas2/funannotate-conda/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/aberas2/funannotate-conda/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.6
emapper.py: 2.0.6
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.28
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.4
tRNAscan-SE: 2.0.7 (Oct 2020)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed

**Comment by nextgenusfs** [comment]
Since most working and some fail I would look at the evidence you are passing those that fail. Are there some bad/strange sequences? You can run that minimap2 command outside of funannotate and might yield some more information.

**Comment by aberaslop** [comment]
Hi Jon, 
The evidence provided is always the same, as I am handling very closely related fungi. 
I run the script that failed:
minimap2 -ax splice -t 16 --cs -u b -G 3000 /home/aberas2/data/Esco-predict/ICBG751_predict/predict_misc/genome.softmasked.fa ICBG751_predict/predict_misc/transcripts.combined.fa | samtools sort --reference /home/aberas2/data/Esco-predict/ICBG751_predict/predict_misc/genome.softmasked.fa -@ 4 -o ICBG751_predict/predict_misc/transcripts.minimap2.bam

And I got this:

M::mm_idx_gen::2.416*0.97] collected minimizers
[M::mm_idx_gen::3.226*1.36] sorted minimizers
[M::main::3.227*1.36] loaded/built the index for 222 target sequence(s)
[M::mm_mapopt_update::3.435*1.34] mid_occ = 55
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 222
[M::mm_idx_stat::3.595*1.33] distinct minimizers: 8312107 (89.63% are singletons); average occurrences: 1.269; average spacing: 2.938
munmap_chunk(): invalid pointer
Aborted


Any idea of the reason behind it? Thanks!

**Comment by aberaslop** [comment]
Thanks, Jon. I will have a look at such features.

**Comment by nextgenusfs** [comment]
If you find something that we can auto detect and fix we can add to pipeline. Probably worth searching that error in minimap2 GitHub page.

**Comment by aberaslop** [comment]
Yes, I will report back if/when I find anything.

**Comment by aberaslop** [comment]
Hi,

I solved the minimap2 problem after talking to the developers. 

I actually wasn't able to reproduce the "invalid pointer" error that minimap2 caused when run alone (as in further attempts it just gave me a segmentation fault). I could, however, fix the funannotate error by separating the minimap2 script from the samtools one.

I run the minimap2 script directing the output to output.sam. Then I used this file as input for the samtools script that results i the transcripts.minimap2.bam. I then run funannotate predict, and everything worked fine. I have not annotated the genome yet, but the number of genes models predicted seem consistent with the genomes that did not fail. 

I hope this helps. 

All the best!

**Comment by nextgenusfs** [comment]
Okay so did developers say anything about why piping to samtools that was causing the error? Piping reduced some IO time which is why I do it.

**Comment by aberaslop** [comment]
No, they didn't. In fact, they mentioned that they did not see anything wrong on the original funannotate script. But they recommended to unpipe for debugging.

**Comment by nextgenusfs** [comment]
Could be samtools problem I guess, I’ve seen strange behavior with v1.10, what version do you have in your environment?

**Comment by aberaslop** [comment]
You are onto something, I have v1.10.2.
