### ISSUE TITLE
Issue with from __future__ import

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#565]
Hi,

I am having problems after upgrading to the newest GitHub version from an otherwise fully functional 1.8.2 (or 1.8.3?) funannotate Conda environment. python is 2.7.18.

Several commands like funannotate species, database, check ... only work when I add the following statement to the beginning of the file:

```
from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
```

It may be a problem with my python version. Or is it something that has been overlooked, because it is used in other scripts that more or less work (like predict). I say more or less because it seems to be a problem recognising the environmental variables (It does not manage to run busco)... That I am also trying to solve.

What are your thoughts?

Take care,

Fernando

**Comment by nextgenusfs** [comment]
Hi @ferninfm. Might be an over sight by me to not include those imports in a few scripts they are for backwards compatibility for py2. At some point would be best to upgrade to py3 as it will be harder to maintain compatibility with py2 in the future.
