### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by pseudogene** [nextgenusfs/funannotate#57]
I have been using Dockers for a while. To simplify the docker experience the easiest way is to create a first docker using your Dockerfile (and the `docker build` command or reposited on DockerHub), then to upload and prepare the licenced files and at last, to create an other Docker using the first docker as a base images. The latter can now be used without further changes in the future.
:)

Michaël

**Comment by nextgenusfs** [comment]
Do you have an example?  I think I sort of understand, but the user still has to install the software requiring individual licenses?  I have nextgenusfs/funannotate on DockerHub.

**Comment by pseudogene** [comment]
Right, assuming that the user has downloaded `gm_et_linux_64.tar.gz`, `gm_key_64.gz` and `RepBaseRepeatMaskerEdition-20170127.tar.gz` in the current folder, the following Dockerfile (untested, sorry) should create the final docker image.

```
FROM nextgenusfs/funannotate

WORKDIR /home/linuxbrew

COPY gm_et_linux_64.tar.gz /home/linuxbrew/gm_et_linux_64.tar.gz
COPY gm_key_64.gz /home/linuxbrew/gm_key_64.gz

RUN tar zxvf gm_et_linux_64.tar.gz && \
    mv /home/linuxbrew/gm_et_linux_64/gmes_petap $GENEMARK_PATH && \
    gunzip gm_key_64.gz && \
    cp gm_key_64 /home/linuxbrew/.gm_key && \
    rm -rf /home/linuxbrew/gm_et_linux_64 gm_key_64 gm_et_linux_64.tar.gz

COPY RepBaseRepeatMaskerEdition-20170127.tar.gz /home/linuxbrew/RepBaseRepeatMaskerEdition-20170127.tar.gz

RUN tar zxvf RepBaseRepeatMaskerEdition-20170127.tar.gz -C $HOME/.linuxbrew/opt/repeatmasker/libexec
RUN brew postinstall repeatmasker

RUN funannotate setup -m dep
```

**Comment by nextgenusfs** [comment]
Okay, that makes sense.  So what is the best way then to distribute the 2nd Dockerfile?  Or just have users create that (copy/paste) or download?  I suppose should be straight forward to have them download the docker file via `wget` or something, and then would just have to issue a `docker build` command.  I appreciate the help, very new to docker...

**Comment by nextgenusfs** [comment]
I'm trying to get this running, but can't seem to mount a volume during the build process.  So are you suggesting that the `docker build` command be run from within the docker container itself? That would require the image to have docker installed?

**Comment by pseudogene** [comment]
You need to create an other docker file (e.g. `Dockerfile.gm64`) with the previous commands. The user needs to download `gm_et_linux_64.tar.gz`, `gm_key_64.gz` and `RepBaseRepeatMaskerEdition-20170127.tar.gz` in its current folder and to download `Dockerfile.gm64` with curl or wget. Then `docker build -f Dockerfile.gm64 -t funannotate .` can be executed from outside any docker.
Funannotate can now be used with `docker run -it --rm -v $(pwd):/home/linuxbrew/data funannotate bash`

**Comment by nextgenusfs** [comment]
Okay, yes that makes sense. Will work on implementing that.  Thanks again.

**Comment by nextgenusfs** [comment]
Working docker version (I hope) can be run following these instructions: http://funannotate.readthedocs.io/en/latest/docker.html
