### ISSUE TITLE
Diamond repeat database was created with different version of diamond, please re-run funannotate setu

### ISSUE THREAD

**Issue by tboonf** [nextgenusfs/funannotate#573]
Hi,
I had a similar issue with whats described here: https://github.com/nextgenusfs/funannotate/issues/358
I had installed the lastest Funannotate version 1.8.5, and installation of dependencies went okay without problem. 

The diamond version installation along with funannotation is diamond: 2.0.8, and I also make sure the system wide diamond was replaced with the same version (just in case). However, when running the predict function, I received the following error message:

[Mar 16 10:28 AM]: OS: Ubuntu 16.04, 64 cores, ~ 264 GB RAM. Python: 3.7.10
[Mar 16 10:28 AM]: Running funannotate v1.8.5
[Mar 16 10:28 AM]: Could not determine diamond database version
[Mar 16 10:28 AM]: Diamond repeat database was created with different version of diamond, please re-run funannotate setup

I went ahead to do the following based on a previous recommendation: https://github.com/nextgenusfs/funannotate/issues/358
rm $FUNANNOTE_DB/*.dmnd
funannotate setup -i all --force

This did not solve the issue. so I went ahead and do the following based on this recommendation:https://github.com/nextgenusfs/funannotate/issues/165

wget -O funannotate.repeat.proteins.fa https://osf.io/vp87c/download?version=1
tar -zxf funannotate.repeat.proteins.fa.tar.gz
sed 's/#/_/g' funannotate.repeat.proteins.fa | sed 's,/,-,g' | sed 's/&//g' > funannotate.repeats.reformat.fa
diamond makedb --in funannotate.repeats.reformat.fa --db repeats -parse_seqids

Despite trying various ways, the problem persists. I am wondering why is this only happening to the repeats database and not the other database that was set up the same way, i.e. funannotate setup -d $HOME/funannotate_db 

Any help is very much appreciated.

**Comment by nextgenusfs** [comment]
Thanks. I just pushed a fix for this to bioconda as I noticed the same thing earlier in the day, diamond v2.0.8 changed format on its output of the dbinfo command. Solution is to downgrade diamond to v2.0.7 or to install the master from the repo using pip.

**Comment by tboonf** [comment]
Thanks. updated version solves the problem.
