### ISSUE TITLE
Conda install issue

### ISSUE THREAD

**Issue by Erboou2020** [nextgenusfs/funannotate#576]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
Hi, when I install the latest release of funannotate by Conda (conda create -n funannotate funannotate), it continued run in my terminal without any results. Can you have a check for this, if this version does not be used in Linux now. 

**What command did you issue?**
conda create -n funannotate funannotate

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`

**Comment by nextgenusfs** [comment]
Its likely just Conda -- if you have packages installed in your `base` environment that typically causes conflicts. I've recently used `mamba` with some success as the solver is a lot faster.  But it will work on a fresh Miniconda install -- that is what builds the docker image.
