### ISSUE TITLE
No module named XXXX

### ISSUE THREAD

**Issue by timkahlke** [nextgenusfs/funannotate#577]
**Are you using the latest release?**
yes

**Describe the bug**
Modules inside the funannotate package can't import funannotate

**What command did you issue?**
Any funannotate XXX command, e.g. funannotate check

**OS/Install Information**
 funannotate check fails so can't but
- Ubuntu 20.04
- miniconda3 env with python2.7.18
- all python * perl libs manually installed

First of all as usual: thanks for the great work!
I tried to set up the latest funannotate and am running into the problem that the package's modules can't import funannotate itself. e.g.
 
````
funannotate check

Traceback (most recent call last):

  File "/.../miniconda3/envs/funannotate_env/bin/funannotate", line 9, in <module>
    sys.exit(main())

  File "/.../miniconda3/envs/funannotate_env/lib/python2.7/site-packages/funannotate/funannotate.py", line 705, in main
    '{:}.{:}'.format(package_name, info[cmdName]['cmd']))

  File "/.../miniconda3/envs/funannotate_env/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)

  File "/.../miniconda3/envs/funannotate_env/lib/python2.7/site-packages/funannotate/check.py", line 11, in <module>
    import funannotate.library as lib

ImportError: No module named library
````

I think the problem is the _funannotate.py_ module that's in the package itself. If I get it right then on "import funannotate.library" the different funannotate modules first search the current directory (empty element in sys.path[0]), find the funannotate.py, import that and can't find other modules because it's a module itself and not a directory.

That said, I'm not sure what the importlib changes included in funannotate.py do ....

Also, the previous version 1.8.3 doesn't have the funannotate.py and imports and runs without problems.

**Comment by nextgenusfs** [comment]
The setup.py changed to a console entry point which is better than what I was doing. Admittedly I didn't test py2.7 -- is there a reason you need to use py2.7? Eggnog mapper is now py3 so there shouldn't be (at least that I'm aware) of a reason to use py2 - I should have said in release notes but I don't think I'm going to make the effort to support py2 moving forward.

**Comment by timkahlke** [comment]
I think I just wasted a lot of time trying to squeeze a new py3 install into py2. Might have followed old docs for manual set-up as the conda3 ran into an infinite "Trying to resolve" loop.

Anyway, thanks for the quick reply.
