### ISSUE TITLE
Incomplete predict_results annotation

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#58]
In the predict_result folder just few first scaffolds are annotated (not sure that the number is fully reproducible), but for my case it can be 2 of 4 first scaffolds. On all further scaffolds gene models are just absent in predict_results/*.tbl gbk and gff files. Ubuntu16.04

If I run funannotate on any of these "unlucky" scaffolds separately - all predictions survive. So, they are real. 

I've tried to track the problem back by pipeline:
- EVM output has predictions for all scaffolds (~12k gene models)
- predict_misc/ncbi.cleaned.gff3 has predictions for all scaffolds (12k)
- gag1 and gag2 folders have all predictions for all scaffolds (12k)
- first tbl2asn run has all 12k gene models, while final tbl2asn report has only 4k models on first scaffold only (pls find first and final tbl2asn reports attached) . 
- predict_misc/tbl2asn/genome.gff *.stats *.tbl have has only 4k models on first scaffold only

In the log-file all 12k gene models survived almost till the very end 2017-03-31 14:19:35,714: 12,208 gene models remaining. But...

> 2017-03-31 14:19:36,817: gag.py -f /home/osboxes/data/fun_out_v02/predict_misc/genome.softmasked.fa -g /home/osboxes/data/fun_out_v02/predict_misc/ncbi.cleaned.gff3 -o /home/osboxes/data/fun_out_v02/predict_misc/tbl2asn --fix_start_stop
> **2017-03-31 14:19:45,602: not enough columns: scaffold_4	EVM	gene**

and scaffold_4 is the last annotated... 

in GAG  "not enough columns" error appears only in _gff_reader.py_

>  List of lists of fields -- because lines with multiple parents
>         are split into multiple lines."""
>         splitline = line.split('\t')
>         if len(splitline) is not 9:
>             print("not enough columns: "+line)
>             return []

trying to find wrong string, but the problem seems to appear consistently in different scaffolds... 

[f38_v02.error.summary.txt](https://github.com/nextgenusfs/funannotate/files/889228/f38_v02.error.summary.txt)
[tbl2asn_discrepency.report_head100.txt](https://github.com/nextgenusfs/funannotate/files/889227/tbl2asn_discrepency.report_head100.txt)
[f38_v02.discrepency.report_head100.txt](https://github.com/nextgenusfs/funannotate/files/889229/f38_v02.discrepency.report_head100.txt)
[funannotate-predict.log.txt](https://github.com/nextgenusfs/funannotate/files/889230/funannotate-predict.log.txt)

**Comment by simas232** [comment]
The problem is exactly the same as in #40 .

I had the same problem when running **funannotate predict** in cluster (CentOS 6.8) and using Docker image. It seems that the number of genes in predict_results folder is random between clean runs of the pipeline, when using the same assembled genome as input. For instance, if EVM/maker provides ca 4500 genes, the number of genes in the results folder varies from 700 to 1500.

To circumvent this problem for now, firstly run **funannotate predict** , then remove everything in tbl2asn folder (except genome.fasta, genome.fsa). Then you can run gag.py and tbl2asn manually. For parameters, check funannotate-predict.log. You should have all genes included in tbl2asn file then.

**Comment by MichaelFokinNZ** [comment]
@simas232 thank you much! how did I missed #40 !!! :)

**Comment by nextgenusfs** [comment]
Not sure why/how this is happening, but seems like it is happening at the renaming gene models step, as from your log file everything looks good up until the last GAG run.  Currently, I'm using two scripts from the MAKER2 pipeline to do the gene renaming, perhaps I should re-write this.  What I don't understand though is that this is apparently variable behavior.  Can you confirm that this only happens when you do a re-run of the pipeline?  If that is the case, just need to remove the tbl2asn folder if present on a re-run and it shouldn't have the error?

**Comment by MichaelFokinNZ** [comment]
Trying to find the issue with my small testing dataset. It is hardy reproducible and kind of random. Seems to be really related to re-run of funannotate.

**Comment by MichaelFokinNZ** [comment]
No, it seems to be somehow size-dependent. **For fresh run**s having ~3Mbp in 10 scaffolds, ~ 1200 models all going fine. But for the full genome ~35M, ~200 scaffolds it does this incomplete results again...  without any error messages in logs or anywhere else. Having last gag and tbl2asn commands running manually (as simas232 suggested), which helps, how to mimic successful completion to let `funannotate annotate` run from the output folder specified?

**Comment by MichaelFokinNZ** [comment]
Any updates here? Does it work well on Mac? Seems to be a major problem of funannotate problem on Linux.

**Comment by nextgenusfs** [comment]
I've never seen this behavior.  If you have a reproducible test case I'm happy to try to figure it out.  As of v0.6.0 the temp folders are deleted prior to GAG running.  GAG developers are also in process of a 2.0 release, so I'm waiting for that release.

**Comment by MichaelFokinNZ** [comment]
I think @simas232 did quite a good stat for this issue on CentOS in the issue #40 , for me it looks as a random interruption in real size genomes as reported above (effective for funannotate 0.6.0 as well). Very strange that this happens only at the last GAG run, and manual re-run helps to get around.  Did you tested the pipeline with the full fungal genome of hundreds contigs on Ubuntu?

**Comment by nextgenusfs** [comment]
Yes, I've run the Docker image v0.6.0 through a 32 MB genome annotation.... I can't reproduce this error on the Ubuntu Docker image or Mac. But again, if you have files that you can reproduce this behavior I'll try to figure it out.  It is impossible for me to troubleshoot without a test case that reproduces the error.

**Comment by MichaelFokinNZ** [comment]
Yes, it is 100% clear. Honestly I don't think it is a matter of dataset, but most likely smth environment related. So, I should try it on Docker. I will be able to share the data-set once the GA article will be accepted (~in 1-2 months I hope). What is really bad is that this issue is "silent" and is not reported by errors and only partially reflected in the discrepancy report, so users can easily miss it.

**Comment by nextgenusfs** [comment]
Hopefully the problem will go away with the updates to the GAG code, at least we seem to have narrowed it down to the last GAG step in the pipeline.

**Comment by MichaelFokinNZ** [comment]
Actually, I can try it on a random fungal genome and if the problem still persist I can share the ~15Gb virtual box image with you.

**Comment by nextgenusfs** [comment]
Yes, if you can get it to produce the error with any publicly available sequence - I can try to reproduce locally via Docker/and or VB.

**Comment by MichaelFokinNZ** [comment]
I've tried another 33M genome (~400 contigs) of Epicoccum sorghinum  with very basic settings,  obviously exactly the same problem. So it is the installation/environment issue. Probably if I install the funannotate and dependencies to the fresh ubuntu it can solve the problem... or not. Because in my case it was not easy and straightforward.

So, would you like me to share something with you? The whole Ubuntu VM (I am using Vbox)? I do have unlimited storage at amazon cloud to share it, but have no idea if any kind of FTP-like upload/download is available there. Do you have may be some place where I can upload the VM?

**Comment by nextgenusfs** [comment]
Okay, I finally got it to reproduce.  Don't know what is causing it yet though, but here's what I ran: https://github.com/nextgenusfs/notebooks/blob/master/Ep_Mac_run.ipynb

**Comment by MichaelFokinNZ** [comment]
so, cool. permissions problem? not re-run because i can reproduce it for
de-novo analysis. also it is "time of the analysis/datasize" related, since
no problems with sample/small datasets.

**Comment by MichaelFokinNZ** [comment]
so, cool. permissions problem?
But I was able to get the same issue with de-novo analysis, not for re-runs. 
Also it is "time of the analysis/datasize" related, since no problems with sample/small datasets.

**Comment by MichaelFokinNZ** [comment]
interestingly, I've got 12341 models vs 12380 in yours, having transcriptome/PASA data from closely related species of the same genus, UniProt limited to fungi and pezizomycotina BUSCO set.  Exonerate 1255 vs 1489, so it is worth using full UniProt DB, but much longer :(

**Comment by nextgenusfs** [comment]
I still can't seem to figure this out, I'm almost at a loss.   It is the strangest thing I've ever seen.  GAG seems to be dying prematurely, but only if run from the funannotate script (so from the subprocess module), i.e. from command line it works fine.  Even stranger, the first two calls to GAG never seem to error out - which implies something with the input to the last GAG command.... again but running same command a second time works.

**Comment by MichaelFokinNZ** [comment]
> .. again but running same command a second time works.
but from the command line only, not from funannotate script. Can you try something like separate funannotate script for last GAG/tbl2asn etc...

**Comment by MichaelFokinNZ** [comment]
also, is there any place I can find/record this GAG error message?

**Comment by MichaelFokinNZ** [comment]
and yes, this problem is permanent for me, not recurrent

**Comment by nextgenusfs** [comment]
There is no error, that is the problem, it just seems to exit, which I can't find a pattern either.  It isn't choking on any particular annotation.  I have one more thing to try, then will change how the command is issued.  Not sure what else to try.  How this could be different on the same version of Python on Mac vs Linux I have no explanation for.

**Comment by MichaelFokinNZ** [comment]
Could it be also related to RAM limitations (I normally have only 4 to 8Gb per VM)? So, having limited memory resources at the end of the run GAG is just shutting down having low priority? Can you try it in limited/unlimited RAM environments?   

So, it can explain low reproducibility on your powerful systems, success of command-line runs and no problems with tiny datasets....

**Comment by nextgenusfs** [comment]
Ok, slept on it and had the answer when I woke up.  So it wasn't GAG having earlier termination, it was the step immediately before that which functions to rename the gene models.  Short story is that function modifies the GFF file in place, however, there must be some differences in how the Python subprocess module communicates with the OS between Mac and Linux, as basically on Linux, the OS wasn't waiting for the command to finish.  So it would get part of the way through and the next command would start, hence the random/sporadic perceived "termination" of GAG.  When actually GAG was processing the info it had available, but the input file was only partially there because the previous command was still running.

I have a few more internal tests to run, but will try to get a new release with this fix out today.

**Comment by MichaelFokinNZ** [comment]
Great!!! Congrats! I my practice finding a bug is really exciting feeling...

On 26/04/2017 2:56 am, "Jon Palmer" <notifications@github.com> wrote:

Ok, slept on it and had the answer when I woke up. So it wasn't GAG having
earlier termination, it was the step immediately before that which
functions to rename the gene models. Short story is that function modifies
the GFF file in place, however, there must be some differences in how the
Python subprocess module communicates with the OS between Mac and Linux, as
basically on Linux, the OS wasn't waiting for the command to finish. So it
would get part of the way through and the next command would start, hence
the random/sporadic perceived "termination" of GAG. When actually GAG was
processing the info it had available, but the input file was only partially
there because the previous command was still running.

I have a few more internal tests to run, but will try to get a new release
with this fix out today.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nextgenusfs/funannotate/issues/58#issuecomment-297057102>,
or mute the thread

**Comment by nextgenusfs** [comment]
v0.6.1 has fixed subprocess module call that was causing this error.
