### ISSUE TITLE
Conda install not working

### ISSUE THREAD

**Issue by caonetto** [nextgenusfs/funannotate#582]
Hi, in a fresh install of miniconda and with a new environment the install is not working. Basically it gets stucks in the solving environment stage (tried with two OS Ubuntu 18 and 20). I waited overnight to see if it eventually gets resolved but it didnt. Anyone experiencing this same issue?

**Comment by nextgenusfs** [comment]
You can try `mamba` which might solve faster.  But the docker image is being built with conda..... https://github.com/nextgenusfs/funannotate/blob/master/Dockerfile

**Comment by caonetto** [comment]
Thanks, that solved the environment in a matter of minutes compared to conda.
