### ISSUE TITLE
Genemark path not working

### ISSUE THREAD

**Issue by caonetto** [nextgenusfs/funannotate#585]
Hi, even though I have genemark installed and I have defined the GENEMARK_PATH variable correctly when I perform funannotate check it still outputs "ERROR: gmes_petap.pl not installed". Is this an issue with the conda install?

**Comment by nextgenusfs** [comment]
Is gmes_petap.pl in your PATH?

**Comment by caonetto** [comment]
Thanks for your quick response. Yes, but still not working after the check command. Strangely it does work if I define the --GENEMARK_PATH when running predict. 
Thanks.
