### ISSUE TITLE
Eggnog standalone

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [nextgenusfs/funannotate#586]
Hi,
I am running funannotate v1.8.2. 

I was wondering on how to best run emapper.py (Eggnog) standalone so it can be passed into funannotate annotate with the --eggnog flag.

What would be the best input file to emapper.py and what flags to use?

There are different dependencies for funannotate and emapper.py which make it incompatible in one environment. 

Thanks!

Benjamin

**Comment by nextgenusfs** [comment]
If you can get the most recent version of eggnog-mapper which is finally py3 than you can use funannotate >1.8.5 -- see here https://github.com/nextgenusfs/funannotate/releases/tag/v1.8.5. Otherwise it's kind of difficult due to their format changing between v1.0.3 and their most current. Older version 1.0.3 will still work but it is py2 which I don't recommend using anymore as I haven't been testing code to make sure works with py2.

**Comment by BenjaminSchwessinger** [comment]
Thanks Jon.

Can you clarify if funannotate v1.8.5 is python 3 now. This isn't clear to me from the docs and the installation instructions are still for v1.7.0 with python 2.7.

Main reason to ask about eggnog mapper was the python 2 vs 3 issue.

Thanks for all the work on this.

Benjamin
________________________________

**Comment by nextgenusfs** [comment]
Sorry I've not had time to update docs. But yes py3 is recommended since v1.8x when I finally got it converted. On next release I will try to update docs to reflect this.

**Comment by BenjaminSchwessinger** [comment]
Great. I will update my versions accordingly.

Thanks.
________________________________

**Comment by BenjaminSchwessinger** [comment]
Hi Jon.

Your conda recipe still wants py2. is there are way round this or can you update it?

**Comment by nextgenusfs** [comment]
Hmm weird. It's not pinned to py2, try 

conda create -n funannotate "python>=3.6,<3.9" funannotate

**Comment by nextgenusfs** [comment]
And I've also found that mamba can speed up the silver quite a bit. You can install mamba into your base env and then use mamba as a drop in replacement for conda.

**Comment by BenjaminSchwessinger** [comment]
Hi Jon,
Thanks that helped with conda defining the python version. This got v1.8.5 installed in python.

I also installed emapper-2.1.2 which throws the following error in the annotate step of funannotate.

 line 241, in parseEggNoggMapper                         NOG, DB = cols[OGi].split('@')                                                                                                                               ValueError: not enough values to unpack (expected 2, got 1) ****


I think the issue is with your function getEggNogHeadersv2 in line 176 of annotate.py which uses different column names in the item2index function. 

The current column headers of emapper v2.1.2 are

#query  seed_ortholog   **evalue**  score   eggNOG_OGs      max_annot_lvl   COG_category    Description     Preferred_name  GOs     EC                                     KEGG_ko KEGG_Pathway    KEGG_Module     KEGG_Reaction   KEGG_rclass     BRITE   KEGG_TC CAZy    BiGG_Reaction   **PFAMs******

Based on your function I guess the names and the order of the output column for emapper have changed that throws your parser. Could fix it but not sure what the previous names are as I don't have an old version. Might be worth also to parse the KEGGs pathway annotations.

Hope that helps.

**Comment by BenjaminSchwessinger** [comment]
Yeah here are the old headers

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.2-v2.0.8#Annotations_file

and new headers

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2#Output_format

**Comment by nextgenusfs** [comment]
I hope they haven't changed headers again from three weeks ago! There was an issue I fixed in master related to them having more than one OG in the "best_og" column, can you try installing master over the top with pip? That will have that fix. If that doesn't work I will update it again....

python -m pip install git+https://github.com/nextgenusfs/funannotate.git

**Comment by BenjaminSchwessinger** [comment]
Okay v1.8.6 of funannotate worked with pip install eggnog-mapper==2.1.0.post1.

So I am closing this now.
