### ISSUE TITLE
CodingQuarry segmentation fault

### ISSUE THREAD

**Issue by wittetom** [nextgenusfs/funannotate#587]
Hi Jon,

When I run funannotate predict after funannotate train, I get a segmentation fault, see output below:

CodingQuarry -p 24 -f /home/tommy/funannotate/RNAseq/Fp133_training/predict_misc/genome.softmasked.fa -t /home/tommy/funannotate/RNAseq/Fp133_training/predict_misc/stringtie.gff3
The environmental variable QUARRY_PATH is set as: /home/tommy/miniconda3/envs/funannotate/opt/codingquarry-2.0/QuarryFiles
STAGE 1
Prediction from transcript sequences, run 1 of 2...
Segmentation fault (core dumped)

I'd rank myself as a beginner user here.  I'm running funannotate from Conda install.  

All other parts of the funannotate pipeline seem to work, (as long as I set the CodingQuarry weight to zero to skip that part of the pipeline).  I'm not sure how important CodingQuarry is, but it seems like something I should try to get running.  If I can't get it to run, plan B is to include the transcriptomic data as --transcript-evidence and just roll with that...  

As I understand it, segmentation faults are tough to diagnose and are likely specific to the computer that's running things (which may have a corrupted package install somewhere etc?). 

However as I'm having a tough time tracking down the source of this fault, I thought I'd just post an issue here and see if you've seen this type of thing before or can point me in the direction of how to find a more specific point of failure for this part of the pipeline. 

Thanks for your time once again.  

Tom

**Comment by nextgenusfs** [comment]
Yes, segfaults can be difficult.  I'd first verify that the input files exist and are not empty, then see if you can run it manually you might get some more information printed out to terminal, ie:
```
CodingQuarry -p 24 -f /home/tommy/funannotate/RNAseq/Fp133_training/predict_misc/genome.softmasked.fa -t /home/tommy/funannotate/RNAseq/Fp133_training/predict_misc/stringtie.gff3
```
You could maybe also try to lower the threads if you get same error? Could it be running out of memory?

**Comment by wittetom** [comment]
Thanks for the tips! 

 I followed your advice, and in opening the files I noticed that genome.softmasked.fa has '^M' line endings after each contig name.  I removed those and CodingQuarry works on the file. 

If I rerun funannotate predict, it will regenerate this file with the bad line endings and stop the pipeline as before... 

Any idea on how I can work around this?  Can I put the output of codingquarry somewhere so that when I rerun 'funnannotate predict' it will see that step as complete?  I'm not sure what funannotate's looking for.

**Comment by nextgenusfs** [comment]
Bizarre. I've never seen that before. What OS and version of python?

**Comment by nextgenusfs** [comment]
It literally is just copied from what you enter on command line -- so I think its your input file?
https://github.com/nextgenusfs/funannotate/blob/master/funannotate/predict.py#L764

**Comment by wittetom** [comment]
Yes, 100%. 

I checked and the input file has the wrong line endings.  Weird.   Everything is being done in linux. As I understand it these line ending problems usually happen when a file is opened and saved using a text editor in Windows, right?  I'll just assume I screwed up somewhere and accidentally switched line endings somehow.  I removed the '^M' and now codingquarry is happy.  I'll keep monotoring for this problem as I process genomes.

Python version is 3.7.4 (should I upgrade that?  I just went with whatever's in the conda package requisites).  I checked some of the other genomes and this didn't happen.  At least I now know what that error looks like and how to fix it.  

Thanks for your time, I think this can be safely closed unless you have more insights. 

Tom

**Comment by nextgenusfs** [comment]
Yeah not sure about the line endings as they shouldn't come from a Linux system that way I wouldn't think. But you could probably run it through multiple Linux programs to fix, ie something like seqkit to wrap lines would work. But I've def had line endings from files opened in windows system cause problems. The version of python isn't important here - what you have is good.
