### ISSUE TITLE
Predict does not find added species

### ISSUE THREAD

**Issue by fbemm** [nextgenusfs/funannotate#588]
I am trying to use an externally trained Augustus profile within a funannotate workflow. Basically, I would like to skip model training during predict. I added the Augustus parameters to funannotate through `species -s`. Passing the info.json to predict now results in the following:

```
[Apr 19 02:09 PM]: Ab initio training parameters file passed: /funannotate/species/plant/info.json
Traceback (most recent call last):
  File "/opt/micromamba/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/opt/micromamba/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/opt/micromamba/lib/python3.7/site-packages/funannotate/predict.py", line 472, in main
    for f in os.listdir(os.path.join(LOCALAUGUSTUS, 'species', aug_species)):
FileNotFoundError: [Errno 2] No such file or directory: 't1/predict_misc/ab_initio_parameters/augustus/species/plant'
```

Maybe this usage is not at all intended at all?

**Comment by nextgenusfs** [comment]
The `funannotate species` command will list the currently installed species that are available:
```
$ funannotate species
  Species                                    Augustus               GeneMark          Snap             GlimmerHMM       CodingQuarry   Date      
  BUSCO_awesome_busco_1365224699             augustus pre-trained   None              None             None             None           2020-01-27
  Conidiobolus_coronatus                     augustus pre-trained   None              None             None             None           2019-10-24
  E_coli_K12                                 augustus pre-trained   None              None             None             None           2019-10-24
  Xipophorus_maculatus                       augustus pre-trained   None              None             None             None           2019-10-24
  adorsata                                   augustus pre-trained   None              None             None             None           2019-10-24
  aedes                                      augustus pre-trained   None              None             None             None           2019-10-24
  amphimedon                                 augustus pre-trained   None              None             None             None           2019-10-24
  ancylostoma_ceylanicum                     augustus pre-trained   None              None             None             None           2019-10-24
  anidulans                                  augustus pre-trained   None              None             None             None           2019-10-24
...
...
```
So for `funannotate predict` I could pass `-s ancylostoma_ceylanicum` and it would use the pre-existing training data for augustus, but since there is no training data for snap/glimmerhmm/etc -- it will train those on the fly. If you pass something like `-s "Genus species"` and the folder `genus_species` is not located in the `$AUGUSTUS_CONFIG_PATH/species` then it will run de novo training for augusts/snap/glimmer/etc as the training set does not exist. 

If you have a parameters.json file from a previous `funannotate predict` run, you can pass that json file to `-p parameters.json` and it will use those data.

**Comment by fbemm** [comment]
```
  Species                                    Augustus               GeneMark   Snap   GlimmerHMM   CodingQuarry   Date      
  Conidiobolus_coronatus                     augustus pre-trained   None       None   None         None           2021-04-19
  E_coli_K12                                 augustus pre-trained   None       None   None         None           2021-04-19
  Xipophorus_maculatus                       augustus pre-trained   None       None   None         None           2021-04-19
  plant                                         augustus self-trained   None       None   None         None           2021-04-19
```

```
Singularity> funannotate predict -i test.fasta -o t1 -s plant --busco_db eukaryota
-------------------------------------------------------
[Apr 19 09:02 PM]: OS: Ubuntu 20.04, 40 cores, ~ 396 GB RAM. Python: 3.7.8
[Apr 19 09:02 PM]: Running funannotate v1.8.7
[Apr 19 09:02 PM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Apr 19 09:02 PM]: Skipping CodingQuarry as no --rna_bam passed
[Apr 19 09:02 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  glimmerhmm   busco          
  snap         busco
```

This is how it looks. "plant" was added manually to the species list. "plant" is present in the `$AUGUSTUS_CONFIG_PATH/species `.

**Comment by fbemm** [comment]
Funnannotate creates the following in `t1/predict_misc/ab_initio_parameters/augustus/species`:

```
.
./anidulans
./anidulans/info.json
./anidulans/augustus
./anidulans/augustus/anidulans_parameters.cfg
./anidulans/augustus/anidulans_weightmatrix.txt
./anidulans/augustus/anidulans_igenic_probs.pbl
./anidulans/augustus/anidulans_exon_probs.pbl
./anidulans/augustus/anidulans_intron_probs.pbl
./generic
./generic/generic_metapars.utr.cfg
./generic/generic_metapars.cfg
./generic/generic_weightmatrix.txt
./generic/generic_igenic_probs.pbl
./generic/generic_metapars.cgp.cfg
./generic/generic_intron_probs.pbl
./generic/generic_parameters.cfg
./generic/generic_exon_probs.pbl
```

**Comment by fbemm** [comment]
If I use a pre-trained species for `-s` it works and says pretrained instead of busco in the program list.

**Comment by fbemm** [comment]
Augustus species data is now here:

```
AUGUSTUS_CONFIG_PATH=/opt/micromamba/config/ -> species/plant
/funannotate/trained_species/ --> plant/augustus

```

But it is still falling back to starting BUSCO

**Comment by nextgenusfs** [comment]
Yes it needs to run BUSCO to train snap and glimmerhmm.

**Comment by fbemm** [comment]
That's fine. But if the Augustus profile is present, it should say pretrained in the list of tools that funannotate runs. RIght? At least this is the behaviour when I use something that comes with Augustus in the first place.

**Comment by nextgenusfs** [comment]
Yes if it didn't say pretrained then something is still not right. You ran funannotate setup after adding the "plant" folder to Augustus_config_path/species? And it shows up in the list from funannotate species?

**Comment by fbemm** [comment]
Yes, I re-run setup.

Configs are now in:

`/opt/micromamba/config/species` and the following ist set `AUGUSTUS_CONFIG_PATH=/opt/micromamba/config/`

The are also in:

`/funannotate/trained_species/` which i guess is the copy that funannotate creates during importing them as new species.

**Comment by fbemm** [comment]
{"augustus": [{"version": "AUGUSTUS (3.3.3)", "source": "augustus slef-trained", "date": "2021-04-19", "path": "/funannotate/trained_species/plant/augustus"}], "genemark": [{}], "codingquarry": [{}], "snap": [{}], "glimmerhmm": [{}]}

**Comment by fbemm** [comment]
Just checked:

`funannotate predict -i test.fasta -o t1 -s plant --busco_db eukaryota -w snap:0 glimmerhmm:0 busco:0 -p /funannotate/trained_species/plant/info.json`

Actually triggers:

```
[Apr 22 11:37 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pretrained 
```

**Comment by fbemm** [comment]
Ok, I finally understood what I did wrong. I added models to `AUGUSTUS_CONFIG_PATH`, added species them via `funannotate species` and then run `funannotate setup`.

I should have just added it to  `AUGUSTUS_CONFIG_PATH` and then run `funannotate setup`. Seems to work properly now with `-s`.

Is there a similar "import" mechanism for snap and glimmerhmm?

**Comment by nextgenusfs** [comment]
There isn't a default import for snap/glimmer but after you complete a predict run you can look at the parameters.json file -- it can be added with the funannotate species scripts (at end of table are examples), so you could write json files and move files around for a custom setup if you just follow what it is expecting and have the correct training files on hand.

**Comment by fbemm** [comment]
I see and that makes sense! Thx for your help!
