### ISSUE TITLE
Clean to remove contigs with only 3 or less nucleotides

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [nextgenusfs/funannotate#594]
Hi Jon,

It would be great if clean had an option to remove contigs that have less than 4 nucleotide types. Predict raises this as error and it would be great to simply have an option to clean this up beforehand.

Thanks!

**Comment by nextgenusfs** [comment]
Yes that's a good suggestion I will add to do list.

**Comment by hyphaltip** [comment]
I might add this to AAFTF too - it is a good point.

**Comment by calliphriend** [comment]
Hello all. Apologies in advance, I am very new to this. I am working on a polychaete genome in 1. 8.15 (Augustus would not work in 1.8.3). When I run clean, I still get the "contains only 3 nucleotides, removing" error numerous times until the process stops running (slurm log file remains same size) without completing/producing the output fasta file. I am definitely concerned the genome is too large to run clean as suggested in other threads, but even with increasing minlength significantly the job doesn't finish. I can't run predict without using force, which I don't want to do with so many contigs that need to be removed. I would sincerely appreciate any direction, thank you.

**Comment by nextgenusfs** [comment]
Hi @calliphriend, no need to apologize!  

The `clean` functionality was written to clean up assembly artifacts from haploid assemblies -- basically it tries to remove contigs if they are fully contained within a larger contig. This might not be a safe assumption for all organisms. You don't need to use it.  But it would probably help to clean up some of the contigs. There are likely many other ways to do this. 

How large is the genome? What is the ploidy of organism and ploidy of assembly?

**Comment by calliphriend** [comment]
Thank you kindly for your help and very quick response! This is excellent to know. I have been looking for alternatives to clean up the only 3 nucleotide contigs and BLASTN or DeconSeq seems promising.

The assembly size is 1,509,999,849 bp; the genome assembly haploid length is 366,115,238 bp. The ploidy of the organism is unknown unfortunately. Thank you again.

**Comment by nextgenusfs** [comment]
Another FYI, I'm not really sure how well `funannotate` will perform assemblies where ploidy is > 1.  I mostly work on fungi (haploid) so haven't experimented with the best approaches to annotating ploidy > 1. One approach might be to annotate the best haplotigs (ie haploid assembly) and then lift those gene models over to the rest of the assembly if that is necessary. 

Would be easy to write a short little python script to remove/scrubb contigs that are either short and/or are likely "bad", ie do not contain all 4 nucleotides.

**Comment by calliphriend** [comment]
For sure – thank you so much for these excellent suggestions! I'll write that script and see if it solves the issue. Many thanks again.
