### ISSUE TITLE
commas missed in tbl2asn cmd from funannotate-predict.log when two Source Qualifiers provided to funannotate predict

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#60]
my command includes both --species and --isolate like that 

`funannotate predict --masked_genome funna_masked.fasta --repeatmasker_gff3 repeatmasker.gff3 -o fun_out_v03 --species "F38_v03" --isolate "F38" --name B5807 --cpus 3 --protein_evidence uniprot_sprot_fungi.fasta  --pasa_gff funna.assemblies.fasta.transdecoder.genome.gff3 --transcript_evidence Trinityv03.fasta --rna_bam funnaS1S6S11_sorted.bam`

trying to work around issues #40/#58 (worth pooling them) I run last gag and tbl2asn commands manually, but the native funannotate command taken from` funannotate predict.log` 

`tbl2asn -p fun_out_v03/predict_misc/tbl2asn -t /home/osboxes/.linuxbrew/Cellar/funannotate/0.6.0/libexec/lib/test.sbt -M n -Z fun_out_v03/predict_results/f38_v03.discrepency.report.txt -a r10u -l paired-ends -j [organism=F38_v03] [isolate=F38] -V b -c fx`

just doesn't work because of non correct spelling of multiple source qualifiers  
from tbl2asn manual` -j "[organism=Saccharomyces cerevisiae] [strain=S288C]"`

with commas added works perfectly
`tbl2asn ....  -j "[organism=F38_v03] [isolate=F38]" .... `

I don't actually understand why commas don't appear in `funannotate-predict.log`
while should be?  `funannotate-predict.py` :) and why the pipeline works well on my Ubuntu 16.04 except #58 

```
if args.isolate:
    ORGANISM = "[organism=" + args.species + "] " + "[isolate=" + args.isolate + "]"
else:
    ORGANISM = "[organism=" + args.species + "]"
cmd = ['tbl2asn', '-p', gag2dir, '-t', SBT, '-M', 'n', '-Z', discrep, '-a', 'r10u', '-l', 'paired-ends', '-j', ORGANISM, '-V', 'b', '-c', 'fx']
```

**Comment by nextgenusfs** [comment]
They aren't there because of how the subprocess module parses the command, but yes on the command line you need them.
