### ISSUE TITLE
Generating GenBank Submission Files

### ISSUE THREAD

**Issue by fmobegi** [nextgenusfs/funannotate#601]
Funannotate implements a strict word limit for  FASTA headers. This doesn't correspond with some of the current NCBI requirements. For example, when indicating that a contig is a mitochondrion, they require adding "[location=mitochondrion]" in the fasta file before creating submission files. Otherwise, the resulting *.sqn or *.gbk files cannot pass the NCBI quality check. 
You might want to relax the word limit for such cases.

**Comment by nextgenusfs** [comment]
The 16 character limit is directly from NCBI for contig names -- the decoration of those primary names happens in tbl2asn/sql generation which is run at the end of annotation. If you have documentation that suggests that's changed let me know, but the other practical reason is that several of the ab initio gene callers cannot deal with complex NCBI FASTA headers with spaces, etc.

**Comment by fmobegi** [comment]
![Capture](https://user-images.githubusercontent.com/16131975/119594493-782d8200-be0e-11eb-8c75-1d3fcd87e4cd.PNG)

I was just going by the email I received from them after submitting my genomes. This is how they advise I should retain and correctly label mitochondrion sequence in the whole genome assembly. 
```

[1] The locus tag prefixes you used on all of these genomes is "FUN", which
is not allowed.  These need to be unique identifiers.  For the first 4, the
prefix is identical to the strain name (for example, TR9571).  We can either
assign automated prefixes or you can use the strain name (except for the ones with
hyphens- the hyphen can't be in the prefix).  Please fix the locus tags used in
your files.

[2] It looks like you included location=mitochondrion in the sequence identifier, which
is not valid.  The "=" is throwing an error.  In order to label that contig as a mitochondrial
contig, you need to use brackets in the fasta file when you generate the SQN file
It needs to look exactly like this:
[location=mitochondrion]
```

**Comment by fmobegi** [comment]
The advised fix is longer than 16 characters. And the special characters therein do upset most tools I must say

**Comment by nextgenusfs** [comment]
Yep, the locus_tag is mentioned here: https://funannotate.readthedocs.io/en/latest/predict.html#submitting-to-ncbi-what-should-i-know

Funannotate cannot annotation mitochondrial genomes, so it should be removed from the de novo assembly prior to running funannotate. Mitochondrial genomes should be a separate submission from your WGS+annotation as it uses a different genetic code.

**Comment by fmobegi** [comment]
Thanks for the information. 
The annotations I used for mitochondrial sequences was generated using PROKKA (Which IMO is best suited for the job). 
I will try to update the files and resubmit.

**Comment by nextgenusfs** [comment]
Prokka annotates bacterial genomes, not mitochondrial genomes.  There are some other tools I think that can do the job, but I don't know what the best current practices are for mitochondria.

**Comment by fmobegi** [comment]
Mitochondria have a bacterial origin... Comparing the ORF predictions and overall annotations from MITOS and PROKKA, I do get better results with the latter. Or perhaps it depends on the genome in question. Just from my experience. I will ask around what others have found, especially the groups dealing with mitochondrial genomes

**Comment by nextgenusfs** [comment]
True, but I thought the genetic code is different -- whereas prokka likely uses codon table 11 by default -- mitochondrial should be different (ie perhaps 4 for fungi). https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi

As far as I know you can't change the codon tables with Prokka or funannotate for that matter.

**Comment by anthonysnead** [comment]
Hello,
I kind of have a similar issue. I have a chromosome-level assembly that I have been attempting to submit as a non-wgs submission. We have cleaned the assembly to only have the 13 chromosomes expected. However, the submission portal requires that you include [location=chromosome]. I attempted to do this with the -t flag followed by "-j [location=chromosome] but then the NCBI submission portal says I do not have a species designator. When I attempt to do -t "-j [species=species] [location=chromosome]" where the species is my species, the genbank conversion just fails. I also tried to just manually add it to the gff file and fasta but then the gff file could not be parsed. Do you have any advice on how to address this? Thanks!
