### ISSUE TITLE
Strange request: adaptors in final fa, mask?

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#602]
Hi Jon,

One of my Funannotate annotated genome has adaptor contamination in it (in three places). NCBI suggested to mask it and resubmit.

Can I pass an altered genome.fasta (rather than the original) plus funannotate genes with annotation to re - create .sqn files again? The coordinates wont change if I replace with NNNs. 

Sorry for the daft question. The only other option is to re run the whole thing ..

cheers,

Pete

**Comment by nextgenusfs** [comment]
Hi Pete.  This has happened to me before as well, I think I ended up fixing the assembly and re-running -- I had some scripts to do this automatically but I doubt they are useful anymore as it was probably 5-6 years ago. 

You should just be able to run `tbl2asn` with your updated genome, there is a wrapper for that in `funannotate fix` but the requirement is to have a GenBank file. 

So probably the simplest way would be to generate a new GBK file with:
```
funannotate util tbl2gbk -f new_masked_genome.fasta -s "Genus species" --isolate "etc" \
    --sbt submission.sbt -t annotate_results/genome.tbl
```
You can then swap that new GBK file for the one in annotate_results/genome.gbk.  Then should be able to run `funannotate fix` on that annotate_results folder and it will re-generate all of the files you need for submission, ie the .sqn file.

**Comment by nextgenusfs** [comment]
When you do this next time, this was my advice from several years ago (submit just the genome first and get the okay from NCBI, then run funannotate on the final approved assembly). https://funannotate.readthedocs.io/en/latest/predict.html#submitting-to-ncbi-what-should-i-know

**Comment by peterthorpe5** [comment]
Thank you very much. I really appreciate your help. once again!!!!

**Comment by hyphaltip** [comment]
[AAFTF](https://github.com/stajichlab/AAFTF) should also screen the vector for you too - it misses a few of the contamination problems because we don't have the same contamdb that NCBI uses.

**Comment by hyphaltip** [comment]
If it is only small amounts, I trim by hand in sequin, if it is internal but really small I might just replace the vector with 'N's unless I am worried about the vector causing chimera

**Comment by peterthorpe5** [comment]
Hi Jon (thank you everyone for your comments!). 

I have a slight problem generating the .gbk
    version:     1.8.2
    and tried with :

    version:     1.8.8
    (Same error). 


$ funannotate util tbl2gbk -f fixed.fa  -s "Crenichthys_baileyi" --strain "V.1.0" --tbl annotate_results/Crenichthys_baileyi_V.1.0.tbl

Traceback (most recent call last):
  File "/mnt/shared/scratch/pthorpe/apps/conda/envs/funannotate/bin/funannotate", line 705, in <module>
    main()
  File "/mnt/shared/scratch/pthorpe/apps/conda/envs/funannotate/bin/funannotate", line 695, in main
    mod.main(arguments)
  File "/mnt/shared/scratch/pthorpe/apps/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/utilities/tbl2gbk.py", line 176, in main
    prefix = locustagGB(os.path.join(tmp, 'genome.gbf'))
  File "/mnt/shared/scratch/pthorpe/apps/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/utilities/tbl2gbk.py", line 55, in locustagGB
    with open(input, 'r') as infile:
**IOError: [Errno 2] No such file or directory:** 'Crenichthys_baileyi_V.1.0_tmp/genome.gbf'

**Comment by nextgenusfs** [comment]
Looks like tbl2asn failed, I might have some time later today to look at it.

**Comment by peterthorpe5** [comment]
I am sorry. I did run when I allocated it with more RAM. Sorted!

**Comment by peterthorpe5** [comment]
HI Jon,

funannotate version:     1.8.8   funannotate fix  did not run tbl2asn.
funannotate fix -i annotate_results/Crenichthys_baileyi_V.1.0.gbk -t annotate_results/Crenichthys_baileyi_V.1.0.tbl --drop remove

would you please be able to advise on where the problem may have occurred?

**Comment by nextgenusfs** [comment]
`funannotate fix` is running the same tbl2asn functions as the rest of the code, so perhaps you misunderstood the `--drop` option, unless `remove` is a file name....
```
$ funannotate fix

Usage:       funannotate fix <arguments>
version:     1.8.8

Description: Script takes a GenBank genome annotation file and an NCBI tbl file to
             generate updated annotation. Script is used to fix problematic gene models
             after running funannotate predict or funannotate update.

Required:
  -i, --input    Annotated genome in GenBank format.
  -t, --tbl      NCBI tbl annotation file.
  -d, --drop     Gene models to remove/drop from annotation. File with locus_tag 1 per line.

Optional:
  -o, --out      Output folder
  --tbl2asn      Parameters for tbl2asn. Default: "-l paired-ends"
        
```

**Comment by peterthorpe5** [comment]
HI Jon, yes remove was just file with a list (one per line) of genes to remove that had naughty stop codons in the middle.
