### ISSUE TITLE
Funannotate Ubuntu installation 

### ISSUE THREAD

**Issue by kalonji08** [nextgenusfs/funannotate#603]
Hello 
I'm installing Funannotate on  Dell Precision T7610. 
Here are the specs : 2 CPUs: xeon R ES-2687w v2 (16 cores 32 threads)
RAM: 80 Gb
OS: Linux (Ubuntu)SSD: 500Gb
I would like to find out if it would possible to install Funannotate with theses specs ?
So far, I've setup a conda environment  and I'm stuck here see picture 
![Funnanotate](https://user-images.githubusercontent.com/59872248/120672002-33e75500-c492-11eb-87bd-d8ff16204e6c.PNG)
attached 

Any assistance would be appreciated Thanks in advance

**Comment by AdamVS** [comment]
This should be possible, but I would recommend using a mamba installation to reduce the time needed to solve the conda environment and packages. See here:
https://github.com/mamba-org/mamba
then after installation:
`mamba create -n funannotate funannotate`

**Comment by nextgenusfs** [comment]
I agree with @AdamVS -- system should be capable, its just conda is super slow at solving the dependencies.  `mamba` should be much faster, you install it in your base conda environment with `conda install -n base mamba` and then use @AdamVS command above to create the funannotate environment.

**Comment by kalonji08** [comment]
Thank you very much @AdamVS and @nextgenusfs I will do that and let you know how it goes

**Comment by kalonji08** [comment]
@AdamVS @nextgenusfs Thank you again I managed to install in less than 1h.
 I just have one last query: I have the error when running :funannotate test -t all --cpus X
Should i be worried about it? 
![FunA Q2](https://user-images.githubusercontent.com/59872248/121267476-87a3d500-c8bc-11eb-8d05-ab5ab772b655.JPG)

**Comment by nextgenusfs** [comment]
Did you get any errors when running the setup database script and/or setting the FUNANNOTATE_DB environment variable?

**Comment by kalonji08** [comment]
@nextgenusfs The first time i didn't set the actual directory then this one worked:
 echo "export FUNANNOTATE_DB=/home/kalonji/funannotate_db " > ~/miniconda3/envs/funannotate/etc/conda/activate.d/funannotate.sh
But i didn't run this one since it was "Unset"
echo "unset FUNANNOTATE_DB=/home/kalonji/funannotate_db " > ~/miniconda3/envs/funannotate/etc/conda/activate.d/funannotate.sh
Was i supposed to run it as well?

**Comment by nextgenusfs** [comment]
The unset file should go in the deactivate.d/ folder otherwise it is being set and then under when you type conda activate. 

Unset should be ~/miniconda3/envs/funannotate/etc/conda/deactivate.d/funannotate.sh

**Comment by kalonji08** [comment]
@nextgenusfs I have changed that Thanks. I think i know what the issue. After running:  funannotate check --show-versions
It looks like I'm missing the following dependencies: How can get in such a way that it will be detected by Funannotate?
![FunA4](https://user-images.githubusercontent.com/59872248/121413971-84652380-c966-11eb-973e-1a348eca07ca.JPG)

**Comment by nextgenusfs** [comment]
Those are optional dependencies and aren't needed for test to work. What is the output of funannotate database command?

**Comment by kalonji08** [comment]
This is the output
![image](https://user-images.githubusercontent.com/59872248/121586823-67972180-ca34-11eb-90cd-1cfb3a4a1cdd.png)

**Comment by kalonji08** [comment]
i made some progress, the test stopped at Funannotate compare because of Proteinortho
![image](https://user-images.githubusercontent.com/59872248/121601741-a209ba00-ca46-11eb-94b0-97b7590869b5.png)

**Comment by nextgenusfs** [comment]
Check the other issues but i think you can downgrade proteinortho to 6.0.16 which has worked for me before.

**Comment by AdamVS** [comment]
I'm having some trouble downgrading to 6.0.16, so I will try to recompile proteinortho (see here https://gitlab.com/paulklemm_PHD/proteinortho/-/issues/51)

I note that Kalonji @kalonji08 is using a Dell T7610. I'm using a T7600.

**Comment by kalonji08** [comment]
I will check the log file if there are other issues besides Proteinortho Thanks a lot. @AdamVS can you please let me know when you manage to downgrade?

**Comment by nextgenusfs** [comment]
It is possible that some other versions might work, I literally cycled through like 10 versions to find the one that worked on one of my systems a few months ago which was the 6.0.16 -- it seems to be system dependent so there must be come dependency version issue that has not been identified yet. But sounds like the rest of your install is working, so compare is a minor part of the annotation process and honestly that script is now probably 5 years old. So you may find it could use some improvement anyway. In short, I wouldn't let this one dependency stop me from using the rest of the pipeline.

**Comment by kalonji08** [comment]
I totally agree! Thank you so much for the help. I really appreciate it. This means a lot to me

**Comment by kalonji08** [comment]
Hello, I just wanted to let you know that the new proteinortho version  6.0.31  has solved the issue. Thanks for the help
