### ISSUE TITLE
Issues with permissions running funannotate predict

### ISSUE THREAD

**Issue by janphilipoeyen** [nextgenusfs/funannotate#605]
**Are you using the latest release?**
$ funannotate version
funannotate v1.8.7

**Describe the bug**
Permission error to info.json when running predict
> PermissionError: [Errno 13] Permission denied: 'info.json'

I am using a version (conda installation) that was installed by a different user on our cluster and get a permission error when running predict. From reading in other issues, it seems that this is usually caused by a lack of permissions related to either the augustus config dir or the directory with the actual info.json file. We changed the permissions of both folders recursively using chmod -R 777, but this did not resolve the issue (see examples below). Are there other directories or files we might have to change permissions or should we set them in a different way?

> funannotate-1.8.7/database/trained_species/tribolium2012]$ ll
> total 1
> drwxrwsrwx 2 user1 nn9825k  32 Jun  8 13:25 augustus
> -rwxrwsrwx 1 user1 nn9825k 286 Jun  8 13:25 info.json

> /funannotate-1.8.7/config]$ ll
> total 3
> drwxrwsrwx   2 user2 nn9825k   6 May  3 21:12 cgp
> drwxrwsrwx   2 user2 nn9825k  12 May  3 21:12 extrinsic
> drwxrwsrwx   2 user2 nn9825k  25 May  3 21:12 model
> drwxrwsrwx   2 user2 nn9825k   3 May  3 21:12 profile
> drwxrwsrwx 110 user2 nn9825k 108 May  3 21:12 species

**Full error**
[Jun 08 04:00 PM]: OS: CentOS Linux 7, 80 cores, ~ 198 GB RAM. Python: 3.7.10
[Jun 08 04:00 PM]: Running funannotate v1.8.7
[Jun 08 04:00 PM]: Found training files, will re-use these files:
  --rna_bam train/training/funannotate_train.coordSorted.bam
  --pasa_gff train/training/funannotate_train.pasa.gff3
  --transcript_alignments train/training/funannotate_train.transcripts.gff3
Traceback (most recent call last):
  File "/cluster/projects/nn9825k/admin/funannotate-1.8.7/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/cluster/projects/nn9825k/admin/funannotate-1.8.7/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/cluster/projects/nn9825k/admin/funannotate-1.8.7/lib/python3.7/site-packages/funannotate/predict.py", line 405, in main
    LOCALAUGUSTUS, 'species', args.busco_seed_species), overwrite=True)
  File "/cluster/projects/nn9825k/admin/funannotate-1.8.7/lib/python3.7/site-packages/funannotate/library.py", line 8178, in copyDirectory
    shutil.rmtree(dest)
  File "/cluster/projects/nn9825k/admin/funannotate-1.8.7/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/cluster/projects/nn9825k/admin/funannotate-1.8.7/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/cluster/projects/nn9825k/admin/funannotate-1.8.7/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'info.json'

**What command did you issue?**
funannotate predict \
        -i BM3_genome.processed.fasta \
        -o train \
        -s "Chrysoperla carnea" \
        --strain BM3 \
        --cpus ${SLURM_NTASKS_PER_NODE} \
        --busco_seed_species tribolium2012 \
        --busco_db endopterygota \
        --organism other \
        --SeqCenter NSC \
        --max_intronlen 150000

**Logfiles**
funannotate-predict.log
[06/08/21 16:00:44]: /cluster/projects/nn9825k/admin/funannotate-1.8.7/bin/funannotate predict -i BM3_genome.processed.fasta -o train -s Chrysoperla carnea --strain BM3 --cpus 5 --busco_seed_species tribolium2012 --busco_db endopterygota --organism other --SeqCenter NSC --max_intronlen 150000

[06/08/21 16:00:44]: OS: CentOS Linux 7, 80 cores, ~ 198 GB RAM. Python: 3.7.10
[06/08/21 16:00:44]: Running funannotate v1.8.7
[06/08/21 16:00:45]: GeneMark path: /cluster/projects/nn9825k/admin/gmes_linux_64
[06/08/21 16:00:48]: Full path to gmes_petap.pl: /cluster/projects/nn9825k/admin/gmes_linux_64/gmes_petap.pl
[06/08/21 16:00:48]: GeneMark appears to be functional? True
[06/08/21 16:00:52]: Found training files, will re-use these files:
  --rna_bam train/training/funannotate_train.coordSorted.bam
  --pasa_gff train/training/funannotate_train.pasa.gff3
  --transcript_alignments train/training/funannotate_train.transcripts.gff3

**OS/Install Information**
$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.4
-------------------------------------------------------
You are running Python v 3.7.10. Now checking python packages...
biopython: 1.76
goatools: 1.0.15
matplotlib: 3.3.4
natsort: 7.1.1
numpy: 1.20.1
pandas: 1.2.3
psutil: 5.7.0
requests: 2.25.1
scikit-learn: 0.24.1
scipy: 1.5.3
seaborn: 0.11.1
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/cluster/projects/nn9825k/admin/funannotate
$PASAHOME=/cluster/projects/nn9825k/admin/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/cluster/projects/nn9825k/admin/funannotate/opt/trinity-2.8.5
$EVM_HOME=/cluster/projects/nn9825k/admin/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/cluster/projects/nn9825k/admin/funannotate/config/
$GENEMARK_PATH=/cluster/projects/nn9825k/admin/gmes_linux_64
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.4.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.7
emapper.py: There was an error retrieving eggnog-mapper DB data: not a valid file "/cluster/projects/nn9825k/admin/funannotate/lib/python3.7/site-packages/data/eggnog.db"
Maybe you need to run download_eggnog_data.py
emapper-2.0.8-2 / Expected eggNOG DB version: 5.0.1 / Installed eggNOG DB version: unknown / Local diamond version: diamond 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1

ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.64_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.1
kallisto: 0.46.1
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.28
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.1.4
tRNAscan-SE: 2.0.7 (Oct 2020)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed

**Comment by nextgenusfs** [comment]
This seems to suggest it is in the directory you are in as the error is in the `LOCALAUGUSTUS, 'species', args.busco_seed_species`. Which I guess indicates it cannot remove a sub directory where you are working, did the other user issue command first and then different user trying to use the same command? I would think a fresh run or new output directory would fix this.
https://github.com/nextgenusfs/funannotate/blob/master/funannotate/predict.py#L400-L403

**Comment by janphilipoeyen** [comment]
Thank you for the quick reply. Indeed, the problem was due to write-restrictions in the predict_misc subfolders. I am not sure exactly why this happened, but removing the predict output folders and restarting seems to have done the trick.
