### ISSUE TITLE
EVM RAM usage

### ISSUE THREAD

**Issue by DrPintoThe2nd** [nextgenusfs/funannotate#608]
Hi Jon,

I was running v1.5 via a docker that has worked for me for years, which for some reason started stalling while running BUSCO (sad face). So I have just tried updating to the latest version to fix this issue and here we are:

I think EVM is sucking up all of my 128Gb of RAM and I'm looking for a way to maybe cap it somehow within he funannotate pipeline..? Notable dataset info: genome is ~1.8Gb

Thanks in advance, this is a super great tool!!

Bug Report:
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.
****Using funannotate-docker downloaded the other day
[Jun 16 08:30 PM]: OS: Debian GNU/Linux 10, 48 cores, ~ 132 GB RAM. Python: 3.7.10
[Jun 16 08:30 PM]: Running funannotate v1.8.8

**Describe the bug**
".................. 
[Jun 16 08:45 PM]: Summary of gene models passed to EVM (weights):
  Source         Weight   Count 
  Augustus       1        23911 
  Augustus HiQ   2        4484  
  GlimmerHMM     1        278526
  pasa           6        15403 
  snap           1        193530
  Total          -        515854
[Jun 16 08:45 PM]: EVM: partitioning input to ~ 35 genes per partition using min 1500 bp interval
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 484, in <module>
    partitions=args.no_partitions)
  File "/venv/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 295, in create_partitions
    lib.softwrap(str(SeqRecords[chr].seq[coords[0] - 1:coords[1]]))))
  File "/venv/lib/python3.7/site-packages/Bio/File.py", line 248, in __getitem__
    record = self._proxy.get(self._offsets[key])
  File "/venv/lib/python3.7/site-packages/Bio/SeqIO/_index.py", line 52, in get
    return next(self._iterator(StringIO(self.get_raw(offset).decode())))
  File "/venv/lib/python3.7/site-packages/Bio/SeqIO/_index.py", line 235, in get_raw
    line = handle.readline()
MemoryError
[Jun 16 08:52 PM]: Evidence modeler has failed, exiting"

**What command did you issue?**
Copy/paste the command used.

./funannotate-docker predict \
	-i genome_masked.fasta --species "My Species" \
	--transcript_evidence transcriptome.fasta \
	--cpus 36 --organism other --optimize_augustus \
	--protein_evidence uniprot_sprot.fasta -o species_training_folder;

**Logfiles**
Please provide relavent log files of the error. 

No logfiles of note that I can see, but it doesn't quite make it through chromosome #1 (genome size ~1.8Gb) so could be a chromosome length issue..(?)

**OS/Install Information**
 -  output of `funannotate check --show-versions`
logname: no login name
logname: no login name
-------------------------------------------------------
Checking dependencies for 1.8.8
-------------------------------------------------------
You are running Python v 3.7.10. Now checking python packages...
biopython: 1.78
goatools: 1.0.15
matplotlib: 3.4.2
natsort: 7.1.1
numpy: 1.20.3
pandas: 1.2.4
psutil: 5.8.0
requests: 2.25.1
scikit-learn: 0.24.2
scipy: 1.6.2
seaborn: 0.11.1
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.15
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/venv/config
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
Traceback (most recent call last):
  File "/venv/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/venv/lib/python3.7/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/venv/lib/python3.7/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/venv/lib/python3.7/site-packages/ete3/__init__.py)
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.8
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.18-r1015
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.5
tRNAscan-SE: 2.0.7 (Oct 2020)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: ete3 not installed
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed

**Comment by nextgenusfs** [comment]
Interesting, it actually seems like biopython SeqIO.index() is running out of memory? Hard to believe it would be requesting more than 128 GB? Or maybe there is some cap on what it can hold in memory for contig length. I think we can do this a slightly different way, let me see if I can find other similar errors with biopythons SeqIO.index()

**Comment by nextgenusfs** [comment]
Can you try latest in master, I just updated EVM in Biopython to use index on disk instead of memory. Hopefully that fixes it.

**Comment by DrPintoThe2nd** [comment]
This might be a dumb question, does "docker pull" grab the latest in master?
For reference, it's only getting ~10% of the way through chromosome 1 (22Mb).

First, I re-pulled and tried again:
"[Jun 17 03:18 PM]: EVM: partitioning input to ~ 35 genes per partition using min 1500 bp interval
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 485, in <module>
    partitions=args.no_partitions)
  File "/venv/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 296, in create_partitions
    lib.softwrap(str(SeqRecords[chr].seq[coords[0] - 1:coords[1]]))))
  File "/venv/lib/python3.7/site-packages/Bio/File.py", line 551, in __getitem__
    record = proxies[file_number].get(offset)
  File "/venv/lib/python3.7/site-packages/Bio/SeqIO/_index.py", line 52, in get
    return next(self._iterator(StringIO(self.get_raw(offset).decode())))
  File "/venv/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 74, in __next__
    return next(self.records)
  File "/venv/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 206, in iterate
    Seq(sequence), id=first_word, name=first_word, description=title,
  File "/venv/lib/python3.7/site-packages/Bio/Seq.py", line 1725, in __init__
    self._data = bytes(data, encoding="ASCII")
MemoryError
[Jun 17 03:25 PM]: Evidence modeler has failed, exiting"

To double-check, I pulled it down from conda set up the virtual env and resumed the run: 
"[Jun 17 10:46 AM]: EVM: partitioning input to ~ 35 genes per partition using min 1500 bp interval
Traceback (most recent call last):
  File "/media/bjp/bioconda/miniconda/envs/funannotate/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 484, in <module>
    partitions=args.no_partitions)
  File "/media/bjp/bioconda/miniconda/envs/funannotate/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 295, in create_partitions
    lib.softwrap(str(SeqRecords[chr].seq[coords[0] - 1:coords[1]]))))
  File "/media/bjp/bioconda/miniconda/envs/funannotate/lib/python3.7/site-packages/Bio/File.py", line 227, in __getitem__
    record = self._proxy.get(self._offsets[key])
  File "/media/bjp/bioconda/miniconda/envs/funannotate/lib/python3.7/site-packages/Bio/SeqIO/_index.py", line 52, in get
    return next(self._iterator(StringIO(self.get_raw(offset).decode())))
MemoryError
[Jun 17 10:56 AM]: Evidence modeler has failed, exiting"

Let me know if neither of these did what I hoped that they did..! haha

Thanks again, Jon!!
Sorry for the hassle!

**Comment by nextgenusfs** [comment]
Yes docker pull should be getting the most recent changes. But the mem issue could be related to your docker settings, ie I thought there was a setting to control RAM available to the docker image?

**Comment by DrPintoThe2nd** [comment]
For posterity, I restarted the computer to make sure it wasn;t something weird, then I went into the funannotate-docker file and made these adjustments (from this documentation https://docs.docker.com/config/containers/resource_constraints/ ):

exec docker run --rm "${IT[@]}" --user "${USER}" -e TZ="${TZ}" **--memory="120g" --memory-swap="-1"** --workdir "${WORKDIR}" --mount "${MOUNT}" nextgenusfs/funannotate:latest funannotate "$@"

It still isn't working.. the edits didn't appear to affect anything else negatively, i.e. the test script ran fine
#########################################################
SUCCESS: `funannotate predict` test complete.
#########################################################

Is this what you were thinking?

**Comment by nextgenusfs** [comment]
I guess it must work differently on Linux, on my Mac for example the docker parent application has RAM limits defined for all images/containers. 

So it must not be that. 

In newer versions of the code with EVM is it creates partitions manually in a way to not spit any gene models. You can try to pass --no-evm-partitions which will treat each contig as a separate call to EVM. This might use a lot of RAM as well and/or be very slow but it will skip the partitioning function that is erroring out. 

I don't really understand how it is running out of memory. If you are used to python and biopython you could try to run SeqIO.index_db call on your genome and see if causes same problem. What is odd is that biopython has parsed your genome several times before this step.

**Comment by DrPintoThe2nd** [comment]
Interesting.. yeah, it just starts cranking and doesn't stop. It may just be a one-off(?) I may look into EVM specifically at some point if I need to, but I'm simultaneously trying to get my v1.5 docker back up and running and I think I just figured that out -- the EVM version there uses almost no RAM(!). I'll close this bug report and hope that no one else hits this issue..

Thanks again, Jon! Appreciate all your work on this program!
Cheers!

**Comment by nextgenusfs** [comment]
So to be clear it hasn't even started running EVM yet. The problem with the old way of running EVM is the partitioning script chunks the data with no regard for the location of gene models, it tries to account for this by offsetting coordinates and overlapping but it results in valid gene models that happen to land on the edges of these partitions to be lost or split. So I wrote a different partitioning strategy that is aware of the gene model boundaries and tries to avoid them.

**Comment by DrPintoThe2nd** [comment]
I believe it started running EVM(?). So it its last act is making a new directory called "EVM" and populating it with subdirectories for each scaffold -- but it only gets ~10% through "LG_1" before blowing out the memory.

It looks like v1.5 just successfully finished EVM!

**Comment by nextgenusfs** [comment]
That's expected, v1.5 is using default EVM partitioning -- which as I said above I re-wrote because its problematic. Your error in v1.8.8 is due to the partitioning strategy I wrote that feeds the data into EVM (EVM is not failling as it hasn't called that tool at all yet). So I need to get a genome assembly large enough to make it fail in my hands, otherwise I don't know how to fix it.

**Comment by DrPintoThe2nd** [comment]
This snake genome has a few really big macrochromosomes that should more than trigger this issue: https://www.ncbi.nlm.nih.gov/genome?term=naja[orgn]

**Comment by hyphaltip** [comment]
I can try this as well on our machines. I have a 1.1gb genome I'm working from and we did a 1.8 insect but I don't know if we have 100+Mb chroms that might be triggering here.  How about I setup a project https://github.com/hyphaltip/Annotate_CobraGenome and see if I can replicate issues.
