### ISSUE TITLE
CDS and mRNA seq extraction doesn't respect codon_start

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#611]
This line retrieves / respects the codon_start when generating the protein translation. however the lines which establish the coding seq in first place don't - so we should probably move this upstream in some way to slice off `codon_start` nucleotides from the coding sequence so it can be translateable. 

https://github.com/nextgenusfs/funannotate/blob/74ff70fa0699109b424bde227d5d9a7d6915bd80/funannotate/library.py#L2916

**Comment by nextgenusfs** [comment]
merged.
