### ISSUE TITLE
BUSCO protein FASTA output was not parsed correctly

### ISSUE THREAD

**Issue by liu3zhenlab** [nextgenusfs/funannotate#618]
Dear Jon,

Thank you for developing this useful tool. I can run your docker version without a problem. However, I would like to add genemark. Now I came across a BUSCO problem. The step of "Running BUSCO to find conserved gene models for training ab-initio predictors" always returned very few valid BUSCO predictions. I found the fasta data in `extracted_proteins` under the directory of `predict_misc/busco/run_magnaporthe_grisea/augustus_output/` are not in a right format. For example, in the file `predict_misc/busco/run_magnaporthe_grisea/augustus_output/extracted_proteins/EOG092600SD.faa.1`,  the protein sequence contains non-protein information (Evidence
%CDSCDS5'UTR3'UTRhintincompatible) as shown below.

```
>g1[chr7:2503445-2503871]
MAIFSNKKFRGAADANKLGIKYRTAMQKYPFLLFGLPFISIIVAGSFVLTPATAIRYEKHDRRVRQMTKEEELGLGKDRRQVDIREEYYRLAAKDLDNWEQKRVERFKGESDGKLEvidence
%CDSCDS5'UTR3'UTRhintincompatible
```
Is this possible a bug in the code of `*/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-BUSCO2.py`? Or is this an Augusto issue?

Thank you.
-Sanzhen

**Comment by hyphaltip** [comment]
Can you describe what version of the package this is?
Generally that is all the results from busco running so I'm unclear that would be generated by funnannotate itsself. Can you also report which version of busco you have installed.

**Comment by liu3zhenlab** [comment]
funannotate 1.8.8
Augustus version is 3.4.0. Is BUSCO from Augustus?

**Comment by nextgenusfs** [comment]
The internal BUSCO version is not compatible with Augustus 3.4 and greater because they changed an output format. We have on our list of stuff to do to upgrade to latest BUSCO. So to get it working just downgrade Augustus to a version <3.4.

**Comment by liu3zhenlab** [comment]
I replace Augustus 3.4.0 with 3.3.3 and it worked. Thank you.
