### ISSUE TITLE
NCBI submission issues

### ISSUE THREAD

**Issue by athulmenon** [nextgenusfs/funannotate#619]
Hi Jon,

Hope you are doing good.

I have been trying to submit the genome to NCBI annotated using funannotate. Unfortunately, I missed it to submit earlier for contamination check before the annotation. Now after submission, NCBI has suggested removing some of the sequences from one scaffold. I masked those bases with "N", but is there any way to edit .sqn and .tbl files to reflect the changes for submission. I saw you have mentioned it will be difficult to do it in the readme file. 

Currently, after masking the .fsa file I replaced the masked fasta and deleted the annotations in .sqn files at the positions NCBI mentioned to trim.

Any help will be appreciated. Thank you.

Regards,
Athul

**Comment by hyphaltip** [comment]
So if you masked the bases by replacing with N in the fasta genome file, the feature coordinates don’t need to change. So you just rerun the tbl2asn cmd or you can run funannotate fix to regenerate sqn file.

**Comment by peterthorpe5** [comment]
@athulmenon (I have nothing to do with the code but am a user and have had the same issues). Jon and hyphaltip both helped loads. These are my notes: (genome.fa is your new NNN masked one)

conda activate funannotate1.8.7

funannotate util tbl2gbk -f genome.fa  -s "sp name" --strain "V.1.0" --tbl annotate_results/PRE_existing.tbl

funannotate fix --tbl PREexisting.tbl --input OUTPUTTED.gbk
funannotate fix -i genome.gbk -t PREexisting.tbl
# run tbl to asn manually. 
python \
PATH_TO/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/tbl2asn_parallel.py \
-i FULL_PATH/prexisting.tbl \
-f full_path/genome.scaffolds.fa \
-o folder_name/ \
--sbt PATH_TO/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/config/test.sbt \
-d report.discrepency.txt -s species -t "-l paired-ends" -v 1 -c 12 --strain V.1.0

**Comment by athulmenon** [comment]
Thank you so much @peterthorpe5 @hyphaltip for your answers. I have generated the files using the above method. Waiting for the submission approval.

Regards,
Athul
