### ISSUE TITLE
passing KEGG annotations to funannotate annotate

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#62]
Is there any way to pass KEGG annotation to funannotate annotate, like it works for InterProScan?
Actually KEGG ontology is the part of EggNog 4.5, it it possible to add them in the next revisions of funannotate?

**Comment by nextgenusfs** [comment]
Yes plausibly.  If there is a way to add the search on the command line I can do it.  I have not integrated the new eggnog mapper yet, basically right now funannotate is just doing a HMMer search using the HMM library from EggNog 4.5. 

The other way in which you can always add any annotation you want is to generated an annotation file for GAG which is a 3 column tsv file that has:
```
mRNA-ID    note    Whatever annotation here
```
Have a look at the files that start with `annotations.*` in the `annotate_misc` folder.  You could parse any output that you want and put it into that format and will get incorporated.

**Comment by MichaelFokinNZ** [comment]
Thank you!
