### ISSUE TITLE
Clean EVM gff is not written when no gene filtered out

### ISSUE THREAD

**Issue by abretaud** [nextgenusfs/funannotate#620]
**Are you using the latest release?**
Yes

**Describe the bug**
When no gene gets filtered out after EVM, the clean EVM gff is not written, generating an error later.
The bug comes from this line I guess: https://github.com/nextgenusfs/funannotate/blob/master/funannotate/library.py#L6782
= the code should just write everything to the clean output when numTotal == 0

**What command did you issue?**
`funannotate predict --input '/tmp/tmps7cf2xyi/files/000/dataset_1.dat' --out output  --database '/funannotate_db'  --species 'fvd' --isolate 'vfd' --strain 'bgf' --organism 'other' --ploidy 1 --SeqCenter 'CFMR' --SeqAccession '12345' --name 'FUN_' --numbering 1     --p2g_pident 80 --p2g_prefilter diamond  --augustus_species 'fly' --min_training_models 200    --busco_seed_species 'fly' --busco_db 'insecta'   --evm-partition-interval 1500   --min_intronlen 10 --max_intronlen 3000 --min_protlen 10 --keep_no_stops --repeat_filter overlap blast`

**Logfiles**
```
[Jul 20 05:06 PM]: 18 total gene models from EVM
[Jul 20 05:06 PM]: Generating protein fasta files from 18 EVM models
[Jul 20 05:06 PM]: now filtering out bad gene models (< 10 aa in length, transposable elements, etc).
[Jul 20 05:06 PM]: 0 gene models remaining
[Jul 20 05:06 PM]: Predicting tRNAs
[Jul 20 05:06 PM]: CMD ERROR: tRNAscan-SE -o output/predict_misc/tRNAscan.out --thread 1 /tmp/tmps7cf2xyi/job_working_directory/000/4/working/output/predict_misc/genome.softmasked.fa
[Jul 20 05:06 PM]: tRNAscan-SE seems to have failed, check logfile for error. You can pass precalculated results to --trnascan
[Jul 20 05:06 PM]: Generating GenBank tbl annotation file
Traceback (most recent call last):
  File "/home/abretaud/miniconda3/envs/__funannotate@1.8.7/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/abretaud/miniconda3/envs/__funannotate@1.8.7/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/abretaud/miniconda3/envs/__funannotate@1.8.7/lib/python3.7/site-packages/funannotate/predict.py", line 1860, in main
    args.numbering, args.SeqCenter, args.SeqAccession, tbl_file)
  File "/home/abretaud/miniconda3/envs/__funannotate@1.8.7/lib/python3.7/site-packages/funannotate/library.py", line 3246, in GFF2tbl
    Genes = gff2dict(evm, fasta, Genes)
  File "/home/abretaud/miniconda3/envs/__funannotate@1.8.7/lib/python3.7/site-packages/funannotate/library.py", line 4230, in gff2dict
    with open(file, 'r') as input:
FileNotFoundError: [Errno 2] No such file or directory: 'output/predict_misc/evm.cleaned.gff3'
```

**OS/Install Information**
The latest package from conda...

**Comment by nextgenusfs** [comment]
Okay, I guess it should die gracefully if there are 0 gene models remaining.....

**Comment by abretaud** [comment]
Hum, no, the problem is when all gene models remain (=0 removal)

**Comment by nextgenusfs** [comment]
```
[Jul 20 05:06 PM]: 18 total gene models from EVM
[Jul 20 05:06 PM]: Generating protein fasta files from 18 EVM models
[Jul 20 05:06 PM]: now filtering out bad gene models (< 10 aa in length, transposable elements, etc).
[Jul 20 05:06 PM]: 0 gene models remaining
```
Sorry I was on my phone and just read the above.....  you are right, missing the else clause writing them all.

**Comment by abretaud** [comment]
Thanks for the quick fix! Tested locally, it works great
