### ISSUE TITLE
funannotate train enters "T" (stopped) state after Trimmomatic trimming step

### ISSUE THREAD

**Issue by papelypluma** [nextgenusfs/funannotate#622]
Hi. I'd like to ask for help if there's a way to get the training step run through without entering a "T" state. I wish I could provide more information on this, but the log file doesn't have any errors. As soon as the Trimmomatic step completes, the funannotate train enters a "T" state/status. I installed funannotate via Conda and ran the "funannotate test -t all". Any help is much appreciated. Thank you.

**Comment by nextgenusfs** [comment]
Can you post the log output from `funannotate train -t rna-seq --cpus X --debug`?

**Comment by papelypluma** [comment]
Hi @nextgenusfs. Thanks for the help and advice! For some reason, it's now working after running the command in the foreground. For some reason, the job enterered a T state when I ran it the background. Now running it on the terminal (via screen), and it seems to proceed without errors. I should've looked at it closely and tried other options.

**Comment by nextgenusfs** [comment]
Great, glad you got it working.
