### ISSUE TITLE
Releases are not tagged on Docker Hub

### ISSUE THREAD

**Issue by alanorth** [nextgenusfs/funannotate#625]
Releases are tagged on GitHub and PyPI, but not on Docker Hub. For posterity in a scientific computing environment it is good to be able to run and reference a certain version. We should be able to pull tagged versions from Docker Hub.

**Comment by nextgenusfs** [comment]
Yeah we will have to add a GitHub action to tag on releases.

**Comment by alanorth** [comment]
Sure I understand. I didn't realize that releases were published to Docker Hub via GitHub Actions. I only do simple builds with Actions and I only release on GitHub manually, so I don't think I can help there. I will discuss the shortcomings of the Singularity/Docker version with my scientists and perhaps stick to the Conda route (though last I checked it is [still 1.8.7](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/funannotate)).

**Comment by nextgenusfs** [comment]
It shouldn't be too hard to add the tagged build. If it wasn't automated I'm not sure I'd get around to manually releasing on multiple platforms. Yes bioconda build is giving me problems from the build environment so still trying to work that out -- you can always install with pip from a tagged release or the master.

**Comment by nextgenusfs** [comment]
Okay, this should be working now.  When new releases are tagged they will get uploaded to docker hub. Docker hub 'latest' is always built after every commit to master.

**Comment by alanorth** [comment]
Wow thanks! Looks like you really went to town on this. I know testing new CI workflows can be frustrating and hilarious for the git commit history... :P
