### ISSUE TITLE
fuannotate predict raises subprocess.CalledProcessError on diamond command

### ISSUE THREAD

**Issue by papelypluma** [nextgenusfs/funannotate#626]
Dear funannotate developers,

I'd like to seek help on the error: subprocess.CalledProcessError: Command '['diamond', 'dbinfo', '-d', '/database/funannotate_db/repeats.dmnd']' returned non-zero exit status 1. This error comes out immediately after running funannotate predict pointing to lines 553 (for line in execute(['diamond', 'dbinfo', '-d', database]):) and 568 (if not lib.CheckDiamondDB(blastdb):) of library.py. The command works fine when run manually on the terminal. Thank you in advance for the help.

**Comment by nextgenusfs** [comment]
Version of funannotate? Version of diamond?

**Comment by papelypluma** [comment]
Hi @nextgenusfs. I'm using funannotate v1.8.7 with diamond v2.0.8. funannotate was installed via mamba, while funannotate check --show-versions indicates that all dependencies are available/installed as well.

**Comment by nextgenusfs** [comment]
And from that environment what is result of :

diamond dbinfo -d /database/funannotate_db/repeats.dmnd


I suspect that your database setup didn't work and perhaps that dmnd database is empty or corrupt. I don't know why else it would fail.

**Comment by papelypluma** [comment]
Here's the result:

> diamond v2.0.8.146 (C) Max Planck Society for the Advancement of Science
> Documentation, support and updates available at http://www.diamondsearch.org
> 
>           Database type  Diamond database
> Database format version  3
>           Diamond build  146
>               Sequences  11950
>                 Letters  9920808

**Comment by nextgenusfs** [comment]
Hmm. So then when you run funannotate test -t predict you are getting the error you showed originally? I guess I haven't tested diamond v2.0.8 but unless it is somehow exiting with non zero status on that command I don't understand why it would fail.

**Comment by nextgenusfs** [comment]
I guess the next level of debug is if you can open up the python interpreter from that environment and try this (obviously use your path to the repeats.dmnd database). 
```
>>> import funannotate.library as lib
>>> lib.getDiamondVersion()
'2.0.5'
>>> lib.CheckDiamondDB('/usr/local/share/funannotate/repeats.dmnd')
True
>>> 
```

**Comment by nextgenusfs** [comment]
I upgraded to v2.0.8 and cannot replicate:
```
$ diamond version
diamond version 2.0.8
(py3-funannotate) jon@Jons-MacBook-Pro:~/funannotate_dev$ diamond dbinfo -d $FUNANNOTATE_DB/repeats.dmnd
diamond v2.0.8.146 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

          Database type  Diamond database
Database format version  3
          Diamond build  136
              Sequences  11950
                Letters  9920808
(py3-funannotate) jon@Jons-MacBook-Pro:~/funannotate_dev$ python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:33:30) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import funannotate.library as lib
>>> lib.getDiamondVersion()
'2.0.8'
>>> lib.CheckDiamondDB('/usr/local/share/funannotate/repeats.dmnd')
True
```

**Comment by papelypluma** [comment]
Hi @nextgenusfs. Thanks for the help. I tried the commands using the interpreter, and there's a non-zero exit stat for lib.CheckDiamondDB

> lib.CheckDiamondDB('/expt/datboncan/database/funannodate_db/repeats.dmnd')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/datboncan/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 568, in CheckDiamondDB
>     for line in execute(['diamond', 'dbinfo', '-d', database]):
>   File "/home/datboncan/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 553, in execute
>     raise subprocess.CalledProcessError(return_code, cmd)
> subprocess.CalledProcessError: Command '['diamond', 'dbinfo', '-d', '/expt/datboncan/database/funannodate_db/repeats.dmnd']' returned non-zero exit status 1.

**Comment by nextgenusfs** [comment]
Not sure what this could be, the getDiamondVersion() is outputting v2.0.8? Thinking python path is diff than interactive? I don't know what else could be happening.

**Comment by papelypluma** [comment]
Hi @nextgenusfs thanks for your help. It throws an error when I do it outside the database directory, but it doesn't when I do it inside the directory where repeats.dmnd is located.

Yes, it's outputting 2.0.8.

**Comment by papelypluma** [comment]
Hi @nextgenusfs. I've figured out what's happening. It's my fault. There's one diamond in the $PATH, and that's what being run by funannotate. I removed it in the $PATH, and now funannotate predict is running.  Thanks for the help! Really appreciate your help and assistance.

**Comment by nextgenusfs** [comment]
Okay -- so wrong diamond version in your PATH.  closing.
