### ISSUE TITLE
Where could I install BUSCO database?

### ISSUE THREAD

**Issue by goshng** [nextgenusfs/funannotate#637]
Hi,

I have a question:

I'd like to use poales BUSCO database, which is not in the default funannotate_db after installing funannotate. I could see the BUSCO DB using the funannotate database subcommand:

$ funannotate database --show-buscos

But, I could not find the poales BUSCO database.

I want to use the predict subcommand with --busco_db option as following:

$ funannotate predict -i assembly-masked.fasta -o assembly-predict.fasta -s "Carex breviculmis" --busco_db poales

although I am sure whether that use of the busco_db argugment is okay.

I am wondering how I could update the funannotate_db with the poales BUSCO database, which is available at the following website:

https://busco-data.ezlab.org/v5/data/lineages/
https://busco-data.ezlab.org/v5/data/lineages/poales_odb10.2020-08-05.tar.gz

Thank you,

**Comment by hyphaltip** [comment]
you can manually download that file and extract it into your $FUNANNOTATE_DB folder.
But we could add that species group to the download set set to make it possible to install with:
`funannotate setup -b poales`

**Comment by nextgenusfs** [comment]
I started on trying to integrate busco5 and remove our local busco 2/3 copy.  I couldn't get conda to solve as there are too many conflicting dependencies.  Having said that you can use the v5 odb10 models with the current implementation I think.  But try to download and extract into funannotate database folder and then see if that works.

**Comment by goshng** [comment]
Thank you! That worked for me.
