### ISSUE TITLE
Which version of signalp should I use?

### ISSUE THREAD

**Issue by goshng** [nextgenusfs/funannotate#639]
Hi,

My question is which version of signalp should I use for running funannotate? There are signal5 and signal4 in conda.

I almost installed funannotate v1.8.9 in Linux and have used it with "predict" but not "annotate" subcommand. The problem was about signalP. 

The version I used with was:
$ conda install -c predector signalp6

This worked for me with "predict" subcommand but not "annotate" subcommand. So, as recommended in the running of signalp6 command,

I downloaded signalp6 from https://services.healthtech.dtu.dk/software.php and have done:
$ signalp6-register signalp-6.0.fast.tar.gz

Then, 
$ funannotate check --show-versions
raised a problem like this:

Checking external dependencies...
	ERROR: signalp found but error running signalp
PASA: 2.4.1
...
trimmomatic: 0.39
	ERROR: signalp not installed

I tried to reinstall signalp6 using the conda command as above. That did not work. 

The "annotate" subcommand fails somewhere in "funannotate/library.py"

def signalP(input, tmpdir, output):
    # split input file into chunks, 20 should mean < 200 proteins per chunk
    from funannotate.check import check_version7
    version = check_version7('signalp')
    if '.' in version:
        version = int(version.split('.')[0])

Anyway, my question is which version of signalp should I use for running funannotate? There are signal5 and signal4 in conda.

Thank you!

**Comment by goshng** [comment]
signalp5 version seems to work with funannotate v1.8.9.

**Comment by nextgenusfs** [comment]
I do not think signalP is available via conda as has a fairly strict license. Either v4 or v5 should work. I didn't know v6 was out. I do not have access as not academia affiliated anymore. It is optional because of the licensing it can't be used by all users.

**Comment by goshng** [comment]
Thank you very much for the answer.
