### ISSUE TITLE
What is the reason of having T1 at the end on protein names?

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#64]
What is the reason of having T1 at the end on protein names? Thank you.
`GN01_00116-T1`

**Comment by nextgenusfs** [comment]
Differentiate a transcript from a gene. T1 would be the first transcript from a gene and T2 would be second. It usually doesn't apply for fungi as we typically don't have multiple transcripts arising from the same gene although it does happen, but also this is to satisfy the naming conventions for NCBI submission.
