### ISSUE TITLE
Are "required options" actually required?

### ISSUE THREAD

**Issue by goshng** [nextgenusfs/funannotate#641]
Hi,

I followed the tutorial available at

https://funannotate.readthedocs.io/en/latest/tutorials.html

to learn how to use it to annotate a plant genome of size being about 250 Mb. It seems to nicely be working. I am surprised how genome annotations are that easy. Anyway, thanks. One problem is that some of the required options do not seem to be required. For example, the following is the header part of annotate help message.

```
$ funannotate annotate

Usage:       funannotate annotate <arguments>
version:     1.8.9

Description: Script functionally annotates the results from funannotate predict.  It pulls
             annotation from PFAM, InterPro, EggNog, UniProtKB, MEROPS, CAZyme, and GO ontology.

Required:
  -i, --input        Folder from funannotate predict
    or
  --genbank          Genome in GenBank format
  -o, --out          Output folder for results
    or
  --gff              Genome GFF3 annotation file
  --fasta            Genome in multi-fasta format
  -s, --species      Species name, use quotes for binomial, e.g. "Aspergillus fumigatus"
  -o, --out          Output folder for results

Optional:
  --sbt              NCBI submission template file. (Recommended)
```

But, in the tutorial above, I find:

"Finally you can run the funannotate annotate script incorporating the data you generated. Passing the funannotate folder will automatically incorporate the interproscan, antismash, phobius results."

`funannotate annotate -i fun --cpus 12`

So, are those "required options" not actually required?

Additionally, I am wondering if the `funannotate test` could be turned into a kind of tutorial by explaining each test runs (or  in the help message: -t, --tests    Test sets to run. [all,clean,mask,predict,busco,rna-seq,annotate,compare]).

Anyway, it would have been several months of work without Funannotate. Thanks!

**Comment by hyphaltip** [comment]
I'm not sure of the question here or what you would like changed.

You need to provide one of, which you did:
```
  -i, --input        Folder from funannotate predict
    or
  --genbank          Genome in GenBank format
  -o, --out          Output folder for results
    or
  --gff              Genome GFF3 annotation file
```
which you did. 

It is correct that species, if not provided, does not trigger an error but then it uses a default species name which is likely wrong for your project so it seems like you. perhaps better warning rather than listing it as required would satisfy the request you are making?

**Comment by goshng** [comment]
I have realized that the required option consists of three with two "or." That makes sense, now.
