### ISSUE TITLE
BUSCO v5.2.2 incorporation?

### ISSUE THREAD

**Issue by Dikaryotic** [nextgenusfs/funannotate#648]
Hiya, 

Just wondering if there are any plans to use the newer version of BUSCO? The gene prediction step is way quicker and it uses a newer set of databases. Or is there a way to maybe incorporate the outcome from a separate BUSCO run into the main funannotate predict step? 

I've wondered a few times and I once again find myself doing a prediction for a weird fungus and wishing I could use the newer version of BUSCO for it. It's a Dothideomycete fungus this time! 

Cheers!

**Comment by nextgenusfs** [comment]
I have a local branch where I was going to make the switch... however I can't get the conda environment to solve due to conflicting dependencies. You can use the newer odb10 models they work the same just download them and put into the funannotate db folder.

**Comment by Dikaryotic** [comment]
That worked like a dream, thanks man!
