### ISSUE TITLE
How can I create lineage folder?

### ISSUE THREAD

**Issue by wangzhennan14** [nextgenusfs/funannotate#65]
HI,
   When I run the Busco, I have download the odb9v1_metazoa_fasta.tar.gz. Then I have unzip the tarball. and when I run the commind line : python BUSCO.py --in data/limit-sample.fa --o test --lineage data/metazoa --mode tran -c 7 -f, there is an error, 
  Command line argument error: Argument "query". File is not accessible:  `data/metazoa/ancestral'

How can I create a lineage folder? Can you help me? Thank you very much!

**Comment by nextgenusfs** [comment]
this sounds like a BUSCO question and not a funannotate question, BUSCO repository is https://gitlab.com/ezlab/busco
