### ISSUE TITLE
Funannotate issue

### ISSUE THREAD

**Issue by nam183** [nextgenusfs/funannotate#66]
I am getting following warning while running my one of trial run in funannotate
"Note, you should fix any tbl2asn errors now before running functional annotation"
but it completed the process and i got output files.

But when i am trying to run funannotate with my actual genome scaffolds it is getting stuck 'Converting to Preliminary Genbank format' step and not generating any output genbank file.
So how can i complete this process.

Thank You

**Comment by nextgenusfs** [comment]
The warning is normal, just telling you that there are probably still some errors in a few gene models. What does the log file look like, any clues in there?

**Comment by nam183** [comment]
There are line saying 'evm.TU.giraau_101.39 was removed in removeBadModels function for unknown reason, please check manually'

And then these are the last lines of log file and it is at tbl2asn step from last 9 days.


2017-04-09 20:40:40,917: 235,783 gene models remaining
2017-04-09 20:40:40,917: Converting to preliminary Genbank format
2017-04-09 20:40:40,918: gag.py -f /data/shared_folder/annotation2017/gir_6Apr/predict_misc/genome.softmasked.fa -g gir_6Apr/predict_misc/cleaned.gff3 -o gir_6Apr/predict_misc/gag2 --fix_start_stop
2017-04-09 22:05:22,403: Reading fasta...
Done.
Reading gff...
Done.
Calculating stats on original genome
Creating start and stop codons...
Calculating stats on modified genome
Writing stats file to gir_6Apr/predict_misc/gag2/ ...
Writing gff, tbl and fasta to gir_6Apr/predict_misc/gag2/ ...

2017-04-09 22:05:26,077: tbl2asn -p gir_6Apr/predict_misc/gag2 -t /home/orf/.linuxbrew/Cellar/funannotate/0.5.4/libexec/lib/test.sbt -M n -Z discrepency.report.txt -a r10u -l paired-ends -j [organism=Bos indicus] -V b -c fx



So, i couldn't find any other clues.
Please help me understand this and is this normal??
Thank You

**Comment by nextgenusfs** [comment]
Can you try to run the tbl2asn command manually and see what happens, i.e. the last command there in your log file.  The error message may not be being captured correctly by the logger.

**Comment by nam183** [comment]
i tried to run the last command but it didn't do anything, i gave command and it was over in a second and no log or output file generated.

**Comment by nextgenusfs** [comment]
Okay, so I need some more info in order to try to help.  What version of tbl2asn?  What files are in the `gir_6Apr/predict_misc/gag2` directory?  Can you run `ls -l gir_6Apr/predict_misc/gag2`.

**Comment by nam183** [comment]
ok so here are the list of files in gag2 folder.

total 8885056
-rw-rw-r-- 1 orf orf        485 Apr  9 23:05 errorsummary.val
-rw-rw-r-- 1 orf orf         16 Apr  9 22:04 genome.comments.gff
-rw-rw-r-- 1 orf orf 2979127635 Apr  9 22:05 genome.fasta
-rw-rw-r-- 1 orf orf 2979127635 Apr  9 22:05 genome.fsa
-rw-rw-r-- 1 orf orf 2827308241 Apr  9 22:59 genome.gbf
-rw-rw-r-- 1 orf orf  101536949 Apr  9 22:05 genome.gff
-rw-rw-r-- 1 orf orf          0 Apr  9 22:04 genome.ignored.gff
-rw-rw-r-- 1 orf orf          0 Apr  9 22:04 genome.invalid.gff
-rw-rw-r-- 1 orf orf   10336975 Apr  9 22:05 genome.proteins.fasta
-rw-rw-r-- 1 orf orf          0 Apr  9 22:04 genome.removed.gff
-rw-rw-r-- 1 orf orf    1193691 Apr 19 15:01 genome.sqn
-rw-rw-r-- 1 orf orf       2925 Apr  9 22:05 genome.stats
-rw-rw-r-- 1 orf orf   62389346 Apr  9 22:05 genome.tbl
-rw-rw-r-- 1 orf orf  128320093 Apr  9 23:03 genome.val

**Comment by nextgenusfs** [comment]
Okay, since it seems that GAG has run correctly, it seems like a tbl2asn error.  When you run tbl2asn from the command line it should look like this, note the quotes are important
```
tbl2asn -p gir_6Apr/predict_misc/gag2 \
      -t /home/orf/.linuxbrew/Cellar/funannotate/0.5.4/libexec/lib/test.sbt \
     -M n -Z discrepency.report.txt -a r10u -l paired-ends -j "[organism=Bos indicus]" -V b -c fx
```
If that doesn't produce a result, I'm not sure what the problem is.

**Comment by nam183** [comment]
i tried running your command and it started the process but then gave following warning and was closed.

[tbl2asn] Feature table identifiers lcl|giraau_200305 do not match record
[tbl2asn] Flatfile genome

[tbl2asn] Validating genome

[tbl2asn] Sequence stream cache failure - rerun with files less than 2 GB in size
Hit Return

Warning says to use less than 2 GB file size and i am running trying to annotate a 3 gb genome sized organism.
So, is this error because i am using a larger file?

Thank You

**Comment by nextgenusfs** [comment]
Yes it must be.  Never dealt with a genome that large!  So we need to find some recommendations for dealing with larger genomes through tbl2asn.  We can split it up into pieces run tbl2asn and then combine the files after, which is probably the recommended approach - but lets see if NCBI has some recommendations for this as my goal with funannotate is to do my best to make sure the output is compatible with NCBI genome submission.

**Comment by nextgenusfs** [comment]
hi @nam183, so here is part of the response from NCBI:
```
Please split your fasta file to have 10000 sequences/fasta file, run 
tbl2asn on the directory, and submit the multiple .sqn files through 
the submission portal, 

The following is detailed information on submission of annotated eukaryotic
genomes.

[] Please see the WGS page, https://www.ncbi.nlm.nih.gov/Genbank/wgs.html 
and https://www.ncbi.nlm.nih.gov/genbank/wgs.submit.html, for 
instructions about how to generate a WGS submission. In addition, 
if the submission includes annotation, be sure to read the 
Eukaryotic Genome Guidelines at 
https://www.ncbi.nlm.nih.gov/Genbank/eukaryotic_genome_submission_annotation.html.

[] Note that annotation is not required for WGS submissions.

[] If there are more than 20,000 contigs, then limit each fasta 
file to 10,000 sequences so that the submission files do not get 
too big.
```
So this means that for large genomes such as the one you are working on, I'll have to write a function that splits the data, and runs tbl2asn on the partitions, and then combine them back together.  This will take me little bit.  But I will update this thread when it is working.

**Comment by nextgenusfs** [comment]
How many scaffolds/contigs do you have?

**Comment by nam183** [comment]
I have around 9 lakh scaffolds

**Comment by nextgenusfs** [comment]
Okay, so with that many scaffolds/contigs NCBI would recommend that they be "chunked" into smaller pieces for submission.  What this effectively means is that I'll have to write a function to split the output prior to running `tbl2asn` and then recombine the data so that the rest of funannotate works.

**Comment by nextgenusfs** [comment]
Sorry this took so long, got put on the "back burner".  As of v1.4.1 `tbl2asn` is run in smaller chunks if assembly is > 10000 contigs and/or > 100 MB.
