### ISSUE TITLE
funannotate predict

### ISSUE THREAD

**Issue by mictadlo** [nextgenusfs/funannotate#663]
Hi,
I do not plan to use GeneMark-ET but I want to use Augustus, GlimmerHMM and SNAP. 

1. If I ran `funannotate train` do I still have to use `funannotate predict --rna_bam `? If yes then what is the difference between `train` and `predict`?
2. Is Is possible to use the output from [Mikado](https://academic.oup.com/gigascience/article/7/8/giy093/5057872?login=true) as the `--stringtie` parameter? This tool apparently shows 
> `..that` the accuracy of transcript reconstruction can be boosted by combining multiple methods, and we present a novel algorithm to integrate multiple RNA-seq assemblies into a coherent transcript annotation. Our algorithm can remove redundancies and select the best transcript models according to user-specified metrics while solving common artifacts such as erroneous transcript chimerisms.

Thank you in advance,

Michal

**Comment by hyphaltip** [comment]
For 1. No - predict will find the RNA BAM files automatically if you ran train already.
note that train will also run full PASA to get polished spliced sites and models for SNAP and augustus training which require a set of gene models in gff/gbk.

**Comment by mictadlo** [comment]
Thank you, is Is possible to use the output from [Mikado](https://academic.oup.com/gigascience/article/7/8/giy093/5057872?login=true) as the `--stringtie` parameter? This tool apparently shows 
> `..that` the accuracy of transcript reconstruction can be boosted by combining multiple methods, and we present a novel algorithm to integrate multiple RNA-seq assemblies into a coherent transcript annotation. Our algorithm can remove redundancies and select the best transcript models according to user-specified metrics while solving common artifacts such as erroneous transcript chimerisms.

**Comment by hyphaltip** [comment]
any assembled transcriptome is an option but I think you still need to give left and right reads for it to select genes with minimal expression level for training step.
