### ISSUE TITLE
Evidence modeler has failed, exiting

### ISSUE THREAD

**Issue by Subhajeet1997** [nextgenusfs/funannotate#664]
This is my code for prediction.
funannotate predict -i Phyca_CPV-219.softmasked.fa  --busco_db alveolata_stramenophiles --organism other --species 'Phytophthora capsici CPV-219' -o Phyca_CPV-219-annoatate --cpus 70 --protein_evidence GCA_016618375.1_Pcap_4.1_protein.faa --weights snap:0 glimmerhmm:0 --no-evm-partitions 2>&1 | tee funannotate_error-Phyca_CPV-219.log

I am getting the following error .

-------------------------------------------------------
[Nov 11 10:04 PM]: OS: Ubuntu 18.04, 80 cores, ~ 1055 GB RAM. Python: 3.8.11
[Nov 11 10:04 PM]: Running funannotate v1.8.7
[Nov 11 10:04 PM]: Skipping CodingQuarry as $QUARRY_PATH not found as ENV
[Nov 11 10:04 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco
  genemark     selftraining
  glimmerhmm   busco
  snap         busco
[Nov 11 10:04 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Nov 11 10:05 PM]: Genome loaded: 7,579 scaffolds; 58,885,463 bp; 35.48% repeats masked
[Nov 11 10:05 PM]: Existing protein alignments found: Phyca_CPV-219-annoatate/predict_misc/protein_alignments.gff3
[Nov 11 10:05 PM]: Existing GeneMark annotation found: Phyca_CPV-219-annoatate/predict_misc/genemark.gff
[Nov 11 10:05 PM]: 22,406 predictions from GeneMark
[Nov 11 10:05 PM]: Existing BUSCO results found: Phyca_CPV-219-annoatate/predict_misc/busco.final.gff3 containing 218 predictions
[Nov 11 10:05 PM]: Existing Augustus annotations found: Phyca_CPV-219-annoatate/predict_misc/augustus.gff3
[Nov 11 10:05 PM]: Pulling out high quality Augustus predictions
[Nov 11 10:05 PM]: Found 3,214 high quality predictions from Augustus (>90% exon evidence)
[Nov 11 10:05 PM]: Skipping snap prediction as weight set to 0
[Nov 11 10:05 PM]: Skipping GlimmerHMM prediction as weight set to 0
[Nov 11 10:05 PM]: Summary of gene models passed to EVM (weights):
[Nov 11 10:05 PM]: EVM: partitioning each contig separately
Traceback (most recent call last):
  File "/home/sutripa/.local/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 478, in <module>
    cmdinfo = create_partitions(args.fasta, args.genes, partitions,
  File "/home/sutripa/.local/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 134, in create_partitions
    interGenes = gene_blocks_to_interlap(genes)
  File "/home/sutripa/.local/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 25, in gene_blocks_to_interlap
    cols = gene_model[1].split('\t')
IndexError: list index out of range
  Source         Weight   Count
  Augustus       1        7116
  Augustus HiQ   2        3214
  GeneMark       1        22406
  Total          -        32736
[Nov 11 10:05 PM]: Evidence modeler has failed, exiting
Traceback (most recent call last):
  File "/home/sutripa/.local/bin/funannotate", line 11, in <module>
    sys.exit(main())
  File "/home/sutripa/.local/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/sutripa/.local/lib/python3.8/site-packages/funannotate/predict.py", line 1791, in main
    os.remove(EVM_out)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sutripa/oomycetes_paper_work/Phytophthora_new_annotation/test/Phyca_CPV-219-annoatate/predict_misc/evm.round1.gff3'

I don't know what is happening. Previously  I ran several times successfully but this time I added the --weights and it is showing the error

**Comment by nextgenusfs** [comment]
It is a rare bug in the partitioning code on only some assemblies. It was fixed in v1.8.9, so upgrade funannotate to latest and should be fixed.

**Comment by Subhajeet1997** [comment]
> It is a rare bug in the partitioning code on only some assemblies. It was fixed in v1.8.9, so upgrade funannotate to latest and should be fixed.

How do I update the version? Do I need to reinstall everything from scratch ?

**Comment by nextgenusfs** [comment]
From the environment you have funannotate installed just run:
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git --upgrade --force --no-deps
```

**Comment by liberjul** [comment]
I had this same issue, while using v1.8.9. It looks like the `gene_predictions.gff3` ended with an empty line (`\n`), which caused `cols = gene_model[1].split('\t')` in `gene_blocks_to_interlap()` to fail. I modified the function to check if the line is greater than 1 character in length and the problem was fixed. I can put a pull request in if that would be helpful.
