### ISSUE TITLE
funannotate 

### ISSUE THREAD

**Issue by erenakae** [nextgenusfs/funannotate#668]
Hi there,
I am trying to annotate proteins with funannotate v1.8.5. I run interproscan independently, and Antismash also worked well. However, annotate failed to integrate results. Any help, please.

 funannotate annotate -i pre_trained_predict8 --iprscan primary_ctg_funout.xml --cpus 12 
[Nov 16 09:39 PM]: OS: CentOS Linux 7, 128 cores, ~ 264 GB RAM. Python: 3.7.10
[Nov 16 09:39 PM]: Running 1.8.5
[Nov 16 09:39 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Nov 16 09:39 PM]: Found existing output directory pre_trained_predict8. Warning, will re-use any intermediate files found.
[Nov 16 09:39 PM]: Parsing input files
[Nov 16 09:39 PM]: Existing tbl found: pre_trained_predict8/predict_results/Puccinia_graminis_f.sp._tritici.tbl
[Nov 16 09:40 PM]: Adding Functional Annotation to Puccinia graminis f. sp. tritici, NCBI accession: None
[Nov 16 09:40 PM]: Annotation consists of: 14,267 gene models
[Nov 16 09:40 PM]: 13,471 protein records loaded
[Nov 16 09:40 PM]: Existing Pfam-A results found: pre_trained_predict8/annotate_misc/annotations.pfam.txt
[Nov 16 09:40 PM]: 10,892 annotations added
[Nov 16 09:40 PM]: Running Diamond blastp search of UniProt DB version 2020_05
[Nov 16 09:40 PM]: 362 valid gene/product annotations from 956 total
[Nov 16 09:40 PM]: Existing Eggnog-mapper results found: pre_trained_predict8/annotate_misc/eggnog.emapper.annotations
[Nov 16 09:40 PM]: Parsing EggNog Annotations
Traceback (most recent call last):
  File "/panfs/roc/msisoft/funannotate/1.8.5/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/panfs/roc/msisoft/funannotate/1.8.5/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/panfs/roc/msisoft/funannotate/1.8.5/lib/python3.7/site-packages/funannotate/annotate.py", line 749, in main
    EggNog = parseEggNoggMapper(eggnog_result, eggnog_out, GeneProducts)
  File "/panfs/roc/msisoft/funannotate/1.8.5/lib/python3.7/site-packages/funannotate/annotate.py", line 241, in parseEggNoggMapper
    NOG, DB = cols[OGi].split('@')
ValueError: too many values to unpack (expected 2)

**Comment by nextgenusfs** [comment]
Most likely incompatible eggnog version with funannotate v1.8.5. You can upgrade funannotate to the latest master with pip and see if that fixes the issue.

**Comment by hyphaltip** [comment]
agree eggnog version update likey no matching with that version of funannotate. do check the version of eggonog.

@nextgenusfs maybe we can pen a short table of the compability of eggnog versions and funannotate versions if we can recall?

**Comment by erenakae** [comment]
Thank you all for your suggestions. eggnog-mapper version is 2.1.1-1 in this case.

**Comment by erenakae** [comment]
With funannotate version 1.8.9, the problem still not fixed.
funannotate annotate -i pre_trained_predict8 --iprscan pre_trained_predict8/primary_ctg_funout.xml --eggnog pre_trained_predict8/EggNogmapper_out.emapper.annotations --cpus 12
-------------------------------------------------------
[Nov 17 11:40 PM]: OS: CentOS Linux 7, 32 cores, ~ 132 GB RAM. Python: 3.8.12
[Nov 17 11:40 PM]: Running 1.8.9
[Nov 17 11:40 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Nov 17 11:40 PM]: Found existing output directory pre_trained_predict8. Warning, will re-use any intermediate files found.
[Nov 17 11:40 PM]: Parsing input files
[Nov 17 11:40 PM]: Existing tbl found: pre_trained_predict8/predict_results/Puccinia_graminis_f.sp._tritici.tbl
[Nov 17 11:40 PM]: Adding Functional Annotation to Puccinia graminis f. sp. tritici, NCBI accession: None
[Nov 17 11:40 PM]: Annotation consists of: 14,267 gene models
[Nov 17 11:40 PM]: 13,471 protein records loaded
[Nov 17 11:40 PM]: Existing Pfam-A results found: pre_trained_predict8/annotate_misc/annotations.pfam.txt
[Nov 17 11:40 PM]: 10,892 annotations added
[Nov 17 11:40 PM]: Running Diamond blastp search of UniProt DB version 2021_04
[Nov 17 11:40 PM]: 362 valid gene/product annotations from 956 total
[Nov 17 11:40 PM]: Existing Eggnog-mapper results found: pre_trained_predict8/annotate_misc/eggnog.emapper.annotations
[Nov 17 11:40 PM]: Parsing EggNog Annotations
[Nov 17 11:40 PM]: EggNog version parsed as 2.1.1-1
Traceback (most recent call last):
  File "/home/rousem/edaex001/.conda/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/rousem/edaex001/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/rousem/edaex001/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 792, in main
    EggNog = parseEggNoggMapper(eggnog_result, eggnog_out, GeneProducts)
  File "/home/rousem/edaex001/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 268, in parseEggNoggMapper
    OGs = cols[DBi].split(',')
TypeError: list indices must be integers or slices, not NoneType

**Comment by erenakae** [comment]
Version 1.81. worked for "funannotate annotate".
