### ISSUE TITLE
--busco_db seems not to work properly

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#67]
I've used `--busco_db pezizomycotina` for both `funannotate predict` and `funannotate annotate`, but
in `/annotate_misc/run_busco/short_summary_busco.txt ` there is still default dikarya db reported 

```
BUSCO version is: 2.0 
The lineage dataset is: dikarya_odb9 (Creation date: 2016-02-13, number of species: 75, number of BUSCOs: 1312)
To reproduce this run: python /home/osboxes/.linuxbrew/Cellar/funannotate/0.6.0/libexec/util/funannotate-BUSCO2.py -i /home/osboxes/data/fun_out_v04/annotate_misc/genome.proteins.fasta -o busco -l /home/osboxes/.linuxbrew/Cellar/funannotate/0.6.0/libexec/DB/dikarya/ -m proteins -c 2 -sp aspergillus_nidulans
```

also in the  funannotate-functional.log the number of proteins used corresponds to dikarya (~1300) not to pezizomycotina set (~3000)!

```
2017-04-21 16:53:17,362: Annotating proteins with BUSCO pezizomycotina models
2017-04-21 16:53:17,363: 1,252 annotations added
```
 do you need some other log/data files?

PS  Pezizomycotina DB is on place, and I remember that for 0.5.X versions I specified it as `pezizomycotina_odb9` which seems to be changed in 0.6.X. The only run the default was used is training set for Augustus ages ago

**Comment by nextgenusfs** [comment]
Okay, will take a look today. Maybe it is an error in the BUSCO2 code...

**Comment by nextgenusfs** [comment]
Well I'm not seeing this same behavior unfortunately.  Here's what I ran with sample data:
```
funannotate annotate -i genome2 -e email.com --busco_db pezizomycotina --cpus 6
[08:34:49 AM]: OS: MacOSX 10.12.4, 8 cores, ~ 17 GB RAM. Python: 2.7.12
[08:34:49 AM]: Running funannotate v0.6.0
[08:34:49 AM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[08:34:49 AM]: Downloading pezizomycotina busco models
[08:35:26 AM]: Parsing input files
[08:35:27 AM]: 297 protein records loaded
...
```
Then the log file says the following in `annotate_misc/run_busco/short_summary_busco.txt`:
```
# BUSCO version is: 2.0 
# The lineage dataset is: pezizomycotina_odb9 (Creation date: 2016-02-13, number of species: 50, number of BUSCOs: 3156)
# To reproduce this run: python /Users/jon/funannotate/util/funannotate-BUSCO2.py -i /Users/jon/funannotate/sample_data/genome2/annotate_misc/genome.proteins.fasta -o busco -l /Users/jon/funannotate/DB/pezizomycotina/ -m proteins -c 6 -sp aspergillus_nidulans
#
# Summarized benchmarking in BUSCO notation for file /Users/jon/funannotate/sample_data/genome2/annotate_misc/genome.proteins.fasta
# BUSCO was run in mode: proteins

	C:2.8%[S:2.8%,D:0.0%],F:0.1%,M:97.1%,n:3156

	88	Complete BUSCOs (C)
	88	Complete and single-copy BUSCOs (S)
	0	Complete and duplicated BUSCOs (D)
	4	Fragmented BUSCOs (F)
	3064	Missing BUSCOs (M)
	3156	Total BUSCO groups searched
```

**Comment by MichaelFokinNZ** [comment]
Ok, will check with sample data tomorrow.

2017-04-22 1:51 GMT+12:00 Jon Palmer <notifications@github.com>:

**Comment by MichaelFokinNZ** [comment]
yep, works correctly for sample data. will delete busco results and re-run the on actual data. should it be the same DB for predict and annotate steps? am I right that how Augustus was trained doesn't affect the busco DB usage?
