### ISSUE TITLE
funannotate annotate doesn't collect SignalP output, if Phobius result is empty

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#68]
Is it correct behaviour?
PS. the Phobius doesn't work if no e-mail provided.

**Comment by nextgenusfs** [comment]
You can install phobius locally and it will run that instead of running remote, `phobius.pl` just needs to be in the $PATH.  If both SignalP and Phobius installed, then only proteins where secretion signal was detected with both programs are annotated.

**Comment by MichaelFokinNZ** [comment]
Thank you, now it is clear why the overlap is zero, without Phobius run.
