### ISSUE TITLE
funannotate predict ERROR: %s is not a properly formatted PASA GFF file

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#698]
Hi,

11 days ago (being up to date with the latest github version) I run across an error integrating PASA GFF files produced by funannotate train.
The issue comes from the EvidenceModeler script checking the PASA gff file format.
I did run it independently to troubleshoot things. When run in my otherwise correct file It returns nothing. I mean, checking stderr and stdout both were NULL. Wrongly formated file do return an error. I checked further and decided to fork funannotate and comment out lines 612-615 of predict.py (see https://github.com/ferninfm/funannotate/commit/7aa68352b873f7a7837b9f540569c46be0d7f68e)
```
# validate it will work with EVM
#if not lib.evmGFFvalidate(PASA_GFF, EVM, lib.log):
#    lib.log.error(
#        "ERROR: %s is not a properly formatted PASA GFF file, please consult EvidenceModeler docs" % args.pasa_gff)
#    sys.exit(1)
```
It is a chaperone, not a solution, which is why I did not report it. The prediction followed flawlessly because the gff file was correct.
All the best

Fernando

**Comment by nextgenusfs** [comment]
Interesting, I've never seen this before.  My first guess at discrepancy would be that perhaps EVM is missing some perl dependency?  It should work no different inside funannotate as it does outside of funannotate.

**Comment by ferninfm** [comment]
Thanks, I have to thoroughly check perl dependencies for EVM
