### ISSUE TITLE
Ubuntu installation: brew install funannotate fails with certificate problem

### ISSUE THREAD

**Issue by f-heeger** [nextgenusfs/funannotate#7]
I am following the Ubuntu installation manual.
`brew install funannotate` shows several errors like this one:

> ==> Downloading https://linuxbrew.bintray.com/bottles/cmake-3.5.2.x86_64_linux.b
>
>curl: (77) error setting certificate verify locations:
>  CAfile: /home/linuxbrew/.linuxbrew/etc/openssl/cert.pem
>  CApath: none
> Error: Failed to download resource "cmake"

The CAfile path is wrong. The home folder is not /home/linuxbrew. No idea why this is happening only for certain parts. Anyway there is a work around for this:
Setting the environment variable `CURL_CA_BUNDLE` like so (for bash):
`export CURL_CA_BUNDLE=/home/heeger/.linuxbrew/etc/openssl/cert.pem`

**Comment by nextgenusfs** [comment]
Hmm.  I've not seen this one.  How about running `brew doctor`, `brew update`, and the try again.  The default location for LinuxBrew is in `$HOME/.linuxbrew` or `/home/username/.linuxbrew`.

**Comment by f-heeger** [comment]
I am pretty sure I ran `brew doctor`. I cant test because the installation is running (with the mentioned work around) at the moment. By the way: I am pretty happy I don't have to do all that manually. Thanks for the well documented installation process.

I will test tomorrow and report back.

**Comment by nextgenusfs** [comment]
Great.  Thanks.  Yeah, homebrew/linuxbrew was the only way I could get this number of tools to install somewhat automatically.  With of course the caveat of on any particular system there are bound to be problems....
