### ISSUE TITLE
BUSCO augustus compilation error

### ISSUE THREAD

**Issue by Rodolfo47** [nextgenusfs/funannotate#728]
Hi developer of funannotate, what a great pipeline!
Recently I get access to a new server and I've instaled funannotate with mamba
I'm trying to do some predictions with --protein_evidence buy I get this error

```
[Jun 04 11:11 PM]: OS: Ubuntu 20.04, 64 cores, ~ 264 GB RAM. Python: 3.8.12
[Jun 04 11:11 PM]: Running funannotate v1.8.9
[Jun 04 11:11 PM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Jun 04 11:11 PM]: Skipping CodingQuarry as no --rna_bam passed
[Jun 04 11:11 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
augustus: ERROR
	PP::Profile: Error parsing pattern file"/home/rangeles/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/EOG092C0B3U.prfl", line 8.
[Jun 04 11:11 PM]: ERROR: augustus --proteinprofile test failed, likely a compilation error. This is required to run BUSCO, exiting.
```
I have seen a very similar [issue](https://github.com/nextgenusfs/funannotate/issues/520) but for iOS
I also have AUGUSTUS (3.3.3) running in the server
I instaled augustus like this
````
sudo apt install augustus augustus-data augustus-doc
```

Do you know what could be happen?

**Comment by Rodolfo47** [comment]
this is my line
````
funannotate predict -i ../out/O.polymorpha_NCYC495.clean.sort.mask.fna -o ../out/O.polymorpha_NCYC495 -s O.polymorpha_NCYC495 --isolate XXX --name O.polymorpha_NCYC495 --ploidy 1 --protein_evidence ../data/Protein_models.faa --cpus 50
````

**Comment by nextgenusfs** [comment]
Perhaps you didn't remove Augustus installed by conda (which is the problem)?

**Comment by Rodolfo47** [comment]
you're right, I didn't remove the augustus package of the conda funannotate env.
I've done it now like thise:
```
conda remove augustus -n funannotate --force
````
I use `--force` cause if not, conda remove several packages and funannotate do not detect Evidence Modeler.

´´´
#predicting line
funannotate predict -i ../out/O.polymorpha_NCYC495.clean.sort.mask.fna -o ../out/O.polymorpha_NCYC495 -s O.polymorpha_NCYC495 --isolate XXX --name O.polymorpha_NCYC495 --ploidy 1 --protein_evidence ../data/Protein_models.faa --cpus 4
´´´
Notwithstanding, I got these new errors:
````
-------------------------------------------------------
[Jun 05 11:16 AM]: OS: Ubuntu 20.04, 64 cores, ~ 264 GB RAM. Python: 3.8.12
[Jun 05 11:16 AM]: Running funannotate v1.8.9
[Jun 05 11:16 AM]: $AUGUSTUS_CONFIG_PATH environmental variable not found, Augustus is not properly configured. You can use the --AUGUSTUS_CONFIG_PATH argument to specify a path at runtime.

````

So I set the path to the augustus installed in my system like these:
````
funannotate predict -i ../out/O.polymorpha_NCYC495.clean.sort.mask.fna -o ../out/O.polymorpha_NCYC495 -s O.polymorpha_NCYC495 --isolate XXX --name O.polymorpha_NCYC495 --ploidy 1 --protein_evidence ../data/Protein_models.faa --cpus 4 --AUGUSTUS_CONFIG_PATH /usr/bin/augustus
````
getting this output
````

-------------------------------------------------------
[Jun 05 11:26 AM]: OS: Ubuntu 20.04, 64 cores, ~ 264 GB RAM. Python: 3.8.12
[Jun 05 11:26 AM]: Running funannotate v1.8.9
[Jun 05 11:26 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
Traceback (most recent call last):
  File "/home/rangeles/.conda/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/rangeles/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/rangeles/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/predict.py", line 260, in main
    JOINHINTS = os.path.join(AUGUSTUS_BASE, 'scripts', 'join_mult_hints.pl')
UnboundLocalError: local variable 'AUGUSTUS_BASE' referenced before assignment

````
I don't have GeneMark license and this is not the issue.
But what about augustus?
what am I doing wrong?

**Comment by nextgenusfs** [comment]
Augustus config path is not where the executable is I don't think. I think apt-get installs it in /usr/share/ -- check out the dockerfile for what I set for than ENV.

**Comment by nextgenusfs** [comment]
export AUGUSTUS_CONFIG_PATH="/usr/share/augustus/config"

**Comment by Rodolfo47** [comment]
Yea, once I set the config path funannotate predict is running !!!
Thank you so much
Your pipeline is my favorite.
In fact, we are going to test its use in a small fungal genomics workshop here in Mexico, that is why we moved to another server.
Thanks again, I hope I'm not bothering you too much.
I think he can already close this issue

**Comment by hyphaltip** [comment]
so glad you got it working - let us know how the workshop goes. I am hoping can spend some time this year developing some more training materials for use in my lab to share.

**Comment by charlesfeigin** [comment]
I'm having the same issue, but even when I set the new AUGUSTUS_CONFIG_PATH, funannotate is still trying to use the previous version of augustus. Do you know what I have to modify to get it to actually use the AUGUSTUS_CONFIG_PATH environment variable?

**Comment by hyphaltip** [comment]
Are you setting / exporting the variable AFTER any conda activate steps?

Jason Stajich, PhD
***@***.***
