### ISSUE TITLE
Error in update stage

### ISSUE THREAD

**Issue by VDaric** [nextgenusfs/funannotate#730]
I'am using the very last docker image. I also have tried mamba installed funannotate version ans I have the same error.

```
$ docker pull nextgenusfs/funannotate
Using default tag: latest
latest: Pulling from nextgenusfs/funannotate
Digest: sha256:0632c1002addf7fb3a5590f0c2a9a6b08a9f381aa71bc2e162f890b58ffec58d
Status: Image is up to date for nextgenusfs/funannotate:latest
docker.io/nextgenusfs/funannotate:latest
```
I am having the following traceback error at update stage  :

```
[Jun 08 02:28 PM]: Parsing GenBank files...comparing annotation                                                                                                                        
Traceback (most recent call last):                                                                                                                                                     
  File "/venv/bin/funannotate", line 8, in <module>                                                                                                                                    
    sys.exit(main())                                                                                                                                                                   
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 711, in main                                                                                               
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/update.py", line 2438, in main
    compareAnnotations2(GBK, final_gbk, Changes, args=args)
  File "/venv/lib/python3.8/site-packages/funannotate/update.py", line 1446, in compareAnnotations2
    UTRs = findUTRs(
  File "/venv/lib/python3.8/site-packages/funannotate/update.py", line 1500, in findUTRs
    refInterlap = InterLap(mrna[i])
IndexError: list index out of range
```
The command :
```
./funannotate-docker update -i out/Am-T4-HMW1/fun --cpus 16 --species "Ascidia mentula" --max_intronlen 8000 --memory 364G
```

**Logfiles**
[funannotate-update.log](https://github.com/nextgenusfs/funannotate/files/8865308/funannotate-update.log)

Logs looks OK to me.

**OS/Install Information**
[versions.txt](https://github.com/nextgenusfs/funannotate/files/8865310/versions.txt)

Huge thanks.

**Comment by nextgenusfs** [comment]
That's a malformated file than, all CDS must have an exon.

**Comment by VDaric** [comment]
By "gene model" do you mean .tbl file ?

[Ascidia_mentula_Am-T4-HMW1.tbl.tar.gz](https://github.com/nextgenusfs/funannotate/files/8871878/Ascidia_mentula_Am-T4-HMW1.tbl.tar.gz)

The gbk file is too bog to be uploaded here. But I printed out cds ans mrna variables content when the error occurred.

```
mrna ->

[
[(3269216, 3269920), (3274085, 3274212), (3274453, 3274722), (3275061, 3275257), (3275553, 3276473)], [(3269216, 3269920), (3269991, 3270118), (3270351, 3270620), (3271758, 3271954), (3272144, 3272485)]
]
```

and

```
 cds -> 
[
[(3269718, 3269920), (3274085, 3274212), (3274453, 3274722), (3275061, 3275257),(3275553, 3275789)],
 [(3269718, 3269920), (3269991, 3270118), (3270351, 3270620), (3271758, 3271954), (3272144, 3272308)],
 [(3282590, 3282792), (3282863, 3282990), (3283209, 3283478), (3284250, 3284446), (3284635, 3284799)]
]
```

And her is the screen capture of the relevant portion of the gbk file. I located those 3 CDS and 2 mRNA features in the file (underlined).

[Screenshot_20220609_175100](https://user-images.githubusercontent.com/2806107/172890986-96bc15f5-41c6-4a24-b3da-48fc124958c7.png)

The third underlined CDS is not from the same gene as other two.
If needed I can provide a link to the gbk file.

Thanks ! :+1:

**Comment by nextgenusfs** [comment]
And it looks like must be a bug somewhere as you ran update as recommended. I do not have a lot of free time right now to debug this, so not sure how long it will take me, apologies. You could just skip the comparison of old/new annotations. Did it write the new output files properly in update_results?

**Comment by VDaric** [comment]
Please don't apologise, you are doing a great job !

My gbk file was produced by recommended workstream. I followed the tutorial, step by step.

I have modified _update.py_ module to ignore the exception. As the case occurred only twice in my 288MB gbk file I'll consider that its not a blocking issue.

Here is my modified file :

[update.tar.gz](https://github.com/nextgenusfs/funannotate/files/8877653/update.tar.gz)
.

**Comment by nextgenusfs** [comment]
Hi @VDaric -- I think this might be fixed, would you be able test the latest docker build to see if you still have original error? I realized that what was happening was that this compare the updated annotations function was parsing the "new/updated" annotation from GBK -- this is problematic due to what I mentioned above if there are multiple transcripts.  So now the script will pull GFF3/FASTA files as well and use those preferentially.  I also put a try/except on that UTR function and a check for mRNA feature (ncRNA features don't have cds so they were causing an error here).  If you can validate the latest image is working than I'll tag a bug fix release, I'm long overdue for a release.

**Comment by VDaric** [comment]
No problem ! I'll test it with my data ASAP. 

I'll need few days for that. The error occurs after several hours and I have to recreate and setup a new virtual machine and transfer the data ....

Thanks !

**Comment by VDaric** [comment]
@nextgenusfs : Test done. 
The "update" stage passed with no error ! :)
