### ISSUE TITLE
PASA dies during training step on Funannotate 1.8.9

### ISSUE THREAD

**Issue by alanorth** [nextgenusfs/funannotate#734]
**Are you using the latest release?**
Funannotate 1.8.9 via Singularity.

**Describe the bug**
PASA dies during the training step.

**What command did you issue?**
Running Funannotate via a Singularity container:

```console
WORKDIR=/var/scratch/aorth/funannotate
rnaseq_ont=/path/to/root.fastq
genome=/path/to/evidence.fasta

singularity run \
            --bind "$genome:$genome","$rnaseq_ont:$rnaseq_ont","$WORKDIR:$WORKDIR" \
            /export/apps/funannotate/1.8.9/funannotate.sif \
            funannotate train --input "$genome" \
            --out "$WORKDIR" \
            --nanopore_cdna "$rnaseq_ont" \
            --max_intronlen 10000 \
            --jaccard_clip --species "Sphenotylis stenocarpa" \
            --cpus 15
```

**Logfiles**

```console
...
Will process 33 alignment assemblies...
Killed
Error, cmd: /venv/opt/pasa-2.4.1/scripts/assign_clusters_by_stringent_alignment_overlap.dbi -M /var/scratch/aorth/funannotate/training/pasa/Sphenotylis_stenocarpa_pasa -L 30.0 > pasa_run.log.dir/cluster_reassignment_by_stringent_overlap.out died with ret 35072 No such file or directory at /venv/opt/pasa-2.4.1/PerlLib/Pipeliner.pm line 187.
        Pipeliner::run(Pipeliner=HASH(0x559c7ad10fc8)) called at /venv/opt/pasa-2.4.1/Launch_PASA_pipeline.pl line 1044
```

**OS/Install Information**

<details><summary>output of `funannotate check --show-versions`</summary>

-------------------------------------------------------
Checking dependencies for 1.8.9
-------------------------------------------------------
You are running Python v 3.8.10. Now checking python packages...
biopython: 1.79
goatools: 1.1.6
matplotlib: 3.4.2
natsort: 7.1.1
numpy: 1.21.1
pandas: 1.3.1
psutil: 5.8.0
requests: 2.26.0
scikit-learn: 0.24.2
scipy: 1.5.3
seaborn: 0.11.1
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
   ERROR: Bio::Perl not installed, install with cpanm Bio::Perl

Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/venv/config
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
Traceback (most recent call last):
  File "/venv/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/venv/lib/python3.8/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/venv/lib/python3.8/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/venv/lib/python3.8/site-packages/ete3/__init__.py)
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.8
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.9.1-internal
kallisto: 0.46.1
mafft: v7.487 (2021/Jul/25)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.22-r1101
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.7
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: ete3 not installed
        ERROR: gmes_petap.pl not installed
        ERROR: signalp not installed
</details>

**Comment by nextgenusfs** [comment]
Nearly impossible to troubleshoot... try `funannotate test -t rna-seq --cpus X` to see if install is functional.  If you get no error from the test than it has something to do with your data.

**Comment by alanorth** [comment]
I ran `funannotate test -t rna-seq --cpus X` and it seems to complete successfully, so this is a problem with our data I guess... Perhaps we need to ask on the PASA GitHub. Thanks!

**Comment by hyphaltip** [comment]
have you tried to run PASA with mysql db instead of sqlite? it will run faster - can't tell if you are getting out of memory errors killing the runs?

**Comment by nextgenusfs** [comment]
mysql is not setup on the docker image -- I tried this awhile ago and it wasn't very easy to get working. Not sure exactly if this singularity image is derived from the docker nextgenusfs/funannotate -- but if so than mysql is not an option.
