### ISSUE TITLE
perl dependencies missing from Docker

### ISSUE THREAD

**Issue by DrPintoThe2nd** [nextgenusfs/funannotate#737]
Hi Jon!

**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
Currently working to get Funannotate working as a Singularity on the cluster and the build was missing 2 perl dependencies for GENEMARK. I was able to fix, but required a quick rebuild of the docker image.

**OS/Install Information**
 -  output of `funannotate check --show-versions`
```
Checking dependencies for 1.8.11

To print all dependencies and versions: funannotate check --show-versions

You are running Python v 3.8.13. Now checking python packages...
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
   ERROR: File::Which not installed, install with cpanm File::Which 
   ERROR: YAML not installed, install with cpanm YAML
```

**Fix**
Disclaimer: I have yet to test this in practice, but getting GENEMARK-ES to run locally required these!

Added `perl-yaml perl-file-which` to the mamba install section starting with "
``` 
#Install funannotate deps from bioconda here specifying specific versions to be able to set ENV below
RUN mamba create -c conda-forge -c bioconda -c defaults ...
``` 
and a rebuild from the current Dockerfile

```
Checking dependencies for 1.8.11

To print all dependencies and versions: funannotate check --show-versions

You are running Python v 3.8.13. Now checking python packages...
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
All 27 Perl modules installed
```

Per usual, thank you so much for all your efforts on this software and you continued support is absolutely amazing!!
Please let me know if there's anything I can do to support your efforts!
Best,
Brendan

**Comment by giriarteS** [comment]
I tried the docker version yesterday and it's missing YAML, Hash:Merge, Logger::Simple and Parallel:ForkManager

**Comment by DrPintoThe2nd** [comment]
Quick fix options, you can rebuild the docker in-line the above suggestions or pull my version and hope it's stable(!) (drpintothe2nd/funannotate:v1.8.11), which wasn't missing any perl modules. Good luck!

**Comment by nextgenusfs** [comment]
assuming this builds properly https://github.com/nextgenusfs/funannotate/runs/7045675696?check_suite_focus=true. Than should be able to pull nextgenusfs/funannotate:latest and hopefully that has what you need. Sorry I just don't use genemark anymore due to licensing issues.  And since you have to build a new docker container to use it, I sort of left that up to those users....

**Comment by DrPintoThe2nd** [comment]
Thanks, Jon!!

**Comment by giriarteS** [comment]
I just pulled the docker image and it's not working:
`docker pull nextgenusfs/funannotate
Using default tag: latest
latest: Pulling from nextgenusfs/funannotate
982cba7e471c: Pull complete 
71b65dbdf3e2: Pull complete 
a5ccc8b648b7: Pull complete 
f7f1240bbb86: Pull complete 
Digest: sha256:4d95894d221bb784adadd12c0bc38e998ed527ecac95c5018592219244771c66
Status: Downloaded newer image for nextgenusfs/funannotate:latest
docker.io/nextgenusfs/funannotate:latest`

`ERROR: File::Which not installed, install with cpanm File::Which 
ERROR: YAML not installed, install with cpanm YAML 
ERROR: local::lib not installed, install with cpanm local::lib`

`docker images
REPOSITORY                TAG       IMAGE ID       CREATED      SIZE
nextgenusfs/funannotate   latest    f2b11db45c97   5 days ago   12.1GB`

**Comment by nextgenusfs** [comment]
yep -- if you followed the GitHub action above you'd see the build has failed, so it has not been updated yet. EBI servers appear to have bad connection it is unable to download the necessary databases.

**Comment by nextgenusfs** [comment]
I can't fix the EBI site -- so I'll try to trigger the build again tomorrow.  The nextgenusfs/funannotate-slim image is updated but it does not have any of the databases.

As I've said many times -- docker is great when it works -- but it is a huge pain when it doesn't.  You get much more flexibility if you do not use the docker image.....

**Comment by nextgenusfs** [comment]
It's in the build recipe. Not sure it's needed. If adding genemark you need to change genemark Perl shebang to use the proper env in docker.
