### ISSUE TITLE
how to revise the path to certain dependencies?

### ISSUE THREAD

**Issue by maysonlin** [nextgenusfs/funannotate#738]
Greetings, 
           Here are list of dependencies of funannotate 1.8.9  I have installed by using `funannotate check --show-versions`

```
Checking dependencies for 1.8.9
-------------------------------------------------------
You are running Python v 3.8.12. Now checking python packages...
biopython: 1.77
goatools: 1.2.3
matplotlib: 3.4.3
natsort: 8.1.0
numpy: 1.22.4
pandas: 1.4.2
psutil: 5.9.1
requests: 2.28.0
scikit-learn: 1.1.1
scipy: 1.8.1
seaborn: 0.11.2
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.7.4
Carp: 1.38
Clone: 0.45
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/scratch/mdegenna/slin023/funannotate
$PASAHOME=/home/slin023/.conda/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/home/slin023/.conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/slin023/.conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/slin023/.conda/envs/funannotate/config/
$GENEMARK_PATH=/home/slin023/gmes_linux_64_4/gmhmme3
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.0.15
emapper.py: There was an error retrieving eggnog-mapper DB data: not a valid file "/home/slin023/.conda/envs/funannotate/lib/python3.8/site-packages/data/eggnog.db"
Maybe you need to run download_eggnog_data.py
emapper-2.1.8 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Diamond found: diamond 2.0.15 / MMseqs2 found: 13.45111

ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2021-08-25
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.9.1-internal
kallisto: 0.46.1
mafft: v7.505 (2022/Apr/10)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
proteinortho: 6.1.0
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.12
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 39
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed
```
It points that signalp, gmes_petap.pl and eggnog.db not installed. I have installed those dependencies on different path, but how do I revise the path, so the funannotate 1.8.9 can recognize the dependency? For example, I have eggnog.db install on /scratch/mdegenna/slin023/eggnog and signalp from /home/slin023/signalp-4.1 , how do I revise the path? Any suggestions are welcome. Thank you for your time!

**Comment by hyphaltip** [comment]
usually you add to your path variable eg in your .bashrc or equivalent.

```
export PATH=/home/slin023/signalp-4.1:$PATH
```

Other HPC systems use the [module](https://modules.readthedocs.io/en/stable/INSTALL.html) system to update path so that installed programs are available.

Other ways include linking single executables into a common path eg if `~/bin` was in your `$PATH`, eg after doing this`export PATH=~/bin/:$PATH`  THEN you could have the executable linked into that common folder eg
```
cd ~/bin
ln -s /home/slin023/signalp-4.1/bin/* .
``` 
However this can be less than ideal if the programs also expect to find files in a related `lib` directory that is relative to the executable so it maybe not best way for complex installs.

**Comment by maysonlin** [comment]
Hi, thank you for helping! The only problem for the installation is eggnog.db. It still shows `emapper.py: There was an error retrieving eggnog-mapper DB data: not a valid file "/home/slin023/.conda/envs/funannotate/lib/python3.8/site-packages/data/eggnog.db"
Maybe you need to run download_eggnog_data.py
emapper-2.1.8 / Expected eggNOG DB version: 5.` Here are things I have tried. 
1. I have used `export PATH=/path/to/my/eggnog.db:$PATH`, the error still remains 
2. I have used `download_eggnog_data.py` , it shows `sh: line 0: cd: /home/slin023/.conda/envs/funannotate/lib/python3.8/site-packages/data: Not a directory
Skipping Pfam database (or already present). Use -P and -f to force download
Skipping MMseqs2 database (or already present). Use -M and -f to force download
No HMMER database requested. Use "-H -d taxid" to download the hmmer database for taxid
Finished.` and `/data` is a binary, not a folder. I submitted download script and it's located at /scratch/mdegenna/slin023/eggnog/eggnog.db, but I am not sure how to revise the path since `funannotate check` trying to locate eggnob.db at `/home/slin023/.conda/envs/funannotate/lib/python3.8/site-packages/data` which is a binary, not a folder, I cannot `mkdir data` to overwrite the binary, I am not sure what it is. 

Any suggestion to revise the path to my egg.db folder is welcome. Thank you!

**Comment by nextgenusfs** [comment]
You just need to follow their instructions and set the ENV variable pointing to your database install https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.8#setup

**Comment by maysonlin** [comment]
I have found using `export EGGNOG_DATA_DIR=` does help locate the installed path, thank you!
