### ISSUE TITLE
tRNA scan issue

### ISSUE THREAD

**Issue by el42008** [nextgenusfs/funannotate#74]
Hi Jon, 

EVM finished properly, but now the scripts complains about the tRNA scan. I guess is someting about compilation but I am not sure
```
2017-04-29 06:11:13,499: 126,950 total gene models from EVM
2017-04-29 06:11:13,536: Predicting tRNAs
2017-04-29 06:11:13,539: tRNAscan-SE -o fun_out/predict_misc/tRNAscan.out /mnt/shared/users/el42208/RNA_data/funannotate/fun_out/predict_misc/genome.softmasked.fa
2017-04-29 06:11:13,616: Number found where operator expected at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 647, near ""/mnt/apps/tRNAscan-SE/"1.23"
        (Missing operator before 1.23?)
String found where operator expected at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 647, near "1.23"/lib/""
        (Missing operator before "/lib/"?)
Number found where operator expected at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 649, near ""/mnt/apps/tRNAscan-SE/"1.23"
        (Missing operator before 1.23?)
String found where operator expected at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 649, near "1.23"/bin/""
        (Missing operator before "/bin/"?)
Number found where operator expected at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 1441, near ""/mnt/apps/tRNAscan-SE/"1.23"
        (Missing operator before 1.23?)
String found where operator expected at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 1441, near "1.23"/lib/""
        (Missing operator before "/lib/"?)
Number found where operator expected at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 1442, near ""/mnt/apps/tRNAscan-SE/"1.23"
        (Missing operator before 1.23?)
String found where operator expected at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 1442, near "1.23"/lib/""
        (Missing operator before "/lib/"?)
syntax error at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 647, near ""/mnt/apps/tRNAscan-SE/"1.23"
syntax error at /mnt/apps/tRNAscan-SE/1.23/bin/tRNAscan-SE line 649, near ""/mnt/apps/tRNAscan-SE/"1.23"
```
Thanks a lot

Elena

**Comment by nextgenusfs** [comment]
Yes, looks like tRNAscan is not installed properly.  Funannotate tries to determine if you have dependencies installed, however it currently does not check if they are working.  That is it just checks with essentially a `which` command to see if program is available in $PATH.

**Comment by el42008** [comment]
Hi Jon,

It went further in teh pipeline this time, but now I get the following:

ESC[92m[04:17:43 PM]ESC[0m: OS: linux2, 32 cores, ~ 264 GB RAM. Python:
2.7.13
ESC[92m[04:17:43 PM]ESC[0m: Running funannotate v0.6.0
ESC[92m[04:17:44 PM]ESC[0m: Augustus training set for potato1 already
exists, thus funannotate will use those parameters.
                If you want to re-train, provide a unique name for the
--augustus_species argument
ESC[92m[04:17:45 PM]ESC[0m: AUGUSTUS (3.2.3) detected, version seems to be
compatible with BRAKER1 and BUSCO
ESC[92m[04:18:11 PM]ESC[0m: Masked genome: 224,092 scaffolds; 730,142,347 bp
ESC[92m[04:18:20 PM]ESC[0m: Using existing transcript evidence alignments
ESC[92m[04:18:39 PM]ESC[0m: Using existing protein evidence alignments
ESC[92m[04:18:45 PM]ESC[0m: potato1 as already been trained, using existing
parameters
ESC[92m[04:18:45 PM]ESC[0m: Now launching BRAKER to train GeneMark and
Augustus
ESC[92m[04:19:48 PM]ESC[0m: 225,157 total gene models from all sources
ESC[92m[04:19:54 PM]ESC[0m: Setting up EVM partitions
ESC[92m[07:02:04 PM]ESC[0m: Generating EVM command list
ESC[92m[07:03:07 PM]ESC[0m: Running EVM commands with 23 CPUs
ESC[92m[02:25:36 AM]ESC[0m: Combining partitioned EVM outputs
ESC[92m[02:30:08 AM]ESC[0m: Converting EVM output to GFF3
ESC[92m[08:23:48 AM]ESC[0m: Collecting all EVM results
ESC[92m[08:54:50 AM]ESC[0m: 127,036 total gene models from EVM
ESC[92m[09:58:53 AM]ESC[0m: Predicting tRNAs
ESC[92m[09:58:53 AM]ESC[0m: Merging EVM output with tRNAscan output
ESC[92m[09:58:53 AM]ESC[0m: Reformatting GFF file using GAG
ESC[92m[10:47:45 AM]ESC[0m: 126,826 total gene models
ESC[92m[10:47:45 AM]ESC[0m: Filtering out bad gene models (< 50 aa in
length, transposable elements, etc).
ESC[92m[11:36:25 AM]ESC[0m: 50,977 gene models remaining
ESC[92m[11:36:25 AM]ESC[0m: Converting to preliminary Genbank format
ESC[92m[12:00:16 PM]ESC[0m: Cleaning models flagged by tbl2asn
Traceback (most recent call last):
  File "/mnt/apps/funannotate/bin/funannotate-predict.py", line 1004, in
<module>
    lib.ParseErrorReport(DirtyGFF, ErrSum, Val, discrep, NCBIcleanGFF,
keep_stops=False)
  File "/mnt/apps/funannotate/lib/library.py", line 1287, in
ParseErrorReport
    with open(Errsummary) as summary:
IOError: [Errno 2] No such file or directory:
'fun_out/predict_misc/gag2/errorsummary.val'


Thanks a lot

2017-04-30 20:02 GMT+01:00 Jon Palmer <notifications@github.com>:
