### ISSUE TITLE
Enroot docker image path problems

### ISSUE THREAD

**Issue by sevragorgia** [nextgenusfs/funannotate#741]
Hi,

I am trying to use the funannotate docker image with enroot and keep having problems because the `PATH` seems to be set in a different way than defined in the Dockerfile. Below the output of the cmd `env`:

```
USERXXXX@cpu-007:~$ enroot start funannotate env
SHELL=/bin/bash
ZOE=/usr/share/snap
QUARRY_PATH=/venv/opt/codingquarry-2.0/QuarryFiles
PWD=/
FUNANNOTATE_DB=/opt/databases
LOGNAME=USERXXXX
TRINITYHOME=/venv/opt/trinity-2.8.5
HOME=/home/USERXXXX
TERM=xterm-256color
USER=me
SHLVL=0
PASAHOME=/venv/opt/pasa-2.4.1
EVM_HOME=/venv/opt/evidencemodeler-1.1.1
AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

```
the `PATH` variable doesn't include `/venv/bin`. I am not really familiar with dockerfiles so I cannot really help there further. I am investigating on my side but maybe it is easier for you to fix this. I can of course test using enroot.

thanks in advance,

Sergio

**Comment by nextgenusfs** [comment]
Not sure what "enroot" is.... but that isn't what is in the PATH variable in the docker image. 

```
$ docker run -it nextgenusfs/funannotate:latest /bin/bash
root@25d233c3e32c:/# echo $PATH
/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@25d233c3e32c:/# 
```

**Comment by sevragorgia** [comment]
hmm... will need to check on my side on what is going on. [Enroot](https://github.com/NVIDIA/enroot) is an NVIDIA software to run containers in user space in HPC envs and should work just like docker. But for whatever reason, of all the variables set by `ENV` only the `PATH` is not updated. 

thanks for checking that (I don't have access to docker in our HPC) I will continue investigating and post here what I can find in case someone else has to use enroot.

Sergio

**Comment by sevragorgia** [comment]
Hi again,

I have more info on this.

So, in **our** system enroot automatically mounts my home and overwrites the `PATH`. This has been confirmed by our tech staff. 

The best solution we came up with so far is sourcing `/etc/environment` in the container before running `funannotate`. This will look something like this:

```
enroot start funannotate bash -c 'source /etc/environment; funannotate train -i input.fasta -o out --cpu 20 --left clean_1.fastq.gz -clean_2.fastq.gz --stranded RF --memory 300G --trinity transcriptome.cds --species "whatever" --max_intronlength 15000'

```
This way the extra environmental variable (above) is not required and the user doesn't need to modify `.bashrc` or the `PATH` on the cluster.

cheers

Sergio

P.S. I am closing this issue now as the solution is provided in case someone face the same problem when using enroot with the funannotate docker container. :-)
