### ISSUE TITLE
fix tbl2asn errors before functional annotation

### ISSUE THREAD

**Issue by el42008** [nextgenusfs/funannotate#75]
Hi Jon, 

I have arrive to this point
### 
2017-05-07 03:56:17,387: Funannotate predict is finished, output files are in the fun_out/predict_results folder
2017-05-07 03:56:17,398: Note, you should fix any tbl2asn errors now before running functional annotation.

How can I check if I have to solve any tbl2asn error? and how I fix them?
in /funannotate/fun_out/predict_misc/tbl2asn/errorsummary.val I get this:
260 WARNING: SEQ_FEAT.ShortExon
2224 INFO:    SEQ_FEAT.RareSpliceConsensusDonor

Thank you very much

**Comment by nextgenusfs** [comment]
You can look here to determine which errors in the discrepancy report and validation are required to be fixed to pass NCBI submission. https://www.ncbi.nlm.nih.gov/genbank/asndisc/

See here how to fix them: https://github.com/nextgenusfs/funannotate/wiki/Frequently-asked-Questions#5-funannotate-said-i-should-manually-fix-problematic-gene-models-how
