### ISSUE TITLE
Augustus compilation error when installed from Conda

### ISSUE THREAD

**Issue by Xueliang24** [nextgenusfs/funannotate#755]
**Are you using the latest release?**
I used `mamba create -n funannotate funannotate` to install and use funannotate 1.8.11.

**Describe the bug**
ERROR: augustus --proteinprofile test failed, likely a compilation error. This is required to run BUSCO, exiting.
augustus is installed along with the installation of funannotate

**What command did you issue?**
After I completed the installation，I ran `funannotate test -t all --cpus 10`

**Logfiles**
Running `funannotate clean` unit testing: minimap2 mediated assembly duplications
Downloading: https://osf.io/8pjbe/download?version=1 Bytes: 252076                                                                                                                                                                             CMD: funannotate clean -i test.clean.fa -o test.exhaustive.fa --exhaustive
#########################################################
-----------------------------------------------
6 input contigs, 6 larger than 500 bp, N50 is 427,039 bp
Checking duplication of 6 contigs
-----------------------------------------------
scaffold_73 appears duplicated: 100% identity over 100% of the contig. contig length: 15153
scaffold_91 appears duplicated: 100% identity over 100% of the contig. contig length: 8858
scaffold_27 appears duplicated: 100% identity over 100% of the contig. contig length: 427039
-----------------------------------------------
6 input contigs; 6 larger than 500 bp; 3 duplicated; 3 written to file
#########################################################
SUCCESS: `funannotate clean` test complete.
#########################################################

#########################################################
Running `funannotate mask` unit testing: RepeatModeler --> RepeatMasker
Downloading: https://osf.io/hbryz/download?version=1 Bytes: 375687                                                                                                                                                              CMD: funannotate mask -i test.fa -o test.masked.fa --cpus 10
#########################################################
-------------------------------------------------------
[Aug 01 09:26 AM]: OS: Ubuntu 20.04, 72 cores, ~ 264 GB RAM. Python: 3.8.12
[Aug 01 09:26 AM]: Running funanotate v1.8.11
[Aug 01 09:26 AM]: Soft-masking simple repeats with tantan
[Aug 01 09:26 AM]: Repeat soft-masking finished: 
Masked genome: /home/chenxl/test-mask_4cb9d15e-0441-4475-97d9-9d9b0142c5c1/test.masked.fa
num scaffolds: 2
assembly size: 1,216,048 bp
masked repeats: 50,965 bp (4.19%)
-------------------------------------------------------
#########################################################
SUCCESS: `funannotate mask` test complete.
#########################################################

#########################################################
Running `funannotate predict` unit testing
Downloading: https://osf.io/te2pf/download?version=1 Bytes: 1489808                     CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 10 --species Awesome testicus]]]]]]]]]]]]#########################################################
-------------------------------------------------------
[Aug 01 09:26 AM]: OS: Ubuntu 20.04, 72 cores, ~ 264 GB RAM. Python: 3.8.12
[Aug 01 09:26 AM]: Running funannotate v1.8.11
[Aug 01 09:26 AM]: Skipping CodingQuarry as no --rna_bam passed
[Aug 01 09:26 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pretrained     
  genemark     selftraining   
  glimmerhmm   busco          
  snap         busco          
augustus: ERROR
	PP::Profile: Error parsing pattern file"/pub/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/config/EOG092C0B3U.prfl", line 8.
[Aug 01 09:26 AM]: ERROR: augustus --proteinprofile test failed, likely a compilation error. This is required to run BUSCO, exiting.
#########################################################
Traceback (most recent call last):
  File "/pub/anaconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/pub/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/pub/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 405, in main
    runPredictTest(args)
  File "/pub/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 160, in runPredictTest
    assert 1500 <= countGFFgenes(os.path.join(
  File "/pub/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-predict_4cb9d15e-0441-4475-97d9-9d9b0142c5c1/annotate/predict_results/Awesome_testicus.gff3'

**OS/Install Information**
 -------------------------------------------------------
Checking dependencies for 1.8.11
-------------------------------------------------------
You are running Python v 3.8.12. Now checking python packages...
biopython: 1.77
goatools: 1.2.3
matplotlib: 3.4.3
natsort: 8.1.0
numpy: 1.23.1
pandas: 1.4.3
psutil: 5.9.1
requests: 2.28.1
scikit-learn: 1.1.1
scipy: 1.9.0
seaborn: 0.11.2
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 1.17
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
local::lib: 2.000029
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/pub/anaconda3/envs/funannotate/funannotate_db
$PASAHOME=/pub/anaconda3/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/pub/anaconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/pub/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/pub/anaconda3/envs/maker/config/
$GENEMARK_PATH=/pub/anaconda3/envs/funannotate/bin/gmes_petap
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.4.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.0.15
emapper.py: 2.1.9
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2021-08-25
gmes_petap.pl: 4.69_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 1.8.0_332
kallisto: 0.46.1
mafft: v7.505 (2022/Apr/10)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
pigz: pigz 2.6
proteinortho: 6.1.0
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.12
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 39
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 37 external dependencies are installed

**Comment by Xueliang24** [comment]
When I raised the issue, I have tried to replace the augustus. But the error also happened.

It means the error also happened when the augustus is 3.3.3 when augustus is installed along with the installation of funannotate

**Comment by nextgenusfs** [comment]
I don't know why the conda version of augustus are broken.  Work around is to remove augustus installed via conda and install augustus from elsewhere, ie apt-get or manually compile.

**Comment by Xueliang24** [comment]
I have used the lastest version of singularity. It could be worked successfully.

**Comment by YDD99** [comment]
where i can get the lastest version of singularity？
