### ISSUE TITLE
clarification of option --rename in annotate

### ISSUE THREAD

**Issue by IanDMedeiros** [nextgenusfs/funannotate#762]
I want to make sure I understand what the --rename option does in funannotate annotate. Is this an alternative if you did not provide an NCBI locus tag with --name in funannotate predict, or do you need to use both?

**Comment by nextgenusfs** [comment]
Yes -- if you forgot to change default or perhaps you received the locus tag for submission to NCBI after you ran predict.

**Comment by IanDMedeiros** [comment]
Thanks!
