### ISSUE TITLE
download/setup databases issue

### ISSUE THREAD

**Issue by hanqu24** [nextgenusfs/funannotate#766]
Hello,

I'm using the newest version--**[Funannotate1.8.13]**. 

When I'm trying to follow the instructions for downloading&setup database using the command: 

**funannotate setup -d ./funannotate_db**

The error I got for **Downloading InterProScan Mapping file**:

![image](https://user-images.githubusercontent.com/26860242/185579915-5e5b75a3-a7fe-4bb8-bab8-8069e282c986.png)

Could you please help me with this? Many thanks!!

**Comment by hyphaltip** [comment]
Something changed on their website I just checked in a fix which updates the url. you could install into your conda env this new version with a pip install or you can update the url in the local .json file
https://github.com/nextgenusfs/funannotate/commit/00bf4b4418c55d94445870f6fa6a8562fc600ce8

**Comment by nextgenusfs** [comment]
Actually if you aren't behind a firewall, funannotate should fetch this update automatically from the GitHub repo.  @hanqu24 can you try to run command again?

**Comment by hanqu24** [comment]
Hello!

Thank you for your quick response! I tried to run the command like 5 times, still getting the same error. FYI, I'm using the campus' HPCC cluster, so I assume there isn't a firewall. I also tried to edit the JSON file, ERROR again. Please see below:

![image](https://user-images.githubusercontent.com/26860242/185718643-99f3074a-e983-4b50-b251-63ba2219be78.png)

**Comment by hyphaltip** [comment]
hi if youa re at UCR as it seems - you can just use the already installed funannotate I already fixed the installed version ?
`module load funannotate`

**Comment by hanqu24** [comment]
Oh!! Hi Jason, I didn't realize it was you. Thanks a lot!

**Comment by nextgenusfs** [comment]
Oh @hyphaltip does that need to be https protocol for the ftp from EBI?

**Comment by hyphaltip** [comment]
I see the error is actually for the next URL - the entries - I can fix this in the downloads json but we should probably put some context to the URL fail error message to indicate which URL is not working.

**Comment by hyphaltip** [comment]
@hanqu24 also feel free to test out on your local conda version - and if you need assistance in running the predictions, masking, etc on HPCC just let us know on the cluster slack.

I am going to close this issue now as I can do a fresh checkout and clean download and all works for me from github.

**Comment by hanqu24** [comment]
Thank you so much! FYI, I found the next URL error yesterday and manually edited the JSON file. But still got the same error on my local conda version.

**Comment by hyphaltip** [comment]
weird, I am not sure -- it seemed to work now on the cluster with this updated code that I checked in today.
