### ISSUE TITLE
CMD ERROR: CodingQuarry -p 16 -f (segmentation fault)

### ISSUE THREAD

**Issue by maysonlin** [nextgenusfs/funannotate#770]
**Are you using the latest release?**
Funannotate 1.8.3
**Describe the bug**
The funannotate ran into some issue from CodingQuarry:
`  snap           busco          
[Aug 22 06:15 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Aug 22 06:15 PM]: Genome loaded: 131 scaffolds; 534,549,832 bp; 19.10% repeats masked
[Aug 22 06:15 PM]: Existing transcript alignments found: funannotateout/predict_misc/transcript_alignments.gff3
[Aug 22 06:15 PM]: Existing RNA-seq BAM hints found: funannotateout/predict_misc/hints.BAM.gff
[Aug 22 06:15 PM]: Existing protein alignments found: funannotateout/predict_misc/protein_alignments.gff3
[Aug 22 06:16 PM]: Existing GeneMark annotation found: funannotateout/predict_misc/genemark.gff
[Aug 22 06:16 PM]: 14,433 predictions from GeneMark
[Aug 22 06:16 PM]: Existing BUSCO results found: funannotateout/predict_misc/busco.final.gff3 containing 2,591 predictions
[Aug 22 06:16 PM]: Existing Augustus annotations found: funannotateout/predict_misc/augustus.gff3
[Aug 22 06:16 PM]: Pulling out high quality Augustus predictions
[Aug 22 06:16 PM]: Found 6,512 high quality predictions from Augustus (>90% exon evidence)
[Aug 22 06:16 PM]: Running stringie on RNA-seq alignments 
[Aug 23 10:29 PM]: Running CodingQuarry prediction using stringtie alignments
[Aug 23 10:40 PM]: CMD ERROR: CodingQuarry -p 16 -f /home/slin023/funannotate/funannotateout/predict_misc/genome.softmasked.fa -t /home/slin023/funannotate/funannotateout/predict_misc/stringtie.gff3
[Aug 23 10:40 PM]: mkdir: cannot create directory ‘./ParameterFiles’: File exists
mkdir: cannot create directory ‘./ParameterFiles/model’: File exists`

**What command did you issue?**
`singularity exec --env GENEMARK_PATH=/home/slin023/gmes_linux_64_4/ /home/slurmsample/singularity/funannotate_1.8.13.sif funannotate predict -i /home/slin023/funannotate/masked.fasta --species "Phormia regina" --transcript_evidence  /scratch/mdegenna/slin023/Transannotation/Trinity-GG.fasta --rna_bam /home/data/FLAG/PhormiaMaggotAging/aging/TrimMapping/trimSorted.out.bam --busco_db /scratch/mdegenna/slin023/funannotate/diptera --cpus 16 -o funannotateout`

**Logfiles**
I ran the CodingQuarry command alone, and found some segmentation fault error, but there is no memory request flag that I can fix this. 
`Running program on 32 CPU cores
mkdir: cannot create directory ‘./ParameterFiles’: File exists
mkdir: cannot create directory ‘./ParameterFiles/model’: File exists
/tmp/slurmd/job5901139/slurm_script: line 22: 34421 Segmentation fault      singularity exec --env GENEMARK_PATH=/home/slin023/gmes_linux_64_4/ /home/slurmsample/singularity/funannotate_1.8.13.sif CodingQuarry -p 16 -f /home/slin023/funannotate/funannotateout/predict_misc/genome.softmasked.fa -t /home/slin023/funannotate/funannotateout/predict_misc/stringtie.gff3`

I have referred to [this similar thread](https://github.com/nextgenusfs/funannotate/issues/289). I think it's better to skip it, but I am not sure if skipping it will make `funannotate predict` stopped or failed because this happened before when funannotate found some exonerate dependencies were missing, so I want to double check if removing CQ will skip the step or if there is any flag that can skip CQ.

**Comment by nextgenusfs** [comment]
You should be able to skip with --weights codingquarry:0.

**Comment by maysonlin** [comment]
that works, thank you!!

**Comment by calizilla** [comment]
@maysonlin I came buy your issue after running into the same segmentation fault: please see here for a solve, in case you are still working with this tool :-) https://github.com/nextgenusfs/funannotate/issues/807#issuecomment-2092067445
