### ISSUE TITLE
logfiles folder not created when running funannotate predict (v. 0.6.2)

### ISSUE THREAD

**Issue by asapb** [nextgenusfs/funannotate#78]
Hi, 

Trying to run funannotate predict (with Funannotate release 0.6.2), but the logfiles/ directory is not created inside the output directory. (Currently my work-around is that I create the output_dir/logfiles/ myself, and then run funannotate.

(I thought this issue was fixed in the previous release 0.6.1?)

Would be grateful for your thoughts on this. 

Many thanks,
Åsa

**Comment by nextgenusfs** [comment]
I thought it was fixed as well.  What was the command that you issued?

**Comment by asapb** [comment]
Just `funannotate predict`:

```
OUT=/path/to/output/directory
mkdir -p $OUT # Creates output directory if it doesn't already exist
assembly=myAssembly # without the FASTA prefix 
species=BUSCO_MBG344001.TrainAugustus_370964125 # my Augustus trained species as it appears when listing available species with the `funannotate species` command
cpus=15
ploidy=1 # Default 1, but will use it with ploidy=2 in other cases so setting it explicitly

funannotate predict -i $OUT/$assembly.fsa -o $OUT -s $species --cpus $cpus --ploidy $ploidy

```

Have also tried running it with the `--augustus_species` option where
`augustus_species=$species`

**Comment by nextgenusfs** [comment]
Okay, problem is currently that I had in the code to check if the path exits for the `--out` option, so my assumption is that $OUT directory already exists? If so, then code is running correctly, although I can modify it to work in this situation.  Currently it is not expecting the output folder to exist for the first run.  If the output folder does exist, then it will use any data already available, i.e. in the case where you restart funannotate, etc.

The `--species` option needs should be something like `--species "Aspergillus fumigatus"` if you are entering from command line, but if you are using via BASH variable those quotes need to be escaped I think, something like:
```
species="\"Aspergillus fumigatus"\"
```

https://github.com/nextgenusfs/funannotate/commit/7156c14151364803920c2215b422df2ef3c9306b should fix this I believe.  Or running an $OUT variable that doesn't already exist.

**Comment by asapb** [comment]
I am running Funannotate on a High Performance Cluster (HPC) at the uni were I work, and was thus submitting the run with a BASH script.

At the beginning I create an output directory with 
```
OUT=/path/to/output/directory/
mkdir -p $OUT # creates directory if it doesn't already exist
```

Thus, by the time my script gets to the line where it calls Funannotate with `funannotate predict` the output directory already exists.

Although I can change the script to not create the output directory, and let Funannotate do that for me instead if that is the correct way to run Funannotate.

Will try that, and also to download the fix you submitted.

Thank you!

**Comment by asapb** [comment]
Ok, the program runs much further now:

```
$ ll
total 12104
funannotate-functional.log
drwxrwxr-x 2  111 May 24 16:42 logfiles/
drwxr-xr-x 5  4096 May 24 16:42 predict_misc/
drwxrwxr-x 2  10 May 24 16:25 predict_results/

```

Just a question about escaping quotes for the `--species` variable:

I previously set species as:
```
species='"Saccharomyces cerevisiae"'
```

This is then returned like this with echo:

`"Saccharomyces cerevisiae"` with the quotes. 

Are you saying I do *not* want the quotes if I am submitting my Funannotate run with a BASH script (rather than running it directly from the terminal)?

If so I'd just set the species like this:

```
species='Saccharomyces cerevisiae'
```

then 

`echo $species` would print 
`Saccharomyces cerevisiae` to STDOUT.

**Comment by asapb** [comment]
Regardless of whether my BASH script sets the `--species` variable `species` as

```
species='Saccharomyces cerevisiae'

```

which prints it without quotes:

```
echo $species
Saccharomyces cerevisiae
```


 or whether I set the `--species` variable as `species` as

```
species='"Saccharomyces cerevisiae"'
```

which prints with the quotes as:

```
echo $species
"Saccharomyces cerevisiae"
```

Funannotate thinks that the `--species` variable has been set to only `cerevisiae`, and hence fails to run.

Only when I set

```
augustus_species=BUSCO_MBG344001.TrainAugustus_370964125 # Generated from separate BUSCO2 run, and found with `funannotate species`
species=$augustus_species
```
does Funannotate run.

**My question is:**
How do I get `funannotate predict` to understand that my `--species` variable is "Saccharomyces cerevisiae" when I am running Funannotate from a BASH script (if I don't want to run it with the `--augustus_species` option, but just with the `--species` option)?


Btw, when I run with the `--augustus_species` option I also set

```
busco_db=saccharomycetales
```

and then I run Funannotate like this

```
funannotate predict -i $SRC/$assembly.fsa -o $OUT --species $species --augustus_species $augustus_species --busco_db $busco_db --cpus $cpus --ploidy $ploidy
```

Many thanks!

**Comment by nextgenusfs** [comment]
Right, so if the species variable does not have double quotes, it will think that the epithet (cerevisiae) is meant to be a command which it doesn't understand.  Sorry, I thought what I had written before would actually work, but you are right it doesn't.  Maybe there is another way to do it but, this will seems to work on my system:
```
#this works, double quoting the variable and no escaping quotes
species="Aspergillus fumigatus"
funannotate predict -s "$species" -i genome1.fasta -o test

#this does not work
species='"Aspergillus fumigatus"'
funannotate predict -s $species -i genome1.fasta -o test
```

**Comment by asapb** [comment]
Ok, I will try that. Thank you very much!
