### ISSUE TITLE
Funannotate tries using Diamond instead of tblastn by default?

### ISSUE THREAD

**Issue by asapb** [nextgenusfs/funannotate#79]
Hi,

Trying to run Funannotate predict, but getting an error when Funannotate tries to run [Diamond](https://github.com/bbuchfink/diamond).

The command I submit is:

```
funannotate predict -i assembly.fa -o output_dir --species "Saccharomyces cerevisiae" --augustus_species my_augustus_trained_data --busco_db saccharomycetales --cpus 6 --ploidy 1
```

At one point Funannotate wants to run Exonerate, but then complains because it cannot find Diamond even though I did not use the `--use_diamond` option.

```
--use_diamond          Use Diamond instead of tblastn for mapping protein evidence
```

The error message said:

```
[08:38:45 PM]: Mapping proteins to genome using tBlastn/Exonerate
Traceback (most recent call last):
  File "/share/apps/funannotate/0.6.2/bin/funannotate-p2g.py", line 46, in <module>
    diamond_version = subprocess.Popen(['diamond', '--version'], stdout=subprocess.PIPE).communicate()[0].split('\n')[0]
  File "/share/apps/python/2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/share/apps/python/2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The code seems to check whether everything is available, but then it says:

```
if args.use_diamond:
    lib.CheckDependencies(['diamond'])
```

The error disappeared after I installed Diamond.

However, can I set `--use_diamond=FALSE` as I don't particularly want to run Diamond instead of regular tblastn?

Also, cannot find Diamond to be listed as a prerequisite for Funannotate in the [installation instructions for Mac OSX](https://github.com/nextgenusfs/funannotate/wiki/Mac-OS-Installation) nor [Ubuntu](https://github.com/nextgenusfs/funannotate/wiki/Ubuntu-Installation).

Kind regards,
Åsa

**Comment by nextgenusfs** [comment]
Thanks, I hadn't noticed this because I had diamond installed.  I think https://github.com/nextgenusfs/funannotate/commit/0f1a3959b01d595c4129fb120d1d3b08947bde73 should fix it.

**Comment by nextgenusfs** [comment]
Diamond was added as sort of a check to see if I could increase the speed of the protein alignments as tblastn is really slow.  Speed is greatly increased with diamond, but I can't get the same level of sensitivity.  So I didn't really implement it full scale and make the switch, it is there as an option if you want it to go quickly or you have a very large genome.

**Comment by asapb** [comment]
Thank you!
