### ISSUE TITLE
Gene prediction with only protein evidence

### ISSUE THREAD

**Issue by alexvasilikop** [nextgenusfs/funannotate#793]
Hello,

What steps does funannotate follow when there is only protein evidence?

e.g.
funannotate predict -i $genome -o $outdir_predict ---cpus 10 --protein_evidence $uniprot --busco_db metazoa --organism other --ploidy 1 --repeats2evm

Unfortunately, i do not have transcriptomic data for my target genome. Would it be beneficial to provide an rna bam and transcriptome assembly from another (not so closeley related species) or is it better to run without trnascript/RNA evidence in this case?
e.g.
funannotate predict -i $genome -o $outdir_predict ---cpus 10 --protein_evidence $uniprot --transcript_evidence --rna_bam $BAM --busco_db metazoa --organism other --ploidy 1 --repeats2evm

Thanks

**Comment by hyphaltip** [comment]
you don't need to provide uniprot file if you have installed the funannotate databases, it will use the installed ones - we find that swissprot works quite well as sufficient input for providing hints.

The system will use BUSCO to train if no transcript evidence to train snap and augustus. CodingQuarry is really better suited for fungal and compact genes and will not run without transcript evidence. genemark.hmm will run a self training step.
I'd provide a 'species' and 'isolate' or 'strain' info to the predict and annotate steps so this is filled in for your final prediction files.

While we have used funannotate in my group on insects and plan genomes there may be some additional tweaking you need to do for intron models to specify a length that is much longer given that metazoan introns tend to be much much longer than fungal ones.

Leave off the `--transcript_evidence --rna_bam $BAM ` files - you do not have any to provide, it will just follow the BUSCO-based training instead.
 
See https://funannotate.readthedocs.io/en/latest/tutorials.html for some info on non-fungi parameters.

**Comment by alexvasilikop** [comment]
Great thank you
