### ISSUE TITLE
issue when installing kent-tools

### ISSUE THREAD

**Issue by krostifangers** [nextgenusfs/funannotate#8]
Hello
I have the following issue during dependencies installation "brew install funannotate"

_==> Installing nextgenusfs/tap/funannotate dependency: kent-tools
==> Downloading http://hgdownload.soe.ucsc.edu/admin/exe/userApps.v327.src.tgz
Already downloaded: /home/krostif/.cache/Homebrew/kent-tools-327.tgz
==> make userApps BINDIR=/home/krostif/.linuxbrew/Cellar/kent-tools/327/bin SCRIPTS=/home/krostif/.linuxbrew/Cellar/kent-tools/327/bin MACHTYPE=x86_64 PNGLIB=-L/home/krostif/.linuxbrew/opt/libpng/lib -lp
Last 15 lines from /home/krostif/.cache/Homebrew/Logs/kent-tools/01.make:
true /home/krostif/.linuxbrew/Cellar/kent-tools/327/bin/dbSnoop
make[2]: quittant le répertoire « /tmp/kent-tools-20160523-24511-b8guqd/userApps/kent/src/hg/makeDb/schema/dbSnoop »
make[1]: quittant le répertoire « /tmp/kent-tools-20160523-24511-b8guqd/userApps/kent/src/hg/makeDb »
cd ameme && echo ameme && make
ameme
make[1]: entrant dans le répertoire « /tmp/kent-tools-20160523-24511-b8guqd/userApps/kent/src/ameme »
gcc -O -g -Os -w -pipe -march=native -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -DUSE_SSL   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I/include -I/home/krostif/.linuxbrew/opt/libpng/include  -o ameme.o -c ameme.c
gcc -O -g -Os -w -pipe -march=native -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -DUSE_SSL   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I/include -I/home/krostif/.linuxbrew/opt/libpng/include  -o fragFind.o -c fragFind.c
gcc -O -g -o /home/krostif/.linuxbrew/Cellar/kent-tools/327/bin/ameme ameme.o fragFind.o   ../lib/x86_64/jkweb.a -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -ldl -lstdc++ -lrt -lm  -pthread -L/lib -lssl -lcrypto -L/home/krostif/.linuxbrew/opt/libpng/lib -lpng -lz -lm -lm
../lib/x86_64/jkweb.a(pngwrite.o): dans la fonction « mgSaveToPng »:
/tmp/kent-tools-20160523-24511-b8guqd/userApps/kent/src/lib/pngwrite.c:51: référence indéfinie vers « png_set_longjmp_fn »
collect2: error: ld returned 1 exit status
make[1]: *** [/home/krostif/.linuxbrew/Cellar/kent-tools/327/bin/ameme] Erreur 1
make[1]: quittant le répertoire « /tmp/kent-tools-20160523-24511-b8guqd/userApps/kent/src/ameme »
make: *** [userApps] Erreur 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues_

It seems to be related to a problem with libpng. I have the version 1.6 installed.
Thank you in advance
regards
Christophe

**Comment by nextgenusfs** [comment]
Hi Christophe,
Did you try running `brew install libpng` first and then `brew install kent-tools`, I have libpng 1.6.21 on my Mac.  What version of Linux are you on?

**Comment by krostifangers** [comment]
Hi 
It was a problem with linuxbrew, that had conflict with other programs. I just fixed it by doing a clean install of linuxbrew
thanks
krostif
