### ISSUE TITLE
incorrect species for the RepeatMasker step

### ISSUE THREAD

**Issue by asapb** [nextgenusfs/funannotate#80]
Hi again,

Am running Funannotate, which in turn calls RepeatMasker. Looking at the output table from the latter (`RepeatMasker/genome.fasta.tbl`) it says the species was set to `homo` (default species), but the species I work with is *Saccharomyces cerevisiae*, which I also set when I run Funannotate predict. 

Am I doing something wrong?

I'm running Funannotate predict from within a script like this

```
species="Saccharomyces cerevisiae"

# My pre-trained Augustus dataset for my assembly, which is found with `funannotate species`:
augustus_species=BUSCO_my_assembly.TrainAugustus_370964125 

ploidy=1
busco_db=saccharomycetales
assembly=my_assembly
cpus=6

OUT=/funannotate/ouput/dir

funannotate predict -i $assembly.fa -o $OUT --species "$species" --augustus_species $augustus_species --busco_db $busco_db --cpus $cpus --ploidy $ploidy
```

The RepeatMasker output I am referring to is the summary table from RepeatMasker, which when run as part of the Funannotate pipeline ends up in:
`/funannotate/output/dir/predict_misc/RepeatMasker/genome.fasta.tbl`

At the end of the that summary table `genome.fasta.tbl` it says

```
The query species was assumed to be homo          
RepeatMasker version open-4.0.6 , default mode
```

Meanwhile, if I run stand-alone RepeatMasker I always set the species like this

```
RepeatMasker -species "saccharomyces cerevisiae" my_assembly.fa 
```

and then the summary table will say

```
The query species was assumed to be saccharomyces cerevisiae
RepeatMasker version open-4.0.6 , default mode
```

Many thanks and kind regards,
Åsa

**Comment by nextgenusfs** [comment]
So funannotate first runs RepeatModeler to generate a custom library of repeats to then use with RepeatMasker.  The `-species` option and `-lib` option are not compatible with each other, I think that what you are seeing in the tbl file is sort of just a logging error from RepeatMasker if you use a custom library it outputs that into the table, despite that isn't what happened. I get the same think in my logfiles even with v4.07. If RepeatModeler does not find any custom repeats, then funannotate runs RepeatMasker using the `-species fungi` option.

**Comment by asapb** [comment]
The summary table from RepeatMasker when run through Funannotate lists elements such as SINEs (ALUs and MIRs), LINEs, LTR- and DNA elements like this:

```
$ cat genome.fasta.tbl 
==================================================
file name: genome.fasta             
sequences:            17
total length:   12275942 bp  (12275942 bp excl N/X-runs)
GC level:         38.17 %
bases masked:     783086 bp ( 6.38 %)
==================================================
               number of      length   percentage
               elements*    occupied  of sequence
--------------------------------------------------
SINEs:                0            0 bp    0.00 %
      ALUs            0            0 bp    0.00 %
      MIRs            0            0 bp    0.00 %

LINEs:                0            0 bp    0.00 %
      LINE1           0            0 bp    0.00 %
      LINE2           0            0 bp    0.00 %
      L3/CR1          0            0 bp    0.00 %

LTR elements:       434       395483 bp    3.22 %
      ERVL            0            0 bp    0.00 %
      ERVL-MaLRs      0            0 bp    0.00 %
      ERV_classI      0            0 bp    0.00 %
      ERV_classII     0            0 bp    0.00 %

DNA elements:         0            0 bp    0.00 %
     hAT-Charlie      0            0 bp    0.00 %
     TcMar-Tigger     0            0 bp    0.00 %

Unclassified:       202       230168 bp    1.87 %

Total interspersed repeats:   625651 bp    5.10 %


Small RNA:            0            0 bp    0.00 %

Satellites:           0            0 bp    0.00 %
Simple repeats:    2974       132239 bp    1.08 %
Low complexity:     537        25304 bp    0.21 %
==================================================

* most repeats fragmented by insertions or deletions
  have been counted as one element
                                                      

The query species was assumed to be homo          
RepeatMasker version open-4.0.6 , default mode
                                   
run with rmblastn version 2.2.27+
The query was compared to classified sequences in ".../repeatmodeler.lib.fa"
RepBase Update 20160829, RM database version 20160829
```

I get the same type of elements listed if I run stand-alone RepeatMasker with the default settings (that is, without specifying the species, which is then set to human).

```
$ RepeatMasker genome.fasta

$ cat genome.fasta.tbl 
==================================================
file name: genome.fasta             
sequences:            17
total length:   12275942 bp  (12275942 bp excl N/X-runs)
GC level:         38.17 %
bases masked:     190392 bp ( 1.55 %)
==================================================
               number of      length   percentage
               elements*    occupied  of sequence
--------------------------------------------------
SINEs:               16          946 bp    0.01 %
      ALUs            0            0 bp    0.00 %
      MIRs            2           96 bp    0.00 %

LINEs:               47         2873 bp    0.02 %
      LINE1           3          144 bp    0.00 %
      LINE2          13          813 bp    0.01 %
      L3/CR1         17         1091 bp    0.01 %

LTR elements:         2          124 bp    0.00 %
      ERVL            1           41 bp    0.00 %
      ERVL-MaLRs      0            0 bp    0.00 %
      ERV_classI      0            0 bp    0.00 %
      ERV_classII     0            0 bp    0.00 %

DNA elements:        17         1164 bp    0.01 %
     hAT-Charlie      2           94 bp    0.00 %
     TcMar-Tigger     2          109 bp    0.00 %

Unclassified:         0            0 bp    0.00 %

Total interspersed repeats:     5107 bp    0.04 %


Small RNA:          164        23730 bp    0.19 %

Satellites:           0            0 bp    0.00 %
Simple repeats:    3048       136162 bp    1.11 %
Low complexity:     542        25501 bp    0.21 %
==================================================

* most repeats fragmented by insertions or deletions
  have been counted as one element
                                                      

The query species was assumed to be homo sapiens  
RepeatMasker version open-4.0.6 , default mode
                                   
run with rmblastn version 2.2.27+
RepBase Update 20160829, RM database version 20160829
```

Obviously, because I ran RepeatMasker without generating a RepeatModeler library the actual numbers for the different elements differ (compared to the RepeatMasker results generated from Funannotate), but the same type of elements are listed in the summary tables from the two RepeatMasker runs (from Funannotate and stand-alone RepeatMasker respectively).

However, if I run stand-alone RepeatMasker setting `-species "saccharomyces cerevisisae"` the summary table displays Retroelements (including SINEs and LINEs), DNA transposons and Rolling circles.

```
$ RepeatMasker genome.fasta -species "saccharomyces cerevisiae"

$ cat genome.fasta.tbl 
==================================================
file name: genome.fasta             
sequences:            17
total length:   12275942 bp  (12275942 bp excl N/X-runs)
GC level:         38.17 %
bases masked:     685951 bp ( 5.59 %)
==================================================
               number of      length   percentage
               elements*    occupied  of sequence
--------------------------------------------------
Retroelements          490       449716 bp    3.66 %
   SINEs:                0            0 bp    0.00 %
   Penelope              0            0 bp    0.00 %
   LINEs:                0            0 bp    0.00 %
    CRE/SLACS            0            0 bp    0.00 %
     L2/CR1/Rex          0            0 bp    0.00 %
     R1/LOA/Jockey       0            0 bp    0.00 %
     R2/R4/NeSL          0            0 bp    0.00 %
     RTE/Bov-B           0            0 bp    0.00 %
     L1/CIN4             0            0 bp    0.00 %
   LTR elements:       490       449716 bp    3.66 %
     BEL/Pao             0            0 bp    0.00 %
     Ty1/Copia         436       425678 bp    3.47 %
     Gypsy/DIRS1        54        24038 bp    0.20 %
       Retroviral        0            0 bp    0.00 %

DNA transposons          0            0 bp    0.00 %
   hobo-Activator        0            0 bp    0.00 %
   Tc1-IS630-Pogo        0            0 bp    0.00 %
   En-Spm                0            0 bp    0.00 %
   MuDR-IS905            0            0 bp    0.00 %
   PiggyBac              0            0 bp    0.00 %
   Tourist/Harbinger     0            0 bp    0.00 %
   Other (Mirage,        0            0 bp    0.00 %
    P-element, Transib)

Rolling-circles          0            0 bp    0.00 %

Unclassified:           21        57370 bp    0.47 %

Total interspersed repeats:      507086 bp    4.13 %


Small RNA:               8        17635 bp    0.14 %

Satellites:              0            0 bp    0.00 %
Simple repeats:       3008       135814 bp    1.11 %
Low complexity:        536        25509 bp    0.21 %
==================================================

* most repeats fragmented by insertions or deletions
  have been counted as one element
                                                      

The query species was assumed to be saccharomyces cerevisiae
RepeatMasker version open-4.0.6 , default mode
                                   
run with rmblastn version 2.2.27+
RepBase Update 20160829, RM database version 20160829
```

As you can see the summary tables look different, in the sense that they list different types of elements. Settings `-species` to `fungi` or `"saccharomyces cerevisiae"` gives the same type of output (the same type of elements are listed), while the default settings (human) and running RepeatMasker through Funannotate gives different output i.e., lists different types of elements (see first two tables above).

That's why I am wondering about the settings when running first RepeatModeler and then RepeatMasker through Funannotate. In the RepeatMasker output from Funannotate it looks as though RepeatMasker treats the assembly as a human genome rather than a fungal one... but maybe this is an issue with RepeatMasker and RepeatModeler rather than an issue with Funannotate?

Looks like an issue though...

**Comment by nextgenusfs** [comment]
It isn't a funannotate issue.  What matters here is the bases that are masked, from funannotate you have 6.38%, from default you have 1.55%, and from `--species saccharomyces` you have 5.59%.  Although I don't know exactly how RepeatMasker works my assumption is that this table is based off of how the repeats are classified prior to masking.  In other words, the classification of the repeats from RepeatModeler isn't as good as what is in the `--species saccharomyces` setting - again I'm assuming this is because we know a whole bunch about yeast, if it were an unknown species there is no a priori knowledge about the repeats you wouldn't be able to specify a species in RepeatMasker.

**Comment by hyphaltip** [comment]
In my experience, for fungi, I don't see any downside in setting species for RepeatMasker to something more general (Fungi or Ascomycota) which will then result in the filtered DB that is run with RepeatMasker to be repeats from the specified clade. There is not going to be a huge performance hit for that slightly larger DB (as compared for example to the runtime for RepeatModeler).

Also - we're exploring running REPET outside of the automated pipelines and feeding that repeat library instead as it is reportedly more accurate than RepeatModeler in terms of not calling multi-copy host proteins as TEs and not splitting candidates into as many sub-pieces.  YMMV so some experimentation may be needed -- because of the downstream TE identification steps that are also part of funannotate the potential downside to an unmasked genomic segment that is in fact a TE are lower because if it protein coding but is a Tpase containing gene it will likely get filtered in the later step I would think.

**Comment by asapb** [comment]
OK Jon, that makes sense. Thank you very much!
Thanks also to hyphaltip for suggesting [REPET](https://urgi.versailles.inra.fr/Tools/REPET) for repeat identification.

**Comment by nextgenusfs** [comment]
v0.7.0 now supports `--repeatmasker_species` option. 51c8788a38b0d1ed9ec053fb13510fe6bcf16335

**Comment by asapb** [comment]
Cool, thanks!

**Comment by aditi17142** [comment]
HI!
I have been trying to use RepeatMasker for de novo assembled genome.  I have installed latest version of RepeatMasker (https://www.repeatmasker.org/RepeatMasker/). The species for the genome isn't available. Kindly guide how to go about it.
