### ISSUE TITLE
SignalP6 support

### ISSUE THREAD

**Issue by pascalangst** [nextgenusfs/funannotate#809]
Hi @nextgenusfs 

I'm seeing an error when running funannotate v1.8.11 with the latest SignalP version. 

```
[Oct 14 03:55 PM]: usage: SignalP 6.0 Signal peptide prediction tool [-h] --fastafile FASTAFILE
                                                  --output_dir OUTPUT_DIR
                                                  [--format [{txt,png,eps,all,none}]]
                                                  [--organism [{eukarya,other,euk}]]
                                                  [--mode [{fast,slow,slow-sequential}]]
                                                  [--bsize BSIZE]
                                                  [--write_procs WRITE_PROCS]
                                                  [--version] [--skip_resolve]
SignalP 6.0 Signal peptide prediction tool: error: argument --format/-fmt/-f/-format: invalid choice: 'short' (choose from 'txt', 'png', 'eps', 'all', 'none')
```

After scrolling through the code, the issue might be that funannotate was not updated to this new version. Funannotate runs fine with SignalP 5.0 for me.

https://github.com/nextgenusfs/funannotate/blob/0776463ec961be5e6fab852c33065ef650ec015f/funannotate/library.py#L5613-L5614

Thank you,
Pascal

**Comment by IanDMedeiros** [comment]
Hi @pascalangst and @nextgenusfs, that commit addresses an issue with how the output is parsed but I know there is still an issue with running signalP6 within funannotate annotate. I had started working on a fix but got sidetracked so I have just been running signalP6 separately and giving the results to annotate with the --signalp flag. If I have time this week I will try to finish the solution I was working on to run it within annotate.

**Comment by IanDMedeiros** [comment]
I just created a pull request (#822) that should deal with any remaining issues around running signalP6 as part of `annotate`. Works on our HPC system, but @pascalangst  could you try it out and make sure it works for you? IIRC @nextgenusfs does not have access to signalP6 because of licensing issues.

**Comment by pascalangst** [comment]
Hi @IanDMedeiros, signalP6 works fine for me with https://github.com/nextgenusfs/funannotate/pull/822. Thank you very much for the quick turnaround.
