### ISSUE TITLE
Funannotate database configuration error

### ISSUE THREAD

**Issue by nam183** [nextgenusfs/funannotate#81]
I am trying to install funannotate v0.6.2
and in that after running "funannotate setup -m all" command successfully without any errors while i am trying to run funannotate predict i am getting following error

> funannotate  database is not properlyconfigured, please run funannotate setup -m all

I have set DB directory to 

> $HOME/funannotate

How can i solve this error?

Thanks

**Comment by nextgenusfs** [comment]
The error is saying that the database is either not downloaded formatted correctly or there is a missing symlink.  Can you try to run setup again and explicitly state where the database folder is, like this:
```
funannotate setup -m all -d /path/to/funannotate/database/folder
```

**Comment by nextgenusfs** [comment]
closing because conversation is stale, reopen if still a problem.

**Comment by ayrton1999** [comment]
Cuando intento hacer la anotación, me sale el siguiente mensaje:
Funannotate database not properly configured, run funannotate setup.


Agradezco la respuesta que me puedan brindar
