### ISSUE TITLE
docker file; can't find gmes_petap.pl

### ISSUE THREAD

**Issue by rec3141** [nextgenusfs/funannotate#83]
I got "ERROR:  gmes_petap.pl is not installed" after running ```funannotate setup -m dep``` in the docker image. I had to manually symlink the scripts in gm_et_linux_64/gmes_petap/ to /usr/local/bin to get it to work.

**Comment by nextgenusfs** [comment]
I need to update the docker image instructions as I think I have an easier way to install and get a complete docker container.  Basically you need to download the base image and then only have to run a docker build command once to integrate genemark and the other individual license downloaded software.

**Comment by nextgenusfs** [comment]
docker instructions now located at http://funannotate.readthedocs.io/en/latest/docker.html#docker, feel free to reopen if still a problem
