### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by lavi3948** [nextgenusfs/funannotate#834]
Hello,
I have been stuck for a while with this error:
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/venv/lib/python3.7/site-packages/funannotate/annotate.py", line 1029, in main
    Cluster_annotations)
  File "/venv/lib/python3.7/site-packages/funannotate/library.py", line 7128, in GetClusterGenes
    Genes = gff2dict(GFF, genome, Genes)
  File "/venv/lib/python3.7/site-packages/funannotate/library.py", line 4235, in gff2dict
    contig, source, feature, start, end, score, strand, phase, attributes = line.split('\t')
ValueError: not enough values to unpack (expected 9, got 1)

I have checked my gff3 file and everything seems fine with it.
Does anyone have suggestions on why I keep getting this error?

**Comment by hyphaltip** [comment]
How did you get here? I don't know what you are trying to load is this gff from w/n funannotate or soemthing external. Be good to know what line of gff fails. If you only provide a few lines of gff does it work? We should try to add more validation steps in the parser I suspect.

**Comment by hyphaltip** [comment]
But the error indicates a line does not have 9 tab delimited columns only one col is detected hence the error for 1 found, 9 expected.

**Comment by lavi3948** [comment]
I get this error when I run funannotate annotate. I validated my gff3 file, which has 9 tab delimited columns.

**Comment by lavi3948** [comment]
Hi Jason,

Just to follow up on this, it appears to have been a problem with the supercomputer I was using, as the next day I tried again and it worked. This issue can be closed.

Thanks,
