### ISSUE TITLE
Error RepeatModeler

### ISSUE THREAD

**Issue by mikaeldahl** [nextgenusfs/funannotate#84]
Hi! 
When I run the funannotate setup it looks like everything should be in place.....ready to roll.
But when I start an analysis it gives me an error that point to RepeatModeler. Can you please help me to see what might be wrong? 

###########################################
funannotate setup -m all                                                                                               [12:21]
OutputDir    = 
Script mode  = all
Found DB symlinked folder
DB directory set to (/usr/local/share/funannotate), continue [y/n]: y
Creating folder to store DB files: /usr/local/share/funannotate
ln: failed to create symbolic link 'DB/funannotate': File exists
-----------------------------------------------
Okay, starting downloading of databases....
-----------------------------------------------
MEROPS DB found, skipping download
-----------------------------------------------
UniProt DB found, skipping download. To update delete uniprot_sprot.fasta.
-----------------------------------------------
Pfam-A DB found, skipping download. To update delete Pfam-A.hmm
-----------------------------------------------
PFAM mapping found, skipping download. To update delete Pfam-A.clans.tsv
-----------------------------------------------
dbCAN DB found, skipping download
-----------------------------------------------
Downloading BUSCO outgroups
--2017-06-02 12:25:48--  https://uwmadison.box.com/shared/static/4pl3ngptpjjfs1cu4se6g27ei0wptsdt.gz
Resolving uwmadison.box.com (uwmadison.box.com)... 107.152.26.197
Connecting to uwmadison.box.com (uwmadison.box.com)|107.152.26.197|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://uwmadison.app.box.com/shared/static/4pl3ngptpjjfs1cu4se6g27ei0wptsdt.gz [following]
--2017-06-02 12:25:49--  https://uwmadison.app.box.com/shared/static/4pl3ngptpjjfs1cu4se6g27ei0wptsdt.gz
Resolving uwmadison.app.box.com (uwmadison.app.box.com)... 107.152.27.199
Connecting to uwmadison.app.box.com (uwmadison.app.box.com)|107.152.27.199|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/3sB2_-IWFEz5DBik8uLF7g0kS6xiAWdUMAhfUM7Eo-MLIlbAr9aAme2q-vvANiZEjX2rcBmiNxls1xQJg76M0VG6ILyv1x0bTrzkyBwK0XkEmHujxA_CDuZY6lPRt3WXrNP5QVlccdMvYW0a1ty9KTc9Q23AQzOIEelNLzhY_KfpytSDfYpagFq_4NUYUzobx2z3fsvNyE7L6FQyZWc0T1SWjT0I6ckHrtEiDr4WNA7PVxpJVnYECcCdCsuZlnhZF0RK4_oI8nBgATLY9DmiAOZjfooiDRGdN4kCURtaGhOgTRKQZBipYhrjY-N66KQdH5SvoJon5xbC-vS82_NkHnRGLHwq_fWgFbiQ78bAuYcdJ2bLFzH2M00ajLC-eHcbwWk2dSZZjCgfJGql07ZkCmibLU-fGubGUlZU66NMFh4Ca9q6tqGP49XbvsrsgDkQ0j2eK6xal5DGrtTN0IrUDrlMhs9AQEiXJOya68kLbIkOfjJ1zi4e5TePmWsZuwxk7G77pUchqaaUN_ALbUI9nyzbBrXWetvxfcXfEyWJhr8a68Gxb0a2KH4AJ94EAjkofTmrJj8apZvEfRzm6A75YMWninyW-FRc0CLbKUwNr4RLe4UsAhoH56fLmbaYrVfGbpK5wnHKC5paLBIp2miUVu_ZnCfv2sed14d_66dLQpbN-FKuOJT4N4oKivFO39__gJcHA0823gZRUK1NeIKGYC8Jtc87u48iLNp3JgmNy_zfKWcUX43ITDcyFv6T-SQaLRmpZBgU5K_ptHOMKl2WN0vM2gBdsK2Zjgn4y2sGyMCWgWebGHOu3LZMLG4ECwaquyb3orZUool0KVWqIvn6x1svodNgvN4oeEtf-WO6JSVvM32mS3M4_ScWgcHPEuWBoNdiD7eC6TYVbhb0ibi1yVOlZeSQA75atOqK0ncMcBXAJJ9hMmR3YMWn--MQ6djrDrkWY0WqZtw8SD2HyI2ujoXtzIi4gOv94Ws9vNEt5O68YkaGXByEik6r3yNO6A5jZDWG9TqTXhRLLxSPDb8rFBoj7QRGn1X3N-FNN-hoDWj_QMoBRhqu6MxulIvuCG0TPff8mTMkmyg2VGR7KmXtukwLfAHysaQQYIqXDcAlYegWhj3_dix2drekdXxAUxrVGDPqzu22vlqdNnqYyO3TEfnDEtw4lBBwa_DkcvjcXm4YdoFRlwZe5h4F/download [following]
--2017-06-02 12:25:50--  https://public.boxcloud.com/d/1/3sB2_-IWFEz5DBik8uLF7g0kS6xiAWdUMAhfUM7Eo-MLIlbAr9aAme2q-vvANiZEjX2rcBmiNxls1xQJg76M0VG6ILyv1x0bTrzkyBwK0XkEmHujxA_CDuZY6lPRt3WXrNP5QVlccdMvYW0a1ty9KTc9Q23AQzOIEelNLzhY_KfpytSDfYpagFq_4NUYUzobx2z3fsvNyE7L6FQyZWc0T1SWjT0I6ckHrtEiDr4WNA7PVxpJVnYECcCdCsuZlnhZF0RK4_oI8nBgATLY9DmiAOZjfooiDRGdN4kCURtaGhOgTRKQZBipYhrjY-N66KQdH5SvoJon5xbC-vS82_NkHnRGLHwq_fWgFbiQ78bAuYcdJ2bLFzH2M00ajLC-eHcbwWk2dSZZjCgfJGql07ZkCmibLU-fGubGUlZU66NMFh4Ca9q6tqGP49XbvsrsgDkQ0j2eK6xal5DGrtTN0IrUDrlMhs9AQEiXJOya68kLbIkOfjJ1zi4e5TePmWsZuwxk7G77pUchqaaUN_ALbUI9nyzbBrXWetvxfcXfEyWJhr8a68Gxb0a2KH4AJ94EAjkofTmrJj8apZvEfRzm6A75YMWninyW-FRc0CLbKUwNr4RLe4UsAhoH56fLmbaYrVfGbpK5wnHKC5paLBIp2miUVu_ZnCfv2sed14d_66dLQpbN-FKuOJT4N4oKivFO39__gJcHA0823gZRUK1NeIKGYC8Jtc87u48iLNp3JgmNy_zfKWcUX43ITDcyFv6T-SQaLRmpZBgU5K_ptHOMKl2WN0vM2gBdsK2Zjgn4y2sGyMCWgWebGHOu3LZMLG4ECwaquyb3orZUool0KVWqIvn6x1svodNgvN4oeEtf-WO6JSVvM32mS3M4_ScWgcHPEuWBoNdiD7eC6TYVbhb0ibi1yVOlZeSQA75atOqK0ncMcBXAJJ9hMmR3YMWn--MQ6djrDrkWY0WqZtw8SD2HyI2ujoXtzIi4gOv94Ws9vNEt5O68YkaGXByEik6r3yNO6A5jZDWG9TqTXhRLLxSPDb8rFBoj7QRGn1X3N-FNN-hoDWj_QMoBRhqu6MxulIvuCG0TPff8mTMkmyg2VGR7KmXtukwLfAHysaQQYIqXDcAlYegWhj3_dix2drekdXxAUxrVGDPqzu22vlqdNnqYyO3TEfnDEtw4lBBwa_DkcvjcXm4YdoFRlwZe5h4F/download
Resolving public.boxcloud.com (public.boxcloud.com)... 107.152.26.200
Connecting to public.boxcloud.com (public.boxcloud.com)|107.152.26.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2374032 (2,3M) [application/octet-stream]
--2017-06-02 12:25:51--  https://public.boxcloud.com/d/1/3sB2_-IWFEz5DBik8uLF7g0kS6xiAWdUMAhfUM7Eo-MLIlbAr9aAme2q-vvANiZEjX2rcBmiNxls1xQJg76M0VG6ILyv1x0bTrzkyBwK0XkEmHujxA_CDuZY6lPRt3WXrNP5QVlccdMvYW0a1ty9KTc9Q23AQzOIEelNLzhY_KfpytSDfYpagFq_4NUYUzobx2z3fsvNyE7L6FQyZWc0T1SWjT0I6ckHrtEiDr4WNA7PVxpJVnYECcCdCsuZlnhZF0RK4_oI8nBgATLY9DmiAOZjfooiDRGdN4kCURtaGhOgTRKQZBipYhrjY-N66KQdH5SvoJon5xbC-vS82_NkHnRGLHwq_fWgFbiQ78bAuYcdJ2bLFzH2M00ajLC-eHcbwWk2dSZZjCgfJGql07ZkCmibLU-fGubGUlZU66NMFh4Ca9q6tqGP49XbvsrsgDkQ0j2eK6xal5DGrtTN0IrUDrlMhs9AQEiXJOya68kLbIkOfjJ1zi4e5TePmWsZuwxk7G77pUchqaaUN_ALbUI9nyzbBrXWetvxfcXfEyWJhr8a68Gxb0a2KH4AJ94EAjkofTmrJj8apZvEfRzm6A75YMWninyW-FRc0CLbKUwNr4RLe4UsAhoH56fLmbaYrVfGbpK5wnHKC5paLBIp2miUVu_ZnCfv2sed14d_66dLQpbN-FKuOJT4N4oKivFO39__gJcHA0823gZRUK1NeIKGYC8Jtc87u48iLNp3JgmNy_zfKWcUX43ITDcyFv6T-SQaLRmpZBgU5K_ptHOMKl2WN0vM2gBdsK2Zjgn4y2sGyMCWgWebGHOu3LZMLG4ECwaquyb3orZUool0KVWqIvn6x1svodNgvN4oeEtf-WO6JSVvM32mS3M4_ScWgcHPEuWBoNdiD7eC6TYVbhb0ibi1yVOlZeSQA75atOqK0ncMcBXAJJ9hMmR3YMWn--MQ6djrDrkWY0WqZtw8SD2HyI2ujoXtzIi4gOv94Ws9vNEt5O68YkaGXByEik6r3yNO6A5jZDWG9TqTXhRLLxSPDb8rFBoj7QRGn1X3N-FNN-hoDWj_QMoBRhqu6MxulIvuCG0TPff8mTMkmyg2VGR7KmXtukwLfAHysaQQYIqXDcAlYegWhj3_dix2drekdXxAUxrVGDPqzu22vlqdNnqYyO3TEfnDEtw4lBBwa_DkcvjcXm4YdoFRlwZe5h4F/download
Reusing existing connection to public.boxcloud.com:443.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

-----------------------------------------------
Funannotate repeat protein DB, skipping download
-----------------------------------------------
Gene Ontology already exists, skipping download. To update delete go.obo.
-----------------------------------------------
MIBiG database already exists, skipping download
-----------------------------------------------
InterPro mapping file already exists, skipping download. To update delete interpro.xml
-----------------------------------------------
Checking External Dependencies....
-----------------------------------------------
blastp installed........./home/mikael/.linuxbrew/bin/blastp
hmmsearch installed........./home/mikael/.linuxbrew/bin/hmmsearch
hmmscan installed........./home/mikael/.linuxbrew/bin/hmmscan
augustus installed........./usr/local/bioinf/augustus-3.2.3/bin/augustus
gmes_petap.pl installed........./usr/local/bioinf/genemark/gmes_petap/gmes_petap.pl
mummer installed........./home/mikael/.linuxbrew/bin/mummer
nucmer installed........./home/mikael/.linuxbrew/bin/nucmer
show-coords installed........./home/mikael/.linuxbrew/bin/show-coords
exonerate installed........./home/mikael/.linuxbrew/bin/exonerate
gmap installed........./home/mikael/.linuxbrew/bin/gmap
blat installed........./home/mikael/.linuxbrew/bin/blat
RepeatModeler installed........./home/mikael/.linuxbrew/bin/RepeatModeler
RepeatMasker installed........./home/mikael/.linuxbrew/bin/RepeatMasker
pslCDnaFilter installed........./home/mikael/.linuxbrew/bin/pslCDnaFilter
bedtools installed........./home/mikael/.linuxbrew/bin/bedtools
bamtools installed........./home/mikael/.linuxbrew/bin/bamtools
gag.py installed........./home/mikael/.linuxbrew/bin/gag.py
tbl2asn installed........./home/mikael/.linuxbrew/bin/tbl2asn
braker.pl installed........./home/mikael/.linuxbrew/bin/braker.pl
funannotate installed........./home/mikael/.linuxbrew/bin/funannotate
mafft installed........./home/mikael/.linuxbrew/bin/mafft
trimal installed........./home/mikael/.linuxbrew/bin/trimal
raxmlHPC-PTHREADS installed........./home/mikael/.linuxbrew/bin/raxmlHPC-PTHREADS
tRNAscan-SE installed........./home/mikael/.linuxbrew/bin/tRNAscan-SE
rmOutToGFF3.pl installed........./home/mikael/.linuxbrew/bin/rmOutToGFF3.pl
proteinortho5.pl installed........./home/mikael/.linuxbrew/bin/proteinortho5.pl
-----------------------------------------------
Checking Python modules....
-----------------------------------------------
biopython installed
psutil installed
natsort installed
goatools installed
sklearn installed
matplotlib installed
seaborn installed
numpy installed
pandas installed
-----------------------------------------------
Checking Perl modules....
-----------------------------------------------
Bio::SeqIO installed
Pod::Usage installed
File::Basename installed
threads installed
threads::shared installed
Thread::Queue installed
Getopt::Long installed
FindBin installed
File::Spec installed
File::Path installed
Data::Dumper installed
YAML installed
Carp installed
Hash::Merge installed
Logger::Simple installed
Parallel::ForkManager installed
-----------------------------------------------
Script complete, funannotate is ready to roll!

#####################################################

#This is the start command and error message.
funannotate predict -i pilon2.fasta -o Afin1_anno1 -s "Genome one" --augustus_species schizosaccharomyces_pombe --transcript_evidence /media/hd01/data/Fungi/Mapping/STAR_mapping_Canu_pilon2/Aligned_RNA.pilon2.sorted.bam --protein_evidence /media/hd01/data/Fungi/Afinlayi_annotation/Resources/Spombe.fa --cpus 1
-------------------------------------------------------
[03:41:57 PM]: OS: linux2, 24 cores, ~ 49 GB RAM. Python: 2.7.13
[03:41:57 PM]: Running funannotate v0.6.2
[03:41:58 PM]: Augustus training set for schizosaccharomyces_pombe already exists, thus funannotate will use those parameters.
		If you want to re-train, provide a unique name for the --augustus_species argument
[03:42:00 PM]: AUGUSTUS (3.2.3) detected, version seems to be compatible with BRAKER1 and BUSCO
[03:42:00 PM]: Loading sequences and soft-masking genome
[03:42:00 PM]: Soft-masking: building RepeatModeler database
[03:42:00 PM]: Soft-masking: generating repeat library using RepeatModeler
Traceback (most recent call last):
  File "/home/mikael/.linuxbrew/Cellar/funannotate/0.6.2/libexec/bin/funannotate-predict.py", line 306, in <module>
    lib.RepeatModelMask(Genome, args.cpus, os.path.join(args.out, 'predict_misc'), MaskGenome, debug)
  File "/home/mikael/.linuxbrew/Cellar/funannotate/0.6.2/libexec/lib/library.py", line 1169, in RepeatModelMask
    os.rename(os.path.join(outdir, RP_folder, 'consensi.fa.classified'), library)
UnboundLocalError: local variable 'RP_folder' referenced before assignment

**Comment by nextgenusfs** [comment]
Have you installed the RepBase repeatMasker libraries?  If you look in the `Afin1_anno1/logfiles/funannotate-predict.log` and `Afin1_anno1/logfiles/funannotate-repeats.log` files you should get more information than is on the command line, likely in this case the repeats log file hopefully will tell you why RepeatModeler has failed.

**Comment by mikaeldahl** [comment]
This is the repeatslog: 
cat /media/hd01/data/Fungi/Afinlayi_annotation/Afin1_anno1/logfiles/funannotate-repeats.log
Building database Repeats:
  Adding /media/hd01/data/Fungi/Afinlayi_annotation/Afin1_anno1/predict_misc/genome.fasta to database
Number of sequences (bp) added to database: 38 ( 23598146 bp )
NCBIBlastSearchEngine::setPathToEngine( /usr/local/rmblast/rmblastn ): Program does not exist! at /usr/local/bioinf/RepeatModeler-open-1.0.10/RepeatModeler line 210.
funannotate-repeats.log (END)

**Comment by nextgenusfs** [comment]
So hopefully that gets you on the right track, RepeatModeler/RepeatMasker is not installed properly.
