### ISSUE TITLE
Can you please add update instructions to FAQ/Wiki

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#85]
... every time struggling to find how to do it... :(

**Comment by nextgenusfs** [comment]
It would help if you pointed me to what isn't clear in the wiki, a manual is on my todo list but admittedly it isn't high on the list.  When I find some time I'm trying to get a manuscript together - at that point I will certainly update docs/manual/wiki.

**Comment by nextgenusfs** [comment]
Ah, now I read the title and understand, thought you were asking to "update" the FAQ/Wiki, but you wanted to know how to install new versions.  Yes I can add that.

**Comment by nextgenusfs** [comment]
https://github.com/nextgenusfs/funannotate/wiki/Frequently-asked-Questions

**Comment by MichaelFokinNZ** [comment]
Yahooo! Thank you.
