### ISSUE TITLE
Convert BAM to GFF format

### ISSUE THREAD

**Issue by cberthelier** [nextgenusfs/funannotate#854]
Hello,

I am trying to convert BAM files (generated using Minimap2 or STAR and sorted with samtools) with funnanotate but it creates a GFF file with only one line "##gff-version 3".
My command line is `funannotate util bam2gff3 -i input_file.bam -o output_file.gff3` 
There is no error or fail. Is it possible to have a verbose option to have more details on what's happened? And are there already similar errors before?
I used  funannotate v1.8.9.

Thank you in advance for the help!

**Comment by nextgenusfs** [comment]
The script is using an internal version of https://github.com/JohnLonginotto/pybam. How did you run minimap2 to generate this file? It is meant to convert transcript to genome alignments to GFF3.

I've got a separate implementation of this that will be what future versions of funannotate utilize here https://github.com/nextgenusfs/gapmm2.  `gapmm2` can output GFF3 format directly.

**Comment by cberthelier** [comment]
I don’t remember exactly how I ran minimap2 but by converting my file to BED format and then in GFF3 works.
I will try gapmm2 another time!
Thank you for your reply.
