### ISSUE TITLE
'funannotate predict' status unclear

### ISSUE THREAD

**Issue by ARW-UBT** [nextgenusfs/funannotate#855]
Hello, 
I started a annotation project of an existing genaome assembly. 
Funannotate clean / sort / mask / train completed successfully. 
Howwever funannotate predict is running since 2 days without 'visible' progress. These the corrent messsage status on the command line: 

[Jan 21 10:53 AM]: OS: AlmaLinux 9.1, 40 cores, ~ 396 GB RAM. Python: 3.8.15
[Jan 21 10:53 AM]: Running funannotate v1.8.13

I have looked in the output folders, and the last modifocation is 2 days old now. It seems that funannotate got stuck somewhere. 
Is there any possibility to find out more about the status of funannotate?
I have provided a chekc output below, it indicates some issues, unfortunately. 
May be you can advise me how to proceed.
Best regards,

**What command did you issue?**
funannotate predict -i ASM104565v1_genomic.cleaned.sorted.masked.fa -o fun-v1 -s "Lasius niger" --strain ASM104565v1 --cpus 40

**Logfiles**
no logfiles available for this command

**OS/Install Information**
funannotate has been installed using mamba
for output of 'funannotate check --show-versions' see attached file
[funannotate-check.txt](https://github.com/nextgenusfs/funannotate/files/10478318/funannotate-check.txt)

**Comment by nextgenusfs** [comment]
Logfile is in the output directory, should tell you where it is stuck.

**Comment by nextgenusfs** [comment]
Did you run funannotate test successfully?

**Comment by ARW-UBT** [comment]
Hi @nextgenusfs 
Since I had some problems with perl-FindBin using GeneMark-ES/EP, I used a recently GeneMark-ETP+ instead, and a 'funannotate test -t all' test run via singularity container completed with no errors. 

Is there a possibility to 'update' existing genomic annotations (at NCBI, see above) with extrinsic evidence such as RNA-Seq data to get UTRs annotated? Or would you NOT recommend to use existing annotations?

**Comment by hyphaltip** [comment]
you definitely can run 'update' on an existing annotation - that's the idea - it can import from the NCBI gbk file. This will also predict alt splicing with PASA and add UTRs if RNAseq supports evidence for that.

**Comment by ARW-UBT** [comment]
Hi @hyphaltip 
Thank you for that great tip. I have seen the 'update' step in the tutorials after the 'predict' step, but I was not aware that I can provide gbff anf gff from NCBI's geneomes directly to funannotate. 
Since 'update' uses gbff, gff and RNAseq data, is the '--busco_db' option relevant for the update script (I could not see it in the available option)?
Great help! Thanks again!

**Comment by nextgenusfs** [comment]
`--busco_db` is not an option for `funannotate update`.  All commands/modules have help menus, just run with `-h` flag.
