### ISSUE TITLE
Problems with funannotate update

### ISSUE THREAD

**Issue by DiegoSafian** [nextgenusfs/funannotate#856]
**Are you using the latest release?**
funannotate               1.8.14 

**Describe the bug**
The funannotate update stops in "Quality trimmed reads" despite I used   --no_trimmomatic 

**What command did you issue?**
funannotate update --fasta /camp/home/safiand/home/users/safiand/genome_annotation/turneri/GCA_922788865.1_HVK001PTURNERI_genomic.shortID.fna --species turneri_up \
	  --gff turneri_tsebr.gff3 \
	  --trinity trinity-GG.fasta \
	  --no_trimmomatic \
	  --left R1.fastq \
	  --right R2.fastq \
	  --pasa_db sqlite --cpus 32 \
	  --out update

**Logfiles**
[01/11/23 09:09:53]: Trimmomatic will be skipped
[01/11/23 09:09:53]: Quality trimmed reads: ('update/update_misc/left.fq.gz', 'update/update_misc/right.fq.gz', None)
[01/11/23 09:09:53]: Trimmomatic failed, update/update_misc/left.fq.gz does not exist.

**Comment by DiegoSafian** [comment]
Solved!

**Comment by nextgenusfs** [comment]
Glad you got it sorted, might be helpful for others to post how you solved it.

**Comment by DiegoSafian** [comment]
The problem was solved by re-installed funnanotate using` conda install funannotate `insted of `conda install -c bioconda funannotate`
