### ISSUE TITLE
annotations.GO.txt not in annotate_misc folder anymore?

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#86]
In 0.6.1 seems that `annotations.GO.txt` file is not saved to misc folder anymore (or removed after run)? while GO annotations are ok and present in final gff/gbk files and also all.annotations.txt
and also IPR misc files not saved anymore?

**Comment by nextgenusfs** [comment]
The method I was using to parse InterProScan results changed in v0.6.1, previously I was getting GO and InterPro in 2 steps hence the two different files.  It is much more efficient in the current version and results in just a single annotation file (annotations.iprscan.txt).

**Comment by MichaelFokinNZ** [comment]
Sorry, I've just realised that since you parse go_terms from InterProScan there are no GO numbers in funannotate pipeline. Why not to include full EggNOG4.5 which seems to have both GO and KEGG annotations?
I've already supplied my funannotate runs with KEGG annot, need GOs now. Do you know may be a smart way to get them from NOG numbers?
