### ISSUE TITLE
Which is the ultimate Augustus version that works with the latest funannotate?

### ISSUE THREAD

**Issue by BrigidaGallone** [nextgenusfs/funannotate#866]
Hello,
I am struggling with Funannotate installation for a while and was hoping you could help me figuring it out how to make it work. For the installation I followed exactly the installation guide and used conda. 

**Are you using the latest release?**
Yes, version v1.8.13 installed via conda a week ago.

**Describe the bug**
During the test run: funannotate test -t predict --cpus ${SLURM_CPUS_PER_TASK} 

The step predict fails with error:
[Feb 10 03:26 PM]:
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.

The error is the same as issue [https://github.com/nextgenusfs/funannotate/issues/776](url) but after a lot of trials and errors it is unclear to me which Augustus version and file (locally/in conda/etc.) to use to run the latest version of funannotate.

**What command did you issue?**
funannotate test -t predict --cpus ${SLURM_CPUS_PER_TASK} 

**Logfiles**
![Screenshot 2023-02-13 at 09 54 38](https://user-images.githubusercontent.com/103991824/218415445-caa25aab-8fee-4bd8-85e7-1867681fb28c.png)

**OS/Install Information**
Checking dependencies for 1.8.13
-------------------------------------------------------
You are running Python v 3.8.15. Now checking python packages...
biopython: 1.80
goatools: 1.2.3
matplotlib: 3.4.3
natsort: 8.2.0
numpy: 1.24.1
pandas: 1.5.3
psutil: 5.9.4
requests: 2.28.2
scikit-learn: 1.2.1
scipy: 1.10.0
seaborn: 0.12.2
All 11 python packages installed

You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.38
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.855
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.54
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.12
YAML: 1.30
threads: 2.25
threads::shared: 1.61
   ERROR: local::lib not installed, install with cpanm local::lib

Checking Environmental Variables...
$FUNANNOTATE_DB=/data1/bgallone/funannotate/funannotate_db
$PASAHOME=/data1/bgallone/conda/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/data1/bgallone/conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/data1/bgallone/conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/data1/bgallone/conda/envs/funannotate/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.5.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.0.15
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2021-08-25
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 17.0.3-internal
kallisto: 0.46.1
mafft: v7.515 (2023/Jan/15)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
proteinortho: 6.1.7
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.16.1
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.11 (Oct 2022)
tantan: tantan 40
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: gmes_petap.pl not installed
	ERROR: pigz not installed
	ERROR: signalp not installed

**Comment by nextgenusfs** [comment]
With funannotate v1.8.13 you have to use Augustus < 3.4.

**Comment by BrigidaGallone** [comment]
Thank you very much for your help! I will try that and close the issue for the moment.
