### ISSUE TITLE
funannotate annotation error | TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by hafizmtalha** [nextgenusfs/funannotate#870]
I am using funannotate annotation step. and facing this issue.. just cant figure out what's this about ??
comand I used was:
funannotate annotate -i magnaporthprediction --cpus 12

[Feb 27 03:14 AM]: EggNog version parsed as 2.1.10
Traceback (most recent call last):
  File "/home/navi/anaconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/navi/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/navi/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 828, in main
    EggNog = parseEggNoggMapper(eggnog_result, eggnog_out, GeneProducts)
  File "/home/navi/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 250, in parseEggNoggMapper
    Description = cols[Desci].split('. ')[0]
TypeError: list indices must be integers or slices, not NoneType

**Comment by hyphaltip** [comment]
this is likely a mismatch between the eggnog version you have installed and the version of funannotate - rae you running latest version of funannotate from github?

**Comment by hafizmtalha** [comment]
> this is likely a mismatch between the eggnog version you have installed and the version of funannotate - rae you running latest version of funannotate from github?

I installed funannotate using conda. I hope its the latest one..!
I am using funannotate version 1.8.13

**Comment by hyphaltip** [comment]
you can try upgrading to latest version which isn't in an official release after you have loaded funannotate env
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git —upgrade —force —no-deps
```
Beyond that I'd suggest looking at the eggnog result files in the annotate_misc folder and make sure they aren't empty or something like that or any other failure reported.

**Comment by hafizmtalha** [comment]
> you can try upgrading to latest version which isn't in an official release after you have loaded funannotate env
> 
> ```
> python -m pip install git+https://github.com/nextgenusfs/funannotate.git —upgrade —force —no-deps
> ```
> 
> Beyond that I'd suggest looking at the eggnog result files in the annotate_misc folder and make sure they aren't empty or something like that or any other failure reported.

Thanks alot. updating funannotate worked for me..!!!

**Comment by charlesfeigin** [comment]
Hi, I've run into a similar error:

Traceback (most recent call last):
  File "/data/home/cfeigin/anaconda3_2022.10/envs/mamba_base/envs/funannotate3/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/data/home/cfeigin/anaconda3_2022.10/envs/mamba_base/envs/funannotate3/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/data/home/cfeigin/anaconda3_2022.10/envs/mamba_base/envs/funannotate3/lib/python3.8/site-packages/funannotate/annotate.py", line 836, in main
    EggNog = parseEggNoggMapper(eggnog_result, eggnog_out, GeneProducts)
  File "/data/home/cfeigin/anaconda3_2022.10/envs/mamba_base/envs/funannotate3/lib/python3.8/site-packages/funannotate/annotate.py", line 254, in parseEggNoggMapper
    Description = cols[Desci].split('. ')[0]
TypeError: list indices must be integers or slices, not NoneType

I am running 

funannotate v1.8.14

emapper-2.1.10 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Diamond version found: diamond version 2.0.15 / MMseqs2 version found: 113e3212c137d026e297c7540e1fcd039f6812b1

**Comment by nextgenusfs** [comment]
What does the header look like in the eggnog output file? `outdir/annotate_misc/eggnog.emapper.annotations`

**Comment by caioald** [comment]
Hi @nextgenusfs, I have bumped in a very similar error when annotating my results running `funannotate v1.8.13` and `emapper-2.1.10 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Diamond version found: diamond version 2.1.6 / MMseqs2 version found: 14.7e284`


`funannotate annotate -i VSF810_predict --cpus 40`

`[Mar 30 10:02 PM]: OS: CentOS Linux 7, 40 cores, ~ 198 GB RAM. Python: 3.8.15
[Mar 30 10:02 PM]: Running 1.8.13
[Mar 30 10:02 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Mar 30 10:02 PM]: Found existing output directory VSF810_predict. Warning, will re-use any intermediate files found.
[Mar 30 10:02 PM]: Parsing input files
[Mar 30 10:02 PM]: Existing tbl found: VSF810_predict/predict_results/Candida_parapsilosis.tbl
[Mar 30 10:02 PM]: Adding Functional Annotation to Candida parapsilosis, NCBI accession: None
[Mar 30 10:02 PM]: Annotation consists of: 5,786 gene models
[Mar 30 10:02 PM]: 5,682 protein records loaded
[Mar 30 10:02 PM]: Existing Pfam-A results found: VSF810_predict/annotate_misc/annotations.pfam.txt
[Mar 30 10:02 PM]: 7,503 annotations added
[Mar 30 10:02 PM]: Running Diamond blastp search of UniProt DB version 2023_01
[Mar 30 10:02 PM]: 1,202 valid gene/product annotations from 1,280 total
[Mar 30 10:02 PM]: Existing Eggnog-mapper results found: VSF810_predict/annotate_misc/eggnog.emapper.annotations
[Mar 30 10:02 PM]: Parsing EggNog Annotations
[Mar 30 10:02 PM]: EggNog version parsed as 2.1.10
Traceback (most recent call last):
  File "/home/projects/ku_00099/apps/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/projects/ku_00099/apps/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/projects/ku_00099/apps/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 828, in main
    EggNog = parseEggNoggMapper(eggnog_result, eggnog_out, GeneProducts)
  File "/home/projects/ku_00099/apps/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 250, in parseEggNoggMapper
    Description = cols[Desci].split('. ')[0]
TypeError: list indices must be integers or slices, not NoneType
`


Here what my `outdir/annotate_misc/eggnog.emapper.annotations` looks like (omitting dome GO terms to reduce the text) :

`## Thu Mar 30 21:38:25 2023
## emapper-2.1.10
## /home/projects/ku_00099/apps/funannotate/bin/emapper.py -m diamond -i /home/projects/ku_00099/data/Caio/yeasts/funannotate/VSF810/VSF810_predict/annotate_misc/genome.proteins.fasta -o eggnog --cpu 40 --scratch_dir /tmp/emapper-080bc977 --temp_dir /tmp --dbmem
##
#query	seed_ortholog	evalue	score	eggNOG_OGs	max_annot_lvl	COG_category	Description	Preferred_name	GOs	EC	KEGG_ko	KEGG_Pathway	KEGG_Module	KEGG_Reaction	KEGG_rclass	BRITE	KEGG_TC	CAZy	BiGG_Reaction	PFAMs
FUN_000001-T1	340170.XP_007375071.1	2.15e-17	83.6	2CMHS@1|root,2QQD8@2759|Eukaryota,38EH2@33154|Opisthokonta,3NVXI@4751|Fungi,3QPBT@4890|Ascomycota,3RRKJ@4891|Saccharomycetes,47AWQ@766764|Debaryomycetaceae	4751|Fungi	S	to Saccharomyces cerevisiae	PIR3	GO:0003674,GO:0003824,GO:0005198,GO:0005199	-	-	-	-	-	-	-	-	-	-	PIR
FUN_000002-T1	5480.G8BFC1	1.13e-133	384.0	COG5137@1|root,KOG3265@2759|Eukaryota,3991X@33154|Opisthokonta,3NXBX@4751|Fungi,3QQ5R@4890|Ascomycota,3RSX1@4891|Saccharomycetes,47AUJ@766764|Debaryomycetaceae	4751|Fungi	K	Histone chaperone that facilitates histone deposition and histone exchange and removal during nucleosome assembly and disassembly	ASF1	GO:0000228,GO:0000785,GO:0000790,GO:0001932	-	ko:K10753	-	-	-	-	ko00000,ko03036	-	-	-	ASF1_hist_chap
FUN_000003-T1	5480.G8BFC2	0.0	912.0	29GNU@1|root,2RPV4@2759|Eukaryota,38TK5@33154|Opisthokonta,3PV8M@4751|Fungi,3REEQ@4890|Ascomycota,3RWQI@4891|Saccharomycetes,47CQN@766764|Debaryomycetaceae	4751|Fungi	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-
FUN_000004-T1	273371.XP_003869188.1	2.95e-287	789.0	COG0679@1|root,KOG2722@2759|Eukaryota,38EXJ@33154|Opisthokonta,3NUHS@4751|Fungi,3QKKD@4890|Ascomycota,3RRRP@4891|Saccharomycetes,479CX@766764|Debaryomycetaceae	4751|Fungi	S	Membrane transport protein	-	GO:0003674,GO:0005215,GO:0005575,GO:0005622	-	ko:K07088	-	-	-	-	ko00000	-	-	-	Mem_trans
FUN_000005-T1	5480.G8BFC4	0.0	1455.0	2CF1Y@1|root,2SVEY@2759|Eukaryota,3AQDD@33154|Opisthokonta,3PGHT@4751|Fungi,3R4JF@4890|Ascomycota,3RWDQ@4891|Saccharomycetes,47BDM@766764|Debaryomycetaceae	4751|Fungi	S	GAL4-like Zn(II)2Cys6 (or C6 zinc) binuclear cluster DNA-binding domain	-	-	-	-	-	-	-	-	-	-	-	-	Zn_clus
`

Thanks in advance!

**Comment by caioald** [comment]
Found the issue:
In annotate.py line 192 an underscore is missing in eggNOG OGs
`DBi = item2index(headerCols, 'eggNOG_OGs') #Caio_mod_from: 'eggNOG OGs'`

**Comment by nextgenusfs** [comment]
That is actually not a bug, as older versions of eggnog had that in header: https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.2-v2.0.8#user-content-Annotations_file

versions newer than v2.1.2, should be using the other parser here: https://github.com/nextgenusfs/funannotate/blob/master/funannotate/annotate.py#L276

Logic around the versions for header parsing is here: 
https://github.com/nextgenusfs/funannotate/blob/master/funannotate/annotate.py#L322-L328

**Comment by caioald** [comment]
I used emapper v.2.1.1 and all the others cols agreed with the `getEggNogHeadersv2` function, but the `DBi`, it was with a underscore as in v2.1.2+
Maybe it was only in that version?

Anyways, I've changed the code in my server and it worked.

Thanks for this great tool!

**Comment by nextgenusfs** [comment]
There was a bug in the version detection that was recently fixed, so perhaps that's why it worked.
