### ISSUE TITLE
Malformed GFF file for funannotate annotate 

### ISSUE THREAD

**Issue by MesYosra** [nextgenusfs/funannotate#873]
funannotate v1.8.13

Hello,
I am trying to get funannotate annotate to work on my data with the command :  
funannotate annotate --gff "/shared/home/ymestiri/projects/annotation_fusarium/yosra/Funannotate/UK0001. gff3" --fasta "/shared/home/ymestiri/projects/annotation_fusarium/yosra/Funannotate/UK0001.fasta" --iprscan "/shared/home/ymestiri/projects/annotation_fusarium/yosra/Funannotate/UK0001_gene. fasta.xml" -d "/shared/home/ymestiri/projects/annotation_fusarium/yosra/Funannotate/FUNANNOTATE_DB" --species "Pseudocercospora fijiensis" --cpus 10 -o "/shared/home/ymestiri/projects/annotation_fusarium/yosra/Funannotate/annotated/".
. I have an error :

 "Error, can't find ID or Parent. GFF file malformed.
VMNF01000004.1 BRAKER CDS 1600277 1601047 0.91 + 0 Parent=jg4615T0" 
some examples from the gff3 file below

**Comment by MesYosra** [comment]
VMNF01000004.1	BRAKER	gene	1600277	1601863	.	+	.	ID=jg4615;Name=jg4615
VMNF01000004.1	BRAKER	mRNA	1600277	1601863	.	+	.	ID=jg4615T0;Parent=jg4615
VMNF01000004.1	BRAKER	start_codon	1600277	1600279	.	+	0	Parent=jg4615T0
VMNF01000004.1	BRAKER	CDS	1600277	1601047	0.91	+	0	Parent=jg4615T0
VMNF01000004.1	BRAKER	CDS	1601095	1601322	1	+	0	Parent=jg4615T0
VMNF01000004.1	BRAKER	CDS	1601372	1601863	1	+	0	Parent=jg4615T0
VMNF01000004.1	BRAKER	stop_codon	1601861	1601863	.	+	0	Parent=jg4615T0
VMNF01000013.1	BRAKER	gene	206335	208048	.	-	.	ID=jg9620;Name=jg9620
VMNF01000013.1	BRAKER	mRNA	206335	208048	.	-	.	ID=jg9620T0;Parent=jg9620
VMNF01000013.1	BRAKER	stop_codon	206335	206337	.	-	0	Parent=jg9620T0
VMNF01000013.1	BRAKER	CDS	206335	206466	0.83	-	0	Parent=jg9620T0
VMNF01000013.1	BRAKER	CDS	206522	208048	0.59	-	0	Parent=jg9620T0
VMNF01000013.1	BRAKER	start_codon	208046	208048	.	-	0	Parent=jg9620T0
VMNF01000009.1	BRAKER	gene	2697787	2699947	.	-	.	ID=jg9030;Name=jg9030
VMNF01000009.1	BRAKER	mRNA	2697787	2699947	.	-	.	ID=jg9030T0;Parent=jg9030
VMNF01000009.1	BRAKER	stop_codon	2697787	2697789	.	-	0	Parent=jg9030T0
VMNF01000009.1	BRAKER	CDS	2697787	2697818	1	-	2	Parent=jg9030T0
VMNF01000009.1	BRAKER	CDS	2697873	2698858	1	-	1	Parent=jg9030T0
VMNF01000009.1	BRAKER	CDS	2698907	2699601	1	-	0	Parent=jg9030T0
VMNF01000009.1	BRAKER	CDS	2699659	2699869	1	-	1	Parent=jg9030T0
VMNF01000009.1	BRAKER	CDS	2699925	2699947	1	-	0	Parent=jg9030T0
VMNF01000009.1	BRAKER	start_codon	2699945	2699947	.	-	0	Parent=jg9030T0
VMNF01000003.1	BRAKER	gene	3603034	3607860	.	-	.	ID=jg7817;Name=jg7817
VMNF01000003.1	BRAKER	mRNA	3603034	3607860	.	-	.	ID=jg7817T0;Parent=jg7817
VMNF01000003.1	BRAKER	stop_codon	3603034	3603036	.	-	0	Parent=jg7817T0
VMNF01000003.1	BRAKER	CDS	3603034	3605124	1	-	0	Parent=jg7817T0
VMNF01000003.1	BRAKER	CDS	3605186	3605259	0.84	-	2	Parent=jg7817T0
VMNF01000003.1	BRAKER	CDS	3607176	3607860	0.96	-	0	Parent=jg7817T0
VMNF01000003.1	BRAKER	start_codon	3607858	3607860	.	-	0	Parent=jg7817T0
VMNF01000007.1	BRAKER	gene	5465290	5467137	.	+	.	ID=jg1690;Name=jg1690
VMNF01000007.1	BRAKER	mRNA	5465290	5467137	.	+	.	ID=jg1690T0;Parent=jg1690
VMNF01000007.1	BRAKER	start_codon	5465290	5465292	.	+	0	Parent=jg1690T0
VMNF01000007.1	BRAKER	CDS	5465290	5465397	0.47	+	0	Parent=jg1690T0
VMNF01000007.1	BRAKER	CDS	5465449	5466010	0.99	+	0	Parent=jg1690T0
VMNF01000007.1	BRAKER	CDS	5466056	5466622	1	+	2	Parent=jg1690T0
VMNF01000007.1	BRAKER	CDS	5466674	5466849	1	+	2	Parent=jg1690T0
VMNF01000007.1	BRAKER	CDS	5466919	5467137	1	+	0	Parent=jg1690T0
VMNF01000007.1	BRAKER	stop_codon	5467135	5467137	.	+	0	Parent=jg1690T0

**Comment by nextgenusfs** [comment]
The error message should be obvious?  The sub features (CDS) do not have ID= field in column 9.
