### ISSUE TITLE
[QUESTION] (not a bug) How can I change the locus ID's after the fact?

### ISSUE THREAD

**Issue by DaRinker** [nextgenusfs/funannotate#886]
I would like to update the locus IDs in my funannotate.out directory 

Will I break anything thing if I just do a global find/replace (e.g. sed -i 's/FUN_/Mynewprefix_/g' )?

**Comment by hyphaltip** [comment]
probably will be fun, but you can also run `funannotate annotate` with the `--rename` option 
https://funannotate.readthedocs.io/en/latest/annotate.html
