### ISSUE TITLE
iprscan.xml not-reused

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#89]
Seems like if there is already a completed annotate_misc/iprscan.xml (either done external from funannotate or from a prior run) it isn't being detected and the ipscan is run again. If you specify the --iprscan PATHTOFILE/iprscan.xml then it uses it. I assume there is just a missing logic step to check for this file in the annotate_misc/iprscan.xml  ? I can look but it may be faster for you to find it @nextgenusfs ?

**Comment by nextgenusfs** [comment]
Logic has been changed at this step, hopefully this is fixed, if not reopen. 51c8788a38b0d1ed9ec053fb13510fe6bcf16335
