### ISSUE TITLE
Inconsistent reslults with dbCAN

### ISSUE THREAD

**Issue by caonetto** [nextgenusfs/funannotate#890]
I am getting some inconsistent results on the annotation of cazymes. Ive manually annotated using the dbCAN server a protein that corresponds to the GH31 group, and the e-value of the hit is 2.2e-122. Ive noticed from the source code of funannotate that the cut-off during hmmscan is 1e-17, however this protein is not getting annotated as part of GH31. 
I have manually annotated the protein using the hmmer database that is downloaded for funannotate and the hit is actually there however is not getting passed through to the final output.
This is the score output when running hmmscan manually with the same commands as funannotate,
GH31                 -            427 wild87red_001881-T1  -            987  2.3e-151  499.9   3.6   1   2       0.1        67   -2.5   0.0    50    89   237   275   220   287 0.75 -
GH31                 -            427 wild87red_001881-T1  -            987  2.3e-151  499.9   3.6   2   2  3.6e-154  2.3e-151  499.9   3.6     3   427   418   859   416   859 0.97 -

The txt file "annotations.dbCAN.txt" located in the annotate_misc folder does not contain this hit.

Any ideas on what could be going on?

Thanks.

**Comment by nextgenusfs** [comment]
Originally with dbCAN there was post evalue filtering, which was if coverage of the hit was less than 45% than to drop it (Note I wrote this probably 5 years ago, so completely plausible that dbCAN post filtering should be re-evaluated). The code running hmmer-dbCAN is here: https://github.com/nextgenusfs/funannotate/blob/fea594ca5572c4b0a6cc3e794127765e85b86471/funannotate/aux_scripts/hmmer_parallel.py#L104-L161

Okay so I had a look here: https://bcb.unl.edu/dbCAN2/help.php.  Seems that we should now be running evalue of 1e-15 and filtering at 35% coverage. I will make the changes.

**Comment by hyphaltip** [comment]
this is fixed with commit [036c9d6](https://github.com/nextgenusfs/funannotate/commit/036c9d60f371f295dc7eeb502d4b05809485ab1a)
