### ISSUE TITLE
Trinity fails at read normalization of paired end data

### ISSUE THREAD

**Issue by geennaam400** [nextgenusfs/funannotate#891]
Funannotate version 1.8.13
Trinity version 2.8.5

Hi, I am training funannotate with paired end RNAseq data I got from SRA. I already added /1 and /2 to the read names, got rid of the headers in the + line of the fastq files, and made sure to use short and concise read names without spaces or weird characters, so Trimmomatic ran successfully. However, somehow trinity cannot inherit this paired-end data correctly because in the last lines of the trinity_normalization.PE.log the following error is shown (illegal division by zero) during normalization. Trinity normalization _did_ ran normally for the single end RNA reads. 
Any tips or tricks? Thanks! See error below:

CMD: /home/yvet/anaconda3/envs/funannotate/opt/trinity-2.8.5/util/..//util/support_scripts//nbkc_normalize.pl --stats_file pairs.K25.stats --max_cov 50  --min_cov 5 --max_CV 10000 > pairs.K25.stats.C50.maxCV10000.accs
Illegal division by zero at /home/yvet/anaconda3/envs/funannotate/opt/trinity-2.8.5/util/..//util/support_scripts//nbkc_normalize.pl line 111.
Error, cmd: /home/yvet/anaconda3/envs/funannotate/opt/trinity-2.8.5/util/..//util/support_scripts//nbkc_normalize.pl --stats_file pairs.K25.stats --max_cov 50  --min_cov 5 --max_CV 10000 > pairs.K25.stats.C50.maxCV10000.accs died with ret 65280 at /home/yvet/anaconda3/envs/funannotate/opt/trinity-2.8.5/util/insilico_read_normalization.pl line 788.

-------------------------------------------------------
Checking dependencies for 1.8.13
-------------------------------------------------------
You are running Python v 3.8.15. Now checking python packages...
biopython: 1.80
goatools: 1.2.3
matplotlib: 3.4.3
natsort: 8.2.0
numpy: 1.24.0
pandas: 1.5.2
psutil: 5.9.4
requests: 2.28.1
scikit-learn: 1.2.0
scipy: 1.9.3
seaborn: 0.12.1
All 11 python packages installed

You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.50
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.855
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.54
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.12
YAML: 1.30
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/yvet/downloads/funannotate_db
$PASAHOME=/home/yvet/anaconda3/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/home/yvet/anaconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/yvet/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/yvet/anaconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/yvet/downloads/gmes_linux_64_4
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.4.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.0.15
emapper.py: There was an error retrieving eggnog-mapper DB data: not a valid file "/home/yvet/anaconda3/envs/funannotate/lib/python3.8/site-packages/data/eggnog.db"
Maybe you need to run download_eggnog_data.py
emapper-2.1.10 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Diamond found: diamond 2.0.15 / MMseqs2 found: 13.45111

ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2021-08-25
gmes_petap.pl: 4.71_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 17.0.3-internal
kallisto: 0.46.1
mafft: v7.508 (2022/Sep/07)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
pigz: pigz 2.6
proteinortho: 6.1.6
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.16.1
signalp: 4.1
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.11 (Oct 2022)
tantan: tantan 40
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 37 external dependencies are installed

**Comment by nextgenusfs** [comment]
For SRA I've just done what Trinity developers suggested: https://github.com/trinityrnaseq/trinityrnaseq/wiki/How-do-I-use-reads-I-downloaded-from-SRA%3F

**Comment by hyphaltip** [comment]
AFAIK usually the mis-formatted IDs caused a failure earlier than this - I think there might be something else not working in your files as this is a divide by zero saying that median coverage was not properly calculated - you might try to see if something else in the error logs or run the command alone.

**Comment by geennaam400** [comment]
Thanks, I managed to fix it by adapting my raw data further!

**Comment by bpeacock44** [comment]
Hi @yvetboele - do you mind sharing what you did to adapt your raw data? I am having a similar error with one of my datasets. Thank you!

**Comment by gchevignon** [comment]
> Thanks, I managed to fix it by adapting my raw data further!

Hello @yvetboele can you please give us more detail on how you adapted your data, please ? Because I got the same error and I am not sure what modification I have to do to fix it ...

Best
Germain
