### ISSUE TITLE
funannotate sort --minlen not working

### ISSUE THREAD

**Issue by abretaud** [nextgenusfs/funannotate#896]
**Are you using the latest release?**
using master branch

**Describe the bug**
the --minlen option of `funannotate sort` isno longer working (writing smaller contigs)

**What command did you issue?**
`funannotate sort --input input.fa --out output.fa --base 'something' --minlen 2100`

The if/else logic is not working as expected after recent refactoring at https://github.com/nextgenusfs/funannotate/blob/afeeb4d49ea00aad3bd25590cf66edd9575e237f/funannotate/sort.py#L36

**Comment by hyphaltip** [comment]
I can fix that - you can also use AAFTF for sorting.

**Comment by abretaud** [comment]
Thanks, the fix works!
