### ISSUE TITLE
Strain not Isolate

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#90]
I'd rather use "strain" instead of "isolate" for the organism identifier information since am submitted data for genomes of strains from a culture collection.

This doesn't seem to be the case with the cmdline switch - I've had to go back in and adjust the tbl file and rerun tbl2asn to get this updated for my final annotations. Is this something we can allow for switching in funannotate or will require additional coding?

**Comment by nextgenusfs** [comment]
now supported in v0.7.0, also added the -T flag to tbl2asn by default. 51c8788a38b0d1ed9ec053fb13510fe6bcf16335
