### ISSUE TITLE
Pasa gff not working

### ISSUE THREAD

**Issue by caioald** [nextgenusfs/funannotate#902]
I'm not sure if I'm doing the right thing when adding pasa_gff to my funannotate run.

When I run the predict command (as below), I get stuck in the `gff_to_gtf` function in `library.py`, which returns an empty `pasa.training.tmp.gtf` file, and consequently won't move forward with augustus training.

`funannotate predict -i ${GMASKED} -o ${ASSEMBLY}_predict -s "LgAc2012" \
    --transcript_evidence $TRANS --rna_bam $BAM --cpus $NPROCS --pasa_gff pasa.gff3
`

If I use pasa.transdecoder.gff3 it will not link the Trinity transcripts header to the genome's headers, thus:
`library.py line 4223: if not contig in SeqRecords:` will be true for all the records and the file will be empty.
`head Trinity-GG.fasta.transdecoder.gff3
TRINITY_GG_1001_c0_g1_i1        transdecoder    gene    1       1625    .       +       .       ID=TRINITY_GG_1001_c0_g1~~TRINITY_GG_1001_c0_g1_i1.p2;Name="ORF type:complete (+),score=29.57"
TRINITY_GG_1001_c0_g1_i1        transdecoder    mRNA    1       1625    .       +       .       ID=TRINITY_GG_1001_c0_g1_i1.p2;Parent=TRINITY_GG_1001_c0_g1~~TRINITY_GG_1001_c0_g1_i1.p2;Name="ORF type:complete (+),score=29.57"
TRINITY_GG_1001_c0_g1_i1        transdecoder    five_prime_UTR  1       111     .       +       .       ID=TRINITY_GG_1001_c0_g1_i1.p2.utr5p1;Parent=TRINITY_GG_1001_c0_g1_i1.p2
TRINITY_GG_1001_c0_g1_i1        transdecoder    exon    1       1625    .       +       .       ID=TRINITY_GG_1001_c0_g1_i1.p2.exon1;Parent=TRINITY_GG_1001_c0_g1_i1.p2
TRINITY_GG_1001_c0_g1_i1        transdecoder    CDS     112     885     .       +       0       ID=cds.TRINITY_GG_1001_c0_g1_i1.p2;Parent=TRINITY_GG_1001_c0_g1_i1.p2
`

If I use pasa results from one of the aligners, the only feature I have is cDNA_match, thus:
`library.py line 4218: if feature not in [...]` will be true for all the records and the file will be empty.

`head Ac2012.sqlite.valid_gmap_alignments.gff3
contig_1030     gmap-Ac2012.sqlite      cDNA_match      5467    6659    86      -       .       ID=align_79384;Target=TRINITY_GG_8_c0_g1_i49 1 1036 +
contig_1030     gmap-Ac2012.sqlite      cDNA_match      5467    6659    81      -       .       ID=align_79385;Target=TRINITY_GG_8_c0_g1_i62 1 975 +
contig_1179     gmap-Ac2012.sqlite      cDNA_match      3302    3804    100     -       .       ID=align_79386;Target=TRINITY_GG_4_c0_g1_i1 1 503 +
contig_1179     gmap-Ac2012.sqlite      cDNA_match      11815   12072   99      -       .       ID=align_79387;Target=TRINITY_GG_2_c0_g1_i1 1 258 +
contig_1179     gmap-Ac2012.sqlite      cDNA_match      9547    9946    100     -       .       ID=align_79388;Target=TRINITY_GG_1_c0_g1_i1 1 400 +
contig_952      gmap-Ac2012.sqlite      cDNA_match      2400    4336    87      -       .       ID=align_79389;Target=TRINITY_GG_7_c0_g1_i34 1 1686 +
`

If I use pasa_assemblies.gff3, I have both previous problems:

`head Ac2012.sqlite.pasa_assemblies.gff3
contig_10       assembler-Ac2012.sqlite cDNA_match      20099   20457   .       +       .       ID=align_160335;Target=asmbl_1 1 359 +
contig_10       assembler-Ac2012.sqlite cDNA_match      20449   20747   .       +       .       ID=align_160336;Target=asmbl_2 1 299 +
contig_10       assembler-Ac2012.sqlite cDNA_match      26178   26424   .       -       .       ID=align_160337;Target=asmbl_3 1 247 +
contig_10       assembler-Ac2012.sqlite cDNA_match      28843   29141   .       +       .       ID=align_160338;Target=asmbl_4 1 299 +
contig_10       assembler-Ac2012.sqlite cDNA_match      29720   29953   .       +       .       ID=align_160339;Target=asmbl_5 1 234 +
contig_10       assembler-Ac2012.sqlite cDNA_match      30557   30825   .       +       .       ID=align_160340;Target=asmbl_6 1 269 +
`

Am I running pasa properly?
`$PASAHOME/Launch_PASA_pipeline.pl -c pasa.alignAssembly.txt \
    -C -R -r --ALT_SPLICE -g $MASKED_GENOME -T $TRANSCRIPTS --CPU $NPROCS \
    --ALIGNERS blat,gmap --stringent_alignment_overlap 30.0 --TRANSDECODER
`

**Comment by nextgenusfs** [comment]
You want the PASA transdecoder genome GFF3 file, ie should end in `.assemblies.fasta.transdecoder.genome.gff3`

**Comment by caioald** [comment]
Ah, ok. I was not figuring out how to get this file.
I will leave it here in case someone needs this in the future and close the issue.

Thanks again.

After running my pasa command above I ran:
```
$PASAHOME/scripts/pasa_asmbls_to_training_set.dbi --pasa_transcripts_fasta ${ASSEMBLY}.sqlite.assemblies.fasta \
--pasa_transcripts_gff3 ${ASSEMBLY}.sqlite.pasa_assemblies.gff3
```

This command output `${ASSEMBLY}.sqlite.assemblies.fasta.transdecoder.genome.gff3` to use as `--pasa_gff`
