### ISSUE TITLE
ERROR: dependencies not installed

### ISSUE THREAD

**Issue by lukaskon** [nextgenusfs/funannotate#915]
I just installed the latest version of funannote via conda and have dependency issues below. Any advice? 

Checking dependencies for 1.8.15
-------------------------------------------------------
You are running Python v 3.8.13. Now checking python packages...
biopython: 1.79
goatools: 1.2.3
matplotlib: 3.4.3
natsort: 8.2.0
numpy: 1.23.4
pandas: 1.5.1
psutil: 5.9.4
requests: 2.28.1
scikit-learn: 1.1.3
scipy: 1.9.3
seaborn: 0.12.1
All 11 python packages installed

You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.50
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.858
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.54
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.12
YAML: 1.30
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed

Checking Environmental Variables...
$PASAHOME=/mnt/home/lukaskon/anaconda2/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/mnt/home/lukaskon/anaconda2/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/mnt/home/lukaskon/anaconda2/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/mnt/home/lukaskon/anaconda2/envs/funannotate/config/
        ERROR: FUNANNOTATE_DB not set. export FUNANNOTATE_DB=/path/to/dir
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
        ERROR: pslDnaFiler found but error running: pslCDnaFilter: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.5.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.31.0
blat: BLAT v36x2
diamond: 2.1.6
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2023-03-24
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 17.0.3-internal
kallisto: 0.46.1
mafft: v7.520 (2023/Mar/22)
makeblastdb: makeblastdb 2.13.0+
minimap2: 2.26-r1175
pigz: 2.6
proteinortho: 6.2.3
salmon: salmon 0.14.1
samtools: samtools 1.16.1
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.11 (Oct 2022)
tantan: tantan 40
tbl2asn: 25.8
tblastn: tblastn 2.13.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: gmes_petap.pl not installed
        ERROR: pslCDnaFilter not installed
        ERROR: signalp not installed

**Comment by lukaskon** [comment]
(funannotate) funannotate$ funannotate test -t all --cpus 12
#########################################################
Running `funannotate clean` unit testing: minimap2 mediated assembly duplications
Downloading: https://osf.io/8pjbe/download?version=1 Bytes: 252076                                                                       CMD: funannotate clean -i test.clean.fa -o test.exhaustive.fa --exhaustive
#########################################################
minimap2 version=2.26-r1175 path=/mnt/home/lukaskon/anaconda2/envs/funannotate/bin/minimap2
-----------------------------------------------
6 input contigs, 6 larger than 500 bp, N50 is 427,039 bp
Checking duplication of 6 contigs
-----------------------------------------------
scaffold_73 appears duplicated: 100% identity over 100% of the contig. contig length: 15153
scaffold_91 appears duplicated: 100% identity over 100% of the contig. contig length: 8858
scaffold_27 appears duplicated: 100% identity over 100% of the contig. contig length: 427039
-----------------------------------------------
6 input contigs; 6 larger than 500 bp; 3 duplicated; 3 written to file
#########################################################
SUCCESS: `funannotate clean` test complete.
#########################################################

#########################################################
Running `funannotate mask` unit testing: RepeatModeler --> RepeatMasker
Downloading: https://osf.io/hbryz/download?version=1 Bytes: 375687                                                        CMD: funannotate mask -i test.fa -o test.masked.fa --cpus 12
#########################################################
-------------------------------------------------------
[May 15 05:17 PM]: OS: CentOS Linux 7, 128 cores, ~ 1056 GB RAM. Python: 3.8.13
[May 15 05:17 PM]: Running funanotate v1.8.15
[May 15 05:17 PM]: Soft-masking simple repeats with tantan
[May 15 05:17 PM]: Repeat soft-masking finished:
Masked genome: /mnt/ufs18/home-054/lukaskon/anaconda2/envs/funannotate/test-mask_87413c55-a7bb-4bf9-94f3-6eeb6c32a2d5/test.masked.fa
num scaffolds: 2
assembly size: 1,216,048 bp
masked repeats: 50,965 bp (4.19%)
-------------------------------------------------------
#########################################################
SUCCESS: `funannotate mask` test complete.
#########################################################

#########################################################
Running `funannotate predict` unit testing                                                                                                                CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 12 --species Awesome testicus]]]]]]]]]]]]#########################################################
-------------------------------------------------------
[May 15 05:17 PM]: OS: CentOS Linux 7, 128 cores, ~ 1056 GB RAM. Python: 3.8.13
[May 15 05:17 PM]: Running funannotate v1.8.15
[May 15 05:17 PM]: Funannotate database not properly configured, run funannotate setup.
#########################################################
Traceback (most recent call last):
  File "/mnt/home/lukaskon/anaconda2/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/mnt/home/lukaskon/anaconda2/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/mnt/home/lukaskon/anaconda2/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 405, in main
    runPredictTest(args)
  File "/mnt/home/lukaskon/anaconda2/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 160, in runPredictTest
    assert 1500 <= countGFFgenes(os.path.join(
  File "/mnt/home/lukaskon/anaconda2/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-predict_87413c55-a7bb-4bf9-94f3-6eeb6c32a2d5/annotate/predict_results/Awesome_testicus.gff3'

**Comment by nextgenusfs** [comment]
Should be obvious from the error no? 
```
[May 15 05:17 PM]: Funannotate database not properly configured, run funannotate setup.
```
You have to install databases, the conda install message should have told you that. https://github.com/bioconda/bioconda-recipes/blob/master/recipes/funannotate/post-link.sh

And read the docs for more help. https://funannotate.readthedocs.io/en/latest/install.html#install

**Comment by lukaskon** [comment]
Ran setup again and all good now, sorry about confusion.
