### ISSUE TITLE
 Creating AGP file and corresponding contigs file error

### ISSUE THREAD

**Issue by el42008** [nextgenusfs/funannotate#92]
Hi, 

I got this error that I really do not know what is the issue:

Traceback (most recent call last):
  File "/mnt/apps/funannotate/bin/funannotate-functional.py", line 665, in <module>
    os.rename(log_name, os.path.join(outputdir, 'logfiles', log_name))
OSError: [Errno 16] Device or resource busy

Cheers

**Comment by nextgenusfs** [comment]
hmm, seems like a linux related error I don't see on my mac.  would suggest it can't move the file because it is still open.  will look into it.  This shouldn't have effected the output files I don't think as it is literally the last command in the script.

**Comment by nextgenusfs** [comment]
things have been moved around in v0.7.0, so this might be fixed.  reopen if you get the same problem.
