### ISSUE TITLE
Evaluation of gene models from funannotate

### ISSUE THREAD

**Issue by kushalsuryamohan** [nextgenusfs/funannotate#923]
Hello,
I am wondering if there is a systematic way to assess the quality of the annotations from funannotate predict?
I'd like to do something similar to what I used to do with the outputs of MAKER wherein I'd create gene models at each AED and then assess the % of RNA-seq reads that mapped to gene models as well as BUSCO completeness scores for each AED score (0.1-1.0).
Is this possible? I couldn't find a reference to AED in the outputs of funannotate predict unless I'm missing something very obvious.

Thanks for your help in advance!

**Comment by kushalsuryamohan** [comment]
Thanks @hyphaltip! This is a good start. Let me dig into the json files and also look at the tools you mentioned.
Closing this for now.

**Comment by nextgenusfs** [comment]
In terms of which gene models end up as the consensus prediction currently we rely on evidencemodeler to do this. It has an internal scoring system that honestly I'm not an expert on exactly how it works. But EVM can make hybrid type models do it's not always just a choice of which prediction to pick.
