### ISSUE TITLE
Add additional annotations with funannotate

### ISSUE THREAD

**Issue by lichen-fungus** [nextgenusfs/funannotate#926]
I am wondering if it would be possible to add annotations from pannzer2 software with funannotate? Thanks for helping.

**Comment by nextgenusfs** [comment]
You can add any custom annotations via `funannotate annotate -a` option, the data should be in a 3 column tab delimited file -- have a look at the `annotation_misc/all.annotations.txt` file to see what the format should be.  At this point, I'm not willing to add any more parsers or dependencies as I spend 99% of the time chasing moving targets as tools change format, etc.

**Comment by lichen-fungus** [comment]
Thanks for letting me know! I can imagine how much work it is to add more parsers. Anyways, I am using your software a lot. It's great, congratulations.
