### ISSUE TITLE
Repeatmasker failed

### ISSUE THREAD

**Issue by kramergj** [nextgenusfs/funannotate#94]
Hi there,

I seem to be having an issue with repeatmasking.  

`funannotate predict -masked_genome mygenome.fasta --species "species_name" -o test_maker --repeatmasker_gff3 mygenome.gff --cpus 4`

`[05:53:18 AM]: Running funannotate v0.6.2
[05:53:23 AM]: AUGUSTUS (3.2.1) detected, version seems to be compatible with BRAKER1 and BUSCO
[05:53:23 AM]: Loading sequences and soft-masking genome
[05:53:23 AM]: Soft-masking: building RepeatModeler database
[05:53:24 AM]: Soft-masking: generating repeat library using RepeatModeler
Soft-masking: running RepeatMasker with default library (RepeatModeler found 0 models)
[05:59:04 AM]: RepeatMasking failed, check log files.`

First off, where do I find the log files?

Secondly, although I would love to be able to entirely annotate a genome on funannotate and compare the results, my primary goal here is to really clean-up a genome that has been annotated with maker for NCBI submission.  Would it be possible for me to entirely bypass the repeatmasker step?  I know that this question was raised here (https://github.com/nextgenusfs/funannotate/issues/25), but I am not entirely sure how to implement those options.

Thank you in advance for your help.

**Comment by nextgenusfs** [comment]
The logfiles are located in the output directory in a subfolder called `logfiles` - the one for repeat masking should be obvious.  You can run RepeatMasker independent of funannotate, i.e.
 ```
RepeatMasker -species some_tax -e rmblast -xsmall yourgenome.fasta
```  
Then you need to convert the output to gff3 like this: 
```
rmOutToGFF3.pl repeatmasker.out > genome.repeatmasker.gff3
```
 Finally you can pass that to funannotate like this:
```
funannotate predict --masked_genome repeatmasked.fa \
--repeatmasker_gff3 genome.repeatmasker.gff3 -o test -s "Your species" --cpus X
```
If you want to pass a Maker GFF3, you can use the `--maker_gff` option which will use gene predictions from maker and run them through evidence modeler.

I'm working on a major update right now, part of that update will be ability to specify a `-species` option to funannotate predict that will run these steps.

**Comment by kramergj** [comment]
Thank you, so I suppose I have a follow up question.  When you pass a maker GFF3 using the ` --maker_gff` option, should/does the program run repeatmasker?

So, I've been able to run repeatmasker outside of the program, but haven't been able to get the file to convert correctly to the gff to run funannotate independently.

However, I am a bit confused as I tried to run two very similar commands and got somewhat different output...I think?

The first one:
`funannotate-predict.py -i mysequence.fasta --maker_gff mysequence.gff -o test -s speciesname --cpus 2`
Which seemed to run EVM (this is what I want to happen!)
```
2017-06-29 23:36:08,510: OS: MacOSX 10.11.6, 4 cores, ~ 8 GB RAM. Python: 2.7.13
2017-06-29 23:36:08,668: Running funannotate v0.6.2
2017-06-29 23:36:12,576: AUGUSTUS (3.2.1) detected, version seems to be compatible with BRAKER1 and BUSCO
2017-06-29 23:36:16,577: Masked genome: 7 scaffolds; 33,618,380 bp; 0.00% repeats masked
2017-06-29 23:36:16,605: Parsing Maker2 GFF for use in EVidence Modeler
2017-06-29 23:36:16,606: /usr/local/opt/python/bin/python2.7 /usr/local/Cellar/funannotate/0.6.2/libexec/util/maker2evm.py /Users/username/Desktop/Genome/160608_finalmaker_noDNA_renamed.gff
2017-06-29 23:36:16,907: 9,907 total gene models from all sources
2017-06-29 23:36:16,953: Using existing EVM run data
2017-06-29 23:36:18,148: EVM did not run correctly, output file missing
```
Contributing to this not working was a file name (with a space) that I think was not well received (I should have known better)

However, this command which is nearly identical...
`funannotate-predict.py -i mysequence.fasta --maker_gff mysequence.gff -o test_output -s speciesname --cpus 2`

Gives this....
```
2017-06-29 20:24:14,377: OS: MacOSX 10.11.6, 4 cores, ~ 8 GB RAM. Python: 2.7.13
2017-06-29 20:24:14,539: Running funannotate v0.6.2
2017-06-29 20:24:17,441: AUGUSTUS (3.2.1) detected, version seems to be compatible with BRAKER1 and BUSCO
2017-06-29 20:24:17,721: Loading sequences and soft-masking genome
2017-06-29 20:24:17,721: Soft-masking: building RepeatModeler database
2017-06-29 20:24:18,891: Soft-masking: generating repeat library using RepeatModeler
2017-06-29 23:34:21,016: Soft-masking: running RepeatMasker with default library (RepeatModeler found 0 models)
2017-06-29 23:34:21,334: RepeatMasking failed, check log files.
```

It doesn't make sense to me...

**Comment by nextgenusfs** [comment]
Yes it runs repeatmasker, it needs that information to properly filter repetitive gene models.  I'm not sure what happened with your first run, did you have a previous run with the same output folder?  Funannotate will re-use any data that is in the output folder - this is so that if there is a mistake or you want to change something you don't have to re-run everything.  So if you had a soft masked genome file and an empty repeatmasker gff3 file in the output folder, it would assume it had run that already and skip that step.  When you ran the second run you specified a new output directory and thus it ran pipeline from the beginning.  

What is in the log file for repeat masking in the second run, if you post the error I can likely tell you what is wrong with the install.

**Comment by kramergj** [comment]
Thank you.  That answers my question about the EVM/repeatmasker difference.  So, I had a filename that repeatmasker didn't like and that seems to be why it failed in example 2.  I fixed that and I am currently re-running.  It hasn't returned any errors yet, but repeatmasker it is still "generating repeat library" after about 9 hours.  I can be patient if I need to be and just let it do it's thing... I've included the logfiles for this run, although perhaps they may not be helpful. 

[funannotate-predict.pdf](https://github.com/nextgenusfs/funannotate/files/1115421/funannotate-predict.pdf)
[funannotate-repeats.log.pdf](https://github.com/nextgenusfs/funannotate/files/1115422/funannotate-repeats.log.pdf)

**Comment by nextgenusfs** [comment]
RepeatModeler can be slow and you could use more CPUs (default is 2), but I see from the logs that you only have 4 on your computer, so it isn't going to run very quickly.  But 9 hours seems a bit long...usually should take 1-2 hours. If the log file isn't progressing, it maybe hung up on something.  Typically the entire predict step runs in < 12 hours on my laptop running with 6 cpus. Nearly all processes are multi-threaded in funannotate, so the more cpus you can give it the faster it will run.  I'm hoping to get a new version released very soon (maybe today) that will have the `--repeatmasker_species` option, this should speed up the run.  Although, once you manage to make a repeatmodeler library, you can pass that via the `--repeatmodeler_lib` option and it will proceed to RepeatMasking which doesn't take that much time.

**Comment by kramergj** [comment]
Thank you for the perspective and for the enormous amount of help!  Yes, I suppose I am able to run repeatmasker on the computer reasonably quickly, but I do specify a species with that. I'll look more into to the repeatmodeler library option and be patient!  Thank you!

**Comment by nextgenusfs** [comment]
I just pushed a new release, if you want to give it a try feel free. to update would be:
```
brew upgrade funannotate
```
Then need to resetup database links
```
funannotate setup -m all -d /path/to/funannotate/DB
```

**Comment by kramergj** [comment]
Great, will do!  So will this release allow me to do the `--repeatmodeler_lib`then?

**Comment by kramergj** [comment]
Sorry, I meant `--repeatmasker_species`

**Comment by nextgenusfs** [comment]
You can bypass repeatmodeler by passing `--repeatmasker_species fungi` for example, this will use the repeat masker pre-configured database for fungi.  If RepeatModeler finishes, the output of that is a fasta file containing a custom library of repeats, you could in the future pass that to the `--repeatmodeler_lib` option which would then mask the custom repeats it finds.

**Comment by kramergj** [comment]
Cool, I am currently trying the `--repeatmasker_species fungi` option with the updated funannotate.  Seems to be working well, so far! Thank you!

**Comment by nextgenusfs** [comment]
going to close this issue, but reopen if there are problems.
