### ISSUE TITLE
I tried to run Funannotate functional annotation in usegalaxy.org.au, program has got run successfully. However the files are not getting generated in history and its marked error with red colour.  

### ISSUE THREAD

**Issue by BharathBioinfo** [nextgenusfs/funannotate#945]
[Aug 02 09:55 PM]: OS: Ubuntu 20.04, 16 cores, ~ 66 GB RAM. Python: 3.8.15
[Aug 02 09:55 PM]: Running 1.8.15
[Aug 02 09:55 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Aug 02 09:55 PM]: Checking GenBank file for annotation
[Aug 02 09:57 PM]: Adding Functional Annotation to __lt__galaxy.tools.parameters.basic.ConnectedValue object at 0x7fd26c407ee0__gt__, NCBI accession: None
[Aug 02 09:57 PM]: Annotation consists of: 31,171 gene models
[Aug 02 09:57 PM]: 30,147 protein records loaded
[Aug 02 09:57 PM]: Running HMMer search of PFAM version 35.0
[Aug 02 10:37 PM]: 28,245 annotations added
[Aug 02 10:37 PM]: Running Diamond blastp search of UniProt DB version 2021_04
[Aug 02 10:46 PM]: 4,514 valid gene/product annotations from 6,809 total
[Aug 02 10:46 PM]: Existing Eggnog-mapper results found: output/annotate_misc/eggnog.emapper.annotations
[Aug 02 10:46 PM]: Parsing EggNog Annotations
[Aug 02 10:46 PM]: EggNog version parsed as 2.1.8
[Aug 02 10:46 PM]: 48,391  COG and EggNog annotations added
[Aug 02 10:46 PM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.74
[Aug 02 10:46 PM]: 5,301 gene name and product description annotations added
[Aug 02 10:46 PM]: Running Diamond blastp search of MEROPS version 12.0
[Aug 02 10:46 PM]: 788 annotations added
[Aug 02 10:46 PM]: Annotating CAZYmes using HMMer search of dbCAN version 10.0
[Aug 02 10:57 PM]: 1,039 annotations added
[Aug 02 10:57 PM]: Annotating proteins with BUSCO eukaryota models
[Aug 02 10:58 PM]: 340 annotations added
[Aug 02 10:58 PM]: Skipping phobius predictions, try funannotate remote -m phobius
[Aug 02 10:58 PM]: Skipping secretome: neither SignalP nor Phobius searches were run
[Aug 02 10:58 PM]: 0 secretome and 0 transmembane annotations added
[Aug 02 10:58 PM]: InterProScan error, output/annotate_misc/iprscan.xml is empty, or no XML file passed via --iprscan. Functional annotation will be lacking.
[Aug 02 10:58 PM]: Found 0 duplicated annotations, adding 89,405 valid annotations
[Aug 02 10:58 PM]: Converting to final Genbank format, good luck!
[Aug 02 11:05 PM]: Creating AGP file and corresponding contigs file
[Aug 02 11:06 PM]: Writing genome annotation table.
[Aug 02 11:07 PM]: Funannotate annotate has completed successfully!

        We need YOUR help to improve gene names/product descriptions:
           0 gene/products names MUST be fixed, see output/annotate_results/Gene2Products.must-fix.txt
           19 gene/product names need to be curated, see output/annotate_results/Gene2Products.need-curating.txt
           1,941 gene/product names passed but are not in Database, see output/annotate_results/Gene2Products.new-names-passed.txt

        Please consider contributing a PR at https://github.com/nextgenusfs/gene2product

mv: target 'out.tbl' is not a directory

**Comment by nextgenusfs** [comment]
duplicate #777
