### ISSUE TITLE
Funannotate annotate -e unrecognized

### ISSUE THREAD

**Issue by kramergj** [nextgenusfs/funannotate#95]
Hello,

I am working on adding functional annotation and am having difficulty.  I am trying to run a simple test case on my genome using the basic command-

`$ funannotate annotate -i outputfolderfrompredict -e youremail@domain.edu --cpus 4`

But I keep getting the error returned: 

```
usage: funannotate-functional.py [options] -i genome.fasta -g genome.gff -o test -e youremail@mail.edu
funannotate-functional.py: error: unrecognized arguments: -e youremail@domain.edu
```

I am not using a .edu email address (my university email address is .ca as I am in Canada) so I am not sure if that would be part of the issue here?

Thank you for any help you can give!

**Comment by nextgenusfs** [comment]
as of v0.7.0 `funannotate annotate` no longer takes email as an option.  Sorry I see that I did not update the help menu...

**Comment by nextgenusfs** [comment]
if you want to run any remote searches, i.e. phobius, antismash, or interproscan -> that command is now `funannotate remote`.

**Comment by kramergj** [comment]
No worries and thank you!  Removed the email and it seems to be working now.
