### ISSUE TITLE
braker installation error

### ISSUE THREAD

**Issue by jannafierst** [nextgenusfs/funannotate#96]
Hi,

I've been following the Mac OS installation but I get the following error when trying to install braker or funannotate 

jannafierst$ brew install funannotate
==> Installing funannotate from nextgenusfs/tap
==> Installing dependencies for nextgenusfs/tap/funannotate: braker
==> Installing nextgenusfs/tap/funannotate dependency: braker
==> Downloading http://bioinf.uni-greifswald.de/augustus/binaries/BRAKER1.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 9a941992535e8fe0c324ad9c4cc58fbf76e36400a5541d45ec7236618487cd04
Actual: cb2d9abe1720ed58753d362eee4af3791007efc617754804882d31f9fe2eab00
Archive: /Users/jannafierst/Library/Caches/Homebrew/braker-1.10.tar.gz
To retry an incomplete download, remove the file above.

I cleaned everything up and updated/upgraded but I can't seem to get past this error. I checked the http://bioinf.uni-greifswald.de/augustus/binaries/ site and it seems they upgraded braker from 1.10 to 1.11 on July 5 - could this cause the error? Thanks!

**Comment by nextgenusfs** [comment]
Yes, that is the issue.  I will update formula, give me a minute.

**Comment by nextgenusfs** [comment]
Can you try again now?  I had the link pointing to the most recent version, didn't know they would use the same name for a newer version.  It is explicit now to v1.11 - although this may break when/if they update again.... thanks for letting me know.

**Comment by jannafierst** [comment]
new error:

jannafierst$ brew install funannotate
==> Installing funannotate from nextgenusfs/tap
==> Installing dependencies for nextgenusfs/tap/funannotate: braker
==> Installing nextgenusfs/tap/funannotate dependency: braker
==> Downloading http://bioinf.uni-greifswald.de/augustus/binaries/BRAKER1_v1.11.tar.gz
######################################################################## 100.0%
Error: inreplace failed
braker.pl:
  expected replacement of "/usr/bin/perl" with "/usr/bin/env perl"

Thanks for looking at this!

**Comment by nextgenusfs** [comment]
Oh, they must have fixed this.... try it again now.

**Comment by jannafierst** [comment]
Works, thanks!
