### ISSUE TITLE
Problems with eggNOG parsing

### ISSUE THREAD

**Issue by simas232** [nextgenusfs/funannotate#97]
I ran _funannotate annotate_, but no annotation was included in _annotate_results_ folder. According to my investigation, this problem is caused by inappropriate eggNOG results parsing, so GAG is unable to generate tbl file with annotation data. When I look in annotations.eggnog.txt file, I see that there are several lines with 'note' column, which doesn't have anything in the following column. When I removed these lines, _funannotate annotate_ pipeline was able to complete everything correctly.

Could you check what is wrong with eggNOG results parsing? I used the online version of eggNOG mapper and then provided the results with --eggnog function. I am attaching eggNOG annotation file for the first 100 proteins and _annotations.eggnog.txt_ for the same 100 proteins. Thanks!

[eggnog_res.txt](https://github.com/nextgenusfs/funannotate/files/1140370/eggnog_res.txt)
[eggnog_parsed.txt](https://github.com/nextgenusfs/funannotate/files/1140371/eggnog_parsed.txt)

**Comment by nextgenusfs** [comment]
Hmm, what settings did you run with eggnog-mapper? Did you use diamond or HMM search?  I've not used the web server, just the local installation.  There are not the number of fields in your file as should be there, i.e. you seem to be have no eggnog descriptions in this file, according to [eggnog docs](https://github.com/jhcepas/eggnog-mapper/wiki/Results-Interpretation) that should be column 12 and COGs should be column 11.  The parser in funannotate is expecting there to be data in these fields.

**Comment by nextgenusfs** [comment]
925d4b85d140994390958fef110a603f48f3805e should clean up the parsing errors, however, I would run the eggnog mapper in HMM mode so that you can hopefully get the COG and descriptions as it will get more annotation for your proteins.

**Comment by simas232** [comment]
Well, I used diamond in the online eggNOG mapper. It seems that there is literally nothing in the last three column in eggnog-mapper output, when diamond is used. The last two columns (COG Cat. and eggNOG HMM Desc.) are always empty. The third one from the end (best OG) is always 'NA'. I did the corresponding run when using hmmer and I got the annotation data in these three columns.

I see that it is definitely better to run eggnog-mapper with hmmer, since it provides more annotation data. However, I noticed that hmmer selection becomes unavailable when providing more than 5000 sequences as input. To my knowledge, eggnog-mapper does hmmsearch for each protein separately anyway, so the overall eggnog-mapper performance shouldn't be worse, when dividing long queries (> 5000 proteins) into the smaller chunks. Although you are not involved in eggnog-mapper development, do you have any reflections about this? Are the results from eggnog-mapper with hmmer are sensitive from the chunk size?

**Comment by nextgenusfs** [comment]
I don't know about chunking your input and combining results, seems like it should work, but would be a question for the eggnog mapper repository.  They have packaged it up nicely and is straightforward to install on Mac or Linux if that is an option for you.

**Comment by simas232** [comment]
Okay, will try the local eggnog-mapper installation, thanks!

**Comment by nextgenusfs** [comment]
I think this is fixed, re-open if you still have problems.
