### ISSUE TITLE
Code fix: wrong path for evidence_modeler.pl in funannotate-runEVM.py

### ISSUE THREAD

**Issue by Bio-finder** [nextgenusfs/funannotate#972]
Hello, 
Just a short message for a quick fix in your script: funannotate-runEVM.py

`    cmd = [os.path.join(EVM, 'evidence_modeler.pl'),`   
should be
`    cmd = [os.path.join(EVM, 'EvmUtils', 'evidence_modeler.pl'),`

I hope this helps.
Best,

**Comment by hyphaltip** [comment]
what version of funannotate are you working from?
this code has worked for many releases so it may depend on what you set the EVMHOME variable to. 
we could probably detect if either path is installed that way.
Can you describe how EVM was installed - via conda or manually?

**Comment by nextgenusfs** [comment]
They changed the location of the script in version 2. Currently funannotate only supports EVM v1.1.1.

**Comment by Bio-finder** [comment]
Ok my bad then, I thought that funannotate was supporting the newest version of EVM. Sorry for the time lost. Just for your knowledge, after this fix, EVM 2.1 runs as it should.

**Comment by nextgenusfs** [comment]
Yeah I will try to find time to add the EVM version check and modify the command accordingly than it should support all versions.
