### ISSUE TITLE
augustus: ERROR         PP::Profile: Error parsing pattern file"/usr/local/venvs/funannotate/lib/python3.9/site-packages/funannotate/config/EOG092C0B3U.prfl", line 8.

### ISSUE THREAD

**Issue by dgslos** [nextgenusfs/funannotate#973]
I keep getting:
```
 augustus: ERROR
        PP::Profile: Error parsing pattern file"/usr/local/venvs/funannotate/lib/python3.9/site-packages/funannotate/config/EOG092C0B3U.prfl", line 8.
```
I tried installing it with sudo apt-get install augustus as suggested in #724, also tried to compile augustus 3.4 myself (got compilation errors).

I think this was solved in augustus 3.5, but this version doesn't seem to be supported by funnanotate. Can this be solved please?

Thanks in advance!

**Comment by nextgenusfs** [comment]
augustus v3.5 should be compatible with the latest release https://github.com/nextgenusfs/funannotate/releases/tag/v1.8.15 as well as the current master.

**Comment by dgslos** [comment]
Yes. I got if finally to work. I had a compilation mistake of Augustus and hence was missing some binaries. Now I can confirm it works! :)

**Comment by nextgenusfs** [comment]
Great, yes Augustus is a huge pain to install.....
