### ISSUE TITLE
Submission of two parts sqn files

### ISSUE THREAD

**Issue by hassantarabai** [nextgenusfs/funannotate#974]
Hello,

I noticed that Funannotate annotate output includes two sqn files (.part_1.sqn and .part_2.sqn) for the genome am annotating. Same for tbl output. Kindly, any advice how to progress in sqn files submission for NCBI as i would expected one sqn file output based on Funannotate manual. 

Thank you

**Comment by nextgenusfs** [comment]
This happens when you have a large genome if I recall correctly, something like `tbl2asn` can't process more than some number of contigs or genome size.  @hyphaltip have you ever had to submit a multiple? Can they just be concatenated?

**Comment by hyphaltip** [comment]
I always upload both files and it works fine at NCBI. Its split because of size of the number of contigs as jon says.

**Comment by hassantarabai** [comment]
Thank you for you feedback. I will close the issue.
