### ISSUE TITLE
Funannotate predict stuck at Augustus step

### ISSUE THREAD

**Issue by krostifangers** [nextgenusfs/funannotate#976]
Hello
I use funnanotate for my fungus gene prediction and annotation. I used funannotate test using the following command : 
funannotate test -t busco --cpus 16 and get the following result (see below) : 
Apparently, augustus_parallel.py cannot import Bio::SeqIO although Bio::SeqIO is available in the funannotate package. 
I should mention that I removed augustus from funannotate and I use the 3.4.0 version of Augustus installed on my computer.
Can you help me?
All the best
Christophe

funannotate test -t busco --cpus 16
#########################################################
Running `funannotate predict` BUSCO-mediated training unit testing
Downloading: https://osf.io/te2pf/download?version=1 Bytes: 1489808
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --cpus 16 --species Awesome busco
#########################################################
-------------------------------------------------------
[Oct 27 11:35 AM]: OS: Debian GNU/Linux 11, 16 cores, ~ 32 GB RAM. Python: 3.8.15
[Oct 27 11:35 AM]: Running funannotate v1.8.15
[Oct 27 11:35 AM]: Skipping CodingQuarry as no --rna_bam passed
[Oct 27 11:35 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  genemark     selftraining   
  glimmerhmm   busco          
  snap         busco          
[Oct 27 11:35 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Oct 27 11:35 AM]: Genome loaded: 6 scaffolds; 3,776,588 bp; 19.75% repeats masked
/home/krostif/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-p2g.py:14: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
[Oct 27 11:35 AM]: Mapping 1,065 proteins to genome using diamond and exonerate
[Oct 27 11:35 AM]: Found 1,505 preliminary alignments with diamond in 0:00:00 --> generated FASTA files for exonerate in 0:00:00
     Progress: 1505 complete, 0 failed, 0 remaining          
[Oct 27 11:35 AM]: Exonerate finished in 0:00:08: found 1,270 alignments
[Oct 27 11:35 AM]: Running GeneMark-ES on assembly
[Oct 27 11:36 AM]: 1,557 predictions from GeneMark
[Oct 27 11:36 AM]: Running BUSCO to find conserved gene models for training ab-initio predictors
[Oct 27 11:39 AM]: 370 valid BUSCO predictions found, validating protein sequences
[Oct 27 11:39 AM]: 367 BUSCO predictions validated
[Oct 27 11:39 AM]: Training Augustus using BUSCO gene models
[Oct 27 11:39 AM]: Augustus initial training results:
  Feature       Specificity   Sensitivity
  nucleotides   99.4%         83.8%      
  exons         63.2%         52.6%      
  genes         76.7%         51.4%      
[Oct 27 11:39 AM]: Running Augustus gene prediction using awesome_busco parameters
Traceback (most recent call last):
  File "/home/krostif/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/augustus_parallel.py", line 9, in <module>
    from Bio import SeqIO
ImportError: No module named Bio
[Oct 27 11:39 AM]: CMD ERROR: perl /home/krostif/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl annotate/predict_misc/augustus.gff3
[Oct 27 11:39 AM]: Error, cannot open file annotate/predict_misc/augustus.gff3 at /home/krostif/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl line 23.

#########################################################
Traceback (most recent call last):
  File "/home/krostif/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/krostif/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/krostif/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 407, in main
    runBuscoTest(args)
  File "/home/krostif/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 200, in runBuscoTest
    assert 1500 <= countGFFgenes(os.path.join(
  File "/home/krostif/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-busco_fc3b1897-7d4a-4ae0-8184-c8051e44bd13/annotate/predict_results/Awesome_busco.gff3'
  

**Logfiles**
Please provide relavent log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`

**Comment by hyphaltip** [comment]
Did you check the packages installed for sure. The error is because that biopython is not installed in the env that is running the parallel run. Is your Augustus just added to your path or installed in a separate conda env?

**Comment by hyphaltip** [comment]
Not seeing any followup so will close this, feel free to reopen if still need help.
