### ISSUE TITLE
TanTan with a repeatModeler consensus library

### ISSUE THREAD

**Issue by Malabady** [nextgenusfs/funannotate#986]
Hello,

Is the default masking method "Tantan" suitable when giving a RepeatModeler-created repeat library? 

Thanks,
Magdy

**Comment by Malabady** [comment]
That's what I ended up doing. Thanks, Umer.

**Comment by hyphaltip** [comment]
tantan is fast and does not have licensing restrictions for folks in industry but repeatmodeler + repeatmasker (or EDTA + repeatmasker) are going to be more sensitive tools for finding diverse TE families to mask.
