### ISSUE TITLE
with --maker_gff tries to run RepeatModeler?

### ISSUE THREAD

**Issue by xvazquezc** [nextgenusfs/funannotate#99]
Hi,
I'm trying to run `funannotate predict` with the gff output from Maker2, but I realised that Funannotate is trying to create a repeat model even though the repeats are already annotated in the Maker2 file.
Is that expected?
Thank you in advance,
Xabi

**Comment by nextgenusfs** [comment]
Yes, that is currently how it is setup.  I can look into parsing the repeats from Maker, although I added Maker support largely for convenience, I think that funannotate does a better job at predictions/training than Maker, at least on fungal genomes.

**Comment by nextgenusfs** [comment]
closing as issue is stale
